### ISSUE TITLE
AssetLocation relationship has incorrect type for end2

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#1004]
Raised on behalf of Tex who found an anomaly in the AssetLocation relationship type.

**Comment by mandy-chessell** [comment]
Good ole Tex ... :)

However what is wrong with it?
End 1 is Location
End 2 is Asset

**Comment by grahamwallis** [comment]
There was a problem in that both ends were Location; that problem has been fixed, (the PR has been merged) but the assembly packaging is not yet propagating the change. When the assembly packaging PR comes through this issue will be OK.

Closing this issue.
