### ISSUE TITLE
Do not run FVT tests by default

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1021]
* standard maven clean install should not run fvt tests (developers)
* pre-commit build needs not run fvt tests
* post-merge fvt tests do not need to run fvt
* daily build should run fvt tests

This will superceded options to disable the fvt tests at mvn cli

Will work with build team....
cc: @bogdan-sava @davidradl @mandy-chessell

**Comment by bogdan-sava** [comment]
Hi @planetf1,
Do you know who can change the jenkins jobs configurations

**Comment by planetf1** [comment]
Ok so the change has been made for the verify builds - now a lot faster with no FVTs. The default for developers was left to run the tests (safer, esp for newbies).

Changes to jenkins job configs start via emailing helpdesk@odpi.org . We do potentially have the option to change ourselves but I'm still getting more clarification on how we can change ourselves - the files are known, but we need to know dependencies, impact too.

Since the fvt test change is made now I will close this issue
