### ISSUE TITLE
Optimise ranger image

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1038]
Can probably free up ~3GB of image space by optimising `ranger-egeriavdc` to a minimal alpine image.

**Comment by cmgrote** [comment]
As part of the optimisation I'm planning to move from mariadb to postgresql as the back-end (to re-use the minimal ~70MB image we already use for sample data rather than the ~300MB image for mariadb)...

**Comment by planetf1** [comment]
There's quite a few improvements possible in the ranger image for sure:
 - Avoiding building (maven artifacts or elsewhere)
 - making it easier to add new plugins (ie for gaian)
 - separating out the database entirely (maybe a seperate container)
 - separating out the solr index entirely
 

The image hasn't changed much in about 1.5 years, so we know a lot more know to make it easier to do this.

**Comment by cmgrote** [comment]
Will be mostly addressed by #1043 -- suggest separate issues for any further optimisations.
