### ISSUE TITLE
Separate solr into its own image and re-use

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1041]
Both the Apache Ranger and Apache Atlas images need to make use of Solr (the latter requires v5.5, and the former also supports that as a minimal version).  Would therefore be good to separate out Apache Solr into its own container and service, and have both the Apache Atlas and Apache Ranger containers (pods) make use of the separate Apache Solr service.

**Comment by cmgrote** [comment]
When I looked at this a bit more closely it looked like it could be a lot of work to separate things out in the containers (as Solr collections must be initialized / created before pointing Atlas / Ranger at it), creating sequencing challenges, version challenges (ensuring the right Solr objects are created depending on the precise Atlas / Ranger version), etc -- combined with the likelihood that the savings here are probably fairly minimal (~100 MB memory, < 1GB image footprint) I'd suggest putting this as a fairly low priority...  Might be more effort than it's worth 🤷‍♂

**Comment by planetf1** [comment]
I'd suggest we just close if we don't think we'll do it... There's a lot that could be improved with ranger, but we'll likely only tackle it when we want a real focus on building some scenarios - and even then this is probably low down in the list.
