### ISSUE TITLE
Add consistent metadata for docker images produced by egeria

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1048]
Egeria's docker images initially tended to carry additional metadata in the form of 
```
# Image metadata following http://label-schema.org/rc1/
LABEL org.label-schema.name = "RangerAdminForEgeriaVDC"
LABEL org.label-schema.description="Apache Ranger Admin service to support Egeria VDC demos"
LABEL org.label-schema.url="https://github.com/odpi/egeria/"
LABEL org.label-schema.vcs="https://github.com/odpi/egeria/tree/master/open-metadata-resources/open-metadata-deployment/docker/ranger-admin"
LABEL org.label-schema.version="0.2.0"
LABEL org.label-schema.schema-version = "1.0"
```
(This example was from ranger)

Over a few changes metadata has been dropped from some images, but it's a good opportunity to review what is actually useful.

http://label-schema.org/ proposes some standards upon which these were based - but egeria images were very early on in the dev cycle

Some thoughts
 - build-date helps consumers understand when a docker image was built
 - urls and description are good for general info
 - vcs references are useful, though it can sometimes be tricky to determine which vcs revision to use. The build process for the docker image can contribute a version easily, but since many images work by downloading git assets, that may be a better version, yet tricky

etc...
Raising in ref to https://github.com/odpi/egeria/pull/1043#issuecomment-492979761

**Comment by cmgrote** [comment]
> build-date helps consumers understand when a docker image was built

I'm not convinced...  Docker already tracks this independently of the labels (ie. you can see the age of an image on Docker Hub, locally via `docker images`, etc), and even the MicroBadger site gives the creation date irrespective of whether it was in a `LABEL` in the image or not.  I'm thinking it might be more trouble to try to work out injecting this label consistently as part of an automated build, and then leaving people to wonder whether this label or the other dates from Docker itself are correct, creates more trouble / confusion than it's worth (?)

**Comment by planetf1** [comment]
The label-schema.org proposal has now been superceeded by the OCI container spec
https://github.com/opencontainers/image-spec

Suggest going with the commit above go retrofit/improve the original labels, then leave this to understand the OCI spec better... there are other related aspects here such as docker alternatives & build pipelines

**Comment by cmgrote** [comment]
Are you sure these are equivalent?  OCI image spec looks much more like the technical description of the contents of the image itself -- eg. akin to what you see when you do a `docker image inspect <image>` and get an output of its filesystem layers, etc.  (Which is all built for you automatically as part of the `docker build ...` process...)  I'd put the responsibility on the build process to automatically construct such detail, ie. if possible on docker itself to conform to the OCI image spec standard (?)

**Comment by planetf1** [comment]
I should have been more specific
https://github.com/opencontainers/image-spec/blob/master/annotations.md

And yess... there is investigation needed, hence the suggestion we keep this open until we investigate more fully.
