### ISSUE TITLE
Egeria atlas customized build failing (VoidResponse)

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1067]
The apache atlas docker build within egeria is currently failing when building open-metadata-resources/open-metadata-deployment/docker/atlas

This step builds atlas within a docker image, which itself is failing due to :
```
[INFO] [ERROR] COMPILATION ERROR :
[INFO] [INFO] -------------------------------------------------------------
[INFO] [ERROR] /root/atlas/open-metadata/src/main/java/org/apache/atlas/openmetadata/admin/server/spring/OpenMetadataAdminRes
[INFO] ource.java:[27,48] cannot find symbol
[INFO]   symbol:   class VoidResponse
[INFO]   location: package org.odpi.openmetadata.adminservices.rest
[INFO] [ERROR] /root/atlas/open-metadata/src/main/java/org/apache/atlas/openmetadata/admin/server/spring/OpenMetadataAdminResource.java:[107,12] cannot find symbol
[INFO]   symbol:   class VoidResponse
[INFO]   location: class org.apache.atlas.openmetadata.admin.server.spring.OpenMetadataAdminResource
[INFO] [ERROR] /root/atlas/open-metadata/src/main/java/org/apache/atlas/openmetadata/admin/server/spring/OpenMetadataAdminRes
[INFO] ource.java:[127,12] cannot find symbol
[INFO]   symbol:   class VoidResponse
[INFO]   location: class org.apache.atlas.openmetadata.admin.server.spring.OpenMetadataAdminResource
```
etc

I can see in the fork https://github.com/grahamwallis/atlas

`./open-metadata/src/main/java/org/apache/atlas/openmetadata/admin/server/spring/OpenMetadataAdminResource.java`

with the failure being caused by
`import org.odpi.openmetadata.adminservices.rest.VoidResponse;`

The reason is that this has changed to `org.odpi.openmetadata.commonservices.ffdc.rest.VoidResponse`
in db936925976cc5fa8bc369beed8b38c04d9fa0de @mandy-chessell 13 May & merged to master in https://github.com/odpi/egeria/pull/1035

The result is that atlas can no longer be built. Although it hasn't changed, the automated docker build process fails, resulting in other images not building either.

I can either
 a) Create a patch I can apply within the docker build itself
 b) Create a PR against your repo @grahamwallis for you to merge (better) 0 if so we can merge the prior 2 patches
 c) you can make the change
 d) We could remove atlas from the build, but I think we should keep our 'best so far' building from source.

cc: @schannamallu 

Originally reported at https://github.com/odpi/ci-management/issues/85

**Comment by mandy-chessell** [comment]
If we make a change it should be to move the Atlas build to Egeria 1.0.

**Comment by planetf1** [comment]
* Currently Atlas is being used in demos for visualization pending availability of egeria UIs
* Atlas integration is moving from the current embedded connector (effectively deprecated) to proxy pattern for better function , easier install, better compatability & maintainability (similar to IGC)
* Will make tactical change here to restore the build
* Will switch atlas container to not be deployed by default
* Will add comments in config that the current Atlas integration is deprecated
* Will open separate issue to track removal of atlas a) for demo/vis (needs UI) and b) to be replaced by better connector

**Comment by eostic** [comment]
Nigel...this is great news!   Using the proxy pattern for Atlas will make things vastly simpler to understand and implement and also makes it conceptually similar to the existing OMAG implementation we are working with for IGC....  Thank you!

**Comment by planetf1** [comment]
Added further patches to
 * Fix issue with VoidResponse & SuccessResponse 
 * Allow connection types to be tolerated
 * upgrade kafka (to consolidate with same version used by other testers)

**Comment by planetf1** [comment]
building full docker images & testing

**Comment by planetf1** [comment]
Test failed with
```
2019-05-24 14:09:24,911 ERROR - [pool-1-thread-8 - fa331acc-963a-4ba6-be9c-f942aca11f94:] ~ myserver OCF-METADATA-MANAGEMENT-0005 The Open Connector Framework (OCF) Metadata Management Service is unable to initialize a new instance; error message is OMAG-PLATFORM-404-004 The open metadata repository services are not initialized for the new ServiceInstance operation (OMRSAuditLogDestination:94)
```

**Comment by planetf1** [comment]
Issue found during testing appears to be a base OMRS issue.
Submitting these changes....
