### ISSUE TITLE
open-metadata initialization in vdc helm chart : set-server-root needs to be 1st

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1081]
When reviewing the initialization of egeria's customized atlas repo, we observed server-url-root was being called after configuring the event bus. It needs to be called first so that the correct default is set for all subsequent REST API calls

**Comment by cmgrote** [comment]
Strange that the ordering is so important for this connector suddenly, as it was working previously without that being the first config method called?  Also seemed to work fine for all the other repository connectors...

Nonetheless, have gone ahead and committed this re-ordering for all of the repository connector initialisations as part of #1071

**Comment by planetf1** [comment]
Ah you beat me to it.. thx
