### ISSUE TITLE
Amend DataField to capture default values

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#1092]
Amend DataField to caption default values so we can store the default values from Avro fields

**Comment by mandy-chessell** [comment]
![0615-Schema-Extraction](https://user-images.githubusercontent.com/12354195/68222081-58432d00-ffe2-11e9-9c72-e91d23db7791.png)

**Comment by mandy-chessell** [comment]
Above is the new definition for `DataField` with the `defaultValue` field.
