### ISSUE TITLE
Amend DataField and schemaAttribute to store alias (used with  Avro fields)

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#1093]

**Comment by mandy-chessell** [comment]
Another cryptic feature.  Looking at the Avro spec, there is a possiblity of adding a list of aliases for a data field.  See https://avro.apache.org/docs/current/api/java/org/apache/avro/Schema.Field.html#aliases--

This is the Data Field extension

![0615-Schema-Extraction](https://user-images.githubusercontent.com/12354195/69068162-356e3b00-0a1c-11ea-9d9a-fabcfd15fb78.png)

**Comment by mandy-chessell** [comment]
This is the equivalent update for the schema attribute.

![0505-Schema-Attributes](https://user-images.githubusercontent.com/12354195/69068896-7ca8fb80-0a1d-11ea-9e0c-4cf925d8f5b1.png)
