### ISSUE TITLE
Amend DataField to capture doc so we can capture docs from Avro fields

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#1094]

**Comment by mandy-chessell** [comment]
I think this is asking to add a new string instance properties to the data field to describe any documentation associated with a data field.  For Apache Avro, this would be set to the value from the `doc()` method.

https://avro.apache.org/docs/current/api/java/org/apache/avro/Schema.Field.html#doc--

See new dataTypeDescription ...

![0615-Schema-Extraction](https://user-images.githubusercontent.com/12354195/69065587-ec1bec80-0a17-11ea-9fdb-57597b92a372.png)
