### ISSUE TITLE
Add sorting order to DataField and SchemaAttribute

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#1096]
Avro Fields have Schema.Field.Order which is  how values of this field should be ordered when sorting records. This value needs to be stored in the DataField and SchemaAttribute

**Comment by mandy-chessell** [comment]
The Avro schema's Enum is defined here: https://avro.apache.org/docs/current/api/java/org/apache/avro/Schema.Field.Order.html

It includes 3 values:
* ASCENDING
* DESCENDING
* IGNORE

This is the new Enum called DataItemSortOrder and its use in SchemaAttribute:

![0505-Schema-Attributes](https://user-images.githubusercontent.com/12354195/69073284-03150b80-0a25-11ea-85f7-b82773583acc.png)

And the new property in DataField

![0615-Schema-Extraction](https://user-images.githubusercontent.com/12354195/69073652-b4b43c80-0a25-11ea-8f15-d29d62003214.png)
