### ISSUE TITLE
Clarify intended behaviour of findEntitiesByClassification

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1103]
The JavaDoc for the `findEntitiesByClassification` method of `OMRSMetadataCollectionBase` currently states:

- `@param matchClassificationProperties Optional list of entity properties to match (contains wildcards).`
- `@param matchCriteria Enum defining how the match properties should be matched to the classifications in the repository.`

I suspect the first bullet is a copy / paste mistake, and that it should be "Optional list of _classification_ properties to match (contains wildcards)."?  Mainly because I believe `findEntitiesByProperty` would otherwise already allow you to do everything this method is attempting...

But this one I'm less sure about:

- `@param sequencingProperty String name of the entity property that is to be used to sequence the results.`

Do we still want to sequence / order results by _entity_ properties, or by _classification_ properties?  (For now I'm assuming it's correct as-is: that we'd still do the sorting by _entity_ properties, though the matching itself may be based on _classification_ properties.)

**Comment by mandy-chessell** [comment]
These are both typos - they should be classification properties

**Comment by cmgrote** [comment]
Shall I make an update to the JavaDoc comments and submit, or are you already mid-work on other changes in that base class?

**Comment by cmgrote** [comment]
Sorry, one other follow-up: what about `sequencingOrder`?  I assume as long as it isn't `...PROPERTY...` based it should still be the entity information that is used for sorting (ie. entity `GUID`, entity create / update times, etc).  (Sorting by classification `GUID` wouldn't make sense given that the search results would all have the same classification?)

**Comment by mandy-chessell** [comment]
The intent was sequencing on the classification properties - rather than the entity properties.  for example - if searching on the new AssetOrigin classification, there are properties for organizationGUID, businessCapabilityGUID and other identifiers - say the search was for a specific org GUID, by sequencing on businessCapabilityGUID, it would group all of the entities belonging to a specific capability together - even though the ordering by GUID itself is arbitrary.

**Comment by cmgrote** [comment]
Right, that makes sense, but I think these would all fit under the `PROPERTY_ASCENDING` or `PROPERTY_DESCENDING` enums of the SequencingOrder...

To be more explicit:

- `GUID`: I would assume still means sorting based on the GUIDs of the _entities_ that are returned
- `CREATION_DATE_RECENT`: based on the creation date of the _entities_
- `CREATION_DATE_OLDEST`: same
- `LAST_UPDATE_RECENT`: based on the update time of the _entities_
- `LAST_UPDATE_OLDEST`: same
- `PROPERTY_ASCENDING`: based on the property (like `businessCapabilityGUID`) of the _classification_
- `PROPERTY_DESCENDING`: based on the property of the _classification_

Does that make sense?

**Comment by mandy-chessell** [comment]
I am not sure I agree with this - I think the problem is that the SequencingOrder has more values than makes sense for a classification.  We either need to clarify that the properties that are not part of a classification are not supported on this call or create another emum.

From a backward compatibility perspective I expect we will have to add documentation to the current method and deprecate it.  Then add a new method with the new enum in it.

**Comment by cmgrote** [comment]
I think it's worth considering both approaches: ultimately the method is returning a list of entities, so it might still be desirable to have the option to sort that list of entities by something entity-specific, even while the list itself has been narrowed based on some value of a classification property...

For example, a user might want only terms classified as `ContextDefinition` with a `ContextDefinition::scope` of "local", but to still sort that list of results by the date of the entity's creation (?)

**Comment by planetf1** [comment]
The method is find<FOO>by<BAR>
The 'by' indicates selection. So the filter should relate to properties of BAR
but the returns are always FOOs, and I see sequencing as related to that result set

In this case
 * FOO is Entity - so we should sequence by properties of entities
 * BAR is Classification - so we should filter/select/search by properties of classification

I think this pattern is generally applicable?

**Comment by mandy-chessell** [comment]
I have been looking at this in more detail and I am coming to the conclusion that the matching of properties should be on the classification properties but the sequencing of results should be based on the entity's properties.

**Comment by cmgrote** [comment]
Agreed on functionality call 2019-07-02:

- Search (and limit results) based on classification properties
- Sort results based on entity properties
