### ISSUE TITLE
Swagger doc not working/unreliable

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1121]
After deploying the current egeria helm chart (with a current docker image built automatically) to the cloud, it's noted that the swagger doc at

http://HOST:port/swagger-ui.html

Seems to fail to load. The initial page loads, but the actual api doc content does not.

Reported by another user on windows also, though a master build from last week when ran locally on macos did result in working swagger

Investigating ...

**Comment by planetf1** [comment]
Latest git sha on egeria in cloud is 227f8525e7818e3bb6680cf588d832002488b7ed (yesterday)

**Comment by mandy-chessell** [comment]
I wonder if we have too many REST operations?

**Comment by planetf1** [comment]
Upping the version seems to fix it (tested on 2 environments).
I couldn't locate the specific error.

I've looked at Javadoc but a) we need to get base javadoc reliably working in the build first then b) we might be able to use the springdox doclet to inject the javadoc.. though it's made more tricky by the multi module project which is't (and why should it be) aligned with the spring component injection. I'll open a new issue to track that & some other issues with the swagger

**Comment by mandy-chessell** [comment]
Thanks for fixing
