### ISSUE TITLE
Egeria UI only works on localhost

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1129]
The Egeria UI is not working correctly in a helm deployment

https://server:port/

fails to render anything interesting - though a page is loaded, and the title is 'Egeria UI'. Source can be viewed. No ad blockers are in Use. Chrome on MacOS as browser. Safari fails too.

2 resource errors reported in developer tools:
```
Uncaught SyntaxError: The requested module '../vaadin-usage-statistics/vaadin-usage-statistics.js' does not provide an export named 'usageStatistics'
(index):1 Uncaught (in promise) TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.
```
/src/my-app.js is being retrieved ok

We should ensure the existing UIs (asset search, subject area) work correctly.

@bogdan-sava @davidradl @grahamwallis please advise if any additional configuration is needed for the GUI to function

Currently only `open-metadata-implementation/user-interfaces/access-services-user-interface/target/access-services-user-interface-*.jar` is copied into the egeria docker image & launched as a standalone springboot application

Previously this was referring to an assembly, but these assemblies were broken a month or two back.

Any fix should ultimately ensure we restore the assemblies - ensure they work as is, and switch the docker build to make use of the correct assembly.

**Comment by planetf1** [comment]
Note that currently the deployment sets only 2 values
```
 OMAS_SERVER_URL
 OMAS_SERVER_NAME
```
which are correctly set

**Comment by planetf1** [comment]
Retested with latest build. Still not working.

**Comment by planetf1** [comment]
This is still occuring - the UI is entirely blank in both chrome and safari (no ad blocker)
No errors are seen from server chassis or UI server even with debug enabled

**Comment by planetf1** [comment]
This is still occuring
cc: @davidradl @grahamwallis @bogdan-sava 

Any idea?

What I see in the UI is
 - Once past the self-signed cert id, the UI loads , and the 'favicon' appears
 - The main pane is completely blank

In the browser debugging I am seeing errors loading the resources (host:port is replaced here)
 https://host:port/node_modules/vis/dist/vis-network.min.js
 https://host:port/service-worker.js

Probably not the main issue
So unable to get to tex or any other UI....

Will investigate further ....

**Comment by davidradl** [comment]
@planetf1 I think polymer.json 

"sources": [
    "images/**/*",
    "locales/**/*",
    "properties/**/*",
    "index.html",
    "src/my-app.js"
  ],

 means that those files will be obtained using http. I suspect that your config is trying to get these resources using https, which it will not like. I added the "properties/**/*", line to ensure the contents of properties folder was obtained using http. Is there a way in your docker image to ensure that when accessing the resources identified above http is used (as they are in my local system) or is that not feasible here?

@grahamwallis @bogdan-sava

**Comment by planetf1** [comment]
When the UI is deployed standalone, I only run the user interface jar ie `java -jar ./open-metadata-distribution/open-metadata-assemblies/target/egeria-1.1-SNAPSHOT-distribution/egeria-omag-1.1-SNAPSHOT/user-interface/access-services-user-interface-1.1-SNAPSHOT.jar` - this only results in the app listening (by default) on port 8443 & only on https. I don't see a difference in that regard between localhost & some remote/container image

To clarify more exactly.

On localhost & safari (ie running jar at cli) I get errors from:
```
[Error] Failed to load resource: the server responded with a status of 404 () (vis-network.min.js, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (en.json, line 0)
[Error] Unhandled Promise Rejection: TypeError: l.LegacyGlobal.should_do_lastpass_here is not a function. (In 'l.LegacyGlobal.should_do_lastpass_here(document)', 'l.LegacyGlobal.should_do_lastpass_here' is undefined)
	l (content-script.js:75:837159)
	s (content-script.js:75:835984)
	promiseReactionJob
[Error] Failed to load resource: the server responded with a status of 404 () (web-animations-next-lite.min.js.map, line 0)
```
Though the UI does at least render correctly.

When accessing the k8s deployed image (or docker-compose) I get:
```
[Error] Failed to load resource: the server responded with a status of 404 () (vis-network.min.js, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (web-animations-next-lite.min.js.map, line 0)
[Error] SyntaxError: Importing binding name 'usageStatistics' is not found.
	link
	linkAndEvaluateModule
	(anonymous function)
	promiseReactionJob
[Error] Unhandled Promise Rejection: TypeError: l.LegacyGlobal.should_do_lastpass_here is not a function. (In 'l.LegacyGlobal.should_do_lastpass_here(document)', 'l.LegacyGlobal.should_do_lastpass_here' is undefined)
	l (content-script.js:75:837159)
	s (content-script.js:75:835984)
	promiseReactionJob
[Error] Failed to load resource: the server responded with a status of 404 () (service-worker.js, line 0)
[Error] Unhandled Promise Rejection: TypeError: Script https://egeriadev.eu-gb.containers.appdomain.cloud:30443/service-worker.js load failed
	(anonymous function)
	rejectPromise
```
Here the UI does not render beyond the favicon

**Comment by planetf1** [comment]
I wonder if the error could relate to https://github.com/odpi/egeria/issues/1153

I note in the docs for https://github.com/vaadin/vaadin-development-mode-detector that this code behaves differently for localhost vs !localhost

Have you been able to run correctly remotely other than localhost?

**Comment by planetf1** [comment]
I tried connecting to my macos running UI (which worked locally) remotely - and.. the UI did come up ok... Hmm

**Comment by davidradl** [comment]
@planetf1 I have looked at the trace in developer mode, it is all going up over https - sorry for misleading you. I think the token might be a red herring. 404 means that tomcat is not serving the path. I suspect that the the Tomcat config is not resolving resources in the jar. 

I see https://stackoverflow.com/questions/16957874/tomcat-not-serving-static-files. This indicates we should be specifying mappings in the  web.xml.

I notice "The two most important configuration files to get Tomcat up and running are called server.xml and web.xml. By default, these files are located at TOMCAT-HOME/conf/server.xml and TOMCAT-HOME/conf/web.xml, respectively." 

 I assume we want different web.xml and server.xml files for the backend Tomcat and for the UI Tomcat. The UI Tomcat needs to server static resources which the backend does not. I assume these files are deployment files the user would be expected to taylor for their deployment. I am not sure where in git we should supply sample deployment file examples, once we work out what should be in them.   

@grahamwallis @bogdan-sava

**Comment by planetf1** [comment]
I was also able to run the UI on a linux host and connect remotely. So it may be there is something different about the container or jvm environment that is causing errant behaviour

**Comment by planetf1** [comment]
As far as the tomcat setup goes --- this is setup automatically by spring boot as far as I know.

**Comment by planetf1** [comment]
Current firefox errors

Local
```
asset-search my-app.js:298:13
token changed from: undefined 
to new value: null my-app.js:290:13
Service worker event waitUntil() was passed a promise that rejected with 'Error: Request for https://localhost:8443/index.html?_sw-precache=0363d54ce2b99931a53cffff6f6cb539 returned a response with status 403'.
```
Remote
```
SyntaxError: import not found: usageStatistics vaadin-element-mixin.js:4:9
Failed to register/update a ServiceWorker for scope ‘https://localhost:18443/’: Load failed with status 404 for script ‘https://localhost:18443/service-worker.js’.
TypeError: ServiceWorker script at https://localhost:18443/service-worker.js for scope https://localhost:18443/ encountered an error during installation.
Source map error: request failed with status 404
Resource URL: https://localhost:18443/node_modules/web-animations-js/web-animations-next-lite.min.js
Source Map URL: web-animations-next-lite.min.js.map
```
​

**Comment by planetf1** [comment]
Looking through vaadin docs, it seems we need to ensure production mode is enabled.
Most build examples refer to use of the vaadin maven plugin, but also it appears vaadin flow is yet to work ootb with polymer 3 as per https://github.com/vaadin/flow/issues/4561

**Comment by planetf1** [comment]
Rebuilt with
```
   "vaadin": { "disableUsageStatistics": true }
```
In package.json & recreated image.

However UI still not functioning Still investigating build process and differences.

**Comment by planetf1** [comment]
Some further analysis

From the container build we have:
```
./src/main/static/build/dev/node_modules/@vaadin/vaadin-usage-statistics/vaadin-usage-statistics.js
./src/main/static/build/dev/node_modules/@vaadin/vaadin-usage-statistics/vaadin-usage-statistics-collect.js
```

whilst in the regular/local build
```
./src/main/static/node_modules/@vaadin/vaadin-usage-statistics/vaadin-usage-statistics-optout.js
./src/main/static/node_modules/@vaadin/vaadin-usage-statistics/vaadin-usage-statistics.js
```

These files get renamed as part of the build process.
It *appears* that in the polymer build process, the vaadin scripts that rename these files are not being executed. This is despite bash being installed. 

See
```
npm not on pathhttps://github.com/vaadin/vaadin-usage-statistics/pull/43/files
Reported in 
https://github.com/vaadin/vaadin-usage-statistics/pull/43
new impleme ntationhttps://github.com/vaadin/vaadin-usage-statistics/pull/43/files
```
Recent attempts to fix
 - refactored pom.xml to use maven antrun plugin to build polymer. Rationale -- we can inject the PATH into the environment so that the downloaded 'node' command is in the path. This is needed as the vaadin scripts call node directly. The thought was this was failing. However testing has not shown this attempted fix to work so far......

An alternative :
 - stop rebuilding egeria as part of the docker build
 - consume maven artifacts (based on assemblies, which also need correcting)
Benefits
 - consistent build artifacts being used
 - usable as part of a broader dev-ops pipeline to push egeria build artifacts into k8s for automated testing

See <issue tbd>

**Comment by planetf1** [comment]
This appears now to be working. 

I note that the vaadin code import has changed to
'export * from './vaadin-usage-statistics-collect.js';'
which is now syntactically correct - and thus allows the page to work

So we still see a difference between a build made in the container, and a build machine build, but the vaadin code is now handling both cases.

There was an issue (above) raised against vaadin (not by me) and planned to be fixed so I can only assume this has been incorporated and picked up (though it's possible another change has been made)

I will raise a new issue if/when a change to the egeria build process is needed for other reasons (speed, consistency) but closing this as the UI is now 'working' (given the ongoing work of course)
