### ISSUE TITLE
github egeria repo has some unnecessary branches - cleanup

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1137]
I noticed we have some branches in egeria that reflect individual work that should be deleted since pull requests should be used for all changes

 cmgrote-dco @cmgrote 
 egeria_contributor_proposal_20190517 @jmertic 
 jmertic-patch-1 @jmertic 

Also I'm unsure what 'maintenance' is ?

@mchessell ? I think it would help to keep things as clean/obvious as possible for new contributors

**Comment by cmgrote** [comment]
Feel free to delete any branch that looks like mine — would have been an accident in the first place on my part
