### ISSUE TITLE
Changes to OMRS MetadataCollection interface

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#1151]
This issue is to capture a couple of upcoming changes:

1. When an Entity is deleted, any Relationships it is participating in are also deleted. This is currently implemented in each of the connector implementations; this has the drawback that no events are generated for the relationship deletions for a connector that relies on the Local Connector for its event mapper. To ensure the events are generated, this function (of checking for existence of relationships associated with the entity, and deletion of those relationships prior to deleting the entity) should be moved up to the Local Connector. The OMRS Repository Connector's implementation of deleteEntity() should instead check for existence of relationships associated with the entity and throw an exception of any relationships exist - they should have already been removed by the Local; Connector.

1. If a repository connector implementation current implements refresh methods for reference copies of entities and relationships - e.g. by overriding the base class implementation by reporting METHOD_NOT_IMPLEMENTED; this should be changed to rely instead on the base class - which is being augmented to handle refresh differently.

These points should both be fixed as part of a PR that will implement the changes to the Local Connector, OMRSMetadataCollectionBase class and the existing repository connectors.

@cmgrote - heads-up re: the IGC connector.
@mandy-chessell - heads-up re: using this issue to track the changes we discussed
@CDaRip2U - heads-up re: possible change needed to SAS connector?

**Comment by mandy-chessell** [comment]
A possible approach to fixing this could be done in the local repository connector that wraps the real repository.  It could call getRelationshipsForEntity on the real repository just before calling delete.  Once the delete is successful, it could send out the delete messages for all relationships that have their home in the local repository (and external relationships that thave replicated by set to the local repository.  This would mean that we would guarantee that the delete messages were sent out.  The worst that could happen is that two delete messages are sent out, one by the real repository and one by the local repository.

**Comment by cmgrote** [comment]
Sounds like this would also remove the need for each repo connector to handle the same logic itself?  Sounds good to me — only other “risk” that comes to mind is that some repositories may have a more optimal means of cascading this themselves: but that could be easily mitigated if we have a flag in the local repo config that would control whether to do the cascade or pass through without cascade (defaulting to the former) (?)

**Comment by cmgrote** [comment]
From our discussion, my plan was to handle this directly in the appropriate connector — in particular so I can remove sub-entities and not just relationships when the entity deleted is a parent / composed entity (eg. deleting a table will delete all columns in the table).  Issue for IGC is https://github.com/odpi/egeria-connector-ibm-information-server/issues/95

**Comment by mandy-chessell** [comment]
This is good - the IGC connector has additional knowledge of the structure of metadata because it has an object model behind it (first time this is an advantage :).

If the local connector also sends out delete events for the relationship then we could get duplicate events which is as undesirable as none.

For the case where the local repository connector is in charge of all events because the real repository connector does not have an event mapper then the local repository connector should send the delete events.

If the real repository connector has an event mapper then we have to leave this responsibility with the real repository connector.  This means we must test that the real repository connector sends these events in the conformance suite.

fyi @CDaRip2U

**Comment by grahamwallis** [comment]
It's not clear to me whether there is still anything required for this issue.
The in-mem and graph repository connectors use the local connector and are relying on it for the event generation. It sounds like the IGC (and Atlas??) connectors implementing this in their own event mappers.

Is that correct?
Is there anything missing or can this issue be closed?
