### ISSUE TITLE
UI sends usage statistics - possible production concern

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1153]
The Egeria UI currently throws an error that can be seen in 'developer tools' '(index):1 Uncaught SyntaxError: The requested module '../vaadin-usage-statistics/vaadin-usage-statistics.js' does not provide an export named 'usageStatistics'' 

I noticed that the vaadin components perform useage tracking, and our UI is including https://host:port/node_modules/@vaadin/vaadin-usage-statistics/vaadin-usage-statistics-collect.js

The components themselves look ok being Apache 2.0, but the stats gathering is disconcerting. Even the vaadin site suggests that during production useage the stats are disabled - and the .js replaced with empty bodies. We at least need to ensure this happens when we deploy. The docs at https://github.com/vaadin/vaadin-usage-statistics also cover how to disable the stats gathering

It's crucial we are transparent and need to take the utmost care with any form of data gathering

Note - I cannot confirm 100% data is being captured, but this needs to be verified

  This was found when debugging #1129 
cc: @bogdan-sava @davidradl

**Comment by planetf1** [comment]
Note during the build this appears
```
19:26:05 [INFO]     Vaadin collects development time usage statistics to improve this product. To opt-out, either run:
19:26:05 [INFO]     npm explore @vaadin/vaadin-usage-statistics -- npm run disable
19:26:05 [INFO]     to store disable statistics for the machine, or add
19:26:05 [INFO]     "vaadin": { "disableUsageStatistics": true }
19:26:05 [INFO]     to the project package.json and re-run npm install to disable statistics for the project.
19:26:05 [INFO] 
19:26:05 [INFO]     For more details, see https://github.com/vaadin/vaadin-usage-statistics
19:26:05 [INFO]   
```

**Comment by planetf1** [comment]
This should be done before next release/any production useage IMO cc: @mstrelchuk

**Comment by planetf1** [comment]
This is still being reported and could be a concern for any production use case. I would suggest they are disabled

**Comment by bogdan-sava** [comment]
still need to be investigate

**Comment by planetf1** [comment]
@sarbull @bogdan-sava  Is this addressed now? If so can be closed

**Comment by sarbull** [comment]
yes, i saw it some days ago, it can be disabled by a `package.json` property.. `"vaadin": { "disableUsageStatistics": true }`

**Comment by sarbull** [comment]
@planetf1 this is because vaadin has an open-source components version and also paid components version, enhanced, updated, whatever, i think those statistics are for gathering components data on what people use and how, it's quite dangerous. 

this is what they state they collect:
```
Collected data
- Vaadin products used in the application, including version numbers
- Frameworks used in the application, including version numbers
- Flow features used in the application, including version numers
- The first and last time a product was used
- The first time statistics were gathered
- Your Vaadin user account
- Whether you are a Vaadin Pro user or not (true/false)
- Browser user-agent string
- The IP address the statistics is sent from
```

in my opinion we can drop vaadin components and use `@paper` components or create new ones.

**Comment by planetf1** [comment]
I'm not an expert on vaadin - it does seem widely used. It looks as if the docs do discuss how to remove stats capture -- my main concern was just to ensure this was absolutely clear to consumers, and most likely disabled by default. Over to the UI team to figure out best technology for the UI though. :-)

**Comment by sarbull** [comment]
@planetf1 it seems that it is disabled by default here [0].

[0] - https://github.com/odpi/egeria-ui/blob/master/package.json#L8

**Comment by planetf1** [comment]
Hopefully - that's good and we could close the issue. However I think it would be worthwhile checking for nothing untoward in the debugger/network trace. I know we had a few funnies in the early days with the vaadin code though that may well now be resolved.

**Comment by sarbull** [comment]
@planetf1 this is visible in the build logs at `npm install` phase:

```bash
$ @vaadin/vaadin-usage-statistics@2.1.0 postinstall /Users/lk61fu/projects/latest/egeria-ui/node_modules/@vaadin/vaadin-usage-statistics
$ node check.js
```

**Comment by sarbull** [comment]
<img width="582" alt="Screenshot 2021-03-18 at 09 53 44" src="https://user-images.githubusercontent.com/1864112/111591224-d7986180-87cf-11eb-938f-f1a88f30594a.png">
