### ISSUE TITLE
Minor updates needed in tutorial contents

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1162]
Working through tutorial to validate #1114 

When referring to the postman collection the text lists the URL, but this isn't a raw link - so postman will give an error if it is pasted into the 'import' URL 

Instead use `https://raw.githubusercontent.com/odpi/egeria/master/open-metadata-resources/open-metadata-tutorials/omag-server-tutorial/resources/omag-server-platform-tutorial.postman_collection.json` for the raw link

**Comment by mandy-chessell** [comment]
Then we need to find a phrase that makes it clear these are the rest API URLs not a clickable link

**Comment by planetf1** [comment]
The intent of the text is I think to allow someone to easily use the requests within postman. They may look at the file too, but that is probably secondary.

If one goes into the import option in postman it requests a URL to import from. I think it reasonable for the reader to copy the URL text and paste in to postman -- it is this case where it fails.

A few possibilities
 * Just change the text and the link to point directly to the raw file -- this allows inspection and cut/paste from the link, or opened URL - though is less pretty
 * Change the text to refer to the raw version, but have the link go to the broader github formatted page -- but this could be confusing even if it meets the most likely case of cut/paste
 * Add a 'copy' icon as I've seen in various tutorials where the referenced text is automatically copied into the clipboard. This could be combined with the other options.

I think the simplest is probably the first of these?

**Comment by cmgrote** [comment]
If I'm understanding, this is a minor change so that users can directly import the collections into Postman by copy / pasting the link, since Postman allows you to import via a URL -- rather than needing to open up the file, manually copy / paste it and / or navigate to the "raw" button.

**Comment by mandy-chessell** [comment]
Thanks Nigel - I get it now - the intent was to allow someone to locate the file for download.  I did not realized you could import it directly into Postman - which is nice.  We probably need 2 links - one to find file in build tree and the other to directly import
