### ISSUE TITLE
Cohort metrics - what would be useful?

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#1168]
The OMRS is processing events and responses from all members of the cohort.  What metrics should we be gathering about its exchanges to help an organization with such use cases as optimize their replication, understand if a member is in trouble etc?

**Comment by cmgrote** [comment]
- Counts of event types by dimensions (if possible), eg. grouped by open metadata type, averages per time slice (hour / day / week / etc).  Useful to monitor reality vs expectation on rate of changes, types handled, etc & via time slice whether there might be exceptional cases preceding slowdowns or outages.
- Average time / delay between an event hitting the cohort and being picked up by each consumer (if possible?) This would allow monitoring of slowdowns in throughput by consumer, potentially indicating overload of the consumer.

**Comment by planetf1** [comment]
* As per Chris, but also a breakdown by repository - especially as these are third party components, so we can understand which ones working well, which not
* Messages queued for delivery to kafka
* Integration of all metrics with appropriate (research) external infrastructure
