### ISSUE TITLE
Document use of TLS Cerificates with Core Egeria technology

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#1196]
See #634

**Comment by cmgrote** [comment]
Hi Mandy -- should we target this for something like a blog entry, or do you have any particular location in mind within the core code stack to put the documentation? 😄

**Comment by mandy-chessell** [comment]
We need the equivalent of a planning and installation guide covering security (ceritifcates, server and user identities, the security plugin), how many servers to have, where to put them, how to divide them into cohorts etc.  This would be for the technical team doing the set up and install.  So this should be in the open-metadata-publication module - but I like the idea of some blogs that point to the relevant points in the guide

**Comment by cmgrote** [comment]
Agreed: good to have documented as part of the project, and we could even have a blog "series" with entries on key bits -- referring back to the documentation for details -- giving us the blog entries for #1212.

**Comment by planetf1** [comment]
Many dimensions ... I think we should cover the basic 'standalone/bare' case as well as within a k8s deployment. There will be multiple options. With pom refactoring coming to an end I plan to spend more time back on k8s/certs/istio as *one* option.

**Comment by cmgrote** [comment]
Excellent!  Sounds like you just volunteered to take a first crack at it 😉
