### ISSUE TITLE
Graph database write-up

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1197]
@grahamwallis ^^

**Comment by grahamwallis** [comment]
@cmgrote - I'm very happy to write this - where should it live?

**Comment by cmgrote** [comment]
In the ODPi WordPress blog: https://lfprojects.linuxfoundation.org/wp-login.php

**Comment by cmgrote** [comment]
@grahamwallis hopefully this is still on your radar? 😉  Give me a shout if you need pointers on the WordPress blog (assuming you have access?)

**Comment by grahamwallis** [comment]
Thanks @cmgrote - I'm on it. Is there a way to save the article as a draft - and then review it before publishing?

**Comment by cmgrote** [comment]
Of course!

To start creating your entry, just go to "Posts" -> "New Post".  Once you start typing in some content you should always have a link in the upper-right that says "Save Draft".  (It will also periodically auto-save as a draft.)

Once you're reasonably happy with it and want to circulate for review (but not yet publish), then there's a little tick-box over in the right-hand side labeled "Pending Review". By default it's un-ticked: just tick it and then your "Save Draft" will turn into "Save as Pending" (which means everyone else can see it to review it, but it won't be publicly available).

**Important note**: there is a link just above the "Pending Review" tick-box that indicates when it will automatically publish -- you probably want to change this to a few days out to give folks time to review before it becomes publicly available automatically...
