### ISSUE TITLE
Conformance Suite write-up

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1202]

**Comment by planetf1** [comment]
@grahamwallis I think you have this in hand? Do you want to close it when the blog is published and add a link? Plus any other docs?

**Comment by grahamwallis** [comment]
Yes - keeping this open for now until the blog is completed.

**Comment by planetf1** [comment]
Closing - now published at https://www.odpi.org/blog/tech-deep-dive/2019/12/04/the-odpi-egeria-open-metadata-conformance-suite-repository-workbench
