### ISSUE TITLE
Repository Connector implementation write-up

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1208]
Write-up of / tutorial for how to implement a repository connector to a metadata collection.

**Comment by cmgrote** [comment]
Blog entry is now drafted and proofread -- it's at quite a different level (detailed technical) than other blog entries, so before publishing I'm wondering if we want to see about creating different "areas" in the blog?  For example, a separate area under which to publish such deep-dive / how-to materials (?)

**Comment by mandy-chessell** [comment]
I like the idea of topics - where is the draft?

**Comment by cmgrote** [comment]
Draft is in the WordPress site — not sure if I need to share it as a draft somehow or if we are all able to see it before it’s published (?)

**Comment by cmgrote** [comment]
I've moved the draft into a "Pending" state, as I suspect this will make it more reviewable by all (I'm also able to Preview from there, which revealed a fair number of minor formatting changes to be made)...

**Comment by cmgrote** [comment]
Blog is set to go-live Monday morning at 7am PST -- please shout before then if any urgent changes needed 😉

**Comment by cmgrote** [comment]
Live!  https://www.odpi.org/blog/2019/07/08/implementing-an-open-metadata-connector
