### ISSUE TITLE
OpenShift demo write-up

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1213]

**Comment by planetf1** [comment]
For v3 IKS now supports OpenShift clusters - indeed I have one deployed for testing.
I think v4 support comes in the fall

**Comment by cmgrote** [comment]
I seem to have lost track of who volunteered for which of these, but thinking this one was yours?

**Comment by planetf1** [comment]
yes

**Comment by planetf1** [comment]
See #1203 for some cloud related blogs.
Instead for core egeria I will add a blog/content around using the open source 'microk8s' project which a number of people including myself have used very successfully.
