### ISSUE TITLE
Allow full build of atlas image from source

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1224]
In https://github.com/odpi/egeria/pull/1152/files the dockerfile was split
The core atlas build was moved into 'Dockerfile.build' . 

However no change was made to the pom.xml to allow this build to run

So
mvn clean install -Ddocker -Ddocker.repo=myrepo

will build the 'modification' layer only. Much of the time this is what is wanted, and it makes development much quicker.

However the original intent was to allow any user of the project to build their own images from scratch (some people require this)

Therefore we need to add an additional configuration to the pom.xml for each of the docker images that are split - probably *optionally* to also run Dockerfile.build -- and also parameterize the use of that base image.

See also https://github.com/odpi/egeria/pull/1178

**Comment by akhilreddyjirra** [comment]
@planetf1 I have modified pom.xml in apache-atlas for building a base/builder  image 
```
                    <execution>
                        <id>base-image-build</id>
                        <phase>package</phase>
                        <goals>
                            <goal>build</goal>
                        </goals>
                        <configuration>
                            <dockerfile>Docker.build</dockerfile>
                            <tag>build</tag>
                        </configuration>
                    </execution>
```
`mvn clean package -Ddocker.repo=xxxx`
this will create the image as 
```
$ docker images
REPOSITORY                                          TAG                   IMAGE ID            CREATED             SIZE
registry-1.docker.io/akhilreddyjirra/apache-atlas   build                 4b98f2df8d56        4 hours ago         10GB

```
i have two things.
1. Is this an accepatable  solution ?
2. If yes ,how can i tell to Dockerfile to take outputs from base/Builder  image

for example in Dockerfile
```
FROM odpi/apache-atlas:build AS build
FROM openjdk:8-jdk-alpine
```
to 
```
FROM <users repo>/apache-atlas:build AS build
FROM openjdk:8-jdk-alpine
```
the following is the pox.xml at open-metadata-resources/open-metadata-deployment/docker/apache-atlas
```
<?xml version="1.0" encoding="UTF-8"?>
<!-- SPDX-License-Identifier: Apache-2.0 -->
<!-- Copyright Contributors to the ODPi Egeria project. -->

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <parent>
        <artifactId>open-metadata-docker</artifactId>
        <groupId>org.odpi.egeria</groupId>
        <version>1.1-SNAPSHOT</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>

    <name>Docker image - Apache Atlas</name>
    <description>
        Samples, Helm charts to deploy Egeria and associated components such as docker image build scripts
    </description>

    <artifactId>open-metadata-docker-apache-atlas</artifactId>

    <packaging>pom</packaging>
    <build>
        <plugins>
            <!-- Setup the docker build.
                 Note - bound to 'install' phase as deploy causes push of maven artifacts
            -->
            <plugin>
                <groupId>com.spotify</groupId>
                <artifactId>dockerfile-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>build-and-tag-latest</id>
                        <phase>install</phase>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>base-image-build</id>
                        <phase>package</phase>
                        <goals>
                            <goal>build</goal>
                        </goals>
                        <configuration>
                            <dockerfile>Docker.build</dockerfile>
                            <tag>build</tag>
                        </configuration>
                    </execution>
                    <execution>
                        <id>tag-version</id>
                        <phase>install</phase>
                        <goals>
                            <goal>tag</goal>
                        </goals>
                        <configuration>
                            <tag>${project.version}</tag>
                        </configuration>
                    </execution>
                    <execution>
                        <id>push-latest</id>
                        <phase>install</phase>
                        <goals>
                            <goal>push</goal>
                        </goals>
                        <configuration>
                            <tag>latest</tag>
                        </configuration>
                    </execution>
                    <execution>
                        <id>push-version</id>
                        <phase>install</phase>
                        <goals>
                            <goal>push</goal>
                        </goals>
                        <configuration>
                            <tag>${project.version}</tag>
                        </configuration>
                    </execution>
                </executions>
                <configuration>
                    <repository>${docker.registry}/${docker.repo}/apache-atlas</repository>
                    <!-- <dockerfile>Docker.build</dockerfile>
                    <imageTag>base</imageTag> -->
                    <buildArgs>
                    </buildArgs>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

**Comment by planetf1** [comment]
Hi,
 Thanks for looking at this.

 If we're going to split the build for atlas, we need to build both versions - is that your plan? 

 For dockerhub a start might be to add a 'buildarg' in the pom.xml above (near bottom)
```
<buildArgs>
--build-arg REPO=${docker.registry}/${docker.repo}
</buildArgs>
```

And then in the dockerfile use
```
ARG REPO=docker.io/odpi
FROM $REPO/apacheatlas:build AS build
```
Or similar?

not tried it yet - do you want to give it a go?

**Comment by akhilreddyjirra** [comment]
> Hi,
> Thanks for looking at this.
> 
> Maybe ... something like
> 
> ```
> <buildArgs>
> --build-arg REPO=${docker.registry}/${docker.repo}
> </buildArgs>
> ```
> 
> And then in the dockerfile use
> 
> ```
> ARG REPO=docker.io/odpi
> FROM $REPO/apacheatlas:build AS build
> ```
> 
> Or similar?
> 
> not tried it yet - do you want to give it a go?

correction
```
<buildArgs>
   <REPO>${docker.registry}/${docker.repo}</REPO>
</buildArgs>
```

**Comment by akhilreddyjirra** [comment]
> Hi,
> Thanks for looking at this.
> 
> Maybe ... something like
> 
> ```
> <buildArgs>
> --build-arg REPO=${docker.registry}/${docker.repo}
> </buildArgs>
> ```
> 
> And then in the dockerfile use
> 
> ```
> ARG REPO=docker.io/odpi
> FROM $REPO/apacheatlas:build AS build
> ```
> 
> Or similar?
> 
> not tried it yet - do you want to give it a go?

@planetf1
my bad i didn't check the mvn install phase earlier, just checked what I notice is both mvn install and package are building the Docker.file only
can you suggest what the issue would be.

mvn clean install -Ddocker -Ddocker.repo=myrepo
mvn clean package -Ddocker -Ddocker.repo=myrepo
[INFO] Building Docker context /home/shris.local/ram/Documents/egeria/open-metadata-resources/open-metadata-deployment/docker/apache-atlas
[INFO] Path(dockerfile): /home/shris.local/ram/Documents/egeria/open-metadata-resources/open-metadata-deployment/docker/apache-atlas/Docker.build
[INFO] Path(contextDirectory): /home/shris.local/ram/Documents/egeria/open-metadata-resources/open-metadata-deployment/docker/apache-atlas
[INFO] 
[INFO] Image will be built as registry-1.docker.io/akhilreddyjirra/apache-atlas:build
[INFO] 
[INFO] Step 1/15 : FROM maven:3.6.0-jdk-8

let know any suggestion? please

**Comment by planetf1** [comment]
If you've made some changes beyond master it may be worth either I test out what you have/see if it's workiing or try and debug it. Or create a PR that we don't merge (so I can pull)? I can take another look

**Comment by planetf1** [comment]
marking as done for now. will reopen if there are residual issues after latest changes
