### ISSUE TITLE
Use prebuild ranger distribution from apache for ranger docker

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1251]
From the new atlas build it was noted that apache makes build versions of released code available for download.

Rather than build ranger from source, we can use this source instead probably cutting an hour off the docker ranger build! See the atlas Docker.build file

https://www.apache.org/dist/ranger/1.2.0/

@akhilreddyjirra - I see you are currently refactoring the ranger/atlas builds so would it make sense for you to make this change? If not I can :-)

See also https://github.com/odpi/egeria/pull/1178/files (not merged, closed - initial proposal)

**Comment by akhilreddyjirra** [comment]
> From the new atlas build it was noted that apache makes build versions of released code available for download.
> 
> Rather than build ranger from source, we can use this source instead probably cutting an hour off the docker ranger build! See the atlas Docker.build file
> 
> https://www.apache.org/dist/ranger/1.2.0/
> 
> @akhilreddyjirra - I see you are currently refactoring the ranger/atlas builds so would it make sense for you to make this change? If not I can :-)
> 
> See also https://github.com/odpi/egeria/pull/1178/files (not merged, closed - initial proposal)

sure @planetf1

**Comment by planetf1** [comment]
done
