### ISSUE TITLE
IGC connector rename breaks current helm chart

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1254]
In the current helm chart the ibm igc pod (proxy) fails to init
```
wintering-molly-vdc-ibm-igc-8bdf8c8c7-pgbc4             0/1     Init:CrashLoopBackOff   5          6m20s
```
Looking in more detail:
```
   Command:
      /bin/bash
      -c
      cd /opt/egeria/connectors && wget https://github.com/odpi/egeria-connector-ibm-igc/releases/download/1.1-SNAPSHOT/egeria-connector-ibm-igc-package-1.1-SNAPSHOT.jar

    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
```
It looks like the URL for the release has changed and is now `https://github.com/odpi/egeria-connector-ibm-igc/releases/download/1.1-SNAPSHOT/egeria-connector-ibm-information-server-package-1.1-SNAPSHOT.jar`

@cmgrote I can address - or are you part way through refactoring?

**Comment by cmgrote** [comment]
Aha, figured that name change would break somewhere -- missed that, though.  Yes please, by all means go ahead and fix if you're already on top of it.
