### ISSUE TITLE
Question on Data Engine OMAS client

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1255]
Looking at the Data Engine OMAS client, it seems there's the creation of a restClient with a userId and password:

```
public DataEngineImpl(String serverName, String serverPlatformRootURL, String userId, String password) throws InvalidParameterException {
    // ...
    this.restClient = new OCFRESTClient(serverName, serverPlatformRootURL, userId, password);
}
```

However, every method of the client itself also currently requires a `userId`, which ends up being passed on to the `restClient`...  Are these meant to be distinct users (and the latter not having any associated password)?  Or should we be re-using the `userId` (and password, if needed) from the `restClient` itself?

**Comment by mandy-chessell** [comment]
The client is for environments such as the Egeria UI that is serving many real users.

The userId/password passed on the constructor is the "system" NPA credentials for the UI application that are used in the HTTP header.  The userId on the calls is the userId of the person that the client is acting on behalf of.

**Comment by cmgrote** [comment]
> The userId/password passed on the constructor is the "system" NPA credentials for the UI application that are used in the HTTP header. The userId on the calls is the userId of the person that the client is acting on behalf of.

Makes sense.  Would it be logical for this second `userId` to be defaulted to something NPA-ish given it is the proxy acting on behalf of a Data Engine that's making the change?  Or should I pull this as another parameter from the configuration of the proxy?  Or pick it up from the underlying object(s) themselves (ie. whoever last modified the underlying job that's being synced)?

**Comment by mandy-chessell** [comment]
Not really - the only time this would be valid is in demo apps - not the general case.

**Comment by cmgrote** [comment]
> Not really - the only time this would be valid is in demo apps - not the general case.

"This" referring to all of the options?  Where should this `userId` come from, when the client is acting on behalf of a Data Engine Proxy, which itself is acting on behalf of a Data Engine? 😄

**Comment by mandy-chessell** [comment]
The server config doc has a local userId and password.  This goes on the constructor for the client.
The userId for the request ideally should be the developer's userId that is creating the process.  If this is not possible then the Data Engine Proxy config should have a default developer userId

**Comment by cmgrote** [comment]
Sounds good, thanks!
