### ISSUE TITLE
Question on addExternalEntity

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1267]
We probably discussed this before (apologies if I forgot the answer -- opening this so we can refer back to it later going forward), but is there a reason we don't allow a GUID for the entity instance itself to be provided via the `addExternalEntity` method?

Example use case: an ETL engine sync'ing its process information via the Data Engine Proxy Services (into a Data Engine OMAS) will most likely be able to provide a unique ID for each one -- and it would potentially be useful to retain this to be able to cross-reference between the data engine's own records of its processes and those held in metadata as owned by the data engine.

**Comment by mandy-chessell** [comment]
Assigning and managing guids is the responsiblity of the reposiotry services.  The repository services may change the guid via the reIdentifyXXX() methods so the data engine can not rely on the value.   The Data Engine should put its unique id into the qualified name.
