### ISSUE TITLE
Update URL for open lineage services

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#1278]
The REST API for open lineage services is currently defined in
org.odpi.openmetadata.governanceservers.openlineage.server.spring.OpenLineageOMASResource

as

````
@RequestMapping("/open-metadata/admin-services/users/{userId}/servers/{serverName}/open-lineage")
````

The "admin-services" marker should be for the configuration and server operation services in the admin services component.

The Open Lineage Services should have its own marker - something like this ...

````
@RequestMapping("/open-metadata/open-lineage/users/{userId}/servers/{serverName}")
````

**Comment by GuyAckermans** [comment]
Thanks for spotting Mandy, it has been corrected.
