### ISSUE TITLE
Support diagnosis of cohort failure

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#1289]
How does an administrator investigate the reasons why metadata is not being shared across one or more cohorts, both in terms of the diagnostic process, and the diagnostic aids that Egeria supplies?

Then having identified the root cause of the problem, how does the administrator fix it.

----
First we need to consider what needs to be in place for the cohort to operate successfully as this gives clues as to what could be wrong.

- The members of a cohort register with each other through an event topic.  This topic needs to be consistently named in each member to ensure they are connected to the same destination.
- The event topic is hosted by an event bus such as Kafka.  This event bus must be operating correctly, and each member needs to be correctly configured to connect to it.  This includes the correct security privilleges.
- Each member must send out a registration request and respond correctly to other member's registration requests.
- The content of each registration request includes descriptive properties of the server.  If the server has a local repository, the metadata collection id (and optional name) is exchanged.  If the server supports remote calls to its local repository then a remote connection is included.
- The federated query calls other members that have successfully registered with the remote connection.
- The calling server needs permission to call methods on the other members' REST APIs.

In this situation, there may or may not be error messages being produced in the audit logs of the cohort members.

**Comment by mandy-chessell** [comment]
The Egeria administrator needs to be able to systematically check each of these points to determine the cause of the problem - and whether it is permanent (eg config error) or temporary (eg a key piece of infrastructure is not available.

If the cause is Egeria, then the adminstrator needs to be able to fix it.

**Comment by mandy-chessell** [comment]
The audit log messages can give a clue to the health of the cohort.  However there are a lot of them and so a mechanism to query for specific types of messages is important.

Within each audit message is a description of what action to take.

**Comment by mandy-chessell** [comment]
Since there may not be an error message it is also important to be able to query the status of a member with respect to the cohort - this includes information such as:

- the configuration values
- the numbers of events that have been sent and received - and the last one processed.
- the local and remote member information
- the remote connectors operating in the enterprise services

**Comment by planetf1** [comment]
In additional to events sent/received/last one, it would be useful to know how many are queued (though this may vary by connector in use for topics)

**Comment by mandy-chessell** [comment]
This is a good idea - we actually do queue events inside Egeria if the event bus is not responding so we could query the event queue.

**Comment by mandy-chessell** [comment]
Still needed
