### ISSUE TITLE
Add event bus destination for audit log

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#1296]
An OMAG server can be configured with many audit log destinations.  Each destination is implemented by an audit log connector.  This enhancement proposes a new destination that pushes the audit log entries to a named topic on the server's configured event bus.

It is in 2 parts:
- provide the connector implementation
- make it easy to configure this new destination in the configuration document for the server.

**Comment by planetf1** [comment]
It looks as if this went in around fcad2262efa21e28111694c5d03a7e91a762f1d2

It would be great - and help navigability if we tracked a xref from the issue to the code change/commit/pr
