### ISSUE TITLE
Ensure consistency of repository connector 'find...' methods

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#1315]
We need to ensure that the repository connectors are consistent in terms of whether they perform sub-string or exact matches for string-type property values.

Specifically, we would like to ensure that the In-Memory, Graph, IGC and SAS connectors are consistent. Other connectors should be considered too in future.

With regard to specific behaviour:

- findEntitiesByProperty, findRelationshipsByProperty, findEntitiesByClassification methods should all perform an exact match for string-type property values. (In addition these methods perform exact match for all other property types).

- findEntitiesByPropertyValue, findRelationshipsByPropertyValue methods should perform a substring match for (all) string-type property values. These methods only match against properties of type string or collection of strings. In the case of a collection of strings (such as an array of strings) then sub-string matches should be performed against the individual array elements.

Each connector should provide clear javadoc to describe the behaviour.

@cmgrote, @CDaRip2U, @mandy-chessell - please make sure you are happy with the above.

**Comment by cmgrote** [comment]
For clarity: is it only the methods in the first bullet point that support regular expressions in their search criteria?

Correct me if I'm wrong, but if all the methods should support regular expressions, I don't understand why the methods in the second bullet point need to implicitly do substring searches.  IMHO it would be better to require the caller to specify in their regex whether they expect a substring match (`*mystring*`) or exact match (`mystring`)...

**Comment by grahamwallis** [comment]
@cmgrote - Hi Chris - There is additional material on regex in issue #1316, but happy to discuss and augment both here and there.

For a repository & connector that understand regex:

- The methods in the first bullet (in this issue) perform exact match with regex.
- The methods in the second bullet perform substring match with regex.

Your suggestion may simplify things for regex-savvy connectors - as you suggest they could behave the same for both sets of methods and require that the regex is a complete match. So for substring the user would have to explicitly say that in the regex. For non-regex-savvy connectors there could still be the difference as listed above.. I'm not sure whether that is better or more confusing; I was trying to keep the two aspects separate (i.e. regex support and sub-string matching). But I am happy to converge on a commonly agreed approach.

What I have currently implemented in the graph repo - yet to be checked in - is that for the find..ByPropertyValue() methods (only) the regex is extended with ".*" as both a prefix and suffix so that the regex will match any portion of a string value. That's not the only way to implement it but it's very simple.

**Comment by cmgrote** [comment]
Stated differently: all methods are expected to perform regex-based matches.  I therefore would suggest that they all do that regex-based match the same way -- not implicitly applying a substring wrapping on some methods and not others -- but forcing the caller of the method to precisely specify the behaviour it is after (ie. do its own wrapping to do a substring match if that is the desired set of results, and not wrapping the regex if it wants an exact match).

That way:

- the methods will have consistent interfaces (from a consumption perspective)
- all of the methods can support both substring and exact matches (simply based on the regex passed)
- the connectors that implement the methods can treat them consistently as well

**Comment by grahamwallis** [comment]
@cmgrote - I agree - let's give the others a chance to agree/object but I like your suggestion.

**Comment by ruxandraRosu** [comment]
Hi,
I have one concern regarding the regex search. In many flows we're using the search by qualifiedName which should retrieve at most one entity for the specified type. Both in atlas connector and local graph this performs a regex search. This is causing 2 issues:
1. Returning multiple entities. 
2. Issue with not returning any entity though there is a match in the repo because of the special characters inside the qualifiedName like (), . etc. This issue happened for some entities, I couldn't identify the exact pattern for when it's happening.

**Comment by cmgrote** [comment]
After today's functionality call, moving ahead with at least consistency and regex usage for the existing `find...` methods (other options to be further cogitated and discussed at a later time).

To assist, helper methods are introduced to escape (qualify) strings that might otherwise be interpreted as regexes but that should not be so interpreted -- see #1339

**Comment by cmgrote** [comment]
@ruxandraRosu can you have a look at the methods added to OMRSRepositoryHelpers in #1339 ?  As I understand it, you can leverage these from within the OMAS (via the Enterprise Repository Connector instance providing a link to the repository content manager instance) -- for example, if you can apply the `getExactMatchRegex()` to your string this should solve both (1) (by enforcing an exact match not a substring / contains / etc) and (2) (by escaping any regex-meaningful characters appropriately).

(Note that we still need to implement the interpretation of these within our connectors -- coming shortly for IGC and Atlas -- but key that you're able to leverage these helpers within your OMASes to ensure everything links up 😄 !)

**Comment by ruxandraRosu** [comment]
Hi @cmgrote,
getExactMatchRegex looks like fixing issue 2, which was the more problematic as it was preventing the entities for being retrieved.
For 1: I am not sure about the case where there are 2 qualifiedNames like this:
qualifiedName=(RelationalTable)=EMP
qualifiedName=(RelationalTable)=EMP2
In this case I think we will still need to verify on OMAS side for exact match.

**Comment by cmgrote** [comment]
> In this case I think we will still need to verify on OMAS side for exact match.

Sounds good -- of course, we need to also first update the underlying repository connectors, but I do believe once we've done that this should solve (2) as well (so long as you've used `getExactMatchRegex()` to construct your query string that you send along).

**Comment by cmgrote** [comment]
Behaviour described in #1316 and #1339 is now implemented in both the Atlas and IGC connectors -- though I noticed a bug in the implementation of my helper methods, so just need to have #1352 merged before all should work...
