### ISSUE TITLE
Kafka event published by one omas on cohort topic not consumed by another omas running in same server instance

### ISSUE THREAD

**Issue by ruxandraRosu** [odpi/egeria#1336]
Events published by Data Engine OMAS are not consumed by AssetLineage OMAS when both OMASs are enabled in the same server. 
This is caused by the event published by DE OMAS having the same serverId in the originator property as the AL OMAS serverId (since both are running in the same instance).
The quick workaround was to start the OMASs in 2 separate servers so they have different serverIds. Looking into the configuration, it looks like the property serverId can be configured for each OMAS, but this would apply for the in/out connectors, not for enterprise connector.  
Shouldn't the event be consumed even when the OMASs are started in the same server instance?

**Comment by mandy-chessell** [comment]
To clarify the use case for others reading this later, events produced by an OMAS are sent on its out topic.  These events are consumed by governance servers, UIs and other applications/tools integrating directly into the Egeria ecosystem.  They are never consumed by another OMAS.

In fact events are **never** passed between OMASs.  However, when an OMAS makes a change to metadata, the local repository where the metadata is mastered will send out a OMRS event.  This event is sent to all local OMASs through the in-memory event topic and to other members of the cohort through kafka.

The other members of the cohort receive the event from kafka and then pass it to its local repository to optionally save it as reference copy of the metadata.  In addition, the local OMASs are informed of the event via the in memory event topic.

**Comment by mandy-chessell** [comment]
The localServerId is a unique guid for each OMAG server - this is different from the metadata collection id which is a unique guid for each repository.  It is not possible to set the localServerId for each OMAS in the server.

Today the localServerId is only used by the kafka topic connector.  It sets this value in the event header of each OMRS Event it sends.  On receipt of ev,vents it inspects the localServerId value in the event header to identify if it is the originator of the event and can therefore ignore it.

Using a server identifier in the event header means it does not need to demarshal the JSON to Java to access the metadata collection Id.   This performance enhancement has been in place for over 6 months and is not the cause of this issue because kafka is not involved in distributing events from the local repository to the local OMASs.

It seems that if local repository was not sending events in the first place then the work around to move the receiving OMAS to a different server would not resolve the issue.   

We are probably looking for a recent change in how events are distributed within a server - and specifically the difference between event distribution from (1) an incoming event from the OMRS topic and from (2) an outbound event from the local repository.  This suggests a problem in initialization of the event processors, the operation of the event processors and/or the distribution of events via the in-memory event topic.

**Comment by mandy-chessell** [comment]
I think I have found the cause of the problem in the initialization of the repository services.  However, it is in code that has not changed.  This means that this bug has always been there and is not a recent change so I am a little puzzled.

I compared the initialization logic with the original OMRS initialization design and discovered that the OMRSRepositoryEventPublisher that should connect the local repository to the enterprise topic connector was not being created and linked into the event manager (see red arrow).

<img width="787" alt="Screenshot 2019-08-03 at 21 11 44" src="https://user-images.githubusercontent.com/12354195/62416556-e2bb6f80-b634-11e9-9765-47bdf3863e17.png">

This would explain why events from the local repository are not passed to the local OMASs.

**Comment by mandy-chessell** [comment]
This is the complete initialization design, for info ...
<img width="846" alt="Screenshot 2019-08-03 at 21 39 38" src="https://user-images.githubusercontent.com/12354195/62416707-b81ee600-b637-11e9-8118-ba45b9670b23.png">

**Comment by mandy-chessell** [comment]
I have added the initialization of the missing event processor plus audit log events to show the initialization of the event processors (see OMRS-AUDIT-0030).  This is the start up sequence:

```
Sat Aug 03 23:26:20 BST 2019 cocoMDS1 OMRS-AUDIT-0001 The Open Metadata Repository Services (OMRS) is initializing
Sat Aug 03 23:26:20 BST 2019 cocoMDS1 OMRS-AUDIT-0002 Enterprise access through the Enterprise Repository Services is initializing
Sat Aug 03 23:26:20 BST 2019 cocoMDS1 OMRS-AUDIT-0003 The local repository is initializing with metadata collection named Data Lake Catalog with an id of 04ff0d60-1e98-48fb-b54a-c4f4cd6bdd11
Sat Aug 03 23:26:20 BST 2019 cocoMDS1 OMRS-AUDIT-0029 The local repository outbound event manager is initializing
Sat Aug 03 23:26:20 BST 2019 cocoMDS1 OMRS-AUDIT-0030 Registering the Local Repository to Enterprise event consumer with the local repository outbound event manager
Sat Aug 03 23:26:20 BST 2019 cocoMDS1 OMRS-AUDIT-0050 The Open Metadata Repository Services (OMRS) is about to process open metadata archive Open Metadata Types
Sat Aug 03 23:26:20 BST 2019 cocoMDS1 OMRS-AUDIT-0301 The local server has added a new type called object with a unique identifier of 1c4b21f4-0b67-41a7-a6ed-2af185eb9b3b and a version number of 1 from ODPi Egeria (OMRS)
  :        :       :       :       :        :       :       :      :        :       :       :       :        :       :       :        :        :       :       :       :        :       :       :    
Sat Aug 03 23:26:20 BST 2019 cocoMDS1 OMRS-AUDIT-0301 The local server has added a new type called RelationshipAnnotation with a unique identifier of 73510abd-49e6-4097-ba4b-23bd3ef15baa and a version number of 1 from ODPi Egeria (OMRS)
Sat Aug 03 23:26:20 BST 2019 cocoMDS1 OMRS-AUDIT-0053 The Open Metadata Repository Services (OMRS) has loaded 436 types and 0 instances from open metadata archive Open Metadata Types
Sat Aug 03 23:26:20 BST 2019 cocoMDS1 OMRS-AUDIT-0004 Connecting to the metadata highway
Sat Aug 03 23:26:20 BST 2019 cocoMDS1 OMRS-AUDIT-0005 Connecting to cohort cocoCohort
Sat Aug 03 23:26:20 BST 2019 cocoMDS1 OMRS-AUDIT-0029 The cocoCohort cohort inbound event manager is initializing
Sat Aug 03 23:26:20 BST 2019 cocoMDS1 OMRS-AUDIT-0030 Registering the cocoCohort event consumer with the local repository outbound event manager
Sat Aug 03 23:26:20 BST 2019 cocoMDS1 OMRS-AUDIT-0030 Registering the Local Repository Content (TypeDef) Manager event consumer with the cocoCohort cohort inbound event manager
Sat Aug 03 23:26:20 BST 2019 cocoMDS1 OMRS-AUDIT-0030 Registering the Local Repository Inbound Instance Events event consumer with the cocoCohort cohort inbound event manager
Sat Aug 03 23:26:20 BST 2019 cocoMDS1 OMRS-AUDIT-0030 Registering the Cohort to Enterprise event consumer with the cocoCohort cohort inbound event manager
Sat Aug 03 23:26:20 BST 2019 cocoMDS1 OMRS-AUDIT-0031 The cocoCohort cohort inbound event manager is starting with 2 type definition event consumer(s) and 2 instance event consumer(s)
Sat Aug 03 23:26:20 BST 2019 cocoMDS1 OMRS-AUDIT-0026 Initializing listener for cohort cocoCohort
Sat Aug 03 23:26:20 BST 2019 cocoMDS1 OMRS-AUDIT-0019 The OMRS Topic Connector TopicConnector.Cohort.cocoCohort has registered with an event bus connector connected to topic egeria.omag.openmetadata.repositoryservices.cohort.cocoCohort.OMRSTopic
Sat Aug 03 23:26:20 BST 2019 cocoMDS1 OCF-KAFKA-TOPIC-CONNECTOR-0001 Connecting to Apache Kafka Topic egeria.omag.openmetadata.repositoryservices.cohort.cocoCohort.OMRSTopic with a server identifier of ae9e1b82-17d5-4d14-9f19-04571d012ed2
Sat Aug 03 23:26:20 BST 2019 cocoMDS1 OCF-KAFKA-TOPIC-CONNECTOR-0003 8 properties passed to the Apache Kafka Consumer for topic egeria.omag.openmetadata.repositoryservices.cohort.cocoCohort.OMRSTopic
Sat Aug 03 23:26:20 BST 2019 cocoMDS1 OCF-KAFKA-TOPIC-CONNECTOR-0002 8 properties passed to the Apache Kafka Producer for topic egeria.omag.openmetadata.repositoryservices.cohort.cocoCohort.OMRSTopic
Sat Aug 03 23:26:20 BST 2019 cocoMDS1 OMRS-AUDIT-0020 The OMRS Topic Connector TopicConnector.Cohort.cocoCohort is ready to send and receive events
Sat Aug 03 23:26:20 BST 2019 cocoMDS1 OCF-KAFKA-TOPIC-CONNECTOR-0010 The Apache Kafka producer for topic egeria.omag.openmetadata.repositoryservices.cohort.cocoCohort.OMRSTopic is starting up with 0 buffered messages
Sat Aug 03 23:26:20 BST 2019 cocoMDS1 OMRS-AUDIT-0015 The listener thread for an OMRS Topic Connector for topic egeria.omag.openmetadata.repositoryservices.cohort.cocoCohort.OMRSTopic has started
Sat Aug 03 23:26:20 BST 2019 cocoMDS1 OMRS-AUDIT-0060 Registering with open metadata repository cohort cocoCohort using metadata collection id 04ff0d60-1e98-48fb-b54a-c4f4cd6bdd11
Sat Aug 03 23:26:20 BST 2019 cocoMDS1 OMRS-AUDIT-0040 An enterprise OMRS connector has been created for the Repository REST Services Open Metadata Access Service (OMAS)
Sat Aug 03 23:26:20 BST 2019 cocoMDS1 OMRS-AUDIT-0041 The enterprise OMRS connector for the Repository REST Services Open Metadata Access Service (OMAS) has started
Sat Aug 03 23:26:20 BST 2019 cocoMDS1 OMRS-AUDIT-0031 The local repository outbound event manager is starting with 2 type definition event consumer(s) and 2 instance event consumer(s)
Sat Aug 03 23:26:20 BST 2019 cocoMDS1 OMRS-AUDIT-0032 The local repository outbound event manager is sending out the 436 type definition events that were generated and buffered during server initialization
Sat Aug 03 23:26:21 BST 2019 cocoMDS1 OMRS-AUDIT-0007 The Open Metadata Repository Services (OMRS) has initialized
Sat Aug 03 23:26:21 BST 2019 cocoMDS1 OPEN-METADATA-SECURITY-0003 The Open Metadata Security Service org.odpi.openmetadata.metadatasecurity.samples.CocoPharmaServerSecurityConnector for server cocoMDS1 is initializing

```

**Comment by DimitriosMaimaris** [comment]
I start all OMAS's and the local repository graph in the same server and then calling the endpoints from Data Engine. The entities are created in the graph and the events are published on Kafka topic but then they are not published in the in memory topic as the other OMAS's do not process this event.

**Comment by mandy-chessell** [comment]
I will try to recreate this using the karma point management in Community Profile OMAS - then we can determine if the problem is in OMRS, connector or the OMASs.

**Comment by cmgrote** [comment]
Is the gist of this thread something worth covering as part of #1206? 😉

**Comment by mandy-chessell** [comment]
This is not about Kafka - it is about the passing of events inside a server.

**Comment by mandy-chessell** [comment]
I have run a number of tests and so has @popa-raluca and we are seeing events passing to the OMASs.  I will close for now and we can reopen if the problem reoccurs.
