### ISSUE TITLE
Method getTypeDefByName not working when server is configured with no local repository

### ISSUE THREAD

**Issue by ruxandraRosu** [odpi/egeria#1340]
In _EnterpriseOMRSMetadataCollection_.class method _getTypeDefByName_ is using activeTypes(that are the types in the local repo) instead of allTypes loaded by enterprise Connector querying all members.
512 -> TypeDef  result = super.filterTypeDefsByName(repositoryHelper.getActiveTypeDefs(), name);
Thus when server is configured with no local repo, the types are not recognized.

**Comment by mandy-chessell** [comment]
Picking this up as no-one working on it and causing problems

**Comment by mandy-chessell** [comment]
Fix is in following commit
https://github.com/mandy-chessell/egeria/commit/370f6aab793aecf4eb990ce0894b248fbcb7617a

**Comment by DimitriosMaimaris** [comment]
I checked the change you did Mandy and is still not getting the types when I am trying to retrieve them.  It gets them when I put allTypes.getTypeDefs() instead of repositoryHelper.getKnownAttributeTypeDefs().

**Comment by mandy-chessell** [comment]
Do you mean getKnownTypeDefs() rather than getKnownAttributeTypeDefs()?

**Comment by mandy-chessell** [comment]
I think this is fixed?  Please reopen if there is still a problem
