### ISSUE TITLE
Information View OMAS build process (question)

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1343]
Currently the Information View OMAS build process outputs a huge amount of debug information as it runs through the `org.odpi.openmetadata.accessservices.informationview.ColumnContextBuilderTest` suite.  It appears to be printing the entire debug log information / output for starting up a metadata repository and registering all of the open types (?)

Wondering if this is expected, and assuming it's necessary whether there's an option to disable all of the debug output?  I wouldn't expect anyone to review the 1000's of lines that are being output, and am wondering if it might speed up building from the command-line when running on battery power (ie. avoiding all of the screen output).

(Might be doing the same again for `org.odpi.openmetadata.accessservices.informationview.ReportCreationTest` as well?)

**Comment by ruxandraRosu** [comment]
Hi, I will check, I don't think I changed the debug level, but will double check. Thanks!

**Comment by cmgrote** [comment]
I'm not sure it's something new -- I suspect it might have been like that for a while...  Maybe there's something we can define as an option to Maven or the like to simply avoid it being printed (?)

**Comment by planetf1** [comment]
I agree with you... 

ideally the build log should be clean enough (by default) so one can clearly see high level progress + any issues. The current volume makes any warnings hard to spot, plus of course when running tests often warnings/errors are correct....

I've not looked at HOW, but I suspect it's a case of ensuring slf or similar is being used within the test cases with an appropriate logging level -- but note there are a few funnies with slf/build I hit when refactoring.

Adding this to build list for now, I think it's valid to persue. Any other comments?

**Comment by ruxandraRosu** [comment]
Hi,
I've added file logback-test.xml to classpath as descibed in https://logback.qos.ch/manual/configuration.html and configured there the log levels.

**Comment by ruxandraRosu** [comment]
logback-test.xml
