### ISSUE TITLE
Support OM types versioning 

### ISSUE THREAD

**Issue by ruxandraRosu** [odpi/egeria#1367]
Currently when changing the type (without increasing the version) the types are no longer resolved because of conflict with the locally stored type. We need to make sure the update and versioning of types will not break all the types and we are able to use them and the already existing entities.

**Comment by mandy-chessell** [comment]
This topic needs to be covered at 3 levels.

1) OMRS support for type versions
2) Repository support for type versions
3) OMAS coding patterns to support changes in type version (and new subtypes introdiced by vendors)

**Comment by mandy-chessell** [comment]
Currently the OMRS assumes only one version of a type is active in the cohort.  We should allow multiple versions. 

We should follow the convention that adding properties should just be a minor update. eg 1.0 to 1.1.  A delete of an attribute, or retype of an attribute is a major update - eg 1.1 -> 2.0.  

OMASs and Egeria Repositories should be written to support multiple versions of the type (and their subtypes) beting returned from repository connector requests and events.

**Comment by mandy-chessell** [comment]
This is a summary of a proposal that we discussed today.

1) We stop directly changing existing types now in the OpenMetadataTypes archive.
2) Any changes to types should be added via a TypeDef patch.  This patch is left open for a release.  It can be changed but the version number should be changed for each change that goes into master.
3) The version name should be updated in each patch using the follwoing rules - update major number if attribute deleted; update minor number if adding an attribute.  (The patch process does not allow an attribute's type to change.)

With the approach outlined above, it will not be possible for a developer to introduce a non-backwardly compatible change.

There are a number of changes that could be done to the OMRS to enable multiple versions of the types to be in use in a cohort.
1) The repository still only supports one version of a type
2) The type version is checked on each inbound reference copy.  The instance is only saved if version number is earlier or equal to local repository's version.
3) When instances are retrieved from the local repository, the local repository connector checks its type version and updates/saves a version that matches the local supported version.

**Comment by mandy-chessell** [comment]
The proposal outlined does not address the changes to the OMASs to support multiple type versions in play in the repository.

**Comment by cong78** [comment]
Hi Mandy, 
Regarding the patch mechanism, if the Type attribute is not allowed to change, but we do need to change one of the attributes, is that means we will to have both minor and major updates on that type? (Deleting old attribute and add new attribute at the same time)

**Comment by mandy-chessell** [comment]
You would need to define a new attribute.  It is not possible to change the type of an attibute since that would not be backward compatible.

**Comment by mandy-chessell** [comment]
To be clear you can not add a new attribute of the same name as one that has been deleted.

**Comment by mandy-chessell** [comment]
However if you deleted an attribute and added a different one in the same patch then it would just be a major update.

**Comment by cmgrote** [comment]
> To be clear you can not add a new attribute of the same name as one that has been deleted.

This raises a further interesting question: how / should we have some mechanism that ensures property names are not re-used across versions (eg. one that was used in v1 of a type, deleted in v2, and then added again (after various other changes) in v3.1?)

**Comment by mandy-chessell** [comment]
We can do that in the patch processing - when the types are loaded the base type and all of the patches are loaded one after the other.

**Comment by grahamwallis** [comment]
With regard to "_The type version is checked on each inbound reference copy. The instance is only saved if version number is earlier or equal to local repository's version_"....

If the repository is at 2.0 and is asked to save a reference copy at v1.1 that includes an attribute that was removed in 2.0, what should the repository do? Should it strip out any attributes it does not understand?

**Comment by mandy-chessell** [comment]
That is a good point - I don't think it should save the instance reference copy if it has an attribute from the past that the local repository does not support.  If the master repository subsequently deleted that attribute, then it can be saved.

What if the local repository retrieves an instance from its store which contains an attribute that is no longer valid?

If we are being consistent then if the instance is a reference copy, the local repository should just delete it.  If it is a master copy I would suggest that the deleted attribute should at the very least be ignored.  Should the local repository actually delete the attribute value from the store?  The benefit of doing this would be that the subsequent retrievals do not have to step over the obsolete attribute.  The disadvantage is that if its type was changed to a subtype that did include the attribute then the attribute could then be seen again.

**Comment by mandy-chessell** [comment]
One other proposal would be that all type changes should be included in their own PR along with the update to the UML.  This means it can be assessed by all OMAS owners and we are sure that all changes are accurately reflected in the type documentation.

**Comment by cmgrote** [comment]
> One other proposal would be that all type changes should be included in their own PR along with the update to the UML. This means it can be assessed by all OMAS owners and we are sure that all changes are accurately reflected in the type documentation.

I like this idea, as it should really call people's attention to the type change then (and have a "review" period in which to comment if they believe that it will have a significant impact, other points to be considered, etc)

**Comment by ruxandraRosu** [comment]
Hi,
The type validation doesn't seem to be in place anymore when creating an entity. I've updated the type of one property from string to int, the type was updated successfully, but I was able to create the entity with the old type(string). Before the latest changes, the attributes were validated.

**Comment by mandy-chessell** [comment]
In the example above the failure is that the type update should have failed as it is illegal to update the type of a property.

**Comment by mandy-chessell** [comment]
Should we fail the build if a property type is changed in the OpenMetadataTypeArchive class?

**Comment by cmgrote** [comment]
Sounds fair to me (assuming it's something we can put into the build & put out a meaningful error message about if it occurs)?

**Comment by mandy-chessell** [comment]
Yes - meaningful message is easy to do.  We can discuss it next week and if agreed I will will make the change.  This will make it clearer to new contributors what the rules are for maintaining the type system.  We already have error messages for duplicate guids and type names etc, so this will follow a similar pattern.

**Comment by cong78** [comment]
Hi @mandy-chessell a quick question on this issue: are we going to implement the versioning in 1.2 Egeria release?

**Comment by mandy-chessell** [comment]
@cong78 yes we plan to - see the milestone setting
