### ISSUE TITLE
Administration Services role clarification

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#137]
Highlighted portion below isn't clear:

"Administration Services drive the initialization of the OMRS at server startup plus access to the OMRS's internal status.  It relies on the OMAG Server to supply it with the configuration information to initialize the connectors it should use _and connectors with other open metadata servers._"

not certain if this should be:
"... It relies on the OMAG Server to supply it with the configuration information to initialize the connectors it should use _and connects with other open metadata servers._"

or:
"...It relies on the OMAG Server to supply it with the configuration information to initialize the connectors it should use _and connectors to other open metadata servers._"

(`open-metadata-implementation/repository-services/docs/README.md`)

**Comment by mandy-chessell** [comment]
Hello Chris,
Strictly speaking it should be "connections for connectors".  Then OMRS 
creates the connectors from the connections.  Here is some more detail...

"Administration Services drive the initialization of the OMRS subsystems 
at server startup, provide access to the OMRS's internal status and 
coordinate the orderly termination of OMRS when the open metadata services 
are deactivated.
OMRS's administration services are called by the server's administration 
services.   It is supplied with the configuration information it needs to 
perform the requested function.  This includes:
Connections for the connectors it should use.
Information about the local repository (if any).
Whether the enterprise repository services should be initialized.
Details of any cohorts it should join.


All the best
Mandy
___________________________________________
Mandy Chessell CBE FREng CEng FBCS
IBM Distinguished Engineer

Master Inventor
Member of the IBM Academy of Technology
Visiting Professor, Department of Computer Science, University of 
Sheffield

Email: mandy_chessell@uk.ibm.com
LinkedIn: http://www.linkedin.com/pub/mandy-chessell/22/897/a49

Assistant: Janet Brooks - jsbrooks12@uk.ibm.com

**Comment by cmgrote** [comment]
Thanks!  Added to PR #139.
