### ISSUE TITLE
Ranger docker image failing

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1372]
See https://jenkins.odpi.org/view/egeria-docker/job/egeria-ranger-maven-docker-stage-master/71/console
```
13:38:26 [INFO] Scanning for projects...
13:38:26 [ERROR] [ERROR] Some problems were encountered while processing the POMs:
13:38:26 [FATAL] Non-readable POM /w/workspace/egeria-ranger-maven-docker-stage-master/open-metadata-resources/open-metadata-deployment/docker/ranger: /w/workspace/egeria-ranger-maven-docker-stage-master/open-metadata-resources/open-metadata-deployment/docker/ranger (No such file or directory) @ 
13:38:26  @ 
13:38:26 [ERROR] The build could not read 1 project -> [Help 1]
13:38:26 org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
13:38:26 [FATAL] Non-readable POM /w/workspace/egeria-ranger-maven-docker-stage-master/open-metadata-resources/open-metadata-deployment/docker/ranger: /w/workspace/egeria-ranger-maven-docker-stage-master/open-metadata-resources/open-metadata-deployment/docker/ranger (No such file or directory) @ 
13:38:26 
13:38:26     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:383)
13:38:26     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)
13:38:26     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)
13:38:26     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)
13:38:26     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:507)
13:38:26     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)
13:38:26     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
13:38:26     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
13:38:26     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
13:38:26     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
13:38:27     at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
13:38:27     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
13:38:27     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
13:38:27     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
13:38:27     at java.lang.reflect.Method.invoke (Method.java:498)
13:38:27     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
13:38:27     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
13:38:27     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
13:38:27     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
13:38:27 [ERROR]   
13:38:27 [ERROR]   The project  (/w/workspace/egeria-ranger-maven-docker-stage-master/open-metadata-resources/open-metadata-deployment/docker/ranger) has 1 error
13:38:27 [ERROR]     Non-readable POM /w/workspace/egeria-ranger-maven-docker-stage-master/open-metadata-resources/open-metadata-deployment/docker/ranger: /w/workspace/egeria-ranger-maven-docker-stage-master/open-metadata-resources/open-metadata-deployment/docker/ranger (No such file or directory)
13:38:27 java.io.FileNotFoundException: /w/workspace/egeria-ranger-maven-docker-stage-master/open-metadata-resources/open-metadata-deployment/docker/ranger (No such file or directory)
13:38:27     at java.io.FileInputStream.open0 (Native Method)
```

**Comment by planetf1** [comment]
Looks like a bad pom

**Comment by cmgrote** [comment]
The Docker images have been re-organised a bit to split up the build-time vs. the run-time...  I had assumed that the changes would be picked up automatically, but seems like there's something hard-coded in our Jenkins pipeline regarding old paths (?)

**Comment by cmgrote** [comment]
Build images for Apache projects are now under `/open-metadata-resources/open-metadata-deployment/docker/build-images/apache/...` while the runtime images are retained at the "top-level" (`/open-metadata-resources/open-metadata-deployment/docker/...`)

The intention is:
- more clearly separate rare builds (`.../build-images/...`) from the runtime
    - against which we should be able to put more restrictive controls on triggering Docker image builds and pushes (ie. only when the `Dockerfile` under `.../build-images/...` changes do those images need to be re-built)
    - which also means these more clearly build once, but may be used as the source for multiple runtime images (eg. if we need other Ranger images than just the admin, with some other subset of build artefacts)
   - also allows cached images to be used for these build images, since they're the long-running ones that will rarely change this should significantly enhance build times (eg. via Maven) after the initial build
- the runtime images should now be pulling their build image starting points directly from Docker Hub (by default, though repo is parameterised to allow local builds if people want to venture that way)
- the ordering of the modules in the upper-level `pom` should ensure that the build images build before any runtime images (if driving the build purely from Maven)

**Comment by planetf1** [comment]
Yes, understand.. But noticed the builds were failing. I'm currently testing them and found the failure. I'll fix the egeria one first, then look at the others.

**Comment by cmgrote** [comment]
Give me a shout if you want more explanation on the changes / where things are now 😄

**Comment by planetf1** [comment]
Ok now ranger.. the reason for this failure is that there is no pom ... in the directory the build process is using ... because the directory is renamed.

The current process isn't ideal - as you said, a full maven build is fine as things are done in the right order, with the right references. The resource requirements being two high resulted in independent jenkins jobs being setup -- and one of those needs updating to address the directory change.

The atlas issue was down to (I think) the base image not being rebuilt at all - another challenge with the split.

However there are potential changes coming in the build pipeline infrastructure so I'm going to fix these up manually, raise an issue/PR for THIS ranger build... then we can look at moving forward when any new CI/CD infra evolves.

**Comment by planetf1** [comment]
fixed (by manually forcing a build of the base ranger image)
