### ISSUE TITLE
[documentation_interface] provide reference documentation that describes the external interface (both input and output)

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1383]
(This is required for lowest level **passing** for CII.)

The documentation of an external interface explains to an end-user or developer how to use it. This would include its application program interface (API) if the software has one. If it is a library, document the major classes/types and methods/functions that can be called. If it is a web application, define its URL interface (often its REST interface). If it is a command-line interface, document the parameters and options it supports. In many cases it's best if most of this documentation is automatically generated, so that this documentation stays synchronized with the software as it changes, but this isn't required. The project MAY use hypertext links to non-project material as documentation. Documentation MAY be automatically generated (where practical this is often the best way to do so). Documentation of a REST interface may be generated using Swagger/OpenAPI. Code interface documentation MAY be generated using tools such as JSDoc (JavaScript), ESDoc (JavaScript), pydoc (Python), devtools (R), pkgdown (R), and Doxygen (many). Merely having comments in implementation code is not sufficient to satisfy this criterion; there needs to be an easy way to see the information without reading through all the source code. If the project does not produce software, choose "not applicable" (N/A).

(see: https://github.com/coreinfrastructure/best-practices-badge/blob/master/doc/criteria.md#documentation_interface)

**Comment by planetf1** [comment]
See https://github.com/odpi/egeria/issues/1124 for swagger specifically.
