### ISSUE TITLE
[release_notes] provide descriptive release notes

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1384]
(This is required for lowest level **passing** for CII.)

The project MUST provide, in each release, release notes that are a human-readable summary of major changes in that release to help users determine if they should upgrade and what the upgrade impact will be. The release notes MUST NOT be the raw output of a version control log (e.g., the "git log" command results are not release notes). Projects whose results are not intended for reuse in multiple locations (such as the software for a single website or service) AND employ continuous delivery MAY select "N/A". (N/A allowed.) (Justification required for "N/A".) (URL required for "met".)

The release notes MAY be implemented in a variety of ways. Many projects provide them in a file named "NEWS", "CHANGELOG", or "ChangeLog", optionally with extensions such as ".txt", ".md", or ".html". Historically the term "change log" meant a log of every change, but to meet these criteria what is needed is a human-readable summary. The release notes MAY instead be provided by version control system mechanisms such as the GitHub Releases workflow.

(see: https://github.com/coreinfrastructure/best-practices-badge/blob/master/doc/criteria.md#release_notes)

These should include any CVEs resolved:
- The release notes MUST identify every publicly known vulnerability with a CVE assignment or similar that is fixed in each new release, unless users typically cannot practically update the software themselves. If there are no release notes or there have been no publicly known vulnerabilities, choose "not applicable" (N/A). (N/A allowed.) (Justification required for "N/A".) [release_notes_vulns]

(see: https://github.com/coreinfrastructure/best-practices-badge/blob/master/doc/criteria.md#release_notes_vulns)

**Comment by jmertic** [comment]
Looks like you've knocked this out with the bug referenced.

One thing that would be good is to do an announcement via the mailing list when a release is cut - not sure where the release process is defined.

**Comment by planetf1** [comment]
See also #2030 which adds a scan of CVEs to the build.

It does not in itself meet the requirement to document the *fixed* CVEs from one release to the next

useful improvement?

**Comment by planetf1** [comment]
#2030 was backed out of 1.2 due to build dependency issues. 
#2120 will attempt to reintroduce for 1.3
