### ISSUE TITLE
[vulnerability_report_process] define vulnerability reporting process

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1386]
(This is required for lowest level **passing** for CII.)

The project MUST publish the process for reporting vulnerabilities on the project site. (URL required for "met".)

E.g., a clearly designated mailing address on https://PROJECTSITE/security, often in the form security@example.org. This MAY be the same as its bug reporting process. Vulnerability reports MAY always be public, but many projects have a private vulnerability reporting mechanism.

If private vulnerability reports are supported, the project MUST include how to send the information in a way that is kept private. (N/A allowed.) (URL required for "met".) [vulnerability_report_private]

Examples include a private defect report submitted on the web using HTTPS (TLS) or an email encrypted using OpenPGP. If vulnerability reports are always public (so there are never private vulnerability reports), choose "not applicable" (N/A).
The project's initial response time for any vulnerability report received in the last 6 months MUST be less than or equal to 14 days. (N/A allowed.) [vulnerability_report_response]

(see: https://github.com/coreinfrastructure/best-practices-badge/blob/master/doc/criteria.md#vulnerability_report_process)

Furthermore (required for **silver** level):
The project MUST have a documented process for responding to vulnerability reports.

This is strongly related to vulnerability_report_process, which requires that there be a documented way to report vulnerabilities. It also related to vulnerability_report_response, which requires response to vulnerability reports within a certain time frame.

This is inspired by Apache Project Maturity Model QU30.

(see: https://github.com/coreinfrastructure/best-practices-badge/blob/master/doc/other.md#vulnerability_response_process)

**Comment by planetf1** [comment]
A few core questions here
 - Do we want to make all our vulnarability process public ?
 - If not we should publish/create an appropriate private list
 - either approach should be documented in our developer guide

**Comment by cmgrote** [comment]
It seems we could keep it private, which is fine by me, though honestly I think either approach is valid.  We could probably leverage GitHub's own "Security" section, to keep things integrated with the rest of the issues / PR / etc landscape?

**Comment by planetf1** [comment]
I don't think this is resolved yet as whilst some docs have been updated describing the process, we don't yet have the list referred to explicitly

**Comment by cmgrote** [comment]
@mandy-chessell mentioned some email list addresses / aliases, which I think @jmertic you may have setup...  Can either of you please advise the specific email list address we can use for folks outside the direct community to report potential security vulnerabilities they've discovered? 🙏 

I'll take care of updating the developer documentation accordingly.

Thanks! 🙂

**Comment by jmertic** [comment]
I setup egeria-security@odpi.org for sending in security issues - that forwards to the Egeria maintainers list which is private.
