### ISSUE TITLE
[delivery_mitm] releases must be delivered using a mechanism that counter MITM attacks

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1388]
(This is required for lowest level **passing** for CII.)

The project MUST use a delivery mechanism that counters MITM attacks. Using https or ssh+scp is acceptable.

An even stronger mechanism is releasing the software with digitally signed packages, since that mitigates attacks on the distribution system, but this only works if the users can be confident that the public keys for signatures are correct and if the users will actually check the signature.

(see: https://github.com/coreinfrastructure/best-practices-badge/blob/master/doc/criteria.md#delivery_mitm)

Furthermore (required for **silver** level):
The project MUST cryptographically sign releases of the project results intended for widespread use, and there MUST be a documented process explaining to users how they can obtain the public signing keys and verify the signature(s). The private key for these signature(s) MUST NOT be on site(s) used to directly distribute the software to the public.

The project results include both source code and any generated deliverables where applicable (e.g., executables, packages, and containers). Generated deliverables MAY be signed separately from source code. These MAY be implemented as signed git tags (using cryptographic digital signatures). Projects MAY provide generated results separately from tools like git, but in those cases, the separate results MUST be separately signed.

This provides protection from compromised distribution systems. The public key must be accessible so that recipients can check the signature. The private key must not be on sites(s) distributing the software to the public; that way, even if those sites are compromised, the signature cannot be altered. This is sometimes called "code signing". A common way to implement this is by using GPG to sign the code, for example, the GPG keys of every person who signs releases could be in the project README. Node.js implements this via GPG keys in the README, but note that in the criterion we are intentionally more general: Node.js Release Team

(see: https://github.com/coreinfrastructure/best-practices-badge/blob/master/doc/other.md#signed_releases)

**Comment by planetf1** [comment]
Our maven artifacts are digitally signed with an ODPi GPG key. However I don't know where the public key is distributed for verification.

@bramwelt - do you know?

**Comment by cmgrote** [comment]
I think this has been answered in the comments on #1415 -- repeating here for simplicity:

> Yes, keys are kept separate from the code for signing. For the previous releases artifacts were signed by keys stored in a signing server (Sigul) - Artifacts were passed to the signing server, then signatures were returned; and for this release they'll be signed by Bintray's site-wide [keypair](https://bintray.com/user/downloadSubjectPublicKey?username=bintray), which signs the artifacts as they're uploaded to the distribution repository.

> The key pair has the binary GPG public key. Looks like http://branchandbound.net/blog/security/2012/08/verify-dependencies-using-pgp/ covers how to then use to verify

**Comment by planetf1** [comment]
@cmgrote are you planning to document this? Do we need to specifically?

**Comment by cmgrote** [comment]
I think it is worth documenting -- happy to do it, unless you want to?  Just re-assign this issue to me if you want me to take care of it.

**Comment by planetf1** [comment]
Worth also noting that our GitHub releases of source code (from GitHub) are not specifically signed by us, though they are generated by GitHub.

**Comment by planetf1** [comment]
I will look at signing the next release as per https://wiki.debian.org/Creating%20signed%20GitHub%20releases

If it looks ok, will add to the release docs.
So leaving this here for now.

**Comment by planetf1** [comment]
@mandy-chessell  - believe we've passed l1 checklist so closing. Please re-open if you feel there are any further followups to do.
