### ISSUE TITLE
[vulnerabilities_fixed_60_days] all medium and high severity vulnerabilities must be resolved within 60 days

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1390]
(This is required for lowest level **passing** for CII.)

There MUST be no unpatched vulnerabilities of medium or high severity that have been publicly known for more than 60 days.

The vulnerability must be patched and released by the project itself (patches may be developed elsewhere). A vulnerability becomes publicly known (for this purpose) once it has a CVE with publicly released non-paywalled information (reported, for example, in the National Vulnerability Database) or when the project has been informed and the information has been released to the public (possibly by the project). A vulnerability is medium to high severity if its CVSS 2.0 base score is 4 or higher. Note: this means that users might be left vulnerable to all attackers worldwide for up to 60 days. This criterion is often much easier to meet than what Google recommends in Rebooting responsible disclosure, because Google recommends that the 60-day period start when the project is notified even if the report is not public. Also note that this badge criterion, like other criteria, applies to the individual project. Some projects are part of larger umbrella organizations or larger projects, possibly in multiple layers, and many projects feed their results to other organizations and projects as part of a potentially-complex supply chain. An individual project often cannot control the rest, but an individual project can work to release a vulnerability patch in a timely way. Therefore, we focus solely on the individual project's response time. Once a patch is available from the individual project, others can determine how to deal with the patch (e.g., they can update to the newer version or they can apply just the patch as a cherry-picked solution).

(see: https://github.com/coreinfrastructure/best-practices-badge/blob/master/doc/criteria.md#vulnerabilities_fixed_60_days)

**Comment by jmertic** [comment]
This is tied into https://github.com/odpi/egeria/issues/1386 - if you put together a security issue management process this would likely be taken care of.

**Comment by planetf1** [comment]
I can work on an initial draft to this & also extend to documenting in our scan processes (there is some already) both in the code (pmd/spotbugs), and externally (sonar cloud for code issues) and most specifically our CLM scans & OWASP build flag

**Comment by planetf1** [comment]
I think we have a process now, and don't currently have open CVEs. See #1386.
