### ISSUE TITLE
[input_validation] validate all inputs from potentially untrusted sources

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1400]
(This is required for **silver** status under CII.)

The project results MUST check all inputs from potentially untrusted sources to ensure they are valid (a whitelist), and reject invalid inputs, if there are any restrictions on the data at all.

The project results MUST check all inputs from potentially untrusted sources to ensure they are valid (a whitelist), and reject invalid inputs, if there are any restrictions on the data at all.

(see: https://github.com/coreinfrastructure/best-practices-badge/blob/master/doc/other.md#input_validation)

This was one of the areas picked up by Fortify scans -- suggest we continue to monitor through those to ensure appropriate input validation (avoiding code injection).

**Comment by mandy-chessell** [comment]
Most APIs validate input parameters - however I would like to have UTs or FVTs in place that means we can demonstrate this is true.

**Comment by cmgrote** [comment]
Whilst we often do basic validation, I'm not sure we're doing white-list based validation?  From scans (like Fortify), the underlying basis for this is likely to avoid the potential for injection: where users can send in data that has characters like '\n', special control characters, etc that could allow the input to go beyond the scope of what we mean to process (either executing arbitrary code unsuspectingly, or leaving the potential for log forging).

Issue needs to remain open, and I'd suggest we target specific risk areas from the areas identified by code analysis tools.
