### ISSUE TITLE
[dynamic_analysis_enable_assertions] include run-time assertions that are checked during dynamic analysis

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1407]
(This is required for **gold** status under CII.)

The software produced by the project MUST include many run-time assertions that are checked during dynamic analysis.

Assertions make dynamic analysis more effective, because they increase the number of problems (including vulnerabilities) that dynamic analysis can detect. Other sources also recommend the use of assertions. "Tip #33: If it Can't happen, use assertions to ensure that it won't." ("The Pragmatic Programmer" by Andrew Hunt and David Thomas, p. 122) The paper "Assessing the Relationship between Software Assertions and Code Quality: An Empirical Investigation" by Gunnar Kudrjavets, Nachi Nagappan, and Tom Ball, May 1, 2006, Technical report MSR-TR-2006-54, presented "... an empirical case study of two commercial software components at Microsoft Corporation. The developers of these components systematically employed assertions, which allowed us to investigate the relationship between software assertions and code quality... with an increase in the assertion density in a file there is a statistically significant decrease in fault density. Further, the usage of software assertions in these components found a large percentage of the faults in the bug database."

(see: https://github.com/coreinfrastructure/best-practices-badge/blob/master/doc/criteria.md#dynamic_analysis_enable_assertions)

**Comment by planetf1** [comment]
this depends on #1406
