### ISSUE TITLE
[small_tasks] clearly identify small tasks that can be performed by new or casual contributors

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1409]
(This is required for **gold** status under CII.)

The project MUST clearly identify small tasks that can be performed by new or casual contributors.

This identification is typically done by marking selected issues in an issue tracker with one or more tags the project uses for the purpose, e.g., up-for-grabs, first-timers-only, "Small fix", microtask, or IdealFirstBug. These new tasks need not involve adding functionality; they can be improving documentation, adding test cases, or anything else that aids the project and helps the contributor understand more about the project.

Identified small tasks make it easier for new potential contributors to become involved in a project, and projects with more contributors have an increased likelihood of continuing. Alluxio uses SMALLFIX and OWASP ZAP uses IdealFirstBug. This is related to criterion installation_development_quick.

(see: https://github.com/coreinfrastructure/best-practices-badge/blob/master/doc/other.md#small_tasks)

**Comment by jmertic** [comment]
Basically, add a few issues to this tag and you should be good to go...

https://github.com/odpi/egeria/issues?q=is%3Aissue+label%3A%22good+first+issue%22+is%3Aopen

We can also then showcase this better on the ODPi TSC page as well, for example on how Open Mainframe Project does this...

https://github.com/openmainframeproject/tac#tac-projects

**Comment by mandy-chessell** [comment]
Still needed
