### ISSUE TITLE
[require_2FA] require 2FA for developers changing a central repository

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1410]
(This is required for **gold** status under CII.)

The project MUST require two-factor authentication (2FA) for developers for changing a central repository or accessing sensitive data (such as private vulnerability reports). This 2FA mechanism MAY use mechanisms without cryptographic mechanisms such as SMS, though that is not recommended.

2FA is used by Node.js and the Linux kernel projects. See "Linux Kernel Git Repositories Add 2-Factor Authentication" by Kontin Ryabitsev and "Linux Foundation Protects Kernel Git Repositories With 2FA" by Eduard Kovacs.

(see: https://github.com/coreinfrastructure/best-practices-badge/blob/master/doc/other.md#require_2FA)

Furthermore:
The project's two-factor authentication (2FA) SHOULD use cryptographic mechanisms to prevent impersonation. Short Message Service (SMS) based 2FA, by itself, does not meet this criterion, since it is not encrypted. [secure_2FA]

A 2FA mechanism that meets this criterion would be a Time-based One-Time Password (TOTP) application that automatically generates an authentication code that changes after a certain period of time. Note that GitHub supports TOTP.

SMS is easier and lower cost for many people, but it also provides much weaker security. It has been argued that SMS isn't really 2FA at all; we permit it, because it's better than nothing, but we don't recommend it because of its weaknesses. So Hey You Should Stop Using Texts for Two-Factor Authentication

**Comment by planetf1** [comment]
Just for reference, this change was made Mon 2 May 2022
