### ISSUE TITLE
[test_branch_coverage80] ensure 80% branch coverage

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1413]
(This is required for **gold** status under CII.)

The project MUST have FLOSS automated test suite(s) that provide at least 80% branch coverage if there is at least one FLOSS tool that can measure this criterion in the selected language.

This adds another test coverage requirement, again requiring more thorough testing. A program with many one-armed "if" statements could achieve 100% statement coverage but only 50% branch coverage (if the tests only checked the "true" branches). Branch coverage is probably the second most common test coverage measure (after statement coverage), and is often added when a stricter measure of tests is used. Branch coverage is widely (but not universally) implemented.

(see: https://github.com/coreinfrastructure/best-practices-badge/blob/master/doc/other.md#test_branch_coverage80)

**Comment by mandy-chessell** [comment]
CII Badge
