### ISSUE TITLE
[hardened_site] harden project website, repo and downloads

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1415]
(This is required for **gold** status under CII.)

The project website, repository (if accessible via the web), and download site (if separate) MUST include key hardening headers with nonpermissive values.

(see: https://github.com/coreinfrastructure/best-practices-badge/blob/master/doc/other.md#hardened_site)

**Comment by cmgrote** [comment]
We may already be catering for this if we're signing our Maven releases, and Maven Central is where we expect people to obtain the releases.  I haven't read the details here, but this might help: http://www.sonatype.com/people/2010/01/how-to-generate-pgp-signatures-with-maven/

Again, I haven't investigated the detail, but an important consideration is usually that the keys used for verification are kept in a separate location from the released artefacts themselves.

**Comment by planetf1** [comment]
@bramwelt Can you confirm our keys are kept securely/seperate?

**Comment by bramwelt** [comment]
@planetf1 @cmgrote Yes, keys are kept separate from the code for signing. For the previous releases artifacts were signed by keys stored in a signing server (Sigul) - Artifacts were passed to the signing server, then signatures were returned; and for this release they'll be signed by Bintray's site-wide [keypair](https://bintray.com/user/downloadSubjectPublicKey?username=bintray), which signs the artifacts as they're uploaded to the distribution repository.

**Comment by cmgrote** [comment]
Just a question of addressing my own ignorance here, then, most likely...  Is there a common pattern by which someone can verify the downloaded artifact against that separate key, after having downloaded the artifact (to ensure no potential man-in-the-middle replacement of code in the artifact or the like)?

**Comment by planetf1** [comment]
@cmgrote The key pair link in the post my trevor above has the binary GPG public key. Looks like http://branchandbound.net/blog/security/2012/08/verify-dependencies-using-pgp/ covers how to then use to verify?

**Comment by cmgrote** [comment]
I believe we've met this one via GitHub itself (see results from https://securityheaders.com/?q=https%3A%2F%2Fgithub.com%2Fodpi%2Fegeria&followRedirects=on)

Specifically, it makes use of the following key hardening headers with nonpermissive values:

- `Strict-Transport-Security`
- `X-Frame-Options`
- `X-Content-Type-Options`
- `Content-Security-Policy`
- `X-XSS-Protection`

**Comment by planetf1** [comment]
@cmgrote it sounds like we're nearly there on this one and you're the expert :-) (removing myself)
