### ISSUE TITLE
[warnings] enable compiler warning flags and resolve any warnings

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1417]
(This is required for lowest level **passing** for CII.)

The project MUST enable one or more compiler warning flags, a "safe" language mode, or use a separate "linter" tool to look for code quality errors or common simple mistakes, if there is at least one FLOSS tool that can implement this criterion in the selected language.

Examples of compiler warning flags include gcc/clang "-Wall". Examples of a "safe" language mode include JavaScript "use strict" and perl5's "use warnings". A separate "linter" tool is simply a tool that examines the source code to look for code quality errors or common simple mistakes. These are typically enabled within the source code or build instructions.

"We routinely set compiler warning levels as high as possible. It doesn't make sense to waste time trying to find a problem that the compiler could find for you! We need to concentrate on the harder problems at hand." ("The Pragmatic Programmer" by Andrew Hunt and David Thomas, p. 91-92) "Tip 23: Always use Source Code Control. Always. Even if you are a single-person team on a one-week project." ("The Pragmatic Programmer" by Andrew Hunt and David Thomas, p. 88)

(see: https://github.com/coreinfrastructure/best-practices-badge/blob/master/doc/criteria.md#warnings)

Furthermore:
The project MUST address warnings. [warnings_fixed]

These are the warnings identified by the implementation of the warnings criterion. The project should fix warnings or mark them in the source code as false positives. Ideally there would be no warnings, but a project MAY accept some warnings (typically less than 1 warning per 100 lines or less than 10 warnings).

(see: https://github.com/coreinfrastructure/best-practices-badge/blob/master/doc/criteria.md#warnings_fixed)

**Comment by cmgrote** [comment]
I would assume this also applies to our build process (Maven), where we have a number of warnings along the lines of:

```
[INFO] --- maven-antrun-plugin:1.8:run (...) @ ... ---
[WARNING] Parameter tasks is deprecated, use target instead
```

```
[INFO] --- maven-jar-plugin:3.1.2:jar (...) @ ... ---
[WARNING] JAR will be empty - no content was marked for inclusion!
```

```
[INFO] --- maven-assembly-plugin:3.1.1:single (...) @ ... ---
[WARNING] Assembly file: /.../.../... is not a regular file (it may be a directory). It cannot be attached to the project build for installation or deployment.
```

and a few others related to deprecated method use, `npm install` (for Polymer?), missing JavaDoc bits, etc.

**Comment by planetf1** [comment]
Currently we:
 - enable some non standard compiler flags (ie for deprecated function). Though -X lint: has lots more options
 - run sonar (sonarcloud.io) against the code to detect common bugs and security issues
 - further augment this with spotbugs, findsecbugs & pmd for additional static analysis. This is available in the maven build as well as sonar reports
 
Optionally in the IDE
 - a developer can use 'error-prone' which can detect more bugs 
 - findbugs, pmd, sonar all also have plugins

It's probably worth documenting our current position & tools better (I'm happy to do this -- but not for the next 2 weeks). We can then discuss improvements.

**Comment by planetf1** [comment]
Also related is the output from our unit tests - where a lot of warnings are actually test passes - can be confusing to anyone just reading the logs.

**Comment by planetf1** [comment]
There are some docs on pmd etc in the developer documentation

**Comment by planetf1** [comment]
Reading the requirement I think the principle is good, but if we document and justify our current approach, and have a plan for continual improvement, that would seem to be appropriate to pass...

**Comment by cmgrote** [comment]
Most of those are separate areas in CII (ie. static and dynamic code analysis ala #1406 and #1407 (there are specific ones for static, but I think we already cover so haven't added an issue to track them), and automated test suites ala #1395 #1396 and #1397) -- this is specifically about the compile / build-time warnings, as I understand it.

**Comment by planetf1** [comment]
So the main additional flag we currently use is -Xlint:deprecated . There are a number of issues open to address deprecations, add exclusions, and look at failing the build if warnings appear.

There are a number of other flags - for example in 1.8 (222) openjdk:
```
  -Xlint:{all,auxiliaryclass,cast,classfile,deprecation,dep-ann,divzero,empty,fallthrough,finally,options,overloads,overrides,path,processing,rawtypes,serial,static,try,unchecked,varargs,-auxiliaryclass,-cast,-classfile,-deprecation,-dep-ann,-divzero,-empty,-fallthrough,-finally,-options,-overloads,-overrides,-path,-processing,-rawtypes,-serial,-static,-try,-unchecked,-varargs,none} Enable or disable specific warnings
```

Enabling is easy (though these are not guaranteed to work with all compilers). I'm not aware we can fail the build - and the more flags enabled the harder this will get. We could add a scan post-build to verify perhaps

**Comment by planetf1** [comment]
I have added a PR to enable further lint checks. By itself this doesn't satisfy this requirement, but it is an enabler. We still need to action the additional warnings (around 308) reported.

there's quite a few warnings on generics - http://www.informit.com/articles/article.aspx?p=2861454&seqNum=2 has some tips.

**Comment by planetf1** [comment]
The next stages are probably to
 - advertise the change to the team . I will do this on slack once PR is merged, and also on the functionality call if the change is approved.
 - update the developer contribution guidelines. I can add this into the PR...
 - Raise specific issues on hotter areas
 - Document our acceptance criteria for the CI badge

**Comment by planetf1** [comment]
The logs are now generated. will target some cleanup for the next release

**Comment by planetf1** [comment]
I think this is effectively done now. The logs are generated in the build, and issues are open for all remaining errors - mostly deprecations with a few unchecked exceptions. I think we can say this requirement is complete

I have no access to the checklists (that I know of?) so assigning to @mandy-chessell to update & close out? (cc: @cmgrote )
