### ISSUE TITLE
Change zoneMembership into Classification

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1459]
Rather than having `zoneMembership` as a property on `Asset`, have it as a `Classification` linked to `Asset`, which still has an array / list of qualifiedNames of the zones of which that the asset is a member.

Rationale:

- zones can be "mastered" somewhere other than the home repository of the asset itself
- zones will no longer a "special case", but act like any other classification

**Comment by mandy-chessell** [comment]
We also agreed to do the same with owner/ownerType.  This then removes all of the governance attributes from outside of the Asset entity.  So if an asset comes from a repository that does not directly support Egeria's governance attibutes they can still be attached and the asset governed.
