### ISSUE TITLE
Egeria monthly workshop documentation

### ISSUE THREAD

**Issue by cong78** [odpi/egeria#1467]
In order to have better documentation of what we have discussed during the workshop, it would be really helpful for us to keep them in the git repo and use as reference on any decisions that we have made. 

This issue will be referenced for the PRs of adding Egeria Workshop documentation in the developer-resources module.

**Comment by cmgrote** [comment]
> In order to have better documentation of what we have discussed during the workshop, it would be really helpful for us to keep them in the git repo and use as reference on any decisions that we have made.

I wasn't on for that part of the discussion, but just wanted to be sure this doesn't supersede creating more granular issues for individual topics that were agreed and need to have some work done to address them (whether fixes, changes, new functionality, etc)?  I wouldn't want to try to track all changes against some large piece of documentation, or it won't be very clear what progress we're making / still remains to be made, and collaborating on further sub-decisions against each granular item won't really be possible...

**Comment by cong78** [comment]
Hi @cmgrote you are right it does not mean we are going to replace any particular issues or any topics we have discussed. It is just used for adding general workshop notes as not everyone of us is involved in every topic during the workshop. So the purpose is just to track what we have discussed during the workshop and some results or questions from it so we can have a memory on it. 

Maybe it is not a practical approach to create an issue for adding the notes of workshop. What do you think?

**Comment by cmgrote** [comment]
> Maybe it is not a practical approach to create an issue for adding the notes of workshop. What do you think?

I think it's great to have the notes of each workshop, no debate there -- but indeed, I'm not sure what the added value of an issue is to ensure that those notes are entered.  They should be easy enough to find just based on the folder structure of the repository when they're committed (?)

As long as we're still planning to create separate (granular) issues for each topic that needs some action, then that gives us the fine-grained traceability and progress monitor-ability(?)

**Comment by cong78** [comment]
> > Maybe it is not a practical approach to create an issue for adding the notes of workshop. What do you think?
> 
> I think it's great to have the notes of each workshop, no debate there -- but indeed, I'm not sure what the added value of an issue is to ensure that those notes are entered. They should be easy enough to find just based on the folder structure of the repository when they're committed (?)
> 
> As long as we're still planning to create separate (granular) issues for each topic that needs some action, then that gives us the fine-grained traceability and progress monitor-ability(?)

Yes I agree with you. It would be wise to keep the issue on lower granular level so it can be clear and resolvable for anyone. In this case I will close this issue and still add the notes. Thanks!
