### ISSUE TITLE
cocoMDS1 not started in docker-compose notebook environment

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1484]
In the docker compose 'lab' notebook environment we create 3 egeria server platforms
 - egeriacore
 - egeriadl
 - egeriadev

In the notebooks
 - metadata-server-config uses egeria core to perform all configuration tasks (including of cocoMDS1)
 - managing-servers points to egeriadl to start cocoMDS1

This fails with a 404, and a debug exception reporting that the config file is not found.

This is because in the docker-compose / k8s case each platform has it's own private filesystem

If all three platforms are run locally they share the local filesystem, and so all platforms can see all the configuration files....

Suggested fixes
 a) As a tactical issue update the docker-compose environment to utilize a shared filesystem for configuration
 b) Investigate best approaches to share config in k8s case (filesystem, maps) & consider how updates to systems are managed across the lifecycle -- not just for a tutorial (++ devops)

**Comment by mandy-chessell** [comment]
Nigel and I talked about this today and we have a cunning plan.  The OMAG Server Platform supports a POST method called:
```
/open-metadata/admin-services/users/{userId}/servers/{serverName}/configuration
```
that takes a configuration document in the request body.  It stores the supplied configuration for the requested server.

I could add another REST API endpoint to the platform to POST a configuration document from one OMAG Server Platform to another.  Under the covers it would call the store configuration endpoint shown above on the destination platform.

This new REST API endpoint would be a POST with the following URL:
```
/open-metadata/admin-services/users/{userId}/servers/{serverName}/configuration/deploy
```
It would have a request body containing the destination OMAG Server Platform's root url.
This could be null in which case the serverURLRoot property from the server's configuration document is used.

When this new endpoint is called, the receiving OMAG Server Platform reads the configuration document for the requested server, determines the destination OMAG Server Platform and calls it to store the config document.  The same userId is used on the request to store the configuration.

This enhancement means an organization can manage configuration documents as a proper software artifact.  For example they could have an administration platform in their dev environment.  Configuration documents can be prepared and tested.  Once they are approved they can be checked into a document or config management repository, retrieved in a devOps pipeline and pushed to the production platform.   Maintenance changes the configuration document can also be pushed to the production platform in a single command.

**Comment by planetf1** [comment]
Just seen the changes. The new section on distrubuting the config looks super. docker-compose loads the latest notebooks (it pulls from git on creation), but I need to rebuild the base image of egeria for the new services. I'll build my own images, but for others, In fact the build process will do this during the day. I'll then verify the compose images and raise any issues found.

**Comment by planetf1** [comment]
This is now fixed thanks.
