### ISSUE TITLE
TEX is not passing logged in user

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1489]
If OMAG Server is setup with security, and one logs into the Egeria UI with user 'faith', 
that userid is not passed to the OMAG server by TEX

The error on the server is
```
egeriacore_1  | 2019-09-04 09:23:58.460 DEBUG 1 --- [nio-8080-exec-4] o.o.o.c.m.f.OMAGServerInstanceErrorCode  : ==> OMAGServerInstanceErrorCode.getMessage([cocoMDS1, anon]): The OMAG Server cocoMDS1 is not available to service a request from user anon
```

This only occurs when metadata security is configured as per the 'metadata-server-config' notebook. If security is disabled (DELETE) then this error does not occur.

**Comment by grahamwallis** [comment]
OK - sorry about that.

I thought I had got the userId all the way through - it gets from the browser to the app (automatically int he request context) and I pull it out of the request context in the TEX controller - but it looks like I should be adding the userId to the Connection immediately after getting the getDefaultLocalRepositoryRemoteConnection from the ConnectorConfigurationFactory and prior to calling the ConnectorBroker.

@mandy-chessell - Hi Mandy - Is that correct?

**Comment by mandy-chessell** [comment]
I think this is the userId that is passed on the each API call - eg

`        public abstract TypeDefGallery getAllTypes(`**String  userId**`) throws ...`

**Comment by mandy-chessell** [comment]
The userId that goes in the connection is the npa serverUserId that is used to secure the request.

**Comment by grahamwallis** [comment]
OK - I think I am doing the former but not the latter. Presumably that is what's causing the effect that Nigel is seeing?

**Comment by mandy-chessell** [comment]
Ah - I have just looked at the debug statement that Nigel included - the problem is that TEX is using the deprecated `get-metadata-collection-id()` method.  This does not have a userId parameter and so the OMRS defaults the userId to `anon`.  The Coco Pharmaceuticals security module does not permit the `anon` userId.

There is a new version of the get-metadata-collection-id method that includes the userId.  This should resolve the problem.

**Comment by grahamwallis** [comment]
Thank you - I seem to recall we discussed that a long time ago. Apologies - I had forgotten

**Comment by planetf1** [comment]
Thanks for investigating - refer also to #1490 . 

But to pick up on another point mandy made -- the connection from TEX to the backend server should be using the NPA userid for the connection itself. And presumably password?

ie in the notebooks the server is configured for

mdrServerUserId   = "cocoMDS1npa"
mdrServerPassword = "cocoMDS1passw0rd"

but the notes refer to only used for a TLS connection?

 The UI currently offers no way to configure this at all?. (for all the UI components). At a minimum a property would be handy (as then it can be set for development or even in containers via the environment though) 

This is addition to the userId passed in get-metadata-collection-id which is for the end user context (and will suffer until #1490 is addressed or ldap is used)

**Comment by planetf1** [comment]
cc: @moyabrannan

**Comment by mandy-chessell** [comment]
I am not quite following the comment above.

Egeria only use the server userId and password together for adding userId/password to HTTP header.  The server userid is also used on calls to egeria apis initiated in the server - eg as a result of an inbound event.

This security information will need to go in the config docs for UI tenants - this is the work that David is doing.  The UI will work without it as long as the server is not requiring security info in the HTTP header.

**Comment by mandy-chessell** [comment]
I have added a quick fix to TypeExplorerController to pass the userId on getMetadataCollectionId.  This is an interim fix.  I need to create an OMRS Java client that can call both the local and enterprise repository services.  Then TEX does not need to use the OMRSRESTConnector.

**Comment by mandy-chessell** [comment]
The userId is coming through - the server is outputting this message:
```
Thu Sep 05 14:18:27 BST 2019 cocoMDS2 OPEN-METADATA-SECURITY-0006 User faith is not authorized to issue a request to server cocoMDS2
```
We just need the fix to #1490 to sync up the userIds in the UI with the userIds in the server's security module.

**Comment by grahamwallis** [comment]
With regard to the NPA - TEX (and REX) will need to set the NPA in the connection, but I am not sure where a UI cpt can discover the NPA from. @bogdan-sava @davidradl - any ideas?

**Comment by planetf1** [comment]
This will need to be in the UI configuration? Note: - this issue is closed, so may be best to open new issue to track. More generally the UI config needs refactoring in any case - for example the asset management UI uses spring properties to set the URl for omas (and only offers 1 - even though differing omass could be on different platforms) ad servername, whilst tex prompts (and in any case goes into omrs)

**Comment by mandy-chessell** [comment]
The NPA would be in the tenant's configuration document - just like the OMAGG server
