### ISSUE TITLE
Getting started with Egeria using notebooks in docker - writeup

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1492]
To make it easier for developers and architects to understand & get some hands-on with Egeria we have developed
 - A series of Jupyter notebooks with explanations and python code fragments
 - A supporting runtime environment - 2 variations: docker-compose & k8s

In this blog post I will document the initial getting started step using docker compose & running the first notebook

The blog will NOT cover further notebooks, detailed explanation of the notebooks, nor will it touch on k8s.
Followon entries will cover - using the k8s version, running in the cloud,  other k8s charts, using openshift

*IF LOGGED ON* to linux foundation wordpress, the current draft is at https://odpilf.lfprojects.linuxfoundation.org/?p=91210&preview=true&dm=bypass

**Comment by cmgrote** [comment]
Just trying to review it to provide any feedback, but while I can see it as "Pending" I can't seem to open it up to read it (?)  The direct link you provided still gives me a 404 as well -- even after I'm logged in...

**Comment by jmertic** [comment]
Not sure, will create an LF IT request for this to see what's going on.

**Comment by planetf1** [comment]
I may well have done the wrong thing in creating the draft. @cmgrote will ping via slack
It's very brief.. is held up currently on the code not quite working correctly. It's been a useful validation exercise of our notebook/coco scenario. One the code is all working I'll push the review.

**Comment by planetf1** [comment]
There are other 'challenges' with the setup too
 - 'new post' from within the page editor results in a 404/not found
 - bad CSS for preformatted has been mentioned (though whilst an existing block cannot be transformed to a 'code' block, creating a new block and then cut/paste works (thanks @cmgrote)
 - preview from within the page editor results in a 404/not found
 - it's unclear what 'submit for review' does. Where does it go? Can we have egeria maintainers automatically notified? Make it easy to establish a team workflow?

**Comment by jmertic** [comment]
Thanks @planetf1!

Can you confirm that 2 and 5 above work better now?

For the others.

- (1) and (3) I believe are related to permissions. Let me sync with the team on this
- (4) -> https://en.blog.wordpress.com/2007/07/10/submit-for-review/

**Comment by jmertic** [comment]
@planetf1 I think we fixed (1) and (3) now - can you test and confirm?

**Comment by cmgrote** [comment]
My quick feedback now that I see the post (with my clone trick 😉):

- In "Running the notebooks", you might want to also give a tip that you can use `SHIFT-Enter` to run each paragraph / block, to avoid the need to constantly click the mouse on the play button.
- Your final point about opening an issue: a) you could link directly to a New Issue page (`https://github.com/odpi/egeria/issues/new`), or b) you should indicate that the button actually says "New Issue" (at the moment you've stated "Open").

**Comment by planetf1** [comment]
thanks for the feedback

**Comment by planetf1** [comment]
Updates made to the draft - the blog is as short as possible - If you can see it, the draft is at https://odpilf.lfprojects.linuxfoundation.org/?p=91210&preview=true&preview_id=91210&preview_nonce=04dabe9a8a&post_format=standard&_thumbnail_id=-1&dm=bypass

**Comment by planetf1** [comment]
The blog is IMO ready to post, other than the template issues. Consulting ODPi team for advice and notifying I am ready to publish.

**Comment by planetf1** [comment]
The CSS for code blocks has been updated which addresses the scrolling issue.
Blog will go live on public website around midday EDT tomorrow.
On that basis am now closing
