### ISSUE TITLE
remove (empty) server configuration UI

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1499]
We have a server-configuration-user-interface directly under user-interfaces. No source is contained, but we do have a module defined in the pom. It gets built into a no-op jar as part of the build process.

Since we've had no code here ever I would suggest we entirely remove this component as it just adds clutter and potentially confusion

**Comment by bogdan-sava** [comment]
README says: The server Configuration User Interface provides the administration user
interface for an open metadata server.
If I remember right, it was designed to be a UI tool for rest configurations that we currently do with postman. 
On the other hand, it can be a view on the UI, accessible if the user has proper  role.
@mandy-chessell what do you think?

**Comment by planetf1** [comment]
A change in directory will break the egeria container build as referenced in /Users/jonesn/src/egeria/open-metadata-resources/open-metadata-deployment/docker/egeria

I intend to change the build to be more resiliant (by using our packaged distro) but until then, if a PR is created I suggest we do not merge until the associated change has been made & tested in the Dockerfile

There are also assemblies in open-metadata-distribution/open-metadata-assemblies/src/main/assemblies . These should include the UI, but do not. My intent was to fix as part of the work mentioned above.

But the change sounds sensible

**Comment by planetf1** [comment]
this has been done as part of ui refactoring
