### ISSUE TITLE
Building egeria within IntelliJ can fail on new install

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1500]
Scenario
 - new install of intellij
 - new import of egeria project
 - mvn is configured as 3.6.2 in intellij
 - java is configured as 11.0.4 (openjdk hotspot) in intellij
 - mvn clean install at command line uses the same jvm/mvn and runs fine
 - using the intellij maven plugin and typing 'mvn clean install' fails with
```
Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.1:jar (attach-javadocs) on project open-connector-framework: MavenReportException: Error while generating Javadoc: Unable to find javadoc command: The environment variable JAVA_HOME is not correctly set.
```

This is because the environment within intellij is a little different to the cli

The following fragment should fix for the IDE without breaking other usage - added in the configuration for the javadoc plugin
```
<javadocExecutable>${java.home}/bin/javadoc</javadocExecutable>

```
This is more noticeable now javadoc is part of the standard lifecycle (from install)

If a global JAVA_HOME is setup, the UI ay inherit and find javadoc, however since IntelliJ supports switching between JDKs as part of the project definition this could end up using the wrong version (or in this case not find it). java.home however is set correctly.. so the above fix provides for consistent results.

**Comment by planetf1** [comment]
After some research
 - It is tricky to set the javadoc executable correctly. This is because 'java.home' gets set to the java environment /executing/ maven itself, not necessarily the compiler. Whilst in my IDE it was an SDK, in the build environment it was a JRE - and in any case could be the wrong version.
 - all intellij does is call maven. The relevant java environment set for the shell will prevail - NOT the version set in the intellij gui
 - this change was indeed introduced by the enabling of javadoc
 - it likely will only affect those trying to coordinate multiple environments through a tool like 'jenv' (my case)
 - if using jenv, the following commands will address the issue:

```
➜  egeria git:(master) java -version
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)
➜  egeria git:(master) jenv global 11.0
➜  egeria git:(master) echo $JAVA_HOME

➜  egeria git:(master) jenv enable-plugin maven
maven plugin activated
➜  egeria git:(master) jenv enable-plugin export
You may restart your session to activate jenv export plugin echo export plugin activated
➜  egeria git:(master) echo $JAVA_HOME
/Users/jonesn/.jenv/versions/11.0
```

Whilst in more simple environments, make sure JAVA_HOME is indeed set to a valid JDK, which is best practice in any case

Therefore closing this, but with notes to help anyone else who may hit this issue.

**Comment by mandy-chessell** [comment]
I am hitting this same problem while setting up a new machine and not seeing how to fix it

**Comment by mandy-chessell** [comment]
<img width="439" alt="Screenshot 2019-09-08 at 11 12 38" src="https://user-images.githubusercontent.com/12354195/64486813-ffe1f000-d229-11e9-84c9-ccd0683b30bf.png">

Also seeing this

**Comment by planetf1** [comment]
Re-opening as there are clearly issues here -- at a minimum we should have instructions to support developers.

In the case of javadoc failing with JAVA_HOME not found, make sure JAVA_HOME is set to a valid *jdk* in ~/.bash_profile (if using MacOS bash), ~/.bashrc (if using homebrew bash), ~/.zshrc (if using homebrew zsh) etc. I think catalina will default to zsh for new users. The IDE does not seem to set it, even though the SDK is configured. I will add more notes on this as part of any 'fix'

For dependency resolution, I did not see the above error despite reinstalling intellij / making new fork on 2 machines but I can guess the issue is that both of those dependencies are 'synthetic' - they are actually created, and inserted into a local maven repo, as part of the build process itself. Once 'mvn clean install' has run I expect they will go away. It's not clear how to fix them in the GUI only as maven is the 'authoritative'  definition of what to do, but IntelliJ isn't quite following it. A note may be useful to warn new users - can you confirm if it went away after a 'mvn clean install' ?

**Comment by planetf1** [comment]
updates made (pending pr)
