### ISSUE TITLE
Create repository proxy for cocoMDS5

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#1527]
CocoMDS5 in the Coco Pharmaceuticals labs is a metadata repository that is attached to an external vendor's ETL tools that is managing the copying of data from/between Coco Pharmaceutical's business systems into the data lake.

This issue is to create a repository proxy that is preloaded with canned metadata representing the business systems and the lineage of the data movement between them and the data lake.

**Comment by mandy-chessell** [comment]
Step one is to introduce a read-only repository.  This is like the inmemory repository but does not support create/update/delete of metadata.  This means it is safe to use it in a production scenario to host static content from, say Open Metadata Archives.

**Comment by planetf1** [comment]
This will be very useful . Any required data files should now be available on the platform if added to the full assembly. Hopefully that is sufficient. if more is needed please @mention or raise an issue :-)
