### ISSUE TITLE
Add deprecation ability to type definitions

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1528]
Per discussion, driven by changes documented in #1317 as one example, it would be good to add the possibility to track a deprecation status against the type definitions -- both at the attribute level and on the broader type definitions (entity, relationship, etc) themselves.

**Comment by mandy-chessell** [comment]
Moved to 1.3 as agreed on team call

**Comment by mandy-chessell** [comment]
It is now possible to mark an attribute as deprecated.  There are two follow on pieces of work:
* mark the attributes that we currently have documented as deprecated in the comments.
* design utilities and changes to the OMRS property services to manage deprecated properties.
