### ISSUE TITLE
Unable to Print Blog entry

### ISSUE THREAD

**Issue by CDaRip2U** [odpi/egeria#1532]
The header/banner from the project seems to visualize OVER the text on pages when you try to print the blog post page.  I have attached a example pdf showing this issue. 

[ODPiBlogPrintIssue.pdf](https://github.com/odpi/egeria/files/3605801/ODPiBlogPrintIssue.pdf)

**Comment by planetf1** [comment]
I can confirm I see this with chrome, but not with safari (file->print in both cases)

**Comment by jmertic** [comment]
Raised this with our web team to review. Thanks for catching this!

**Comment by planetf1** [comment]
Tested - and this problem seems fixed now.
