### ISSUE TITLE
Blog - Meet ODPi Egeria the new Open Source Metadata Standard

### ISSUE THREAD

**Issue by moyabrannan** [odpi/egeria#1533]
Blog covers:
-The Problem with data…
-Introducing Egeria…
-Egeria’s Savvy Skills
-Why Open Source? 
-Egeria the Water Nymph

My next blog is a follow on from this which dives into Egeria's Savvy Skills

**Comment by mandy-chessell** [comment]
Blogg published here: https://www.odpi.org/blog/egeria/2019/09/23/meet-odpi-egeria-the-new-open-source-metadata-standard
