### ISSUE TITLE
Blog - Egeria’s Seven Savvy Skills

### ISSUE THREAD

**Issue by moyabrannan** [odpi/egeria#1534]
1.	Ultimate Source and Destination for data assets, or Full Lineage 
2.	Provenance of Metadata 
3.	Time Travel Through the Data 
4.	Data Awareness and Notifications 
5.	Governance, Access and Security 
6.	Understanding for All, through Business 
7.	Collaboration

**Comment by planetf1** [comment]
done? could add link & close?

**Comment by planetf1** [comment]
done? could add link & close?

**Comment by mandy-chessell** [comment]
I think so - https://www.odpi.org/blog/egeria/2019/09/30/my-favorite-seven-savvy-skills-in-egeria
