### ISSUE TITLE
Blog - Data Lake Data Asset Access Maturity Patterns

### ISSUE THREAD

**Issue by moyabrannan** [odpi/egeria#1535]
Data Lake Asset Access Maturity Model
Level 0 - No Metadata Standard - No Security
Level 1 - Simple Access Control -  using NFS file system security 
Level 2 – Policy Based Access with an Enforcement Point
Level 3 – Metadata Glossary based Policy Access
Level 4 – Context based Data Access

**Comment by planetf1** [comment]
can we move this to 1.3
