### ISSUE TITLE
Problems using kafka embedded in Helm charts

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1540]
It seems that when using the Kafka (+ Zookeeper) chart dependencies that are embedded in the `vdc` Helm chart, while the necessary topics are created, no messages seem to be produced into the bus.  That is, `kafka-topics --list` shows all of the expected topics, but `kafka-console-consumer --from-beginning --topic ...` against the OMRS topic does not list any messages, despite servers having gone through their registration process.

This seems to have knock-on effects when trying to get various members to intercommunicate across the cohort (ie. they don't recognise that there are any other members of the cohort).

Using a k8s-external Kafka bus seems to be fine -- so this seems limited to the Kafka bus that's embedded via the Helm chart dependencies.

**Comment by planetf1** [comment]
Thanks for spotting.

I've been working with the lab docker-compose environment where kafka is working fine.
However when I checked the k8s version of the lab, I get the issue you describe above.

I tried to use the same base containers for zookeeper and bitnami that I used in the compose environment. However I was unable to get them to listen properly. I then switched to use the ready-made bitnami kafka chart (similar to confluent) which seems to work properly and is better supported.

I've run through the open metadata labs configuring, managing servers .. and cohort configuration and verified through audit logs, checking messages, & the cohort queries that we now have proper communication.

I will open a PR to merge this change & suggest we do the same change for the vdc chart. The pattern is very similar, but the charts look better (they are used in production by many people)

**Comment by planetf1** [comment]
Note that for the labs I've left them with persistence disabled for now (which isn't a big deal for the tutorial environment) but there remain outstanding github issues to enable persistence, especially for the vdc chart

**Comment by planetf1** [comment]
I've created a PR to propose a change to use the bitnami charts in the vdc chart too.

Unfortunately this was a little more tricky as we already have instances of kafka & zookeeper. Shouldnt be a problem but I hit a clash on naming -- which the base chart controls. Similar property names (kafka & zookeeper-service). In theory an 'alias' in requirements.yaml fixes this, but it doesn't work properly with 2nd level dependencies (something we hit challenges with the confluent charts). I've therefore done some (rough) refactoring.

The docs etc are not updated at this point -- but I wanted to share the chart updates for review. We could then merge if they look ok, and fix up the docs in the next PR./

I was able to run through the full *default* (no solr/igc) vdc setup using internal kafka and verify that there was at least some communication in the cohort ie:

2019-09-14 16:44:53.785  INFO 1 --- [.coco.OMRSTopic] o.o.o.r.auditlog.OMRSAuditLog            : myserver OMRS-AUDIT-0110 A new registration request has been received for cohort coco from server apacheatlas that hosts metadata collection 4763c8e9-d00f-4294-92b2-9ae7836f024e
Sat Sep 14 16:44:53 GMT 2019 myserver OMRS-AUDIT-0110 A new registration request has been received for cohort coco from server apacheatlas that hosts metadata collection 4763c8e9-d00f-4294-92b2-9ae7836f024e

**Comment by planetf1** [comment]
the default configuration for bitnami kafka is development-esque with respect to scalability/clustering. however they provide a more production ready values.yaml if needed, including docs on security. this chart should be superior to cp-kafka.

**Comment by cmgrote** [comment]
Confirmed fixed now that we have bitnami charts 👍

**Comment by planetf1** [comment]
Super to hear. It looked good when I tried it. Didn't get the chance to complete the docs, so thanks for putting in that PR to complete the tidying up. The bitnami charts look a lot better.
