### ISSUE TITLE
Ui tenancy make the config file active 

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#1569]
Ui tenancy make the config file active #1568

**Comment by davidradl** [comment]
I suspect this will involve starting the server as well.

**Comment by mandy-chessell** [comment]
I would suggest that the UI platform uses the same approach as the OMAG Server Platform.   The admin calls can be issued to any instance of the platform.  This creates the configuration document that is stored in the destination by the configuration store connector.

There is also an admin call to deploy configuration documents to other platform instances.

When the tenant is to be started, an instance call is issued to the desired platform.  It starts the tenant and uses the configuration document to work out which UI components (services) are activated in the tenant.

**Comment by davidradl** [comment]
not relevant after #2577
