### ISSUE TITLE
tenancy ui amend the UI urls to include the serverName   

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#1571]
tenancy ui amend the UI urls to include the serverName  and use the appropriate server name in omas calls

**Comment by davidradl** [comment]
I am thinking about how to do this and see a couple of options: 
1) We have the server name in the request for all resources , js and rest end points. The myapp.js currently routes based on the name of the view- this would need to be chnaged to not use a global variable and somehow cope with the preceding url segment that would be a tenant id.

2) Keep the resource , js end points the same as these are static resources. Specify the tenant id on the login page as a dropdown of available tenants (unless we think a tenant should not be aware of the names of the other tenants). We then store the tentant id in a session storage and use it on all url calls. the rest calls would need to include the tentant id - either in the url or in the http header (as with the token). If at some stage we want to use custom resources then we could include the tenant id in the url - I assume those resources would live in a tenant specific url. We currently obtain resources without using security - which might be an issue.

I am thinking option 2 could work better. What do you think @bogdan-sava @grahamwallis @mandy-chessell ?
 
all the best, David.

**Comment by mandy-chessell** [comment]
Hello David - you are right, the tenant should not be aware of other tenants

**Comment by mandy-chessell** [comment]
I agree the tenant id should be in the URL.  All of the tenant specific resources/connectors should be picked up from their config document.

**Comment by davidradl** [comment]
@mandy-chessell I found https://dzone.com/articles/multi-tenancy-in-the-api-world-made-easy, which has the tenantid as a http header parameter. Is this an option? In this case the user would specify the tenant on the logon page. This would be reasonably simple to implement.

I am unsure how to get tomcat to server web pages if the first url segment is the tenantid, maybe we need to configure the tenantid as a context path. The url is also used to route to the subpages so the <app-location> routing logic would probably need to be changed. I could put the tenantid in the url for the rest calls that the browser makes or pick it up from the http header (which we do for the  token). I notice http://tomcat.10.x6.nabble.com/multi-tenant-web-app-td4997645.html  
@bogdan-sava any thoughts on how to cope with the tenant id in the url for web page serving.

**Comment by planetf1** [comment]
As a slight aside ... In some deployments I would expect a desire to offer urls like
 acme.bigcloud.com - quite apart from including in the path
 
I've barely touched nginx (very common for production deployment, including k8s but also regular) but it seems it's easy to take a subdomain from a URL, and then map that in a proxied request to a new http header.

That way if we went with the http header parm, a provider could I think manage the subdomain routing externally, whilst in our code we'd just use the header.

That may be easier than managing the url subdomains within egeria -- which may cause more code impact/spring rerouting/filtering ?

**Comment by davidradl** [comment]
please keep open
