### ISSUE TITLE
OMAS-DATA_ENGINE-0003 incorrect audit message formatting

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1578]
```
Tue Sep 17 12:16:37 GMT 2019 cocoMDS1 OMAS-DATA-ENGINE-0003 The Data Engine Open Metadata Access Service (OMAS) is shutting down its instance for server {0}
```
{0} should contain the name of the server being shut down

**Comment by planetf1** [comment]
Since the server name is already contained in the message, one option is simply to remove the parm reference

**Comment by planetf1** [comment]
though other messages leave it in place

**Comment by popa-raluca** [comment]
Resolved with Data Engine OMAS - implement update functionality #1808
