### ISSUE TITLE
TEX fails in k8s tutorial environment (with security enabled)

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1579]
In the tutorial environment, TEX fails when pointed to:
http://lab-egeria-lake-service:8080
cocoMDS4

The same endpoint/servername works with the Glossary UI (once fix for #1577 is applied)

TEX ui reports the generia failure, but the back-end server reports:
```
Tue Sep 17 12:46:27 GMT 2019 cocoMDS4 OPEN-METADATA-SECURITY-0006 User anon is not authorized to issue a request to server cocoMDS4
```

This suggests we have another case where userid is not being passed

The current container image version is based off
```
bash-4.4$ head git.log
commit 5d3a483401544c587713fad6beba01388710a2a8
Merge: cc259aea6 65c4feb3b
Author: David Radley <39792797+davidradl@users.noreply.github.com>
Date:   Mon Sep 16 11:28:22 2019 +0100

    Merge pull request #1567 from davidradl/subjectarea

    #1566 add subject area design doc and story board

commit 65c4feb3b0c60968e508843ff3f2f3966e61cc7e
```

I couldn't see any relevant later commits from https://github.com/odpi/egeria/commits/master

**Comment by planetf1** [comment]
The current code appears to try and catch the UserNotAuthorized exception - to specifically report the fact the user isn't authorized. This logic doesn't appear to be triggered in this case.

Likely need to debug within the container to understand exact code path

**Comment by planetf1** [comment]
Code was changed to
```
                metadataCollectionId = metadataCollection.getMetadataCollectionId(userId);

```
but still seem to be getting error

**Comment by grahamwallis** [comment]
Please see PR #1775

**Comment by planetf1** [comment]
Now working fine in k8s after #1775
