### ISSUE TITLE
tenancy ui add omas specific endpoints

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#1583]
As the back end server might not support the omas that we want to call - then we should allow omas specific servers to be specified, that override the default backend omas server

**Comment by mandy-chessell** [comment]
A UI tenant is supporting a community of users.  These users may be specialists and only need some of the OMASs.  We know which OMASs are needed from their profiles.  The governance servers deployed to support them also have well-known OMAS requirements.  This means it is possible to determine what OMASs to deploy for the metadata server supporting this community.

An additional OMAS can be configured on a metadata server with a single REST call.  This means if an OMAS is found to be missing, it is easy to rectify.

Ultimately the UI Platform supports all of the UI functions for all of the OMASs and the governance servers.  Therefore insisting that all possible OMASs are available to a deployment of the UI tenant is undesirable.

Each metadata server supports an enterprise view of the metadata.  This is built up from the content of the members for the list of cohorts that the metadata server is connected to.  So it is possible that two metadata servers will each support a different enterprise view.   If a UI tenant is connected to more than one metadata repository, that are in turn connected to different cohorts, the view of metadata returned to the different OMASs by the different metadata repositories will be inconsistent.

We should support the notion that the metadata server supporting a UI is correctly configured for its connected user community.  IE correct configuration is where the connected metadata server supports all of the OMASs needed by the user community and the linked governance servers.  I do not think we should allow a UI tenant to connect to more than one metadata server.

**Comment by planetf1** [comment]
This makes sense - it means we do need to make it clear in the doc/readme for deployment, and also through appropriate error messages/logs in any cases where the required OMASs are not available

**Comment by davidradl** [comment]
closing as this is not needed
