### ISSUE TITLE
Decide if we need to use OpenMetadataPlatformSecurityVerifier for ui admin calls

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#1584]
OpenMetadataPlatformSecurityVerifier

**Comment by mandy-chessell** [comment]
The short answer to this is "of course" :)

This connector determines who is allowed to issue platform service calls to the UI platform.  Examples of these are admin calls, diagnostic calls and the ability to start and stop tenants. 
Only approved users should be allowed to do this.

I think the open question is whether the same connector interface supported by the OMAG Server Platform could be used by the UI Platform.  If it could be the same then it would be an advantage to a cloud provider to have the same control apply to both platforms consistently.

**Comment by mandy-chessell** [comment]
This function will be automatically include in the UI platform when we implement #1792

**Comment by davidradl** [comment]
Added to UI  in #1939
