### ISSUE TITLE
Data Platform OMAS incorrect shutdown

### ISSUE THREAD

**Issue by bogdan-sava** [odpi/egeria#1587]
Calling temporary deactivate a server with Data Platform OMAS active fails.
Message is:
`OMAG-ADMIN-500-001 Method deactivateTemporarily for OMAG server omas returned an unexpected exception of org.odpi.openmetadata.commonservices.ffdc.exceptions.PropertyServerException with message OMAG-PLATFORM-400-002 The OMAG server omas has been requested to shutdown but the following services are still running: [Data Platform OMAS]`

sutdown method of FataEngineAdmin is called but it is not removed from OMAGServerInstance.serviceInstanceMap

**Comment by cong78** [comment]
Hi Bogdan I will try to fix it as soon as possible.

**Comment by cong78** [comment]
@bogdan-sava  Do you mind to check if the bug is fixed? :)

**Comment by cong78** [comment]
As the linked PR was merged, I will close this issue.
