### ISSUE TITLE
Dependency issue of Data Platform Service server side with generic API implementation

### ISSUE THREAD

**Issue by cong78** [odpi/egeria#1593]
Currently the Data Platform Service under Governance Server is adding the dependency from Cassandra Connector, which is not architecturally correct and may introduce potential security and build issues. One of them is an existing issue #1519 that Cassandra maven dependency version is old with an insecure version of Guava.

As the next step, there should be a generic interface in API module from Data Platform Service side for any potential data platforms who want to plug in. Which is showed in the following drawing:
![data-platform-services copy](https://user-images.githubusercontent.com/11947525/65242462-54b51e80-dae6-11e9-88fc-862d627a5055.png)

For this issue, there are following tasks should be implemented: 
1. Refactoring of Data Platform Service Server module and remove the Cassandra Dependency. 
2. Implementation of generic interface in Data Platform Service API module.
3. Implementation of Cassandra Connector to adapt this new generic interface.

**Comment by mandy-chessell** [comment]
Thank you @cong78

**Comment by mandy-chessell** [comment]
One other point to look at is the ConnectorConfigurationFactory.  This should not include references to specific connector implementations (except for the core connecctors for OMRS).

The method `getDataPlatformConnection` has the connector provider class name is passed in as a string - but then towards the end, it is ignored and cassandra provider is used to create the connector type.  This means the connection returned is always for cassandra.

**Comment by cong78** [comment]
For Apache Cassandra, we also need to build a data-store-connector to retrieve the Connection Object of Cassandra Assets.

**Comment by mandy-chessell** [comment]
The Cassandra data-store-connector instance is for accessing data on cassandra.  An instance of this connector is created by the ConnectorBroker using the Connection object attached to the Cassandra Asset.  This is done in the Asset Connumer's program.

The Cassandra data-store-connector is different from the Cassandra metadata extractor connector that runs in the Data Platform server.

**Comment by cong78** [comment]
> This is done in the Asset Connumer's program.

Is that means the Asset Consumer OMAS will create the connection object for Cassandra data-store-connector instance ?

**Comment by mandy-chessell** [comment]
The Asset Consumer OMAS is responsible for creating the **connector** instance.  It uses the Connection object attached to the Asset when the Asset is created.   The Data Platform server needs to create the Connection for the Cassandra data-store-connector for each Cassandra Asset it creates.  This Connection object is linked to the Asset

**Comment by cong78** [comment]
> The Data Platform server needs to create the Connection for the Cassandra data-store-connector for each Cassandra Asset it creates.
For `Cassandra data store connector` and `Cassandra metadata extractor connector`, can I put them together in one module? Like what you did for Kafka topic connector. 
Or I have to put `Cassandra data store connector` under `data-store-connectors` and `Cassandra metadata extractor connector` under `governance-deamon-connectors`?

**Comment by mandy-chessell** [comment]
It would be better to have them in different modules (in the places you suggest) because they are used in very different cirumstances.  If they are in the two places they will be easier to find because they will be with connectors used in similar circumstances

**Comment by cong78** [comment]
> The Asset Consumer OMAS is responsible for creating the **connector** instance.

Hi Mandy I am a bit struggling on implementing the logic of `Cassandra data store connector `and `Cassandra metadata extractor connector`. I have done the Data Platform OMAS client implementation as well as the Data Platform Service Generic API module for extracting metadata. 

I assume during the Data Platform Governance Server initialisation, the generic connector should be initialised by calling the data platform configuration with specific connector provider. And that connector provider should be `Cassandra metadata extractor connector`.

And for the initialisation of `Cassandra data store connector `, do I configure it inside of the `Cassandra metadata extractor connector`? So when a Cassandra new asset has been created, it will attach the `Cassandra data store connector` connection object and send to Data Platform OMAS.  Then I assume the Asset Consumer OMAS clients can retrieve the Cassandra asset by looking for the Cassandra connection object. 

Am I making sense?

**Comment by mandy-chessell** [comment]
Hello @cong78,
The generic metadata extractor connector is an API and base class that sits in the data platform server's API module along with the base class for the connector provider.  The cassandra metadata extractor connector and provider extends these base classes and are located in their own module under "adapters".

The data platform governance server has a Connection object for the cassandra metadata extractor connector in its configuration document.  During its initialization, it calls the ConnectorBroker, passing the Connection object.  The ConnectorBroker returns an instance of the cassandra metadata extractor connector and begins to receive information about new cassandra schemas.  Each cassandra schema results in a new Asset object linked to both a Connection object and SchemaType object being stored in the metadata repository via calls to the Data Platform OMAS client.

The Connection object links to a ConnectorType and an Endpoint object.  The ConnectorType includes the fully qualified Java class name of the connector provider for the cassandra data store connector.  The endpoint has the network address of Cassandra plus information about the specific schema.

The SchemaType describes the structure of the Cassandra schema.  So it will have SchemaAttributes etc linked to it.

When an API such as the Asset Catalog OMAS locates a cassandra asset of interest, it retrieves the Asset object, Schema Type and Connection.  The UI application (or end user application) then passes either the Asset GUID, or ConnectionGUID to the Asset Consumer OMAS client.  This has the connector broker in it.  It looks up the connection object and creates an instance of the Cassandra data store connector.  The user application can then use the connector to access both the data in cassandra and the metadata about the asset in the metadata repository.

**Comment by cong78** [comment]
> Each cassandra schema results in a new Asset object linked to both a Connection object and SchemaType object being stored in the metadata repository via calls to the Data Platform OMAS client.

Does this call has to be happened in the Data Platform Governance Server side? Or Can I call initialise the new Data Platform client in the `Cassandra metadata extractor connector` to send schema changes directly as well?

**Comment by mandy-chessell** [comment]
The `Cassandra metadata extractor connector` should have a method where the DataPlatform OMAS client is passed to it.  The reason for doing this is that it then does not need to knw the server URL root and server name where the OMAS is running.

**Comment by mandy-chessell** [comment]
Still work to do
