### ISSUE TITLE
SecurityServiceConnector interface and base classes should be under consuming component

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#1601]
The interface for the `SecurityServiceConnector` is in the `ranger-connector` module.  It should be in the `security-sync-services` along with base classes for the connector and connector provider.  The ranger connector (correctly located under adapters) should then depend on this.

The reason it is important that the connector interfaces are located with the consuming module rather than one of the connector implementations is to avoid technologies called from connector implementations from being pulling onto the OMAG Server Platform when they are not in use.  Today, the security-sync-services depend on the ranger-connector which brings in the ranger libraries into our stack - these libraries are being flagged in the scanning report.  It would be good to ensure that the ranger libraries are only pulled into the server platform if there is a security sync server configured to call ranger.

The `SecurityServiceConnector` interface could do with some Javadoc as well :)

**Comment by mandy-chessell** [comment]
A related problem is found in the ConnectorConfigurationFactory in that the ranger connector is being explicitly set up so it is not possible to request a different connector implementation.  In addition, this class is used in the Admin Services in the OMAG platform so by accessing the ranger connector in this class, ranger is pulled into the platform.

**Comment by planetf1** [comment]
Agree with the core comment. This is in addition .. 
One technique to consider is that if we become wary of distributing any of our modules with ranger is we could select the dependency as 'provided' - this means we can use at compile time, but at runtime the broader environment will need to provide the right libraries.

This may add another step for the deployer, and it does mean the deployer would need to know about acceptable versions, but it's a way to avoid runtime contamination by libraries.

That being said if the change describe in the opening is made, the exposure is much narrower in any case

I've not tested (yet?)_ but suspect this may clean up the security scan too, and places the onus on the deployer to get this right.

This could also be used for other technologis such as derby/gaian. connectors in #1606

**Comment by mandy-chessell** [comment]
This still needs to be fixed
