### ISSUE TITLE
Open Lineage Services calling JanusGraph and pals directly

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#1602]
The `open-lineage-services-server` module has dependencies on:
- janusgraph-core
- gremlin-core
- tinkergraph-gremlin
- lucene-analyzers-common

All of these external technologies should be called from connectors that have generic APIs to allow other technologies to be swapped in by changing the connector implementation.

The connector based architecture we have in Egeria is critical to ensuring our main libraries only have the minimal dependencies.  It then loads only the connectors it needs from the Connection objects found in the configuration.

**Comment by DimitriosMaimaris** [comment]
There is an open pull request for the fix of the issue @mandy-chessell  can you please review it.
