### ISSUE TITLE
ViewGeneratorConnector should be under consuming component

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#1606]
The Interface and base classes for the ViewGeneratorConnector and Provider should be under the consuming component `virtualization-services-api`.  This is so that the virtualizer governance server does not have dependencies on Derby.

For clarity, the DerbyConnector should probably be called the ViewGeneratorDerbyConnector. This is to distinguish it from a derby connector that would be used by an application to acccess data in Apache Derby.

**Comment by mandy-chessell** [comment]
In addition, the `getVirtualizationSolutionConnection()` method in the `ConnectorConfigurationFactory` has hard-coded package names for the derby connector.
It should be independent of the connector implementation with the specifics passed in on the parameters.

**Comment by innerTide** [comment]
Hi Mandy, I'm working on this issue. I've created a new package viewgenerator at [virtualization-services-api](https://github.com/odpi/egeria/tree/master/open-metadata-implementation/governance-servers/virtualization-services/virtualization-services-api/src/main/java) and moved derby connector the the upper level of directory as ViewGeneratorDerbyConnector in view-generator-connectors. Is this what you suggest in the first reply? Thanks in advance for your clarification!
