### ISSUE TITLE
Develop connector for ElasticSearch

### ISSUE THREAD

**Issue by jan-frommann** [odpi/egeria#1613]
Based on how ES represents and stores documents/data, it probably makes most sense, to develop this as a data store connector. Not entirely sure about the adequate types yet (TabularColumn and TabularSchemaType or DocumentSchemaType and DocumentSchemaAttribute?).

Being able to derive the data lineage of the documents stored in ES would be a nice addition (Potentially using FileBeat and/or MetricBeat?)!

**Comment by mandy-chessell** [comment]
Assigned to @cong78  to ensure we don't forget it.  However @jan-frommann if you want to take it on then please assign it to yourself.

**Comment by cong78** [comment]
> Assigned to @cong78 to ensure we don't forget it. However @jan-frommann if you want to take it on then please assign it to yourself.

Hi Mandy, I will start investigating the ES about any metadata APIs or libraries that we can use. Last week we also had a talk with ING Tech Infra that they also might need this functionality.

**Comment by jan-frommann** [comment]
Hi Mandy, Hi Cong,

I'd love to assign this to me, but how do I do that?

Thanks in advance! 

Jan

**Comment by cong78** [comment]
> Hi Mandy, Hi Cong,
> 
> I'd love to assign this to me, but how do I do that?
> 
> Thanks in advance!
> 
> Jan

Hi Jan,

In Egeria we have a concept of Open Connector Framework (OCF) - see the open-connector-framework module [https://github.com/odpi/egeria/blob/master/open-metadata-implementation/frameworks/open-connector-framework/README.md](url)

It is an open standard that everyone can develop their own connectors and then communicate with Egeria. 
If you are looking for an example you can check out Kafka Connector [https://github.com/odpi/egeria/tree/master/open-metadata-implementation/adapters/open-connectors/event-bus-connectors/open-metadata-topic-connectors/kafka-open-metadata-topic-connector](url) or Cassandra Metadata Extractor Connector that currently I am working on [https://github.com/odpi/egeria/tree/master/open-metadata-implementation/adapters/open-connectors/data-store-connectors/cassandra-data-store-connector](url)

But as a first step, I will recommend you to read  a design documentation about how to build a connector or governance server for external technologies that want to interact with Egeria. :)
[https://github.com/odpi/egeria/tree/master/open-metadata-implementation/governance-servers/docs/design](url)

Let me know if you have any questions. 

Cheers,

Cong

**Comment by jan-frommann** [comment]
Hi Cong,
Thanks a lot, for the valuable information!
I'm actually just the messenger. I'm working closely with a team of developers, that will ultimately do the heavy lifting.
If you don't mind, I will use you as an additional contact, in case we have question to make sure, we're aligned with the main project.

Cheers,

Jan

**Comment by cong78** [comment]
> If you don't mind, I will use you as an additional contact, in case we have question to make sure, we're aligned with the main project.

Yes sure and if they have any questions they are also welcomed to join the Developer call every Thursday morning we are more than happy to answer any questions. :)

**Comment by mandy-chessell** [comment]
Work still going on
