### ISSUE TITLE
Provide clickable links between notebooks in tutorials (for example the readme 1st)

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1631]
Should be possible to create links from one notebook to another

We may need to add hostname of the jupyter server as a variable (docker, kubernetes), or relative links may work

Opening for investigation.

**Comment by planetf1** [comment]
Actually very easy

Use an example like
```
[click](egeria-server-config.ipynb)
```
from the readme.1st notebook.
cc: @mandy-chessell

**Comment by cmgrote** [comment]
See #1634 for an initial application of these to the `read-me-first.ipynb`.
