### ISSUE TITLE
Unable to checkout egeria code on Windows PC

### ISSUE THREAD

**Issue by m-steen** [odpi/egeria#1632]
It has become impossible to checkout the egeria source code from github on a Windows PC due to filenames/paths being too long. Below are the errors and warnings given when I checkout.

$ git clone https://github.com/odpi/egeria.git
Cloning into 'egeria'...
remote: Enumerating objects: 961, done.
remote: Counting objects: 100% (961/961), done.
remote: Compressing objects: 100% (401/401), done.
remote: Total 112817 (delta 259), reused 804 (delta 181), pack-reused 111856
Receiving objects: 100% (112817/112817), 72.74 MiB | 20.25 MiB/s, done.
Resolving deltas: 100% (66780/66780), done.
error: unable to create file open-metadata-implementation/adapters/open-connectors/event-bus-connectors/open-metadata-topic-connectors/inmemory-open-metadata-topic-connector/src/main/java/org/odpi/openmetadata/adapters/eventbus/topic/inmemory/InMemoryOpenMetadataTopicConnector.java: Filename too long
error: unable to create file open-metadata-implementation/adapters/open-connectors/event-bus-connectors/open-metadata-topic-connectors/inmemory-open-metadata-topic-connector/src/main/java/org/odpi/openmetadata/adapters/eventbus/topic/inmemory/InMemoryOpenMetadataTopicProvider.java: Filename too long
error: unable to create file open-metadata-implementation/adapters/open-connectors/event-bus-connectors/open-metadata-topic-connectors/kafka-open-metadata-topic-connector/src/main/java/org/odpi/openmetadata/adapters/eventbus/topic/kafka/KafkaOpenMetadataEventConsumerConfiguration.java: Filename too long
error: unable to create file open-metadata-implementation/adapters/open-connectors/event-bus-connectors/open-metadata-topic-connectors/kafka-open-metadata-topic-connector/src/main/java/org/odpi/openmetadata/adapters/eventbus/topic/kafka/KafkaOpenMetadataEventConsumerProperty.java: Filename too long
error: unable to create file open-metadata-implementation/adapters/open-connectors/event-bus-connectors/open-metadata-topic-connectors/kafka-open-metadata-topic-connector/src/main/java/org/odpi/openmetadata/adapters/eventbus/topic/kafka/KafkaOpenMetadataTopicConnectorAuditCode.java: Filename too long
error: unable to create file open-metadata-implementation/adapters/open-connectors/event-bus-connectors/open-metadata-topic-connectors/kafka-open-metadata-topic-connector/src/main/java/org/odpi/openmetadata/adapters/eventbus/topic/kafka/KafkaOpenMetadataTopicConnectorErrorCode.java: Filename too long
error: unable to create file open-metadata-implementation/adapters/open-connectors/governance-daemon-connectors/data-platform-connectors/cassandra-open-metadata-connector/src/main/java/org/odpi/openmetadata/adapters/connectors/cassandra/auditlog/CassandraConnectorAuditCode.java: Filename too long
fatal: cannot create directory at 'open-metadata-implementation/adapters/open-connectors/governance-daemon-connectors/security-officer-connectors/security-officer-tag-connector/src/main/java/org/odpi/openmetadata/openconnector/governancedarmonconnectors/securityofficerconnectors': Filename too long
warning: Clone succeeded, but checkout failed.

**Comment by planetf1** [comment]
See https://github.com/odpi/egeria/blob/master/Community-Guide.md 'Important additional setup for WIndows users'

In Summary you need to issue
```
git config --system core.longpaths true
```
Do let me know if this doesn't work (or works) or indeed if you get any other issues on WIndows

Note also that these days the WSL layer is improving, and the latest WSL2 provides a very unix like/interesting environment with a full linux kernel.

It's a limitation of git on windows.

**Comment by planetf1** [comment]
May I also suggest that if you just want to learn about & experiment with egeria in a easier environment, we have tutorials now available - see https://github.com/odpi/egeria/tree/master/open-metadata-resources/open-metadata-labs .

**Comment by planetf1** [comment]
please reopen if this doesn't work or if you have further difficulties/need advice
