### ISSUE TITLE
Switch egeria builds over to Azure pipelines

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1652]
Agreed at face2face egeria meeting 2 Oct that we are happy to
 * Make the jfrog artifactory our source for snapshots 
 * Make the Azure builds the source for our built artifacts ie
 -> Use the Java 8 pipeline to publish to jfrog
 -> Use the azure docker builds to push to dockerhub / stop the jenkins builds from going to dockerhub
 -> Make the azure java 8/11 builds mandatory
 -> across all our repositories

But
 * leave the jenkins builds active for now (except docker)
 * Change to non mandatory
 * leave the sonarcloud and nexus clm in place (move to azure or equiv when ready)

Across all our repos ...

cc: @bramwelt @cmgrote @mandy-chessell

**Comment by bramwelt** [comment]
@planetf1 Glad to hear you all have been happy with the work! Did you agree on a specific date for doing a cutover, or should we just choose a day? There are three things that need to change:

1. Switching the required status checks in branch protections from Jenkins to AZP maven verify jobs - As I don't have rights on the Github org that's something the Egeria team will need to do.
2. Add a 'Service Connection' for the ODPI Dockerhub Org to AZP (that's on me)
3. Updating the Docker jobs to use the service connection and change the repo parameter to push to the right organization.

Since 2 and 3 can be done without impacting things, I'll put a PR up shortly and someone can approve/merge when a time/date is decided.

**Comment by bramwelt** [comment]
Oh, and if someone could submit a [ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/2/create/38) to disable the Jenkins docker jobs, and verify they're off before switching to the AZP ones, that would be appreciated. :smile:

**Comment by planetf1** [comment]
We basically agreed ASAP :-)

1. I don't have access to the github repo configuration for Egeria. I'm not sure @mandy-chessell does either, I think it was the LF build team/jm that had this?
2.  thanks
3. It's been merged

* I'll open up a ticket to disable the jenkins job

We also have the sonarcloud/Nexus IQ processes which are currently kicked off by jenkins. Whilst not time critical, I assume they will be moving also - last we chatted there was some discussion about whether they were still the most appropriate tools, though we do need that functionality.

**Comment by planetf1** [comment]
Jenkins ticket opened - https://jira.linuxfoundation.org/servicedesk/customer/portal/2/IT-17837

**Comment by planetf1** [comment]
Also opened https://jira.linuxfoundation.org/servicedesk/customer/portal/2/IT-17838 to request support team flip the switch on azp/jenkins for mandatory status checks - we discussed leaving jenkins active for a short while just in case. I'm thinking let's leave them until we get through our release process.

See https://jira.linuxfoundation.org/servicedesk/customer/portal/2/IT-17838

On a related topic, who can update the description of Egeria in AZP? Currently we have nothing?

**Comment by planetf1** [comment]
Reopening as we still have a few activities to complete on this.

**Comment by bramwelt** [comment]
The AZP jobs have been switch to be required, and the docker jobs disabled - So both those support requests should be closed out (I'll update them first with some final comments).

> We also have the sonarcloud/Nexus IQ processes which are currently kicked off by jenkins. Whilst not time critical, I assume they will be moving also - last we chatted there was some discussion about whether they were still the most appropriate tools, though we do need that functionality.

Working on these now. The Sonar job should be ready to go today, and the CLM one looks pretty straight forwards. I expect those to be finished/merged by EOW. 

> On a related topic, who can update the description of Egeria in AZP? Currently we have nothing?

I added the description from egeria.odpi.org and the tags from the Github repository to AZP for you.

**Comment by planetf1** [comment]
@bramwellt - we are seeing that the PR verify step for Sonar has been re-activated.
For example in https://github.com/odpi/egeria/pull/1741

Since our merge job uses the java profile, whilst the PR check is (and can only??) use javascript profile our results end up being very erratic.

Additionally the PR check validates recent code, but not that particular PR, so until we've got our sonar results in a better state I think we need to :
 - Run sonar after merge (java profile)
 - disable the sonar check on PRs

I'm not sure where the error got introduced, perhaps in changing the egeria project definition(s) on github? Not checked the connector repos too

**Comment by bramwelt** [comment]
@planetf1 I noticed that this morning. I believe it's because I connected the SonarCloud org to the Github org, which isn't explicitly needed to run the checks. I've removed it for now, so hopefully things will look more consistent.

**Comment by planetf1** [comment]
thanks. - updated PR now looks normal.

**Comment by planetf1** [comment]
@bramwelt I think it could now be time to discontinue the jenkins builds -- at least for regular PRs, since the too frequent 'X' become confusion, and azure is running at least as well 

Are there any other changes you think we need to make before removing them from the PRs?
I'm thinking we should not decommission completely quite yet, but stop verification?

**Comment by bramwelt** [comment]
@planetf1 Shouldn't be a problem; We'll get them disabled today and will hold off on decom till you give the go-ahead. :)

Still working with JFrog to track down the SNAPSHOT issue, making minor progress: will forward you updates when I have them.

**Comment by planetf1** [comment]
Another observation with the 1.1 release - though we trigger the azure pipelines build on PR creation, the checks are not mandatory, but optional.

Can we get this updated so that the egeria-release-* branches have the same protection as master?

**Comment by bramwelt** [comment]
@planetf1 I didn't setup branch protections for the 1.1 release branch, but I do see they're there now.

The node issue should be temporary. The `frontend-maven-plugin` downloads nodejs and npm binaries as part of it's install phase from the nodejs.org site - Sometimes this fails either due to networking, or the site not returning all the whole binary, which is what causes the errors.

We can mitigate this by proxying the binaries in Artifactory (that way they're cached) and telling the plugin to grab them from Artifactory instead of directly from nodejs.org.

For verify jobs you should be able to click the 'rerun' on the checks page of the PR for the one that failed, and for merges ...well that should have worked :confused: - I retrigged the [build](https://dev.azure.com/ODPi/Egeria/_build/results?buildId=1482&view=logs&j=3712e2db-5985-53a6-7458-42565b9e5a6a) and it said 'Canceled' and ran for <1 second. Clicking `Run new` and passing the failed commit ID seems to have started a new [build](https://dev.azure.com/ODPi/Egeria/_build/results?buildId=1500&view=results) though...

**Comment by bramwelt** [comment]
I've put up #1910 to address the node/npm failures.

**Comment by planetf1** [comment]
Thanks - that should boost reliability. For branch protections, I asked @mandy-chessell to make that change today so should now be done.

For kicking off a build - any idea on why the re-run didn't work?

**Comment by bramwelt** [comment]
I'm not sure. We may need to raise a support ticket with Azure to figure that out.

**Comment by planetf1** [comment]
Could we do that? Do I need to raise an IT request?

I think it's important we understand how we can retriever a build? Obviously we can push a new commit, but that dirties our code history unnecessarily (in some cases).

Given the migration is pretty much done now, I'm thinking it may be appropriate to close this initial issue, then I/we can raise specific ones with new issues that come to light (and I presume alongside IT tickets where required). We'll tag with cicd

Future work will include

Docker
 - I/the dev team need to consider an approach in terms of what we're trying to achieve and document in a little more detail, but may include (issues on some of these)
 - refactoring our docker builds to be release specific
 - running a docker build automatically after a master merge
 - (maybe) running a docker build for PRs

Reliability
 - thanks for the updates around node/artifactory
 - retriggering
 - build performance

Usability
 - linkages to the Nexus CLM report (perhaps sonarcloud too?)

Automated test/deployment
 - Extending beyond the build to deploying a test environment (probably k8s) and capturing results

Release
 - still need to work through testing this

**Comment by planetf1** [comment]
I think we now have issues that cover most of these - not all are tagged CICD yet since they require more input from the egeria team/me ! (such as automating our CTS run)

If we have issues with retriggering I will raise an IT issue.

I will assume we have to work the the Nexus version we have for now (will raise an IT issue if usability becomes an issue)

As such I think we can close this general issue now
