### ISSUE TITLE
Additional components to support future notebook tutorials

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1655]
To support future notebook tutorials, add the following to the docker-compose tutorial environment & k8s 'lab' chart

 - An additional egeria platform (factory)
 - Shared file storage for file connectors (accessible by all platforms, UI, notebook)
 - LDAP server, populated with coco pharma directory
 - Environment variables accessible from notebook to access correct server/port for the above

**Comment by planetf1** [comment]
@mandy-chessell I will now start adding this

**Comment by planetf1** [comment]
The new server will be called 'factory' . The environment variable will be  `factoryPlatformURL=http://factory:8080` (docker-compose), and will be appropriately mapped in k8s. This will be used by the notebooks to find the new server.

**Comment by planetf1** [comment]
I am going to target 1.3 for the completion of this. There is a PR open (draft) which so far adds just the new platform. We can merge that if it's helpful, but I will need to do the ldap work after the 1.2 branch is created.

**Comment by mandy-chessell** [comment]
I think this makes sense - in 1.3 we need to build out the Coco demo enough to be able to show the duplicates being loaded and processed - this is going to require the additional components
