### ISSUE TITLE
Ensure that the UI config file is encrypted 

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#1658]
The UI config file contains credentials so need to be encrypted.

**Comment by cmgrote** [comment]
You mentioned that it uses a similar, but different format / mechanism to the core config files -- not sure, but maybe worth taking this opportunity to come up with a more abstract encryption provider that can be used across both (?)

(Though the encrypted version of the base config was just committed, so probably need to re-work that a little if so...)

**Comment by mandy-chessell** [comment]
We talked about having a single config connector/provider with 2 methods - one for the server config and one for the UI config - this would be a good time to do it.  The base class should throw an exception if the UI config method is called and it is not implemented by the connector implementation.

**Comment by cmgrote** [comment]
Thanks for the reminder 😄  Should we go ahead and do this to both the encrypted and non-encrypted config file store connectors (ie. extend each with methods for the UI config)?

**Comment by planetf1** [comment]
Note I added some review comments on dependency changes needing checking in that PR

**Comment by mandy-chessell** [comment]
This issue needs to be folded up with the refactoring - no point in creating a duplicate encrypted connector only to delete it later since the tactical solution will nto be used in production

**Comment by davidradl** [comment]
not relevant after #2577
