### ISSUE TITLE
Debugging Egeria client code - sources not found

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1659]
In order to reproduce a reported problem I created a new IntelliJ project just containing my test code.

I had previously built egeria from source (master) which populated maven artifacts into my ~/.m2, as well as specified our snapshot repo within the test project's maven pom.xml via
```
    <version>1.0-SNAPSHOT</version>
    <repositories>
        <repository>
            <id>egeriasnap</id>
            <name>Egeria Snapshot Repo</name>
            <url>https://odpi.jfrog.io/odpi/egeria-snapshot</url>
        </repository>
        <repository>
            <id>central</id>
            <name>Maven Central</name>
            <url>https://repo1.maven.org/maven2/</url>
        </repository>
    </repositories>

```

When debugging in the test project, and dropping into the egeria client code, IntelliJ was able to decompose the class files fairly well .. however it was not picking up the actual source.

The option to 'download sources' resulted in an error 
```
Sources not found for: org.odpi.egeria:ocf-metadata-client:1.1-20191004.123226-31
```

In my local ~/.m2 I had the following from my master build:
```
➜  egeria cd ocf-metadata-client
➜  ocf-metadata-client ls
1.1-SNAPSHOT             maven-metadata-local.xml
➜  ocf-metadata-client cd 1.1-SNAPSHOT
➜  1.1-SNAPSHOT ls
_remote.repositories
maven-metadata-egeriasnap.xml
maven-metadata-egeriasnap.xml.sha1
maven-metadata-local.xml
ocf-metadata-client-1.1-20190927.155640-22.jar
ocf-metadata-client-1.1-20190927.155640-22.jar.sha1
ocf-metadata-client-1.1-20190927.155640-22.pom
ocf-metadata-client-1.1-20190927.155640-22.pom.sha1
ocf-metadata-client-1.1-20191004.123226-31-sources.jar.lastUpdated
ocf-metadata-client-1.1-20191004.123226-31.jar
ocf-metadata-client-1.1-20191004.123226-31.jar.sha1
ocf-metadata-client-1.1-20191004.123226-31.pom
ocf-metadata-client-1.1-20191004.123226-31.pom.sha1
ocf-metadata-client-1.1-SNAPSHOT-javadoc.jar
ocf-metadata-client-1.1-SNAPSHOT-sources.jar
ocf-metadata-client-1.1-SNAPSHOT.jar
ocf-metadata-client-1.1-SNAPSHOT.pom
resolver-status.properties
➜  1.1-SNAPSHOT
```
whilst jfrog has 
```
ocf-metadata-client-1.1-20190930.122708-28.pom           30-Sep-2019 12:27  1.39 KB
ocf-metadata-client-1.1-20191001.092428-29-javadoc.jar   04-Oct-2019 07:29  154.03 KB
ocf-metadata-client-1.1-20191001.092428-29-sources.jar   04-Oct-2019 07:29  54.83 KB
ocf-metadata-client-1.1-20191001.092428-29.jar           01-Oct-2019 09:24  59.44 KB
ocf-metadata-client-1.1-20191001.092428-29.pom           01-Oct-2019 09:24  1.39 KB
ocf-metadata-client-1.1-20191004.072919-30-javadoc.jar   04-Oct-2019 12:32  154.01 KB
ocf-metadata-client-1.1-20191004.072919-30-sources.jar   04-Oct-2019 12:32  54.83 KB
ocf-metadata-client-1.1-20191004.072919-30.jar           04-Oct-2019 07:29  59.44 KB
ocf-metadata-client-1.1-20191004.072919-30.pom           04-Oct-2019 07:29  1.39 KB
ocf-metadata-client-1.1-20191004.123226-31.jar           04-Oct-2019 12:32  59.44 KB
ocf-metadata-client-1.1-20191004.123226-31.pom           04-Oct-2019 12:32  1.39 KB
```
As can be seen from this, some builds do include the sources (-sources.jar), others dont.

Debugging java software with maven nicely requires these sources are available to 3rd parties (for open source it's no concern sharing), indeed upload to maven central MANDATES source.

So there is something wrong in the build/upload - profiles perhaps, which needs investigating to better support consumers of Egeria.

Investigating ....

**Comment by planetf1** [comment]
The build process in maven looks ok.
The pipeline in Azure looks good https://dev.azure.com/odpi/Egeria/_build/results?buildId=287&view=logs&j=ac0a620f-bc12-5590-dc41-1227e7934d92
Even jfrog artifactory is confirming for that build that the 'sources' were published https://odpi.jfrog.io/odpi/webapp/#/builds/Egeria/20191004.2/1570191159739/published%20

Look at the directory listing more closely
```
ocf-metadata-client-1.1-20190930.122708-28-javadoc.jar   01-Oct-2019 09:24  153.96 KB
ocf-metadata-client-1.1-20190930.122708-28-sources.jar   01-Oct-2019 09:24  54.83 KB
ocf-metadata-client-1.1-20190930.122708-28.jar           30-Sep-2019 12:27  59.44 KB
ocf-metadata-client-1.1-20190930.122708-28.pom           30-Sep-2019 12:27  1.39 KB
ocf-metadata-client-1.1-20191001.092428-29-javadoc.jar   04-Oct-2019 07:29  154.03 KB
ocf-metadata-client-1.1-20191001.092428-29-sources.jar   04-Oct-2019 07:29  54.83 KB
ocf-metadata-client-1.1-20191001.092428-29.jar           01-Oct-2019 09:24  59.44 KB
ocf-metadata-client-1.1-20191001.092428-29.pom           01-Oct-2019 09:24  1.39 KB
ocf-metadata-client-1.1-20191004.072919-30-javadoc.jar   04-Oct-2019 12:32  154.01 KB
ocf-metadata-client-1.1-20191004.072919-30-sources.jar   04-Oct-2019 12:32  54.83 KB
ocf-metadata-client-1.1-20191004.072919-30.jar           04-Oct-2019 07:29  59.44 KB
ocf-metadata-client-1.1-20191004.072919-30.pom           04-Oct-2019 07:29  1.39 KB
ocf-metadata-client-1.1-20191004.123226-31.jar           04-Oct-2019 12:32  59.44 KB
ocf-metadata-client-1.1-20191004.123226-31.pom           04-Oct-2019 12:32  1.39 KB
```

There is some time overlap going on. The builds I linked to above are the 12:32 builds from 4 Oct.
Yet at this very same time the javadoc, sources for the PREVIOUS build was published.

I don't believe there's an issue with egeria, but maybe with azure or artifactory. Since atifactory IS reporting these artifacts as published, it //looks// like a jfrog problem at this time.

Inclined to see if this is just a one off or re-occurs....

**Comment by planetf1** [comment]
@bramwelt Any ideas what could have happened?

It does not look to be artifact specific, but is specific to this run of the build

Looking at the full directory https://odpi.jfrog.io/odpi/egeria-snapshot/org/odpi/egeria/open-lineage-services-server/1.1-SNAPSHOT/ there are some other oddities where the file update time is days/weeks different from the artifact date. The issue described here has occured a small number of times since we've been running azure/jfrog

**Comment by bramwelt** [comment]
Hmm..this is odd. I'm not sure what's happening here; taking a look.

**Comment by bramwelt** [comment]
This is very strange. It would appear the javadoc and sources aren't showing up until the _next_ merge happens. I kicked off another [build](https://dev.azure.com/odpi/Egeria/_build/results?buildId=288&view=results), and saw the [open-lineage-services-server](https://odpi.jfrog.io/odpi/egeria-snapshot/org/odpi/egeria/open-lineage-services-server/1.1-SNAPSHOT/) now has the 20191004.123315-31 snapshot has javadocs and sources, but 20191004.205612-32 does not!

**Comment by bramwelt** [comment]
Seems to be this [issue](https://www.jfrog.com/jira/browse/GAP-279) but they say it was fixed in a previous version. So either it wasn't actually fixed or somehow the issue has regressed - Either way I'm going to open a support request to see if we can get some more eyes on this from JFrog.

**Comment by planetf1** [comment]
Thanks - it does look strange. Only noticed it when I created an external/standalone project ( to try and act more like an egeria consumer ).

We can clearly change our build process if needed, but given local m2 looks correct, and azure/even jfrog logs *look* as if they are trying to post the correct artifacts, it does look more like a jfrog problem with indexing as you describe, and in any case I have no idea what to change to get jfrog to be happier.

**Comment by planetf1** [comment]
One extra bit of info - the build process first created an empty sources/javadoc jar file (0 length), THEN later in the build will overwrite with actual sources/javadoc. This was needed to satisfy maven central, and indeed is documented in their FAQ, as some of our modules don't contain real source, and javadoc. But that is all within the actual maven process, not the publishing afterwards. But mentioning in case there's some interaction here. (it worked for nexus+maven central on our 1,0 release)

**Comment by planetf1** [comment]
I checked the most recent build, and indeed that pattern is repeating itself - we are never getting the correct/latest sources until after the next build.

I flipped the repo for snapshots in my test project back to nexus, and it worked *perfectly*. Intellij correctly downloaded sources and was able to debug against the original source in maven artifact. Much smoother. Checking the repo directly again shows nexus was just right.

So Nexus works, jFrog fails

**Comment by planetf1** [comment]
I noticed 1.26.2 is current version of jfrog cli tools (used in azure dev pipelines). 1.29.1 is current. that being said there was no reference to fixed issues in this area at https://bintray.com/jfrog/jfrog-cli-go/jfrog-cli-linux-amd64#release but maybe worth a try (if we can control it) .

**Comment by bramwelt** [comment]
I raised the issue with JFrog, and CC'd you on the email. Hopefully we'll hear back from them soon.

An interesting note as well - this doesn't appear to affect non-SNAPSHOT versions. In the testing I've done for a mock [release](https://odpi.jfrog.io/odpi/list/egeria-release-local/org/odpi/egeria/open-lineage-services-server/1.1/) all the files are there.

**Comment by planetf1** [comment]
I think we may have had a jfrog indexing issue crop up in https://github.com/odpi/egeria/issues/1702

Very odd, but looks like our docker build picked up a few old artifact. I'm guessing related, but if you prefer we can reopen 1702... the most recent build was fine but worrying as to what the build did....

**Comment by planetf1** [comment]
@bramwelt any news from jfrog on this?

**Comment by bramwelt** [comment]
@planetf1 They said were not able to reproduce. Today I had the time to successfully reproduce the issue locally with the most recent artifactory-oss container and their own maven-example project, and I'll should have a walkthrough written up tomorrow.

**Comment by planetf1** [comment]
Thanks for the update -- great progress having a simple test case.

**Comment by bramwelt** [comment]
@planetf1 Here's the [gist](https://gist.github.com/bramwelt/eb5b09c8371e34c2ef01b68e2d1543aa) for reproducing the issue.

Interestingly it appears the Artifactory "Builds" system is not involved - Though it might be able to help, we'll see.

Responding to the issue I raised with JFrog, and will let you know when they've gotten back to me and hopefully directed us in the right direction - Or identified the bug that might exist in Artifactory. :crossed_fingers:

**Comment by planetf1** [comment]
Any further news?

**Comment by bramwelt** [comment]
The last response I got was from yesterday saying they'd reproduced and were going to look into it future.

**Comment by bramwelt** [comment]
> Thank you for your patience.
> I would like to update you that we are currently working together with R&D to provide a fix for this behavior.
>Once the fix will be ready, we will test it and release it.
>
> I will personally update you once the fix is ready, which will be around next week.

This is the update I received this morning.

**Comment by planetf1** [comment]
Waiting on jfrog - we cannot fix this for 1.2, and in any case it is only affecting our internal builds, not release builds, so will only effectively affect those working directly with master.

**Comment by bramwelt** [comment]
Pinged JFrog on an update for this today - They were supposed to get back to me, though maybe they were busy with Kubecon prep :woman_shrugging:. Will update when I hear something.

**Comment by bramwelt** [comment]
JFrog got back to me stating version 1.31.0 of the CLI was released with a fix for this yesterday. I confirmed it works locally, and seems to be working for 1.3-SNAPSHOTS (master merges) currently as well!

https://odpi.jfrog.io/odpi/list/egeria-snapshot-local/org/odpi/egeria/admin-services-server/1.3-SNAPSHOT/

**Comment by planetf1** [comment]
Superb ! That's looking good. Thanks for chasing up. I think we can close now.
