### ISSUE TITLE
Remove case sensitivity from Postgres objects in Coco Pharma samples

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1660]
Currently the Postgres objects (ie. tables and columns) in the Coco Pharma samples database use case sensitive names.  I think I had done this originally in order to simplify the mapping between the database objects and other IGC metadata as part of the sample metadata loading there, but this is causing other issues with that setup anyway.

I would also expect that this case-sensitivity is going to wreak havoc on any common SQL tools as all of these objects' names must be double-quoted in the SQL sent to Postgres to be properly resolved by Postgres itself (which for any tool that generates the SQL itself is likely going to break things?).

For example, our table `WORKLOCATION` can only be successfully queried using:

```sql
select * from "WORKLOCATION";
```

Trying to do:

```sql
select * from WORKLOCATION;
```

will give an error from Postgres along these lines (because what it is actually doing without the quotes is translating to `worklocation`, which then doesn't match the all-caps case-sensitive definition that is used in the sample data loading itself):

```
relation "worklocation" does not exist
```

Before I go ahead and make this change, just want to check to ensure that I'm not going to be breaking anyone else's work?

**Comment by planetf1** [comment]
It won't affect me (assuming the vdc deployment still works). Am not yet using the postgres data

**Comment by planetf1** [comment]
+ I agree with the rationale for the change

**Comment by cmgrote** [comment]
Removed case-sensitivity of the samples themselves in #1700, though this breaks the IGC samples with respect to Postgres (however, I don't think they were ever working with respect to Postgres anyway, so leaving to another PR to actually fix the IGC side of things).
