### ISSUE TITLE
Clean up schema model

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#1669]
In the meeting last week we discussed some changes to the schema definitions. This issue tracks the implementation of the decisions:
### Remove duplicate attribute definitions
The  **DerivedSchemaAttribute** entity replicated some of the attributes already defined in its superclass **SchemaAttribute**.  These duplicate attributes have been removed because they are unnecessary.  However it was pleasing to note that the duplicate definitions caused no problems as it means we can redefine an attribute at a higher level in the inheritance hierarchy without breaking backward compatibility.

### Use existing properties
There was also duplication in the properties of these entities with other elements of the model and we agreed that **id**, **comment** and **aggregatingFunction** should be deprecated to use qualifiedName, Comment and formula respectively.  Since we do not have the deprecating function in the OMRS type system yet, I have left the properties defined and changed their descriptions to include  "deprecated" like this
```
        final String attribute1Name            = "formula";
        final String attribute1Description     = "Transformation used to create the derived data.";
        final String attribute1DescriptionGUID = null;
        final String attribute2Name            = "comment";
        final String attribute2Description     = "Comment from source system (deprecated).";
        final String attribute2DescriptionGUID = null;
        final String attribute3Name            = "id";
        final String attribute3Description     = "Id of derived schema attribute (deprecated).";
        final String attribute3DescriptionGUID = null;
        final String attribute4Name            = "aggregatingFunction";
        final String attribute4Description     = "Aggregating function of derived schema attribute (deprecated).";
        final String attribute4DescriptionGUID = null;

```
### Simplify TypeEmbeddedAttribute classification

We agreed that the **TypeEmbeddedAttribute** classification is only a stub for special nesting cases and it does not need the attributes for a fully fledged **SchemaType** so it is reduced to two attributes: encodingStandard and dataType.

### Resulting UML

The UML models look like this now - note it does not show the deprecated fields:
![0505-Schema-Attributes](https://user-images.githubusercontent.com/12354195/66297269-4721d600-e8e7-11e9-9e88-b48c651e82d4.png)

![0512-Derived-Schema-Elements](https://user-images.githubusercontent.com/12354195/66297291-5012a780-e8e7-11e9-8b60-9854cd1fa286.png)

**Comment by mandy-chessell** [comment]
### Consistent use of displayName
We also discussed why **SchemaType** had an attribute called displayName and **SchemaAttribute** had an attribute called name.  We agreed to go with displayName and move the definition of it (and description) to their joint superclass of **SchemaElement**.

The name property in **SchemaAttribute** has been left and marked deprecated in the description as above.

It looks like this:
![0501-Schema-Elements](https://user-images.githubusercontent.com/12354195/66297849-61a87f00-e8e8-11e9-8b49-2a5a4efe53c9.png)

### Consistent linkage for SchemaTypeImplemenetation relationship

The **SchemaTypeImplementation** relationship used to connect a **SchemaType** to a **Referenceable**.  This is inconsistent with other uses and so it has been changed to  link **SchemaType** to **Process**.

**Comment by mandy-chessell** [comment]
![0504-Implementation-Snippets](https://user-images.githubusercontent.com/12354195/66298045-d8de1300-e8e8-11e9-9eb4-ccc41bac7bbe.png)

**Comment by cong78** [comment]
Hi Mandy just wondering would we keep the `Deprecated` in the description after the proper versioning of OM types?

**Comment by mandy-chessell** [comment]
The verisoning has always been there - just no support for deprecation.  There is a separate issue to add the deprecation support.  The deprecation will add a field to various parts of the type definition.  However, I think updating the description is also helpful.
