### ISSUE TITLE
Reverse generic config store

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#1679]
See comment on #1677

**Comment by cmgrote** [comment]
@bogdan-sava could we add a parameter-less method that overloads the now-parameterized method, which simply calls the now-parameterized method with the config class that was previously used (in the non-generic version) to provide backward compatibility for non-UI configs?

(Assuming that would be adequate to cover the backward-compatibility issue, whilst still providing the same generic mechanism for all other configs?)

**Comment by bogdan-sava** [comment]
Sorry there was not an issue about it

I think it is a design issue to have dependency of specific format into a connector that should have the purpose to save and retrieve config files in json or encrypted json.
It means no matter what config you want to write or read, connector carries the dependency of OMAGServerConfig, and with it entire  admin-services-api.
If we add for the UI, than will carry the entire admin-services-api of the UI.

**Comment by mandy-chessell** [comment]
It only has a dependency on the parts of the config it needs - not all of API - some storage structures may have a fixed schema and are not able to support an arbitrary structure

**Comment by cmgrote** [comment]
> some storage structures may have a fixed schema and are not able to support an arbitrary structure

I'm not sure I'm following...  if a storage mechanism needs to be able to persist our existing server config (just as one example) then the only "fixed schema" (eg. in an RDBMS) I could envision would be a BLOB / CLOB -- basically just an array of bytes...  How else to persist the arbitrary nested / hierarchical structure inherent in the config document?  (And if it's just a CLOB / BLOB, it _should_ be able to store any arbitrary structure that's capable of being serialized to an array of bytes?)

(For the examples we know of thus far -- files and document stores -- to me this is precisely what they're both basically doing: just storing the config document as a string...)

**Comment by cmgrote** [comment]
I'm wary of adding methods every time we have a new type of configuration we want to persist, if fundamentally the configurations are all going to have a similar "structure" of being hierarchical with varying degrees of sparsity or "filled-in-ness" (?)

**Comment by mandy-chessell** [comment]
Some may be in tables - some in an CLOB - there is no reason why an implementer would assume it is an opaque structure.  They may use particular values to set up index or something similar ...

**Comment by cmgrote** [comment]
Would we expect a storage mechanism to only support some of the methods and not others?  (I'm assuming they'd need to implement the entire interface, so to provide some implementation for all of the config documents?)

**Comment by mandy-chessell** [comment]
We are not going to be adding new platforms on a regular basis

**Comment by bogdan-sava** [comment]
Yes, but it is a matter of design. The structure suppose not to be in the connector, but in the usage of it. 
`serverConfigStore.retrieveServerConfig(OMAGServerConfig.class); `
means only support OMAGServerConfig structure

**Comment by cmgrote** [comment]
Sounds like something we should discuss in tomorrow morning's call? 😄

**Comment by mandy-chessell** [comment]
Completely correct - the config store may need to know about the structure it is storing in order to store it.  This is not a generic connector - it is very specific for configuration documents

**Comment by mandy-chessell** [comment]
I would rather have 2 connectors that this approach

**Comment by cmgrote** [comment]
Ok, let me take a stab at a revision that exposes two methods but still has internal reuse for our file-based connector implementations...

**Comment by bogdan-sava** [comment]
exactly

**Comment by bogdan-sava** [comment]
Need to create exactly the same connector with the only difference that uses a different format.
This is classical purpose for use generics in java.

**Comment by cmgrote** [comment]
How should the `initialize()` method behave if we have one connector that supports both UI and Server configs (which should presumably be two different files)?  At the moment the file is being named based on the endpoint in the `ConnectionProperties`, but with both in a single connector (and only one `initialize(... ConnectionProperties)` I think they'd end up with the same filename (?)

For backwards-compatibility I could prefix "ui." on the UI-specific one, but I don't think I could change the name of the non-UI server config?

**Comment by mandy-chessell** [comment]
The short answer is that is is the choice of the connector implementor how they store the config documents.  The value in the endpoint is just a guide that is sufficient enough to identify which config is needed.

I would say for our default file connector that there is only one file managed by the connector.  It has the same file name as before.   It is capable of storing either or both of the config doc structures we have.  The only time that the file will have both is if there are 2 servers with the same name, one on the UI platform and one on the server platform and they are sharing a home directory - so pretty unlikely but not impossible.

There is no need to add "ui" to the file name if it contains a ui config file. 

The UI config methods should have a default implementation to throw an exception.  This would be invoked if an existing connector had not implemented the UI methods.

When either method is called to retrieve a config doc, the file is opened and the appropriate config doc is returned.  If it is missing then a default version is returned (just like today).

This approach is backwardly compatible and does not cause a duplication of code.  It also keeps the contract clear as to what type of data needs to be stored.

**Comment by mandy-chessell** [comment]
Another approach is to have the endpoint as a directory name and have a specific file name for each type of config file.  However this is overly complex.

The important point is that backward compatibility is a requirement of both the interface and the default file implementation.  IE it should be able to read existing config files.

**Comment by cmgrote** [comment]
We agreed on the call today that in order to avoid delays to progressing to have @davidradl go ahead and merge his PR with the separate UI connector (after resolving the other comments on the PR), recognising that we will refactor this once we are all on a call together (hopefully Thursday?) to agree the refactoring.

**Comment by cmgrote** [comment]
We agreed on today's call that we should continue to progress with our tactical approach to ensure continued progress, but that we'll leave this open to recognise the need to re-factor later on.

**Comment by mandy-chessell** [comment]
Assign to me to refactor

**Comment by mandy-chessell** [comment]
I think this is fixed?
