### ISSUE TITLE
remove any local version references in poms

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1683]
Our dependencies are mostly tracked through
 properties (to provide a symbolic name relating to a numeric version)
 dependencyManagement (to mandate consistency)

Some local references have crept into updates - or missed first time around

This issue will correct any left behind.

For eample https://github.com/odpi/egeria/pull/1672/files?file-filters%5B%5D=.xml (the fault wasn't introduced in this PR, just was made clear in the review)

**Comment by planetf1** [comment]
Found some in open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/pom.xml

**Comment by mandy-chessell** [comment]
The build error message that is displayed when there is a missing dependency in a pom includes the version number - I think this is why they are creeping back in

**Comment by planetf1** [comment]
Yes you are probably correct. We can't influence that check - but it may be possible to enforce certain guidelines through 'check style'

**Comment by planetf1** [comment]
PR open to fix.
