### ISSUE TITLE
Investigate Docker image optimisations

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1687]
It looks like we might be able to pull the necessary latest versions of `.jar` file builds directly from Artifactory, rather than needing to use Maven (and its significant footprint) to pull them.

Raising this to investigate further as time / priorities permit.

API endpoint in Artifactory is:
https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-RetrieveLatestArtifact

Thinking would be to apply this to:

- Building the base `egeria` image itself (from latest built snapshot)
- Injecting connector `.jar` files at startup time of Helm chart (`initContainer`s pulling from here rather than manually-managed GitHub releases on the connector GitHub repos)

**Comment by cmgrote** [comment]
Closing as duplicate of #1688

**Comment by planetf1** [comment]
great minds think alike ;-) Yes it's a super idea we can followup in the other issue
