### ISSUE TITLE
Egeria docker build - retrieve artifact more efficiently

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1688]
Look at using something similar to
https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-RetrieveLatestArtifact

to retrieve the latest artifact (such as the server chassis)

Currently the egeria docker image build does this at docker build time (this now takes less than 5 minutes compared to 30-60 previously) - and this step does require jre/maven. It can take a minute or so. This alternative makes it simpler, quicker - though does lose some flexibility in terms of the origin (must be artifactory)

It also means we could defer the retrieval until the image is launched - with no dependency on jre/maven, and no extended time. (this makes the container itself very stable), but if so we need to figure out the appropriate versioning approach, especially when containers are released onto dockerhub with known labels

One option could be to 'bake' a version in, but also optionally refresh at launch time - controlled via a config parm.

Opening for consideration

**Comment by cmgrote** [comment]
Just a quick note for myself: it's also for images (like `egeria`) that are "injected" with things like connectors at runtime (eg. within the `vdc` Helm chart) -- this gives us a more automated and robust way of always injecting the latest snapshot that has been built.  (Up to now these inject-able `.jar` files have been manually maintained as GitHub releases by myself...)

**Comment by cmgrote** [comment]
@planetf1 have you already started work on this?  Given broken build status, I'd be happy to take this up and fix ASAP (I'm guessing I could get to PR within the next hour or two)...

**Comment by planetf1** [comment]
No not yet so feel free :-)

**Comment by planetf1** [comment]
I would presume you are still thinking of pulling the same artifact, but doing it via a jfrog curl or similar based retrieval instead of a maven invocation

**Comment by planetf1** [comment]
the root cause of the docker build failure is probably an artifact issue rather than this optimisation I would guess, so in theory the two would be independent.

I'll continue looking //specifically// at the source artifact(s) and assemblies (in the docker build issue) and perhaps you can look at the retrieval optimization?

**Comment by planetf1** [comment]
Indeed it is - so same artifact should be fine (and build should be fixed) when I correct path, making this useful, but on a different timescale (independent - quick or slow is fine)

**Comment by planetf1** [comment]
Ok so the docker build is fine now. Looks like a build funny. Will followup on the pipelines/jfrog side (see issue)... So feel free to make this change at your leisure. should be independent.
