### ISSUE TITLE
AssetConsumer client - getAssetProperties - assetName & assetTypeName outer are null

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1693]
When using the AssetConsumer client and calling getAssetProperties(userid,guid) the top level assetName & assetTypeName are null, though the elementTypeName is correct.

**Comment by planetf1** [comment]
For example the code
```
                           AssetUniverse props;
                            props=client.getAssetProperties(clientUserId,assetGUID);
                            System.out.println(props);
```
is used after running the configuring/starting/building a data catalog notebook & with 
clientUserId=peterprofile
assetGUID=4ffc1543-c510-456a-b62a-5a3aafaff0fa

We get back
```
AssetUniverse{assetBean=Asset{displayName='Week 1: Drop Foot Clinical Trial Measurements', shortDescription='null', description='One week's data covering foot angle, hip displacement and mobility measurements.', owner='null', ownerType='OwnerType : Other', zoneMembership=null, latestChange=Asset created, qualifiedName='CSVFile:file://secured/research/clinical-trials/drop-foot/DropFootMeasurementsWeek1.csv', additionalProperties=null, extendedProperties={quoteCharacter=", delimiterCharacter=,, fileType=csv}, meanings=null, type=ElementType{elementTypeId='2ccb2117-9cee-47ca-8150-9b3a543adcec', elementTypeName='CSVFile', elementSuperTypeNames=[DataFile, DataStore, Asset, Referenceable], elementTypeVersion=1, elementTypeDescription='A description of a comma separated value (CSV) file', elementSourceServer='cocoMDS1', elementOrigin=ElementOrigin{originCode=1, originName='Local to cohort', originDescription='The element is being maintained within one of the local cohort members. The metadata collection id is for one of the repositories in the cohort. This metadata collection id identifies the home repository for this element. '}, elementHomeMetadataCollectionId='d18e7297-2c66-41dd-8e2f-492d7845e29f', elementHomeMetadataCollectionName='null', elementLicense='null'}, GUID='4ffc1543-c510-456a-b62a-5a3aafaff0fa', URL='null', classifications=null}, assetMeanings=null, schema=null, feedback=AssetFeedback{informalTags=null, likes=null, ratings=null, comments=null}, knownLocations=null, lineage=AssetLineage{}, relatedAssets=AssetRelatedAssets{pagingIterator=AssetPagingIterator{maxCacheSize=100, totalElementCount=1, cachedElementStart=0, cachedElementList=[], cachedElementPointer=0}}, externalIdentifiers=null, relatedMediaReferences=null, noteLogs=null, externalReferences=null, connections=AssetConnections{pagingIterator=AssetPagingIterator{maxCacheSize=100, totalElementCount=1, cachedElementStart=0, cachedElementList=[], cachedElementPointer=0}}, licenses=null, certifications=null}
```
(from debug - for info ie the assetBean looks ok)

but props.AssetName & prps.assetTypeName are both set to <Unknown>

**Comment by planetf1** [comment]
Looking at another deployment of the 'vdc' chart (atlas, egeria, igc) I see
 egeria - can see ibmigc, atlas
 ibmigc - can see atlas
 atlas - can't see any other cohort members

**Comment by planetf1** [comment]
assetName/assetTypeName are in AssetDescriptor (also assetSuperTypeNames) & should be set in the constructor called by subtypes

**Comment by planetf1** [comment]
This should be fixed by https://github.com/odpi/egeria/pull/1701 thanks @mandy-chessell

**Comment by planetf1** [comment]
With the above my sample code now gets:
```
PropertyServerException{reportedHTTPCode=400, reportingClassName='org.odpi.openmetadata.accessservices.assetconsumer.client.AssetConsumer', reportingActionDescription='getAssetProperties', errorMessage='OMAG-OCF-400-002 The request for the properties of asset getAssetProperties failed with the following message returned: 'void org.odpi.openmetadata.frameworks.connectors.properties.AssetUniverse.setAssetBean(org.odpi.openmetadata.frameworks.connectors.properties.beans.Asset)'', reportedSystemAction='The system is unable to process the request.', reportedUserAction='Use the information in the message to understand the nature of the problem and once it is resolved, retry the request.', reportedCaughtException=null, relatedProperties=null}
	at org.odpi.openmetadata.commonservices.ocf.metadatamanagement.client.ConnectedAssetClientBase.getAssetProperties(ConnectedAssetClientBase.java:140)
	at org.odpi.openmetadata.accessservices.assetconsumer.client.AssetConsumer.getAssetProperties(AssetConsumer.java:179)
	at org.planetf1.example.AssetOwnerSample.main(AssetOwnerSample.java:50)
```

**Comment by mandy-chessell** [comment]
The first comment on this is that the error message is not very good.  It records an unchecked exception (probably NPE) but the exact nature of the exception is not recorded.  This need to be fixed.

**Comment by mandy-chessell** [comment]
I have tried to recreate this problem and cannot.  I did find a problem in the fomatting of an error message and the wrong serviceId was being passed from the ConnectedAssetProperties client to the server so the connectedAssetProperties.refresh() call was failing,  I also improved the OMAG-OCF-400-002 error message so we should get more information when this problem is recreated.

**Comment by planetf1** [comment]
I will retry my test code following the recent merges into master.

**Comment by planetf1** [comment]
Awaiting daily container build to verify in controlled environment (#1630 #1734 will improve this turnaround in future)

**Comment by planetf1** [comment]
This test code that was failing is now working against current master (docker-compose), so it would
appear the fixes have addressed the problem.

I observed that the fully qualified name for the csv file is now file://secured/research ... etc rather than CSVFile (which I think is fine). Also I note that the display name is 'secured/research' - I wonder if it should begin with / but that's minor.

Importantly assetName, assetTypeName, assetSuperTypeNames are all now correctly populated

**Comment by mandy-chessell** [comment]
On the qualified name - had discussion with the palisade tam and agreed that the CSVFile on the front of the qualified name made the getAssetByName harder to use because you needed to know the open metadata type of the asset.  Now it is just the file name which is a well known value.

I don't think the display name should begin with a '/' because it suggests to me that it is at the file system root.
