### ISSUE TITLE
Use common approach for java clients when throwing exceptions

### ISSUE THREAD

**Issue by ruxandraRosu** [odpi/egeria#1695]
Client connectors should have a similar approach when throwing exception. For example some java clients are throwing unchecked exceptions, some are throwing checked exceptions for similar cases.

**Comment by mandy-chessell** [comment]
Are these connectors or clients?  Either way, the exceptions are part of the interface.
Generally checked exception are clearer and preferred.

However, whether the excceptions are checked or unchecked, they should be Egeria exceptions with defined status code, message, system action and user response.

Could you give a list of the differences that you are seeing? @ruxandraRosu

**Comment by ruxandraRosu** [comment]
I am referring to java client like for asset-catalog or open-lineage-services. I've noticed when integrating OLS client into ui component that the approach is different for these 2 clients and I think a general approach, like a guideline for all java clients is desirable. One of the clients is throwing InvalidParameter and PropertyServerException checked exceptions, the other only runtime exceptions.

**Comment by mandy-chessell** [comment]
This makes sense ... we should have a joint call to discuss this.  I made an assumption that our FFDC principles and requirements are well known and I realize that this is not the case.

**Comment by ruxandraRosu** [comment]
As discussed in today's functionality call, 2 approaches are preferable:
1. Client should throw checked exceptions instead of runtime exceptions, in accordance with the response received from server
2.Use RestClientConnector instead of RestTemplate

**Comment by mandy-chessell** [comment]
I have assigned this to my list to cover the definition of the design guidelines - if we agree changes then we can have specific issues for the clients that should change

**Comment by mandy-chessell** [comment]
This issue is moving forward as there is a drive to get all to use the REST Connector and many clients use the OCF/ODF and GAF base classes for clients.

I will leave this open for another release and do an assessment of where we are
