### ISSUE TITLE
TypeExplorer UI fails to connect (docker-compose environment)

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1696]
The docker-compose tutorial environment contains a UI server in addition to 3 egeria platforms & jupyter. The intent was to be able to augment the tutorials if necessary with some UI guidance notes.

However in this environment the type explorer does not appear to work

When Type explorer is pointed at 
cocoMDS4 / datalake:8080 the following error is displayed:
```
Error occurred: The repository could not be reached, please check the server name and URL root and verify that the server is running 
```

datalake:8080 which is the name/port *within* the cluster, as used within the notebooks. 

Note that It's not obvious from the GUI where the connector is to/from, which makes a big difference in a container based installation, but it's actually from the UI backend to the egeria data lake server - so this host should be correct|

Opening for further investigation

**Comment by planetf1** [comment]
As an aside, noted when checking the docker-compose yaml that we only setup a link from the ui to the datalake platform - Since the type explorer may be useful to point at any platforms these additional links should be added too. However this isn't the issue preventing the current connectivity (as proven by the SA working)

**Comment by grahamwallis** [comment]
I suspect this might be because the serverURLRoot is. incomplete.
Did you try http://datalake:8080?

**Comment by planetf1** [comment]
That was the URL used - apologies I shortened it in the issue text.

On our status call today you mentioned an issue with security enabled. I do have security enabled, so that could be the reason. Happy to test a fix

**Comment by grahamwallis** [comment]
Please see PR #1775

**Comment by planetf1** [comment]
Now works fine after 1775 (cocoMDS1 / http://datalake:8080 )
