### ISSUE TITLE
Correct pom issues injected in #1673 / #1692

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1697]
Errors noted testing this change - unfortunately is already merged so will open in new issue:
```
➜  configuration-store-connectors git:(master) ✗ pwd
/Users/jonesn/src/egeria/open-metadata-implementation/adapters/open-connectors/configuration-store-connectors
➜  configuration-store-connectors git:(master) ✗ mvn install
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.odpi.egeria:configuration-store-connectors:pom:1.1-SNAPSHOT
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.odpi.egeria:ui-admin-services-client:jar -> duplicate declaration of version ${open-metadata.version} @ org.odpi.egeria:egeria:1.1-SNAPSHOT, /Users/jonesn/IdeaProjects/egeria/pom.xml, line 544, column 25
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
```

I will also raise a seperate issue to see what hard checks can be put in build to avoid any reoccurance

Other changes look good so far thanks

_Originally posted by @planetf1 in https://github.com/odpi/egeria/pull/1692#issuecomment-540040348_

**Comment by planetf1** [comment]
To clarify, these errors occur on master bdf6060f9f54abe986b7247d9a22d9642b73db42  when in 'configuration-file-store-connector' and running 'mvn clean install' - they are the very first messages at the top, and can be missed if the log isn't inspected as they quickly scroll past.

**Comment by davidradl** [comment]
@planetf1 Yes sorry - I did not notice those messages, so I assumed I was clean.
