### ISSUE TITLE
Azure pipeline verify build failure - artifact already exists

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1703]
@bramwelt  We have seen a build failure on the Java 11 build at https://dev.azure.com/odpi/Egeria/_build/results?buildId=358&view=results

This was for PR #1700 (@cmgrote ) but the error doesn't appear to be in the Java code, rather we get this in 'Publish Pipeline Artifact'
```
#[error]Artifact target-358_Java-1.11 already exists for build 358.
```

**Comment by bramwelt** [comment]
This is really odd. I'm not sure what's happening here, as those build's shouldn't contain the same Id. I might have overlooked this in my testing though and misunderstood that somehow BuildId is linked to the PR#? Sadly I don't see much [documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#build-variables) about how that ID is set or generated, but switching to BuildNumber should probably help ensure it doesn't happen again.

**Comment by planetf1** [comment]
Thanks.. it's looking really good generally, just ironing out a few hiccups :-)

I'll leave this open for a PR? Or if it's fixed out of the source we can close when done.

**Comment by bramwelt** [comment]
Yeah I'll get a PR up and attached to this issue.
