### ISSUE TITLE
Handle metadata exception in AssetCatalog omas

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#173]
Currently asset catalog omas gives the following if the metadata collection is not initialized

ie from:
{{baseURL}}/open-metadata/access-services/asset-catalog/users/rux/get-typedefs

{
    "timestamp": "2018-09-11T09:21:35.077+0000",
    "status": 500,
    "error": "Internal Server Error",
    "message": "No message available",
    "path": "/open-metadata/access-services/asset-catalog/users/rux/get-typedefs"
}

Instead a useful exception should be raised - for example subject area returns

{{baseURL}}/open-metadata/access-services/subject-area/users/rux/glossaries/123

{
    "class": "MetadataServerUncontactableExceptionResponse",
    "relatedHTTPCode": 200,
    "responseCategory": "MetadataServerUncontactableException",
    "exceptionClassName": "org.odpi.openmetadata.accessservices.subjectarea.utilities.OMRSAPIHelper",
    "exceptionErrorMessage": "OMAS-SUBJECTAREA-503-003 The access service has not been initialized and can not support REST API call ",
    "exceptionSystemAction": "The org.odpi.openmetadata.accessservices.subjectarea.server has received a call to one of its open metadata access services but is unable to process it because the access service is not active.",
    "exceptionUserAction": "If the org.odpi.openmetadata.accessservices.subjectarea.server is supposed to have this access service activated, correct the org.odpi.openmetadata.accessservices.subjectarea.server configuration and restart the org.odpi.openmetadata.accessservices.subjectarea.server."
}

**Comment by danielaotelea** [comment]
Not the current behaviour. I close the issue.
