### ISSUE TITLE
Support sequence order on find requests.

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#1747]
I came across a "ToDo" in the repository helper class that needs work ...

The `formatEntityResults` and `formatRelationshipResults` methods are not sorting the results before chopping out the entries that are outside of the paging parameters.

If anyone is good at sorting functions please pick this up.

**Comment by grahamwallis** [comment]
Is this what you're looking for?


 /**
     * Use the paging and sequencing parameters to format the results for a repository call that returns a list of
     * entity instances.
     *
     * @param fullResults        - the full list of results in an arbitrary order
     * @param fromElement        - the starting element number of the instances to return. This is used when retrieving elements
     *                             beyond the first page of results. Zero means start from the first element.
     * @param sequencingProperty - String name of the property that is to be used to sequence the results.
     *                             Null means do not sequence on a property name (see SequencingOrder).
     * @param sequencingOrder    - Enum defining how the results should be ordered.
     * @param pageSize           - the maximum number of result entities that can be returned on this request.  Zero means
     *                             unrestricted return results size.
     * @return results array as requested
     */
    private List<EntityDetail>    formatEntityResults(List<EntityDetail>   fullResults,
                                                      int                  fromElement,
                                                      String               sequencingProperty,
                                                      SequencingOrder      sequencingOrder,
                                                      int                  pageSize)
    {
        if (fullResults == null)
        {
            return null;
        }

        if (fullResults.isEmpty())
        {
            return null;
        }

        if (fromElement > fullResults.size())
        {
            return null;
        }

        List<EntityDetail>  sortedResults = sortEntityResults(fullResults, sequencingProperty, sequencingOrder);

        if ((pageSize == 0) || (pageSize > sortedResults.size()))
        {
            return sortedResults;
        }

        return new ArrayList<>(fullResults.subList(fromElement, fromElement + pageSize - 1));
    }

    private List<EntityDetail>  sortEntityResults(List<EntityDetail> listOfEntities, String propertyName, SequencingOrder sequencingOrder)
    {

        Collections.sort(listOfEntities, new java.util.Comparator<EntityDetail>() {
                    @Override
                    public int compare(final EntityDetail object1, final EntityDetail object2)
                    {
                        /*
                         * Ideally we would not include all this type inspection in the comparison
                         * function - but we do not know the types until we are comparing the
                         * pair of instances. There is no guarantee the list is homogeneous or that
                         * the objects to be compared are of the same type.
                         */

                        int    ret;
                        String o1PropertyTypeName = null;
                        String o2PropertyTypeName = null;
                        Object o1PropertyValue    = null;
                        Object o2PropertyValue    = null;

                        /*
                         * If object1 has the named property, retrieve its value. Same for object2.
                         * If neither object has the property return 0
                         * If one object has the property sort that higher: +1 if object1, -1 if object2
                         * If both have a value for the property, of different types, return 0.
                         * If both have a value for the property, of the same type, compare them...
                         * This is only performed for primitives, anything else is treated as ignored
                         */
                        InstanceProperties o1Props = object1.getProperties();
                        if (o1Props != null) {
                            InstancePropertyValue o1PropValue = o1Props.getPropertyValue(propertyName);
                            if (o1PropValue != null) {
                                InstancePropertyCategory o1PropCat = o1PropValue.getInstancePropertyCategory();
                                if (o1PropCat == InstancePropertyCategory.PRIMITIVE) {
                                    o1PropertyTypeName = o1PropValue.getTypeName();
                                    o1PropertyValue = ((PrimitivePropertyValue) o1PropValue).getPrimitiveValue();
                                }
                            }
                        }
                        InstanceProperties o2Props = object2.getProperties();
                        if (o2Props != null) {
                            InstancePropertyValue o2PropValue = o2Props.getPropertyValue(propertyName);
                            if (o2PropValue != null) {
                                InstancePropertyCategory o2PropCat = o2PropValue.getInstancePropertyCategory();
                                if (o2PropCat == InstancePropertyCategory.PRIMITIVE) {
                                    o2PropertyTypeName = o2PropValue.getTypeName();
                                    o2PropertyValue = ((PrimitivePropertyValue) o2PropValue).getPrimitiveValue();
                                }
                            }
                        }
                        if (o1PropertyTypeName == null && o2PropertyTypeName == null) {
                            ret = 0;
                        } else if (o1PropertyTypeName != null && o2PropertyTypeName == null) {
                            ret = 1;
                        } else if (o1PropertyTypeName == null) { // implicit: o2PropertyTypeName != null
                            ret = -1;
                        } else if (!o1PropertyTypeName.equals(o2PropertyTypeName)) {
                            ret = 0;
                        } else {

                            // Both objects have values, of the same type for the named property - compare...
                            ret = typeSpecificCompare(o1PropertyTypeName, o1PropertyValue, o2PropertyValue);

                        }
                        if (sequencingOrder == SequencingOrder.PROPERTY_DESCENDING) {
                            ret = ret * (-1);
                        }

                        return ret;
                    }
                }
        );

        return listOfEntities;

    }

    private int typeSpecificCompare(String typeName, Object v1, Object v2) {
        /*
         * It must have been previously established that both objects are of the type
         * indicated by the supplied typeName
         */
        int ret;
        switch (typeName) {
            case "boolean":
                ret = ((Boolean) v1).compareTo((Boolean) v2);
                break;
            case "byte":
                ret = ((Byte) v1).compareTo((Byte) v2);
                break;
            case "char":
                ret = ((Character) v1).compareTo((Character) v2);
                break;
            case "short":
                ret = ((Short) v1).compareTo((Short) v2);
                break;
            case "integer":
                ret = ((Integer) v1).compareTo((Integer) v2);
                break;
            case "long":
                ret = ((Long) v1).compareTo((Long) v2);
                break;
            case "float":
                ret = ((Float) v1).compareTo((Float) v2);
                break;
            case "double":
                ret = ((Double) v1).compareTo((Double) v2);
                break;
            case "biginteger":
                ret = ((BigInteger) v1).compareTo((BigInteger) v2);
                break;
            case "bigdecimal":
                ret = ((BigDecimal) v1).compareTo((BigDecimal) v2);
                break;
            case "string":
                ret = ((String) v1).compareTo((String) v2);
                break;
            case "date":
                ret = ((Date) v1).compareTo((Date) v2);
                break;
            default:
                LOG.debug("Property type not catered for in compare function");
                ret = 0;
        }
        return ret;

    }

**Comment by mandy-chessell** [comment]
Maybe :)
