### ISSUE TITLE
InternalOMRSEventProcessingContext incorrectly shares events to process across threads

### ISSUE THREAD

**Issue by jnhagelberg** [odpi/egeria#1763]
I noticed that the list of futures for events was getting extremely long.  I tracked it down to a problem with InternalOMRSEventProcessingContext .  This was actually preventing the offsets from being committed, since the future list was continually being added to by our async processing.  I have fixed this locally and am creating a PR.

Update: PR : https://github.com/odpi/egeria/pull/1764

**Comment by mandy-chessell** [comment]
@jnhagelberg hello Jeff - note that this went into master after the 1.1 branch was made so this problem will be in the 1.1 release.  We are hoping to create the 1.2 branch in November.
