### ISSUE TITLE
Add an InTopic to DE OMAS

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1770]
I think we should have an InTopic for the Data Engine OMAS, so that things like the data engine proxy can hand-over asynchronous messages to the Data Engine OMAS rather than relying on synchronous API calls.

At the moment the data engine proxy services are using the Data Engine OMAS client to make API calls, and there is a long wait until all of these calls are processed by the OMAS before state is persisted back into the underlying data engine. I think it would be more robust to generate messages, pass these asynchronously, and then immediately store the data engine's processing state while the Data Engine OMAS is still processing?  Any subsequent state changes within the data engine can then be picked up and asynchronously passed across again (queuing up behind any others already in the topic) while the Data Engine OMAS continues to process the topic.

To give a sense of timings (and why I think this addition / change is important), with our simple 3-4 job Coco Pharma example:

- The data engine proxy services startup and processing of the samples takes ~15 seconds (~3 seconds of which is actual job lookup and transformation, the rest is service, connection, etc startup (one-off) overhead)
- The data engine OMAS processing (and onwards) takes more than 2 minutes from there
- Only once that is complete is the data engine (DataStage) given the go-ahead to store when it last sync'd changes

Should anything go wrong in the second bullet, the "last sync'd changes" marker in the underlying data engine is not updated -- despite it's actions (the first bullet) happening fairly quickly.

This relates to https://github.com/odpi/egeria-connector-ibm-information-server/issues/64, which is only possible if there is an InTopic on the OMAS to write into. This change would ensure there is minimal risk of a service disruption requiring changes to be re-processed from the data engine. (Instead they'd be state-persisted in the InTopic, ready for processing whenever service is restored.)

**Comment by popa-raluca** [comment]
I assume this have to be done before the linege related release(https://egeria.odpi.org/release-notes/release-notes-1-3.html) ?

**Comment by cong78** [comment]
Hi Chris I am starting working on this user story and from what I understood over the description, after the inTopic of DE OMAS, the IGC Connector will publish events directly without any intermediate steps to DE Proxy right?

**Comment by cmgrote** [comment]
No, the IGC connector is not involved here...  The steps would be (after OMASes and proxies configured and an `InTopic` available):

1. DE Proxy polls for changes via its configured connection (in our example, the DataStage Connector)
1. DataStage Connector queries (via IGC, but not the IGC connector) for any changed objects since the last sync (or all, if no previous sync found)
1. All changed jobs (and their details: stages, links, columns, schemas, etc) are queried by the DataStage Connector
1. DataStage Connector translates all of these details into DE OMAS objects
1. DataStage Connector will push these DE OMAS objects onto the `InTopic` of DE OMAS
1. DataStage Connector will mark the last sync point (via IGC, but not the IGC connector) and hand-back control to DE Proxy
1. DE Proxy will sleep for the defined interval (60 seconds by default)
1. The DE Proxy will loop back to (1) again

**Comment by cong78** [comment]
Thanks thats very clear to me now. Just one more question to confirm:
> No, the IGC connector is not involved here
The DataStage Connector you are mentioning is the module of this one?
`egeria-connector-ibm-information-server/datastage-adapter`

**Comment by cong78** [comment]
I think it is hehe

**Comment by cmgrote** [comment]
Yes, the DataStage Connector is under `egeria-connector-ibm-information-server/datastage-adapter` while the IGC Connector is under `egeria-connector-ibm-information-server/igc-adapter`.  Note that there is no dependency between them -- though they both rely on the underlying IGC REST client library (which is completely independent of Egeria): `egeria-connector-ibm-information-server/igc-clientlibrary`

**Comment by cmgrote** [comment]
Looks like we've merged the implementation of the InTopic -- next question from my side is how I should make use of it?  Is it something that should be exposed via the DataEngineClient (which currently still only appears to operate against the REST API)?  Or should I somehow be calling the InTopic directly?

**Comment by cong78** [comment]
> Looks like we've merged the implementation of the InTopic -- next question from my side is how I should make use of it? Is it something that should be exposed via the DataEngineClient (which currently still only appears to operate against the REST API)? Or should I somehow be calling the InTopic directly?

Hi Chris, as I see from other existing connectors that are calling the in/out Topics of OMASes, it is done by governance server configuration POST calls with provided topic name and then being called directly in the connector. But now sure it is the good practice from the architectural design perspective. I will ask it during tomorrow functionality call to Mandy. :)

**Comment by cong78** [comment]
As a conclusion from what we have discussed from latest FC, I will add the functionalities from DE OMAS client that consumers can retrieve the connection objects of DE OMAS inTopic. For DS Proxy it can configure the inTopic by calling the DE OMAS client to use the inTopic connection further.

**Comment by cong78** [comment]
@popa-raluca Just realised I forgot to change the docs for previous user story of createExternalDataEngine. I will update it together with inTopic usage.

**Comment by cmgrote** [comment]
Just for clarity (to avoid mistake I just made changing labels) -- targeting the 1.4 release, as that's the lineage-related release...
