### ISSUE TITLE
Expose unique message id to message consumers

### ISSUE THREAD

**Issue by jnhagelberg** [odpi/egeria#1778]
This is related to https://github.com/odpi/egeria/issues/863.  When the server restarts unexpectedly, we need a way to distinguish stale messages from messages that were incompletely processed.  Messages that were incompletely processed should be reprocessed, but other (duplicate) messages with the same version and guid as a message we have previously processed can be safely ignored.  One very simple way we can do this is to enhance `OMRSEventProcessingContext` to be able to provide a unique identifier for the message that is currently being processed.  For Kafka, we’re using the message offset as the unique identifier.

I've put together a PR for this and am in the process of submitting it.

**Comment by mandy-chessell** [comment]
Hello @jnhagelberg - is this complete?

**Comment by planetf1** [comment]
I believe this is complete. Closing - @jnhagelberg please reopen if I'm mistaken
