### ISSUE TITLE
NPE in ConnectorBroker

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#179]
When attempting to configure my egeria install I hit a code path where I get the following exception:

java.lang.NullPointerException: null
	at org.odpi.openmetadata.frameworks.connectors.ConnectorBroker.getConnection(ConnectorBroker.java:260) ~[classes/:na]
	at org.odpi.openmetadata.frameworks.connectors.ConnectorBroker.getConnector(ConnectorBroker.java:471) ~[classes/:na]
	at org.odpi.openmetadata.frameworks.connectors.ConnectorBroker.getConnector(ConnectorBroker.java:331) ~[classes/:na]
	at org.odpi.openmetadata.repositoryservices.metadatahighway.OMRSMetadataHighwayManager.getTopicConnector(OMRSMetadataHighwayManager.java:394) ~[classes/:na]

This appears to be caused in getConnection:

    /**
     * Extract the connection from the embedded connection and push any arguments into the
     * AdditionalProperties for the connection.
     *
     * @param embeddedConnection embedded connection object.
     * @return connection object augmented with the arguments from the embedded connection.
     */
    private ConnectionProperties   getConnection(EmbeddedConnectionProperties   embeddedConnection)
    {
        ConnectionProperties connection = null;

        if (embeddedConnection != null)
        {
            AccessibleConnection accessibleConnection = new AccessibleConnection(embeddedConnection.getConnectionProperties());
            Connection           connectionBean       = accessibleConnection.getConnectionBean();

            AdditionalProperties arguments            = embeddedConnection.getArguments();

            if (arguments != null)
            {
                Map<String, Object>  additionalProperties = connectionBean.getAdditionalProperties();
                Iterator<String>     argumentNames = arguments.getPropertyNames();

                while (argumentNames.hasNext())
                {
                    String  argumentName = argumentNames.next();

                    additionalProperties.put(argumentName, arguments.getProperty(argumentName));
                }

                connectionBean.setAdditionalProperties(additionalProperties);
            }
[
<img width="2658" alt="screenshot 2018-09-12 at 10 35 28" src="https://user-images.githubusercontent.com/7292002/45416323-97dce600-b677-11e8-8fa3-f4aa01f6976b.png">
](url)

It occurs as additionalProperties is null, even though the connectionBean is ok

It may be worth validating this & capturing information for the returned exception, though I've not yet identified why in particular this NPE is hit during the configuration of my server

**Comment by planetf1** [comment]
In my case this occurred because I was incorrectly passing (or trying to) my additional configuration on cohort configuration rather than event bus configuration. This is why the additionalProperties were null - they hadn't been passed on the event bus config request. 

We could do with catching this user error earlier and producing a better exception. 

Having made the correction the server now starts :-)

**Comment by mandy-chessell** [comment]
Pull request https://github.com/odpi/egeria/pull/186 addresses the null pointer exception.

I think the second part of the comment is suggesting that Egeria should detect that that additional properties were passed on the wrong command.  This is not possible since either commands are configuring connectors for OMRS and the additionalProperties request body is valid on either.  Therefore, smart as Egeria is, it is not possible for it to detect that properties intended for one command have been passed on a different command.
