### ISSUE TITLE
DE OMAS - Update external data engine registration methods from software server capability 

### ISSUE THREAD

**Issue by cong78** [odpi/egeria#1791]
For Data Engine OMAS, there are methods and REST endpoints have been defined from clients side to create software server capability from external data engines. However, there are few things need to be added or changed to make the full logic working. For this issue there are following listed changes will be implemented: 
1. Update DE OMAS Client method from `createSoftwareServerCapability` to `createExternalDataEngine` to make it more intuitive and clear from other OMASes with similar capabilities. 
2. Add Common Services methods in `repositoryHandler` that has `createExternalEntity` and `createExternalRelationship` that can pass the external data engine's GUID. 
3. Update DE OMAS Server entity and relationship creation methods(handlers) in DE OMAS with parameters of external data engine's GUID. 
4. Update DE OMAS Client & Spring modules with updated methods that can pass external data engine's GUID.

@popa-raluca @cmgrote 
Please let me know if you have any questions. Thanks. :)

**Comment by popa-raluca** [comment]
Looks good, just one more thing - common handler SchemaTypeHandler needs to be updated as well to make use of the newly added methods from RepoistoryHandler. 
DataEgineSchemaTypeHandler uses SchemaTypeHandler when creating and updating SchemaTypes & Schema Attributes

**Comment by cong78** [comment]
From the conclusion of discussion in PR #1831 :
1. We will only keep the `externalSourceName` (qualified name from external data engine) to be included in the payload. And DE OMAS Server will be responsible to search the linked GUID of the external source. 
2. We will keep the value of `externalSourceName` as a property in DE OMAS client (cache). And when the client is dead the governance engine (like Data Engine Proxy) should be able to reset the value according to the payload.
