### ISSUE TITLE
Proposed introduction of JSON-LD library into Egeria

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#1799]
As part of the design model work I am parsing a standard model exported in JSON-LD into an open metadata archive.  The open metadata archive means that the glossary and model elements can be loaded into an open metadata repository.

There is a library that I am using called JSON-LD-Java.  This is the POM dependency

        <dependency>
            <groupId>com.github.jsonld-java</groupId>
            <artifactId>jsonld-java</artifactId>
            <version>0.12.5</version>
        </dependency>

It has a call that converts JSON-LD into a LinkedHashMap<String, Object>.

Does anyone have an concerns with theu se of this library?

**Comment by grahamwallis** [comment]
I don't have any concerns with this proposal

**Comment by cong78** [comment]
Looks good. :)

**Comment by planetf1** [comment]
Agreed - looks like a good approach
