### ISSUE TITLE
Starting server with kafka configured results in many warnings about kafka config 

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#180]
The following WARNing is produced many times when launching a service instance with a configured event bus.

If this is normal, but harmless, at best it should be downgraded to an INFO rather than WARN.
It may also indicate a bug?

2018-09-13 09:04:39.965  WARN 70428 --- [nio-8080-exec-6] o.a.k.clients.producer.ProducerConfig    : The configuration kafka.omrs.topic.id = cocoCohort was supplied but isn't a known config.

**Comment by mandy-chessell** [comment]
Should this one be raised against Apache Kafka? or is this saying that something we are going creates this warning?

**Comment by planetf1** [comment]
See also #337

**Comment by planetf1** [comment]
Also this looks like a specific duplicate of #336

**Comment by mandy-chessell** [comment]
I think this is fixed

**Comment by planetf1** [comment]
yes
