### ISSUE TITLE
Proposed introduction of Avro into Egeria

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#1800]
I am working on sample onboarding and discovery services that work with Avro files.  This means we will start including Avro in our runtimes where these services are enabled (they are OCF connectors).

Avro is defined as a depndency on the top-level pom with a version number of

```
        <avro.version>1.9.1</avro.version>
```
There are currently no modules using it.

Are there any concerns about adding Avro to our samples?

**Comment by grahamwallis** [comment]
I am not aware of any.

**Comment by planetf1** [comment]
To be completely accurate, I assume you mean that you will add avro into the top level pom in the dependencyManagement section - this is basically saying that IF another module is found to use it - directly, or transitively, THEN that version from dependencyManagement (and indirectly from properties) will be the one used....

But it will be good to get avro samples in :-)

**Comment by mandy-chessell** [comment]
I think Avro is already there in the top level pom

**Comment by planetf1** [comment]
Ah I just have checked...  - was just clarifying '<dependencies> vs <dependencyManagement> in technical terms in the pom as we want to be careful with dependency ballooning (our checks should cause this to be picked up in any case)
