### ISSUE TITLE
Fix & improve Nexus CLM scans

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1824]
Nexus CLM scans have previously been run from jenkins - weekly https://jenkins.odpi.org/view/CLM/job/odpi-egeria-maven-clm-master/

We now have  azure pipeline builds for CLM. The URL can be discovered from the build logs of a CLM build such as https://dev.azure.com/odpi/Egeria/_build/results?buildId=1116&view=logs&j=0f078380-ac3e-5e5f-e0b3-465dfb800fdc&t=8453ffff-1b48-53ab-fec0-8f40db482b56&l=16991 -- it also runs after each merge. Superb!

** However the URL is non-obvious. Is there any way we can make this more obvious when the pipeline runs?

We are also running the CLM report on master, but for a release, we need to ensure we include the correct licenses, and updated information about dependencies. For this the CLM report is useful. I

And my main ask -> 
** Could we run CLM for egeria-release-1.1 also ? I can guess at how to do this in the yaml but unsure what needs setting up on the nexus side?
cc: @bramwelt

**Comment by planetf1** [comment]
I also notice the organization on nexus-clm is currently 'odpi-egeria-test' - needs updating?

**Comment by planetf1** [comment]
I also note that Nexus-CLM is scanning our java code, but not
 - Javascript
 - Dockerfiles

Is it capable of either of these?

**Comment by bramwelt** [comment]
> ** However the URL is non-obvious. Is there any way we can make this more obvious when the pipeline runs?

You're supposed to be able to see all the violations in Azure without having to open Nexus-IQ, which will also provide the link, but there seems to be an issue with it retrieving the data and I haven't dug into it yet: https://dev.azure.com/odpi/Egeria/_build/results?buildId=1116&view=SonatypeIntegrations.nexus-iq-azure-extension.nexus-iq-report-hub

Though it looks like this may rely on a feature that was added in September, and our IQ server is running an older version than that.

> And my main ask ->
> ** Could we run CLM for egeria-release-1.1 also ? I can guess at how to do this in the yaml but unsure what needs setting up on the nexus side?
> cc: @bramwelt

Sure can! It's set to run against the `egeria-release-*` branches, but the patch needs to be cherry-picked in that added the job to azure pipelines: #1707 

> I also note that Nexus-CLM is scanning our java code, but not
> 
> * Javascript
> * Dockerfiles
> 
> Is it capable of either of these?

I'll have to look at our version and the docs to find out.

> I also notice the organization on nexus-clm is currently 'odpi-egeria-test' - needs updating?

Whoops: I forgot to update that once the job was merged! Fixed. :)

**Comment by planetf1** [comment]
* thanks for info on the nexus integration. you're updating the IQ server I think? (I see reference in the PR to that in terms of scripts too), so we should get that nicer integration when done

* I'm not sure what the action is for egeria-release-* - actually I looked and see there is a nexus-iq trigger set for egeria-release-* so it should be running? I'm not familar enough with azure pipelines?

**Comment by bramwelt** [comment]
> * thanks for info on the nexus integration. you're updating the IQ server I think? (I see reference in the PR to that in terms of scripts too), so we should get that nicer integration when done

Looking into this. It may pose a bit of a challenge to as our IQ server is shared across multiple projects, and upgrading it may break their CLM jobs without some coordination.

> * I'm not sure what the action is for egeria-release-* - actually I looked and see there is a nexus-iq trigger set for egeria-release-* so it should be running? I'm not familar enough with azure pipelines?

In order for the CLM jobs to be triggered on the egeria-release-* branch the azure pipeline config needs to be present. It's pretty confusing because though the change is in master to run the job against the branches, if the branches themselves don't contain the CI config they can't be triggered (as the configuration is evaluated from the branch that runs).

If the release branch had been created after the CLM job was merged this wouldn't be a problem. #1832 should fix it :)

**Comment by planetf1** [comment]
Got it thanks.

**Comment by planetf1** [comment]
I can close this now - or would you prefer to keep it open to track the UI integration/sw update?

**Comment by bramwelt** [comment]
You should see the egeria-release-1.1 CLM scans [here](https://dev.azure.com/ODPi/Egeria/_build?definitionId=23&_a=summary&repositoryFilter=4&branchFilter=173) now.

Yes, let's close this as the primary issue (getting CLM runs on the release branch) is done, and updating Nexus-IQ is a larger task.
