### ISSUE TITLE
Update httpclient > 4.5.2

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1828]
Currently the janus connector is using org.apache.httpcomponents:httpclient:4.5.2 which is subject to a directory traversal security exposure documented as SONATYPE-2017-0359 (7)

Current versions appear to have addressed this flaw

**Comment by grahamwallis** [comment]
Which connector is this referring to?

**Comment by planetf1** [comment]
```
[INFO] org.odpi.egeria:janus-connector:jar:1.2-SNAPSHOT
[INFO] +- org.janusgraph:janusgraph-es:jar:0.3.1:compile
[INFO] |  +- org.elasticsearch.client:elasticsearch-rest-client:jar:6.0.1:compile
[INFO] |  |  +- org.apache.httpcomponents:httpclient:jar:4.5.2:compile
[INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.5:compile
[INFO] |  |  +- org.apache.httpcomponents:httpasyncclient:jar:4.1.2:compile
[INFO] |  |  \- org.apache.httpcomponents:httpcore-nio:jar:4.4.5:compile
```

**Comment by grahamwallis** [comment]
OK - thanks - it isn't obvious from the name that this is part of the OLS.

**Comment by grahamwallis** [comment]
This issue should really be assigned to Guy or someone working on the OLS. 
I cannot change the assignment.

**Comment by planetf1** [comment]
@GuyAckermans can you take a look (cc: @grahamwallis )

**Comment by GuyAckermans** [comment]
Will do

**Comment by planetf1** [comment]
This has been fixed everywhere we can control it -- we do still pull in 4.5.2 via hadoop - but this will be addressed by moving hadoop components to a new repo
