### ISSUE TITLE
Empty collection vs null

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#183]
When developing GE-omas I used 'getPropertiesDefinition' on TypeDef to get a list of optional attributes & iterate (to pass to ranger)

I missed out a check for null - so NPE, but I wonder if we would be better returning an empty collection
in these cases, rather than a null? Collections such as lists are often used with iterators, and unless there's a particular reason to use null, an empty list seems easier?

Open for discussion.

**Comment by mandy-chessell** [comment]
I have been explicitly removing all empty lists from every object so that properties only appear if they have relevant content.  Otherwise the collection has to be retrieved, and an iterator created to discover it is empty.

**Comment by mandy-chessell** [comment]
It also makes it easier to deprecate properties since the consumers are coded to allow for the absence of elements within types and instances.  When a deprecated property begins to disappear, the consumers continue to work.
