### ISSUE TITLE
Refine scoping for GE Omas classificationDefs

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#184]
Currently 'classificationdefs' will return all typedefs in the category CLASSIFICATION_DEF

However this includes all kinds of classifications - such as WebServer, Application server... not just governance classifications

Opening this issue as a reminder that this needs refining
 * Some scoping could be applied based on valid entities for a classification (validEntityDefs) - it's only worth getting classifications that relate to assets types that a security endpoint is managing

This may require API changes. For now all classification defs are returned

**Comment by danielaotelea** [comment]
Governance Engine OMAS scope has been changed. 
In this moment, GE OMAS is listening for the "Security Tags" classification assigned to Schema Elements. 
The initial scope of the ClassificationDef has been changed.

**Comment by planetf1** [comment]
The excellent implementation we now have  meets the thought behind this original issue so we can close.
