### ISSUE TITLE
egeria website doesn't render fully on mobile

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1840]
The egeria website at http://egeria.odpi.org has some issues on mobile

a) Although the page layout changes going down to a smaller device (like iPhone XS Max - which is still large), the navigation capability is nowhere to be seen - I believe it used to appear in a drop down menu
b) Pictures such as architecture diagrams are severely chopped. This is always going to be a challenge on a small device, but perhaps bringing up in a new page, or having scroll bars could be an improvement

One useful suggestion - in Safari, with develop mode enabled, there is an option 'Develop->Enter responsive design mode' which allows the viewer to select different device types for testing.

We should go through the website and ensure they render sensibly. I have actually used the website with friends/at conference to show egeria so would be good to 'look good' -- visitors to a conference may also well follow such a link to find out about the project.

**Comment by planetf1** [comment]
Have tested again. the issue remains - the nav bar does not appear on mobile, nor indeed a narrow window. Diagrams remain truncated.

There's docs on github pages at https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll

I'm not familar with this area so if anyone else reading this would like to work on this issue please reassign!

Removing milestone for now - will need much more investigation into github pages.

**Comment by planetf1** [comment]
still broken 2020-03-27

**Comment by planetf1** [comment]
This still occurs.

The top level egeria page no longer includes navigation.
However the link to 'tutorials' does display a left nav bar on desktop. 
This does not appear on mobile (iOS 13.5, iPhone XS Max)

**Comment by planetf1** [comment]
On mobile it's still tricky to find content. The nav bar on desktop gives a top level list of information which is quite useful - it I want to use, or contribute, or learn. This is lost on mobile where we only see the detailed text.

**Comment by planetf1** [comment]
Still seems odd on mobile, but if no-one is concerned we can close

**Comment by planetf1** [comment]
@cmgrote - FYI given you are looking at updated formatting of these pages

**Comment by cmgrote** [comment]
Assuming we go for the change to the suggested MkDocs approach that @davidradl and I are using in our repos it should render great on mobile -- including adaptive / reactive changing of the menus and table of contents to not take up any of the page but be collapsed menu bars instead, etc.

Hope to have a prototype of some of the main areas of the site up in early August on my fork for us to review.

(I'm seeing areas for what I think will be significant improvements to consumability, but they need some rework to some of the existing pages to achieve, so TBD...)

**Comment by mandy-chessell** [comment]
@planetf1 is this fixed?

**Comment by planetf1** [comment]
@mandy-chessell yes, we are much better now with the new docs site, and I can generally navigate.

The only confusion is if one goes to 'learn more' on the front screen, the left nav no longer works adequately - and only contains the challenge/our solution / key concepts / patterns. Different to on the web where the main nav bar remains. This is slight confusion, though a 'back' in the nav panel gets one back to the main menu. A minor usability glitch. May just be me who normally goes via that route on the web page. 

Much easier to go straight to the (hamburger) menu which has the full navigation.

I think we can close for now

**Comment by cmgrote** [comment]
> The only confusion is if one goes to 'learn more' on the front screen, the left nav no longer works adequately - and only contains the challenge/our solution / key concepts / patterns.

This is probably more a less-than-intuitive way that the theme works rather than it not being possible...  Basically on a mobile device all the navigation structure is collapsed into the hamburger menu, but since it is many levels deep there is a back arrow in the hamburger menu itself that allows you to jump up a level in the nav structure -- what's shown there the first time you open it is the nav structure at the level of the page you're viewing, rather than the top-level nav structure (you need to use that back arrow to go "back" up to a higher-level in the overall nav structure).

**Comment by planetf1** [comment]
Yes - it was just confusion over where 'learn more' took me to. Probably just me. I had no problem finding the content with the back menu, it was just that difference with my particular navigation on the web. hence agreeing it should be closed :-)
