### ISSUE TITLE
NPE from GovernanceEngineOMRSTopicListener

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#1844]
Just received this from my Coco Pharmacetutical set up ...

Thu Oct 24 06:25:59 BST 2019 cocoMDS1 Exception OMRS-AUDIT-0101 Unable process an incoming event {"class":"OMRSEventV1","protocolVersionId":"OMRS V1.0","timestamp":1571894758987,"originator":{"metadataCollectionId":"52394ab2-7343-4d36-9cc0-921824c349e0","serverName":"cocoMDS1","serverType":"Open Metadata Server","organizationName":"Coco Pharmaceuticals"},"eventCategory":"INSTANCE","instanceEventSection":{"class":"OMRSEventV1InstanceSection","protocolVersionId":"OMRS V1.0","eventType":"CLASSIFIED_ENTITY_EVENT","typeDefGUID":"fe30a033-8f86-4d17-8986-e6166fa24177","typeDefName":"SoftwareServerCapability","entity":{"class":"EntityDetail","type":{"class":"InstanceType","typeDefCategory":"ENTITY_DEF","typeDefGUID":"fe30a033-8f86-4d17-8986-e6166fa24177","typeDefName":"SoftwareServerCapability","typeDefVersion":1,"typeDefDescription":"A software capability such as an application, that is deployed to a software server.","typeDefSuperTypes":[{"guid":"a32316b8-dc8c-48c5-b12b-71c1b2a080bf","name":"Referenceable"}],"validInstanceProperties":["qualifiedName","additionalProperties","name","description","type","version","patchLevel","source"]},"instanceProvenanceType":"LOCAL_COHORT","metadataCollectionId":"52394ab2-7343-4d36-9cc0-921824c349e0","metadataCollectionName":"cocoMDS1","createdBy":"peterprofile","updatedBy":"peterprofile","createTime":1571894758982,"updateTime":1571894758987,"version":2,"guid":"f2cb72e0-12ff-46e7-9953-5dc21c737826","classifications":[{"class":"Classification","type":{"class":"InstanceType","typeDefCategory":"CLASSIFICATION_DEF","typeDefGUID":"cab5ba1d-cfd3-4fca-857d-c07711fc4157","typeDefName":"FileSystem","typeDefVersion":1,"typeDefDescription":"A server that support a file system containing a hierarchy of file folders and data files.","validInstanceProperties":["format","encryption"]},"createdBy":"peterprofile","createTime":1571894758987,"version":1,"classificationOrigin":"ASSIGNED","name":"FileSystem","status":"ACTIVE"}],"properties":{"class":"InstanceProperties","instanceProperties":{"name":{"class":"PrimitivePropertyValue","instancePropertyCategory":"PRIMITIVE","typeGUID":"b34a64b9-554a-42b1-8f8a-7d5c2339f9c4","typeName":"string","primitiveDefCategory":"OM_PRIMITIVE_TYPE_STRING","primitiveValue":"file://"},"qualifiedName":{"class":"PrimitivePropertyValue","instancePropertyCategory":"PRIMITIVE","typeGUID":"b34a64b9-554a-42b1-8f8a-7d5c2339f9c4","typeName":"string","primitiveDefCategory":"OM_PRIMITIVE_TYPE_STRING","primitiveValue":"file://"}},"propertyNames":["qualifiedName","name"],"propertyCount":2},"status":"ACTIVE"}}} due to exception java.lang.NullPointerException from listener org.odpi.openmetadata.accessservices.governanceengine.server.listeners.GovernanceEngineOMRSTopicListener@21588913

**Comment by mandy-chessell** [comment]
This is not the cause of the problem because entity type is SoftwareServerCapability which does have a supertype - however entities such as Annotation does not have a super type and would NPE in this code

```
public boolean isSchemaElement(EntityDetail entityDetail) throws UserNotAuthorizedException, RepositoryErrorException, org.odpi.openmetadata.repositoryservices.ffdc.exception.InvalidParameterException, TypeDefNotKnownException {
        List<TypeDefLink> typeDefSuperTypes = entityDetail.getType().getTypeDefSuperTypes();
        boolean schemaAttribute = typeDefSuperTypes.stream().anyMatch(typeDefLink -> typeDefLink.getName().equals(SCHEMA_ATTRIBUTE));
        if (schemaAttribute) {
            return true;
        }
        for(TypeDefLink typeDefLink : typeDefSuperTypes){
            TypeDef typeDef = metadataCollection.getTypeDefByName(GOVERNANCE_ENGINE, typeDefLink.getName());
            if(typeDef.getSuperType().getName().equals(SCHEMA_ATTRIBUTE)){
                return true;
            }
        }
        return false;
```

**Comment by mandy-chessell** [comment]
This problem is showing up in the lab notebook examples where we are creating FileSystem software server capabilities.

**Comment by grahamwallis** [comment]
I'm seeing it during the CTS tests too.

**Comment by mandy-chessell** [comment]
I am going to work on a fix today

**Comment by mandy-chessell** [comment]
The NPE is coming from this part of `isSchemaElement` shown above at this `if` statement:
```
if(typeDef.getSuperType().getName().equals(SCHEMA_ATTRIBUTE)){
                return true;
            }
```
The instance is a `SoftwareServerCapability`.  Its superclass is `Referenceable` which has no supertypes.  At the time of the NPE, the `typeDef` variable is set to Referenceable's typeDef.  The call to `getSuperType()` returns `null` as expected and the subsequent call to `getName()` results in the NPE.

**Comment by mandy-chessell** [comment]
I have fixed the NPE but have now found another problem.
The GovernanceEngine OMAS is calling the OMRS with a dummy userId rather than the localServerUserId passed in the configuration document.  This means that its requests are being rejected by the security module ...

```
Mon Nov 04 13:18:11 GMT 2019 cocoMDS2 Security OPEN-METADATA-SECURITY-0006 User GovernanceEngine is not authorized to issue a request to server cocoMDS2
```

**Comment by mandy-chessell** [comment]
The final fix was to replace the code with a call to the repositoryHelper isTypeOf() method to determine if the entity is a type of SchemaAttribute.
