### ISSUE TITLE
Proposal - Abort build if unapproved license is found in dependencies

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1845]
We track licenses for all dependencies being picked up via maven (etc)
A report is generated and can be reviewed, triage, approval sought etc

However it would save time, and prevent accidental misuse if we added into the build the validation of licenses against that published on maven central. This could then prevent a PR merge if unapproved licenses are found.

More investigation is needed as there seem to be a few possible approaches, need to handle dual licenses, and ideally work closely with other license scanning techniques.

This won't cover everything (for example I'm unsure if we can do the same for our UI code with web components)

A good idea?

**Comment by grahamwallis** [comment]
Yes - I think is a good idea.

**Comment by mandy-chessell** [comment]
me too

**Comment by planetf1** [comment]
I'm going to suggest we move this to the next release and target 1.3. We haven't yet sorted the manual steps/review

**Comment by grahamwallis** [comment]
I support your suggestion.

**Comment by planetf1** [comment]
Currently our code scan occurs off the merge build, via Nexus IQ, and the results are periodically reviewed.
At this point I don't think there's a good option for this automation and will close until such point as we revisit our license analytics
