### ISSUE TITLE
Subject Area UI is blank

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1851]
On both release-1.1 and master, the subject area UI section renders with a blank content section
 (Safari, built with java 11)

Will add screenshot

Please advise if you need a fix added to 1.1 urgently. Otherwise I recommend a readme note with a reference to this bug

**Comment by planetf1** [comment]
See https://pasteboard.co/IDAfvzS.png

**Comment by planetf1** [comment]
I checked chrome, and it worked ok (I should have beforehand).
Additionally after another pom fix has gone into 1.1 the latest build is also looking fine in the subject area UI. 

I'll assign to myself and do some more checks later. for example the docker images on master & release 1.1 (when ready)

**Comment by davidradl** [comment]
I have not tested Safari. I have raised issue #1861 to agree the supported browsers for the UI

**Comment by planetf1** [comment]
The formal build runs & creates the egeria ui jar.& then deploys into the container
Using the build from yesterday the subject UI renders correctly.

**Comment by planetf1** [comment]
closing until/unless a specific pattern is identified which causes this
