### ISSUE TITLE
Agree supported browsers for Egeria UI

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#1861]

**Comment by cmgrote** [comment]
Might be worth looking at a deeper-dive of the "Browser Support" chart towards the bottom of https://www.webcomponents.org -- all major browsers (except Edge) are listed as stable, but delving into the link itself you can see that some do not support certain aspects of Web Components (eg. WebKit, which is what is behind Safari, does not support `HTML Imports` portion of web components, but seems to support the rest) (?)

**Comment by planetf1** [comment]
Agree we should document. I think for open source we are ok targeting current, stable versions of the browsers. I would certainly start with chrome, safari . Edge is a less a concern as Microsoft is replacing the 'old' edge with the 'new' chromium (like chrome) based one. We could target that instead. (as it will no doubt just work). Then add firefox, opera if we can.

Note that we should also consider screen layout. Whilst it involves some compromises given screen estate, mobile chrome/safari on iOS/android should be checked too [but some areas like TEX we may decide to make sure work, but note a caveat about how usable on a smaller device).
