### ISSUE TITLE
Add space for repository connector implementations to stash local identifiers in headers of instances

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#1862]
This issue proposes an extension to the audit header of entities, entity proxies, relationships and classifications.  It would be a map of string to object.  Repository connector implementations can use it to keep useful information for mapping the Egeria identifiers to the actual master object in the repository connector's store.  The repository services will transmit these values but not read, validate or change them.

**Comment by mandy-chessell** [comment]
The new property called `mappingProperties` is now in master in the audit header for instances.

https://github.com/odpi/egeria/blob/master/open-metadata-implementation/repository-services/repository-services-apis/src/main/java/org/odpi/openmetadata/repositoryservices/connectors/stores/metadatacollectionstore/properties/instances/InstanceAuditHeader.java

This leaves 2 pieces of work.

- [ ] Extend the CTS to check that this field is property stored

- [ ] Extend the graph repository to store this property (and any other new property that comes along)

**Comment by grahamwallis** [comment]
Would it be possible to declare mappingProperties as Map<String, Serializable> ?
This would guarantee that any value would be serializable and would ensure that any repository should be able to store it.
