### ISSUE TITLE
Resillience and Future-proof profiles for the repository workbench of the conformance test suite

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#1864]
This issue proposes two new optional profiles for the conformance test suite.

* **Resilience** tests that the technology under test can handle badly formatted events and REST payloads.
    * These payloads should be ignored at minimal cost

* **Future-proof** tests that the technologgy under test can cope with extended events and REST payloads that are coming from a possible future release of egeria.
    * These payloads should be processed, ignoring the additonal fields, if understood.
    * If the payloads represent a new command then it should be ignored.

**Comment by grahamwallis** [comment]
We should keep this open - it is still a valid requirement

**Comment by grahamwallis** [comment]
We should keep this open - it is still a valid requirement

**Comment by grahamwallis** [comment]
We should keep this open - it is still a valid requirement
