### ISSUE TITLE
Be wary of character encoding in RestTemplate

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1872]
It seems that by default `RestTemplate` (at least `.exchange()`) will communicate any strings using ISO-8859-1 encoding rather than (as you might expect) UTF-8...

If you're making use of RestTemplate to send any information to REST endpoints, it might be worth explicitly setting the string message converter in use to UTF-8 (assuming you expect to handle anything other than basic English text) -- see https://github.com/odpi/egeria-connector-ibm-information-server/pull/117 for an example of how to do this.

**Comment by mandy-chessell** [comment]
Sounds like we should get it right in the REST Client connector and get all of the components to use that?
