### ISSUE TITLE
Remove cassandra-driver-core - not needed

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1873]
> Hi @DimitriosMaimaris - would it be possible for you or one of the team to look at this
> recommended change as I don't have a cassandra environment to validate with (yet!)

I think we can remove this dependency in general since it is used to connect with thrift for Cassandra but we will use cql driver.

_Originally posted by @DimitriosMaimaris in https://github.com/odpi/egeria/pull/1820#issuecomment-545794959_

**Comment by cong78** [comment]
Hi Nigel, I think the cassandra-core-driver has been upgraded to the the current dependency:
            <dependency>
                <groupId>com.datastax.oss</groupId>
                <artifactId>java-driver-core</artifactId>
                <scope>compile</scope>
                <version>${oss.version}</version>
            </dependency>

This dependency is being used by Cassandra Connectors.

**Comment by cong78** [comment]
I will close this issue as the dependency is used for cassandra connectors and has been updated to latest versions.

**Comment by planetf1** [comment]
I did update it, however my understanding was that @DimitriosMaimaris indicated it was not needed.

If so we should remove entirely? 

I could remove and verify the build, but I'm not familiar enough with how to validate with cassandra simply (yet). We do need to get that into some kind of fvt, but until then I thought it best to let you remove.

Should I go ahead and remove (we can revert if we find out it is needed?)

**Comment by planetf1** [comment]
Have looked at the connector code. It currently is dependent on cql in the code. So indeed, we should close...
