### ISSUE TITLE
1.1 maven artifacts not being published (to artifactory)

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1874]
Browsing https://odpi.jfrog.io/odpi/egeria-snapshot/org/odpi/egeria/
it appears that 1.1 artifacts are not being published despite the fact that the main project version is 1.1

This means it likely we won't be able to promote to staging either
cc: @bramwelt

Needs investigating

**Comment by bramwelt** [comment]
@planetf1 1.1 builds shouldn't be showing up in the snapshot repo as they're not snapshots. In order for the staging artifacts to be deployed into the egeria-staging repository, you'll want to start the 1.1 release process in [AZP](https://dev.azure.com/ODPi/Egeria/_release?_a=releases&view=mine&definitionId=1) by clicking 'Create Release' and selecting the commit to stage from the egeria-release-1.1 branch.

**Comment by planetf1** [comment]
Thanks for the explanation, we're in the stage of addressing some 1.1 issues prior to being ready to release/stage.. so I hadn't realise the build artifacts wouldn't go anywhere.

This probably means next time it makes sense to defer to version renaming until nearly ready for staging - if that's automated that's less of a problem in any case.

Closing, but we should capture this in the docs. Thanks

**Comment by bramwelt** [comment]
No worries, @planetf1. I'll have an PR to the docs up shortly where we can collaborate on the release steps.
