### ISSUE TITLE
Invalid userId passed to server start up/shutdown methods issues by the OMAG Server Platform

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#1878]
I am seeing invalid userId messages when I shutdown a platform that has servers running.  The userId appears to be blank.  Will investigate further.

**Comment by mandy-chessell** [comment]
It looks like there is a property that is being used for the userId called `sysUser`.  Need to find where it is documented.

**Comment by bogdan-sava** [comment]
It is documented since has been introduced in https://github.com/odpi/egeria/blob/master/open-metadata-implementation/server-chassis/server-chassis-spring/README.md

**Comment by bogdan-sava** [comment]
The purpose is to temporary deactivate servers when the platform shutdown signal is received

**Comment by mandy-chessell** [comment]
The purpose is understood - the problem is that the code assumes the userId is set up.
It should either not call the deactivation if there is no userId because it causes a security error or handle the security exception and provide instructions to the admin so they know how to fix it.
