### ISSUE TITLE
remove full platform archive from assembly maven artifact

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1890]
The open-metadata-assemblies maven artifact currently contains the full server platform archive -- these are unnecessary, and indeed undesirable

a) Our docker images pull required files from jfrog
b) within an org it is expected that they will build locally

It is not an intent to ship a binary of ready to run code.

Therefore this large jar can be removed

https://odpi.jfrog.io/odpi/egeria-snapshot/org/odpi/egeria/open-metadata-assemblies/1.1-SNAPSHOT/

This should be done for 1.1 as well as master (compliance)

**Comment by planetf1** [comment]
This is applied to 1.1 & master by reverting ad593e50fca6553a89c75ea6173922e15faa2b4c where the archive was added (to support docker builds - no longer needed)

**Comment by planetf1** [comment]
See ec0aec43bbcfa98920bf850e023a7351d78976a8 (1.1) & f7bb03c10f89fcd4ef4d9cacff3481e307a72ed5 (master)

**Comment by mandy-chessell** [comment]
Assuming we are still assembling the server image?
