### ISSUE TITLE
Extend docker-compose & k8s tutorial environmentsto support CTS

### ISSUE THREAD

**Issue by moyabrannan** [odpi/egeria#1892]
Modify the Docker build to support a Text platform to showcase CTS

**Comment by planetf1** [comment]
Proposal
 - Add new 'platform' to support the CTS driver 

Although the CTS could be run in the current environment just as a new server this keeps the cts aspects distinct - alongside use of a seperate cohort (which can be created in a notebook) and hence seperate kafka topics

The notebook itself will be implemented in #1893 whilst #353 will look at automating the CTS as part of the CI/CD pipeline

**Comment by planetf1** [comment]
After a discussion with @mandy-chessell we will continue using the existing dev platform for launching CTS within the coco pharma environment, as this is representative of what they would do as a company.

There is therefore no need for an additional platform, so the notebook can be written with no changes to the infra (compose or k8s)

#353 automation may result in the creation of a more technical/custom environment that does not use coco pharma, but that will be addressed there.
