### ISSUE TITLE
Create Notebook to run CTS

### ISSUE THREAD

**Issue by moyabrannan** [odpi/egeria#1893]
Create a new notebook to configure the Test environment for CTS, then run the workbench test and display back results.

The requirement to determine how results are aggregated to best show results

**Comment by mandy-chessell** [comment]
There is a notebook already created - just empty
Here is the link  https://github.com/odpi/egeria/tree/master/open-metadata-resources/open-metadata-labs/conformance-testing-labs

**Comment by planetf1** [comment]
Assigning this to 1.3

**Comment by grahamwallis** [comment]
Fixed by #2113
