### ISSUE TITLE
CTS Blog

### ISSUE THREAD

**Issue by moyabrannan** [odpi/egeria#1894]
Create Blog to introduce and provide an overview of CTS.

**Comment by planetf1** [comment]
I think Graham is working this - can you also confirm if targeted at 1.3?

**Comment by grahamwallis** [comment]
It's going out roughly the same time as 1.2 - but is not ties to the release branch obviously

**Comment by planetf1** [comment]
Blogs are at
 overview: https://www.odpi.org/blog/egeria/2019/12/04/what-is-egerias-conformance-test-suite-for-metadata-repositories
 detail: https://www.odpi.org/blog/tech-deep-dive/2019/12/04/the-odpi-egeria-open-metadata-conformance-suite-repository-workbench
