### ISSUE TITLE
Move server autostart into admin services

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#1907]
The autostart feature of the OMAG Server Platform is coded in the Spring server chassis.  This has 2 problems:

* The code needs to be duplicated into the UI Server Platform
* The code needs to be rewritten if we add support for a different REST framework.

This feature moved the code into the admin-services

**Comment by bogdan-sava** [comment]
It seems that UI platform are using different admin services so even there code needs to be duplicated.

The only common module I see is open-connector-framework, but i don't think it belongs there. Maybe rename http-helper to app-helper and add it there?

Also temporary deactivate is triggered in Spring context closed event. Maybe a better idea is to also use JVM hook (Runtime.getRuntime().addShutdownHook) but

**Comment by mandy-chessell** [comment]
We will be bringing the admin services for the UI into the main admin services module when the basic work is completed.

Even if there were 2 admin services, we still need to bring the function into the admin services so that when we have different REST frameworks, the function still works

**Comment by mandy-chessell** [comment]
Using the Spring hook is fine - it needs to directly invoke the admin services function.

**Comment by bogdan-sava** [comment]
I mean for the deactivate part when shutting down the platform, finding a place to put JVM shutdown hook instead Spring close event will make this part work independent of Spring

**Comment by mandy-chessell** [comment]
I understand your suggestion
