### ISSUE TITLE
Conformance granularity?

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1909]
As I'm working through implementing some of the write operations, I've been thinking about whether it might be worthwhile to consider some kind of qualification to the Conformance mark -- particularly for pre-existing repositories (like IGC, Atlas, and others) that are (probably all?) likely to only support a subset of the open metadata types rather than all of them...

Should we make it clear somewhere / somehow with which subset of the open metadata types a given repository is Conformant?

I think this would be very valuable for anyone shopping around for repositories, to be able to consider how broad its support is for the open metadata types of interest to a particular use.  Just seeing that a repository is broadly Conformant (but not qualifying for which open metadata types) leaves it open to misinterpretation that a Conformant repository can carry out its conformed activities on _all_ open metadata types.

Taking IGC as an example, I would hope to achieve:

| profile | types |
|----|----|
| Metadata sharing | for 10's of open metadata types across entities, classifications and relationships |
| Metadata maintenance | for ~5 open metadata entity types, ~5 classifications and ~10 relationships |
| Non-conformance | for 100's of open metadata types |

- Marking IGC as "conformant" for metadata sharing (without any qualification) when it only supports a small percentage of the types doesn't answer the user question of "I need it to share information about instances of type X, can it do that?"
- Same when marking IGC as "conformant" for metadata maintenance (without any qualification) when it only supports an even smaller percentage of the types (eg. "I need it to maintain information about instances of type Y, can it do that?")

Which implies to me that if we go in the more granular (type-by-type) direction, it would be ideal to have this separation against each of the profiles themselves -- as even in the same repository the types that conform to one profile vs another may differ...

I'm assuming that we probably get to this level of granularity in the CTS itself by cycling through the types that we detect a given repository tells us it can handle; but I'm not sure we're "rolling it up" into a reported form?  (Trying to go through the entire CTS output would be pretty arduous to answer the basic questions above...)

**Comment by mandy-chessell** [comment]
@cmgrote This was considered when we put the conformance mark together.  The mark is showing that the repository can safely added to the cohort.  In addition there is the report from the tool that goes into the detail of which requirements are covered - it would be this report that is used to compare repositories and is the qualification that you are asking for.

The good thing about the CTS is that anyone can run it - so if an organization is comparing repositories, they can run (or ask the vendor to run) the CTS as part of the procurement process.

**Comment by grahamwallis** [comment]
Is there an easy way to generate a list of the types that are supported by a given repository? (Not a runtime question - i.e. not using getAllTypes() :0-)

**Comment by cmgrote** [comment]
> Is there an easy way to generate a list of the types that are supported by a given repository? (Not a runtime question - i.e. not using getAllTypes() :0-)

I'll have a deeper look once the broader set of CTS changes are in, but I thought the CTS already makes use of `getAllTypes()` as one of its early steps to determine what types to use when invoking other methods -- if so, then there is implicitly a list of types that the CTS is testing against, and that we could therefore report from the CTS.

So I think all of that detail is in the CTS, I'm just keen on investigating whether there's a sub-report or the like that we could create that "rolls up" this summary on a type-by-type basis for easier digestion than reading through all of the detailed tests 😉

**Comment by grahamwallis** [comment]
Agreed - it's the availability of the generated digest/report that I was asking about

**Comment by grahamwallis** [comment]
Looking at the spring module for the CTS I can see the following URLs:
(GET) /report - returns the whole enchilada
(GET) /report/test-cases/{testCaseId} - will report on an individual testcase
(GET) /report/test-cases/failed - will report on all failed test cases
(GET) /report/workbenches/{workbenchId} - provides info on level of conformance for given workbench

My system is in the middle of a full CTS run at the moment but when it has finished I will experiment with the above

**Comment by grahamwallis** [comment]
I think the API is close but does not quite provide what we are looking for.

You can interrogate the CTS server to give the results of a given test case - but that requires that you specify the type that was being tested, as the testCaseId in the above URL is formed like this:

repository-entity-lifecycle-Asset

The above example is specifying the entity lifecycle test case for the type Asset.

If you GET from that URL you will get something the following, but you would have to od once per type. I think we are seeking a summary of 'types that this repository supports'.

http --json --pretty all  GET localhost:8080/servers/CTS1/open-metadata/conformance-suite/users/garygeeke/report/test-cases/repository-entity-lifecycle-Asset | tee /tmp/cts_result
{
    "class": "TestCaseReportResponse",
    "relatedHTTPCode": 200,
    "testCaseResult": {
        "class": "OpenMetadataTestCaseResult",
        "discoveredProperties": {
            "Asset soft delete support": "Enabled",
            "Asset undo support": "Disabled"
        },
        "notSupportAssertions": [],
        "successMessage": "Entities can be managed through their lifecycle",
        "successfulAssertions": [
            "repository-test-case-base-01: Repository connector supplied to conformance suite.",
            "repository-test-case-base-02: Metadata collection for repository connector supplied to conformance suite.",
            "repository-test-case-base-01: Repository connector supplied to conformance suite.",
            "repository-test-case-base-02: Metadata collection for repository connector supplied to conformance suite.",
            "repository-test-case-base-01: Repository connector supplied to conformance suite.",
            "repository-test-case-base-02: Metadata collection for repository connector supplied to conformance suite.",
            "repository-entity-lifecycle-01: Asset new entity created.",
            "repository-entity-lifecycle-02: Asset new entity has createdBy user.",
            "repository-entity-lifecycle-03: Asset new entity has creation time.",
            "repository-entity-lifecycle-04: Asset new entity has correct provenance type.",
            "repository-entity-lifecycle-05: Asset new entity has correct initial status.",
            "repository-entity-lifecycle-06: Asset new entity has correct type.",
            "repository-entity-lifecycle-07: Asset new entity has local metadata collection.",
            "repository-entity-lifecycle-08: Asset new entity has version greater than zero.",
            "repository-entity-lifecycle-09: Asset new entity is known.",
            "repository-entity-lifecycle-10: Asset new entity summarized.",
            "repository-entity-lifecycle-11: Asset new entity retrieved.",
            "repository-entity-lifecycle-12: Asset new entity is unattached.",
            "repository-entity-lifecycle-13: Asset entity status updated.",
            "repository-entity-lifecycle-14: Asset entity new status is Active",
            "repository-entity-lifecycle-15: Asset entity with new status version number is 2",
            "repository-entity-lifecycle-16: Asset entity can not be set to DELETED status.",
            "repository-test-case-base-01: Repository connector supplied to conformance suite.",
            "repository-test-case-base-02: Metadata collection for repository connector supplied to conformance suite.",
            "repository-test-case-base-01: Repository connector supplied to conformance suite.",
            "repository-test-case-base-02: Metadata collection for repository connector supplied to conformance suite.",
            "repository-entity-lifecycle-17: Asset entity properties cleared to min.",
            "repository-entity-lifecycle-18: Asset entity with min properties version number is 3",
            "repository-entity-lifecycle-21: Asset entity deleted version number is 4",
            "repository-entity-lifecycle-22: Asset entity no longer retrievable after delete.",
            "repository-entity-lifecycle-23: Asset entity restored ",
            "repository-entity-lifecycle-24: Asset entity restored version number is 5",
            "repository-entity-lifecycle-25: Asset entity retrieved following restore ",
            "repository-entity-lifecycle-26: Asset entity purged."
        ],
        "testCaseDescriptionURL": "https://egeria.odpi.org/open-metadata-conformance-suite/docs/repository-workbench/test-cases/repository-entity-lifecycle-test-case.md",
        "testCaseId": "repository-entity-lifecycle-Asset",
        "testCaseName": "Repository entity lifecycle test case",
        "unsuccessfulAssertions": []
    }
}

**Comment by cmgrote** [comment]
I'm not suggesting this rolled-up view already exists, I'm suggesting adding it 🙂

**Comment by cmgrote** [comment]
I suspect I'll have my hands full just trying to get Atlas and IGC running and then conformed within the new CTS -- pushing this back to 1.3...

**Comment by grahamwallis** [comment]
Still seems like a good thing to do - keeping open
