### ISSUE TITLE
Add reserved words to archive builder

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#1920]
The repository find APIs allow the standard header properties to be specified as search targets.  This causes problems if the instance properties have the same name as the header properties.  This issue proposes that the open metadata types archive builder polices (prevents) the creation of instance properties that clash with the instance header property names.

In addition there needs to be some modification to the existing types as a small number of types currently have clashing names (which is how we found this problem in the CTS).

**Comment by mandy-chessell** [comment]
I propose to use this change as a test of the deprecation and type def patching / versioning support that are documented in #1528 and  #1367.  As such they will be rolled up together.

**Comment by cmgrote** [comment]
Sounds like this is also related to #2099?

**Comment by mandy-chessell** [comment]
Whoops - still needed
