### ISSUE TITLE
unable to issue addEntity

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#193]
When attempting to invoke {{baseURL}}/open-metadata/repository-services/users/{{user}}/instances/entity

where {{}} are relevant variables

it appears the code in OMRSRestRepository.java is not invoked (was trying to debug) but there is an issue hit earlier on in the spring framework to do with the structure of the request body

2018-09-17 15:50:53.310  WARN 6144 --- [nio-8080-exec-2] .w.s.m.s.DefaultHandlerExceptionResolver : Failed to read HTTP message: org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Missing type id when trying to resolve subtype of [simple type, class org.odpi.openmetadata.repositoryservices.rest.properties.EntityCreateRequest]: missing type id property 'class'; nested exception is com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Missing type id when trying to resolve subtype of [simple type, class org.odpi.openmetadata.repositoryservices.rest.properties.EntityCreateRequest]: missing type id property 'class'

**Comment by mandy-chessell** [comment]
What is the request body sent?

**Comment by planetf1** [comment]
It seems to happen regardless of the request body sent - empty, or a full example (which isn't useful) from swagger.

It also affects create relationship & create entity proxy. It's something to do with jackson/spring serialization/deserialization I think, and the way class mapping is done.

**Comment by mandy-chessell** [comment]
You are right, this request body is incorrect - it does not have the class information for the request body in it.  Our JSON should look like this ... this is a GET response for an entity ... notice it begins with the "class" tag - this is required to allow Jackson to process subclasses:

{
    "class": "EntityDetailResponse",
    "relatedHTTPCode": 200,
    "entity": {
        "class": "EntityDetail",
        "type": {
            "class": "InstanceType",
            "typeDefCategory": "ENTITY_DEF",
            "typeDefGUID": "578a3510-9ad3-45fe-8ada-e4e9572c37c8",
            "typeDefName": "GovernanceOfficer",
            "typeDefVersion": 1,
            "typeDefDescription": "Person responsible for a governance domain.",
            "typeDefSuperTypes": [
                {
                    "guid": "a32316b8-dc8c-48c5-b12b-71c1b2a080bf",
                    "name": "Referenceable"
                }
            ],
            "validInstanceProperties": [
                "qualifiedName",
                "additionalProperties",
                "title",
                "scope",
                "domain"
            ]
        },
        "createdBy": "julesk",
        "createTime": "2018-09-11T13:01:20.139+0000",
        "version": 1,
        "instanceProvenanceType": "LOCAL_COHORT",
        "metadataCollectionId": "87b06ffe-9db2-4ef5-ba6e-8127480cf30d",
        "guid": "fd7d41e7-70f5-42ec-86d3-88683e599494",
        "instanceURL": "http://localhost:8080/instances/entity/fd7d41e7-70f5-42ec-86d388683e599494",
        "properties": {
            "class": "InstanceProperties",
            "instanceProperties": {
                "title": {
                    "class": "PrimitivePropertyValue",
                    "instancePropertyCategory": "PRIMITIVE",
                    "primitiveDefCategory": "OM_PRIMITIVE_TYPE_STRING",
                    "primitiveValue": "Chief Data Officer (CDO)"
                },
                "qualifiedName": {
                    "class": "PrimitivePropertyValue",
                    "instancePropertyCategory": "PRIMITIVE",
                    "primitiveDefCategory": "OM_PRIMITIVE_TYPE_STRING",
                    "primitiveValue": "EXEC-CDO"
                },
                "domain": {
                    "class": "EnumPropertyValue",
                    "instancePropertyCategory": "ENUM",
                    "ordinal": 1,
                    "symbolicName": "Data",
                    "description": "The data (information) governance domain."
                }
            },
            "propertyNames": [
                "qualifiedName",
                "domain",
                "title"
            ],
            "propertyCount": 3
        },
        "status": "ACTIVE"
    }
} 

All of our JSON uses this format.  Also note that the OMRS REST API is not designed for general use - it is typically used only by the OMRS REST Repository Connector for managing metadata in remote repositories.

**Comment by mandy-chessell** [comment]
I think you have this working now?

**Comment by planetf1** [comment]
Correct, I am able to successfully add an entity and relationship using a very simple body. I think the most useful way to mitigate against similar issues in future would be to fix up/correct the swagger docs, though that will only cover REST (which applies here) - not configuration or messaging. In part that's addressed by #213 though that is purely the 'class' aspect, and there's a lot more here to look at.

Happy for you to track that as you feel makes sense. No code changes needed on creating an entity

**Comment by mandy-chessell** [comment]
I agree we need to fix the swagger and #213 covers it.  Trying to keep the OMRS REST API quite hidden as do not want it used outside of the OMRS - however if we publish somthing it should be right :)
