### ISSUE TITLE
Asset catalog get supported types

### ISSUE THREAD

**Issue by bogdan-sava** [odpi/egeria#1936]
create API rest endpoint that returns types supported by asset-catalog
create method in client

gueryParameter: name - used to filter all supported types by name or displayName, that contains the parameter. Parameter is not mandatory.

**Comment by danielaotelea** [comment]
Asset Catalog OMAS configuration should provide a list of: 
SupportedTypes and DefaultTypes. These will be added on accessServiceOptions. 
The defaulted types for the AC OMAS are: GlossaryTerm, Asset, SchemaElement. 

The second task is to provide a REST endpoint that returns the supported types. 
@bogdan-sava is it enough for this service to return the typeName and typeGUID?

**Comment by danielaotelea** [comment]
Hi, Bogdan! There is something that is missing from the Asset Catalog OMAS related to the supported types? 
If not, can we close this issue?
