### ISSUE TITLE
Review of open-lineage-services module

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#1946]
Below are comments on the `open-lineage-services-api` module:
* `OpenLineageConnectorBase` should at least implement `OpenLineageGraphStore` as the server-side call casts the connector to this interface.  If the `BufferGraphStore` and `MainGraphStore` interfaces are designed to represent two different connectors then there should be a `MainGraphStoreConnectorBase` with `MainGraphStoreProviderBase` as well as a `BufferGraphStoreConnectorBase` with `BufferGraphStoreProviderBase` instead of `OpenLineageConnectorBase` with `OpenLineageProviderBase`.
* `LineageResponse` class inherits from `OpenLineageAPIResponse` but not listed in the `OpenLineageAPIResponse`'s `@JsonSubTypes` annotation.

Comments on the `open-lineage-services-client`
* The client does not take an NPA userId/Password so not setting security in header.  It is calling restTemplate directly so exceptions are not propertly processed.  It should ideally use the REST Client Connector.
* Some methods return response objects (eg `VoidResponse`).  These response objects should be processed - turning the exception details into a real exception and returning responses as if there was no REST inteface inbetween.  For example a VoidResponse is used on REST call for a client method that has a void return type.  LineageResponse is used on a REST call for a clinet method that has a Lineage return type.

Comments on the JanusGraphConnector (in adapters)
* JanusConnectorException should be a checked exception declared on the OpenLineageGraphStore interface.
* No README.md to help understand the code and what it is for (hard to find the actual connector implementations).  New module not linked to from parent README.md
* No `<name>` or `<description>` tags in the pom file

Comments on open-lineage-services-server
* `JobConfiguration` stores the buffer graph as a static - this will not work in a multi-tenent deployment.
* `OpenLineageRestServices` is swallowing exceptions and not reporting to caller for many of its methods.  For example, what happens if the serverName is incorrect?  In addition, the userId is not being passed to the handler to validate the user is allowed to access this service.

Comments on open-lineage-services-spring
* `exportGraph()` method returns a string - not following FFDC coding standards.
```
    /**
     * Return an entire graph, in GraphSON format.
     *
     * @param userId     calling user.
     * @param serverName name of the server instance to connect to.
     * @param graph      MAIN, BUFFER, MOCK, HISTORY.
     * @return The queried graph, in graphSON format.
     */
    @GetMapping(path = "/export/sources/{graph}", produces = {MediaType.APPLICATION_JSON_VALUE})
    public String exportGraph(@PathVariable("userId") String userId,
                              @PathVariable("serverName") String serverName,
                              @PathVariable("graph") String graph) {
        return restAPI.exportGraph(serverName, userId, graph);
    }
```

General comments:
 * No Javadoc

**Comment by GuyAckermans** [comment]
Hi Mandy, thank you for your review. All points should be addressed from PR #2303 on.
