### ISSUE TITLE
How to attach valid values to new schema structure

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#1955]
Valid value Sets define a list of valid values for a field.
https://egeria.odpi.org/open-metadata-publication/website/open-metadata-types/0545-Reference-Data.html

Typically the type of the field is a primitive value such as a string.

The valid value set can be attached to any referenceable so it could be attached to either the schema type or the schema attribute.  It would seem logical to me that the valid value set is attached to the schema type.  However, in the new scheme, the type may be a classification - particularly if it is a primitive.

We could
* add a guid string to the pimitive type classification
* create a new schema type called Enum that is linked explicilty to the schema attribute (ie the classification is not known).  This Enum schema type would have the valid values relationship.
* connect valid values set to schema attributes
* something else.

I am in favour of the Enum Schema Type - but was interested in others thoughts.

**Comment by cmgrote** [comment]
I think I'm also in favour of that sort of approach.  As an alternative to a new schema type, could we have an `Enum` relationship with one endpoint being a schema attribute (*) and the other a valid values set (1)?

I could imagine such a relationship might also have a property like `demandsStrictAdherence` that when `true` would imply the values for the schema attribute must be one from the valid values set, while when `false` would imply that the valid values set is more "guidance" and other values could also be permitted (?)

**Comment by mandy-chessell** [comment]
We already have the relationship - the question is where to attach it to the schema structure.

I like the `demandsStrictAdherence` property - I will add it and make the default `true`.

**Comment by cmgrote** [comment]
> We already have the relationship - the question is where to attach it to the schema structure.

Aha, ok, I thought so but my memory was failing me (and not easily finding it in the archive)...

Probably helpful to look at some illustrative examples on the functionality call, assuming you've already diagrammed the idea(s)...  But to illustrate in some sort of simple / naive textual way for the moment, the proposal would be something like this:

- SchemaAttribute
  - _relationship_
- _NewEnumSchemaType_
  - _EnumRelationship_
- ValidValuesSet

... ensuring that we are only ever linking the _EnumRelationship_ to a SchemaType (in this case a new schema type to represent an enumeration)

Whereas the alternative re-using the "simplified" schema types the structure could be something like:

- SchemaAttribute (+ TypeEmbedded classification)
  - _EnumRelationship_
- ValidValueSet

... but we'd need to allow linking the _EnumRelationship_ to a SchemaAttribute directly (or more generally to a SchemaElement if it could be applied to both a SchemaType and a SchemaAttribute), or to avoid the need for this some sort of "implied" or loose relationship by GUID captured in the TypeEmbedded classification itself.

One other question: is this all in addition to, or as a potential replacement of the `ValidValueAssignment` relationship that exists today between `Referenceable` and `ValidValueSet` (which would therefore cover the latter example already, I think)?

I'm initially not too keen on adding extra layers again, but also suspect that enumerations will probably be relatively uncommon so maybe won't be too bad in terms of "exploding" the number of relationships, etc -- so think I could probably be convinced either way 🤷‍♂

**Comment by mandy-chessell** [comment]
@cmgrote The relationship we have is the `ValidValueAssignment`.  I am coding its use at the moment which is why I rasied this issue to discuss how to attach this relationship to the schema structure :)

**Comment by mandy-chessell** [comment]
The decision from the call is to create an EnumSchemaType that will be used for schema where the definition of the attribute as an Enumeration is explicit, such as in Avro.  The valid values set is then linked to the EnumSchemaType.

The other use case that we discussed is when the valid values set represents the discovered set of values through metadata discovery.  In this case, the valid values set can be connected to the schema attribute.
