### ISSUE TITLE
Ensure that the OMRS code does not skip properties in instances that have come from a future release

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#1956]
The Jackson used by the OMRS code is configured to ignore properties it does not understand.  This means that if an entity from a future release is sent via an event to a back-level OMRS server then any additional header fields are ignored.

This is good up to a point - certainly better than raising an error.  The OMRS only knows how to make use of the header properties that were defined when it was written and so the other fields are irrelevant to it.   However this is not good enough.

The header information is used by the OMRS to control the protocol.  Where these header fields are set up in the master to help it manage the mapping to its real repository, they need to be present in any copy it receives.  If the back level OMAS strips out these fields in say an entity mastered in this future release and then creates an entity proxy from it for a relationship, when the new relationship is sent to the rest of the cohort, the master is not able to map the relationship back to its real entity.

We need to fix this in 1.2 at least for events - and possibly back port it to 1.1.  Fixing this for the REST API needs to be in place by 1.3.

**Comment by mandy-chessell** [comment]
Graham and I discussed this problem yesterday.  Removing Jackson from the event parsing and creating a new parser that correctly preserves extra fields in a map in the instance header inbound and puts them back outbound needs to be part of the fix.  This parser is not too hard to write and would give us the assurance for the future.

We also had an idea of defining some additional repository helper methods to create an instance properties object (called the coreProperties) and populate it from the header.  This could be used by real repository connectors to manage find match properties that refer to header properties and to simplify storing an arbitrary set of header properties.

**Comment by mandy-chessell** [comment]
This issue was inspired by #1862

**Comment by cmgrote** [comment]
Do we also need to be wary about any potential security implications?  I would assume that generally not allowing unknown properties is a "good thing" because it limits the potential for someone to "inject" values into a payload -- if we arbitrarily de-serialize and forward anything & everything could this be opening an injection surface?

**Comment by mandy-chessell** [comment]
This is a very good point - we can not open up a security hole in the interests of backward compatibility.

If we can not have the back level server arbitrarily managing extra properties then we need to prevent it from saving the reference copy.  Each event has a version number.  We should increase the version number and ignore all events that are of a higher version number than the server is able to handle.

Since we have the instances and typeDefs coming over the REST APIs too, there should be a version number in the audit header and the local repository can also reject instance and typeDefs it does not understand.

I like this better I think.
