### ISSUE TITLE
How does an individual find out more about the data sources they are using.

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#196]
Using Coco Pharmaceuticals persona to drive the scenario, provide Egeria capability with supporting resources to enable Callie Quartile (Data Scientist) to access all of the known information about a data source she is attempting to use.

**Comment by mandy-chessell** [comment]
** Outline of the scenario **
In this scenario, Callie Quartile is searching for company-owned data sets about employees - she wants to build a birthday card service to send an electronic birthday card to each employee on the appropriate day.   Part of this project is to find appropriate data.  The steps to do this are:

* She issues a search request on the company's asset catalog and discovers the employee directory data set.  This has the public information about all employees ... very interesting !!
* She decides to look at this in more detail and extracts the connection information and instantiates the connector to the data set.
* Through the connector she is able to see detailed metadata about the employee directory data set and can query the data itself.
* She decides this is a good data set and adds it to her list of favourites.
* She also adds feedback on the description and classification.

**Comment by planetf1** [comment]
is this fixed for 1.2?

**Comment by planetf1** [comment]
If incomplete this won't make 1.2 so moving to 1.3
