### ISSUE TITLE
Issue with findEntitiesByProperty with exact match

### ISSUE THREAD

**Issue by ruxandraRosu** [odpi/egeria#1960]
I am having an issue retrieving an existing entity using exactMatchPattern. I have an Endpoint entity with network address similar to "xyz.OMTD.COM". I am trying to retrieve it using findEntitiesByProperties with matchProperties containing getExactMatch("xyz.OMTD.COM"). No entity is returned with this call.

**Comment by ruxandraRosu** [comment]
Hi,
@grahamwallis @cmgrote I am not sure who to assign this to.

**Comment by mandy-chessell** [comment]
Which repository are you using?

**Comment by ruxandraRosu** [comment]
The entity I am looking is in atlas. I am still using the old atlas code  with latest egera code(not the latest connector), is this causing the issue?

**Comment by grahamwallis** [comment]
OK - that's going to be one for Chris to look at but I am happy to help if needed

**Comment by cmgrote** [comment]
> I am still using the old atlas code with latest egera code(not the latest connector), is this causing the issue?

Most likely that's the problem, as the connector itself needed to be updated to use the new helper methods internally (since Atlas doesn't understand Java regular expressions)...  How old are we talking?

**Comment by grahamwallis** [comment]
When you say the "old atlas code" I hope that's not the old, old native connector - that hasn't been maintained since about February. That code really should not be used.

**Comment by ruxandraRosu** [comment]
I will close this issue, on my laptop I still have the old native code.
