### ISSUE TITLE
Add documentation for new CTS test cases

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#1998]

**Comment by grahamwallis** [comment]
Please see PR #1999

**Comment by planetf1** [comment]
Looks like this can be closed? closing ....

**Comment by cmgrote** [comment]
I think we're still missing the documentation for the latest (read-only) search test cases:

https://egeria.odpi.org/open-metadata-conformance-suite/docs/repository-workbench/test-cases/repository-entity-sharing-property-search-test-case.md

... is referred to in the CTS output, but the link gives a 404 (and can't see any corresponding markdown in master)

**Comment by grahamwallis** [comment]
Fixed by #2097
