### ISSUE TITLE
server-chassis add jwt token authentication for REST calls APIs

### ISSUE THREAD

**Issue by bogdan-sava** [odpi/egeria#2002]
Spring security will be added in spring-boot application.
All the rest calls will require token authentication. For the time being SigningKey of the jwt will be an application property. 

The SpringRESTClientConnector needs to support jwt authentication. Token to be used needs to be added to configuration.

**Comment by bogdan-sava** [comment]
![JwtAuthentication](https://user-images.githubusercontent.com/40362260/68694042-15a0c800-0581-11ea-8e45-4e6d1ea0dc7c.png)

**Comment by bogdan-sava** [comment]
validate NPA username for server method is needed.
Not sure if platform-services or admin-services is the right place 
@mandy-chessell what do you think?

**Comment by mandy-chessell** [comment]
A server's NPA userId is in its config doc.  It is used on outbound REST calls when we are encoding the NPA in the HTTP header.

Each server has a metadata security connector.  This is where it can validate that the NPA is entitiled to issue requests to this server.

**Comment by bogdan-sava** [comment]
![JwtAuthentication](https://user-images.githubusercontent.com/40362260/68764912-4c7bea00-0624-11ea-874a-e6260afab554.png)

**Comment by bogdan-sava** [comment]
There are 4 tasks to be completed in order to activate token authorization for NPAs.

1. Add server side filter to check the request has an authorization header. For the moment Basic Auth and API token will be supported
2. Rest connector should support adding authorization header on requests
3. Config document of the server should contain the authorization information NPA credentials for basic authentication or NPA username and secret key used to parse token
4. Registration of the server in cohort should publish Authorization type used by the server. Supported values are: NO_AUTH, BASIC, API_KEY

**Comment by bogdan-sava** [comment]
**1. Server side diagram** 

![JwtAuth](https://user-images.githubusercontent.com/40362260/69056996-c1cb2e80-0a19-11ea-83da-5139d340133b.png)

**Comment by bogdan-sava** [comment]
2. Client side perspective
Rest Client Connectors should initialized according to auth method required by the remote be able to add header auth token to the requests.

![ClientView](https://user-images.githubusercontent.com/40362260/69068967-5c356d00-0a2e-11ea-80bb-5d11cc0beb81.png)
