### ISSUE TITLE
SchemaType optimizations for Asset Lineage OMAS

### ISSUE THREAD

**Issue by cong78** [odpi/egeria#2003]
Similar issues to Data Engine OMAS #1826 that some changes need to be done for AL OMAS to adapt the schema types optimizations defined in #1669 & #1317. 

@DimitriosMaimaris I will add more actions need to be done later so you can review the changes.

@popa-raluca we also need to have the updated payload from DE OMAS to have the updated schema type optimizations to test the asset lineage changes. I will keep track on the issue you are doing.

**Comment by popa-raluca** [comment]
@cong78 the old payloads should be ok to use for now. Only change needed is to add the external data engine source name in the payload.
When we will integrate with the new igc-connector and data stage proxy engine we might need to update them, but for now we can test our dev work with the old payloads.

**Comment by cong78** [comment]
The PR has been merged and I will close this issue.
