### ISSUE TITLE
Unable to update external entitties with local graph repository

### ISSUE THREAD

**Issue by popa-raluca** [odpi/egeria#2012]
DataEngine OMAS fails on update after pulling the latest changes from master. The entities are created as external - for a data engine that owns them, but they should be able to be updated as well.
There is no method for updating external entitties in OMRSMetadataCollection, so I'm not sure how I can do this if the updateEntity method can't be used

**Comment by popa-raluca** [comment]
Did some further investigations, and the problem apears because the enternal entity has the InstanceProvenanceType set to UNKNOWN on getEntitySummary methods.
Looks like the problem is in `GraphOMRSMapperUtils.mapProvenanceOrdinalToEnum(Integer provenanceOrdinal)` , the ordinal for` InstanceProvenanceType. EXTERNAL_SOURCE ` is actually 6

**Comment by grahamwallis** [comment]
Hi Raluca - Sorry about that - good spot and thanks for diagnosing the problem. I would rather not have the mapping methods in the utils class but to try to be efficient the enum values are stored using their ordinal so need some way to reconstitute them. 

Please see PR #2013

**Comment by mandy-chessell** [comment]
Is this complete?
