### ISSUE TITLE
open lineage UI rest api has no java doc / swagger

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#2016]
The Open lineage UI class and rest APIs are not java doc'ed. I could work out what some of them were but I was not sure about what the end2end API call was doing. I see
getEndToEndLineage(String userId, View view, String guid)  {
        LineageVerticesAndEdges response = openLineageClient.lineage(userId, graphName, Scope.END_TO_END, view, guid);
        return processResponse(response);

The lineage method has javadoc "   * Returns the graph that the user will initially see when querying lineage. In the future, this method will be
     * extended to condense large paths to prevent cluttering of the users screen. The user will be able to extended
     * the condensed path by querying a different method."

I find this java doc confusing, it does not seem like an API definition; 
-I do not understand what it means by " the graph that the user will initially see".  In what context?
-I suggest explaining what lineage is here somewhere. 
-I am not sure what you mean by an end; I suggest this is defined if it is an important concept for the API. Do we need destinations and ends or are they the same.
- it mentions paths, if this is an import concept for the API, this should be defined. 
- we refer to future - this should be tracked as a git issue and the issue number be put in the code. 

Maybe something like "Lineage of an asset is it's information supply chain; it extends back to where the asset was sourced (the ultimate source) and where it is destined (the ultimate destination). The lineage consists of assets, processes |(and ..?). This call returns a graph in the form of a map of lists of edges and nodes. Edges and nodes are graph concepts; edges being relationships and nodes being the things that are related together. The nodes can represent an asset or process (or..) as defined by the node type. The edges are directed relationships between the nodes (are there types here as well?).

**Comment by ruxandraRosu** [comment]
Hi @davidradl ,
Are you running with latest master? There should be javadoc on the OL APIs, I will try to enhance it.

**Comment by davidradl** [comment]
Hi @ruxandraRosu, sorry I am running a bit back level. I hope my feedback is helpful anyway,   David.

**Comment by ruxandraRosu** [comment]
Hi @davidradl,

I've added swagger to EgeriaUIPlatform in PR https://github.com/odpi/egeria/pull/1995.
