### ISSUE TITLE
open lineage UI api end point names could be more informative

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#2017]
I notice that many of the the open lineage UI rest api paths have the form /entities/{guid}/....
I suggest that entities be changed to assets. I suggest the concept of entities it not exposed in this API / UI, as this is an asset orientated UI / API.

For /entities/{guid}/glossary-lineage") I suggest this is changed to 
/glossary-term/{guid}/lineage")

I am wondering whether lineage should be plural. It seems there could be more than one ultimate destination or ultimate source - so shouldn't the rest end points be plural. In this case should the return type be a set or list of maps.

**Comment by mandy-chessell** [comment]
May be `glossary-term` should be `glossary-terms`?

**Comment by GuyAckermans** [comment]
It was my understanding that we don't call columns and tables (which is what is queried here) assets, is that incorrect?

Right now only a single endpoint is used to query lineage, do I understand correctly that your suggestion is to make a separate endpoint for glossary lineage?
