### ISSUE TITLE
Asset catalog OMAS use of concept term is confusing

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#2019]
org.odpi.openmetadata.accessservices.assetcatalog.model contains a class called Term - it is exposed in the search API. The Term is a list of AssetElements. I had assumed the word Term meant a glossary term. I suggest renaming this class - maybe to AssetElementList or AssetElements.

**Comment by planetf1** [comment]
++ I noticed this when debugging an issue with AssetCatalog client, and first-pass the naming confused me.

**Comment by ruxandraRosu** [comment]
This is to be handled on asset-catalog-omas, assigning this to Daniela.

**Comment by danielaotelea** [comment]
Hi! Based on https://github.com/odpi/egeria/pull/2033, can we close this issue?

**Comment by davidradl** [comment]
closing
