### ISSUE TITLE
change the Asset catalog OMAS to not expose type guids

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#2037]
OMASes should not be exposing type guids, as types can be identified by name. The OMAS caller should not have to manage type guids.

**Comment by danielaotelea** [comment]
Added in the PR https://github.com/odpi/egeria/pull/2140

**Comment by danielaotelea** [comment]
Hi! The Asset Catalog OMAS is not exposing the type def GUID anymore. Can we close this issue?
