### ISSUE TITLE
Exceptions seen in OMAS topic listeners

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#2040]
During running of the CTS tests I have been seeing various exceptions reported by OMAS topic listeners. 

For example:

Mon Nov 18 13:30:18 GMT 2019 cocoMDS1 Exception OMRS-AUDIT-0101 Unable process an incoming event {"class":"OMRSEventV1","protocolVersionId":"OMRS V1.0","timestamp":1574083818852,"originator":{"metadataCollectionId":"69c99b46-1742-43be-9c6e-4d4af55378b0","serverName":"cocoMDS1","serverType":"Graph Metadata Repository"},"eventCategory":"INSTANCE","instanceEventSection":{"class":"OMRSEventV1InstanceSection","protocolVersionId":"OMRS V1.0","eventType":"NEW_ENTITY_EVENT","typeDefGUID":"d81a0425-4e9b-4f31-bc1c-e18c3566da10","typeDefName":"TabularColumn","entity":{"class":"EntityDetail","type":{"class":"InstanceType","typeDefCategory":"ENTITY_DEF","typeDefGUID":"d81a0425-4e9b-4f31-bc1c-e18c3566da10","typeDefName":"TabularColumn","typeDefVersion":1,"typeDefDescription":"A column attribute for a table oriented data structure.","typeDefSuperTypes":[{"guid":"1a5e159b-913a-43b1-95fe-04433b25fca9","name":"SchemaAttribute"},{"guid":"718d4244-8559-49ed-ad5a-10e5c305a656","name":"SchemaElement"},{"guid":"a32316b8-dc8c-48c5-b12b-71c1b2a080bf","name":"Referenceable"}],"validInstanceProperties":["qualifiedName","additionalProperties","anchorGUID","displayName","description","position","minCardinality","maxCardinality","allowsDuplicateValues","orderedValues","defaultValueOverride","nativeClass","name"]},"instanceProvenanceType":"LOCAL_COHORT","metadataCollectionId":"69c99b46-1742-43be-9c6e-4d4af55378b0","metadataCollectionName":"cocoMDS1","createdBy":"OMAGServer","createTime":1574083818773,"version":1,"guid":"51dd71b4-cb0b-4b4a-9d5e-031aa2571396","properties":{"class":"InstanceProperties","instanceProperties":{"defaultValueOverride":{"class":"PrimitivePropertyValue","instancePropertyCategory":"PRIMITIVE","primitiveDefCategory":"OM_PRIMITIVE_TYPE_STRING","primitiveValue":"TestdefaultValueOverrideValue"},"qualifiedName":{"class":"PrimitivePropertyValue","instancePropertyCategory":"PRIMITIVE","primitiveDefCategory":"OM_PRIMITIVE_TYPE_STRING","primitiveValue":"TestqualifiedNameValue"},"displayName":{"class":"PrimitivePropertyValue","instancePropertyCategory":"PRIMITIVE","primitiveDefCategory":"OM_PRIMITIVE_TYPE_STRING","primitiveValue":"TestdisplayNameValue"},"description":{"class":"PrimitivePropertyValue","instancePropertyCategory":"PRIMITIVE","primitiveDefCategory":"OM_PRIMITIVE_TYPE_STRING","primitiveValue":"TestdescriptionValue"},"orderedValues":{"class":"PrimitivePropertyValue","instancePropertyCategory":"PRIMITIVE","primitiveDefCategory":"OM_PRIMITIVE_TYPE_BOOLEAN","primitiveValue":true},"allowsDuplicateValues":{"class":"PrimitivePropertyValue","instancePropertyCategory":"PRIMITIVE","primitiveDefCategory":"OM_PRIMITIVE_TYPE_BOOLEAN","primitiveValue":true},"maxCardinality":{"class":"PrimitivePropertyValue","instancePropertyCategory":"PRIMITIVE","primitiveDefCategory":"OM_PRIMITIVE_TYPE_INT","primitiveValue":42},"minCardinality":{"class":"PrimitivePropertyValue","instancePropertyCategory":"PRIMITIVE","primitiveDefCategory":"OM_PRIMITIVE_TYPE_INT","primitiveValue":42},"nativeClass":{"class":"PrimitivePropertyValue","instancePropertyCategory":"PRIMITIVE","primitiveDefCategory":"OM_PRIMITIVE_TYPE_STRING","primitiveValue":"TestnativeClassValue"},"anchorGUID":{"class":"PrimitivePropertyValue","instancePropertyCategory":"PRIMITIVE","primitiveDefCategory":"OM_PRIMITIVE_TYPE_STRING","primitiveValue":"TestanchorGUIDValue"},"name":{"class":"PrimitivePropertyValue","instancePropertyCategory":"PRIMITIVE","primitiveDefCategory":"OM_PRIMITIVE_TYPE_STRING","primitiveValue":"TestnameValue"},"position":{"class":"PrimitivePropertyValue","instancePropertyCategory":"PRIMITIVE","primitiveDefCategory":"OM_PRIMITIVE_TYPE_INT","primitiveValue":42}},"propertyCount":12,"propertyNames":["minCardinality","nativeClass","defaultValueOverride","qualifiedName","displayName","anchorGUID","name","description","orderedValues","position","allowsDuplicateValues","maxCardinality"]},"status":"ACTIVE"}}} due to exception org.odpi.openmetadata.accessservices.assetlineage.ffdc.exception.AssetLineageException: REPOSITORY-HANDLER-400-003 An unexpected error was returned by the property server during getEntityDetails request for open metadata access service Asset Lineage OMAS on server cocoMDS1; message was OMRS-REST-API-503-006 A client-side exception was received from API call getEntityDetail to repository In-memory repository@CTS1.  The error message was CLIENT-SIDE-REST-API-CONNECTOR-503-002 A client-side exception org.springframework.web.client.ResourceAccessException was received by method getEntityDetail from API call https://localhost:8080/servers/CTS1/open-metadata/repository-services/users/{0}/instances/entity/{1} to server In-memory repository@CTS1 on platform https://localhost:8080/servers/CTS1.  The error message was I/O error on GET request for "https://localhost:8080/servers/CTS1/open-metadata/repository-services/users/OMAGServer/instances/entity/51dd71b4-cb0b-4b4a-9d5e-031aa2571396": Unrecognized SSL message, plaintext connection?; nested exception is javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection? from listener org.odpi.openmetadata.accessservices.assetlineage.listeners.AssetLineageOMRSTopicListener@6626a384

It is not always the AssetLineage topic listener that reports them. Other OMASs exhibit similar behaviour.

I have not done any investigation - just wanted to capture.

**Comment by cong78** [comment]
Hi Graham I will take a look and get back to you. :)

**Comment by mandy-chessell** [comment]
In OMRS I have added a wrapper around each of the topic listeners so it is possible to isolate which topic listeners are producing exceptions - this helped identify #2311.  It also prevents an exception in one topic listener from disrupting the processing of another.

**Comment by planetf1** [comment]
@grahamwallis I think I noticed a few of those recently, though I didn't persue at the time and they were asset lineage. I'll check again next time I run. The CTS likely stresses things much more.

**Comment by grahamwallis** [comment]
I have not seen any of these exceptions for a while now. Anybody else?
