### ISSUE TITLE
CTS not catching FNS on addRelationship for graph query tests

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#2046]
As one of the first steps of the graph query tests (`TestGraphQueries`), a few method calls deep there are calls to `addEntity` and `addRelationship`, both of which could throw `FunctionNotSupportedException`s that should not be fatal errors due to their optionality.

Currently nothing in the test catches these as expected exceptions, and instead they're logged as an unexpected exception.

(Not sure if this has any knock-on impact to other tests, or is simply a nice-to-have to cleanup?)

**Comment by planetf1** [comment]
Fixed in PR above - both 1.2 & master
