### ISSUE TITLE
Asset Lineage OMAS - Logic handling of entity and relationship deletion OMRS instance events

### ISSUE THREAD

**Issue by cong78** [odpi/egeria#2053]
Currently we only implemented methods for the entity and relationship creation / update events from OMRS instance events. We need to investigation what it means if we have deletion events and how we can handle them properly to give correct asset lineage context. 

We need to take care two scenarios: 
- Update lineage context
Some entities and relationships will be added, removed or updated, which will result in an updated lineage graph. 
- Delete lineage context
If an ETL/data processing job is retired or de-active, the data lineage should be also marked as invalid or outdated as well from the UI front-end.

**Comment by popa-raluca** [comment]
@cong78 You can have delete events for update - if the update payload doesn't have some entitties that were present in the initial payload and the update semantic for the payload is REPLACE or not specified. You can check https://github.com/odpi/egeria/issues/1684 for more details

**Comment by cong78** [comment]
> @cong78 You can have delete events for update - if the update payload doesn't have some entitties that were present in the initial payload and the update semantic for the payload is REPLACE or not specified. You can check #1684 for more details

Hi Raluca, just checked the issue and seems logical. But I think we need to differentiate UPDATE and DELETE the ETL job as the first one only delete few entities with relationships and second one will remove everything for that lineage. I am not sure what would happen if an end-user de-active an entire ETL job in current data stage but if an ETL job is not valid anymore I don't think we should show it from lineage UI.

**Comment by cong78** [comment]
Adding Dimi and Raluca.
