### ISSUE TITLE
Fix problem in CTS

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#2056]

**Comment by grahamwallis** [comment]
CTS was skipping tests. Whilst fixing this I am also adding further null properties protection (for both entities and relationships) in the read-only test cases (extending what is in #2047).

Also catching FunctionNotSupported in the Graph Queries test case (for #2046) so now discovered property should  be set to disabled, and test case should return.

**Comment by grahamwallis** [comment]
Fixes are in PR #2062

**Comment by cmgrote** [comment]
> Fixes are in PR #2062

... for master -- just to confirm that the same change will be made to the 1.2 branch (to enable all tests)?  And presumably that means we need to hold on releasing 1.2 to MC? cc: @planetf1

**Comment by planetf1** [comment]
1.2 won't go to MC yet anyway. I want to run the cts .... and yes there's. PR for this https://github.com/odpi/egeria/pull/2073

**Comment by cmgrote** [comment]
I'm discovering a number of other remaining CTS bits we might want to look at as well -- raising a few more issues for those to discuss how we want to handle...

**Comment by planetf1** [comment]
Closing - PRs have gone into 1.2 & master for the reported issue
