### ISSUE TITLE
TypeDefAttribute name clashes with core properties

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#2099]
There are a number of types that have type-defined attributes whose names clash with core properties in the InstanceAuditHeader.

They are:
- [x] SoftwareServerPlatform (type, version)
- [x] SoftwareServer (type, version)
- [x] SoftwareServerCapability (type, version)
- [x] CloudPlatform (type)
- [x] CloudTenant (type)
- [x] CloudService (type)
- [x] Comment (type)
- [x] GraphStore (type)
- [x] LogFile (type)
- [x] Database (type, version)
- [x] DatabaseServer (type, version)
- [x] MetadataRepository (type)
- [x] MetadataServer (type)
- [x] RepositoryProxy (type)
- [x] BusinessCapability (type)
- [x] ~~SchemaAttributeType (type)~~ -- this is a relationship endpoint, so not a conflict (leaving as-is)
- [x] DataStore (createTime)
- [x] DataSourcePhysicalStatusAnnotation (createTime)
- [x] EnterpriseAccessLayer (metadataCollectionId)
- [x] MetadataCollection (metadataCollectionId)
- [x] ExternalReference (version)
- [x] PropertyFacet (version)
- [x] CohortMember (version)
- [x] ImplementationSnippet (version)
- [x] PolicyAdministrationPoint (type) (1.7)
- [x] PolicyDecisionPoint (type) (1.7)
- [x] PolicyEnforcementPoint (type) (1.7)
- [x] PolicyInformationPoint (type) (1.7)
- [x] PolicyRetrievalPoint (type) (1.7)

For the time being core property search is disabled in graph repository to work around the above. When the attributes are renamed,, core property search should be re-enabled.

(CG edit: after much head-scratching on debugging a problem, updated the list above to a complete list -- note in particular that `type` clashes with the name of a property in InstanceAuditHeader, and appears in many other open metadata types... Would it be easier to update the InstanceAuditHeader property to be `instanceType` instead of `type` (or would this break backwards-compatibility?))

**Comment by grahamwallis** [comment]
This issue is waiting for the type def patch capability to be implemented

**Comment by grahamwallis** [comment]
Keep open

**Comment by cmgrote** [comment]
Agreed on August 4th workshop to rename the properties of the open types themselves (deprecate existing, add a new property) -- do not rename any of the header properties.

**Comment by cmgrote** [comment]
Properties are all deprecated and added in the open types archive itself; still to do:

- [ ] updates to diagrams to rename the properties

Holding those updates for @mandy-chessell 's push of type updates (which will involve various updates to types and therefore the diagrams).
