### ISSUE TITLE
How does an organization manage a digital service through its lifecycle?

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#211]
Using Coco Pharmaceuticals persona to drive the scenario, provide Egeria capability with supporting resources to manage the governance aspects of each stage of evolution of a [digital service](https://odpi.github.io/data-governance/digital-services/).

**Comment by mandy-chessell** [comment]
This is work in progress

**Comment by wbittles** [comment]
@mandy-chessell can you can assign this to me ?

**Comment by mandy-chessell** [comment]
Keep open

**Comment by planetf1** [comment]
I think this should be kept open @wbittles ? Could be worth keeping a summary in here
