### ISSUE TITLE
Increase notebook memory for containers

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#2118]
The CTS notebook requires a higher than default data limit.

This is referred to in the text as
jupyter notebook --NotebookApp.iopub_data_rate_limit=1.0e10 

For the docker-compose & k8s environments this should be done in our templates so the user
needs to do nothing

For the local environment it would be useful if the notebook could check this parm, though that may not be feasible

Fix in master only

**Comment by planetf1** [comment]
Note also that the 'lab' interface is preferred so the text could be updated

**Comment by grahamwallis** [comment]
What's the "lab interface"?

**Comment by planetf1** [comment]
> What's the "lab interface"?

'jupyter lab' (if you have the module/are up to date). It just looks prettier so is how the compose & k8s environments are setup. No significant functional issue. https://towardsdatascience.com/jupyter-lab-evolution-of-the-jupyter-notebook-5297cacde6b

**Comment by planetf1** [comment]
Rolled into #2119 so closing
