### ISSUE TITLE
Swagger docs do not document requirement for 'class' in JSON request payload

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#213]
Currently our swagger docs are misleading.

An Example. addEntity is documented at http://localhost:8080/swagger-ui.html#!/omrs45repository45resource/addEntityUsingPOST

This gives a request body that does not include the required 'class: EntityCreateRequest' at the top level, and indeed the required classes throughout the structure (with the current Jackson mappings)
 
This is a common pattern through OMRS, and one should be able to use the swagger docs as a guide for using the API.

Suspecting some more swagger tagging is needed

Further info:
The error returned using the sample swagger is

```
{
    "timestamp": "2018-09-19T07:39:39.124+0000",
    "status": 400,
    "error": "Bad Request",
    "message": "JSON parse error: Missing type id when trying to resolve subtype of [simple type, class org.odpi.openmetadata.repositoryservices.rest.properties.EntityCreateRequest]: missing type id property 'class'; nested exception is com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Missing type id when trying to resolve subtype of [simple type, class org.odpi.openmetadata.repositoryservices.rest.properties.EntityCreateRequest]: missing type id property 'class'\n at [Source: (PushbackInputStream); line: 52, column: 1]",
    "path": "/open-metadata/repository-services/users/me/instances/entity"
}
```

**Comment by mandy-chessell** [comment]
The documentation should also direct people away from calling this REST API - it is a private REST API for OMRS.

Nevertheless, this issue should address the swagger for all OMASs too because they are (or should be) using the same style of payload.

**Comment by planetf1** [comment]
As an example the following (simple) payload works for addEntity. It was very unclear how to get to this from the documentation 

```
{
    "class": "EntityCreateRequest",
    "entityTypeGUID": "0921c83f-b2db-4086-a52c-0d10e52ca078",
    "initialClassifications": [
    {
      "class": "Classification",
      "name": "Confidentiality"
    }
  ]
}
```

**Comment by planetf1** [comment]
Closing this in lieu if #1124 which will address improvements to swagger docs
