### ISSUE TITLE
OMRS: Improve exception when incorrect classification name passed on addEntity

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#215]
When trying to create a new entity through the OMRS REST API addEntity operation, if an incorrect classification such as:

```
  "initialClassifications": [
    {
      "class": "Classification",
      "name": "confidentiality"
    }
```

is passed (since the correct name of the classification is 'Confidentiality' - ie with an upper case C ....

then the returned response is:

```
{
    "timestamp": "2018-09-21T10:58:23.420+0000",
    "status": 500,
    "error": "Internal Server Error",
    "message": "OMRS-LOCAL-REPOSITORY-503-007 An OMRS repository connector myserver has passed an invalid parameter to the repository content manager isValidClassificationForEntity operation as part of the addEntity request",
    "path": "/open-metadata/repository-services/users/me/instances/entity"
}
```

The check occurs in isValidTypeCategory (OMRSRepositoryContentManager)
`        TypeDef   typeDef = knownTypeDefNames.get(typeName);
`
which shows the correct entry is
`"Confidentiality" -> "ClassificationDef{validEntityDefs=[EntityDef{superType=null, description='An open metadata entity that has a unique identifier.', descriptionGUID='null', origin='bce3b0a0-662a-4f87-b8dc-844078a11a6e', createdBy='ODPi Egeria (OMRS)', updatedBy='null', createTime=Thu Jan 18 22:04:00 GMT 2018, updateTime=null, options=null, externalStandardMappings=null, validInstanceStatusList=[InstanceStatus{ordinal=15, name='Active', description='The instance is approved and in use.'}, InstanceStatus{ordinal=99, name='Deleted', description='The instance has been deleted and is no longer available.'}], initialStatus=InstanceStatus{ordinal=15, name='Active', description='The instance is approved and in use.'}, propertiesDefinition=[TypeDefAttribute{attributeName='qualifiedName', attributeType=PrimitiveDef{primitiveDefCategory=PrimitiveDefCategory{code=11, name='string', javaClassName='java.lang.String', guid='b34a64b9-554a-42b1-8f8a-7d5c2339f9c4'}, category=AttributeTypeDefCategory{typeCode=1, typeName='Primi"`

Since specifying an incorrect classification isn't that uncommon I would guess, I think a more unique exception would be helpful to allow the user to correct the request

Not checked what is returned from the client API.

Note that once the 'C' is corrected, this code then validates the classification correctly.

**Comment by mandy-chessell** [comment]
I am not sure wht the issue is here.  It is an internal logic error because the "user" is typically another OMRS.  An OMRS should never be flowing a type it has not validated.  The error message says that the error occured in isValidClassificationForEntity() and it was in invalid parameter.  What more are you expecting?

**Comment by planetf1** [comment]
On re-reading the text of the error I agree. There are a lot of potential parameters to get correct for addEntity so I was expecting to see invalid parameter be qualified by /which/ parameter. In this case the method name (isValidClassificationForEntity) should be ok to distinguish so will close
