### ISSUE TITLE
CTS report - enhancement suggestions

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#2164]
Currently the cts report (from the REST api) returns a report of the number of failed/pass/total etst cases, and details of each test - in a grouped format.

However, if this is to be a 'compliance report'  - or at least the underlaying evidence for, I would suggest we consider adding more information to the report such as

* CTS itself
 -> what git version was the driver code
 -> what was the start time of the test, when was the report generated
 -> What else can we report about the driving environment (platform, java version, cohort members etc)
* Technology under test
 -> What version was this (ideally for egeria repos this would include git commit, but needs to be more flexible given this is any tech - I don't think major version is enough)
 -> What configuration can we extract about the technology - configuration, deployment

Some of this could be done through docs, but the more that can be gathered by the actual test, the more suitable the results are for publishing, sharing & supporting.

Requires further discussion....

**Comment by cmgrote** [comment]
Good thoughts -- I think a few are probably already covered (here a snippet from the top of the test report):

```json
{
  "class" : "OpenMetadataConformanceTestLabResults",
  "testRunDate" : 1575540518760,
  "testResultsFromWorkbenches" : [ {
    "class" : "OpenMetadataConformanceWorkbenchResults",
    "workbenchId" : "repository-workbench",
    "workbenchName" : "Open Metadata Repository Test Workbench",
    "versionNumber" : "V1.0 SNAPSHOT",
    "tutType" : "Open Metadata Repository",
    "tutName" : "myserver",
    "profileResults" : [ {
```

So these are already there

- the start time of the test is already there (`testRunDate`)
- the version of the workbench that was run (`versionNumber`) -- interesting that this doesn't seem to have ever been updated (this example is from the v1.2 release?!)

I think the specific git commit of the workbench should be less important -- in general, we should only be considering CTS results from released versions, not snapshots, and therefore a specific version number (of a released version) for the CTS I think should be sufficient (once it's correct) (?)

For tracking my own results, I'm also capturing all of the `*.config` and `*.registrystore` files for the configuration of the technologies -- but I don't believe either of these captures the underlying platform or Java version details...

**Comment by grahamwallis** [comment]
I can see why the version is incorrect - it's a hard-coded string in the workpad. Do we have an existing way of dynamically stamping our build info such that at runtime we could retrieve the version number? I found references for how to use the maven resources plugin to stamp into a properties file, which might be good enough. Is there a better way?

**Comment by mandy-chessell** [comment]
The version number is not related to the release of Egeria - it is related to the release of the CTS.

**Comment by grahamwallis** [comment]
I thought we'd agreed that they were going to move in synchrony

**Comment by grahamwallis** [comment]
It would be easy to update the workpad string at each release, but a bit of a chore and likely to get forgotten sometimes.

**Comment by planetf1** [comment]
Interestingly when I switched versions from 1.1 - 1.2 - 1.3 (-SNAPSHOT, or dropping) I think I found everything, but of ciourse I never searched for 1.0-SNAPSHOT.

**Comment by planetf1** [comment]
And apogies for missing those extended details. I was only getting the TestLabReportResponse, which is the initial example covered in the CTS notebook. Good to see a little more info in OpenMetadataConformanceTestLabResults (maybe we need to clarify in the notebook too)

**Comment by planetf1** [comment]
Ideally I'd like to see the git version too. It's common in some tools including kubectl, helm etc.. especially helpful if we're running the cts daily. Ok our pipeline can also record the info, but even better if the generated asset is able to capture it in one result?

**Comment by grahamwallis** [comment]
Keep open...

**Comment by grahamwallis** [comment]
I taken a look at this issue with a view to adding things like OS, OS version, Java runtime version, etc to the report. It would be easy to discover and record these for the CTS Server, but possibly of dubious merit. I am thinking that the more interesting server is the SUT Server, and whilst we could augment the OMAGServerPlatform so that it discovers more about is runtime environment, we don't have an API (currently) that would allow the CTS Server to interrogate the SUT Server to find transfer this knowledge to the CTS, for inclusion in the test report. 

It seems to me that we could report the CTS configuration, although it is possibly quite a large object to include.

I'm not sure I understand what we mean by "git version". If we mean the number of the latest git commit, and if we have a way to capture that so it's discoverable at runtime, then as above I think we could report it for the CTS Server, which would show us the specific level of code for the Conformance Suite (only) but it would not currently be possible or the CTS Server to learn the value from the SUT Server. Also as @cmgrote said above, isn't the CTS major release the important factor?

I'm open to ideas but am not sure that there are any changes that jump out at me yet.

**Comment by planetf1** [comment]
Any thoughts @cmgrote - we now have some improved reporting in the cts. I wonder if capturing additional metadata is valuable?

**Comment by cmgrote** [comment]
It could be, but Graham's point is the key one: unless the TUT is running under the same OMAG as the CTS itself, we'd need to define an entire interface through which this additional metadata could be captured and passed from the TUT to the CTS -- given that we can currently automate the CTS through eg. Helm / k8s and collect similar information directly via that orchestration, I'm not sure it's worth the investment (at least at this point) to try to define an entirely new interface for this information within Egeria itself.

**Comment by planetf1** [comment]
Suggest we close this now if we have no plan to implement nor external requests
