### ISSUE TITLE
Open lineage janus connector - unnecessary dependency

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#2169]
In open lineage janus connector we have dependencies on
 - commons-logging
 - commons-codec
Both are defined as an exclusion for the dependency check

The code makes no reference explicitly, and compiles fine without the dependency
commons-logging defines an api, which is not used/imported

As such there's a few possibilties
 a) The components are needed at runtime. If that's the case we should probably change 'scope' to runtime 
 b) The components are needed at runtime, but provided by the environment - in which case they can likely be removed
 c) they are not needed - can be removed

Unfortunately I'm not sure how to verify the runtime behaviour of lineage services - do we have any cheat-sheet on verification beyond UTs? I wanted to verify we are not unnecessarily adding dependencies which can cause clashes & greater exposures 

I propose a PR which removes the dependency

cc: @DimitriosMaimaris @GuyAckermans

**Comment by GuyAckermans** [comment]
Can be removed as far as I'm concerned. Dimi?

**Comment by planetf1** [comment]
update made
