### ISSUE TITLE
AssetElement in Asset search API

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#2179]
I notice that the Asset search OMAS exposes a concept called AssetElement, a list of these are returned to the UI after a search.

1) I am not sure what AssetElement is as it does not have any javadoc, it subclasses Element, but is referred to in the UI methods as asset header. I am not sure what context and connection means here.
2) Element has 
"    private static final long serialVersionUID = 1L;

    private String guid;
    private String typeDefName;
    private String typeDefGUID;
    private String metadataCollectionId;
    private String name;
    private String createdBy;
    private Date createTime;
    private String updatedBy;
    private Date updateTime;
    private Long version;
    private String status;
    private String url;
    private Map<String, Object> properties;
    private List<Element> parentElement;"

I am thinking that metadataCollectionId and typeDefGUID should not be exposed to the caller of the OMAS - these are internal things. I think display name and qualified name could be included - I am not sure which name is. I am not sure what the url is.
3) I assume that AssetElement is an Element associated with an asset typedef. Is this correct? So would not include glossary terms.
4) parentElement is singular and points to a List. I am not sure what parent this means here. does parent mean anything here in terms of ownership / containment?
5) I see there is Element with subclasses of AssetElement (which has context and connections) and AssetDescription (which has classifications and relationships). I assume that we do not need to have Asset connections ,context , relationships and classifications all together. I assume that AssetElement is the searchresult (rename to AssetSearchResult?) and AssetDescription is the details of the Asset (maybe rename to AssetDetails so as not to be confused with the text description associated with the asset).
@bogdan-sava

**Comment by bogdan-sava** [comment]
I Agree

**Comment by danielaotelea** [comment]
Hello, David! Thank you for your review!

1. I will update the JavaDoc 
2. In the last PR for the Asset Catalog OMAS I removed the typeDefGUID. 
3. Maybe the name of this POJO is not correct. The initial design of the Asset Catalog was to search for assets, since then we have added some other types for search as: Glossary Terms and Schema Elements. I will try to rename the class with something meaningful. The response of the asset catalog OMAS includes the Glossary terms currently.
4. The parentElement is used to build the context of the given element. The list can be removed, I will investigate.
5. The connection contains the connection identifier and qualified name. Those will be used by UI to get the connection (using Asset Consumer) in order to connect to the asset. This connection is empty for the Glossary Terms or other types returned by the Asset Catalog OMAS.
The context of the element is build based on the type in order to retrieve relevant output to the enduser.

**Comment by davidradl** [comment]
Thanks for your quick response @danielaotelea @bogdan-sava . 
Apologies for 2 - I did not spot that PR.

A couple more thoughts on 5:
- if the connection is empty for Glossary term why not have a glossary term class that does not include this field. 
- I am not sure what the context is. It is currently a list of Elements, I am not sure how this list is used compared to the parent list. I suspect we may only need one list and that it relates to what we are showing as columns in the search results table result; I assume this is where the drill down information from schema element to asset or glossary term is. Or am I misunderstanding?

**Comment by danielaotelea** [comment]
1. "connections" is not present in the response this is not available. For example, the first call of the search contains a glossary term in the response. The second call is building the context for the entities that have a "Semantic Assignment" relationship with the glossary term (from the 1st call). Let's assume that we have 2 Relationships Columns that have a "Semantic Assignment" Relationship with the given GT. In this case, the asset catalog OMAS builds the context for these columns (retrieving the table, schema, database where these columns can be found), also the connection to the asset that contains the column.

**Comment by danielaotelea** [comment]
If there is no connection present (for example, there is no connection to the GT), the response does not include the connection list.

**Comment by davidradl** [comment]
"If there is no connection present (for example, there is no connection to the GT), the response does not include the connection list." It is a matter of style, in this case the omas client will inflate the response to contain that field with null. I would have an enum for the type of response  and then inflate to an object without that field, so it is very clear. It is fine to leave it the way it is - just a suggestion :-)

**Comment by danielaotelea** [comment]
Hi, can we close this issue?
