### ISSUE TITLE
OpenLineageService exception processing required

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#2181]
I notice in OpenLineageService there are catch blocks like this:
 "
  } catch (InvalidParameterException e) {
            e.printStackTrace();
        } catch (PropertyServerException e) {
            e.printStackTrace();
        } catch (OpenLineageException e) {
            e.printStackTrace();
        }
" 
I think the UI needs to be made aware of these sorts of errors.

**Comment by GuyAckermans** [comment]
Hi David,
This is a WIP interrupted because of Ruxandra's departure from the team. Error handling in the lineage UI will most likely be taken over by Bogdan.

**Comment by davidradl** [comment]
@GuyAckermans ok thanks for letting me know
