### ISSUE TITLE
Have a "Run Egeria" option on the Egeria documentation page

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#2190]
Have a "Run Egeria (Jupyter notebooks)" option on the Egeria documentation page. It is currently under the "Digging Deeper" section- if we have a "Run Egeria (Jupyter notebooks)" link here the notebooks would be be easier to find and use.

**Comment by planetf1** [comment]
The page http://egeria.odpi.org has an entry
'If you are interested in getting started with ODPi Egeria, try our tutorials. Alternatively read on for more information.'

This could be more highlighted, but having looked I'm not sure it needs changing?

Was there another link you were thinking of:?
