### ISSUE TITLE
broken link on egeria.odpi.org

### ISSUE THREAD

**Issue by bogdan-sava** [odpi/egeria#2192]
to reproduce go to 
https://egeria.odpi.org/open-metadata-resources/open-metadata-tutorials/beginners-guide/running-natively.html

click on 
Follow the OMAG Server Platform tutorial for instructions on how to set up and run a platform yourself. 

result:
404 page not found

**Comment by planetf1** [comment]
Good spot -- it's also worth noting that whilst those commands will get /a/ platform running, to run the tutorials you actually need 3 platforms, so we also need to explain that
