### ISSUE TITLE
dependencyManagement vs version properties

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#22]
In the top level POM we have a set of properties such as
        <log4j.version>2.4.6</log4j.version>

Then when we have a <dependency> flag in either this pom, or any child we can use:
            <version>${log4j.version}</version>

This would seem to work, but I wondered whether it was simpler to use the standard maven mechanism for expressing the use of consistent versions, where we would use
<dependencyManagement> flags in the top level pom to declare our default versions, and then use <dependency> as today where each plugin needs to be used

We would do the same for <pluginManagement> to ensure consistent use of plugin versions across the project (in exceptional cases overriding can be done at any level). 

Atlas did use the explicit property mechanism, but I would think going with standard maven is simpler, 

Happy to do a patch if the community feels this is a better approach

**Comment by mandy-chessell** [comment]
What would the flags look like ?

**Comment by planetf1** [comment]
See example in https://github.com/GaianRangerPlugin/ranger-gaian-plugin/blob/master/pom.xml

Basically this uses the 'DependencyManagement' to express the version that should be used in all modules, without actually pulling in as a dependency. In the 'Dependency' section the version is then omitted. A similar pattern applies to the plugins with 'PluginManagement'. This is the 'standard' maven mechanism

One main difference is the effective on transitive dependencies - the maven scheme arguably provides a little more assurance as to what is used.

There's some further docs at https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html

**Comment by mandy-chessell** [comment]
I think we should do this - as the code gets bigger, dependency management is going to become more important.  I would like to take you up on your offer to code the patch (when you are back from vacation :)

**Comment by planetf1** [comment]
Updating top level pom.
Removing any DependencyManagement elsewhere
Added validation - as an example if an inconsistent version is used we now fail the build with
```
[INFO] --- maven-dependency-plugin:3.1.1:analyze-dep-mgt (depmgmt) @ access-services-user-interface ---
[INFO] Found Resolved Dependency/DependencyManagement mismatches:
[INFO] 	Dependency: org.springframework.security:spring-security-web:jar
[INFO] 		DepMgt  : 5.1.4.RELEASE
[INFO] 		Resolved: 5.1.5.RELEASE
```

There's no exception handling yet - will need to add on a case by case basis (overriding <plugin> configuration in local pom.

Discrepancies so far
* Janusgraph - 0.3.1 used by graph repo, 0.3.0 by lineage -> updated to 0.3.1
* spring-security-web - 5.1.4 used most places, 5.1.5 in user interface (incorrect version compatibility with spring-web) -> corrected to 5.1.4 (this was caused by using the wrong property)

Local version properties and numbers have NOT been removed in this PR -- though any update that makes them inconsistent will fail the build. These will be cleaned in a subsequent update

**Comment by planetf1** [comment]
Also not added -- any refactoring of UI build and expression of non-maven dependency versions (npm and polymer components)

**Comment by planetf1** [comment]
this has been implemented
