### ISSUE TITLE
CTS NPEs on relationship endpoint EntityDef lookups

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#2213]
Came across a number of NullPointerExceptions in the (master) CTS as follows: under the `run()` method of the test classes below, the endpoint definitions of a relationship are retrieved but `repositoryHelper.getTypeDefByName(...)` fails with an NPE when the type definition is a supertype that is not implemented by the repository being tested. (For example, `ActorProfile` when the repository only implements `Person`; `Asset` when the repository only implements `Database`; `ComplexSchemaType` when the repository only implements `TabularSchemaType`, etc.)

Seems like another case where we should be retrieving the endpoint definitions of the relationship from the open type definitions themselves -- not from the repository under test?

Seen in all of the following:

- [ ] `TestSupportedRelationshipLifecycle`
- [ ] `TestSupportedRelationshipReidentify`
- [ ] `TestSupportedRelationshipPropertySearch`
- [ ] `TestSupportedRelationshipPropertyAdvancedSearch`

**Comment by planetf1** [comment]
There's a fair number of potential NPEs reported in the sonar scan on the CTS code also, so suggest checking those out too

**Comment by grahamwallis** [comment]
Hmmm.. that's confusing. Those type checks were introduced specifically to check that the repository's reported type matches the 'known' type. It uses the same repo helper method that is used to get the properties (which also needed to come from the known type, not the repository's returned type). I was under the impression that the getTypeDefByName would return the known type, as opposed to the active type. I will take a deeper look.

**Comment by grahamwallis** [comment]
I think the ones from the sonar scans *might* be bogus - there are lots of places in the CTS where we perform a test, then call an assertCondition method which will throw an exception if the assertion is not satisfied. The tests can continue safely after the assertion has been tested. I have discussed with Mandy adding explicit belt and braces protection to avoid the sonar scan warnings but we decided not to at the time - I will take another look when I get a moment

**Comment by grahamwallis** [comment]
@cmgrote - Hi Chris - when the connector is called on verifyTypeDef does it throw TypeDefNotSupportedException? (I'm just eye-balling repo content manager code and trying to work out why the unimplemented super-types would not be in knownTypes).

**Comment by cmgrote** [comment]
On my repository, yes, it will throw `TypeDefNotSupportedException` for the supertypes that I have not implemented.  So, for example, if you called `verifyTypeDef` on my connector with the GUID of the `Asset` type def, you would get a `TypeDefNotSupportedException`.  However, if you called the same with the GUID of `Database` (which is a subtype of `Asset`) then you should get `true`.

**Comment by grahamwallis** [comment]
I think that you are doing the right thing. 

What's puzzling is that if a connector response to verifyTypeDef with a TypeDefNotSupportedException then the RCM should (from looking at the code) be caching the typedef into knownTypes (and not into activeTypes). But if that were the case then I would expect my type-checking assertion to get the type back from the repo helper when it calls getTypeDefByName (which looks in the knownTypes).
