### ISSUE TITLE
Remove warning from Sonar Scans caused by Spring Annotations

### ISSUE THREAD

**Issue by wbittles** [odpi/egeria#2214]
The are currently 671 occurrences of @RequestMapping usage throughout the Egeria code base (regex @RequestMapping\(method\s=\sRequestMethod) that are generating warning from the Sonar Scans. This is issue is intended to replace @RequestMapping calls with the more up to date @GetMapping , @PostMapping , @DeleteMapping ,@PutMapping

**Comment by planetf1** [comment]
It's an interesting example of some of the more minor issues we have. It's tagged as a code smell/minor. I agree it's clearer to use the new forms, but @requestmapping itself isn't deprecated.

We may have two other options to consider for all such issues
 a) We can triage and close the issues as 'wont fix' or 'false positive' - this is fine for the odd warning, but painful for many
 b) We may be able to change the profile used to not detect the error

That all being said, if it's simple to fix then the easiest course I agree is to fix (though there are more serious issues we also need to get sorted - bugs & security).

**Comment by wbittles** [comment]
It looks like a pretty straight forward change, I've opened a PR with the changes for the @GetMapping case (220 instances) , please feel free to reject it if there there is a preference for another approach. Point taken on the more severe issues.

**Comment by planetf1** [comment]
The main merges have gone in ... are you planning more changes  - if so we can keep open?

**Comment by wbittles** [comment]
Hi Nigel I'm not planning on putting any more in until after the code freeze. Should I close the PR's ?

**Comment by planetf1** [comment]
The PRs are closed.
If this issue is incomplete I suggest keeping it open (and summarising what area needs looking at)
Otherwise let's close it

**Comment by mandy-chessell** [comment]
I think it is ok to close - I have updated the new REST APIs I added since @wbittles did the change.  I like it - the new annotations are easier to read.
