### ISSUE TITLE
suggested change to the OpenLineageClient rest calls

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#2219]
I notice that the OpenLineageClient rest calls take the form  

callGetRESTCall(methodName, LineageResponse.class,
                serverPlatformURLRoot +
                        BASE_PATH +
                        LINEAGE +
                        LINEAGE_SOURCES +
                        LINEAGE_SCOPES +
                        LINEAGE_VIEWS +
                        LINEAGE_ENTITIES +
                        "?" +
                        DISPLAYNAME_CONTAINS +
                        "&" +
                        INCLUDE_PROCESSES,
                serverName, userId, graphName.getValue(), scope.getValue(), view.getValue(), guid, displayNameMustContain, includeProcesses);
        detectExceptions(methodName, lineageResponse);

This means that there is a very long rest url including the scope, view , sources, entities.

I think it would be much more preferable to specify most/all of the parameters in a request body, because:
1) The URL segments has an inherent order which is not important
2) In theory you should be able to get each rest segment as a separate resource using get calls. I think because the order is not important this is not very intuitive.
3) url segment have escaping issues for weird characters
4) If we need to every specify lists or sets - then the rest segments are not very intuitive in url segments.

**Comment by GuyAckermans** [comment]
Done
