### ISSUE TITLE
Common module for building JanusGraph Configuration 

### ISSUE THREAD

**Issue by DimitriosMaimaris** [odpi/egeria#2221]
Both egeria repository and open-lineage janus connector need to receive a configuration object for instantiating the graph based on the preferable backend and index engine. It will be nice to discuss a way to have a common way of reusing the way we build the configuration to be used by any graph that has JanusGraph as an implementation. As well to have a dynamic dependency loading based on that configuration.

**Comment by grahamwallis** [comment]
@DimitriosMaimaris - thanks for raising this.

The minimum we would need is some way of choosing the persistence backend - could be free format or could an enum of tested backends (to which we could add in future):
e.g. "backend" : { "berkeley" | "cassandra" }

Specifically for Berkeley we need to know the storage path:
e.g. "storage.directory" : { <sub-folder name> }

Similarly for search backends we need some way of choosing between tested indexers:
e.g. "search" : { "lucene" | "elastic" }

Specifically for Lucene we need to know the index path:
e.g. "index.search.directory" : {  <sub-folder name>  } 

Can you please add the similar configuration options for Cassandra and Elastic?

Given the conversation about performance, we may also want to add tuning parameters for Janusgraph (generally) or the configured backend. There may need to be tuning of things like the transaction cache and/or db cache, or there may need to be tuning for the backend. I'm sure we will discover these in due course, so keeping an open format with property names similar to Janusgraph would seem sensible. This would also be useful for things other than performance tuning.

**Comment by DimitriosMaimaris** [comment]
Indeed we also need to cater for tuning different options each backend allows, good point.

**Comment by planetf1** [comment]
I'm not familar enough with the configurations required, but I think the connectors should focus on flexible configuration for the //client//. Where we also offer a backend/server, then we may wish to include some configuration for this, but I wonder if this should be provided in a seperate module - ie a janus connector & a janus implementation.

This is even more relevant with cassandra where again I'd expect to see client related related configuration, but configuration of the backend would be the responsibility of the backend providers.

I think we need a clearer seperation between the 'connector' and the implementation. For example in kafka we do support many config parms, but they are basically client parms, not server which we don't touch.
