### ISSUE TITLE
link broken in running egeria natively 

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#2222]
https://github.com/odpi/egeria/blob/master/open-metadata-resources/open-metadata-tutorials/beginners-guide/running-natively.md, the OMAG Server Platform link gets a 404.
@planetf1 . The incorrect link is https://github.com/odpi/egeria/blob/master/open-metadata-resources/open-metadata-tutorials/open-metadata-tutorials/omag-server-tutorial/task-starting-the-omag-server-platform.md

**Comment by bogdan-sava** [comment]
duplicate of https://github.com/odpi/egeria/issues/2192
