### ISSUE TITLE
CTS TestSupportedEntitySharingPropertySearch assertion seems incomplete

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#2223]
Assertion 4 of this CTS test case looks for whether the results are null or not (and if they are null fails the assertion).  However, above this there is a calculation of the results that are _expected_ (and are used as part of assertion 5); if the number of expected results is 0 then I believe it is perfectly valid for the results in assertion 4 to be null (?)

I'd suggest that the assertion for 4 is revised to something more like:

```java
( (expectedEntityCount > 0 && result != null) || (expectedEntityCount == 0 && (result == null || result.isEmpty()) )
```

**Comment by grahamwallis** [comment]
Yep - good spot - and I'm already on the case - been working on a refactored unified test case and that is one of the changes I've made.

**Comment by grahamwallis** [comment]
The PR mentioned above is a fix to just the entity and relationship sharing testcases. 

I aim to switch over to the refactored search tests soon but the PR should help until then.
