### ISSUE TITLE
Asset catalog omas error user response

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#2227]
Sorry I missed the slot to review #2179. I notice inAssetCatalogErrorCode.java 

1) I think that Constants.UNIQUE_IDENTIFIER_FOR_THE_ASSET_IS_CORRECT is not usually the appropriate user action when it is used. For example below there is no assets found with a particular classification. This is a valid 'not found' case not an error case requiring a different asset unique identifier to be specified.
    CLASSIFICATION_NOT_FOUND(404, "OMAS-ASSET-CATALOG-404-008 ",
            "The requested asset {0} has not classification in OMAS Server {1}",
            "The system is unable to retrieve the classifications for the given asset.",
            "Check that the unique identifier for the asset is correct."),
            Constants.UNIQUE_IDENTIFIER_FOR_THE_ASSET_IS_CORRECT),

2) Also in the case where the unique identifier is that of an asset, it would be good to specify which unique identifier and its value, e.g. qualified name or unique attribute or guid. 
3) I assume that in the example OMAS-ASSET-CATALOG-404-008 that asset insert should be its display name which is readable/meaningful to the user  but may not be unique. I wonder if the messages need to be explicitly include the display name and qualified name.

**Comment by danielaotelea** [comment]
Hi, David! Thank for for feedback!
Please, take a look on the PR: https://github.com/odpi/egeria/pull/2228
I removed the error codes that are not used anymore in the Asset Catalog OMAS.
Also, the new error message contains the asset identifier.
