### ISSUE TITLE
tagsync for Egeria

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#226]
Apache Ranger needs to be populated with asset-tag mappings so that it can apply tag based policies - ie policies based on classification metadata as stored in egeria. 

Here we will implement an initial version of this tagsync using REST api sufficient to support our initial 'mvp' capabilities. Enhancements will follow later and additional issues will be raised to track

This tagsync will effectively
 - be launched via a standalone java application
 - read a list of (classified) assets & classifications via an Egeria GE omas REST call
 - push them to Ranger via a Ranger REST api call
 - pause for a configurable period, and repeat

**Comment by mandy-chessell** [comment]
Firstly I really like the way you lay our what you are doing in the issues like this.  The downside is that you get feedback :)  

Could this standalone Java application run in the server chassis?  We talked about having governance daemons each being a configured capability that effectively runs in the OMAG Server and can be turned on and off through the config.

OK to defer if this is too much for the first step - but it would be good if this "tag sync" code was structured to make it easy to move to the server chassis at a later date - and also located in a module under governace-servers.

Also I thought we cam up with a new name for tag sync - but I can not remember what it was.

**Comment by planetf1** [comment]
Co-incidentally I just opened up this issue as I'm about to start working on tagsync, and I was already looking in the directory structure for the server chassis, so that was already my intent (depending on how much effort it is).

There are still limitations, omissions with the GE omas api , but it is now returning some assets and classifications, so it's prudent to at least get the other side connected up so that we can see a egeria-ranger flow

My planned name is openmetata-sync

**Comment by planetf1** [comment]
Postman collections for work so far:
 Ge-OMAS : https://www.getpostman.com/collections/c964552c54fa77b0eb64
 Ranger: https://www.getpostman.com/collections/f70bf02e9baa6ccbf8cf

**Comment by danielaotelea** [comment]
The initial exchange between Egeria and external enforcement policies tools is done.
Also, the syncing is done based on the events. 
There is something else that is missing? Are some parts of the issue not covered in the current implementation?

**Comment by planetf1** [comment]
No, I think what we have covers the intent of this issue. Closing
