### ISSUE TITLE
remove tomcat dependency from view services if possible

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#2267]
See initial review comment below - let's track in a new Issue.

shouldn't depend on tomcat, as suppose to run in different servlet container also

_Originally posted by @bogdan-sava in https://github.com/odpi/egeria/pull/2220/threads/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjIwNjU5NjM1OnYy/unresolve_

**Comment by davidradl** [comment]
Not possible at this time because the HttptServletRequest is required to get the user from the request, and that class is supplied by Tomcat.

**Comment by planetf1** [comment]
I'd like to keep open to investigate further.. Fit example to see if a more minimal dependency from https://mvnrepository.com/artifact/org.apache.tomcat is possible rather than the embed package. 

Not had time yet so deferred to new issue

**Comment by planetf1** [comment]
I'll take a look. Reassigning

**Comment by bogdan-sava** [comment]
It is possible and it's needed.
HttpServletRequest is from javax.servlet.http package

https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html

**Comment by bogdan-sava** [comment]
It is in the servlet-api, present in all servlet containers. Of course.

**Comment by planetf1** [comment]
https://mvnrepository.com/artifact/javax.servlet/javax.servlet-api

ie
javax.servlet:javax.servlet-api

may be appropriate

And for confirmation, the openliberty documentation (one might use openliberty for eclipse microprofile) also uses this maven artifact it's in example pom at https://openliberty.io/guides/maven-intro.html#running-the-tests

**Comment by planetf1** [comment]
Hi David - assigned as it probably makes sense to factor in as part of your UI work

**Comment by planetf1** [comment]
Note the example on maven dependencies at https://howtodoinjava.com/maven/maven-dependency-scopes/ . Search for 'servlet'. It suggests using 'provided' scope for this dependency as it's provided by the container

**Comment by davidradl** [comment]
As we agree this - we should update the view serviced in line, as per the review comment for #2577

**Comment by planetf1** [comment]
We should still try and do this

**Comment by planetf1** [comment]
I think the UI work has moved on to the point where there's little point in leaving this open right now - both UIs are being driven by requirements
