### ISSUE TITLE
Admin services dependent on user interface 

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#2268]
Core admin services appear to be dependent on user interface admin services

See ./open-metadata-implementation/admin-services/admin-services-client/src/main/java/org/odpi/openmetadata/adminservices/ConfigurationManagementClient.java which has
`import org.odpi.openmetadata.userinterface.adminservices.configuration.properties.UIServerConfig;`

_Originally posted by @planetf1 in https://github.com/odpi/egeria/pull/2220_

**Comment by planetf1** [comment]
Additional note
admin-services client is depending on ui-admin-services-api

**Comment by davidradl** [comment]
fixed in #2220

**Comment by planetf1** [comment]
Checking the pr review the dependency is still there.

Reopening and will elaborate example and double check. I'll investigate

**Comment by planetf1** [comment]
closing due to reversion. will reopen after any new refactoring complete as part of review
