### ISSUE TITLE
OMRSMetadataCollectionBase change to make findRelationships optional?

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#2275]
We updated the CTS to make the findRelationships methods part of an optional profile (no longer part of the mandatory metadata sharing profile).  Should we also update the OMRSMetadataCollectionBase class to throw a FunctionNotSupportedException by default in all cases (for these methods) to reflect this optionality?

Currently the methods only throw this exception if there is an asOfTime parameter provided, and otherwise default to throwing a RepositoryErrorException.

**Comment by mandy-chessell** [comment]
Agreed - makes sense

**Comment by cmgrote** [comment]
Wary that you may be updating other parts of the class, but if not and you want me to make this change just let me know 😁

**Comment by grahamwallis** [comment]
I have no other changes lined up for the base class. Got for it if you like.

**Comment by cmgrote** [comment]
Moving back to 1.3 release as it will be a necessary change for Atlas connector to pass the CTS (since it doesn't implement these methods) + it is a very simple change -- PR imminent...

**Comment by cmgrote** [comment]
@grahamwallis change seems to be fine in the base class now (via PR #2281), but the CTS itself of course doesn't (yet) recognise an FNS from these methods as an acceptable outcome:

```json
"conformanceStatus": "NOT_CONFORMANT",
"negativeTestEvidence": [
  {
    "profileId": 12,
    "requirementId": 47,
    "testCaseId": "repository-relationship-sharing-property-search-AttributeForSchema",
    "testCaseName": "Repository relationship sharing property search test case",
    "testCaseDescriptionURL": "https://egeria.odpi.org/open-metadata-conformance-suite/docs/repository-workbench/test-cases/repository-relationship-sharing-property-search-test-case.md",
    "testEvidenceType": "UNEXPECTED_EXCEPTION",
    "assertionMessage": "test-case-base-01: Unexpected Exception FunctionNotSupportedException",
    "conformanceException": {
      "exceptionClassName": "org.odpi.openmetadata.repositoryservices.ffdc.exception.FunctionNotSupportedException",
      "errorMessage": "OMRS-METADATA-COLLECTION-501-001 OMRSMetadataInstanceStore method findRelationshipsByProperty for OMRS Connector org.odpi.egeria.connectors.apache.atlas.repositoryconnector.ApacheAtlasOMRSMetadataCollection to repository type myserver is not implemented"
    }
  }
```

Is that a simple change to make on the CTS side?

**Comment by grahamwallis** [comment]
@cmgrote - I can change that - will do so straight away.
One comment on the PR though - looking at it in more detail did you really mean to change getEntityNeighborhoodParameterValidation? I don't think that ever throws an FNSException.

**Comment by cmgrote** [comment]
I haven’t changed that method, and indeed it does not throw FNS — just a quirk of the diff display on GitHub I suspect...

**Comment by planetf1** [comment]
Interesting comment -- but I see why. It's just because the diff is just showing a few lines earlier/later  - and happens to show a line from the next method. Maybe some day we'll have a code aware diff which points out the enclosing method!

**Comment by grahamwallis** [comment]
Actually I think it was quite explicit - it claimed line number 2305 had changed.
It doesn't matter - it's an OK change anyway; but intriguing nonetheless.

**Comment by planetf1** [comment]
It did change ... (and yes I was referring to the wrong method and hence wrong explanation!)

<img width="1224" alt="Screenshot 2019-12-20 at 14 34 38" src="https://user-images.githubusercontent.com/7292002/71261692-f04c6a00-2335-11ea-83f9-d164092ba38a.png">

<img width="1079" alt="Screenshot 2019-12-20 at 14 36 16" src="https://user-images.githubusercontent.com/7292002/71261766-1bcf5480-2336-11ea-9e2a-5eb561821e18.png">

**Comment by cmgrote** [comment]
Ah, yes, if we’re talking about the JavaDoc I did change that in many more spots because in many places it still explicitly mentioned the asOfTime parameter as the reason for FNS when in reality the method is optional in general — hence I updated the JavaDocs to make this clear (so no confusion over it being limited to asOfTime alone).

But I didn’t change any of the functionality of any of the other methods.
