### ISSUE TITLE
Add simple notebook to demonstrate configuration of User Interface

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#2286]
Previously the UI has been usable with minimal configuration by developers, and in the container environment has been automatically configured.

#2266 will handle the container environment, but first I will create a simple, somewhat hardcoded, notebook to ensure developers can understand how to get the UI working. Indeed if using the coco pharma environment locally (3 platforms - 8080, 8081, 8082 - and using the documented server names) it will work with no change.

**Comment by planetf1** [comment]
Moving to 1.4 due to #2285

**Comment by mandy-chessell** [comment]
The configuration of the UI platform should eventually be folded into the main server config notebook - so it is possible to configure the coco environment (metadata servers, governance servers and ui servers) all in one place.

**Comment by planetf1** [comment]
Closing for now until we have a UI that needs this
