### ISSUE TITLE
UI - configuration admin wrong behavior

### ISSUE THREAD

**Issue by bogdan-sava** [odpi/egeria#2290]
The configuration has a path parameter serverName, but also a field into the body of the request
called "localServerName".

If those two have different value a validation error is returned.

Doesn't make sense. If the 2 values should be always the same, just remove one.

**Comment by davidradl** [comment]
Hi Bogdan, this is the same as the OMAGServerConfig admin behaviour. I think this is working as designed. When we move one platform server config to another server then the localServerName and its URL are needed and are obtained from the config file. What do you think @mandy-chessell ?

**Comment by mandy-chessell** [comment]
You are right @davidradl - it is to support our deployment - and also to help the implementation of the config store.

**Comment by bogdan-sava** [comment]
@davidradl It does not make any sense for designing a rest endpoint in general, not only for this project.
Why to design an endpoint that validates a path param has always the same value as an attribute in the body?
Deploy is a different call.
