### ISSUE TITLE
UI - login wrong behavior

### ISSUE THREAD

**Issue by bogdan-sava** [odpi/egeria#2291]
Start the UI.
Type the server name into the field
Press enter key makes server name to disappear, url change with a query parameter and no feedback whatsoever to know what happened.

Type a diffrent server name and click the '+' button ( why '+' ??? ). The result is a credentials are asked but the url query parameter is the previous one.

After credentials check, if successful, have no clue in what tenant I am logged in.

**Comment by davidradl** [comment]
Thanks for the feedback. This was as discussed in the calls. I was going to get rid of the first page. We are reverting the big ui change, so this is not an issue.
