### ISSUE TITLE
Minor typo in building-an-asset-catalog notebook may be confusing

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#2297]
Cell 13 begins
```
print (" ")
print ("GET " + server1GetAssetsURL)
print ("{ " + searchString + " }")
print (" ")

response=requests.post(server1GetAssetsURL, data=searchString)

```

Note the text output to the screen says 'GET' but the actual request sent is a POST

Should check other notebooks for the same pattern

**Comment by mandy-chessell** [comment]
Good spot - I am changing this notebook at the moment - so eaiser if I fix it

**Comment by mandy-chessell** [comment]
Should be ok now

**Comment by planetf1** [comment]
Looks good now thanks
