### ISSUE TITLE
Problem with sending booleans over REST

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#2312]
I am seeing a curious problem in the marchalling or unmarshalling of booleans over a REST API.  This is something that has recently stopped working since it is visible in the lab notebooks.

Here is the example I see ...
When we create a comment - either attached directly to something like an asset or a reply to another comment, there is a boolean to determine if the comment is public or private.

The REST APIs were passing this boolean successfully a little while ago but now the value is always set to whatever default is defined in the java bean that receives the value.  I have set this to true (public) as a temporary fix to allow the lab notebooks to work but it needs investigating to discover if it is a problem in my local environment or due to a change in Jackson level.

**Comment by planetf1** [comment]
The jackson version was last updated (to 2.10.1) on 12 Nov by dependabot. Could we have missed seeing the issue for that long? 

I've not seen anything obvious myself but may be worth some other eyes over issues reported at https://github.com/FasterXML/jackson-core/issues & https://github.com/FasterXML/jackson-databind/issues

More recently in Dec (12th) spring was upgraded to 5.2.2 (and friends)

Do you have a specific code example?

**Comment by grahamwallis** [comment]
Is the problem that the comment is actually an  instance of a Comment entity, which does not appear to have an isPublic field? The Comment bean does have such a field but are we missing it from the (entity) definition for Comment?

**Comment by mandy-chessell** [comment]
This is a regression - the boolean is not being deserialized on the REST API call. 

The boolean is in the Comment bean and stored in the relationship between the Referenceable and the Comment.  This function has been working ok and just began to fail recently.

**Comment by planetf1** [comment]
There have been many jackson and spring updates. We need to consider how we protect against this -- can we add a test case? And do you have an example of a specific rest call that would fail?

Presumably you are referring to the 'building a data catalog' notebook - for example Erin adds a comment?

I notice we set the value to the Python value True - which is treated more like 1 - so when it gets passed through the requests module, I wonder if it's actually 1, not True... sorry this is an area I'm unfamilar with, but wonder if this could more be type conversion issues in the notebook?

How does it behave with curl or httpie - may eliminate python specifics from the discussion?

**Comment by grahamwallis** [comment]
I suspect that we want to keep this open. I think the problem may be that the Comment bean has an isPublic property, and has methods isPublic() and setPublic(). Without either annotation tr methods for getisPublic(), setIsPublic() Jackson will not know how to serialize/deserialize it. I think we should try adding these methods alongside the existing isPublic() and setPublic() methods, to retain compatibility with the current uses of those latter methods.
