### ISSUE TITLE
Audit log connector comments PR #2319

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#2322]
1. The README.md in audit-log-log4j-connector has been copied from the console connector - the title needs correcting, and description of function - since it does not log to stdout.

2. The connector needs renaming. It is not a log4J connector, but rather an slf4j connector (which itself can be configured to use log4J). ie it is not using log4j APIs. Itself it is dependent on slf4j-api only (quite correctly) and needs to be bound to an implementation at runtime, which could be via logback, slf4j-simple, or a variety of other options.

initially observed in #2319

**Comment by mandy-chessell** [comment]
Hopefully fixed - thanks for point this out ...
