### ISSUE TITLE
CTS checking types against a hard-coded version number?

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#2326]
Currently the CTS type-checking tests are looking at a hard-coded type version number of `1`.  As best I can tell one of the recent merges updated the types to version `2`, which is resulting in pretty much every type now failing validation through the CTS.

(See assertion 7 and 8 in `TestSupportedTypeDef`.)

I'm not sure which one needs the corrective action:

- should the CTS skip checking a version number at all?
- should the CTS type checking test cases be updated to match the version number of the open types for the release?
- should the open metadata types not have their version increased unless they have actually been patched / created / somehow modified in the new release (ie. should unmodified types retain their original version number)?
- some other change / fix?

**Comment by planetf1** [comment]
This looks like essential to fix for 1.3

**Comment by grahamwallis** [comment]
From discussion on community call 2nd Jan it was decided that for 1.3 release we should relax the version check. We will discuss how to improve type version checking and may introduce for 1.4.

**Comment by cmgrote** [comment]
Agreed on the call for 1.3 to simply relax / remove the version-specific check while we work out exactly what scenarios we want the CTS to test and allow.

I think this means we just remove this code-phrase from assertion 7 and 8:
` && ((typeDef.getVersion() == 2) || (typeDef.getUpdateTime() != null))`

**Comment by cmgrote** [comment]
Resolved by another change related to the versioning of typedefs -- so no patch / fix needed to the CTS.
