### ISSUE TITLE
How should deprecated properties in the open metadata types be handled?

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#2333]
When we deprecate a property in an open metadata type, what should happen when:
* A repository discovers an instance with deprecated properties
* A remote cohort member sends an instance with a deprecated property
* An OMAS retreives instances using a deprecated property
* An OMAS creates an instance using deprecated properties
* An OMAS updates an instance containing deprecated properties (including changing the deprecated property itself)

Deprecation is defined in the property's TypeDefAttribute.
When a property is marked as deprecated, it is possible to provide a `replacedBy` property name if the property has effectively been renamed.  However, if it is going away then the `replacedBy` property is null in the `TypeDefAttribute`.

**Comment by grahamwallis** [comment]
Is it a reasonable answer to suggest that repositories and OMASs should continue to support a deprecated property for a limited amount of time (actually measured in number of releases, e.g. "up to and including 1.6")  after which it should report an error or refuse to handle/accept/store an instance with a discontinued property?

**Comment by cong78** [comment]
> * An OMAS creates an instance using deprecated properties

Maybe a question/idea from this topic, does any consumer of OMASes need to aware of version of OM types beforehand? Such as for a data engine tries to plug in Data Engine OMAS, it needs to verify the version of the DE OMAS supports. Probably even send a standard OM Type payload to verify the consistency of the types that it is going to interact with the OMAS.

**Comment by mandy-chessell** [comment]
The OMASs should completely hide the version of the types that they are using.  They are responsible for providing a backward compatible interface to their consumers so the clients of the OMASs should not care.

However, it is reasonable that an OMAS does some checking of the types they are using at server start up since the types it uses may not be supported in the cohort - or types may have been deprecated or extended.

I agree that the deprecated types need to be supported - probably "forever".

I was thinking that we could have a discovery service that is looking for instances that are using either deprecated types and/or attributes.  It could file a report - just as we do for duplicate suspects and divergent duplicates - that the stewardship server would handle.

The value I see in this is that the OMASs are relatively easy to keep up-to-date.  However, there may be third party integrations that are using the deprecated types and are pumping that use them instances into the cohort.  The stewardship report would be to highlight that a thrid party integration needs updating.

**Comment by mandy-chessell** [comment]
Are we ready to add the rules/requirements to the developer documentation and close this issue?
