### ISSUE TITLE
This condition appears incorrect?

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#2343]
https://github.com/odpi/egeria/blob/07d459aee471d50b43b0b40dd6f76f8668e41319/open-metadata-implementation/repository-services/repository-services-implementation/src/main/java/org/odpi/openmetadata/repositoryservices/localrepository/repositorycontentmanager/OMRSRepositoryContentManager.java#L1868

This condition appears to check that two versions are equal, but if they are it logs an error that they are not the same version and fails the verification...  Seems like it is missing a `!` at the start of the condition?

Result is that all kinds of errors are suddenly appearing from trying to do operations via the repository helpers...  But this also looks like it was changed in relation to the infinite loop that was discussed -- and I'm not up-to-speed on all the nuances there, so not eager to change anything myself for fear of inadvertent side-effects 😬

**Comment by grahamwallis** [comment]
Agreed - it looks like the change to comparing the (string) versionName is only half complete - it would have been necessary to move to .equals() but the negation has been lost.

**Comment by grahamwallis** [comment]
There are two occurrences of this on lines 1868 and 1911

**Comment by grahamwallis** [comment]
I was about to pop in a PR for this but it appears that validAttributeTypeDefId has another error - it should be looking in the knownAttributeTypeDefs (and expecting to get an AttributeTypeDef) rather than a TypeDef from knownTypeDefs

**Comment by mandy-chessell** [comment]
@cmgrote @grahamwallis @planetf1 sorry about that - was clearly too tired when I did that - I can fix it up when I look at #2344

**Comment by grahamwallis** [comment]
No problem - there's a PR #2345

**Comment by planetf1** [comment]
This appears to have been fixed now ...
