### ISSUE TITLE
suggested changes to AssetLineageEventType

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#2362]
AssetLineageEventType has 

    PROCESS_CONTEXT_EVENT                   (0, "ProcessContextEvent", "Has the full context for a Process"),
    TECHNICAL_ELEMENT_CONTEXT_EVENT         (1, "ProcessContextEvent", "Has the full context for a technical element"),
    CLASSIFICATION_CONTEXT_EVENT            (2, "ProcessContextEvent", "Has the full context for a classified element"),
    UPDATE_ENTITY_EVENT                     (3, "UpdateEvent", "Has the entity that is being updated"),
    DELETE_ENTITY_EVENT                     (3, "DeleteEvent", "Has the entity to be deleted"),

1) I notice DELETE_ENTITY_EVENT has the same number (3) as update.
2) ProcessContextEvent is in 3 of the events.
3) I suggest removing the "Has the " from the start of each description.
4) Is the description of CLASSIFICATION_CONTEXT_EVENT  correct? I assume that this event would occur when an element is declassified as well - in this case the event is not for a classified element.
Maybe talk of the asset getting a classification change; or will we get this event for a glossary term classification as well (if so do we need 2 types of events one for assets and one for glossary terms).  
5) I am wondering whether UPDATE_ENTITY_EVENT should be UPDATE_ASSET_EVENT, and  DELETE_ENTITY_EVENT should be DELETE_ASSET_EVENT - so it is very clear what we are dealing with.
6) I am wondering whether we need asset create and asset restore events?

**Comment by DimitriosMaimaris** [comment]
Thanks David for pointing it 1 and 2 will be fixed. Regarding 4 when we deal with classification we will see it is not is the scope for next release so there has not been any investigation for the cases we can have.
For 5 we delete and update entities that are not assets so I don't see a point of changing it and for 5 if we handle events of those in the future then will be added now it is not necessary.
