### ISSUE TITLE
Duplicated line in OCFOMASServiceInstance.java 

### ISSUE THREAD

**Issue by cong78** [odpi/egeria#2363]
I am trying to look at the code changes of asset scanning and found a duplicated line of code. Not sure if it a typo or with a reason. @mandy-chessell Could you please have a look on it? Thanks. 

https://github.com/odpi/egeria/blob/1d17344820b482e8d62138c0a4b807eb2bcfcaaf/open-metadata-implementation/common-services/multi-tenant/src/main/java/org/odpi/openmetadata/commonservices/multitenant/OCFOMASServiceInstance.java#L138

```
 this.externalIdentifierHandler = new ExternalIdentifierHandler(serviceName, serverName, invalidParameterHandler, repositoryHandler, repositoryHelper, lastAttachmentHandler);
 this.externalIdentifierHandler = new ExternalIdentifierHandler(serviceName, serverName, invalidParameterHandler, repositoryHandler, repositoryHelper, lastAttachmentHandler);
```

**Comment by mandy-chessell** [comment]
It looks ok to remove one of the copies
