### ISSUE TITLE
Simple event implementation that does not rely on Kafka?

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#2364]
I'm interested in a simple event publishing implementation that will not rely on Kafka, so that we could easily use it for testing purposes (ie. as part of the build process).

I was thinking about something along the lines of a very basic in-memory list that we simply append to with the string-representation of any events: and it looks like this might be most easily feasible by extending the `OMRSRepositoryEventBuilder` class with a very simple implementation that manages a private `List<String>`, where the `sendTypeDefEvent` and `sendInstanceEvent` methods just append to the `List<String>`.  Basically something like an "In-Memory Cohort" analogous to how we have an "In-Memory Repository" (?)

Would this be logical / useful for others (ie. to include as an implementation in Egeria core)?  Or is it quite an invasive addition that's instead likely to break things?

**Comment by planetf1** [comment]
One big bonus of any alternative event implementation is that of proving our pluggability.Absolutely in no way should it break things, or we've made a big error!

it also may help to isolate any kafka specific issues when testing

Any tests we're likely to automate here though will (should IMO) be beyond unit tests, so whilst they should be easy to run I wouldn't expect them to run in a dev build environment, though absolutely could after say a merge (where our other FVTs and longer tests should run)

So overall? Viable - yes, useful - probably, essential - don't think so ??

**Comment by mandy-chessell** [comment]
We have something similar that we use for the event publishing between the OMRS and OMAS - https://github.com/odpi/egeria/tree/master/open-metadata-implementation/adapters/open-connectors/event-bus-connectors/open-metadata-topic-connectors/inmemory-open-metadata-topic-connector

**Comment by cmgrote** [comment]
I was hoping that might be the case -- thanks, I'll have a look at that!
