### ISSUE TITLE
Support for postgres databases

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#2399]
Support for postgres needs to come in 2 parts

* Implementation of a JDBC style data connector for use by asset consumers.
* Implementation of a polling metadata extractor connector to be hosted in the Data Platform governance server.

There is also some related work to create a generic JDBC connector that the postgres and gaian connector extend (similar pattern to the file-based connectors).

**Comment by planetf1** [comment]
As part of this work we should
 - also incorporate a sample postgres database in the demo environment
 - allow for external connectivity (outside k8s/compose) to a user's own database
Note - we already deploy coco pharma data within the odpi-egeria-vdc chart

This scenario may also extend to java sample code. If we create this it should be independent of the egeria source tree (and will be outside)

**Comment by planetf1** [comment]
See also #2399 which proposes the idea of using postgres for virtualization

**Comment by mandy-chessell** [comment]
@wbittles - this one is for you ...

**Comment by mandy-chessell** [comment]
The postgres connector has been delivered thanks to @wbittles (see https://github.com/odpi/egeria-database-connectors)

and work has been done to incorporate the connector in container environments thanks to @planetf1.

THe next step is to incorporate it into the labs.
