### ISSUE TITLE
Strange REST API for Open Lineage Services Configuration

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#2404]
What is the purpose of the two different methods for configuring the open lineage services.
I see 2 endpoints:
```
   /**
     * @param userId             user that is issuing the request.
     * @param serverName         local server name.
     * @param openLineageServerConfig configuration properties for open lineage server
     * @return void response or
     * OMAGNotAuthorizedException     the supplied userId is not authorized to issue this command or
     * OMAGInvalidParameterException invalid serverName or accessServicesConfig parameter.
     */
    @PostMapping(path = "/open-lineage/configuration")
    public VoidResponse setAccessServicesConfig(@PathVariable String userId,
                                                @PathVariable String serverName,
                                                @RequestBody OpenLineageServerConfig openLineageServerConfig)
    {
        return adminAPI.setOpenLineageConfig(userId, serverName, openLineageServerConfig);
    }


    @PostMapping(path = "/open-lineage")
    public VoidResponse enableOpenLineageServices(@PathVariable String userId,
                                                  @PathVariable String serverName)
    {
        return adminAPI.enableOpenLineageService(userId, serverName);
    }
```
Neither has sufficient Javadoc to explain what they are for.  When I look at the implementation then `adminAPI.setOpenLineageConfig` looks reasonable.  However the `adminAPI.enableOpenLineageService` seems to retrieve the config from the store and then puts it back into the config store unchanged - what is the purpose of this?

**Comment by GuyAckermans** [comment]
adminAPI.enableOpenLineageService appears to be redundant. I will remove it.

Many other governance engines (e.g. security synch, dataplatform) seem to have the same implementation.

**Comment by GuyAckermans** [comment]
The method for setting a governance server config could maybe be moved to a common code base? It seems to be very similar between governance engines.

**Comment by GuyAckermans** [comment]
The enableOpenLineageServices call has been duplicated by many governance governance servers developers even though it is redundant. Having a common code base could help in preventing code quality issues like these.

**Comment by mandy-chessell** [comment]
There probably are common functions that can be added for governance servers - in the way that we have done for access services - however the Open Lineage Services is the first governance service that is scheduled for release - and so I would expect a greater level of maturity for it than other governance services - for example - how do you disable these services in a server?  What are the values that are valid in each field?
