### ISSUE TITLE
Duplicates in OMRSErrorCode

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#2410]
There are some duplicate messageIds and formatting differences in OMRSErrorCode, for example `OMRS-REPOSITORY-400-062` is defined twice with different information each time.

We should probably apply some test to ensure uniqueness during the build (think I saw such a test elsewhere, maybe in AuditCode?)

**Comment by mandy-chessell** [comment]
Agreed - the only way to keep the messageIds unique is to test in the unit tests.  In some modules I have messageId uniqueness tests but the list of messages to test is manually maintained.   I have been thinking that this should be changed to work with the iterator that each enum has to ensure complete coverage event when new messages are defined.

**Comment by mandy-chessell** [comment]
Example - see ErrorCodeTest in the asset-consumer-api.  It tests for uniqueness but only on a manually maintained list
