### ISSUE TITLE
Improve wording of platform shutdown message

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#2444]
If Egeria is shutdown - ie with CTRL-C in a tty, the message produced is:
```Platform shutdown requested. Temporary deactivating any auto-started servers```

This could be improved

* 'Temporarily is the correct word to use.'
* ALL servers will be shutdown, not just the auto start ones
* Servers affected could be listed
* Specifying the name of the platform/host+port or some identifier would be useful
* could add a timestamp

**Comment by bogdan-sava** [comment]
When shutdown the platform, in my opinion, all the servers suppose to be temporary deactivated, so let other members of the cohort know about they are not available

**Comment by mandy-chessell** [comment]
Unfortunately both assertions are not correct and I have only just corrected the behaviour to only auto-shutdown those servers that were auto-started. 

This is explained in the issue where the change was made - but to summarize
- The temporary deactivation of the server unregisters the server from the cohort.  This causes an update to the enterprise connectors in all of the other members of the cohort(s) to remove the server from their list.
- When the platform is part of a HA cluster, individual platform instances may be recycled on a regular basis.  This may be to apply a rolling patch.
- If the servers in this platform are temporarily deactivated, they will unregister the server from the other members of the cohort even though there are other platforms running the server and so the unregistration request is inappropriate.

**Comment by mandy-chessell** [comment]
It is fine to change the message to include a time stamp, list the server names and change "temporary" to "temporarily" just please do not change it to shut down all servers running on the platform.

**Comment by planetf1** [comment]
In my scenario (CTRL-C) all servers are going to shut down anyway -- though it may be via different routes. It was here I was thinking knowledge of which were shutting down would be useful.

But from the discussion above it's clear we have a few cases when servers shutdown
 - a temporary shutdown for operational reasons - ie a server crashes, platform is stopped etc- in which case membership shouldn't be removed from a cohort even temporarily
 - an explicit temporary shutdown/pause - in which case they should be removed
 - an explicit permanent shutdown - in which case they should be removed  & definitions deleted

In a development case it's somewhat easy to accidentally conflate these (as I did).

I agree that a platform shutdown should be regarded as the first - very temporary. We should have an explicit, assertive action for the other two.

On that basis I agree with @mandy-chessell above, & definitely would not modify the behaviour of what is 'shutdown'

I would still
 * ensure the message going to stdout includes timestamp, server names etc that the action is being taken on
 * Additionally looking at adding a message when the platform is being shutdown to notify that the following servers X/Y/Z will be unavailable here... this is more of admin info .. as you say the slack may be taken up elsewhere in another container, on another machine, but it's still useful to see it in the logs of this particular system.. since the java process is about to go. (needs to be quick)
 - which is still inline with my original observation

**Comment by mandy-chessell** [comment]
The message only comes out now if there are auto-started servers.  It has a timestamp and lists the servers being stopped.
