### ISSUE TITLE
Potential for NPEs during exception construction

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#2446]
I found a few spots where our own Exceptions were debug-logging, and explicitly calling methods like `.toString()` on objects that could be null (and would thus result in an NPE as part of throwing such an exception).

I don't believe there's any reason for such debug-logging to remain in these exceptions, so will remove it; alternatively, we should do null-handling before attempting to call such methods.

**Comment by mandy-chessell** [comment]
I had a look at the PR and it is just removing the debug logging which does not seem to be a helpful approach.  The fields in question should never be null if the caller is using them properly.  The correct fix is to police the parameters and at least log an error if any of the fileds are null.

**Comment by cmgrote** [comment]
Fair enough -- the change you're suggesting is simple enough, but I'm wondering if it's the best approach?

> The fields in question should never be null if the caller is using them properly.

On this point, I hesitate to suggest that the caller is using them improperly because looking at the implementation there isn't anything asserting that the `caughtError` parameter cannot be null.  For example, trace the `ConnectionCheckedException` constructor and it goes through successive `super()` calls to:

- `OCFCheckedExceptionBase` (which if `caughError` is null simply sets a private member that is already `null` by default to `null` again)
- to `Exception` (which only passes along to its `super()` and does nothing else)
- to `Throwable`, whose JavaDoc for the constructor that is called explicitly states "`cause` [the name of the same parameter in Throwable's constructor] the cause (which is saved for later retrieval by the `getCause()` method).  (A `null` value is permitted, and indicates that the cause is nonexistent or unknown.)"

Therefore, following Java's own implementation and our extension of this implementation, I think it can be argued that `caughtError` could feasibly be `null` (ie. indicating that the cause is nonexistent or unknown, just as it does within the core Java exceptions / throwables themselves)?

I argue the point only because in places where we as developers may want to simplify our exception raising, we may want to define some simple methods that throw exceptions after constructing all the proper formatted strings, etc -- so each time we need to throw such an exception we have 1 line of code rather than constantly copy / pasting the 5-6 lines it otherwise requires each time.  (Just like the `reportUnsupportedMandatoryFunction()` and other similar methods in `OMRSMetadataCollectionBase`, for example).

If we assert that we must choose between these two constructors, even though in reality their implementation would mean (this debug-logging question aside) you obtain precisely the same constructed exception, it means that as developers we need double the number of lines of code to implement these generic methods (check for a null cause, depending on the result call one constructor or the other).  Multiply this by all the potential exceptions we might want to create such methods for, and it seems like a lot of unnecessary code we're putting in on the caller's side?

> The correct fix is to police the parameters and at least log an error if any of the fields are null.

If we can't agree on the above point, and still want to police these parameters, then in this case I would suggest making use of some annotation like `@NotNull` on the parameter in the call, so that developers are actually warned about this inline in their IDE.  Adding logic that does a `log.error()` call when the parameter passed is null raises the question of who will actually see that error, and when, since it will only show up if _all_ of the following conditions hold:

- only at runtime
- only if that code path happens to be hit (at runtime)
- only if the person running the platform has enabled the logging at that level of severity (which thus far we seem to be actively discouraging to ensure we build proper audit log output?)

In other words, a developer would never be told up-front if their call to the constructors is problematic, and would never know it unless they happen to hit the condition during some testing (while having debug-logging enabled at the same time).

Therefore this error-logging approach doesn't seem like the most valuable to developers, who would be the only ones in a position to actually fix the "problem" (albeit whether they fix it or not, per the first point above the behavior of the system would be identical, begging the question whether it's worth all this effort to police, raise errors, and "fix"?)  IMHO it seems like we're just polluting the log output...

One final side point, which we might want to raise a new issue on: I would strongly encourage us to look for any other locations where we are constructing concatenated strings and passing this singular string to any logger method -- this is problematic not only for its potential for an NPE (such as this example when using `.toString()`) but also because it means that the entire string must be constructed (all the `.toString()`s called and their result instantiated and concatenated) regardless of whether that particular logging level is even enabled or not: meaning a waste of processing and heap.  Passing these variables as arguments after a formatting string leaves it up to the logger to determine whether to actually construct any of these strings or not, depending on whether the logging level is enabled or not at runtime.  (The first thing the logger does is check whether the level is enabled, and only if it is does it actually go about formatting the string and plugging in the various parameters provided into the formatted output.)

**Comment by planetf1** [comment]
Just a side reference wrt concatenation and formatting - we need to consider injection ie https://github.com/odpi/egeria/issues/1670

**Comment by cmgrote** [comment]
> Just a side reference wrt concatenation and formatting - we need to consider injection ie #1670

It appears that this injection potential exists regardless of using the concatenation or the formatting approach, though, if I'm following correctly?

(Although presumably if we get rid of concatenations and use only the formatting approach it will be easier to determine where there might be an injection as the string we code will be fixed, so we only need to check the object array that is passed as arguments for the formatting?  And this should probably be done for all sorts of reasons beyond logging, ie. in any case where we've received input directly from a user, as that would be the surface for injecting into all sorts of areas?)
