### ISSUE TITLE
Bugs in Understanding Cohorts notebook

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#2458]
```
serverName = "cocoMDS2"
serverPlatformURL = 'http://localhost:8080'
serverPlatformName = "platformName"

queryServerCohorts(serverName, serverPlatformName, serverPlatformURL)
```

Is found under 'querying a server's cohorts'

This reference is invalid in a container environment. cocoMDS2 is on core, so should use 'corePlatformURL' as initialized earlier in this notebook as
```
corePlatformURL     = os.environ.get('corePlatformURL','http://localhost:8080') 

```

**Comment by planetf1** [comment]
Additionally this notebook would benefit from adding
```
%run ../common/environment-check.ipynb
``` early on, so that it works even if the user hasn't yet explicitly run the config/start notebooks

**Comment by planetf1** [comment]
platformURLroot is also not initialized in this notebook - it should be set to one of the platforms pre-configured (dev/core etc)

**Comment by mandy-chessell** [comment]
Sorry Nigel, I'll fix it
