### ISSUE TITLE
Question: regarding repository not supporting general regex

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#2462]
If a repository does not support searching by general regex, is it preferable for it to return no instances, or to throw a FunctionNotSupportedException?

Our approach until now has been the former, but the IGC connector implements the latter - which does have a nice degree of clarity.

I am happy with either but will need to adjust the expectations of the CTS search tests if we adopt the exception.

**Comment by planetf1** [comment]
From a consumer perspective I'd prefer the clarity of the FNSE

**Comment by grahamwallis** [comment]
One caveat with the exception approach is that the error message would need to clearly identify which requested function is not supported. Sounds obvious, but currently when the IGC connector throws an FNSE in response to a find request we 'implicitly' know that it's because it doesn't support general regexes. There are many parameters that we pass to a find request, so we would need to at least indicate which parameter is asking for function that is not supported.

**Comment by cmgrote** [comment]
> One caveat with the exception approach is that the error message would need to clearly identify which requested function is not supported.

Did you mean which _function_, or which requested _parameter_ is not supported (or both)?

**Comment by grahamwallis** [comment]
I meant both - where function was intended in the sense that the caller is requesting some function that is not supported by the method they called. (function != method).

i.e the long description.....The caller has invoked a method passing a set of parameter values that will dictate what function the called method tries to perform. During execution of the called method, it discovers that it has been asked to perform some function that it cannot deliver, either because it is bing asked to match a general regex, look back in time, provide sequenced results, etc etc. If possible it would help if the method throws an FNSE that identifies what function cannot be delivered and if possible which parameters are requesting that undeliverable function.

**Comment by cmgrote** [comment]
Ok, sure, but I guess that's just part of the message (which needs to be human-interpretable)?

If we want it to be programmatically-distinguishable we should really have different exceptions for each scenario, which changes the interface...

**Comment by grahamwallis** [comment]
Per today's call we discussed this and agreed that it is preferable to throw the exception.
A human interpretable error message is desirable for the CTS tests - to enable the tester to diagnose the specific cause of the failure from the test report alone.
The enterprise connector already has a result merge algorithm for federated queries that prioritises failures as part of forming the aggregated result set.

I will use this issue to alter the CTS to tolerate a FNSException from the advanced regex tests.
There should be no need to change any of the existing repository connectors.

**Comment by grahamwallis** [comment]
Fixed by #2494 (sorry, I did say I was going to use this issue to fix, but instead it was easier to roll this change in with the others in #2494)
