### ISSUE TITLE
Various broken links on website

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#2464]
I've noticed various broken links the last time I tried to navigate the website (egeria.odpi.org).  I'm wondering if there might be some utility out there that we should at least run periodically that would automatically crawl through the website and feedback any such broken links to us so that we can proactively fix them?

(I'm guessing not necessarily as part of the build process, since the website itself isn't updated until after a build is merged, but maybe something we could at least have run once a day or the like?)

@planetf1 any ideas? 🙂

**Comment by planetf1** [comment]
I did raise some issues with @jmertic & chris so hopefully the worst offenders are fixed.

However any automatic checking could be useful. A google search shows a variety of attempts for different scenarios 'github actions link checker'

**Comment by planetf1** [comment]
Nothing obvious in github actions marketplace - https://github.com/marketplace?before=Y3Vyc29yOjQx&query=pages&type=actions&utf8=✓

Github uses jekyll - see https://jekyllrb.com/docs/configuration/ . But no obvious options for checking. Some themes have aids, and there are external tools ....

**Comment by jmertic** [comment]
Tried this tool...

https://github.com/aarmora/jordan-does-dead-link-checking

Which gave me the attached output. Not sure if it's right or not...

[egeria.odpi.org-badlinks.json.txt](https://github.com/odpi/egeria/files/4092810/egeria.odpi.org-badlinks.json.txt)

**Comment by planetf1** [comment]
I've noticed the link checker when run last night executed for 6 hours before being terminated..

See 
```
 Link Checker 5h 59m 49s
5
##[error]The operation was canceled.
1
Run peter-evans/link-checker@v1
4
/usr/bin/docker run --name dfb81d21ce2ff854228af120899e8a0e146_9f4059 --label 488dfb --workdir /github/workspace --rm -e INPUT_ARGS -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/egeria/egeria":"/github/workspace" 488dfb:81d21ce2ff854228af120899e8a0e146 -v -r *
5
##[error]The operation was canceled.
```
investigation needed - I'll reopen this Issue since its a new idea we are experimenting with

**Comment by cmgrote** [comment]
Agreed, let's leave the issue open for the moment; however, I've swapped that link checker for another as that original one had various false positive results without any way of indicating that they should be ignored.

(The new one is also showing some errors, though, so will work through those...)

**Comment by grahamwallis** [comment]
Am I right in thinking that the link checker is checking all the forks? I seem to be getting notifications about link problems from my fork, which I keep almost up to date with master. I would have thought that it should be focussed on master. Am I missing something?

**Comment by cmgrote** [comment]
> Am I right in thinking that the link checker is checking all the forks? I seem to be getting notifications about link problems from my fork, which I keep almost up to date with master. I would have thought that it should be focussed on master. Am I missing something?

Interesting...  do GitHub actions run on all forks?  There isn't anything we have specified in the config (that I'm aware of) that would cause this, unless it's the default behavior (?)

**Comment by planetf1** [comment]
When I look at my github actions output I am only seeing it run on odpi/egeria -- NOT my fork

**Comment by cmgrote** [comment]
> When I look at my github actions output I am only seeing it run on odpi/egeria -- NOT my fork. Furthermore I believe the repo owner (ie fork owner) would need to approve that particular action to run.

It looks to me like the long-running ones _are_ running on your fork (eg. this one that was cancelled after running for 6 hours):

- https://github.com/planetf1/egeria/runs/428786334?check_suite_focus=true

The ones running on master take a matter of minutes:

- https://github.com/odpi/egeria/actions?query=workflow%3A%22Check+documentation+links%22

Actually, though, I guess it makes sense that they will run everywhere as the configuration of the Action is part of the code itself (under `.github/workflows/...`) -- not something setup separately through GitHub.  So I suspect that by default any fork that has Actions enabled will automatically pickup any actions we add and run them on the fork as well?

**Comment by cmgrote** [comment]
It seems that if we want to _not_ have this be the case, it is up to the fork owner to disable actions in their own fork?

<img width="897" alt="Screenshot 2020-02-06 at 11 37 09" src="https://user-images.githubusercontent.com/5864283/73933801-2b4e3100-48d5-11ea-84cc-6d6f20fa9f0a.png">

**Comment by grahamwallis** [comment]
Thanks Chris - I've disabled them on my fork.

**Comment by cmgrote** [comment]
Closing as we now seem to have the link checker operational and (I think?) only running on master.  Suggest if there are still problems with actions running against all forks that we open a new issue on that topic specifically.
