### ISSUE TITLE
Document example of OMRS interactions

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#2470]
Per call today, would be helpful to document an example of the OMRS interactions across 2 metadata repositories, their local OMRS collections, the enterprise connector, event mappers, etc -- to understand how areas like queries against the repos are used to create events that propagate to the rest of the network (and how refresh requests / events work into that mix).

**Comment by cmgrote** [comment]
@grahamwallis is it possible to share what you had documented so far somewhere?

**Comment by grahamwallis** [comment]
Keep open
