### ISSUE TITLE
Further describe "anchorGUID" on SchemaElement

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#2483]
On today's call we discussed the intended behavior of `anchorGUID` in eg. SchemaElement.  We discussed that it should point to the `Asset` (when there is an `Asset` involved); however, the current types describe that it simply points to a `Referenceable`.  I believe we should create an update to the types to change this attribute's description to refer to the `Asset` level (when available) rather than a `Referenceable` in general?

(In other areas, particularly around discovery, that `anchorGUID` is used it does refer to `Asset` rather than `Referenceable`.)

From type archives 1.2:

```java
private EntityDef getSchemaElementEntity()
    {
        final String guid            = "718d4244-8559-49ed-ad5a-10e5c305a656";
        final String name            = "SchemaElement";
        final String description     = "An element that is part of a schema definition.";
        final String descriptionGUID = null;
        final String superTypeName   = "Referenceable";

        EntityDef entityDef = archiveHelper.getDefaultEntityDef(guid,
                                                                name,
                                                                this.archiveBuilder.getEntityDef(superTypeName),
                                                                description,
                                                                descriptionGUID);

        /*
         * Build the attributes
         */
        List<TypeDefAttribute> properties = new ArrayList<>();
        TypeDefAttribute       property;

        final String attribute1Name            = "anchorGUID";
        final String attribute1Description     = "Optional identification of the referenceable that this schema element is a part of.";
        final String attribute1DescriptionGUID = null;

        // ...
    }
```

**Comment by mandy-chessell** [comment]
For further info - here is the definition of an "achor" from the Egeria website.

https://egeria.odpi.org/open-metadata-implementation/access-services/docs/concepts/anchor.html

**Comment by cmgrote** [comment]
Per the definition:

> Anchors are metadata entities that group other entities together. They act like containers. This means, for example, if the anchor is deleted then the entities linked to the anchor are also deleted.

I'm still not sure this is explicit enough for us to point that in cases where an Asset exists it should point to that.  In the case of a SchemaElement, I could still consider that it is contained within the SchemaType, that when the SchemaType is deleted the SchemaElement should also be deleted, and therefore by the definition above that the anchorGUID could point to the SchemaType -- but we explicitly agreed on the call that we should point to the Asset when available (and I don't think this is explicitly documented).

I also think the definition as documented there at the moment is confusing, as it appears contradictory:

> Anchors ... act like containers. This means, for example, if the anchor is deleted then the entities linked to the anchor are also deleted.

And then just below in another paragraph:

> ... not all metadata entities linked to an anchor are deleted when the anchor is deleted.

(I think we're trying to explain something about the directionality of the anchorGUID?  eg. that if the object with the anchorGUID attribute is deleted the other object it pointed to remains; but if we delete the object that has any others that reference it via an anchorGUID attribute then these other referencing objects should also be deleted?)

**Comment by mandy-chessell** [comment]
Happy for you to create a better definition - I just pointed you to this so you can update the description in context.  

It is similar to the distinction between a composition and an aggregation in UML in that it relates to the lifecycle of the linked objects.  However in Egeria it is more than the relationship between 2 objects - it is a cluster of objects.  For asset, for example, when we delete an asset, the schema, connections, feedback and comments are all deleted, but objects such as the license are not.  When the connection is deleted the connector type and endpoint are not deleted because they can be connected to many things and can exist on their own

**Comment by cmgrote** [comment]
Per linked issue, I think this additional description is helpful to find a way to incorporate as well (leaving as a note here for further cogitation on coming up with a revised description):

> The concept of an anchor is to describe the core object in a cluster of related objects that describes a single external concept. An example is a schema element to its asset. We only use the anchorGUID for elements that are not directly connected via a relationship, but instead by a chain of entities and relationships.

**Comment by cmgrote** [comment]
From today's call we agreed:

- we will change the description of the `anchorGUID` property within SchemaElement to make explicit that it should only ever refer to the top-level Asset of the schema (and that the property is optional)
- we will retain the name `anchorGUID` for the property for consistency with other areas
- if in the future we still require more clarity, we could consider having a specific property, but for now we do not think this will be necessary

**Comment by mandy-chessell** [comment]
@cmgrote Hi Chris - master is now set up to make type changes for the 1.5 release - add the TypeDefPatch to `OpenMetadataTypesArchive` class.
