### ISSUE TITLE
Adding an "anchorGUID" property to Process

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#2508]
In further discussions from today's call, we identified that it would be useful to have something like the `anchorGUID` property on a Process, which could be used by a low-level (child) Process to point directly at its containing (parent) Process.

This would allow us to:

- Short-cut calculating this hierarchical relationship through what could be many relationships traversing many types in-between.
- Short-cut the determination that when a containing parent Process is deleted, it likely means that its contained (child) Processes should also be removed. **

However, I believe this approach would also differ from elsewhere we have `anchorGUID` since in this case it would be pointing to other instances of the same type.

**Are we amenable to adding such a property to Process (even if we call it something else, perhaps `owningProcessGUID`)?)**

** Taking DataStage as an example, this won't _always_ be the case (ie. at all levels).  For example, a Job owns the stages that it runs -- so in that case if the Job is deleted then any stages with the property set to that job's GUID should also be deleted; however, a Sequence (highest level) does not own the Jobs it runs, so deleting the highest level (Sequence) should not delete any Jobs that happen to be used within the sequence.  We may therefore want to only populate such an attribute where there is truly a containment / ownership relationship (in this example, between Stage and Job, but not between Job and Sequence)?

Also note that this will not preclude the fix that ensures we have multiple PortAliases and PortDelegation relationships between the different levels of Processes -- which will ensure that we can still figure out the parent-child relationship between eg. Sequence and Job in the example above even without this new property being populated (for the reasons outlined above).

**Comment by mandy-chessell** [comment]
These are the problems with this proposal which I think is already outlined above.

- The concept of an anchor is to describe the core object in a cluster of related objects that describes a single external concept.  An example is a schema element to its asset.  We only use the anchorGUID for elements that are not directly connected via a relationship, but instead by a chain of entities and relationships.  So having an attibute that is called anchorGUID would be confusing because it is linking 2 anchor objects.

- It is more appropriate to add a new relationship between the processes to show parent child-relationship.  This relationship could be used for processes where there is not the schema detail or as a short cut for the detailed use cases.

**Comment by cmgrote** [comment]
Thanks @mandy-chessell -- this helps broaden my understanding of `anchorGUID`s as well, for #2483 🙂 

Based on the above rationale, I would then propose the following:

- Adding a new relationship to the open types called `ProcessOwnership`, with one endpoint being `owningProcess` ("the parent process that acts as a container for the child") and the other being `ownedProcess` ("the child process that is contained within the parent") and cardinality of 1 parent to many children
- Modifying our DE OMAS payload for the Process object to include a `parentProcess` property.  If populated, this would create an instance of the `ProcessOwnership` type above with the `ownedProcess` being the one represented by the payload and the `owningProcess` being the one described by the value of this `parentProcess` property.  (For DataStage I would want to just send the `qualifiedName` of the parent process here, but other DEs might want to send a guid -- so I would suggest as we've done elsewhere that this property would have two sub-properties: a `guid` and a `qualifiedName`?  And as elsewhere the DE OMAS would need to lookup the `qualifiedName`, if provided, to see if there is already an entity with that defined.)
- In the case of DataStage I would populate this property only for the Stage-Job relationship (where there is ownership), but not for the Job-Sequence relationship (where there is not ownership).

@popa-raluca @DimitriosMaimaris ^^ would this work?  Any objections / concerns / alternatives we should consider?

(One that I just thought of is that since I'd be providing the relationship details on the child process, but I'm sending the child processes first, the parent process it refers to would commonly not exist when you're creating the child -- so you'd probably need to create a proxy for the parent if it is not already there (and "upgrade" it later to a full entity once you receive the parent process)?)

**Comment by popa-raluca** [comment]
Sounds good - I'm not sure yet how I can upgrade a proxy entity to a full one.
Alternatively, I could create all the ProcessOwnership relationships at the end when processing the payload, after all the processes have been created

**Comment by cmgrote** [comment]
Actually @mandy-chessell raised a good point that we don't need to be quite this strict in the relationship (ie. use it only for containment).  I'd suggest a slight revision to above as follows:

- We call the new relationship `ProcessHierarchy`, and the endpoints would be `parentProcess` ("the parents of the nested child processes") and `childProcess` ("the processes nested in the parent process").  The cardinality would change to be many-to-many (the same child process could be used in multiple parents, and a given parent could have multiple child processes).
- We add a relationship attribute (of type enum) called `containmentType` with possible values "USED" and "OWNED" indicating whether this hierarchical relationship indicates simple usage (first value) or ownership / containment (second value).
- Our DE OMAS payload would then have an array for `parentProcess` (to allow multiple), and each element of the array would have 3 sub-properties: `guid`, `qualifiedName` and `containmentType`.
- For DataStage, I would populate this property for the Stage-Job relationship (where there is ownership) with the `containmentType` set to `OWNED` and for the Job-Sequence relationship I would populate it with `containmentType` set to `USED`.

A tiny bit more complex, but hopefully still feasible?

**Comment by cmgrote** [comment]
From today's call: should try to come up with a complete list of enumerated values (and include `Other`) as these cannot change after the type is initially released.
