### ISSUE TITLE
CTS still capturing some unexpected exceptions without sufficient context

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#2509]
I can still see at least one case where the CTS is capturing an unexpected NPE without providing sufficient context when logging it -- for example:

```
{
  "profileId": 0,
  "requirementId": 3,
  "testCaseId": "repository-find-attribute-typedefs-by-category",
  "testCaseName": "Repository find attribute type definitions by category test case",
  "testCaseDescriptionURL": "https://egeria.odpi.org/open-metadata-conformance-suite/docs/repository-workbench/test-cases/repository-find-attribute-typedefs-by-category-test-case.md",
  "testEvidenceType": "UNEXPECTED_EXCEPTION",
  "assertionMessage": "Unexpected Exception NullPointerException : null",
  "conformanceException": {
    "exceptionClassName": "java.lang.NullPointerException"
  }
}
```

This isn't really enough to go on to track down the problem, as nothing is logged via the audit log or debug logging to the console either (the stack trace is entirely lost).

**Comment by cmgrote** [comment]
In the particular example above the root cause was naturally a bug in one of the connectors; however, it does expose areas in the CTS itself where NPEs can occur -- in this case:

- `TestFindAttributeTypeDefsByCategory` can be constructed with a null value provided to `allAttributeTypeDefs`.
- The final assertion of the `run()` method of the same class attempts a `.size()` on this parameter, which if it has been constructed with null of course results in an NPE from the CTS itself.

**Comment by cmgrote** [comment]
(Suggest that we just solve this point issue by adding null handling, but might be worth a Sonar scan review to see if there are other spots where NPEs could occur and tackle them pro-actively as well?)

**Comment by grahamwallis** [comment]
The PR that fixed issue #2472 handled this for all the instance test cases.
The same approach could be used to handle unexpected exceptions from the typedef test cases.

**Comment by grahamwallis** [comment]
A Sonar scan of the CTS generally shows up a lot of false alarms - because Sonar doesn't realise that assertCondition will throw an exception if the condition is not satisfied. So it reports 'possible null' even after assertCondition(something != null), ...

**Comment by grahamwallis** [comment]
Keep open
