### ISSUE TITLE
Create superclasses for integration governance servers

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#2512]
We have a set of governance servers that simply host connectors that integrate with third party tools to exchange metadata:

- Receiving third party events and transforming them to a call to the client of an OMAS.
- Receiving outTopic events from an OMAS and turning them into calls to an thrid party API.
- Regularly polling a third party API and updating the open metadata through a client of an OMAS.
- Regularly polling a third party API and sending it update requests when its content is out of date with the open metadata retrieved through a client of an OMAS.

What is different for each case is that there is are different types of connectors and a different OMAS involved.  However most of the logic in terms of server startup/shutdown/managing listeners and polling are common.

There are a number of new governance servers that follow this pattern in the backlog.  This issue is to use the development of the governance servers for AssetConsumer OMAS and CommunityProfile OMAS to establish a set of common services and framework to reduce the effort in writing these types of server.

Once it is in place we can look at moving the existing servers into these new services.

* Data Platform Server
* Data Engine Proxy
* Security Sync Server
* Virtualizer

**Comment by cmgrote** [comment]
Would indeed be good for the common functionality to be encapsulated in a superclass -- just to confirm we can still extend that superclass (if needed) to implement any minor differences that need to be catered for within a particular server or proxy, without needing to override or re-implement the common functionality?

**Comment by mandy-chessell** [comment]
Yes :)

**Comment by mandy-chessell** [comment]
There are 2 parts to this:
* a new type of server for the integration daemons
* a new type of server for the engine hosts.

**Comment by mandy-chessell** [comment]
Delivered as part of #3707
