### ISSUE TITLE
CTS completion status - complete (no it isn't)

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#2533]
Running the CTS notebook, fairly soon after launching the test I gathered status and read:
```

Retrieve repository-workbench status ...
   ... retrieving completion status from server CTS_Server ...

   ...... (GET http://localhost:8082/servers/CTS_Server/open-metadata/conformance-suite/users/garygeeke/status/workbenches/repository-workbench )

Workbench repository-workbench is complete.
```
Further down
```
Date of conformance test:          2020-02-03T10:58:45.397+0000
Number of tests that were run:     228
Number of tests that failed:       0
Number of tests that were skipped: 0
```
A few minutes later (using graph) I had the same, except with 1439 tests

The architecture of the CTS does make this a difficult question to answer 'is the test complete' -- but how we currently document it is misleading and confusing to someone new to the area.

Reading the text more finely it does specifically say 'completed it's synchronous tests' - but I think we need more caveats around use of the term 'completion'

**Comment by planetf1** [comment]
Note that something else odd went on in this test given the number run, but the 228 vs 1439 figure still supports the original issue report.

**Comment by grahamwallis** [comment]
The CTS notebook does include the following text:

> The repository workbench runs a lot of tests (several thousand) and it can take a while to complete. There is no 'completion event' because when the confirmance suite has completed the synchronous workbench tests it continues to run and will perform asynchronous tests in responses to events that may be received within the cohort. The consequence of this is that it is not easy to know when the CTS has 'finished'. However, if you scan the output console logging from the conformance suite it is possible to detect the log output:
> Thu Nov 21 09:11:01 GMT 2019 CTS_Server Information CONFORMANCE-SUITE-0011 The Open Metadata Conformance Workbench repository-workbench has completed its synchronous tests, further test cases may be triggered from incoming events.

It also goes on to describe what the tester might see following completion of the synchronous tests.

**Comment by planetf1** [comment]
Conversely I also saw just now:
```
Retrieve repository-workbench status ...
   ... retrieving completion status from server CTS_Server ...

   ...... (GET http://localhost:8082/servers/CTS_Server/open-metadata/conformance-suite/users/garygeeke/status/workbenches/repository-workbench )

Workbench repository-workbench has not yet completed.
```
```
Date of conformance test:          2020-02-03T14:06:30.129+0000
Number of tests that were run:     3936
Number of tests that failed:       0
Number of tests that were skipped: 0
```

which is also confusing

That being said it's tricky to think what we could say beyond the notes you posted, plus the CTS is quite a specialist area. So it may be reasonable to address this defect as 'wontfix'

**Comment by grahamwallis** [comment]
Hmmm.... that is more puzzling. Were you running more than one workbench (at the same time)?

**Comment by grahamwallis** [comment]
Following code review I am puzzled by this and cannot currently see how to reproduce it. Discussed it with @planetf1 and we have decided to close the issue and will reopen if the problem occurs in future.
