### ISSUE TITLE
DataEngineConnector/Proxy issues

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#2536]
This issue is about the DataEngineConnector definition located in module `data-engine-proxy-connector`.  This connector describes a plug point supported by the `data-engine-proxy-services`.  This means the classes and interfaces that support this connector should use the java package root of these services - that is they should be under:
```
org.odpi.openmetadata.governanceservers.dataengineproxy.
```
rather than
```
org.odpi.openmetadata.openconnectors.governancedaemonconnectors.dataengineproxy
```
where they are today.  This second package name would be where implementations of this connector would reside.

Another comment on this connector:
It passes the Data Engine OMAS's client to the connector.  This means:
   * the connector implementations are affected by any change to the Data Engine OMAS's client.
   * the connector implementation has to deal with server specific attributes such as the userId of the data engine proxy server.
  If the connector had a context object that wrapped the client:
     * it would offer a simpler interface to the connector implementation
     * the data engine proxy server could protect its connector implementations from changes
     * the data engine proxy server could ensure attributes such as the userId and externalMetadataCollectionId are set consistently on all requests.
This would be especially valuable since there seem to be userId properties throughout the property beans found in the model package.

**Comment by mandy-chessell** [comment]
One other thought - the connector methods are logging a warning if they are not overridden.
If they must be overridden, the methods could be abstract - like the class?
If they do not need to be overridden then why is there a warning?  Where does the connector developer go to find out if they have a problem or not?

**Comment by mandy-chessell** [comment]
Sorry for the continuous stream of comments - I am looking at the different implementations of the Governance Daemons for the common services and the polling mechanism here looks interesting.  However ...

I can not see the call to start the data engine proxy connector.  The change poller seems to be started if needed but not the connector.

I also can not see where the Thread is created when the change poller is not being used.  the connector still needs a thread to run in so that the admin start request can return?

Also the change poller is formatting and throwing runtime errors if anything goes wrong but there is nothing catching it - it would be better that the errors were going to the audit log (logException) as this is an unattended thread.

**Comment by cmgrote** [comment]
> ... This second package name would be where implementations of this connector would reside.

Good catch -- this was a remnant of the move of the Maven module, but clearly I forgot to rename the Java package!

> It passes the Data Engine OMAS's client to the connector....  If the connector had a context object that wrapped the client...

Yes, it would be good to clean this up.  Do we have such a wrapper / context pattern already implemented elsewhere that I could use as an example?

> One other thought - the connector methods are logging a warning if they are not overridden.

Another good catch: will clean this up to properly indicate which methods must be implemented (as abstract) and change methods that do not need to be overridden to simply log at a debug level rather than a warning.

> I can not see the call to start the data engine proxy connector. The change poller seems to be started if needed but not the connector.

Hmmm, right you are -- it seems that the connector is being started inside the change poller thread, rather than outside the thread and then being passed into the thread.  (At this point we have not put in any logic for a connector that does not require polling, so leaving that as a future TODO...)

> Also the change poller is formatting and throwing runtime errors if anything goes wrong but there is nothing catching it - it would be better that the errors were going to the audit log (logException) as this is an unattended thread.

Yes, thanks for catching that -- will fix.
