### ISSUE TITLE
Implement a repository with historical store

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#2545]
It appears that various metadata repositories do not capture and retain their own history of their metadata.

Could a simple (perhaps niche) use case for Egeria be to serve as such a historical store?

If so, suggestion here would be to create a tutorial that guides teams on configuring Egeria as such.

**Comment by mandy-chessell** [comment]
It is a good idea except we do not have a repository to do that at the moment.  Only the in-memory repository keeps history.  @grahamwallis and I have talked about extending the janusgraph repository to support history and agreed it needs to be a separate store - may be relational, maybe a search-type store - that the graph repository connector manages along side the graph store.

**Comment by cmgrote** [comment]
Ah, I suspected that might be the case -- I'll push it further out milestone-wise...

**Comment by grahamwallis** [comment]
> ...a separate store - may be relational, maybe a search-type store - that the graph repository connector manages along side the graph store.

Or could we use a possibly a more generic approach in which the history store can act as companion to any type of local repository?

**Comment by cmgrote** [comment]
Re-opening based on today's call -- there seems to be critical mass building towards the need to have a historical repository as potentially a quick on-ramp to broader consumption of Egeria.

**Comment by cmgrote** [comment]
A potential open source option for a bi-temporal back-end store is [Crux](https://github.com/juxt/crux) (MIT License), which provides bi-temporal over pluggable backends (immutable transaction logs via SQLite, Postgres, MySQL, H2, and commercial options like MS SQL Server and Oracle as well as graph-oriented indexes via the likes of RocksDB and LMDB).

The project also appears to be actively maintained (changes within the last few days and hours) by a number of contributors (perhaps half-a-dozen core contributors?)

**Comment by cmgrote** [comment]
We now have a store: https://github.com/odpi/egeria-connector-crux

... back to the original issue's suggestion: defining a tutorial on configuring Egeria to act as a historical repository "side-car" to another repository (that itself does not have history).

I suspect this will rely on some minimal event support from the other repository: at least the refresh events (could these be sufficient on their own to publish semi-history?), but more ideally a full set of events (so that we have a point-in-time event containing all details for every change, from which we can then populate the full history in the "side-car" repository).

**Comment by cmgrote** [comment]
Will likely consider how we leverage #5402 to accomplish this somewhat transparently and consistently.
