### ISSUE TITLE
JSON parse error: Could not resolve type id 'AccessServiceClientConfig' 

### ISSUE THREAD

**Issue by kkumar27** [odpi/egeria#2559]
While configuring the _findItDL01_ discovery engine services in the 'Coco Pharmaceutical' tutorial, following error is thrown:
`Configuring findItDL01 as a discovery server ...
   ... configuring the findItDL01 discovery engine services...
   ...... (POST http://dev:8080/open-metadata/admin-services/users/garygeeke/servers/findItDL01/discovery-engine-services/access-service )
   ...... Response:  {'timestamp': '2020-02-06T14:03:27.001+0000', 'status': 400, 'error': 'Bad Request', 'message': "JSON parse error: Could not resolve type id 'AccessServiceClientConfig' as a subtype of `org.odpi.openmetadata.adminservices.configuration.properties.OMAGServerClientConfig`: known type ids = [DiscoveryEngineServicesConfig, OMAGServerClientConfig, StewardshipEngineServicesConfig]; nested exception is com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'AccessServiceClientConfig' as a subtype of `org.odpi.openmetadata.adminservices.configuration.properties.OMAGServerClientConfig`: known type ids = [DiscoveryEngineServicesConfig, OMAGServerClientConfig, StewardshipEngineServicesConfig]\n at [Source: (PushbackInputStream); line: 1, column: 11]", 'path': '/open-metadata/admin-services/users/garygeeke/servers/findItDL01/discovery-engine-services/access-service'}
   ...... (POST http://dev:8080/open-metadata/admin-services/users/garygeeke/servers/findItDL01/discovery-engine-services/discovery-engines )
   ...... Response:  {'relatedHTTPCode': 200}`

Which in turn is throwing below error while running `%run common/environment-check.ipynb`

Error Thrown on Docker console:
`datalake_1   | Thu Feb 06 11:52:34 GMT 2020 findItDL01 Exception OMAG-ADMIN-0102 The admin services caught an org.odpi.openmetadata.adminservices.ffdc.exception.OMAGConfigurationErrorException exception whilst initializing the governance services subsystem for the Discovery Server called findItDL01; error message is DISCOVERY-ENGINE-SERVICES-400-008 The discovery engine services are unable to initialize a new instance of discovery server findItDL01; error message is DISCOVERY-ENGINE-SERVICES-400-002 Discovery server findItDL01 is not configured with the platform URL root for the Discovery Engine OMAS`

**Comment by mandy-chessell** [comment]
Apologies - I renamed the Java class and forgot to update the notebook
