### ISSUE TITLE
If server instance configured with event bus/kafka and started without kafka running = hang

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#256]
I attempted to configure and start an egeria server on a different machine to normal, and by mistake had not configured kafka.

The event bus configuration did specify kafka, using default ports/localhost.

When I tried to create the instance, the POST never came back after more than an hour. I would have expected a timeout and exception

The event bus was configured with
```
{
"producer":
{
"bootstrap.servers":"{{kafkaep}}",
"acks":"all",
"retries":"0",
"batch.size":"16384",
"linger.ms":"1",
"buffer.memory":"33554432",
"max.request.size":"10485760",
"key.serializer":"org.apache.kafka.common.serialization.StringSerializer",
"value.serializer":"org.apache.kafka.common.serialization.StringSerializer",
"kafka.omrs.topic.id":"{{cohort}}"
},
"consumer":
{
"bootstrap.servers":"{{kafkaep}}",
"zookeeper.session.timeout.ms":"400",
"zookeeper.sync.time.ms":"200",
"fetch.message.max.bytes":"10485760",
"max.partition.fetch.bytes":"10485760",
"key.deserializer":"org.apache.kafka.common.serialization.StringDeserializer",
"value.deserializer":"org.apache.kafka.common.serialization.StringDeserializer",
"kafka.omrs.topic.id":"{{cohort}}"
}
}
```
I also enabled access services, configured cohort (just this one), setup inmemory repo, and the instance create was with
{{baseURL}}/open-metadata/admin-services/users/{{user}}/servers/{{server}}/instance

The console log from the scenario is at https://gist.github.com/planetf1/0765a9bd1ce39334a07a15b8c3c48098 (the initial entries rolled off the log, but the errors repeat)

**Comment by planetf1** [comment]
Part of the reason for this is that launching the instance does a LOT of interactions with kafka.
Kafka not running is the worst case, but subsequent attempts let me hit another issue, which also had a similar effect.

I noticed the rest call not coming back, and I saw errors from OMAGApplication:

`Caused by: org.apache.kafka.common.errors.TimeoutException: Batch containing 1 record(s) expired due to timeout while requesting metadata from brokers for cocoCohort-0`

I think this is because the correct listeners were not being advertized to the clients. This is a kafka configuration issue arguably, but not necessarily obvious to debug.

The fix is to correct configuration - ie for a single local node one might add the following to kafka's server.properties:

```
listeners = PLAINTEXT://localhost:9092
advertised.listeners=PLAINTEXT://localhost:9092
```

I think we should look at a few aspects here
 * Adding useful tips on configuring kafka to the setup documentation
 * See if we can figure out kafka isn't active, and report a clearer, specific exception sooner
 * See if we can figure out we have an issue with the listener configuration returned back to the client, and similarly raise an exception
 * Look at whether the initial setup can be made more efficient - there seem quite a number of calls so far (which is why the request goes away for so long if requests timeout rather than returning in a few milliseconds)
 * Move to an async request/response model for any long running REST queries (whatever the reason). Users would expect them to return in seconds, perhaps a minute. an hour is not acceptable (if needed as we fix the above)

**Comment by mandy-chessell** [comment]
I am not sure an asynchronous pattern will be helpful as the hang alterted you to the incorrect configuration - if the REST call returned OK but the server is inoperable then it would be harder to detect the issue.

The rest of the Kafka specific aspects need to be fixed in the Kafka connector

**Comment by planetf1** [comment]
This has been fixed with recent kafka changes
