### ISSUE TITLE
Only run actions on odpi/egeria - not forks

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#2574]
We're seeing actions run against all forks of our repository. Some appear to work, other's (like the linkchecker) fail.

This causes noise, and to stop requires every fork owner to disable actions.

From https://help.github.com/en/actions/automating-your-workflow-with-github-actions/contexts-and-expression-syntax-for-github-actions it looks as if we could use a conditional expression to only run the action in question when the repository is 'odpi/egeria' (or similar for our igc/atlas connectors).

We need to be careful this doesn't cause any issues with PRs -- since the fork itself is owned by a user other than odpi.

I think this is worth trying out.

I will propose a change
cc: @cmgrote @grahamwallis

**Comment by planetf1** [comment]
This added on a step would work
```
if: github.repository == 'odpi/egeria'
```
more more generally
```
if contains('github.repository','odpi/')
```
looks better

Seems to be needed on each step to be skipped...

**Comment by planetf1** [comment]
Doesn't seem to be possible on entire action, though a cleaner way to avoid conditional clutter is covered in https://github.community/t5/GitHub-Actions/conditional-jobs-and-workflows/td-p/32166

**Comment by planetf1** [comment]
After merging, the overnight schedule run of the link checker still ran on my fork

I'm going to propose additional changes to add the conditional at the <step> level.

**Comment by cmgrote** [comment]
> After merging, the overnight schedule run of the link checker still ran on my fork

... and somehow it looks like it did _not_ run on the master repo (?)

**Comment by planetf1** [comment]
I can confirm this is working as expected.
 - odpi/egeria - stale/linkcheck actions ran successfully
 - planetf1/egeria (and anyone else's fork) - actions run but are a complete no-op and do not execute steps.

There's no way to completely stop an action from running (unless disabled for the forked repo), but this is a decent compromise.

**Comment by cmgrote** [comment]
> I can confirm this is working as expected.

I don't think it is -- looking at the detailed logs, the steps that had the condition against them are entirely skipped _on master_ as well: https://github.com/odpi/egeria/runs/440017789?check_suite_focus=true

I think this is related to the conditional doing a literal-value check rather than checking the value within a variable?  See PR #2584

**Comment by planetf1** [comment]
Last night actions ran completely on forks+odpi
Submitted new PR to resolve
