### ISSUE TITLE
introduce subject area view service and associated admin 

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#2577]

**Comment by davidradl** [comment]
This is server side only extension of the existing admin to add view services. subject Area will be the only one added here in this issue. This is a subset of issue #1942.

**Comment by davidradl** [comment]
I intending to merge this on the 20th of February (addressing any feedback). Let me know if this does not give enough time to review this change.

**Comment by mandy-chessell** [comment]
The code is using the same pattern as access services - does that mean we expect third parties to plug in view services into the view server in the same way that third party access services can be plugged into the metadata server/metadata access point?

**Comment by mandy-chessell** [comment]
One other thought - from a consumability point of view it may be better that the view services have different names from the access services to reduce the chance of people muddling them up?
