### ISSUE TITLE
When Kafka is temporarily unavailable during startup, OMRS cohorts never get initialized

### ISSUE THREAD

**Issue by jnhagelberg** [odpi/egeria#2595]
I have put together a fix for this issue which I will be submitting for review shortly.

We have seen this in a few cases where the Kafka pod gets into a weird state in our environment.  This is not a common scenario, but we have seen it enough times that it makes sense to do what we can to automate the recovery when Kafka does come back up.

What we have done here is put in a retry mechanism that kicks in if the initial connection to the cohort fails.  The retry mechanism is totally configurable and can be turned off If desired.  With the changes, the first initialization attempt is done synchronously, the same way it is now.  If the initialization attempt fails, then an additional attempt is scheduled to run in a background thread if certain conditions are met.  If that fails, we schedule an additional retry attempt.  We do this until the configured maximum number of retries have been exhausted.  The default behavior is that there is one retry thread shared between all of the cohorts.  This can be configured programmatically by applications that embed egeria.   In addition, the default number of retries is 20, and by default we wait 10 seconds between retries.  These are also configurable.  There are certain kinds of initialization errors we exclude from the mechanism.  These are for cases where we are sure that doing a retry will not resolve the issue.

The changes also introduce a new `CohortConnectionStatus`: `AWAITING_RETRY`.  If the intialization of the cohort manager fails in a way that is retryable (and the max retries have not been exhausted), the connection state is set to `AWAITING_RETRY`.  When the retry starts, the state will go to `INITIALIZING` and resume its usual progression.  If the initialization fails with an error that is not retryable, the state will stay at `CONFIGURATION_ERROR` (and no retries will be scheduled)

**Comment by jnhagelberg** [comment]
I've created https://github.com/odpi/egeria/pull/2596

**Comment by planetf1** [comment]
I added some comments to PR #2596 - seen before I saw the issue (catching up)

**Comment by planetf1** [comment]
We believe #2989 will address this scenario, and the PR in #2990 is now merged.

Please re-open if the fix is insufficient
