### ISSUE TITLE
Backward Compatibilty: restore ability to set topic name via 'kafka.omrs.topic.id'

### ISSUE THREAD

**Issue by jnhagelberg** [odpi/egeria#2605]
In older versions of egeria, it was possible to explictly set the name of the Kafka topic using a producer property named "kafka.omrs.topic.id".  We can see that behavior here: https://github.com/odpi/egeria/blob/736b84c87d16e59739d2fb0a9387907b364ad958/open-metadata-implementation/adapters/open-connectors/event-bus-connectors/open-metadata-topic-connectors/kafka-open-metadata-topic-connector/src/main/java/org/odpi/openmetadata/adapters/eventbus/topic/kafka/KafkaOpenMetadataTopicConnector.java

Unfortunately, with the more recent code, the desired topic name cannot now be set up front.  Instead it requires the configuration to be created using the default topic name, fetched back, updated in place, and then updated in Egeria through a configuration update.  While this process works, it is very cumbersome.  

Restoring this mechanism gives us a simple way to set the topic name we want to use up front and insulate ourselves from future default topic name changes.

**Comment by mandy-chessell** [comment]
This is going back to the initial Kafka Event Bus connector that took no account of the admin services.  It also used a Kafka specific approach for setting the topic id.  This is not suitable for Egeria where the Kafka event bus connector can be swapped out for another event bus service.
It was fixed as soon as we noticed the bug.

For many releases now, the topic name is set up in the connector configuration - in the address property of the Endpoint object.  This is consistent for all event bus implementations.  (It also follows the common pattern for other types of connectors too.)

The default topic name is only a default and you are in control of the configuration process.  If you do not like the defaults then do not use them for your private cohort.  There are admin commands that do not use the defaults.

If you are connecting to a public cohort, you need to use the topic name established for the cohort.  This may be the default topic name or something different.

We have an enhancement request to provide a REST call to update the cohort topic (#2514).
This will make it easy for an org to make changes to the topic name.  Providing this capablity makes it more likely that organizations will change the name of the topic for the cohort so it is going to be a common situation.

Having a private back door way of setting the topic name that only works for Kafka is a recipe for configuration errors that would be difficult to debug.  The property is not even one that is defined by Kafka.

**Comment by mandy-chessell** [comment]
Note, the change to remove support for `kafka.omrs.topic.id` occurred in release 0.2 of Egeria.  This was before the function was officially released.
