### ISSUE TITLE
REST API inserts not displaying on egeria.odpi.org

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#2607]
Throughout our documentation of REST APIs we have been using the POSTMAN placeholders - eg {{serverName}} - unfortunately these are interpreted as Jekyl variables and come out as a null.  Here is an example from Asset Consumer OMAS.

<img width="1075" alt="Screenshot 2020-02-18 at 09 04 13" src="https://user-images.githubusercontent.com/12354195/74720411-aa285f80-522d-11ea-98e0-f642db592b1e.png">

Initially I thought it was an error in the markdown but it is displaying ok in IntelliJ.

I have gone through and changed these to use single curly braces.  I have also made the insert names more consistent:

* {serverName} - for the name of the OMAG Server
* {serverURLRoot} - for the network address of the OMAG Server Platform
* {userId} - for the user Id of the caller 
       :

**Comment by planetf1** [comment]
If we want the docs to literally match what a user may type with postman, then there is a mechanism for doing this with jekyll markup (apparently - not tried)

```
https://stackoverflow.com/questions/24102498/escaping-double-curly-braces-inside-a-markdown-code-block-in-jekyll
```
If however we are just using them as a more abstract description, then any recognized parm replacement technique is fine. Especially where we have actual code samples in notebooks, postman collections, or curl/httpie snippets
