### ISSUE TITLE
Difference in neighborhood behaviour between in-memory and graph repositories

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#2628]
The getEntityNeighborhood method works differently between the in-memory and graph repositories, with regard to entity type filtering.

With either repository, if the entityTypeGUIDs filter parameter is null then all entity types are included in the returned subgraph.

If any entityTypesGUIDs are listed in the entityTypeGUIDs filter parameter then the two repositories behave differently. The difference concerns the root entity - i.e. the entity whose GUID  Is supplied to the getEntityBNeighborhood() method's entityGUID parameter.

The graph repository always includes the root entity in the subgraph; it is not subject to the filtering parameter. The root entity is included whether the filter is null, is non-null and contains the root entity's typeGUID, or is non-null and does not contain the  root entity's typeGUID.

The in-memory repository includes the root entity in the subgraph provided the filtering parameter is null or contains the typeGUID of the root entity. It does not include the root entity in the subgraph if the filtering parameter is non-null and does not contain the typeGUID of the root entity.

My opinion is that the in-memory repository should always include the root entity, regardlesss of the setting of the entityTypeGUIDs parameter.

A simple way to implement this change would be to check that, if the filter parameter is non-null and does not contain the typeGUID of the root entity, that the typeGUID is added the filter parameter. Alternatively, this could be fixed within the implementation of the InMemoryEntityNeighbourhood class.

@mandy-chessell @cmgrote - any comments? How do the proxy repository connectors handle this?

**Comment by cmgrote** [comment]
Easy: the repository proxies don't implement any of the graph queries (like neighborhood) 😉

**Comment by grahamwallis** [comment]
Fixed by #2838 at beginning of April
