### ISSUE TITLE
Create 1.5 Release

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#2654]
- [x] Create 1.x branch
- [x] Update master to 1.(x+1)-SNAPSHOT
- [x] Update branch from 1.x-SNAPSHOT to 1.x
- [x] Remove release notes from branch
- [x] Run tests including CTS
- [x] Ensure release is current in master release notes & Add any final text
- [x] Launch release pipeline 
- [x] Approve release
- [x] Verify artifacts on maven central
- [x] Publish final 1.x docker images
- [x] Create GitHub release
- [ ] Blog Post
- [ ] Update master with new Type patchfile

**Comment by planetf1** [comment]
Notebooks and CTS tests all look good with no additional failures

**Comment by planetf1** [comment]
Currently blocked by incomplete sync. See #2704 for an effort to add parallism. However that in itself caused additional issues, so reverting to N=1 to flush out the final packaging issues preventing sync.

**Comment by planetf1** [comment]
Current issues on the publishing are:

Not present in JCenter:
***-services-samples:1.5
discovery-engine-connectors:1.5
glossary-author-view:1.5
glossary-author-view-server:1.5
glossary-author-view-spring:1.5
readonly-repository-connector:1.5
stewardship-engine-services:1.5
stewardship-engine-services-api:1.5
stewardship-engine-services-client:1.5
stewardship-engine-services-server:1.5
stewardship-engine-services-spring:1.5
view-services:1.5

Va;idation failed:
open-metadata-conformance-suite-server:1.5 - no javadoc/signature
subject-area-server:1.5 - no sources/signature

Errors reported relating to repository: (could be related to a previous partial sync)
security-sync-connectors:1.5
security-sync-services:1.5
stewardship-action:1.5
stewardship-action-api

Bad Request from API
stewardship-action-client:1.5
stewardship-action-server:1.5

Source: https://dev.azure.com/ODPi/Egeria/_releaseProgress?releaseId=116&_a=release-environment-logs&environmentId=348

**Comment by planetf1** [comment]
Reporting to bintray issues with:

a) Packages that have  packaging=pom, and contain the required `<scm>` tag which are failing validation for no clear reason. This is a re-run of the problems last release where JFrog said we needed the scm tag, which we added.....

 glossary-author-view 
 stewardship-engine-services
 view-services

Packaging errors in egeria

Missing sources. These poms are defined as packaging=jar (default) but don't contain sources, which we know isn't permitted. It is basically invalud. We can either a) ignore b) add dummy source/javadoc/jar c) change packaging type to pom. Since these are mostly currently empty and not used, I'm inclined to leave as-is cc: @mandy-chessell 
 stewardship-engine-services-api
 stewardship-engine-services-client
 stewardship-engine-services-spring

Errors in artifactory -- missing signatures. This may be fixable by redoing the full build, perhaps signature gen failed for some reason?
 open-metadata-conformance-suite-server - no signature for the javadoc jar....

**Comment by planetf1** [comment]
The three packages failing validation are now synced to maven central after manual addition
The stewardship-engine-* packages will be left as-is, as they are currently empty, awaiting implementation in a future release

**Comment by planetf1** [comment]
Contacting LF team to see if they can re-sync https://odpi.jfrog.io/odpi/webapp/#/artifacts/browse/tree/General/egeria-release-local/org/odpi/egeria/open-metadata-conformance-suite-server/1.5 to bintray (I don't have permissions)

**Comment by planetf1** [comment]
See https://jira.linuxfoundation.org/servicedesk/customer/portal/2/IT-19257

**Comment by grahamwallis** [comment]
The link is only viewable to a limited audience

**Comment by planetf1** [comment]
> The link is only viewable to a limited audience

Yes it is sorry - I can't control that. It's included so that I can point the LF support team here for further info.

@bramwelt is looking at trying to republish that artifact. It looks to me as something went awry in the signing process, which is basically an artifactory operation as best I know

**Comment by planetf1** [comment]
Chasing up - still blocked from completing the release.

**Comment by planetf1** [comment]
Release 1.5 artifacts are now synced to maven central.
