### ISSUE TITLE
subject-area rest calls parameter 'SequencingProperty'

### ISSUE THREAD

**Issue by bogdan-sava** [odpi/egeria#2668]
Hi,

This is a parameter present in many subject area endpoints and it is the only parameter starting with capital letter in the entire rest API.

`@RequestParam(value = "SequencingProperty", required=false) String sequencingProperty
`
Is it intended or just a typo ?

**Comment by davidradl** [comment]
adding a comment to keep open

**Comment by davidradl** [comment]
@bogdan-sava thanks for spotting this - it was a bug :-)
