### ISSUE TITLE
Introduce a configuration change to allow the subject area omas to run in different modes

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#267]
Introduce a configuration change to allow the subject area omas to run in different modes, namely:
- only support minimal status 
- only support maximum status values
- support repositories as inclusively as possible. 

This configuration is to inform the subject area omas on when to use Glossary Term vs controlled Glossary Term

**Comment by mandy-chessell** [comment]
It should be possible to query the supported types from the Enterprise OMRS Repository Connector to determine if the ControlledGlossaryTerm is supported.  This would mean you would not need a configuration variable.

**Comment by davidradl** [comment]
@mandy-chessell I was thinking I could expose one concept of Term which could map to GlossaryTerm or ControlledGlossaryTerm and then use the config to determine how the OMAS would work with these different OMRS types. I thought the OMAS behaviour would then be more obvious. Do you think this works ?

**Comment by mandy-chessell** [comment]
What would be the scope of the configuration - per glossary; per deployment of the Subject Area OMAS or per cohort?   Who would be expected to configure it
