### ISSUE TITLE
Storing Classifications in Open Lineage Services

### ISSUE THREAD

**Issue by GuyAckermans** [odpi/egeria#2687]
Some questions about storing classifications for lineage:

1   Should all classification types be stored in OLS, or should we have a filter? A potential use case for storing all classification types could be: "Show me the complete list of all classifications that have ever been assigned to this glossary term"  (Provided we have historical lineage)

2 If we decide to filter on classification types, could we establish a list of classification types that are relevant for Open Lineage Services? 

3  If we decide to filter on classification types, should this filtering happen in the Asset Lineage OMAS (which events are published) or in the Open Lineage Services (which events are processed)? An argument to not place the filter in AL Omas could be that somebody who is interested in the classification types that we decide to filter out, could build his/her own version of OLS to receive these versions anyway.

**Comment by cmgrote** [comment]
IMHO:

1) Probably not, and I would suggest that the "show me the complete list of all classifications that have ever been assigned to _x_" is probably one (or more) other OMASes (?)

2) This sounds like the best approach to me: which classifications are relevant to lineage?

3) A configurable list for the AL OMAS, which we default to the set of classifications that we think are applicable (but that could therefore be easily overridden / extended if there are others of interest)?  If OLS then operated based on this same configured list, then it would be dynamic enough to be configurable, but narrow enough for a "default" set to be applied for filtering 🙂

**Comment by cong78** [comment]
I agree to have a default list that relevant to asset lineage context as long as the **Asset Lineage OMAS** can be configurable and able to filter relevant classifications to AL OMAS out topic, then the OLS can just store the classifications.
