### ISSUE TITLE
Building a data catalog notebook failures if run quickly

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#2688]
Scenario
 - 1.5 release code
 - odpi-egeria-lab chart deployed into openshift 4.3
 - Run through 'config' and 'start' notebooks
 - Open 'building a data catalog' and execute Run->Run All Cells

2 failures occur

**1. Zone visibility**

```
assetOwner = "tanyatidie"
ownerType  = "USER_ID"
​
addOwner(cocoMDS2Name, cocoMDS2PlatformName, cocoMDS2PlatformURL, erinsUserId, "Asset 1", asset1guid, assetOwner, ownerType)
addOwner(cocoMDS2Name, cocoMDS2PlatformName, cocoMDS2PlatformURL, erinsUserId, "Asset 2", asset2guid, assetOwner, ownerType)
addOwner(cocoMDS2Name, cocoMDS2PlatformName, cocoMDS2PlatformURL, erinsUserId, "Asset 3", asset3guid, assetOwner, ownerType)
​
addZones(cocoMDS2Name, cocoMDS2PlatformName, cocoMDS2PlatformURL, erinsUserId, "Asset 1", asset1guid, ["data-lake", "human-resources"])
addZones(cocoMDS2Name, cocoMDS2PlatformName, cocoMDS2PlatformURL, erinsUserId, "Asset 2", asset2guid, ["data-lake", "human-resources"])
addZones(cocoMDS2Name, cocoMDS2PlatformName, cocoMDS2PlatformURL, erinsUserId, "Asset 3", asset3guid, ["data-lake"])
​
Setting owner on Asset 1 to tanyatidie ...
Setting owner on Asset 2 to tanyatidie ...
Setting owner on Asset 3 to tanyatidie ...
Setting governance zones on Asset 1 ...
Setting governance zones on Asset 2 ...
Setting governance zones on Asset 3 ...
Once these zones are set up, Callie can see the assets:

[17]:

assetConsumerPrintAssets(cocoMDS3Name, cocoMDS3PlatformName, cocoMDS3PlatformURL, calliesUserId, newFilesSearchString)
No assets found
```

In fact we should see assets here. 

**2. Retrieving assets** 
```
server2AssetEntityQuery = server2RepositoryServicesURL + '/instances/entity/' + asset1guid
​
print (" ")
print ("GET " + server2AssetEntityQuery)
​
response = requests.get(server2AssetEntityQuery)
​
print ("Returns:")
prettyResponse = json.dumps(response.json(), indent=4)
print (prettyResponse)
print (" ")
 
GET http://lab-core:8080/servers/cocoMDS2/open-metadata/repository-services/users/garygeeke/instances/entity/10b3bd34-e491-4cc2-9791-3a60b4e3f6f8
Returns:
{
    "class": "EntityDetailResponse",
    "relatedHTTPCode": 400,
    "exceptionClassName": "org.odpi.openmetadata.repositoryservices.ffdc.exception.EntityProxyOnlyException",
    "exceptionErrorMessage": "OMRS-REPOSITORY-400-051 A request for entity 10b3bd34-e491-4cc2-9791-3a60b4e3f6f8 has been passed to repository cocoMDS2 as the guid parameter of the getEntityDetail operation but only an entity proxy has been found",
    "exceptionSystemAction": "The system is unable to return all of the details of the entity.  It can only supply an entity summary.",
    "exceptionUserAction": "The fact that the system has a proxy means that the entity exists in one of the members of the connected cohorts.  The repository where it is located may be unavailable, or the entity has been deleted but the delete request has not propagated through to this repository."
}
 
The entity includes its type definition and the properties of the asset. Also notice the metadata collection id for cocoMDS1 around the middle of the structure.
```

These errors are specific to running through the notebook quickly... 
If a small pause (a few seconds is sufficient) then the notebook runs successfully.

* Need to understand the reason (sync vs async)
* May need to add protection in notebooks (sleep)if expected [at some point we may want to run automated for validation, and in any case should be robust for users]

**Comment by planetf1** [comment]
This was not seen locally... most likely due to slightly different timing.

**Comment by mandy-chessell** [comment]
It definately needs investigating - there should be no timing issue - I think there is a bug in the enterprise connector in that it is not properly combining the classification results.

**Comment by planetf1** [comment]
Note: #3005 references above looks very similar ... When investigating/testing we should remember to check the observation there also.

**Comment by planetf1** [comment]
I had the same issue today on understanding an asset where
```
assetConsumerSearchForAssets(cocoMDS3Name, cocoMDS3PlatformName, cocoMDS3PlatformURL, calliesUserId, ".*Patient.*")
```
returned a guid, but 
```
printAssetUniverse(cocoMDS3Name, cocoMDS3PlatformName, cocoMDS3PlatformURL, calliesUserId, assetGUID)
```
failed to find the asset

Then rerun about 5s later it was fine.

**Comment by planetf1** [comment]
Here's a current example, found when testing 2.6 -- 

Ok until step 8 which fails with

Current assets defined: 
No assets found

Comments then fail with:
No comment added
OMAG-REPOSITORY-HANDLER-404-007 The Referenceable entity with unique identifier a04b6dfa-bfb2-4357-8eca-3b68cd272199 is not found for method addCommentToAsset of access service Asset Consumer OMAS in open metadata server cocoMDS2, error message was: OMRS-REPOSITORY-404-002 The entity identified with guid a04b6dfa-bfb2-4357-8eca-3b68cd272199 passed on the getEntityDetail call is not known to the open metadata repository cocoMDS5
 * The system is unable to update information associated with the entity because none of the connected open metadata repositories recognize the entity's unique identifier.
 * The unique identifier of the entity is supplied by the caller.  Verify that the caller's logic is correct, and that there are no errors being reported by the open metadata repository. Once all errors have been resolved, retry the request.
 
Which then causes a type error at which point the notebook aborts

ie:
<img width="1032" alt="Screenshot 2021-02-01 at 17 39 59" src="https://user-images.githubusercontent.com/7292002/106496687-16d75100-64b5-11eb-847d-02e60d2310b5.png">
<img width="1042" alt="Screenshot 2021-02-01 at 17 40 21" src="https://user-images.githubusercontent.com/7292002/106496693-18087e00-64b5-11eb-85ee-ae2576702758.png">
<img width="1020" alt="Screenshot 2021-02-01 at 17 40 47" src="https://user-images.githubusercontent.com/7292002/106496697-1939ab00-64b5-11eb-9a23-f286f726b0ed.png">

**Comment by planetf1** [comment]
This isn't a regression per, se (and most users would run carefully/more slowly) so I suggest ok to go with 2.6 in this area

**Comment by mandy-chessell** [comment]
Are the servers running already, before the notebook starts, or are they started as part of the notebook?

**Comment by planetf1** [comment]
Clean environment. no config Run through config notebook, then server notebook first, allow it to complete (but only on the notebook output - not checking for idle in terms of cohort events). Then run straight through (run all) the data catalog notebook.

I don't expect a regular user would do this but it suggests we might have timing windows we don't explain or understand

**Comment by mandy-chessell** [comment]
Just updated my original comment - sounds like my suspicion is a possibility - will look into it further

**Comment by planetf1** [comment]
That sounds plausible. Unscientific sample of two. 
 a) Wait until all activity has calmed down - notebooks work fine
 b) Run in full as soon as start notebook completes  - issues as documented
 
 Good issue to find

**Comment by planetf1** [comment]
Can confirm this is still occuring in the 2.8 release

**Comment by planetf1** [comment]
this also affects other notebooks like 'understanding an asset'
