### ISSUE TITLE
Add favourite projects API to community profile OMAS 

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#2689]
similar to favourite assets, it would be useful to have a  favourite projects API in the community profile OMAS. These favourite projects could be used for a glossary author to pick between when beginning working with the glossary authoring UI.

**Comment by mandy-chessell** [comment]
Still needed

**Comment by mandy-chessell** [comment]
This is available in the Community Profile OMAS MyFavouriteCollections interface.
