### ISSUE TITLE
Update docs/defaults on port 8080 usage - zookeeper uses by default at 3.5+I

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#2690]
In zookeeper 3.5.0 and above, an admin server is deployed by default on port 8080.
This is, for example, installed by homebrew on MacOS

The docs state:
```
The AdminServer
New in 3.5.0: The AdminServer is an embedded Jetty server that provides an HTTP interface to the four letter word commands. By default, the server is started on port 8080, and commands are issued by going to the URL "/commands/[command name]", e.g., http://localhost:8080/commands/stat. The command response is returned as JSON. Unlike the original protocol, commands are not restricted to four-letter names, and commands can have multiple names; for instance, "stmk" can also be referred to as "set_trace_mask". To view a list of all available commands, point a browser to the URL /commands (e.g., http://localhost:8080/commands). See the AdminServer configuration options for how to change the port and URLs.

The AdminServer is enabled by default, but can be disabled by either:

Setting the zookeeper.admin.enableServer system property to false.
Removing Jetty from the classpath. (This option is useful if you would like to override ZooKeeper's jetty dependency.)
Note that the TCP four letter word interface is still available if the AdminServer is disabled.
```

See more at https://zookeeper.apache.org/doc/r3.5.7/zookeeperAdmin.html

The IMPACT of this is that if the user follows instructions for running tutorials locally, or indeed just launches egeria with defaults, the server will fail due to a port clash.

At a minimum the docs should be updated to remind the user that zookeeper may be a common cause. We should probably also consider whether to keep the default coco pharma environment to using 8080. Or an easier option may be to recommend zookeeper admin server is disabled or moved to another port

The problem is most acute in a standalone developer environment where kafka, zookeeper, egeria are likely colocated. It's not an issue in containers, nor if, for example, kafka is remote.

**Comment by planetf1** [comment]
For example to keep the function enabled one could use:
```
adminPort=9990
zookeeper.admin.enableServer=true
```
( /usr/local/etc/zookeeper/zoo.cfg on MacOS homebrew )

**Comment by grahamwallis** [comment]
Should we consider registering an 'egeria' port with IANA?

**Comment by mandy-chessell** [comment]
Well caught @planetf1

**Comment by planetf1** [comment]
Thankfully ( #2519 ) we now at least allow the error message to explain the clash (in general terms, not specific to zookeeper)

My inclination is to leave the ports as-is, and to just update the docs for 'running locally' .
