### ISSUE TITLE
Improve java client packaging

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#2691]
Currently java clients are placed into our egeria-omag assembly in a 'clients' directory.

However the jars are not really useful as they stand, since they do not include any required dependencies - nor, as an alternative, do we list what jars need to be present to use.

We expect other products building in egeria capability will consume our maven artifacts - in which case the maven dependency mechanisms will bring the appropriate artifacts into their project - and they can choose whether to build a combined jar, copy dependencies etc.

Opening to make a decision on the way forward and take necessary actions
cc: 

Output from client directory in generated assembly:
```
➜  target git:(egeria-release-1.5) ✗ ls
archive-tmp                              egeria-1.5-distribution.tar.gz           maven-archiver
classes                                  egeria-1.5-omag-server                   open-metadata-assemblies-1.5-sources.jar
egeria-1.5-deploy                        egeria-1.5-omag-server.tar.gz            open-metadata-assemblies-1.5.jar
egeria-1.5-deploy.tar.gz                 egeria-1.5-sources.tar.gz                rat.txt
egeria-1.5-distribution                  javadoc-bundle-options
➜  target git:(egeria-release-1.5) ✗ cd egeria-1.5-distribution
ls
➜  egeria-1.5-distribution git:(egeria-release-1.5) ✗ ls
egeria-omag-1.5
➜  egeria-1.5-distribution git:(egeria-release-1.5) ✗ cd egeria-omag-1.5
ls
➜  egeria-omag-1.5 git:(egeria-release-1.5) ✗ ls
LICENSE           clients           samples           user-interface
NOTICE            conformance-suite server            utilities
➜  egeria-omag-1.5 git:(egeria-release-1.5) ✗ ls -la clients
total 528
drwxr-xr-x  24 jonesn  staff    768  2 Mar 11:11 .
drwxr-xr-x  10 jonesn  staff    320  2 Mar 11:11 ..
-rwxr-xr-x   1 jonesn  staff    989 27 Feb 22:16 README.md
-rwxr-xr-x   1 jonesn  staff  33773  2 Mar 11:09 admin-services-client-1.5.jar
-rwxr-xr-x   1 jonesn  staff   6685  2 Mar 11:02 asset-catalog-client-1.5.jar
-rwxr-xr-x   1 jonesn  staff  11273  2 Mar 11:02 asset-consumer-client-1.5.jar
-rwxr-xr-x   1 jonesn  staff  23517  2 Mar 11:03 asset-owner-client-1.5.jar
-rwxr-xr-x   1 jonesn  staff  12062  2 Mar 11:03 community-profile-client-1.5.jar
-rwxr-xr-x   1 jonesn  staff   7057  2 Mar 11:07 data-engine-client-1.5.jar
-rwxr-xr-x   1 jonesn  staff   5839  2 Mar 10:59 data-platform-client-1.5.jar
-rwxr-xr-x   1 jonesn  staff   1695  2 Mar 11:07 data-privacy-client-1.5.jar
-rwxr-xr-x   1 jonesn  staff   1693  2 Mar 11:04 data-science-client-1.5.jar
-rwxr-xr-x   1 jonesn  staff   1656  2 Mar 11:04 dev-ops-client-1.5.jar
-rwxr-xr-x   1 jonesn  staff   1754  2 Mar 11:04 digital-architecture-client-1.5.jar
-rwxr-xr-x   1 jonesn  staff  22344  2 Mar 11:05 discovery-engine-client-1.5.jar
-rwxr-xr-x   1 jonesn  staff   6218  2 Mar 11:05 governance-engine-client-1.5.jar
-rwxr-xr-x   1 jonesn  staff  13714  2 Mar 11:05 governance-program-client-1.5.jar
-rwxr-xr-x   1 jonesn  staff   1723  2 Mar 11:05 information-view-client-1.5.jar
-rwxr-xr-x   1 jonesn  staff   1729  2 Mar 11:06 it-infrastructure-client-1.5.jar
-rwxr-xr-x   1 jonesn  staff   1733  2 Mar 11:06 project-management-client-1.5.jar
-rwxr-xr-x   1 jonesn  staff   1732  2 Mar 11:06 security-officer-client-1.5.jar
-rwxr-xr-x   1 jonesn  staff   1734  2 Mar 11:06 software-developer-client-1.5.jar
-rwxr-xr-x   1 jonesn  staff   2799  2 Mar 11:06 stewardship-action-client-1.5.jar
-rwxr-xr-x   1 jonesn  staff  64263  2 Mar 11:07 subject-area-client-1.5.jar
➜  egeria-omag-1.5 git:(egeria-release-1.5) ✗
```

Originally discussed in https://github.com/odpi/egeria/issues/284

**Comment by mandy-chessell** [comment]
Agree - we should show how to use the clients via maven central and simlar repositories.

**Comment by planetf1** [comment]
Suggest we use #1643 to persue improving the code samples - which will be examples of using the clients, and in this issue I can make the change to remove the clients

**Comment by planetf1** [comment]
cc: @moh-bluemetrix

**Comment by planetf1** [comment]
The simple way to do this is to modify each pom within a -client project to create the jar with dependencies. This would need to be explicit in the pom, as profile activation (which could use a top level defined build profile) cannot be based on a wildcarded value (like artifact ends in -client) or derived property. Duplication but manageable. We already do this in some areas. Easy/well trodden path.

HOWEVER following this approach results in us building two jars for each maven artifact. One with dependencies, and one without.

If we consider how the jars are being used
 - Standalone, where making it easier to pull required dependencies makes it easier to deploy
 - maven, where we want to the build process to pull in the minimum possible & not have duplications esp in classpath.

We already have some maven artifacts containing jars with dependencies. There's the obvious ones like the server chassis, but also some utilities. This is probably not useful for maven reuse from maven central, and could be undesirable

Instead it would make sense to either (or both!)
 a) Build a modified jar-with-dependencies and add into our assemblies only 
 b) Lay out a directory structure in the assembly containing the relevant dependencies (many) alongside our jars with - though this may need classpath updates in the jars that we might want to launch directly.

This way the maven artifacts remain lean/minimal, but we also make it easier to run the clients.

I will experiment with a & b to figure out what approaches work and how usable they may be, taking a slightly broader look at how we properly package for different consumers

**Comment by planetf1** [comment]
See #3101 which has changed our connectors to pull in dependencies.

**Comment by planetf1** [comment]
So far, any 'applications' (ie with a main) such as FVTs, utilties & samples are setup so that they are packaged together with dependencies. This is present both in the maven artifact and distribution. This seems to work well.

Recently in #3101 we have extended this to connectors - this leads to some duplications, but only in terms of what is placed on-disk - at least long term. Short term since we have maven artifacts dependent on these connectors, those components that include them will bloat. However Once we lose static dependencies this should revert to normal.

Clients are expected to be bound statically by either egeria or 3rd party apps. Where this is done with maven we get the right dependencies without problem.

If we bloat the clients by including full dependencies, every piece of egeria code that includes those dependencies will suddenly grow significantly, and many artifacts could double in size.

This seems undesirable

I think that the approach of making each jar independent isn't scalable to this area. Instead we need to pick apart the dependencies and populate a common lib tree during assembly. That will need to be a complete set of everything that may be needed
