### ISSUE TITLE
add recent projects to community profile

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#2705]
similar to #2689
Extend PersonalProfile to that it contains the recent projects. I was thinking that for the Ui is would be probably only useful to have the last few projects (5 or 10) to choose between. So rather than implementing as a relationships (and being able to page), I was thinking of implementing as a new array attribute in the personalProfile. If there was something in the list that has been deleted, we validate on access. 

I am thinking of having new APIs similar to the my-assets APIs in the community profile. recent-projects (though without paging). The contents could be returned in a ProjectListResponse similar to AssetListResponse.

I was thinking that the GlossaryAuthorView could make a addToRecentProjects call when a project has been set as the one that is being worked on.

**Comment by davidradl** [comment]
I was thinking of 3 implementation options:
1) Implement the connection between community profile and its recent projects in relationships. 
2) Implement as a new array attribute in the personal profile. with a limited size 
3) Issue queries and use the updated by / created by and time fields in the entity to determine you last updated / created the entry. I do not think this would be very performant and would not pickup that a user had looked at a project.

I am favouring option 2).

**Comment by mandy-chessell** [comment]
What is the definition of a "recent project"?
The suggested implementation - assuming it is decribing changes to the CP OMAS API?

**Comment by mandy-chessell** [comment]
This needs to be sync-ed with the CRUD methods in ProjectManagementOMAS

**Comment by davidradl** [comment]
@mandy-chessell I was thinking that from the glossary authoring point of view I would want to have the last 5 projects that had been used by a particular user displayed in the UI. So the options I am seeing are :
1) Implement connection between community profile and its recent projects in relationships.
2) Implement as a new array attribute in the personal profile. with a limited size. 
3) Issue queries and use the updated by / created by and time fields in the entity to determine you last updated / created the entry. I do not think this would be very performant and would not pickup that a user had looked at a project.
4) Have a relationship from the Community profile to a RecentProjects object that has 2 properties  a list of recent projects and maximum size of the list. In this way we can decouple the community profile from the RecentProjects.The OMAS would be policing 1 - 1 and composition. and the list limit.     
5) I wonder whether a more generic ProfilePreferences Type might be worth adding and a relationship to the Community profile. The Profile preferences could hold the recent projects and the favourite projects. Consider moving the favourite assets from community profile, so that external community profiles would come in more cleanly.
6) A more general version of 5 might be to allow Project preferences to include Type as well as, recents , favourites and allow more than one Project preferences per community profile. For glossary authors ,Glossary and Project entities would be used. For other OMAS other recents and favourites might be useful (e.g. policy for security policy authors).    
       
Given we cannot have 2), and 1) may need mechanisms to clean up older recent projects. 5) could mean we add many versions of this for different types. I suggest 5) or 6)

**Comment by mandy-chessell** [comment]
Still needed
