### ISSUE TITLE
Create integration with the Aristotle metadata registry

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#2724]
Aristotle is a metadata registry based on the [open ISO/IEC 11179 metadata standard](http://metadata-standards.org/11179/) available both as open source software and in a hosted cloud offering.  It appears to be used primarily in the realm of government, non-profits and academia.

It _appears_ that the metadata managed is largely around descriptions of data elements (further analysis needed), so this issue is to consider the best means of integrating with the registry: eg. through a means such as the Subject Area OMAS or a repository proxy.

More information:

- https://www.aristotlemetadata.com

**Comment by mandy-chessell** [comment]
May be more related to design model omas if they are design element or asset owner if related to real data sources?  Only be subject area if curated by subject area expert.

**Comment by planetf1** [comment]
It looks as if their links to github from their website are all dead.
The org appears to be at https://github.com/search?q=aristotle-mdr and whilst there's some repos around there's little activity

The code is available - python - at https://pypi.org/project/aristotle-metadata-registry/ but not seen any sign of an open repo.

That being said always good to consider open and closed options, engage with new communities, share ideas.
