### ISSUE TITLE
Mismatch between schemaAttribute bean definition of cardinality and open metadata type

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#2726]
The Asset Ownwer OMAS method to add a CSV file is not working.  It is expecting to set a cardinality of string - eg 1..* etc - and the open metadata types have two integer values for min and max cardinality.

I am not sure how the min and max values for cardinality work because so many types are of unlimited size.  This is why the OCF (and hence Asset Owner OMAS and Asset Consumer OMAS) uses a string.

The result is an error when the CSV file is created.
![image (2)](https://user-images.githubusercontent.com/12354195/76334180-9632c380-62ea-11ea-9368-bb67f59c272b.png)

We need to add a string form of cardinality to the open metadata types to support the OCF.  If the integer versions are used, the OCF metadata management module can turn it into a string.

**Should I also deprecate the min and max integers for cardinality or should I leave them as an optional format?**

I will leave as an option, with the OCF supporting both approaches unless anyone has strong objections.

**Comment by cmgrote** [comment]
The change to the open metadata types was covered in PR #1545 as part of simplification that we covered under issue #1317 -- we discussed the details at our face-to-face workshop in Huizen (https://github.com/odpi/egeria/wiki/Egeria-Meeting-1st,-2nd-October-2019-@-Huizen,-Netherlands#2nd-october-2019).

(The updated documentation on the types was merged as part of #1545: eg. https://egeria.odpi.org/open-metadata-publication/website/open-metadata-types/0505-Schema-Attributes.html)

I don't see any mention of the OCF use of this as part of those, though, so perhaps we missed that dependency at that point (?)

**Comment by grahamwallis** [comment]
There is another alternative - which would be to retain the two values but make them strings (not integers), then you could have a 'max' value like '*'.

IMHO it would be nice to have one way of handling cardinality.

**Comment by cmgrote** [comment]
We did discuss this and from what's documented (and merged, post-approval -- see #1545) it seems we agreed that `-1` would represent the `*` value numerically.

**Comment by mandy-chessell** [comment]
Agreed - been doing more research into the history of this and I think we can leave the open metadata types as they are defined and extend the schema attribute bean to support the string and the int versions so the values can be displayed and stored in a way that they can be processed

**Comment by mandy-chessell** [comment]
Digging further, I see that bounded schema type has also been deprecated and replaced with flags in the schema attribute.  Supporting schemas using this new pattern impacts 2 released OMASs:

* Asset Consumer OMAS - retrieves schemas
* Asset Owner OMAS - creates schemas

Updating Asset Owner OMAS is easy:
* Change the creation of a schema type so if a new BoundedSchemaType is attached to a Schema Attribute, the request can be turned into an update to the Schema Attribute entity in the repository.
* Extend existing API to allow the new bounded schema concepts to be set directly in the
Schema Attribute.

For Asset Consumer OMAS, I think it has to expose both the old and the new pattern for
bounded schema and follow the way that the schema is stored to determine how the schema is returned.  This is so that existing schemas can continue to be retrieved using existing
code and new schemas that adopt the new style, benefiting from the faster processing.

The downside of this approach is that an existing user of Asset Consumer OMAS (and although we do not know of any, there may be) would need to be updated to process the new types of schema.

If it turns out that there are users of Asset Consumer OMAS that can not be changed, we can add an option to Asset Consumer OMAS to always use the old style for all schemas.  However I do not propose to implement this until we get a complaint.  So if this is required now please comment.

**Comment by mandy-chessell** [comment]
Updates to OCF Beans:
* Deprecate BoundedSchemaType and BoundedSchemaCategory
* Add DataItemSortOrder enum
* Add SchemaAttributeCategory enum supporting UNKNOWN, ARRAY, SET, BAG, SINGLETON
* Add new SchemaType beans - EnumSchemaType, LiteralSchemaType, SimpleSchemaType, SchemaTypeChoice
* Extend SchemaTypeBean with linkName and linkProperties if the type is external to the schema.

When the schemaType bean is manufactured from the `TypeEmbeddedAttribute` classification, it has the GUID of the schemaAttribute's entity.  The schemaTypeHandler in OCF Metadata Handlers needs to retrieve entities of type "SchemaElement" when retrieving SchemaTypes.

The OCF read-only wrappers that are used for the connected asset properties of an OCF connector also need extending with: AsetEnumSchemaType, AssetLiteralSchemaType, AssetSimpleSchemaType and AssetSchemaTypeChoice.

Changes to open metadata types:
* Extend `TypeEmbeddedAttribute` classification with the following properties:
   * schemaTypeName - string name of schema type to allow enums and literals to use the embedded form.
   * Missing properties from SchemaType
       * versionNumber
       * usage
       * author
       * namespace
   These values are optional and their default value comes from parent schema type.
   * Missing property from PrimitiveSchemaType
       * defaultValue
   * Missing property from EnumSchemaType
       * fixedValue

**Comment by mandy-chessell** [comment]
Other changes - re-add cardinality property to SchemaAttribute but mark as "deprecated" (this was not possible when the original simplification work was done).

Extend Asset Owner OMAS to provide specialist support for different types of schema so that the mapping is encoded rather than having to be learned by developers.

**Comment by planetf1** [comment]
This seems complete so closing
