### ISSUE TITLE
Create feature branch for open lineage

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#2730]
Work to create some features requires part of the Egeria team to collaborate closely to develop and test capability. It's necessary to do this away from the 'master' branch both to prevent destabilizing master, but also to provide control over when changes in master are incorporated into that development stream of work

The proposal here is to make use of a 'feature branch' to manage this work. 
This approach is also open to other features with similar requirements, and where an individual working on his/her fork and issuing a PR - still the favoured approach - is not sufficient

Changes will be merged back into master prior to cutting a branch and releasing

- [x] Feature developer - Add docs on how a developer works with code changes, PRs on their feature branch
- [x] Feature integrator - add docs on rolling changes from feature branch into master
- [x] Admin - add feature branch setup/configuration for repo owner (inc naming convention)
- [x] Release process - refer to feature branch integration prior to cutting branch
- [x] Feature PR build - setup/validate PR builds for process via a dummy feature
- [ ] Create feature branch for OLS
- [x] Setup PR builds for feature branch
- WILL NOT BE DONE -> ( ) Setup merge build for feature branch

Exclusions - These may be added later but are not currently required by the OLS team
 * Artifacts will not be published to artifactory
 * Docker images will not be built and published

Primarily this is because a) they aren't needed currently and b) Our naming strategy for repositories do not take account of the branch name.

**Comment by planetf1** [comment]
See https://github.com/odpi/egeria/pull/2764 for docs on feature branch

@mstrelchuk @mandy-chessell I = propose we create the 'egeria-feature-openlineage'  branch from master next week (Tue?). I need to check you are happy with the process and the name. It would be good if open lineage merges were quiesced prior to creating the branch. 

I will next validate the PR process with a dummy feature

**Comment by planetf1** [comment]
PR #2765 created for allowing builds to run on features - this needs merging before I can test the process with a dummy feature

**Comment by planetf1** [comment]
Added branch protection rules - same as master - for egeria-feature-*
Basically this enforces PRs and the PR build
Kept seperate from master in case we need to adapt independently

**Comment by planetf1** [comment]
Now testing PR process in https://github.com/odpi/egeria/pull/2766

**Comment by planetf1** [comment]
Feature build working fine. Just awaiting agreement for the right time to make the branch.

**Comment by planetf1** [comment]
@DimitriosMaimaris @mstrelchuk @bogdan-sava Hopefully we can discuss tomorrow 24 Mar - please consider when is an appropriate time for me to make the branch.

**Comment by planetf1** [comment]
With the 1.6 branch planned for Thu 26 Mar it may be an opportune time to also create the ols branch.

**Comment by lpalashevski** [comment]
Starting the feature branch with the release 1.6 makes perfect sense, let's do one last verification on the Thursday call. Thank you for setting this up Nigel.

**Comment by planetf1** [comment]
Release 1.6 was branched and master updated to 1.7-SNAPSHOT in https://github.com/odpi/egeria/pull/2822

This will form the starting point for the lineage release

**Comment by planetf1** [comment]
The branch `egeria-feature-openlineage` is now created
@mstrelchuk @lpalashevski @DimitriosMaimaris This release is now over to you to work with, update master & vice versa as per your needs
