### ISSUE TITLE
Add history to cohort registry

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#2741]
The cohort registry manages information about the active members of the cohort.  It would be useful to extend this to maintain a history of the membership so that it is possible to look up the originator of any metadata found in the repository.

Should we also add details of open metadata archives loaded too?  This way we have a complete record of the "home repositories" of all metadata types and instances.

(Do nto need to include external instances because have "replicatedBy" value to tie it back to owning open metadata repository.

**Comment by planetf1** [comment]
It would be useful to know cohort 'members' that have no repository - ie cocoMDS4 for coco pharma. This aids in understanding all the collaborators in the cohort. Even though these servers do not participate in federated queries & updates, they do host services ie OMAS etc.

**Comment by mandy-chessell** [comment]
Still need this

**Comment by mandy-chessell** [comment]
I am closing this since the DEREGISTERED_REPOSITORY support was enabled without this capability.
