### ISSUE TITLE
RepositoryContentValidator not checking specific primitive type 

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#2756]
The RepostioryContentValidator's validatePropertiesForType method checks that the supplied primitive instance property has the correct instance property category, but does not check that the PrimitiveDefCategory matches the actual type defined by the attribute.

**Comment by mandy-chessell** [comment]
I think Graham has fixed this because it lead to problems in Asset Owner because the primitve type was strign rather than char.

**Comment by grahamwallis** [comment]
@mandy-chessell Agreed - for some reason I must have raised two issues for this - it was also raised in #2843 and fixed by #2846. I think I must have chosen to fix the more entertaining of the two issues :-)
