### ISSUE TITLE
Review CII Best Practices badge

### ISSUE THREAD

**Issue by jmertic** [odpi/egeria#277]
https://bestpractices.coreinfrastructure.org/en

Achieving a badge is one of the requests the ODPi TSC has for Active stage projects. Egeria technically was grandfathered in before this requirement, but it would a great show to the community if this badge was achieved. Happy to discuss with the community and help in any way that I can.

**Comment by mandy-chessell** [comment]
Hello John, ww have been working our way through the requirements but are stuck on finding a security person to join the team.

**Comment by jmertic** [comment]
That's great to hear Mandy!

Perhaps could you start submitting Egeria - even though there is work to do - at the site above with the progress thus far? It helps give downstream users confidence that the project is taking all of those items seriously. Happy to help in any way I can.

**Comment by jmertic** [comment]
Any progress here?

**Comment by cmgrote** [comment]
Closing this singular issue now that we have a dedicated project (https://github.com/odpi/egeria/projects/18) listing all of the individual items that we still need to address as separate issues (for more granular tracking).
