### ISSUE TITLE
Debug info or rogue dialogue on type explorer

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#2781]
When running type explorer in the docker compose environment, I receive a popup

type-manager cpt: serverName and serverURLRoot fields are cocoMDS1 http://datalake:8080

These are correct - perhaps useful - but look like a rogue debug message left behind?

<img width="1614" alt="Screenshot 2020-03-23 at 15 58 37" src="https://user-images.githubusercontent.com/7292002/77336361-4fe45800-6d1f-11ea-8034-7a4d57d44dda.png">

**Comment by grahamwallis** [comment]
Hi @planetf1  - this wasn't really a debug message - it was a rather poor mechanism for confirmation to the user that the server details had been set correctly. It does need to go, and should e done as part of a wider reaching overhaul of Tex to make it look more like its younger brother Rex. 

Thanks for raising the issue.
