### ISSUE TITLE
Egeria compilation failure if JAVA_HOME is missing in the env

### ISSUE THREAD

**Issue by fpompermaier** [odpi/egeria#2795]
if the JAVA_HOME env variable is not set the compilation of ALF fails because of the javadoc maven plugin. The error given is the following:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.1:jar (attach-javadocs) on project audit-log-framework: MavenReportException: Error while generating Javadoc: Unable to find javadoc command: The environment variable JAVA_HOME is not correctly set. `

As stated by https://stackoverflow.com/questions/13961615/unable-to-find-javadoc-command-maven it is sufficient to add the following configuration to the plugin:

```
<plugin>
        <groupId>org.apache.maven.plugins</groupId>
         <artifactId>maven-javadoc-plugin</artifactId>
         <version>3.0.1</version>
          <configuration>
               <javadocExecutable>${java.home}/bin/javadoc</javadocExecutable>
          </configuration>
</plugin>
```

**Comment by fpompermaier** [comment]
This does not seem to work on JDK < 1.9 because javadoc is not under jre/bin (see https://issues.apache.org/jira/browse/MJAVADOC-595)

**Comment by planetf1** [comment]
We came across this in #1500. Unfortunately I did try this fix, and we found one issue was that it sets the path to javadoc in relation to the java install executing maven, which in some cases isn't a JDK - but could be a JRE. And in that case there is no javadoc executable.

That being said it's good to revisit - so will suggest looking at this again - should probably hold off any merge for the moment

Ah! I just saw your post - exactly what I was going to say!

**Comment by planetf1** [comment]
This was the PR that updated the dev docs 2316 but clearly if we can find an approach within maven that can cover java 8,11 & beyond, use of jre or jdk, and works cross-platform, which still ensuring javadoc is always built (for validation) then that's great :-)

Changing the build env and removing from the normal mvn clean install is tempting, but means developers won't see javadoc warnings, which tends to mean issues - even warnings - don't ever get addressed....

**Comment by planetf1** [comment]
May be possible to add a plugin that could check JAVA_HOME is set, and if not produce a clearer, quicker message ..?

**Comment by fpompermaier** [comment]
I think the only way to deal with this here is to use maven profiles with activation rules that tries to guess where the javadoc executable is. If the user is using a jre to compile we can disactivate the javadoc plugin

**Comment by planetf1** [comment]
A few thoughts
 * I think as a project we've agreed javadoc will get run by default
 * A developer may skip javadoc generation if they wish - `-Dmaven.javadoc.skip=true`
 * We can activate optional profiles by java version -- but I don't think this completely addresses the issue
 * Guessing the path is likely very problematic given the range of environments and platforms being used
 * JAVA_HOME *apparently* gets used by other java plugins, so we may see other issues beyond javadoc - though I've not verified this
 * maven enforcer may be a tool to at least CHECK the user's config - and would give the ability to give a much clearer error message if their setup is wrong. ie see https://maven.apache.org/enforcer/enforcer-rules/requireFilesExist.html . We already use this in our build - but not for this test.
 * We could enforce a check for using either $JAVA_HOME or java.home.
 * We *may* need to investigate the build system config (some are in .azure-pipelines, others are on azure pipelines itself not under SCM ('release' pipelines cannot be) - and more importantly consider the impact to anyone where these tests currently pass.
 * Therefore validating against the current use of $JAVA_HOME may be safest - no change of behaviour, just making it MUCH CLEARER what the user got wrong and how to fix?
 * OS should include Windows, Windows WSL2, Linux x86_64, Linux arm64, macOS at a min
 * Java should include 8,11,14 . Hotspot+j9 (unlikely diff)
 * maven be launched with JRE or JDK
 * JAVA_HOME may be set to JRE or JDK

It would be superb to get a fix to this - but the above reflects the challenge leading to me initially just documenting :-(

**Comment by fpompermaier** [comment]
Ok..I think that documenting this in the build from sources would be enough for the moment..you could close the ticket if you want

**Comment by planetf1** [comment]
Thanks for looking. If you do find a solution that works better, or see improvements for the docs please feel free to re-open. for now I will close.
