### ISSUE TITLE
About graph connections

### ISSUE THREAD

**Issue by immmus** [odpi/egeria#2811]
Hi all!

Studying the source code of the project came across several janusgraph factories.
Namely:
"org.odpi.openmetadata.openconnectors.governancedaemonconnectors.openlineageconnectors.janusconnector.factory.GraphFactory"
and
"org.odpi.openmetadata.adapters.repositoryservices.graphrepository.repositoryconnector.GraphOMRSGraphFactory"

And I had questions about different configuration approaches.
If with GraphOMRSGraphFactory everything is extremely clear. We just pass the standard settings from the janusgraph documentation during the initial server setup (http://localhost/open-metadata/admin-services/users/{userId}/servers/test/local-repository/mode/local-graph- repository)
_{
	"storage.backend" : "cassandra",
	"storage.username" : "user",
	"storage.password" : "pass",
	"storage.hostname" : "123, 123",
	"index.search.backend" : "elastic",
	"index.search.hostname" : "123"
}_

That is not so obvious with GraphFactory.  It’s not clear where exactly the configuration settings are set.

And if in the case of GraphOMRSGraphFactory, we just set the settings in the janusgraph documentation style. And in the code is initialization through key -> value in "open" method: 
```
        JanusGraphFactory.Builder build = JanusGraphFactory.build();
        storageProperties.forEach((k, v) -> build.set(k, v));
```

GraphFactory uses a different configuration style, in this case camelcase aliases are used:
It is not clear where "storage.hostname" is passed to "ConnectionProperties" as a List, and why not default it as a comma-separated string?)

```
  private JanusGraphFactory.Builder janusFactoryCassandra(ConnectionProperties connectionProperties){

        String listString = String.join(",", (ArrayList) connectionProperties.getConfigurationProperties().get("storageHostname"));

        return JanusGraphFactory.build().
                set("storage.backend",connectionProperties.getConfigurationProperties().get("storageBackend")).
                set("storage.username",connectionProperties.getConfigurationProperties().get("username")).
                set("storage.password",connectionProperties.getConfigurationProperties().get("password")).
                set("storage.hostname", listString).
                set("storage.cql.cluster-name",connectionProperties.getConfigurationProperties().get("clusterName")).
                set("storage.cql.keyspace",connectionProperties.getConfigurationProperties().get("storageCqlKeyspace")).
                set("index.search.backend",connectionProperties.getConfigurationProperties().get("indexSearchBackend")).
                set("index.search.hostname",connectionProperties.getConfigurationProperties().get("indexSearchHostname"));
    }
```

It seems to me that different configuration approaches can confuse the end user.  
I would also like to understand where the configuration is made for GraphFactory to work with OpenLineage:)

I could make it clear that it’s not clear to you since I’m not a native speaker), so if something is not clear in my reasoning, be sure to ask questions)
Thx!)

**Comment by DimitriosMaimaris** [comment]
Hello,

Yes this will be the same for both factories it should be generic to support all configuration from janusgraph as it is in GraphOMRSFactory. There are some changes going on this matter and this is going to be a common code for both factories. Also there changes happening for configuring remotely to a Gremlin Server.

**Comment by grahamwallis** [comment]
Hi @immmus @DimitriosMaimaris @lcpopa - I liked the configuration updates that Liviu made to the GraphOMRSGraphFactory. My original only had Berkeley, Lucene and Liviu did a nice job of adding the ability to dynamically configure the backends (and any other k,v properties). Is it proposed that similar changes will be made to the OLS graph factory?

**Comment by immmus** [comment]
> Hello,
> 
> Yes this will be the same for both factories it should be generic to support all configuration from janusgraph as it is in GraphOMRSFactory. There are some changes going on this matter and this is going to be a common code for both factories. Also there changes happening for configuring remotely to a Gremlin Server.

Hi, thanks for the answer, but I want to see how to configure OLS, what other requests for this should be sent. For example, for the base of cassandra.

**Comment by DimitriosMaimaris** [comment]
> > Hello,
> > Yes this will be the same for both factories it should be generic to support all configuration from janusgraph as it is in GraphOMRSFactory. There are some changes going on this matter and this is going to be a common code for both factories. Also there changes happening for configuring remotely to a Gremlin Server.
> 
> Hi, thanks for the answer, but I want to see how to configure OLS, what rest requests for this should be sent. For example, for the base of cassandra.

So to clarify lineage is as technical preview at the moment is not yet developed entirely we are still making changes and enhance what is there. Also readme needs to be updated. If you want to configure OLS with a base Cassandra for now you. can do that: [OLS readme.](https://github.com/odpi/egeria/tree/master/open-metadata-implementation/governance-servers/open-lineage-services) 
Replace the configuration with the below
```

"configurationProperties":{ 
            "graphDB":"cassandra",
            "graphType":"bufferGraph",
            "storageBackend":"cql",
            "storageHostname": "ip1,ip2,ip3...", 
           "username": "cluster username",
           "password": "cluster pass",
           "clusterName":"cluster name",
           "storageCqlKeyspace":"keyspace name"
            "indexSearchBackend":"lucene"
 or for elastic   replace with 
     "indexSearchBackend":"elasticsearch",
     "indexSearchHostname":"hostname"
          }
```

you need to add this for both graphs buffer and main graph. I suggest to have two separate keyspaces for each one since the schemas are different. For this to work you need to add open-lineage-janus-connector jar with dependencies as an external dependency. 

For the api calls you can check the swagger as well. Ping me on slack if you need more clarifications.

**Comment by DimitriosMaimaris** [comment]
> Hi @immmus @DimitriosMaimaris @lcpopa - I liked the configuration updates that Liviu made to the GraphOMRSGraphFactory. My original only had Berkeley, Lucene and Liviu did a nice job of adding the ability to dynamically configure the backends (and any other k,v properties). Is it proposed that similar changes will be made to the OLS graph factory?

@grahamwallis Yes it will be the same there are changes going to happen there I will share them on a functionality  call.

**Comment by immmus** [comment]
> > > Здравствуйте, 
> > > Да, это будет одинаково для обеих фабрик, оно должно быть общим для поддержки всей конфигурации из janusgraph, как это делается в GraphOMRSFactory. В этом вопросе происходят некоторые изменения, и это будет общий код для обеих фабрик. Также происходят изменения для удаленной настройки сервера Gremlin.
> > 
> > 
> > Привет, спасибо за ответ, но я хочу посмотреть, как настроить OLS, какие остальные запросы на это должны быть отправлены. Например, для базы кассандры.
> 
> @immmus Итак, прояснить происхождение, так как технический предварительный просмотр на данный момент еще не разработан полностью, мы все еще вносим изменения и улучшаем то, что есть. Также readme необходимо обновить. Если вы хотите настроить OLS с базовой Cassandra на данный момент вам. можно сделать это: [OLS readme. ](https://github.com/odpi/egeria/tree/master/open-metadata-implementation/governance-servers/open-lineage-services)
> Замените конфигурацию следующим
> 
> ```
> 
> "configurationProperties":{ 
>             "graphDB":"cassandra",
>             "graphType":"bufferGraph",
>             "storageBackend":"cql",
>             "storageHostname": "ip1,ip2,ip3...", 
>            "username": "cluster username",
>            "password": "cluster pass",
>            "clusterName":"cluster name",
>            "storageCqlKeyspace":"keyspace name"
>             "indexSearchBackend":"lucene"
>  or for elastic   replace with 
>      "indexSearchBackend":"elasticsearch",
>      "indexSearchHostname":"hostname"
>           }
> ```
> 
> Вы должны добавить это как для буфера графиков, так и для основного графика. Я предлагаю иметь два отдельных пространства ключей для каждого, поскольку схемы разные. Чтобы это работало, вам нужно добавить jar open-lineage-janus-connector с зависимостями в качестве внешней зависимости.
> 
> Для вызовов API вы также можете проверить чванство. Звоните мне, если вам нужно больше разъяснений.

@DimitriosMaimaris Thank you very much. I really missed the readme.
