### ISSUE TITLE
Implement case-insensitive search helpers

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#2824]
- Add case-insensitive search helper methods to provide consistency in achieving case-sensitive (default) vs case-insensitive search.

We then need to ensure this functionality is implemented and handled in all the various repository connectors.

**Comment by grahamwallis** [comment]
I am currently wrestling with an issue with the JanusGraph implementation of case-insensitive search.

If I could implement this with the (?i) match flag - which is a Java 1.8 Pattern flag - then the user would have the ability to include or exclude the match flag from the regex. In fact, if they wanted they could even enable and disable case at different points in the regex, but that would be a luxury option that we probably don't need. However the (?i) match flag approach is not working in JanusGraph - I have raised a question to the user group and will report back if anyone there can help. 

To make case-insensitive work I mayd have to use the (ugly) approach of converting each alpha character in the regex to its upper and lower case pair, eg as follows:

asset  ==> [aA][sS][sS][eE][tT]

This approach seems to work with JG and its indexing backends (which all use the Lucene regex parser). I'm OK with this approach from an efficiency and ugliness point of view; we parse the regex in the connector anyway and no-one will see the expanded regex. However, I am concerned that if I automatically and always do this expansion, then the user will always get case-insensitive search. With this approach the user will not have any control., without augmenting our search API, so there would be no way to disable it.

**Comment by cmgrote** [comment]
I'm working on adding the following helper methods to those that already exist:

- `getXYZRegex(String, boolean)` - overloads the existing `getXYZRegex(String)` methods (which still behave as case-sensitive) to provide the option to get a case-insensitive string (when the provided boolean is `true`).  This will use the `(?i)` mechanism in Java to apply the case-insensitivity.
- `isXYZRegex(String, boolean)` - will similarly overload the existing `isXYZRegex(String)` methods to allow specifying whether to check for case-sensitivity (false) or not (true) in determining the truthiness of the result
- `isXYZRegex(String)` - will still exist, but will now return true regardless of whether the regex is case-sensitive or not (akin to calling the new 2-arg method with both a true and a false, and `||`'ing the results)
- `isCaseInsensitiveRegex(String)` - will indicate whether the provided regex is case-insensitive (true) or not, irrespective of what's actually in the regex (whether from one of the other helper methods, or a "pure" regex)
- `getUnqualifiedLiteralString(String)` - will still exist, but will now strip off the case-insensitive operator (if present) as well as any of the other regex-wrappings from the other helper methods

**Comment by grahamwallis** [comment]
Hi @cmgrote - yes I think that should work for the patterns generated by the helper methods. 

For a user composed regex with '(?i)' at the start it would be the same. i.e. the graph connector could detect that (using the helper method) and process the regex accordingly.

A user entering a 'custom' (non-helper) regex could insert multiple match flags throughout the regex. I could try to spot all occurrences and expand the regex only the places needed, but I'm worried that the parsing for that could become complex/unreliable.

**Comment by cmgrote** [comment]
> A user entering a 'custom' (non-helper) regex could insert multiple match flags throughout the regex. I could try to spot all occurrences and expand the regex only the places needed, but I'm worried that the parsing for that could become complex/unreliable.

Agreed, I have no intention of trying to support anything more complicated, and I'd be surprised if anything other than the in-memory repository is ever going to be able to do so reliably...  (I'm not even sure the Atlas connector is going to have any way to support case-insensitive, as I believe their searches are case-sensitive.)
