### ISSUE TITLE
Data Engine OMAS Functionality

### ISSUE THREAD

**Issue by moh-bluemetrix** [odpi/egeria#2825]
I have been working on Data Engine integration using the appropriate OMAS client. While the OMAS client does allow for all of the relevant entities such as Processes and Port Implementations to be created and linked, I have noted that two features in particular would be extremely useful under the Data Engine API endpoints:

1. Searching for Assets
A data engine must create lineage between assets. To do this, the engine must have access to the source and destination asset schemas, specifically the qualified names of columns. 
Currently, separate OMAS clients must be utilized to search for existing assets. The asset catalog OMAS client can be used to search for specific assets by certain criteria such as a qualified name. In the context of a Data Engine, it would be useful to perform a search based on qualified name and return an object where the schema and column qualified names can be easily extracted and used for lineage creation.

2. Creation of Missing Assets
In the event that a data engine can not find an asset, there should be the ability to create it based on the information the Engine has available. It is not sufficient to create Processes that are not linked to assets. Structured data such as database tables and files (CSV, JSON, AVRO) can be consumed and created by Data Engines so it would be beneficial to be able to create the associated assets for them if required.

Is the intention to keep these endpoints segregated in other OMAS clients such as Data Platform & Asset Catalog for modularity? I would think that inclusion of these endpoints under the Data Engine OMAS client is beneficial since any Data Engine should be able to perform the actions noted above via communication with Egeria only.

**Comment by mandy-chessell** [comment]
Each OMAS is designed to support all of the needs of a particular tool so these look like good suggestions for the Data Engine OMAS.
