### ISSUE TITLE
Asset Lineage exception

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#2836]
When I start a server and it receives a NewEntityEvent relating to a Process entity, the following exception is logged.

Wed Apr 01 16:35:40 BST 2020 Report_Server Exception OMAS-ASSET-LINEAGE-0005 An exception occurred while processing incoming event OMRSInstanceEvent{instanceEventType=OMRSInstanceEventType{ordinal=1, name='NewEntityEvent', description='A new entity has been created.'}, typeDefGUID='d8f33bd7-afa9-4a11-a8c7-07dcec83c050', typeDefName='Process', instanceGUID='c584ad29-b6ff-4b8a-8577-1a2a0d387204', originalEntity=null, entity=EntityDetail{type=InstanceType{typeDefName='Process', typeDefCategory=TypeDefCategory{typeCode=6, typeName='EntityDef', typeDescription='An object or concept of interest.'}, typeDefGUID='d8f33bd7-afa9-4a11-a8c7-07dcec83c050', typeDefVersion=1, typeDefDescription='Well-defined sequence of activities performed by people or software components.', typeDefDescriptionGUID='null', typeDefSuperTypes=[TypeDefLink{guid='896d14c2-7522-4f6c-8519-757711943fe6', name='Asset', status=TypeDefStatus{ordinal=1, name='ActiveTypeDef', description='TypeDef available and in use.  This is the default value equivalent to null'}, replacedByTypeGUID='null', replacedByTypeName='null'}, TypeDefLink{guid='a32316b8-dc8c-48c5-b12b-71c1b2a080bf', name='Referenceable', status=TypeDefStatus{ordinal=1, name='ActiveTypeDef', description='TypeDef available and in use.  This is the default value equivalent to null'}, replacedByTypeGUID='null', replacedByTypeName='null'}], validStatusList=null, validInstanceProperties=[qualifiedName, additionalProperties, name, description, owner, ownerType, zoneMembership, latestChange, displayName, formula]}, entityProperties=InstanceProperties{propertyNames=java.util.LinkedHashMap$LinkedKeyIterator@5cb8097c, propertyCount=3, instanceProperties={name=PrimitivePropertyValue{primitiveValue=process-1, primitiveDefCategory=PrimitiveDefCategory{code=11, name='string', javaClassName='java.lang.String', guid='b34a64b9-554a-42b1-8f8a-7d5c2339f9c4'}, instancePropertyCategory=InstancePropertyCategory{typeCode=1, typeName='Primitive', typeDescription='A primitive type.'}, typeGUID='null', typeName='null'}, qualifiedName=PrimitivePropertyValue{primitiveValue=process-qn001, primitiveDefCategory=PrimitiveDefCategory{code=11, name='string', javaClassName='java.lang.String', guid='b34a64b9-554a-42b1-8f8a-7d5c2339f9c4'}, instancePropertyCategory=InstancePropertyCategory{typeCode=1, typeName='Primitive', typeDescription='A primitive type.'}, typeGUID='null', typeName='null'}, displayName=PrimitivePropertyValue{primitiveValue=onboarding-process, primitiveDefCategory=PrimitiveDefCategory{code=11, name='string', javaClassName='java.lang.String', guid='b34a64b9-554a-42b1-8f8a-7d5c2339f9c4'}, instancePropertyCategory=InstancePropertyCategory{typeCode=1, typeName='Primitive', typeDescription='A primitive type.'}, typeGUID='null', typeName='null'}}}, classifications=null, instanceURL='null', GUID='c584ad29-b6ff-4b8a-8577-1a2a0d387204', instanceProvenanceType=InstanceProvenanceType{ordinal=1, name='Local to cohort', description='The instance is being maintained within one of the local cohort members. The metadata collection id is for one of the repositories in the cohort. This metadata collection id identifies the home repository for this element. '}, metadataCollectionId='fee38e97-4bf3-4732-85b4-96bc58a80272', metadataCollectionName='Schema_Server', instanceLicense='null', status=InstanceStatus{ordinal=1, name='Draft', description='The content is incomplete.'}, createdBy='garygeeke', updatedBy='null', createTime=Wed Apr 01 16:35:34 BST 2020, updateTime=null, version=1, statusOnDelete=null}, originalRelationship=null, relationship=null, instanceBatch=null, homeMetadataCollectionId='null', originalHomeMetadataCollectionId='null', originalTypeDefSummary=null, originalInstanceGUID='null', errorCode=OMRSInstanceEventErrorCode{ordinal=0, name='No Error', description='There has been no error detected and so the error code is not in use.', encoding=null}, eventTimestamp=Wed Apr 01 16:35:35 BST 2020, eventDirection=OMRSEventDirection{ordinal=1, name='Inbound Event ', description='Event from a remote member of the open metadata repository cluster.'}, eventCategory=OMRSEventCategory{ordinal=3, name='Instance Event', description='Event used to manage the replication of metadata instances within the metadata repository cohort'}, eventOriginator=OMRSEventOriginator{metadataCollectionId='fee38e97-4bf3-4732-85b4-96bc58a80272', serverName='Schema_Server', serverType='Metadata Repository Server', organizationName='null'}, genericErrorCode=null, errorMessage='null', targetMetadataCollectionId='null', targetRemoteConnection=null, targetTypeDefSummary=null, targetAttributeTypeDef=null, targetInstanceGUID='null', otherOrigin=null, otherMetadataCollectionId='null', otherTypeDefSummary=null, otherTypeDef=null, otherAttributeTypeDef=null, otherInstanceGUID='null', OMRSEventV1=org.odpi.openmetadata.repositoryservices.events.beans.v1.OMRSEventV1@1b76886f}
Wed Apr 01 16:35:40 BST 2020 Report_Server Exception OMAS-ASSET-LINEAGE-0005 Supplementary information: log record id 1657cc09-1e81-43d0-983a-5c1744429685 org.odpi.openmetadata.accessservices.assetlineage.ffdc.exception.AssetLineageException returned message of Cannot get the relationships from repository, relationship does not exist. and stacktrace of 
OCFCheckedExceptionBase{reportedHTTPCode=404, reportingClassName='org.odpi.openmetadata.accessservices.assetlineage.handlers.ProcessContextHandler', reportingActionDescription='Retrieving Relationship', reportedErrorMessage='Cannot get the relationships from repository, relationship does not exist.', reportedErrorMessageId='null', reportedErrorMessageParameters=null, reportedSystemAction='The system is unable to get the relationships for the queried entity.', reportedUserAction='Check if the relationship queried is available on the repository in the cohort.', reportedCaughtException=null, reportedCaughtExceptionClassName='null', relatedProperties=null}
	at org.odpi.openmetadata.accessservices.assetlineage.handlers.ProcessContextHandler.hasEntitiesLinkedWithProcessPort(ProcessContextHandler.java:121)
	at org.odpi.openmetadata.accessservices.assetlineage.handlers.ProcessContextHandler.checkIfAllRelationshipsExist(ProcessContextHandler.java:93)
	at org.odpi.openmetadata.accessservices.assetlineage.handlers.ProcessContextHandler.getProcessContext(ProcessContextHandler.java:88)
	at org.odpi.openmetadata.accessservices.assetlineage.outtopic.AssetLineagePublisher.publishProcessContext(AssetLineagePublisher.java:77)
	at org.odpi.openmetadata.accessservices.assetlineage.listeners.AssetLineageOMRSTopicListener.processNewEntity(AssetLineageOMRSTopicListener.java:146)
	at org.odpi.openmetadata.accessservices.assetlineage.listeners.AssetLineageOMRSTopicListener.processInstanceEvent(AssetLineageOMRSTopicListener.java:102)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicListenerWrapper.processInstanceEvent(OMRSTopicListenerWrapper.java:146)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicConnector.processOMRSEvent(OMRSTopicConnector.java:508)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicConnector.lambda$processEvent$0(OMRSTopicConnector.java:445)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by DimitriosMaimaris** [comment]
This is normal and is not an issue. It cannot find a relationship for an entity so that's why you see that. Maybe I have to switch to info or debug.

**Comment by grahamwallis** [comment]
@dimi - It definitely needs to be reduced to debug - otherwise every time someone creates a process an exception stack trace is being output. It is not an error condition.

**Comment by DimitriosMaimaris** [comment]
@grahamwallis you are right I will switch it.

**Comment by popa-raluca** [comment]
This is already fixed in the egeria-feature-openlineage branch, will be merged into master along with the other lineage changes
