### ISSUE TITLE
Javadoc warnings in generated code of Subject Area OMAS

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#287]
The Javadoc command produces a lot of warnings from the generated code from Subject Area OMAS.  However they look very repetitive and may only be a couple of minor issues in the template.  One looks like missing text from an @return and the other is related to an @throws.

It would be helpful to get rid of these since it makes it hard to locate warnings coming out of the other modules.

**Comment by CDaRip2U** [comment]
I'll coordinate with David on this, but locally i am down to 7 warnings in subject-area-server.  I'll try to get the last of those done and discuss when to move this in.

**Comment by CDaRip2U** [comment]
I believe David fixed the last of these warnings for now.  closing.
