### ISSUE TITLE
Proposed change to RestTemplate for SpringRESTClientConnector

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#2883]
This issue is a proposed change to the SpringRESTClientConnector.

It currently news up a RestTemplate.
The proposed change is to use create the RestTemplate with the RestTemplateBuilder so that the URI encoding can be controlled.

The reason for this is that, if a regular expression is used for searchCriteria on a call to findEntitiesByPropertyValue or findRelationshipsByPropertyValue, the searchCritera string is appended to the URI as a query parameter. 

If the regex contains a '+' character (which means the string to be matched must contain at least one, and optionally multiple,  occurrences of the previous character - the '+' is encoded as a space.

For example, the regex "bond_0+7" should match "bond_07", "bond_007", "bond_0007", etc.
Without the above proposal the query parameter is converted to "bond_0 7", so the search fails.
With the proposed change, the "+" is preserved, and the regex is delivered to the Spring server interface as "bond_0+7", and the search would succeed.

The change is to replace the creation of the RestTemplate with the following:
```
 DefaultUriBuilderFactory builderFactory = new DefaultUriBuilderFactory();
 builderFactory.setEncodingMode(DefaultUriBuilderFactory.EncodingMode.VALUES_ONLY);
 restTemplate = new RestTemplateBuilder()
                .uriTemplateHandler(builderFactory)
                .build();
```
The associated PR has been built and tested and addresses the problem. 
With the PR, searches work.

**Comment by grahamwallis** [comment]
@bogdan - Bogdan could you please make sure you are happy with this change?
PR is 2884

**Comment by planetf1** [comment]
I've also added my comment to the PR
