### ISSUE TITLE
update type archive for 1.7

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#2892]
Update the open metadata archive for release 1.7 (OpenMetadataTypesArchive)

See https://github.com/odpi/egeria/issues/2749

**Comment by mandy-chessell** [comment]
I have done this already

**Comment by planetf1** [comment]
> I have done this already

I don't see in master yet. Is it in a pending change?
```
➜  opentypes git:(master) ls
OpenMetadataTypesArchive.java         OpenMetadataTypesArchive1_3.java      OpenMetadataTypesArchive1_5.java      OpenMetadataTypesArchiveWriter.java
OpenMetadataTypesArchive1_2.java      OpenMetadataTypesArchive1_4.java      OpenMetadataTypesArchiveAccessor.java package-info.java
➜  opentypes git:(master) pwd
/Users/jonesn/src/egeria/open-metadata-resources/open-metadata-archives/open-metadata-types/src/main/java/org/odpi/openmetadata/opentypes
➜  opentypes git:(master) git pull upstream amster
fatal: couldn't find remote ref amster
➜  opentypes git:(master) git pull upstream master                                                                                                                          <<<
From https://github.com/odpi/egeria
 * branch                master     -> FETCH_HEAD
Already up to date.
```
Or perhaps I misunderstand the process - but would expect to move the OpenMetadataTypesArchive to include 1_6, and then create a new one (ran out of time to do creating the release so was going to return to it this week)

**Comment by planetf1** [comment]
Having checked I now see this was added in 4bd09f075e

**Comment by mandy-chessell** [comment]
Yes - sorry I did not link the commit as I had done it before this issue was raised - just was slow at merging it into master.  Part of the changes I made was to make it easier to do the update.  Do you want to do the 1.8 version?
