### ISSUE TITLE
Kafka Consumer polling time not configurable

### ISSUE THREAD

**Issue by lcpopa** [odpi/egeria#2916]
Kafka Consumer polling frame should be configurable, as various aspects of the habitat in which Kafka is running must be taken into account.

KafkaOpenMetadataEventConsumer:440
```
    private void awaitNextPollingTime() {
		try
		{
		    Thread.sleep(1000);
		}
		catch (InterruptedException e)
		{
		    log.error(String.format("Interruption error: %s", e.getMessage()), e);
		}
	}
```

**Comment by planetf1** [comment]
Also assigning @wbittles
