### ISSUE TITLE
Can not change rootPath for egeria ui

### ISSUE THREAD

**Issue by zoranid** [odpi/egeria#2918]
Need to access egeria app on /my-app/  path rather then /

As it is spring boot application the following should work:
java -jar ui.jar --server.servlet.context-path=/a123. However accessing ui from browser https://localhost:8443/my-app/ shows a blank page. I tried to use the following receipt https://stackoverflow.com/questions/42090070/serving-polymer-app-to-a-path-not-at-root with no success.  I also changed BOOT-INF/classes/public/index.html as per instructions in index.html
```
window.MyAppGlobals = {
  rootPath: '/my-app/'
}; // Load and register pre-caching Service Worker
```
I was able to get home page to load with errors but was not able to login

**Comment by bogdan-sava** [comment]
PR created.
Once is merged, the only thing to be done is to use --server.servlet.context-path parameter
Polymer rootPath is dynamically generated according to contextPath

PS: Thank you let us know about it.

**Comment by zoranid** [comment]
Great. Thanks @bogdan-sava. Would this change be reflected in egeria docker image? If so, what is the image tag? docker.io/odpi/egeria:<tag>

**Comment by bogdan-sava** [comment]
after it propagates to 1.8-SNAPSHOT tag

**Comment by planetf1** [comment]
FYI we now build the docker image for SNAPSHOTs straight from master once the code is merged - so it should be on dockerhub within around 30 minutes from merge time.
