### ISSUE TITLE
Create Release 1.7

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#2923]
In preparation of the 1.7 release
Current estimate date to start this off - around 23 Apil

- [x] ✅ Create 1.x branch
- [x] ✅ Update master to 1.(x+1)-SNAPSHOT
- [x] ✅ Update branch from 1.x-SNAPSHOT to 1.x
- [x] ✅ Remove release notes from branch
- [X] ⚠️ Verify notebooks (#2959/#2970/#3005/#2935)
- [X] ✅ check UI (#3006)
- [x] ✅  Run CTS 
- [x] ✅ Run FVTs (this is only FVTs automated in the build process)
- [x] ✅ Check samples (only samples in the build)
- [x] ⚠️ Check swagger doc (#3007)
- [X] ⚠️ Ensure release is current in master release notes & Add any final text (#2873)
- [x] ✅ Launch release pipeline 
- [x] ✅ Verify docker image/charts/compose
- [x] ✅ Approve release
- [x] ✅ Verify artifacts all on maven central (check for JCenter & other errors in release logs)
- [X] ✅ Create GitHub release
- [X] ⏭️ Blog Post (need to do a catchup post)
- [x] ⏭️ Update master with new Type patchfile (planned against new release)

**Comment by cmgrote** [comment]
23 March? 😱

**Comment by planetf1** [comment]
@mandy-chessell can you provide either the text (below), or a committed update to /release/release-notes-1-7.md to cover the Reference Data Management feature in 1.7 ?

Since this isn't actually checked into the release & there is more testing to go, it can be early next week...

**Comment by planetf1** [comment]
#2935 - 'Exception OMAS-GOVERNANCE-ENGINE-0008 The Governance Engine Open Metadata Access Service (OMAS) encounter an exception while processing incoming event {0}' is being reported constantly when dealing with entities

**Comment by planetf1** [comment]
CTS (in mem) succeeded with:
```
Date of conformance test:          2020-04-30T13:05:54.995+0000
Number of tests that were run:     4280
Number of tests that failed:       0
Number of tests that were skipped: 0
```
```
id	name	description	profilePriority	conformanceStatus
0	0	Metadata sharing	The technology under test is able to share met...	MANDATORY_PROFILE	CONFORMANT_FULL_SUPPORT
1	1	Reference copies	The technology under test is able to save, loc...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
2	2	Metadata maintenance	The technology under test supports requests to...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
3	3	Dynamic types	The technology under test supports changes to ...	OPTIONAL_PROFILE	UNKNOWN_STATUS
4	4	Graph queries	The technology under test supports graph-like ...	OPTIONAL_PROFILE	CONFORMANT_PARTIAL_SUPPORT
5	5	Historical search	The technology under test supports search for ...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
6	6	Entity proxies	The technology under test is able to store stu...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
7	7	Soft-delete and restore	The technology under test allows an instance t...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
8	8	Undo an update	The technology under test is able to restore a...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
9	9	Reidentify instance	The technology under test supports the command...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
10	10	Retype instance	The technology under test supports the command...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
11	11	Rehome instance	The technology under test supports the command...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
12	12	Relationship search	The technology under test supports the ability...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
13	13	Entity advanced search	The technology under test supports the use of ...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
14	14	Relationship advanced search	The technology under test supports the use of ...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
```

**Comment by planetf1** [comment]
And for the graph CTS:
```
Date of conformance test:          2020-04-30T14:20:26.419+0000
Number of tests that were run:     4280
Number of tests that failed:       0
Number of tests that were skipped: 0
```
id	name	description	profilePriority	conformanceStatus
0	0	Metadata sharing	The technology under test is able to share met...	MANDATORY_PROFILE	CONFORMANT_FULL_SUPPORT
1	1	Reference copies	The technology under test is able to save, loc...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
2	2	Metadata maintenance	The technology under test supports requests to...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
3	3	Dynamic types	The technology under test supports changes to ...	OPTIONAL_PROFILE	UNKNOWN_STATUS
4	4	Graph queries	The technology under test supports graph-like ...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
5	5	Historical search	The technology under test supports search for ...	OPTIONAL_PROFILE	CONFORMANT_NO_SUPPORT
6	6	Entity proxies	The technology under test is able to store stu...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
7	7	Soft-delete and restore	The technology under test allows an instance t...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
8	8	Undo an update	The technology under test is able to restore a...	OPTIONAL_PROFILE	CONFORMANT_NO_SUPPORT
9	9	Reidentify instance	The technology under test supports the command...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
10	10	Retype instance	The technology under test supports the command...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
11	11	Rehome instance	The technology under test supports the command...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
12	12	Relationship search	The technology under test supports the ability...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
13	13	Entity advanced search	The technology under test supports the use of ...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
14	14	Relationship advanced search	The technology under test supports the use of ...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
```

**Comment by planetf1** [comment]
Delays caused by
 * response from a package sync (bintray-> maven central) taking 2m-30m and hence jobs timing out
 * Maven central being down for several hours returning 405 http errors (under maintenance)

Finally sync completed with the following issues
stewardship-engine-services-api - not in JCenter. Attempt to add shows 'sources not found'
stewardship-engine-services-client - as above
stewardship-engine-services-spring - as above


Checking the source shows that this is the same state as with 1.6 - ie that the artifacts are incorrect as reported -- they are defined to be of type 'jar' but do not contain any source. 

This is another learning from our current process -- ideally we need to find a way to know, automatically, that this is ok - so that the process doesn't fail. This could be a user workflow step, or maybe a way as part of the build we can mark as 'do not distribute'

However this means the release to maven central is now complete
