### ISSUE TITLE
Cannot audit log exception during configuration of audit log store

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#2928]
OMRSOperationalServices.getAuditLogStore() method can detect an error in the configuration by catching a ConnectorCheckedException. In the catch block it tries to log the exception to the auditLog. Because the auditLog is still null it results in an NPE, which hides the original (valid) ConenctorCheckedException.

Presumably we just need to remove the attempt to audit log the original exception.

**Comment by mandy-chessell** [comment]
Agreed
