### ISSUE TITLE
swagger with filter set on is not working

### ISSUE THREAD

**Issue by bogdan-sava** [odpi/egeria#2938]
swagger UI with filter option is not working properly and ends up in a javascript error.

<img width="1051" alt="Screen Shot 2020-04-18 at 8 32 29 AM" src="https://user-images.githubusercontent.com/40362260/79629135-52d03e00-814f-11ea-9cc1-a8164fe1df8a.png">

Without filter parameter seems to work fine.

**Comment by bogdan-sava** [comment]
sometimes loads with 'No operations defined in specs' message:
<img width="1312" alt="Screen Shot 2020-04-18 at 9 04 43 AM" src="https://user-images.githubusercontent.com/40362260/79629711-66ca6e80-8154-11ea-943c-8b08e0aa50fd.png">

**Comment by planetf1** [comment]
Agreed - let's remove it
