### ISSUE TITLE
UI add layout configuration for spring-boot-maven-plugin

### ISSUE THREAD

**Issue by bogdan-sava** [odpi/egeria#2944]
adding layout config allows to use loader.path in order to add external dependencies

**Comment by planetf1** [comment]
I added some notes to the PR 
 I'm presuming this changes the artifact from a jar to a zip - this may have other impacts we need to look at / fix up.

 See PR for notes so far -- but this should indeed probably be discussed in this issue (which I saw after)

**Comment by bogdan-sava** [comment]
Jar is a zip format with jar extension.
The configuration itself is not change the format but allows using loader.path the same way as server-chassis (where we have the same configuration already), which allows loading external dependencies (jars and or files).
Primary purpose is to be able to externalize css files so to be able to customize the look and feel without changing the build. 
Long term is to be able to plug in and out additional views in the UI.

There are no other artifacts affected.
It is not impact current functionality at all.

**Comment by planetf1** [comment]
Sounds good. I misinterpreted as a format change with external impact, but if still jar and follows the pattern of the server chassis that sounds very appropriate - and agree with the reasoning behind the requirement
