### ISSUE TITLE
Remove omrs-monitor

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#2958]
omrs-monitor is no longer used

@grahamwallis I'm thinking now I may as well remove the container to keep the codebase simple - it just adds clutter keeping things we don't need around. This was prompted by https://github.com/odpi/egeria/pull/2956

Not sure if you want to delete the code or not? If so I'm happy to do, but I'll assume not.

Or conversely do you see a chance we'll move forward with the monitor in future?

**Comment by grahamwallis** [comment]
@planetf1 Thanks Nigel - I'd be happy to see it removed (both the container and the code). We can resurrect it if we ever need to, but I somehow think we won't need it.

**Comment by planetf1** [comment]
Ok - thanks. I'll do that removal as part of this change then
