### ISSUE TITLE
Assign metadataCollectionId as key in kafka messages

### ISSUE THREAD

**Issue by kbaibhav** [odpi/egeria#296]
Currently no key is assigned to the messages sent on open metadata kafka topic, assigning the key as metadata collection id of the originator will allow the event originator in cohort to ignore the message before de-serializing  it. Also it can be used to ignore the messages from a particular member in  cohort, if required.

**Comment by mandy-chessell** [comment]
See. Git Issue https://github.com/odpi/egeria/issues/279 (Item 2) and Pull Request https://github.com/odpi/egeria/pull/295
