### ISSUE TITLE
IV OMAS does not complete initialization - NPE in Kafka Config

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#297]
If I look at the startup messages, IV OMAS is no longer outputting its "initialized" message and I wondered if it is completing initialization.  I notice that Subject Area OMAS is no longer getting initialized which adds to my suspicion that IV OMAS is hanging in initialization. :)

Running the code through the debugger shows a null pointer exception coming from **initializeInformationViewTopicConnector** where the "kafka.omrs.topic.id" property is replaced by 
accessServiceInTopic.getQualifiedName().

private OpenMetadataTopicConnector **initializeInformationViewTopicConnector**(Connection accessServiceInTopic, Connection accessServiceOutTopic) {
        final String actionDescription = "initialize";
        if (accessServiceInTopic != null) {
            Map<String, Object> properties = accessServiceInTopic.getAdditionalProperties();
            **((Map) properties.get("consumer")).replace("kafka.omrs.topic.id", accessServiceInTopic.getQualifiedName());
            ((Map) properties.get("producer")).replace("kafka.omrs.topic.id", accessServiceOutTopic.getQualifiedName());**
            accessServiceInTopic.setAdditionalProperties(properties);
            try {
                return getTopicConnector(accessServiceInTopic);
            } catch (Exception e) {
                InformationViewAuditCode auditCode = InformationViewAuditCode.ERROR_INITIALIZING_CONNECTION;
                auditLog.logRecord(actionDescription,
                        auditCode.getLogMessageId(),
                        auditCode.getSeverity(),
                        auditCode.getFormattedLogMessage(accessServiceInTopic.toString()),
                        null,
                        auditCode.getSystemAction(),
                        auditCode.getUserAction());
                throw e;
            }

I don't have this property set so hence the problem.

The current implementation of the Kafka connector incorrectly uses the "kafka.omrs.topic.id" as the place where the topic name is passed.  When Pull Request #279 is merged, this will change the kafka connector to take the topic name from the endpoint.getAddress() so this code will fail all of the time - not just when someone like me does not have all of the properties set correctly.

**Comment by ruxandraRosu** [comment]
Fixed in pull request #301
