### ISSUE TITLE
Kafka - WakeupException after temporary deactivate the services for a server 

### ISSUE THREAD

**Issue by danielaotelea** [odpi/egeria#2991]
After calling DELETE {{url-server}}/open-metadata/admin-services/users/{{user-id}}/servers/{{server-id}}/instance, I got the following exception: 

Mon Apr 27 15:51:09 EEST 2020 platform-2 Shutdown OMRS-AUDIT-0011 The Open Metadata Repository Services (OMRS) has disconnected from the open metadata repositories
Mon Apr 27 15:51:09 EEST 2020 platform-2 Shutdown OMAG-ADMIN-0006 The platform-2 server has completed shutdown
Mon Apr 27 15:51:09 EEST 2020 platform-2 Shutdown OMRS-AUDIT-0016 The listener thread for the OMRS Topic Connector for topic OMRSTopic.openmetadata.repositoryservices.cohort.cohort1.OMRSTopic has shutdown
Mon Apr 27 15:51:09 EEST 2020 platform-2 Shutdown OMRS-AUDIT-0016 The listener thread for the OMRS Topic Connector for topic platform-2.openmetadata.repositoryservices.enterprise.platform-2.OMRSTopic has shutdown
Exception in thread "Kafka-Consumer-OMRSTopic.openmetadata.repositoryservices.cohort.cohort1.OMRSTopic" org.apache.kafka.common.errors.WakeupException
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.maybeTriggerWakeup(ConsumerNetworkClient.java:511)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:275)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:212)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.commitOffsetsSync(ConsumerCoordinator.java:977)
	at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1511)
	at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1459)
	at org.odpi.openmetadata.adapters.eventbus.topic.kafka.KafkaOpenMetadataEventConsumer.run(KafkaOpenMetadataEventConsumer.java:272)
	at java.lang.Thread.run(Thread.java:748)
Mon Apr 27 15:51:09 EEST 2020 platform-2 Shutdown OCF-KAFKA-TOPIC-CONNECTOR-0011 The Apache Kafka producer for topic OMRSTopic.openmetadata.repositoryservices.cohort.cohort1.OMRSTopic is shutting down after sending 543 messages and with 0 unsent messages
Mon Apr 27 15:51:09 EEST 2020 platform-2 Startup OCF-KAFKA-TOPIC-CONNECTOR-0002 8 properties passed to the Apache Kafka Producer for topic OMRSTopic.openmetadata.repositoryservices.cohort.cohort1.OMRSTopic
Mon Apr 27 15:51:09 EEST 2020 platform-2 Startup OCF-KAFKA-TOPIC-CONNECTOR-0010 The Apache Kafka producer for topic OMRSTopic.openmetadata.repositoryservices.cohort.cohort1.OMRSTopic is starting up with 0 buffered messages

**Comment by planetf1** [comment]
Looks like it's trying to do a final commit as it's shutting down, but exceptions are not caught in this final last attempt. Since we know we're shutting down anyway we should probably discard.
Most of the time I suspect it's harmless but should be tidied up.Perhaps we should log an audit event if any messages were unprocessed, or if we couldn't commit the right offset - potential there for messages being replayed the next time the consumer starts up - should be ok though.

**Comment by planetf1** [comment]
Also fao @wbittles

**Comment by wbittles** [comment]
I'd need to see trace to be certain, and I'm not sure what "_temporary deactivate the services for a server_"  actually involves, but looking at the exception the kafka consumer is still running when the server was deleted. Looking at the code, the Egeria connector doesn't actually implement a Kafka disconnect, instead it causes Kafka to throw a WakeupException, and returns successfully even though it has just "passed the buck", hence we are getting 
"OMRSTopic.openmetadata.repositoryservices.cohort.cohort1.OMRSTopic has shutdown"
reported before the exception, which is technically correct, but confusing.

There is a way of asking kafka to stop a consumer gracefully and ideally this worth future investigation as a more graceful solution, it is a bit more involved but still a reasonable bug fix.

As this is a cohort topic, I'd be extremely reluctant to allow any kind of buffering/replay behaviour.
I think this brings us round to the whole cohort initialisation issue.

adding @grahamwallis for FYI

**Comment by grahamwallis** [comment]
@wbittles - please also see #3144 for a similar consideration (about the commitSync/rebalance exception handling)

**Comment by wbittles** [comment]
@planetf1 @grahamwallis @danielaotelea 
I've opened PR #3247 to address all the issues raised here.

**Comment by planetf1** [comment]
This appears to be addressed as above so closing.
