### ISSUE TITLE
UnRegistration Event is not sent when a server is disconnected from the cohort 

### ISSUE THREAD

**Issue by danielaotelea** [odpi/egeria#2997]
The current setup contains two platforms.
The first platform is running with one server - server1. This server runs only access-services.
The second platform is running with one server - server2. Server2 has enabled access-services and Egeria local-graph. 
After running instance on each server, the initial exchange is successful, the Registry Event - Registration is sent.
When server2 is deactivated temporarily, there is no event published on cohort topic.
When server2 is activated again, the Registry Event - REFRESH_REGISTRATION_REQUEST is sent successfully.

**Comment by planetf1** [comment]
My understanding is that a temporary deactivation of a server does not result in a deregistration event - the server may be being recycled or moved, and will rejoin the cohort & pick up with messages from the appropriate sync point?

**Comment by danielaotelea** [comment]
Yes, indeed. After a temporary deactivation of a server, there is no Kafka event so that server is not recycled.

**Comment by planetf1** [comment]
I meant that I think that is as-designed. We only deregister a server from the cohort if it's removal is permanent. The managing servers lab refers to this behaviour at https://github.com/odpi/egeria/blob/master/open-metadata-resources/open-metadata-labs/administration-labs/managing-servers.ipynb

**Comment by mandy-chessell** [comment]
@planetf1 is correct - it is working correctly.  We do not send the unregistration request when a server goes down (deactivate temporarily) because there may be other instances of the server still running and they will not want to be unregistered from the cohort.

**Comment by planetf1** [comment]
@danielaotelea can this be closed?
