### ISSUE TITLE
OMRS Search not returning subtypes of the requested type

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#300]
For example, if you search for "Asset" entities then it should return entities that are of the Asset's subtypes such as DeployedDatabase, DeployedAPI.

**Comment by cmgrote** [comment]
@grahamwallis and I have now fixed this for our respective connectors -- anywhere else it still needs to be resolved (InMemory?) or can we close?

**Comment by mandy-chessell** [comment]
The repository helper has methods that the in-memory repository is using to manage subtypes
