### ISSUE TITLE
Audit Log - default supported severities list is empty

### ISSUE THREAD

**Issue by danielaotelea** [odpi/egeria#3000]
Based on the current documentation, if the supportedSeverities list is empty, the default configuration should support all severities.

**Comment by mandy-chessell** [comment]
What is the behaviour that you are seeing - which severities are not supported when the list is empty?  Is this for a specific audit log connector?

The design is that to request all severities you either pass a null or empty list of severities to
the audit log connector implementation.

The base class for the audit log connectors includes a method called `isSupportedSeverity`
which always returns true if the list is null or empty.

**Comment by mandy-chessell** [comment]
I think this is resolved
