### ISSUE TITLE
Release 1.7 - UI fails with 'We are experiencing an unexpected error'

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#3006]
When testing release 1.7 ( 632e6e1a6ece21ec9f1fd8607249f5adc31b33d8 )and opening up the GUI, an error
'We are experiencing an unexpected error. Please try again later!' 
is reported

Search also fails - for example if the 'building a data catalog' notebook is run beforehand, one can normally search for assets containing 'csv'. This fails
Further more subject area & type explorer fail also

No audit log messages in UI container, nor in any of the targeted egeria servers (ie core or data lake).

Investigating ...

**Comment by bogdan-sava** [comment]
There is no AuditLog in UI and logging is turned of by default in the applicacation.properties

**Comment by bogdan-sava** [comment]
Quick test on my side works fine.
Not using notebook but fresh build, config and run from branch egeria-relase-1.7 .
