### ISSUE TITLE
Adding new dependency: Spring Boot Actuator

### ISSUE THREAD

**Issue by danielaotelea** [odpi/egeria#3019]
Spring Boot Actuator is used to expose operational information about the running application – health, metrics, info, dump, env, etc. It uses HTTP endpoints or JMX beans to enable us to interact with it. Once this dependency is on the class-path several endpoints are available for us out of the box: /info, /health.

Spring Boot Actuator provides dependency management and auto-configuration for Micrometer, an application metrics facade that supports numerous monitoring systems, including: AppOptics,Prometheus.

**Comment by planetf1** [comment]
this has been done.? close?

**Comment by danielaotelea** [comment]
Yes, it's done.
