### ISSUE TITLE
Validate Kafka Topic Name is made up of valid characters in Kafka Connector

### ISSUE THREAD

**Issue by bogdan-sava** [odpi/egeria#302]
For example, the "/event-bus" rest call invalid value for topicURLRoot  (such as 'localhost:9092/OMRSTopic') should to return bad request exception. 

Affected file OMAGServerAdminResource.java

**Comment by mandy-chessell** [comment]
I have changed the label to an enhancement since the /event-bus method is working correctly.  Improving the diagnostics for Kafka is desirable.
