### ISSUE TITLE
Subject Area problems

### ISSUE THREAD

**Issue by immmus** [odpi/egeria#3090]
Collected all the problems that need to be fixed in one issue

1. 
 When call get request all categories without parameters to

_http://localhost:8080/servers/test/open-metadata/access-services/subject-area/users/admin/categories_
```

I was get next exception:
{
    "class": "InvalidParameterExceptionResponse",
    "relatedHTTPCode": 200,
    "responseCategory": "InvalidParameterException",
    "exceptionClassName": "org.odpi.openmetadata.accessservices.subjectarea.server.handlers.ErrorHandler",
    "exceptionErrorMessage": "OMAS-SUBJECT-AREA-400-035 Invalid parameter processing request findCategory.",
    "exceptionSystemAction": "The system is unable to process the request.",
    "exceptionUserAction": "Please correct the parameter and retry."
}
```
Request without parameters don't might throw exception, it must return all categories.  How it work for glossaries and terms.

1.1 .

After I fixed the bug and i've filling catalog via org.odpi.openmetadata.accessservices.subjectarea.samples.SubjectAreaDefinitionSample.
And I was get next the picture when I was called all categories again, I get only one entity instead of all and with each request different.

The fact is that the findCategory method in the class org.odpi.openmetadata.accessservices.subjectarea.handlers.SubjectAreaCategoryHandler 
has the following limitation:

```
response = getCategory(userId, entityDetail.getGUID());
                    if (response.getResponseCategory() == ResponseCategory.Category) {
                        CategoryResponse categoryResponse = (CategoryResponse) response;
                        Category category = categoryResponse.getCategory();
                        categories.add(category);
                    } else {
````

That is, if an entity arrives with a different ResponseCategory other than Category, the method does not add (in this case, SubjectAreaDefinition).
The problem is clearly of an architectural nature, as when adding any new ResponseCategory, the method will grow "if else", which will make the code less supported. The architecture of work in this case is worth rethinking.

This problem is absent if you simply use the Category entity.

2. 

I noticed that in the class org.odpi.openmetadata.accessservices.subjectarea.server.services.SubjectAreaRESTServicesInstance there are two big unused methods "getRelationshipsFromGuid" written a year ago

3. 

I noticed a problem when getting categories, ParentCategorySummary is not installed, although the method for this is in SubjectAreaUtils, but it is not used

**Comment by immmus** [comment]
I know how fix 1 and 3 problems, but I can't to proceed with this because I am waiting for merge this pr's (#3071, #3069, #3067). Please, could you do it faster?;) I am waiting already a week...

**Comment by immmus** [comment]
Solution 1 and 2 problems is here https://github.com/odpi/egeria/pull/3137

**Comment by immmus** [comment]
@planetf1 Hi, can you assign to me this issue. I resolved all these problems;)

**Comment by planetf1** [comment]
@immus sure (cc: @davidradl ). I am assuming these will not go into 2.0 (which we're trying to get out once a decision on the previous PR is made)

**Comment by immmus** [comment]
@planetf1 okay

**Comment by immmus** [comment]
This issue complete in the https://github.com/odpi/egeria/pull/3245.
