### ISSUE TITLE
Proposal: make swagger-ui default html document of server-chassis

### ISSUE THREAD

**Issue by bogdan-sava** [odpi/egeria#3096]
Swagger UI contains now very useful information and external links.
What do you think about making it default html document by changing  default configuration from:

`springdoc.swagger-ui.path=/swagger-ui.html`

to 

`springdoc.swagger-ui.path=/`

this mapping will cause redirect automatically from 
http://localhost:8080
to 
http://localhost:8080/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config

**Comment by planetf1** [comment]
I think it's a good idea to think about -- ie having a good default landing page - at least in the development case. In production perhaps this should be disabled.

One question is whether the landing page should be a pretty/informative page, or the swagger page.

But if there are no other comments I'd be happy to go with your suggestion for now.

**Comment by planetf1** [comment]
Note that the new Dojo lab documentation includes references to the swagger UI - so URL/screenshots will need updating there.

**Comment by bogdan-sava** [comment]
we can leave it for after the Dojo or you can pick it up

**Comment by planetf1** [comment]
After this week's dojo is best -- though that material is long-lived, so will need to be kept up to date with any changes.
