### ISSUE TITLE
refinements for build of presentation server

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#3098]
Initial presentation server code was added in #3085

This is currently standalone, but will need to be integrated into the maven build.

A few observations from the code PRs  so far
 - need to revisit how we handle nodejs build process, in particular how tools & modules are downloaded, and where these are placed in the build tree. This may impact how 'mvn clean' works, whether we can reach each phase correctly, use of .gitgnore & rat exclusions
 - Dependabot should be configured to point to the package.json so we can verify dependencies
 - need to review if our security scans are finding any issues (LF/nexus)
 - any node WARNings should be reviewed/fixed 
 - ensure cross platform build ok (linux x86, macos, windows, pi)
 - ensure necessary artifacts added to assemblies
 - ensure we can run from assembly
 - ensure all works ok in container environments (ports, files etc)
 - users should be synchronized with full coco set used by original UI
 - certificates are included. Replacement/usage needs documenting -- see also #1403

And a few few functional issues
 - Security is being added to chassis in #1403 - this may impact

cc: @grahamwallis @davidradl - Adding these notes as a placeholder when we do the integration.

**Comment by planetf1** [comment]
See also #3135 to address integration requirements around security

**Comment by planetf1** [comment]
[ ] Initial maven driven build of existing node build
[ ] Add artifact (ie bundle.js) to assembly
[ ] Add/configure docker image
[ ] Update lab deployment to include node deployment
[ ] refactor/clean build paths to use maven-friendly paths

**Comment by planetf1** [comment]
Initial PR created.

Note that I am not using the scripts in the package.json. Whilst it is possible to call these, they will need refactoring as must be platform independent. Initially the frontend plugin already has first class support for webpack. Finally by doing seperately in the pom, at least initially, it avoids any conflict with current dev activity - an easier transition

**Comment by davidradl** [comment]
@planetf1  as discussed, I reviewed a previous pr https://github.com/odpi/egeria/pull/3152 and noticed some minor things. The presentation server pom name and description did not seem right. Also there is a TODO around maven clean in the pom file - that seems to have been left in - I am not sure there is anything left to do there.

**Comment by planetf1** [comment]
See also #3231 which updates the assembly creation process to use moduleSets and correct dependencies.

This also brought up the question of what each maven artifact we 'build' should contain.

- A maven module of packaging type 'pom' means little happens - we create an artifact with that pom definition but do not expect to find any other attachments - though these can be added if needed
 - jar based modules are handled nicely by maven by default -- we end up with the java code neatly packaged into a sources attachment, as well as the build jar as a binary
 - what does this all mean for a node based application? ....
   * should we collate all of the source files into the sources attachment?
   * Do we collate anything needed at runtime into a binary attachment?
   * Do we use non standard classifiers or types?

There are distinct benefits in ensuring our artifacts are 'complete' - we know some people will use them (from maven central etc) to create their runtime environment, so ad-hoc picking from the source tree itself is not a consistent approach with that (using sources from an attachment to the artifact would be ok though)

THEN we need to update the current assembly for presentation server, as well as the consuming docker image, to make use of these accordingly.

This needs some research into what best practice is. What do other maven based projects do when building node based components? If we can't find any examples we can certainly do something reasonable based on core principles around maven, but worth researching before jumping ahead.

**Comment by planetf1** [comment]
I found the presentation server build wasn't actually invoked from the 'user-interface' module -- so though it could be built manually this wasn't done automatically . I enabled this in #3231 but unfortunately the build is now broken by recent changes in presentation server.

I've now reverted the change in #3231 so the UI is not built and we can fix here.

The errors from the last build are at https://dev.azure.com/ODPi/Egeria/_build/results?buildId=8541&view=logs&j=4dc6fbf2-95db-5f93-ea5a-117822a16d38&t=61dc2478-351e-57b7-3c49-54d8ca2911d9&l=23593
```
[INFO] --- frontend-maven-plugin:1.10.0:webpack (webpack-build) @ presentation-server ---
[INFO] Running 'webpack.js --mode development --devtool inline-source-map' in /home/vsts/work/1/s/open-metadata-implementation/user-interfaces/presentation-server/nodejs
[INFO] clean-webpack-plugin: /home/vsts/work/1/s/open-metadata-implementation/user-interfaces/presentation-server/nodejs/dist has been removed.
[INFO] Hash: ca7406fa6159c5d84400
[INFO] Version: webpack 4.43.0
[INFO] Time: 63932ms
[INFO] Built at: 07/16/2020 3:49:52 PM
[INFO]       Asset       Size  Chunks             Chunk Names
[INFO]   bundle.js   41.4 MiB    main  [emitted]  main
[INFO] favicon.ico   43.6 KiB          [emitted]  
[INFO]  index.html  496 bytes          [emitted]  
[INFO] Entrypoint main = bundle.js
[INFO] [0] multi babel-polyfill ./src/client/index.js 40 bytes {main} [built]
[INFO] [./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./src/client/app.scss] 397 bytes {main} [built]
[INFO] [./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./src/client/index.scss] 460 KiB {main} [built]
[INFO] [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {main} [built]
[INFO] [./src/client/App.js] 848 bytes {main} [built]
[INFO] [./src/client/Frame.js] 4.74 KiB {main} [built]
[INFO] [./src/client/app.scss] 1.19 KiB {main} [built]
[INFO] [./src/client/auth/Login.css] 1.08 KiB {main} [built]
[INFO] [./src/client/auth/login.js] 4.84 KiB {main} [built]
[INFO] [./src/client/contexts/IdentificationContext.js] 3.6 KiB {main} [built]
[INFO] [./src/client/images/Egeria_glossary_author_32.js] 363 bytes {main} [built]
[INFO] [./src/client/images/Egeria_logo_color.js] 415 bytes {main} [built]
[INFO] [./src/client/images/Egeria_logo_white_110.js] 351 bytes {main} [built]
[INFO] [./src/client/index.js] 304 bytes {main} [built]
[INFO] [./src/client/index.scss] 1.2 KiB {main} [built]
[INFO]     + 6153 hidden modules
[INFO] 
[INFO] ERROR in ./src/client/images/Egeria_glossary_32.js

```

**Comment by planetf1** [comment]
@davidradl @jmmadsen I suggest I'll assign you to own this so that *when you are ready* you can describe the process
for building the UI, and what you expect to achieve.

Then assign it back for any additional changes you need to the packaging, container build, charts, deployment etc so that we can end up with an easily usable UI fully incorporated into our demos, and standard approaches for deployment including docker

**Comment by planetf1** [comment]
We are planning to move the UI build over to a new repo as per #4110 . As such I think it makes sense to close this for now & track ongoing enhancements in the new repo
