### ISSUE TITLE
Improve usability of importing all postman collections provided by Egeria

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#3100]
Our current dojo instructions guide a user to importing a series of postman collections which are distributed through the source tree. This distribution makes sense from a development perspective.

However for initial interactions with egeria we could bundle up all the collections either into one big collection, or collect together all the json files into one folder. This could be added to distribution assemblies & then imported in one step

**Comment by mandy-chessell** [comment]
I do not think this will help - the trouble that participants where having was finding the requests they needed. Bundling them up will not help there - particularly when we have collections for all of the OMASs :).  I thought about have a special postman collection for the dojo - this would make it easier to do the dojo - but not to see farther.   We could have a special one for the dojo and then ask them to load the component ones and look at them so they know they are there?

**Comment by planetf1** [comment]
Understand and agree --- less is more.

Outside the dojo though, for developers, easy access to all the collections via a single import would be beneficial, so this proposal may still have a place.

I wonder how feasible it could be to tag different requests with usage so that they are automatically composed into different bundles - I suspect too complex and too postman-specific.

The simplest approach seems to be as you describe - just to have a separate collection for the dojo

**Comment by mandy-chessell** [comment]
When I looked at the original description in the cold light of day I could see why people were baffled - the description was not clear and the postman collection has a bizarre structure that was not at all helpful.

I have done some work reorganizing the folder structure inside the server configuration collection and improving the documentation in the dojo around configuring the server.  Hopefully that will do it and we can avoid a dojo specific collection.
