### ISSUE TITLE
Many missing connectors in OMAG assembly

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#3101]
encrypted connector needs checking , in assembly deployed to docker container

**Comment by planetf1** [comment]
```
bash-4.4$ pwd
/opt/egeria/server/lib
bash-4.4$ ls -la
total 172
drwxr-xr-x    2 egeria   egeria        4096 May 26 10:13 .
drwxr-xr-x    4 egeria   egeria        4096 May 26 10:13 ..
-rw-r--r--    1 egeria   egeria        4446 May 26 10:13 avro-file-connector-1.8-SNAPSHOT.jar
-rw-r--r--    1 egeria   egeria       11464 May 26 10:13 basic-file-connector-1.8-SNAPSHOT.jar
-rw-r--r--    1 egeria   egeria        8892 May 26 10:13 cassandra-data-store-connector-1.8-SNAPSHOT.jar
-rw-r--r--    1 egeria   egeria       13279 May 26 10:13 csv-file-connector-1.8-SNAPSHOT.jar
-rw-r--r--    1 egeria   egeria        8556 May 26 10:13 data-folder-connector-1.8-SNAPSHOT.jar
-rw-r--r--    1 egeria   egeria       19559 May 26 10:13 discovery-service-connectors-1.8-SNAPSHOT.jar
-rw-r--r--    1 egeria   egeria       11075 May 26 10:13 gaian-connector-1.8-SNAPSHOT.jar
-rw-r--r--    1 egeria   egeria       56586 May 26 10:13 open-lineage-janus-connector-1.8-SNAPSHOT.jar
-rw-r--r--    1 egeria   egeria       13087 May 26 10:13 open-metadata-security-samples-1.8-SNAPSHOT.jar
```

no sign of the file store connector for config

**Comment by planetf1** [comment]
Looking at missing connectors there are many connectors missing.

Some of these are currently statically bound to the server via hard maven dependencies - where possible this hard dependency should be removed, and the connector dynamically loaded. (a seperate issue?)

We then have a series of connectos for
 - configuration
 - discovery (note we have multiple connectors in a single maven project - need to decide if these can be handled in a single artifact or should be split - I'm inclined to do the latter if they are diverse)
 - governance actions
 - audit logs
 - cohorts
 - archive files

Most likely ALL of these should be built with dependencies and added to lib..  Then at a later point any hard dependencies can be addressed.

**Comment by mandy-chessell** [comment]
Once this is done we can clean up the ConnectorConfigurationFactory which will help the security story.

**Comment by planetf1** [comment]
Agreed - let's try and do for 1.9

**Comment by mandy-chessell** [comment]
2.0?

**Comment by planetf1** [comment]
ok 'release after next' :-) If we agree in the next team meeting to go ahead with 2.0 for adding the https/ssl, then it will be 2.0 :-)

**Comment by planetf1** [comment]
If connectors are to be loaded dynamically, they can only be used if all libraries they are dependent on are found in the file path. 

Currently the connectors that are built do not include dependencies, so most will fail to load - unless we are 'lucky' enough to find the server chassis already happens to have ALL dependencies in the classpath.

We therefore have do do one of the following
 * Determine all the libraries that will be needed, and ensure they are placed under 'lib'
configuration-encrypted-file-store-connector. This will result in the smallest size and avoid duplication, but will be tricky to arrange and maintain
* Build all connectors as 'fat jars' including all dependencies. This will increase the size, but we can be confident that all needed libraries will be present. Additionally all the core Egeria dependencies have consolidated dependencies, so there will be no concerns about unknown library versions being used. However 3rd party connectors could introduce additional dependencies, and other classpath entries could change the behaviour. The benefit is this also extends to replacing libraries to fix bugs or location specific workarounds
* Build fat jars with relocation (ie 'shaded') - and likely extend to our 'apps' like the server chassis too. This will mean binding specific versions of libraries 

I think option a) is not feasible. b) is easy c) needs further consideration.

Therefore my proposal is to build fat jars, and review how well it works when we work on #1607. If needed we can switch to relocated jars in a future change.

**Comment by planetf1** [comment]
Some refinements on a)

Either
 * Use 'copy-dependencies' goal of maven-dependency-plugin to populate all per-module dependencies into target/lib -- and then pick/merge at assembly time .... or try to collect into a multi-module target
 * Develop a maven plugin for a more 'smart' approach.

Still continuing with b) for now.

**Comment by planetf1** [comment]
The current list of connectors now built is:
```
open-connector-archives-2.0-SNAPSHOT-jar-with-dependencies.jar
open-connector-archives-2.0-SNAPSHOT-jar-with-dependencies.jar
discovery-service-connectors-2.0-SNAPSHOT-jar-with-dependencies.jar
open-connector-archives-2.0-SNAPSHOT-jar-with-dependencies.jar
inmemory-open-metadata-topic-connector-2.0-SNAPSHOT-jar-with-dependencies.jar
kafka-open-metadata-topic-connector-2.0-SNAPSHOT-jar-with-dependencies.jar
discovery-service-connectors-2.0-SNAPSHOT-jar-with-dependencies.jar
rest-client-connectors-api-2.0-SNAPSHOT-jar-with-dependencies.jar
rest-client-connectors-2.0-SNAPSHOT-jar-with-dependencies.jar
spring-rest-client-connector-2.0-SNAPSHOT-jar-with-dependencies.jar
configuration-file-store-connector-2.0-SNAPSHOT-jar-with-dependencies.jar
configuration-encrypted-file-store-connector-2.0-SNAPSHOT-jar-with-dependencies.jar
csv-file-connector-2.0-SNAPSHOT-jar-with-dependencies.jar
data-folder-connector-2.0-SNAPSHOT-jar-with-dependencies.jar
basic-file-connector-2.0-SNAPSHOT-jar-with-dependencies.jar
avro-file-connector-2.0-SNAPSHOT-jar-with-dependencies.jar
cassandra-data-store-connector-2.0-SNAPSHOT-jar-with-dependencies.jar
gaian-connector-2.0-SNAPSHOT-jar-with-dependencies.jar
audit-log-slf4j-connector-2.0-SNAPSHOT-jar-with-dependencies.jar
audit-log-file-connector-2.0-SNAPSHOT-jar-with-dependencies.jar
audit-log-console-connector-2.0-SNAPSHOT-jar-with-dependencies.jar
audit-log-event-topic-connector-2.0-SNAPSHOT-jar-with-dependencies.jar
cohort-registry-file-store-connector-2.0-SNAPSHOT-jar-with-dependencies.jar
graph-repository-connector-2.0-SNAPSHOT-jar-with-dependencies.jar
omrs-rest-repository-connector-2.0-SNAPSHOT-jar-with-dependencies.jar
readonly-repository-connector-2.0-SNAPSHOT-jar-with-dependencies.jar
inmemory-repository-connector-2.0-SNAPSHOT-jar-with-dependencies.jar
open-metadata-archive-file-connector-2.0-SNAPSHOT-jar-with-dependencies.jar
cassandra-metadata-extractor-connector-2.0-SNAPSHOT-jar-with-dependencies.jar
security-officer-tag-connector-2.0-SNAPSHOT-jar-with-dependencies.jar
view-generator-connectors-2.0-SNAPSHOT-jar-with-dependencies.jar
ranger-connector-2.0-SNAPSHOT-jar-with-dependencies.jar
janus-connector-1.2-jar-with-dependencies.jar
open-lineage-janus-connector-2.0-SNAPSHOT-jar-with-dependencies.jar
```
These are basically all we have under 'adaptors' excluding the factories.

**Comment by planetf1** [comment]
Added to assembly (server/lib) for now. 

Another way of reducing dependencies....

If we consider the egeria server chassis to be 'the platform' we might be able to mark all platform-provided dependencies as 'provided' in those components that are dynamically loaded into the chassis. That tells maven it's already there and should mean the assembly will not duplicate that core set. The assembly plugin itself has more sophisticated rules for manipulating what is included.

Suggest deferring further refactoring to #1607

**Comment by planetf1** [comment]
The final distribution now contains:
```
jonesn:open-metadata-assemblies/ (issue3101*) $ ls target/egeria-2.0-SNAPSHOT-distribution/egeria-omag-2.0-SNAPSHOT/server/lib                                                                                                                                       [17:51:09]
audit-log-console-connector-2.0-SNAPSHOT-jar-with-dependencies.jar                  configuration-file-store-connector-2.0-SNAPSHOT-jar-with-dependencies.jar           open-lineage-janus-connector-2.0-SNAPSHOT-jar-with-dependencies.jar
audit-log-event-topic-connector-2.0-SNAPSHOT-jar-with-dependencies.jar              csv-file-connector-2.0-SNAPSHOT-jar-with-dependencies.jar                           open-metadata-archive-file-connector-2.0-SNAPSHOT-jar-with-dependencies.jar
audit-log-file-connector-2.0-SNAPSHOT-jar-with-dependencies.jar                     data-folder-connector-2.0-SNAPSHOT-jar-with-dependencies.jar                        open-metadata-security-samples-2.0-SNAPSHOT-jar-with-dependencies.jar
audit-log-slf4j-connector-2.0-SNAPSHOT-jar-with-dependencies.jar                    discovery-service-connectors-2.0-SNAPSHOT-jar-with-dependencies.jar                 ranger-connector-2.0-SNAPSHOT-jar-with-dependencies.jar
avro-file-connector-2.0-SNAPSHOT-jar-with-dependencies.jar                          gaian-connector-2.0-SNAPSHOT-jar-with-dependencies.jar                              readonly-repository-connector-2.0-SNAPSHOT-jar-with-dependencies.jar
basic-file-connector-2.0-SNAPSHOT-jar-with-dependencies.jar                         graph-repository-connector-2.0-SNAPSHOT-jar-with-dependencies.jar                   security-officer-tag-connector-2.0-SNAPSHOT-jar-with-dependencies.jar
cassandra-data-store-connector-2.0-SNAPSHOT-jar-with-dependencies.jar               inmemory-open-metadata-topic-connector-2.0-SNAPSHOT-jar-with-dependencies.jar       spring-rest-client-connector-2.0-SNAPSHOT-jar-with-dependencies.jar
cassandra-metadata-extractor-connector-2.0-SNAPSHOT-jar-with-dependencies.jar       inmemory-repository-connector-2.0-SNAPSHOT-jar-with-dependencies.jar                view-generator-connectors-2.0-SNAPSHOT-jar-with-dependencies.jar
cohort-registry-file-store-connector-2.0-SNAPSHOT-jar-with-dependencies.jar         kafka-open-metadata-topic-connector-2.0-SNAPSHOT-jar-with-dependencies.jar
configuration-encrypted-file-store-connector-2.0-SNAPSHOT-jar-with-dependencies.jar omrs-rest-repository-connector-2.0-SNAPSHOT-jar-with-dependencies.jar
```

Note that 350MB is consumed by these uber jars out of a distribution total of 680MB, so it is significant.

**Comment by planetf1** [comment]
See update to #2691 -- as the number of artifacts using this approach increases, the duplication escalates rapidly.

The change here can hopefully meet the immediate needs of #1607 to allow dynamic loading of connectors, but most likely we need to move to a smarter model in the 2.1/2.2 timeframe that keeps individual maven artifacts lean, but builds a complete distribution layout at assembly time

Alternatively we can defer PR #3171 until 2.1 and perform a more complete analysis & refactoring across all apps, tests, clients, utilties that takes account of the different use cases from 3rd party apps, to native egeria components, with consideration of both static and dynamic loading.
