### ISSUE TITLE
Subject area OMAS should use spring rest client connector

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#3112]
Subject area OMAS client is making use of restTemplate correctly in 'RestCaller.java'.

Instead SA omas should be brought inline with other OMASs and make use of our spring client reset connector (SpringRESTClientConnector.java)

Found in https://github.com/odpi/egeria/pull/3056 (and a workaround implemented) - note this workaround will need to be removed in a future PR

Update by David:
I have increased the scope of the issue as the change exposed some issues in Subject Area:
- the rest connector needed extending to handle calls (including put) that subject area makes 
- the code needed refactoring so that the client side extended the connector class. 
- as part of the change refactoring the code needed to handle PropertyServerExceptions
- I realised that the Exception messages were not being properly populated with their parameters. 
- I noticed that the update spring end point was not consistent for relationships, as it did not include the guid. This came to light while refactoring the client side code around the connectors. The lines updates now key off the guid in the url not the guid in the supplied Line .
- The FVT default port number and the Subject Area definition sample ports have changed to from 9444 to 9443.
- I made some improvements to the individual view admin services as I found errors as I tried to use them. This brings them more in line with the access services.

**Comment by immmus** [comment]
> Subject area OMAS client is making use of restTemplate correctly in 'RestCaller.java'.
> 
> Instead SA omas should be brought inline with other OMASs and make use of our spring client reset connector (SpringRESTClientConnector.java)
> 
> Found in #3056 (and a workaround implemented) - note this workaround will need to be removed in a future PR

Hi @planetf1 and @davidradl ! I can take this task to me and make these changes.

**Comment by davidradl** [comment]
@immmus Sorry I have almost completed these changes.

**Comment by immmus** [comment]
> @immmus Sorry I have almost completed these changes. Thank you very much for the offer.

Oh okay)), nothing wrong)

**Comment by davidradl** [comment]
@immmus I have identified #3156 and #3157 which you could work on if you would like to. Please update those issues if you want to do them and I will assign them to you.
