### ISSUE TITLE
Cannot resolve d3 when building presentation server

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#3131]
Can't resolve 'd3' in '/Users/davidradley/egeria/open-metadata-implementation/user-interfaces/presentation-server/nodejs/src/client/components/RepositoryExplorer/components/diagram'

**Comment by davidradl** [comment]
if I issue npm install d3 it gives errors - but seems to work after that

**Comment by grahamwallis** [comment]
Hi @davidradl @planetf1 - I was going to comment on the PR but switched to here as the PR is closed. For my development environment I used 'npm install d3' and was thinking that when we integrate the presentation-server into the Maven build we would do essentially the same, if a general 'npm install' does not spot the dependency (which I had assumed it would).

**Comment by planetf1** [comment]
I think it's fine to just have a working recipe for now. Perhaps if you could capture that in the README, it would be a good starting point for getting into a maven build. I could try and work with it to put something together...

Makes sense the big moving parts are in there, and you know how you will deploy it -- at least for now - ie is it a jar, a war etc? Or indeed multiple.

**Comment by davidradl** [comment]
@grahamwallis - I forgot the npm install trick. Thanks.

**Comment by davidradl** [comment]
closing as I think this is not an issue if you run npm install

**Comment by planetf1** [comment]
Sounds good - will verify for sure in #3098
