### ISSUE TITLE
Update Presentation server to use secure protocols

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#3135]
The code as is uses unsecured protocol. I will look to change this one the main change has gone in #1403 . @planetf1 @grahamwallis.

I intend to use this issue to introduce configuration into the presentation server. I notice that there is a webpage that details a way of doing this 
https://medium.com/@felipedutratine/manage-config-in-nodejs-to-get-variables-from-file-and-env-variables-87526509aad1

I am thinking that we could use a similar method, with: 
1) we store the config in the config folder where the presentation server runs.
2) Our config files would be named to include the serverName e.g. 
presentation.server.<server-name>.config
I assume we would need to do a 'require' with a wildcard in the code.
3) There would only be one file for a one server in the presentation server config folder . 
4) It would be possible to run a presentation server using environment variables
5) It would be possible to run a presentation server with server1 environment variables. It would also be possible to run a presentation server with server2 environment variables at the same time.
6) In order to allow  5) we would need to ensure there were no clashes or ports urls etc.  
7) For this initial check in all servers would authenticate using the same user store. 
8) for the environment variable I am envisaging at least:

egeria_presentation_server_name = aaaa.    // this is the server name to use      
egeria_presentation_server_remote_servername_for_aaaa = viewserver1 // remote servername
egeria_presentation_server_name_remote_url_root_for_aaaa = https://viewhostName:8443 //remote url
9) Currently the nodejs server code references a self-signed certificate from the file system. 
// ssl self signed certificate and key
var cert = fs.readFileSync(__dirname + '/../../ssl/keys/server.cert');
var key = fs.readFileSync(__dirname + '/../../ssl/keys/server.key');
I assume we should use the same certificate as the the rest of Egeria. This may involve build process copying the cert and key into the presentation server folder tree - so the existing logic could be used. 
10) I assume we would need an environment variable alternative to 9). 
11) We need to amend the express middleware passthrough of the rest calls to augment them with ssl, based on the environment variables.      

Is the above sufficient @planetf1 ? I am not sure whether this code needs to be aware of the trust store.

**Comment by planetf1** [comment]
self signed certs is something I'm working on currently as we have a few challenges. 

As you say, we should probably start by using a common cert - note that currently we have them stored in pkcs12 format, and they are configured by reference to the classpath. That could change, but I would consolidate to as few variations/copies as reasonable. At least by default. 

I would expect we'll so something similar to the way we use ./lib for adding connector classes - we might use ./etc/ssl or similar for the certs (and in this regard the current chassis and old UI would change to align). these would be put in place by the assembly.

I would say hold and we'll return to this once the base PR is integrated, and we have the build running. We may then need to come back again once other changes from the original secure issue are addressed.  There's still issues being worked through in the base PR that need addressing first.§

**Comment by davidradl** [comment]
I have the following design @planetf1 and @grahamwallis . Do you have any concerns are the next pr I hope to put in. 

1. An environment variable as follows needs to be set (the prefix is capitalised for windows that can care about mixed case) :
`EGERIA_PRESENTATIONSERVER_SERVER_aaa={"remoteServerName":"cocoMDSV1","remoteURL":"https://localhost:9443"}`

in this case a local presentation server named aaa will be configured to issue calls to a remove server called cocoMDSV1 using the root URL https://localhost:9443.

I like having one environment variable per server so we can verify it is consistent at the same time in the code. We can add other parameter to the json as required.  
2) The code looks for environment variables of this shape, that contain those properties.
3) When working in development it is possible to specify a .env file. that contains these environment variables. We .gitignore .env    
4) We supply a sample .env-sample that can be copied and renamed and values amended.
5) Not validating the certificate is a hard coded parameter on the rest invocations.
6) Nigel suggested having strictSSL=false or the like. We could specify that on a per servername basis. As we verify the certs properly then we could consider this.

**Comment by planetf1** [comment]
* That would seem to be fine for compose/k8s etc
* Keep any .env exclusion in .gitignore scoped - as we already use such a file in the docker compose module
* On 5/6 The not validating certificate will need to be parameterized ... but am still working on that in the base so fine to leave for now, and we can fix in a later PR

I think the key is let's do something that gives a chance of having a working stack in master, and then we can iterate through again on improving/fine tuning.

**Comment by grahamwallis** [comment]
I have a question - why is an environment variable necessary? (rather than doing the configuration in the P-S config).

**Comment by davidradl** [comment]
> I have a question - why is an environment variable necessary? (rather than doing the configuration in the P-S config).

@grahamwallis . On the OMAG servers there is the connector framework which allows configuration to occur to files or to non-files (cloud services do not have access to the file system). For nodejs the way to pass configuration seems to be using environment variables; this is the same for Tomcat UIs which use environment variables and has the application.properties file as a convenient file based way of setting them. Lack of a config file in production, also means we do not need to encrypt it as well! For the presentation server we are looking to add  per tenant minimal information to allow it to access the downstream server ; so we do not expect the configuration to be very large (end point identification and maybe additional pieces around security if we need to).

**Comment by grahamwallis** [comment]
@davidradl - Awesome - thanks!

**Comment by planetf1** [comment]
Environment variables are popular with docker/k8s too. 
We can secure content in 'secrets' and then expose either as an environment variable map, or file -- so with the implementation above we have both options :-)

**Comment by davidradl** [comment]
As this is  an issue that is high and for the next milestone; I think the presentation server is now using secure protocols. I will track further enhancements in other issues.

**Comment by planetf1** [comment]
Thanks - will drive any further changes from the work under #1403 for the 2.0 release
