### ISSUE TITLE
Subject Area term category and glossary apis should be able to take a project parameter 

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#3156]

**Comment by davidradl** [comment]
Hi @immmus , I wonder if you would like to do this this issue. I would like it if the subject area API for Term, Category and glossary (and their subtypes) could take an optional project summary attribute, in a similar way to the way we pass in an associated Glossary.  So for example Term would have an extra 
  private GlossarySummary glossary =null;
  private ProjectSummary project =null;

The glossary author view services would need to be updated in line with this. 

After this issue is in,  I will then enhance the presentation server to pass in a glossary project when I create Terms , Categories or Glossary.

**Comment by immmus** [comment]
> > Hi @immmus , I wonder if you would like to do this this issue. I would like it if the subject area API for Term, Category and glossary (and their subtypes) could take an optional project summary attribute, in a similar way to the way we pass in an associated Glossary. So for example Term would have an extra
> > private GlossarySummary glossary =null;
> > private ProjectSummary project =null;
> > The glossary author view services would need to be updated in line with this.
> > After this issue is in, I will then enhance the presentation server to pass in a glossary project when I create Terms , Categories or Glossary.
> > The server would then create the relationship to the project and the caller would not need to issue more than one api call.
> > The javadoc will need to updated as part of this change and appropriate new error messages be added and the FVT enhanced
> > Let me know and I will assign you the issue.
> 
> Hi @davidradl, I until I do not quite understand what exactly is meant by Project entities and how in general Term, Category and Glossary should interact with it :(

If you will tell me more details about this and I will understand I will try to do it with pleasure:)

**Comment by davidradl** [comment]
@immmus  Great:-) As background,  there is a user interface called the presentation server (written is javascript - you do not need to change this !). It calls Subject Area view services (OMVS) that calls subject Area Access services (OMAS). In the Ui we set a default glossary and a default project. 

At the moment when we create a Term we supply a Term object (you will have seen this in the code I think). the create Term supplies a json payload like this 
```
{
"name":"BBB2 Attr",
"description":"test term 2 ",
"spineAttribute": true,
"glossary":
	{

	"guid":"4491ee7e-da36-419f-8ba3-af7d87a04a73"
	}
}

```

I would like to extent the Term object so it could be created like this : 

```
{
"name":"BBB2 Attr",
"description":"test term 2 ",
"spineAttribute": true,
"glossary":
	{

	"guid":"4491ee7e-da36-419f-8ba3-af7d87a04a73"
	}
},
"project":
	{
	"guid":"4491ee7e-da36-419f-8ba3-af7da04a7344"
	}
}

```


you will notice that Term is defined like this 
```
public class Term extends GovernedNode implements Serializable {
    private static final Logger log = LoggerFactory.getLogger(Term.class);
    private static final String className = Term.class.getName();

    private String summary =null;
    private String abbreviation =null;
    private String examples =null;
    private String usage =null;

    private GlossarySummary glossary =null;

```
The ideas being that the caller only needs to issue one call (createTerm) rather than 2 (create term and create project scope relationship).
 
So we need to create a new class ProjectSummary (similar to GlossarySummary)
And Add this line to Term `ProjectSummary project=null;`

Be aware Terms have a subtype activity and Project has a sub type GlossaryProject - that the caller should be using.

In the same way we should add a ProjectSummary to Category and Glossary, and allow the containing entity to be updated / replaced with it. 

Does this make sense? I am hoping to make use of the this parameter in the UI.

Note that internally the project attribute in Term should be mapped to a ProjectScope relationship - which we you will need to create. See what we do for glossary in createTerm in SubjectAreaTermHandler. 

I am hoping to have this in place in the next couple of weeks is that going to be ok - if you do not have time - I can do it.

**Comment by immmus** [comment]
> @immmus Great:-) As background, there is a user interface called the presentation server (written is javascript - you do not need to change this !). It calls Subject Area view services (OMVS) that calls subject Area Access services (OMAS). In the Ui we set a default glossary and a default project.
> 
> At the moment when we create a Term we supply a Term object (you will have seen this in the code I think). the create Term supplies a json payload like this
> 
> ```
> {
> "name":"BBB2 Attr",
> "description":"test term 2 ",
> "spineAttribute": true,
> "glossary":
> 	{
> 
> 	"guid":"4491ee7e-da36-419f-8ba3-af7d87a04a73"
> 	}
> }
> ```
> 
> I would like to extent the Term object so it could be created like this :
> 
> ```
> {
> "name":"BBB2 Attr",
> "description":"test term 2 ",
> "spineAttribute": true,
> "glossary":
> 	{
> 
> 	"guid":"4491ee7e-da36-419f-8ba3-af7d87a04a73"
> 	}
> },
> "project":
> 	{
> 	"guid":"4491ee7e-da36-419f-8ba3-af7da04a7344"
> 	}
> }
> ```
> 
> you will notice that Term is defined like this
> 
> ```
> public class Term extends GovernedNode implements Serializable {
>     private static final Logger log = LoggerFactory.getLogger(Term.class);
>     private static final String className = Term.class.getName();
> 
>     private String summary =null;
>     private String abbreviation =null;
>     private String examples =null;
>     private String usage =null;
> 
>     private GlossarySummary glossary =null;
> ```
> 
> The ideas being that the caller only needs to issue one call (createTerm) rather than 2 (create term and create project scope relationship).
> 
> So we need to create a new class ProjectSummary (similar to GlossarySummary)
> And Add this line to Term `ProjectSummary project=null;`
> 
> Be aware Terms have a subtype activity and Project has a sub type GlossaryProject - that the caller should be using.
> 
> In the same way we should add a ProjectSummary to Category and Glossary, and allow the containing entity to be updated / replaced with it.
> 
> Does this make sense? I am hoping to make use of the this parameter in the UI.
> 
> Note that internally the project attribute in Term should be mapped to a ProjectScope relationship - which we you will need to create. See what we do for glossary in createTerm in SubjectAreaTermHandler.
> 
> I am hoping to have this in place in the next couple of weeks is that going to be ok - if you do not have time - I can do it.

Hi, now I'm doing other task, but I will try to do it. If I will have problems I will inform )
Just as I understand it, project should not be a mandatory parameter for creating entities, because not everyone needs it. Correctly?

**Comment by davidradl** [comment]
@immmus Yes - project is not mandatory parameter.
If we get a Term / category glossary and it has a project we should include it in the response

**Comment by immmus** [comment]
Hi @davidradl , while thinking over the best way to accomplish this, I wondered: "Do you need to check when creating the Term or Category the compliance of the Glossary project and the specified projects when creating the above entities?"

For example we can see below at slide that ParentCategory's glossary and ChildCategory's glossary are different. It's normal??
![Screenshot 2020-07-08 at 14 24 09](https://user-images.githubusercontent.com/35165540/86913812-d767a280-c127-11ea-884c-a9849f97d80b.jpeg)

**Comment by davidradl** [comment]
@immmus Sorry I have just spotted your question. A parent category does not need to be in the same glossary as the child category. We want it to be flexible. For example there may be a glossary with top level categories in and the glossaries per country that include country specific child categories. This will all depend on how an organization arranges its semantic data. Egeria has suggested using subject areas which is one way to arrange semantic information we think can be used effectively for governance. Also a term does not need to be in same glossary as the categories it belongs to.

**Comment by immmus** [comment]
> @immmus Sorry I have just spotted your question. A parent category does not need to be in the same glossary as the child category. We want it to be flexible. For example there may be a glossary with top level categories in and then have glossaries per country that include country specific child categories. This will all depend on how an organisation arranges its semantic data. Egeria has examples of using subject areas, which is one way to arrange semantic information we think can be used effectively for governance. Also a term does not need to be in same glossary as the categories it belongs to.

Okay. Thank you)
