### ISSUE TITLE
SubjectArea should default the qualifiedName if not specified

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#3157]
For the OMRS entities that the subject area creates, if the qualified name has not been specified then we should create one (as this property should be unique.

The property should default to the the omrs type name followed by a - followed by the guid. 
For example if we were creating a Glossary Term, it should return a on object with the qualifiedName set to "GlossaryTerm-<guid>"  where <guid> is the guid. 

The java doc should be updated in line with this change

**Comment by davidradl** [comment]
@immmus do you fancy doing this issue? If so I will assign to you

**Comment by mandy-chessell** [comment]
The GUID is not a good qualified name - it needs to be something meaningful to the external users so there is a chance of them finding it later (most find requests will be via the qualifiedName).  

I would suggest that specifying the qualified name is mandatory on the access service.  The UI could generate a candidate qualified name if necesary - but ultimately it has to be at least partially human readable.

**Comment by immmus** [comment]
Yes, I can take this task. But if I know how to do variant proposed by @davidradl, that variant proposed by @mandy-chessell involves the introduction of a required parameter in the form of qualifiedName, which entails backward compatibility problems because before this was not required.
Let's think about how we can solve this problem)
How do we ensure that the user creates a unique qualifiedName for each object?

**Comment by immmus** [comment]
It is also unclear how we can fill the already created entities with qualifiedName if this has not been done before. Even if later we will create this default property...

**Comment by davidradl** [comment]
@immmus Let's hold off on implementing on this one until we have agreement on the designs. fyi you can amend the qualified name after creation using an update. The subject Area OMAS API has not been "released" yet - it is in development as documented in the banner [banner](https://github.com/odpi/egeria/blob/master/open-metadata-implementation/access-services/subject-area/README.md) so we can change the API. Once we put Subject Area OMAS  in Released status then we would need to be concerned with backwards compatibility and versioning in.

**Comment by immmus** [comment]
> @immmus Let's hold off on implementing on this one until we have agreement on the designs. fyi you can amend the qualified name after creation using an update. The subject Area OMAS API has not been "released" yet - it is in development as documented in the [Subject Area Readme](https://github.com/odpi/egeria/blob/master/open-metadata-implementation/access-services/subject-area/README.md) banner, so we can change the API. Once we put Subject Area OMAS in Released status then we would need to be concerned with backwards compatibility and versioning in.

I get it. So the question of backward compatibility has disappeared. Then you need to think about how best to implement this.
In this case, we have to go in the path of the atlas, in which when creating an entity if `qualifiedName == null`, then `name (displayName) + guid `is set. What do you think?

**Comment by davidradl** [comment]
@immmus I am talking with @mandy-chessell about this. The problem with (displayName) + guid would be when the display name was renamed - it would get out of sync; we would not want to force them to be in sync incase that is not intended.  We are hoping the qualified name is a unique readable name. Appending with the type name means that we have a unique name without the possibility of getting out of sync with the display name. The other option is to mandate this field on everything we create - as Mandy suggests. We do not want the API to police the uniqueness; including the guid in the name means it is readable but likely unique.

**Comment by immmus** [comment]
> @immmus I am talking with @mandy-chessell about this. The problem with (displayName) + guid would be when the display name was renamed - it would get out of sync; we would not want to force them to be in sync incase that is not intended. We are hoping the qualified name is a unique readable name. Appending with the type name means that we have a unique name without the possibility of getting out of sync with the display name. The other option is to mandate this field on everything we create - as Mandy suggests. We do not want the API to police the uniqueness; including the guid in the name means it is readable but likely unique.

Okay)

**Comment by davidradl** [comment]
Hi @immmus,
@mandy-chessell  and I have decided that a more readable qualified name is preferable than including guid. to this end  we are suggesting that for create requests when the qualified name is not set:
1) For Glossaries the display name should be used as the default (we expect Glossary names to be unique).
2) For Projects the display name should be used as the default 
3) For Terms default <glossary qualified name >.< term display name >
4) For Categories default <glossary qualified name >.< category display name >  

The user (glossary author) then needs to manage renames themselves.
Prior to setting the qualified name in the entity, we should search for that name to see if it exists first, so we do not knowingly create a duplicate. So it you have a term with display name Person under the same glossary, the first duplicate would have display name person, qualified name  <glossary qualified name >.person-2, then qualified name <glossary qualified name >.person-3 etc. I suggest adding junits around this logic in the code. 

If qualified name <glossary qualified name >.person-1 gets deleted and <glossary qualified name >.person-2 exists, and we get a create for person, then we create qualified name <glossary qualified name >.person-3

**Comment by immmus** [comment]
> Hi @immmus,
> @mandy-chessell and I have decided that a more readable qualified name is preferable than including guid. to this end we are suggesting that for create requests when the qualified name is not set:
> 
> 1. For Glossaries the display name should be used as the default (we expect Glossary names to be unique).
> 2. For Projects the display name should be used as the default
> 3. For Terms default .< term display name >
> 4. For Categories default .< category display name >
> 
> The user (glossary author) then needs to manage renames themselves.
> Prior to setting the qualified name in the entity, we should search for that name to see if it exists first, so we do not knowingly create a duplicate. So it you have a term with display name Person under the same glossary, the first duplicate would have display name person, qualified name .person-2, then qualified name .person-3 etc. I suggest adding junits around this logic in the code.
> 
> If qualified name .person-1 gets deleted and .person-2 exists, and we get a create for person, then we create qualified name .person-3

Hey. But is it normal for us to create several terms with one display name in one glossary?
With the addition of junits I completely agree)

**Comment by grahamwallis** [comment]
I don't know if it helps but RepositoryExplorer uses the following strategy to pick a label for display purposes. This is all at the OMRS level so it is dealing with a broad range of types. 
In the following order of priority:
1. If set use displayName
2. Else if set use name
3. Else if set use qualifiedName (truncating and keeping the last part it if it is very long)
4. Finally if all else failed, use the guid.

The above is the general strategy, there are more specific attributes chosen for specific super-types (e.g. any subtype of InformalTag uses the tagName, any sub-type of DataField uses dataFieldName).

If it helps in this situation, the code can be found in the chooseLabelForEntity method.

**Comment by davidradl** [comment]
@immmus let me know if you have any questions. We are contactable on slack on the ODPi channel

**Comment by immmus** [comment]
> @immmus let me know if you have any questions. We are contactable on slack on the ODPi channel

 While everything is clear. If anything I'm in touch :)
