### ISSUE TITLE
discovery service connectors - consider refactoring (splitting up)

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#3170]
In #3101 we 
 a) built all connectors with dependencies
 b) Added all connectors to server/lib in our assembly

I noticed in this process that the discovery service connectors are bundled all together in a single jar

Where a connector has different dependencies, or may be used selectively, it should be in it's own artifact, not added to a single jar.

For now we can consider this module as a 'discovery service connector multipack' :-) but as/if it grows, splitting up is probably appropriate

See also the discussion in #3101 in terms of how we ensure dependencies are met.

Will not target this for 2.0

**Comment by mandy-chessell** [comment]
They don't have different dependencies - only Java implementation - and we load them as a set of services for a discovery engine.

**Comment by planetf1** [comment]
I agree that at the moment we really have a single coherent set of services.

However what got me thinking was that one of these is for CSVs, which then has a static dependency on the CSV file store connector. This is a fairly simple case. We may do the same for avro, which will pull in more.

But then we go off to hadoop, or cassandra -- they are quite distinct discovery services and I would have thought we might load them individually -- similar to the other connectors?

**Comment by mandy-chessell** [comment]
yes - interesting point - agreed - they will always pull in the base connector for the technology they are working with

**Comment by mandy-chessell** [comment]
Given the discovery connectors we have at the moement I do not think there is any need to make a change now - but if we build discovery connectos that are based around different technologies then they should be separate.
