### ISSUE TITLE
Kafka version inconsistencies & backlevel

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#320]
In the top level pom.xml kafka.version is set to 0.10.0.0
For the virtualizer in kafka is set to 1.0.0, as it is in the igc repository connector

2.12 was July 2018 as was 1.1.1. 1.0.0 was sep 2017 & 0.10.0.0 was May 2016

ideally we should set a single version in the top level, and use this consistently throughout
We also need to decide which version to go with. If not the latest, why not, and which.

**Comment by planetf1** [comment]
As of 20190222 I am still seeing the connector using 0.10.0.0 - and am seeing some kafka instabilities

Current kafka stable is 2.1.1 whilst 0.10.0.0 was released May 2016

Such a wide client/server difference may be causing these issues - hard to verify without trying, but in any case we should consider keeping kafka far more current.

cc: @cmgrote @mandy-chessell @grahamwallis

**Comment by planetf1** [comment]
i would also recommend using <DependencyManagement> rather than a property

**Comment by mandy-chessell** [comment]
Got for the latest release ...

**Comment by planetf1** [comment]
Kafka updated to 2.1.1 (current) as above
Kafka property removed
Added <DependencyManagement> section for kafka (v2.1.1)
Reference to version under <Dependency> removed in 3 poms (including top level)
Rebuilt
Launched egeria, joined cohort, verified kafka initialization and tx/rx
Looks ok.
