### ISSUE TITLE
bug in information lab glossaryId not defined

### ISSUE THREAD

**Issue by geoHeil** [odpi/egeria#3203]
The lab https://github.com/odpi/egeria/blob/master/open-metadata-resources/open-metadata-labs/information-architecture/working-with-standard-models.ipynb

in this line:

```
response = requests.get(getGlossaryMoreInfoURLRoot + glossaryId + getGlossaryMoreInfoURLTail)

```

fails to execute as the `glossaryId` is not defined.

At least for me:
```
No glossaries loaded 
Response was:
{
    "class": "GlossaryViewEntityDetailResponse",
    "relatedHTTPCode": 200,
    "result": []
}
```

is the output of the previous cell

**Comment by planetf1** [comment]
very similar to #2278 which we hope to fix soon (ie this release or next)

**Comment by planetf1** [comment]
closing as we'll cover this in #2278
