### ISSUE TITLE
Multiple SLF bindings reported in server chassis

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#3204]
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/egeria/server/lib/graph-repository-connector-2.0-SNAPSHOT-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/egeria/server/lib/open-lineage-janus-connector-2.0-SNAPSHOT-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/egeria/server/server-chassis-spring-2.0-SNAPSHOT.jar!/BOOT-INF/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
```

The graph repository connector and open lineage connector should NOT be including an slf4j binding. This should only be brought in by the platform/utilities/applications.

Relatively harmless in terms of function, but those two connectors need fixing to remove their chosen implementation. It may be that the bindings are being pulled in by dependencies - indeed likely given what change caused this to surface. We will likely need an exclusion of the loaded dependencies.

Introduced by #3101

**Comment by grahamwallis** [comment]
It sounds like these two (graph) connectors are pulling in SLF4J via their dependency on JanusGraph? I took a quick look at the graph-repo-connector POM but it seems to be only specifying a dependency in the same way that other Egeria modules do. What change do we need to make to avoid this more direct dependency? Is it something in the connector module's POM or do we need to do an exclude as we pull in JG for example?

**Comment by planetf1** [comment]
org.odpi.egeria:graph-repository-connector:jar pulls in
```
 [INFO] org.odpi.egeria:graph-repository-connector:jar:2.0-SNAPSHOT
 [INFO] +- org.janusgraph:janusgraph-cassandra:jar:0.5.2:runtime
 [INFO] |  +- io.dropwizard.metrics:metrics-jvm:jar:3.2.2:runtime
 [INFO] |  +- ch.qos.logback:logback-classic:jar:1.2.3:compile
 [INFO] |  |  \- ch.qos.logback:logback-core:jar:1.2.3:compile
```
which is the likely cause since logback is a typical implementation for slf4j. Whilst slf44-simple is included, it is only for test

Currently looking into it

**Comment by planetf1** [comment]
PR opened with fix

The principle I'm following is that in so far as is possible, the binding of any logging implementation for slf4j should be done at the last point (ideally completely at runtime). This means when we ship jars - with or without dependencies - they should not include a logging implementation if they are libraries (which most are) . Only if they are executable (ie server chassis, UI, samples, utilities)

There's a reference to this here: http://www.slf4j.org/faq.html#configure_logging although it's not detailed enough. There are some reports of issues hitting the multiple slf warning when using Janusgraph. In my view JG should NOT be including a logging implementation as a dependency if the intent of slf4j is to be realised.
