### ISSUE TITLE
Make Virtualizer log messages more user-oriented

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#321]
As per review https://github.com/odpi/egeria/pull/316/files/82ba80a5aa4332258e692596e3816de66794012a#diff-456f9029498cc094a86a8b1fb3918d97 -- many of these error messages are coded for the developer - understandable to begin with, but perhaps we should return in a later reiteration to redo the text as more user-centric? This might include being more specific about what access, what database, which user etc. Some will remain as 'internal' issues which require code changes - and for those we may want to use the text we have in other exceptions about raising a github issue.

**Comment by innerTide** [comment]
Hi @planetf1 , the new version of virtualizer also provides up-to-standard audit log, which offers more detailed information on exceptions. This issue can also be closed.

**Comment by planetf1** [comment]
closing
