### ISSUE TITLE
Reversion of config file store connector

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#3237]
In the Admin Guide, we describe the process for removing the configured configuration document store connector, by using the DELETE method against {serverURLRoot}/open-metadata/admin-services/users/{adminUserId}/stores/connection

The guide states that this "reverts the store to the default clear text JSON file store" but presumably we actually revert to using the default encrypted JSON file store.

**Comment by cmgrote** [comment]
Good spot — I think there was one other documentation area I hadn’t seen that I also updated, so can include the wording change here in the same PR.  Can you point me to the specific file, just to be sure?

**Comment by grahamwallis** [comment]
HI @cmgrote - sure it is in .../admin-services/docs/user/configuring-the-configuration-document-store.md
