### ISSUE TITLE
Remote retrieval of metadata collectionId for each cohort member for each federated request

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#3300]
The enterprise connector extracts the metadata collection id for each cohort member during a federated query to support audit messages and exceptions.  This is typically retrieving the value stored locally in the superclass and so has limited performance overhead.

However, the OMRSRESTMetadataCollection, used to issue requests to remote cohort members, has overridden this getMetadataCollectionId method.  It retrieves the value from the remote connector and compares it with the local to make sure it is still connected to the correct remote repository.  Its a useful sanity check, but means that we effectively make an additional remote request to each remote cohort member during a federated query.

I have changed the getMetadataCollectionId method in the OMRSRESTMetadataCollection so it only checks the remote's metadata collection id once and then caches it.  This means we have the validation - but only do it once.  It is not quite as safe (for example, the remote's metadata collection id changes then it will not be noticed immediately) however since it halves the remote calls we make during federated queries, it is worth doing.

**Comment by grahamwallis** [comment]
@mandy-chessell - Would it be worth periodically refreshing the id? e.g. on a time-basis, if the cached id is aged it could be automatically re-queried on a subsequent (federated) query?
