### ISSUE TITLE
Subject Area API subtle change in delete processing after big refactor

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#3302]
Prior to the big refactor a delete of a term in the FVT was interpreted as a a soft delete, the response contained the deleted Term (and I assume the other nodes)  
After the refactor the delete term does not contain the deleted term. 

The API needs to be re instated and the FVTs amended to test this, the glossary author view service needs amending as well

**Comment by davidradl** [comment]
@immmus is this something you want to look at?

**Comment by immmus** [comment]
@davidradl Hi, after refactoring, the removal is still soft. There is no remote term in the answer just for the reason that the remove method in RepositoryHadler is void. But the deleteEntity method from OMRSMetadataCollection is still used. And before they sent it, I scratched it all out, the method did not change in any way.

**Comment by immmus** [comment]
@planetf1 @davidradl  I've just ran test and we are can see the results. All test's without errors.
<img width="1341" alt="Screenshot 2020-07-07 at 11 17 21" src="https://user-images.githubusercontent.com/35165540/86746222-94340380-c043-11ea-90c5-08ebf73bfb5d.png">

https://gist.github.com/immmus/e87b80b697e4208a9aa9779fecf8260b

And can see soft deleted.
<img width="1198" alt="Screenshot 2020-07-07 at 10 43 25" src="https://user-images.githubusercontent.com/35165540/86741687-3fdb5480-c040-11ea-9e7d-a46cd1ca8625.png">

The problem most likely is that by running tests from different methods, they run in parallel and therefore we always get different search results.

**Comment by immmus** [comment]
@planetf1 @davidradl 
In this form, tests pass in parallel.

<img width="1271" alt="Screenshot 2020-07-07 at 11 50 09" src="https://user-images.githubusercontent.com/35165540/86752799-4a015100-c048-11ea-9e02-eb76fd6dd383.png">

It's results:
https://gist.github.com/immmus/fbfc75da6a5bfd44a8c53a977ab506f9

In the future, there is an intersection of the logic of tests! As can be seen on the next slide.
<img width="1044" alt="Screenshot 2020-07-07 at 11 53 34" src="https://user-images.githubusercontent.com/35165540/86753218-977dbe00-c048-11ea-8a5c-c15cfb4e4a87.png">

So friends, let's objectively look at the situation and not come up with theories about some kind of regressions. In this case, the problem is that the logic of the tests is not isolated from each other and when they are run in parallel, they simply break.

**Comment by immmus** [comment]
Here are some more screenshots that I missed.

![Screenshot 2020-07-07 at 13 27 26](https://user-images.githubusercontent.com/35165540/86769678-2f36d880-c058-11ea-8d17-862989192092.jpeg)
![Screenshot 2020-07-07 at 13 27 40](https://user-images.githubusercontent.com/35165540/86769685-30680580-c058-11ea-8cca-31bd333c7047.jpeg)
![Screenshot 2020-07-07 at 13 26 51](https://user-images.githubusercontent.com/35165540/86769688-31993280-c058-11ea-8bee-d51bf41a0209.jpeg)

**Comment by davidradl** [comment]
@immmus I have a look further into this; it is more subtle than I originally thought. 

- subject area api has 2 delete APIs for entities and relationships. One for soft and one for hard.
- the big refactor change the implementation to use the repository handler removeIsolatedEntity; which issues a deleteEntity, which is escalated to a purge - so does not ever return Function not supported as it did before the big change. 
- I agree it is better to be using the repository handler, but this means that we need to remove the purges of nodes and relationships. I think we can keep restores.    
- I have been talking with @mandy-chessell, she is making changes to the repositoryHandler to have it check the providence. The repository handler will be enhanced to only allowed through API calls that target non external repositories.
- Because of the last point. Mandy suggests that subject area  use the repository handler removeEntity rather than removeIsolatedEntity - this will check provenance when her change goes in.

**Comment by immmus** [comment]
> @immmus I have a look further into this; it is more subtle than I originally thought.
> 
> * subject area api has 2 delete APIs for entities and relationships. One for soft and one for hard.
> * the big refactor change the implementation to use the repository handler removeIsolatedEntity; which issues a deleteEntity, which is escalated to a purge - so does not ever return Function not supported as it did before the big change.
> * I agree it is better to be using the repository handler, but this means that we need to remove the purges of nodes and relationships. I think we can keep restores.
> * I have been talking with @mandy-chessell, she is making changes to the repositoryHandler to have it check the providence. The repository handler will be enhanced to only allowed through API calls that target non external repositories.
> * Because of the last point. Mandy suggests that subject area  use the repository handler removeEntity rather than removeIsolatedEntity - this will check provenance when her change goes in.

The difference between removeEntity and removeIsolatedEntity is that it checks Properties, but then calls removeIsolatedEntity anyway. Or mb, I don’t understand something?
<img width="1138" alt="Screenshot 2020-07-07 at 15 01 46" src="https://user-images.githubusercontent.com/35165540/86778853-87bfa300-c063-11ea-8bd0-7f82c3d9c582.png">

**Comment by davidradl** [comment]
@immmus yes you are right, but Mandy is making a change to the implementation of these methods (not yet in master) that means we should use removeEntity. So when her changes go in - it will work as expected.

**Comment by davidradl** [comment]
I see 
<img width="754" alt="Screenshot 2020-07-07 at 14 07 19" src="https://user-images.githubusercontent.com/39792797/86785972-488d5400-c05b-11ea-9386-690d8466f372.png">

and
<img width="863" alt="Screenshot 2020-07-07 at 14 07 39" src="https://user-images.githubusercontent.com/39792797/86786019-5a6ef700-c05b-11ea-9bac-7ac0431da5b7.png">

**Comment by davidradl** [comment]
@immmus So removeEntity calls removeIsolatedEntity which calls deleteEntity which if it fails calls purgeEntity. I suggest you do not touch this code, Mandy is updating this code to cope with provenance.

**Comment by immmus** [comment]
> @immmus So removeEntity calls removeIsolatedEntity which calls deleteEntity which if it fails calls purgeEntity. I suggest you do not touch this code, Mandy is updating this code to cope with provenance.

Yes I understood it. Let's to wait when @mandy-chessell will make a changes and we will make ours. Okay?

**Comment by davidradl** [comment]
Okay.

**Comment by immmus** [comment]
> Okay.

Thank you:)
