### ISSUE TITLE
Fix automated FVTs for Subject Area

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#3304]
In #3297 a PR was developed that automated the subject area tests.

However 9d17cbd9e4c35329892bf034fb5ac24e0bb42e44 appears to have broken some tests when run under the failsafe/JUnit framework . In the PR above two tests were disabled - Category & Term. This needs further investigation and resolution. See the PR for a more extensive discussion on the issues noted.

In addition the FVTs could be tidied up
 * Use of hardcoded strings duplicated in the test classes should be replaced by the use of java properties from failsafe. A subsequent FVT set will likely adopt this approach
 * The tests could be refactored to be more JUnit centric - finer grained tests

**Comment by planetf1** [comment]
Note also EffectiveDates needs FVT adding (none was added as it's a slightly different pattern to the other tests )

**Comment by planetf1** [comment]
See also #3302

**Comment by davidradl** [comment]
@planetf1 are we ok to close this one ? Or do you want to leave it open to track the other potential improvements we could make.

**Comment by planetf1** [comment]
I think we're good to close this one.

#426 is open with some general notes on fvt testing (which might improve cross-component -- for example ensuring we capture jacoco coverage data)- we'll learn more implementing on another component. So I'll handle it via that issue
