### ISSUE TITLE
Investigate alternative ways of packaging server-chassis spring application

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#3352]
Currently we build a spring boot application for the server chassis which includes many dependencies. This covers our optional connectors, but also all our core server capability. As part of the build of the server chassis we then use the spring boot plugin to build a fat jar so that the app can be launched in one step.

Since the component scan occurs at runtime we could potentially just build the core spring application, and then through our packaging/assembly ensure that the relevant capability is included on the classpath.

We also may want to consider what it means to deploy the chassis to a different app server other than tomcat

Raising this issue as a placeholder to look into best practice for springboot in complex dynamic environments.

**Comment by immmus** [comment]
Deploy the chassis to a different app server other than tomcat. Spring supports fairly easy integration with other app. For example netty, jetty.

**Comment by planetf1** [comment]
This is closely related to the discussion on assemblies, since we are basically creating a recipe of

* an empty 'chassis' to carry our useful components
* We add in runtime dependencies for the core server function
* we package as a spring boot app
//
later
//
* we build optional connectors
* we add these into an assembly (with or without dependencies)
* we add the chassis into the assembly
* we expect users to run from there.

But maybe we're missing a trick in that spring is already focussed on dynamic loading, so for the server perhaps the 'assembly' to get as far as building a war or similar is actually the server chassis build..

needs thinking through so will look at alongside

**Comment by planetf1** [comment]
I haven't seen any specific requirements for this, and don't forsee we'll persue until that point. More likely we might look at eclipse microprofile as an alternative way of hosting our rest services (in addition to spring).
