### ISSUE TITLE
Update type definition to allow specification of allowable provenance types

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#3361]
Egeria supports the following types of metadata provenance. 

![metadata-provenance-diagram](https://user-images.githubusercontent.com/12354195/87939866-9ad56880-ca90-11ea-8831-98236fcbe270.png)

This is the definition of the provenance types from the code:

```
    UNKNOWN                 (0, "<Unknown>",               "Unknown provenance"),
    LOCAL_COHORT            (1, "Local to cohort",         "The instance is being maintained within one of the local cohort members. " +
                                                                          "The metadata collection id is for one of the repositories in the cohort. " +
                                                                          "This metadata collection id identifies the home repository for this element. "),
    EXPORT_ARCHIVE          (2, "Export Archive",          "The instance was created from an export archive. " +
                                                                          "The metadata collection id for the element is the metadata collection id of the originating server. " +
                                                                          "If the originating server later joins the cohort with the same metadata collection Id " +
                                                                          "then these elements will be refreshed from the originating server's current repository."),
    CONTENT_PACK            (3, "Content Pack",            "The instance comes from an open metadata content pack. " +
                                                                          "The metadata collection id of the elements is set to the GUID of the pack."),
    DEREGISTERED_REPOSITORY (4, "Deregistered Repository", "The instance comes from a metadata repository that " +
                                                                          "used to be a member of the one of the local repository's cohorts but it has been deregistered. " +
                                                                          "The metadata collection id remains the same. If the repository rejoins the cohort " +
                                                                          "then these elements can be refreshed from the rejoining repository."),
    CONFIGURATION           (5, "Configuration",           "The instance is part of a service's configuration.  The metadata collection id is null."),
    EXTERNAL_SOURCE         (6, "External Source",         "The instance is maintained by an external technology.  The metadata collection id is the guid of the technology's descriptive entity.");

```
Some of the OMAS APIs support both LOCAL_COHORT and EXTERNAL_SOURCE provenance options.

What is emerging is the realization that some types of metadata should not be introduced into the open metadata ecosystem with particular provenance (such as EXTERNAL_SOURCE) because it limits the choices an organization can make on how they govern their resources.  EXTERNAL_SOURCE provenance should only be used where the technology that is providing the metadata is the only valid source for it.  For example, a database server is the only valid source for the schema of a database.  Any metadata representation of the database schema that is different from the definition in the database server is wrong.  This means that forcing all updates to the database schema to come from the same source makes sense.  However, AssetZoneMembership is a classification that should not be defined with EXTERNAL_SOURCE provenance because it needs to be updated by many different processes during the lifetime of the asset.

The rules for restricting the different provenance valued for each of the open types are being encoded in the OMAS implementations.  In the community call last week we decided it would be better to encode this knowledge in the type definitions.  This issue is to agree how this should be done and to document the updates to Egeria.

----
Implementation suggestions:

* The TypeDef could be updated with a boolean to say whether the EXTERNAL_SOURCE provenance is allowed or not.
       * The default would be FALSE. 

* Alternatively, the TypeDef could be updated with a list of allowed provenance types.
        * The default would be [LOCAL_COHORT, EXPORT_ARCHIVE, CONTENT_PACK, DEREGISTERED_REPOSITORY, CONFIGURATION].
        * A null value would also be interpreted as being set to the default value.

* Alteratively, the TypeDef could be updated with a list of forbidden provenance types.
        * The default would be [EXTERNAL_SOURCE] and again, the null value would be the same as the default value

The boolean is easy to implement but will not cover the circumstances where we want to restrict other types of provenance.  The lists allow other restrictions to be included.  The choice depends on what the default behaviour should be if a new type of proveance was added - should it be allowed by default or restricted by default?

Looking for other suggestions, votes and recommendations.

**Comment by grahamwallis** [comment]
I would vote for the second option - as I think it should scale better than option 1 if further provenance types need to be policed. I prefer it to option 3 as I think it is clearer.

**Comment by mandy-chessell** [comment]
Decision of community call 31st July was to use the boolean option as it is the simplest and we can change it if future requirements come along.  The advantage of this apporach is that it ties very nicely to the OMRSRepositoryConnector AP
I that has special add methods for external instances.  The effect of this boolean would be to disable these methods for the type.

Meeting attendees also reminded us that new policing also needs to be added to the rehome methods and it would be good to have new comformance tests for this value.

Current view on which types to allows external instances of are all types of assets, all types of schema element and the relationships between them.

These types will be updated explicitly - there is no thought to having this capability inherited through the type hierarchy.
However, there will be a check in the archive builder that once external instances are permitted, it is not possible to add a subtype that does not allow externla instances.

**Comment by mandy-chessell** [comment]
This is still needed
