### ISSUE TITLE
Kafka logging at Egeria startup 

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#337]
When starting Egeria as per #336, there is a lot of Kafka logging produced.  By default we should not display this logging. This defect is to change the logging settings (log4j) so that this logging is not produced. Assigning to Chris as discussed with him

**Comment by planetf1** [comment]
See also #180

**Comment by cmgrote** [comment]
I think this is now resolved -- the logging appears if you enable `DEBUG` level, but otherwise not (?)  Can this be closed?
