### ISSUE TITLE
Follow on Server author considerations

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#3383]
It would be good to have info icons next to each field pointing into the Egeria website for the definitions
Local URL root, I suggest defaulting to the standard non-Docker one https://localhost:9443 would be better.
I am thinking local server type would be a dropdown.
E.g., does not need the last comma. In fact I am not sure I would put e.g. I have seen the label repeated here; I think that makes more sense.
It would be good if the wizard widget was at the top or it can scroll off the bottom
The current content is Just over a page - so I had to scroll. It would be better to have the basic content show in a page.
Instead of first step , second step, third step, I suggest basic , advanced, preview . The text underneath can be more detail.
I suggest setting the organisation name up front (prior to the wizard) so all server definitions use it. This ui would be setting up servers for an organisation. We may want to extend the env to supply this so the ui does not need to enter it.
If I fill in all the fields and press the button is hangs if you put in an invalid server name . Is that was you expect at this stage?
on the second page, the big forward and back buttons look strange. Maybe if they were not primary buttons and were arranged next to each other. I would have hoped for smaller buttons maybe with > and <. It would also be good to be able to navigate back by pressing the radio button on the wizard widget.
on the second screen, the access servers all need to be listed. Maybe 2 radio buttons , with all access services and choose access services.
It hung trying to get to the third screen.
It did create the config file for the new server on the view server :-) and the content looked as expected.
I did see some network errors in the log

Errors I see in the network errors in the log:

@dkneisly I have been talking with @planetf1 another maintainer. We suggest : Platform URL root instead of local URL root. We also think we should remove local from all the fields in the UI - we don't think that word helps. We could have Server Userid and Server password. The server userid would be that of the Server not GaryGeeke.

**Comment by planetf1** [comment]
Do we need the platform URL at all? -- at least eventually (even if we do right now). Since we're already adding configuration in the view service @grahamwallis is using to have logical names/permitted set of platforms (and in that case servers) wouldn't we do the same with platforms here? 

Though it does depend on the definition of 'server author' since someone has to configure that permitted set in the view server? (apologies, not entirely familar with the overall use case)

**Comment by davidradl** [comment]
Some more feedback:
The serverURL root is only used for metadata repositories not all server types.  Need to think about the setting of the eventBusConfig since that is needed for cohort members. 
The server type should not be there any more - and the server category should be a dropdown to select since it will determine what is shown on the next screen

**Comment by davidradl** [comment]
@planetf1 Good point. Phase 1 of the config UI is issuing admin commands to the platform that the view server is running. So for phase 1 we need it. Phase 2 is to  have the admin calls coming into a view service. I think this is a phase 2 consideration, when we could adopt the approach that @grahamwallis is trail blazing. It is also a value add for using a view service. Phase 2, there is potentially a bootstrap issue that we cannot use this Ui to configure the view service that it needs.

**Comment by planetf1** [comment]
I think it's fine to come back in phase 2... but does bring up the fact we need to consider that initial bootstrap. What are the defaults, and what can be pre-configured ie through properties/parameters be it to the jar or a container -- this will also be quite interesting in the operator model on k8s where the operator will actually launch the platform entirely, and again will need to be able to configure as needed (it can use the admin services also)
