### ISSUE TITLE
change folder names in a subject area from Relationships to Lines

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#3384]
change folder names in a subject area from Relationships to Lines

**Comment by davidradl** [comment]
@immmus is this something you would like to do?

**Comment by immmus** [comment]
Hi @davidradl I really don't quite understand why this us.

**Comment by davidradl** [comment]
@immmus I was thinking that in line with you https://github.com/odpi/egeria/pull/3367 change, which is changing the objects to nodes in the folder / package name, we could change the folder package name from relationships to lines, as all the classes in this package inherit from class Line. Am I making sense - or do you think I have missed something?

**Comment by immmus** [comment]
> @immmus I was thinking that in line with you #3367 change, which is changing the objects to nodes in the folder / package name, we could change the folder package name from relationships to lines, as all the classes in this package inherit from class Line. Am I making sense - or do you think I have missed something?

In this case the SubjectAreaRelationshipClient and etc are a client for SubjectAreaRelationshipRESTResource. So I would not rename it.
