### ISSUE TITLE
Provide a meaningful error when the view server fails to connect to the downstream server

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#3387]
I found this testing Glossary author, if the view server does not find the downstream server, then I would want to see some error relating to Not connected - similar to if the view server was not contactable.  
The scope of this change is to change the view sever and ensure that the glossary author displays the appropriate error in this case.

**Comment by mandy-chessell** [comment]
I believe should be the view service's reponsibility to handle this case - not the view server?
