### ISSUE TITLE
REX feedback / suggestions

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#3394]
After quickly playing around with REX (Repository Explorer) UI, a few usability comments / suggestions (most hopefully minor):

- [ ] Currently the "search" input takes any input: the help suggests that it _can_ (but not must) be a regular expression.  For repositories with limited support for regular expressions, it _must_ be a regular expression or it will likely result in a `FunctionNotSupportedException` that is thrown back to the UI (and which currently is not reported anywhere in the UI: only that no results were found).  I think we therefore need to take one of two approaches: 1) actually report back as part of the "no results found" dialogue that a FNS exception was hit (and include its details, which would suggest to a user that a regular expression is needed), or 2) add a tickbox (ticked by default?) that auto-translates any input into the search into a "contains" query (wraps it using the helper method before passing it on to repositories), or 3) use a drop-down that shows all the helpers as options (contains, exact, starts with, ends with) and allow a user to select one of these rather than needing to know how to type the equivalent regular expression (and based on a selection of one of these, again maybe defaulting to "contains", have the UI call the appropriate wrapper method before passing the query on to the underlying repository).
- [ ] Currently the help dialogue does not show the `\` on the quoting: it gives an example of `Qany.characters.you.like!E.*` rather than `\Qany.characters.you.like!\E.*`
- [ ] Is the "Repository Server" config necessary via the UI? I was assuming this (or at least a default) could be picked up from a properties or somewhere similar, presumably that's what the asset search is doing (?) Fine to have an override, but would be nice to have one load-up-able by default -- in either case, the override would ideally be a panel that can be hidden to save screen real estate (+ what's there being vertically narrowed: lots of empty space around it at the moment).  (Note that this becomes particularly frustrating as tokens expire and you're forced to login again, you have to continually re-enter this configuration again in the UI).
- [ ] Probably more of a question for the overall UI framework, but the multiple scrollbars that are embedded in various parts of the page quickly become a minor nuisance to navigation when everything doesn't fit without needing to scroll

**Comment by grahamwallis** [comment]
@cmgrote - Thanks for the feedback and the good suggestions. I'm assuming you were using the view-service/presentation-server version of Rex, so please correct me if that is wrong.

The "Repository Server" config step will be replaced by a simpler operation where the view service provides the browser with the names of repository servers that the user can select, and the endpoint information (which is configured at the view service) will resolve the actual endpoint and make the necessary connections. That's how the new (not yet pushed) adminUI works and I intend to roll it out over the Tex and Rex view services. That does not include the 'ui-chassis' implementations (of Rex and Tex) but I will talk to @bogdan about whether/how to make a similar change there.

Your search input points very helpful and I agree that the interface needs some combination of a) better documentation, b) better validation of user input and possibly c) helpers. You mentioned some nice ideas and I will take a good look and investigate.

On your point about the scrollbars, it would be interesting if you could try the view-server/presentation-server version of Tex and see what you think. That component uses a different means of controlling layout and scrolling and I think it should be a lot simpler. I inane to retrofit that into Rex as well, but have not done that yet.

I will take a look at he escaping issue in the help dialogue - sounds like I needed double escapes!

Thanks again for the helpful feedback.

**Comment by grahamwallis** [comment]
I think all of the above suggestions are now included in Rex, apart from the search wrapper - instead of which I have currently taken the documentation route by adding to the user help text.
