### ISSUE TITLE
Node and Line additional properties values are String. Why not Object??

### ISSUE THREAD

**Issue by immmus** [odpi/egeria#3396]
Hi @davidradl .
In subject area nodes and lines field additionalProperties is Map<String, String>, but if I would want to add value object, list or map as describe in the InstancePropertyCategory.
<img width="722" alt="Screenshot 2020-07-28 at 17 13 47" src="https://user-images.githubusercontent.com/35165540/88677710-4e280800-d0f6-11ea-9caf-f88ea45e1abb.png">
<img width="1249" alt="Screenshot 2020-07-28 at 17 15 41" src="https://user-images.githubusercontent.com/35165540/88678202-de664d00-d0f6-11ea-9102-62f3f46701a5.png">

Maybe it’s worth considering this question before it’s too late?

**Comment by davidradl** [comment]
Hi @immmus, 
It is good question. what I was thinking for the Subject Area was that the we get a Term or other entity we are concerned with, and we look through the properties for ones we recognise. We map though into fields in the Term concept. There may be other attributes we do not recognise (either becase we have not added support fro them or they are attributes that Egeria does not recognise). If so, then we can keep them as strings and include them on updates so they are not lost. There is a simplicity about forcing to a String as then we know how to handle it. It might be that by doing this we try to replace a different type of object with a String version that may not work. 

I am thinking we have a few options:
1) Leave as is. Probably not a good idea as this could change existing content that we are looking to preserve, if it is not a String. 
2) We could amend the update process that it is never a replace, in that case any existing content would not be changed
3) We could not accept the additional properties on the update - only provide them as a map of strings for display in the UI and not allow them as input parameters.

I think I am keenest on 3), with documentation to say that 
- additional properties can be seen in get requests
- if additional properties need to be maintained then the 'replace style' updates should not be used 
- specifying additional properties on a create or update will be ignored.
I suspect this means a code change to ensure that subject area creates and updates do not accept the additional properties. I think this would mean a change to EntityDetailMapper to remove line 
" instanceProperties.setProperty("additionalProperties", mapPropertyValue);"

I would like to give the community a chance to give their suggestions.
@mandy-chessell @planetf1 @grahamwallis @cmgrote any thoughts?

**Comment by immmus** [comment]
Personally, I would like to use InstanceProperties in this case as it is used in EntityDetail. Because this option is much scalable and does without unnecessary hardcode.
<img width="969" alt="Screenshot 2020-07-29 at 14 33 17" src="https://user-images.githubusercontent.com/35165540/88795485-c51dd900-d1a8-11ea-8297-d55207b9cf53.png">

**Comment by davidradl** [comment]
@immmus I am not sure I follow. The instance properties map you mention is a map, the String is the name of the property ( the attribute name). For the additionalProperties, I would expect an entry in this map with key "additionalProperties" and an InstancePropertyValue that is a String String map. The content of the additionalProperties should not be at the top level as those properties are not known to Egeria (because they are not defined in the type system), so we do not know what they mean. The best we can do is not touch this content, so we do not break any processing that might rely on it. Am I making sense?

**Comment by davidradl** [comment]
@immmus can we close this issue now - I think we have fixed this in line with our discussions.
