### ISSUE TITLE
Make qualifiedName attribute on Referenceable a mandatory attribute

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#340]
This requires two changes:
Adding the following line to the definition of the qualified name attribute
        property.setAttributeCardinality(AttributeCardinality.ONE_ONLY);
Adding validation for mandatory properties to the repository validator

**Comment by cmgrote** [comment]
This can be closed now, right?

**Comment by mandy-chessell** [comment]
Agreed
