### ISSUE TITLE
mvn clean deploy fails 'by default' -> need to resolve for master integration build

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#341]
Currently 'mvn clean deploy' fails with

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.236 s
[INFO] Finished at: 2018-11-02T08:52:29Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project egeria: Failed to retrieve remote metadata org.odpi.egeria:egeria:0.3-SNAPSHOT/maven-metadata.xml: Could not transfer metadata org.odpi.egeria:egeria:0.3-SNAPSHOT/maven-metadata.xml from/to ossrh (https://oss.sonatype.org/content/repositories/snapshots): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with

This is because maven deploy is expected to deploy built artifacts to a repo.
Much of the enablement for this is done under a 'release' profile, which is not active by default (nor should it be)

Discussing with Linux Foundation build team what are the best practices for 'deploy' target to cover
 * developers building themselves (though most wouldn't use deploy)
 * Daily integration builds on jenkins.odpi.org publishing to the ODPi repository
 * Making it easier to create a 'release' and also push that to the public maven central repo

**Comment by planetf1** [comment]
Note that mvn clean deploy is working on the LF build infra ie jenkins jobs:

The master integration build is now working
https://jenkins.odpi.org/view/egeria/job/egeria-maven-merge-master/lastBuild/

I see that 0.3-SNAPSHOT s are getting published to nexus:
https://nexus.odpi.org/service/local/repositories/snapshots/content/org/odpi/egeria/

Waiting for further recommendations from LF team to see if we need to make any further changes on publishing of artifacts

**Comment by mandy-chessell** [comment]
Thanks Nigel, Jeremy, this is an important milestone for us :)

**Comment by planetf1** [comment]
Closing this, as I believe it is normal behaviour if the user running does not have priviliges
