### ISSUE TITLE
How add term to category?

### ISSUE THREAD

**Issue by immmus** [odpi/egeria#3410]
Hi @davidradl!
How add term to category? And after how get Categorization for this term?

**Comment by davidradl** [comment]
@immmus By creating a TermCategorization relationship between them. We have the relationship SCRUD methods exposed in the Subject Area OMAS. We could added new APIs like /users/{userId}/categories/{guid}/termCategorization for a category centric way of doing SCUD on this relationship. And equivalent for Term.

To get a Terms relationships use  "/users/{userId}/terms/{guid}/relationships
For Categories use /users/{userId}/categories/{guid}/relationships
Then you would need to look through the results for TermCategorizations.

**Comment by immmus** [comment]
> To get a Terms relationships use "/users/{userId}/terms/{guid}/relationships"
> For Categories use "/users/{userId}/categories/{guid}/relationships"

The problem with these requests is that we get all relationships but we need only termCategorization. We need api  /users/{userId}/categories/{guid}/{relationshipName} and for other glossary artifacts too.

**Comment by immmus** [comment]
@davidradl What are you think with my comment?

**Comment by immmus** [comment]
@davidradl I still wait your answer on my comment -> https://github.com/odpi/egeria/issues/3410#issuecomment-666603296 ....

**Comment by davidradl** [comment]
@immmus Sorry I missed this issue. 

1. Get I think a get of the form scoped on the relationship type would be useful. Though by convention/ consistancy we would use the plural of the type name .  
2. Another useful get would be /users/{userId}/categories/{guid}/terms to get to the associated terms from the category, where terms is from the TermCategorization definition. This pattern could be expanded to all relationships e.g
 /users/{userId}/terms/{guid}/replacedTerms. We would need to be careful around synonym where the end name and the plural of the type are both the same word - Synonyms. I suggest Synonym-relationships be used for this case. 

Based on the second point and the name clash with synonyms, it would be clearer and more consistent to have the rest call of the form. 
/users/{userId}/categories/{guid}/termCategorization-relationships 

Assuming we are sticking with relationships and not using lines in the API Rest end points.

**Comment by immmus** [comment]
> @immmus Sorry I missed this issue.
> 
> 1. Get I think a get of the form scoped on the relationship type would be useful. Though by convention/ consistancy we would use the plural of the type name .
> 2. Another useful get would be /users/{userId}/categories/{guid}/terms to get to the associated terms from the category, where terms is from the TermCategorization definition. This pattern could be expanded to all relationships e.g
>    /users/{userId}/terms/{guid}/replacedTerms. We would need to be careful around synonym where the end name and the plural of the type are both the same word - Synonyms. I suggest Synonym-relationships be used for this case.
> 
> Based on the second point and the name clash with synonyms, it would be clearer and more consistent to have the rest call of the form.
> /users/{userId}/categories/{guid}/termCategorization-relationships
> 
> Assuming we are sticking with relationships and not using lines in the API Rest end points.

@davidradl Okay. When can we do this? Or I can do it.

**Comment by davidradl** [comment]
@immmus Yes It would be great if you would do this.

**Comment by immmus** [comment]
> @immmus Yes It would be great if you would do this.

Okay, I getting started do it.

**Comment by immmus** [comment]
https://github.com/odpi/egeria/pull/3524
