### ISSUE TITLE
Subject area UI fails in 2.1 (pre-release testing)

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#3411]
Running the coco pharma notebooks (k8s), after running config/start/creating a data catalog notebooks, I launched the UI and was able to login, use tex/rex, asset search

However the subject area UI fails :
 * Click on subject area
 * Click + alongside projects
 * Enter a/a/a/
 * click create

no errors shown, but no projects appear in dropdown

will check locally

**Comment by davidradl** [comment]
https://github.com/odpi/egeria/issues/3421

**Comment by davidradl** [comment]
@planetf1 -can we close - the subject are a ui is now not present in the ui chassis?

**Comment by planetf1** [comment]
Yes
