### ISSUE TITLE
Tests should check for no unexpected exceptions (ie on server)

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#3414]
When reviewing #3386 it was noted that the PR caused unexpected errors to be added into the server's audit logs due to incorrect processing.

The automated FVT test for subject area did not pick this up -- since the test still worked fine as far as the subject area API was concerned.

We need to consider how to address this kind of issue in automated testing. It may be that FVTs or integration tests do need to check for unexpected audit events as part of their verification.

cc: @davidradl

**Comment by mandy-chessell** [comment]
This work is not planned
