### ISSUE TITLE
Allow an organization to defined its own governance zones and governance classification levels

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#3417]
In area 4 there are places where there is an enum for the governance domain and an enum for the level of a governance classification.  These are the current models:

![0401-Governance-Definitions](https://user-images.githubusercontent.com/12354195/89021569-ab030880-d318-11ea-8ac8-428197de837b.png)

![0422-Governance-Action-Classifications](https://user-images.githubusercontent.com/12354195/89021579-afc7bc80-d318-11ea-9c64-f2e0624ec92b.png)

The enums provide meaningful defaults to help organizations that are setting up governance for the first time.  What should an organization do if they want to have their own list of governance domains and classification levels?  

The purpose of the issue is to modify the types (and supporting OMASs/security services) to allow for both use of the enums and the ability for an organization to add their own.

We had half of this idea implemented for the **GovernanceConfidentiallyClassification** in that it took an integer which indirectly referred to a level defined in the **GovernanceConfidentialityLevel**.  

![0421-Governance-Confidentiality-Levels](https://user-images.githubusercontent.com/12354195/89022022-47c5a600-d319-11ea-81f0-fcba95f7772d.png)

The proposal is to add an integer to the entities that use the **GovernanceDomain**, **CriticalityLevel**, **RetentionBasis**, **ConfidenceLevel** enums.  Also reinstate the **ConfidentialityLevel** enum and add it back into the **GovernanceConfidentialityClassification**.

The new types look like this.  Notice there are classifications for **Collection** from Area 1 to be able to manage these levels as a set of values.

![0401-Governance-Definitions](https://user-images.githubusercontent.com/12354195/89022315-b99def80-d319-11ea-91ef-56887a99ff61.png)
![0421-Governance-Classification-Levels](https://user-images.githubusercontent.com/12354195/89022336-c28ec100-d319-11ea-8f59-8e41583933ca.png)
![0422-Governance-Action-Classifications](https://user-images.githubusercontent.com/12354195/89022376-d803eb00-d319-11ea-9ec7-7dc7625a51a0.png)
![0425-Subject-Areas](https://user-images.githubusercontent.com/12354195/89022352-ccb0bf80-d319-11ea-8c81-e3436b11a364.png)

Notice also that the enums all have "OTHER" options to mean that the values are defined in the domain/classification levels.

The integer value is used by preference, but if it is 0 then the enum value is checked.  If the Enum value is unspecified, null or set to "OTHER" then the integer value of 0 is believed - otherwise the ordinal from the enum is used.

The common services will set up the integer value from the enum ordinal whenever the enum is in use - however, not all processing may do that which is why both values still need to be checked when used.

As part of this change, the OpenMetadataSecurity module now passes the governance classifications on the Asset object.
The level will be passes as an integer.  It is called from the common services which will pass the enum ordianal if it is in use (using hte same logic as described above).

The OCF connected asset services will also pass the level value as an integer.  There is an enum defined that matches the open metadta type enum to allow lookup of the symbolic name and description if the org is using the enum values.

OMASs that set up and use these values - eg Governance Program OMAS, Asset Owner OMAS, Subject Area OMAS, ... - should follow a similar pattern.

**Comment by grahamwallis** [comment]
This looks more flexible - but I have a nagging concern about maintenance of consistency if an organisation were to start out with the pre-defined enums and then replace with their own; it seems it would be an almighty task to ensure that consistency is maintained as sets of values are switched. Or am I missing something?

**Comment by mandy-chessell** [comment]
How would you do it?

My view is that data migration is a problem if they change their classification level definitions after a time whether they use the enums or not.  Providing the enums does not make it more or less of an issue.  Whichever case, it would make sense to use different level identifiers for their new values which means it makes it possible to detect an unmigrated value.

**Comment by mandy-chessell** [comment]
Added in #3707
