### ISSUE TITLE
Remove subject area from the Polymer UI

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#3421]
@bogdan-sava @planetf1 Are you ok with me removing the subject Area from the Polymer UI. At this time, we are not planning to use it or enhance it.  I am concentrating on providing this UI capability in the presentation server.

**Comment by planetf1** [comment]
Yes I would support this.

**Comment by bogdan-sava** [comment]
What is the reason?

**Comment by davidradl** [comment]
@bogdan-sava. I and others are developing a User Interface based around React that is multi-tenant, the server side runs on Express and is called the [presentation server](https://egeria.odpi.org/open-metadata-implementation/admin-services/docs/concepts/view-server.html).  I am creating a glossary author UI, which is now more capable than the Server Chassis Subject Area one. The presentation server communicates to a view server. My thinking is unless someone wants to enhance the subject area UI, we could get rid of the Subject Area UI and use the glossary author presentation server UI instead for this capability. Happy to share more details if you are interested.

**Comment by bogdan-sava** [comment]
ok
