### ISSUE TITLE
Subject Area API get Term relationships not working correctly.

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#3434]
I am writing UI code that calls the relationships APIs around the subject area. I get all the relationships associated with a Term, it comes back without the TermGuid and GlossaryGuid. I have debugged the server and it seems that the LineMapper calls setEnd1GuidInLine(line, guid1); and setEnd2GuidInLine(line, guid2); But when it comes out of that method the object does not appear to have those fields set.

Some thoughts on how to investigate :

-  I was suspect this regressed during the large subject area refactor. The previous code instantiated the child object so it was serialised with the child fields. The SubjectArea. responses had annotations  in the parent class to indicate how to Jackson serialise.
- I wonder if all we need to do is to add in annotations to Node.java and Line.java, indicating how to serialise the child objects. Searching for @JsonSubTypes in the Egeria code base will give examples on how to do this.

**Comment by davidradl** [comment]
@immmus  would you like to look at this - this appears to be a consequence of the API refactor. I need to get this fixed quite soon - so if you have not time to look at it this week - I will do it.

**Comment by immmus** [comment]
> @immmus would you like to look at this - this appears to be a consequence of the API refactor. I need to get this fixed quite soon - so if you have not time to look at it this week - I will do it.

Hi @davidradl ! I see it after request:
<img width="1182" alt="Screenshot 2020-08-03 at 22 22 05" src="https://user-images.githubusercontent.com/35165540/89219136-eda63880-d5d7-11ea-96b9-005f93c20868.png">

There are looks its good here. I will look further.

**Comment by immmus** [comment]
<img width="1359" alt="Screenshot 2020-08-03 at 22 34 10" src="https://user-images.githubusercontent.com/35165540/89220156-c3557a80-d5d9-11ea-9c7b-3e021647ac58.png">
This response result too is good.

**Comment by immmus** [comment]
> @immmus Thanks for you quick response. It is great you cannot recreate it :-) that means it is not a basic error - I will dig in further to see why it is not working for me.

@davidradl okay I will wait result your research and I will try to understand your problem.

**Comment by davidradl** [comment]
I get 
{
   "class":"SubjectAreaOMASAPIResponse",
   "relatedHTTPCode":200,
   "result":[
      {
         "systemAttributes":{
            "status":"ACTIVE",
            "createdBy":"faith",
            "createTime":"2020-08-04T08:31:18.932+00:00",
            "version":1,
            "guid":"14800083-5a4b-4dd3-a377-da41a9b27302"
         },
         "typeDefGuid":"1d43d661-bdc7-4a91-a996-3239b8f82e56",
         "lineType":"TermAnchor",
         "name":"TermAnchor",
         "guid":"14800083-5a4b-4dd3-a377-da41a9b27302"
      }
   ]
}

**Comment by immmus** [comment]
> I get
> {
> "class":"SubjectAreaOMASAPIResponse",
> "relatedHTTPCode":200,
> "result":[
> {
> "systemAttributes":{
> "status":"ACTIVE",
> "createdBy":"faith",
> "createTime":"2020-08-04T08:31:18.932+00:00",
> "version":1,
> "guid":"14800083-5a4b-4dd3-a377-da41a9b27302"
> },
> "typeDefGuid":"1d43d661-bdc7-4a91-a996-3239b8f82e56",
> "lineType":"TermAnchor",
> "name":"TermAnchor",
> "guid":"14800083-5a4b-4dd3-a377-da41a9b27302"
> }
> ]
> }

Can you give me screenshot postman, that I can see where you are requesting?

**Comment by davidradl** [comment]
I can see where the issue is, but have not worked out how to solve it. The setup I use to drive the Ui, is to run one metadata server cocoMDS1 that is connected to by a view server cocoView1, I then start an express server we call the presentation server. I am writing the glossary author part of a React Ui that communicates to the presentation server. In this case the browser passes through a request to get the term relationships like this : `https://localhost:9443/servers/cocoView1/open-metadata/view-services/glossary-author/users/faith/terms/d22f7e5c-d34d-47ef-9a9a-c9a117d2ea88/relationships`. The glossary author view then issues the subject area equivalent of `https://localhost:9443/servers/cocoMDS1/open-metadata/access-services/subject-area/users/faith/terms/d22f7e5c-d34d-47ef-9a9a-c9a117d2ea88/relationships`    
The view service uses the subject area client to issue the call.  Somehow it loses the child fields while handling the response in the glossary author view service.The subject area client call is issued in GlossaryAuthorViewTermRESTServices

**Comment by davidradl** [comment]
@immmus in TermFVT line 97 I added 
`        List<Line> lines = getTermRelationships(term1);
        if (lines.size() != 1) {
            throw new SubjectAreaFVTCheckedException("ERROR: Expected 1 relationship");
        }
        Line line = lines.get(0);
        if ( line.getLineType() != LineType.TermAnchor) {
            throw new SubjectAreaFVTCheckedException("ERROR: Expected TermAnchor");
        }
        TermAnchor termanchor = (TermAnchor)line;

        if (termanchor.getGlossaryGuid()  == null) {
            throw new SubjectAreaFVTCheckedException("ERROR: ExpectedGlossaryGuid");
        }
        if (termanchor.getTermGuid()  == null) {
            throw new SubjectAreaFVTCheckedException("ERROR: ExpectedTermGuid");
        }`

The FVT fails on the cast. I am thinking that the java client library might be losing the real type of the Line - in this case TermAnchor so it loses the guids. I wonder if we need to construct the TermAnchor so it forces java to know its real type in the response processing of this list of lines.  
I am busy this afternoon. If you have time could you have a look please. It would be good to add tests like this to the FVT to check that these sort of values do come through the client APIs.

**Comment by immmus** [comment]
> @immmus in TermFVT line 97 I added
> ` List lines = getTermRelationships(term1);
> if (lines.size() != 1) {
> throw new SubjectAreaFVTCheckedException("ERROR: Expected 1 relationship");
> }
> Line line = lines.get(0);
> if ( line.getLineType() != LineType.TermAnchor) {
> throw new SubjectAreaFVTCheckedException("ERROR: Expected TermAnchor");
> }
> TermAnchor termanchor = (TermAnchor)line;
> 
> ```
>     if (termanchor.getGlossaryGuid()  == null) {
>         throw new SubjectAreaFVTCheckedException("ERROR: ExpectedGlossaryGuid");
>     }
>     if (termanchor.getTermGuid()  == null) {
>         throw new SubjectAreaFVTCheckedException("ERROR: ExpectedTermGuid");
>     }`
> ```
> 
> The FVT fails on the cast. I am thinking that the java client library might be losing the real type of the Line - in this case TermAnchor so it loses the guids. I wonder if we need to construct the TermAnchor so it forces java to know its real type in the response processing of this list of lines.
> I am busy this afternoon. If you have time could you have a look please. It would be good to add tests like this to the FVT to check that these sort of values do come through the client APIs.

Yes, I also noticed that the Line client type loses information about TermAnchor. I will figure out how to solve this problem.

**Comment by davidradl** [comment]
@immmus I this the problem is that the `Line.java `does not have @JsonSubTypes annotations detailing all its subclasses - this should allow the Line to deserialise properly. Please add the equivalent for `Node.java` . For an example of how to implement this see `AdminServicesConfigHeader.java`. Please let me know if you can get to this this week - or I will make the change, as this change will unblock some UI work I am doing. Many thanks David.

**Comment by immmus** [comment]
@davidradl Yes, I really long understood it and added these annotations to Line.java but I have getting errors after change...
I struggled with the problem for a long time and I have to admit that I don't know how to solve it yet.
<img width="768" alt="Screenshot 2020-08-06 at 19 16 52" src="https://user-images.githubusercontent.com/35165540/89557386-65b07080-d81b-11ea-889c-c15c50be4207.png">
<img width="1699" alt="Screenshot 2020-08-06 at 19 16 40" src="https://user-images.githubusercontent.com/35165540/89557391-68ab6100-d81b-11ea-9897-c87bb1bf77e1.png">

I will be very thank you if you help to me with it.

**Comment by davidradl** [comment]
@immmus I think you need to have a name on each line
```
@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.PROPERTY,
        property = "class")
@JsonSubTypes({
        @JsonSubTypes.Type(value = AccessServiceConfig.class, name = "AccessServiceConfig"), 
```

what happens is that the name then ends up in the response; Jackson then knows to match the name to the class and can type it appropriately. Without the name - Jackson has nothing to key off.

**Comment by immmus** [comment]
> @immmus I think you need to have a name on each line similar to this code:
> 
> ```
> @JsonTypeInfo(
>         use = JsonTypeInfo.Id.NAME,
>         include = JsonTypeInfo.As.PROPERTY,
>         property = "class")
> @JsonSubTypes({
>         @JsonSubTypes.Type(value = AccessServiceConfig.class, name = "AccessServiceConfig"), 
> ```
> 
> what happens is that the name then ends up in the response; Jackson then knows to match the name to the class and can type it appropriately. Without the name - Jackson has nothing to key off.

I did  with the names but I was also getting this error...

**Comment by immmus** [comment]
@davidradl I hasten happy to you)), I seems to resolve this problem

**Comment by immmus** [comment]
https://github.com/odpi/egeria/pull/3462

**Comment by davidradl** [comment]
@immmus good news - I will test it out tomorrow morning

**Comment by davidradl** [comment]
@immmus Do you want to add the enhanced FVT tests to check that the appropriate specialized Line properties are being honoured  under this issue on another one ?

**Comment by immmus** [comment]
> @immmus Do you want to add the enhanced FVT tests to check that the appropriate specialized Line properties are being honoured under this issue on another one ?

@davidradl If you want to add, you can do this:) else I can do this. I wait your answer:)

**Comment by immmus** [comment]
@davidradl I am already doing tests. Soon will be complete.

**Comment by immmus** [comment]
@davidradl https://github.com/odpi/egeria/pull/3487

**Comment by davidradl** [comment]
@immmus clever way of testing it :-)

**Comment by immmus** [comment]
> @immmus clever way of testing it :-)

Thank you)
