### ISSUE TITLE
ui-chassis-spring has failing rat check on dependencies.log

### ISSUE THREAD

**Issue by wbittles** [odpi/egeria#3439]
I'm experiencing a build fail with mvn clean install with the following 

`[ERROR] Failed to execute goal org.apache.rat:apache-rat-plugin:0.13:check (rat-check) on project ui-chassis-spring: Too many files with unapproved license: 1 See RAT report in: /home/wbittles/egeria/open-metadata-implementation/user-interfaces/ui-chassis/ui-chassis-spring/target/rat.txt -> [Help 1]
`
The only file listed in the rat report was 
egeria/open-metadata-implementation/user-interfaces/ui-chassis/ui-chassis-spring/target/dependencies.log

[rat.txt](https://github.com/odpi/egeria/files/5021253/rat.txt)

**Comment by davidradl** [comment]
@wbittles If you delete that file then re-run does it fail? Rat checking should not check the target folders with the rat plugin having <exclude>**/target/**</exclude> in the top level pom.xml. This must be local to you as the build is working on master. 
Are you at master with no changes?

**Comment by bogdan-sava** [comment]
it seems you have a file called dependencies.log there and shouldn't.

However, locally you can:
`mvn clean install -Drat.skip`

and the rat check will be skipped

**Comment by wbittles** [comment]
@bogdan-sava If the log file shouldn't be there, I'll try and track down what's generating it then. thanks

**Comment by planetf1** [comment]
I can confirm I don't have that file. The contents may give a clue? Could it just be a file you created when checking dependencies?

If I create any files when searching/debugging I always try and place outside the build tree. If your current build process (with changes) creates extra files then as david mentioned it's best to place them in target (much better than adding more exclusions).

Also bear in mind that if you create extra files you won't want them picked up by git in error, so be careful with git add/commit too (again there's an exclusion mechanism, and target is removed by default)

**Comment by davidradl** [comment]
@wbittles can we close this, it is not obvious what Egeria change could help here?
