### ISSUE TITLE
Subject Area FVT does not run with local graph repo.

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#3453]
https://github.com/odpi/egeria/issues/3446 will knit this into the build

**Comment by davidradl** [comment]
The first bug is that when a createTerm is issued with associate governance classifications - the entityDetail for creation has the associated classifications. The graph repo logic is stricter than the in memory repo logic and checks that the classification that is supplied has a type. The first fix is to supply the appropriate type.

**Comment by davidradl** [comment]
The second bug is around updateTerm when there are changes to the classifications.

**Comment by planetf1** [comment]
On the first issue - do we need to also tighten up the in memory repo?

**Comment by davidradl** [comment]
> On the first issue - do we need to also tighten up the in memory repo?
I have raised issue https://github.com/odpi/egeria/issues/3455 to have the CTS be enhanced to test any cases where the in memory repo and the graph repo act differently, that the current Subject Area FVT exposes. We should ensure both repos work before committing the CTS enhancements.

**Comment by davidradl** [comment]
The 3rd issue is we have an entity with a classification that has an enum property set. In this case it is Criticality and the level is set to Catastrophic. The FVTI then issues an classifyEntity, the in memory repo makes the change the returns the level in the classification as null, the graph repo does not make the change. What actually happens is that the attribute is not sent to the server in the rest call, so the server gets a classification with no properties. The in memory repo does not check for null and just copies null over, the graph repo checks for null and makes no changes to the existing value. I think the graph repo is correct in this case and am amending the in memory repo logic and the FVT test.

**Comment by davidradl** [comment]
fyi I have a fix for the 2nd issue -which is to move the remove out of the for loop to avoid the concurrentModificationException

**Comment by davidradl** [comment]
3rd issue update" I amended the in memory repo code in so that if there was an existing classification of the same name as the new one, and the new classification had null instance properties - then use the existing classification instanceProperties, unfortunately this failed junit DatabaseContextHandlerTest with a null pointer in the build. I am not sure how to run this junit out side of the build @planetf1 any ideas?

**Comment by planetf1** [comment]
2 approaches

a) Hack the groovy script to add a long sleep at the end. Everything needed should be setup. Then when the maven build gets to that point run the test in intellij
b) Start a server chassis manually (think the tests are coded to use 10443 so use `-Dserver.port=10443`) and just configure the inmem/graph repo + subject area OMAS as usual

I'm not sure the best way to support debugging in future. Perhaps easiest for server-side is to allow an option to set the agent string so that the server VM will pause until debugger attached? (which is something else you could do manually via the groovy script). Mostly though if the test fails the dev of the area is likely to run the server manually anyway.

**Comment by planetf1** [comment]
That test is in information view. It's a regular unit test so though it's run from maven/groovy it should be runnable in intellij without doing anything special. Since information view is incomplete it could well be a put in that component's test code too. 

Where do you get the NPE? If it's server-side I would launch a chassis, attach with debugger, then run the JUnit from intellij? And if it's client it's even easier - just debug the test case directly?

**Comment by davidradl** [comment]
For the 3rd issue I am commenting out the check in the TermFVT and have raised issue https://github.com/odpi/egeria/issues/3457 for it to be looked at.

**Comment by planetf1** [comment]
For the 3rd issue another option is to mark test as disabled (as it then shows up in test reports as skipped) - but whichever way works

**Comment by davidradl** [comment]
> That test is in information view. It's a regular unit test so though it's run from maven/groovy it should be runnable in intellij without doing anything special. Since information view is incomplete it could well be a put in that component's test code too.
> 
> Where do you get the NPE? If it's server-side I would launch a chassis, attach with debugger, then run the JUnit from intellij? And if it's client it's even easier - just debug the test case directly?

Thanks Nigel - I managed to run it using Maven install; junit was failing to find a DTD. I have commented out the failing test and reverted the change I made that caused this issue. I have raised this as a separate issue, so the FVT should now work after the pr goes in, with one check commented out.

**Comment by planetf1** [comment]
If it's a failing test it's probably better to annotate with @Disabled or @Test(enabled=false) depending on test framework/similar - that way we get a report of any skipped tests in the overall results. Not critical and good we have an issue for it, just a minor thought.

**Comment by davidradl** [comment]
> If it's a failing test it's probably better to annotate with @disabled or @test(enabled=false) depending on test framework/similar - that way we get a report of any skipped tests in the overall results. Not critical and good we have an issue for it, just a minor thought.

Unfortunately the test is a sequences of API calls and checks that they complete successfully, as such disabling the error is not being one of the checks (i.e. commenting out an if). commenting out the test would remove the many good tests that are around the failing one.

**Comment by planetf1** [comment]
fair enough :-)
