### ISSUE TITLE
Issue found during subject Area FVT testing 

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#3457]
Running TermFVT against the in memory repo and the graph repo. It fails on the graph repo as is. 

The have an entity with a classification that has an enum property set. In this case it is Criticality and the level is set to Catastrophic. The FVT then issues an classifyEntity, the in memory repo makes the change the returns the level in the classification as null, the graph repo does not make the change. What actually happens is that the attribute is not sent to the server in the rest call, so the server gets a classification with no properties. The in memory repo does not check for null and just copies null over, the graph repo checks for null and makes no changes to the existing value. I think the graph repo is correct in this case and am amending the in memory repo logic and the FVT test. I am thinking of making the change that a classifyEntity with a classification that has no instanceProperties, should result in a new classification if there previously was not one . In the case where there already is a classification with classification properties then we do not amend the existing classification. Assuming nothing else has changed by the classifyEntity (like effectivity dates) , I wonder should I update the Entity version. The current code updates the entity version. 

InInMemoryOMRSMetadataCollection in classifyEntity before it updates the Entity: I had tried this change : 

` EntityDetail existingEntity = repositoryStore.getEntity(entityGUID);
        List<Classification> existingclassifications = existingEntity.getClassifications();

        InstanceProperties existingClassificationInstanceProperties = null;
        for (Classification existingclassification :existingclassifications) {
            if (existingclassification.getName().equals(newClassification.getName())) {
                existingClassificationInstanceProperties = existingclassification.getProperties();
            }
        }
        // ensure that the existing classifications are not overwritten if the new classification does not have any
        if (newClassification.getProperties() == null) {
            newClassification.setProperties(existingClassificationInstanceProperties);
        }

        EntityDetail updatedEntity = repositoryHelper.addClassificationToEntity(repositoryName,
                                                                                    entity,
                                                                                    newClassification,
                                                                                    methodName);`

This introduced a null pointer junit error in the build. in  DatabaseContextHandlerTest.

**Comment by grahamwallis** [comment]
@davidradl - I'm not sure that would be an appropriate change anyway - would it not prevent someone from clearing the classification properties (deliberately)?
