### ISSUE TITLE
Move ranger-gaian plugin code into Egeria

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#347]
Currently the ranger gaian plugin code is at https://github.com/GaianRangerPlugin/ranger-gaian-plugin

This should be moved into the Egeria codebase

**Comment by planetf1** [comment]
Initial move into egeria has been done.

I have moved the proxy auth plugin into
open-metadata-implementation/adapters/authentication-plugins/gaian-impersonation

I have moved the ranger plugin into
open-metadata-implementation/adapters/governance-engines-plugins/gaian-ranger-plugin

I have added SPDX statements so rat passes

Also updated poms, check clean build.

Not done yet
 - double check all licenses (this build pulls quite a few more dependencies in, and needs a new local repo for gaian & derby)
 - refactor the dependency version management amongst the pom hierarchy (seperate issue will be raised). Also check versions are current
 - tested the execution and setup of the plugin
 - tested the unit tests (there aren't many.....)

cc: @mstrelchuk @danielaotelea

**Comment by CDaRip2U** [comment]
Nigel, For the large files, could we add them as assets in the Nexus repository and pull them as build dependencies as needed there for assets > 100Mb?   https://nexus.odpi.org/content/repositories/

**Comment by planetf1** [comment]
My concern is wanting to push them to a 'well known' repository, rather than having a dependency which might only be known in our team. It's true the odpi repo is external, so we could refer to in a readme, but they aren't really assets we create or own, so it's a little borderline.

In the end I figured the authoritative source for now is the distribution zip, so my maven tasks were based on that & appear to work....  at least we are automatically deriving what we need from that 'official' source..... and it can be run by anyone
