### ISSUE TITLE
Review/fix Egeria concepts and documentation to ensure we are using inclusive language

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#3486]
On today's community call we agreed that it is important to us that Egeria is inclusive in both its community and implementation.  Campaigns such as **Black Lives Matter (BLM)** have reminded us that our language is riddled with inappropriate phrases that are demeaning to subsets of our community.  This issue is to coordinate a review of the Egeria terminology, personas, and documentation to eliminate any inappropariate terms.

Please add and discuss suggestions for changes to Egeria's terminology.  Aspects to consider include (but not limited to) race, gender, mental health, age...

----
Below is a suggested list of term replacements from Chris Replogle:

Term  | Replacement 
------|-------
| Whitelist | Allowlist |
| Blacklist | DenyList |
| Master/Slave | Controller/Node |
| Master Branch | Main Branch |
| Grandfathered | Legacy Status |
| Gendered pronouns | Them, they, their |
| Man hours | Person hours, developer hours |
| BlackHat/WhiteHat | Unethical/Ethical |
----

**Comment by davidradl** [comment]
@mandy-chessell I can see the use of grandfather in a UI dependancies. 
Under /open-metadata-implementation/user-interfaces/presentation-server/nodejs/node_modules/language-tags there are references to grandfather and grandfathered tags. I have raised issue https://github.com/mattcg/language-tags/issues/8 against this package. If they cannot enhance the package or do not respond - I suggest we investigate further to see if we can use an alternative package.

**Comment by planetf1** [comment]
A few other possibilities
 * master/slave -> primary/secondary (me) or primary/replica [drupal](https://www.drupal.org/node/2275877)

**Comment by davidradl** [comment]
There are numerous usages of the word slave in the ui chassis dependancies. Not in our code.

**Comment by davidradl** [comment]
https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx shows how to rename the Git master to main branch. I think this is our biggest use of the word master, and it ends up in url links to Git repository content in our docs.

**Comment by planetf1** [comment]
I suggest keeping a todo list of the changes, then opening up issues against each area (like master - not read details above but imo we don't rename, instead we effectively copy, switch default & lock. master probably needs to stay around for historic reasons, but cannot be used for anything new nor should we refer links to it.. but this detail we can track in an issue?

Shall we start with a list (edit here, perhaps move to top comment) to summarise further discussion below
[ ] Switch to using 'main' for default git branch
