### ISSUE TITLE
Add CODEOWNERS for all components

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#351]
As per https://help.github.com/articles/about-codeowners/

Adding code owners would allow review requests to be automatically routed to the right people 
In future it would be possible to require a review from a codeowner, but this is likely overkill for now.

Codeowners can be defined as individual users, or groups. The latter may be more flexible as it avoids depending on any one individual, but this requires additional setup on github to define those groups.

The 'component' is purely defined by relative path, in a form similar to .gitignore

Opening to track discussion

**Comment by planetf1** [comment]
Adding initial version for the components i'm working on as an example/test of the process

**Comment by planetf1** [comment]
Initial changes made for a few components - process appears to work - suggest leave open to remind us other components/owners need doing

**Comment by mandy-chessell** [comment]
Initial set of CODEOWNERS established
