### ISSUE TITLE
Change how relationship ends are exposed in Subject Area OMAS API 

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#3514]
currently the subject Area API exposes the guids of each end of the Line as an attribute. this does not make it easy for the Ui to process. 

For example the TermAnchor payload has :

```
       "lineType":"TermAnchor",
         "name":"TermAnchor",
         "termGuid":"90fea757-384f-45fc-9770-59f17a78be51",
         "glossaryGuid":"b1df5979-9213-4cdb-8f41-cd96cffb1ab1",
         "guid":"8c81da89-ee61-4cb4-a15f-58a4b7fdf145"
      }
```

It is not obvious that the glossaryGuid and termGuid are special attributes indicating the guids of entities at each end.

It would be better to remove these from the attributes and have :
end1 : {
     "nodeType": "Glossary",
      "attributeName: "anchor",
      "attributeLabel": "Anchor",
      "attributeDescription: "Owning glossary.",
      "cardinality":"AT_MOST_ONE",
},
end2 : {
        "nodeType": "Term",
       "attributeName": "terms",
       "attributeLabel": "Terms",
       "attributeDescription": "Terms owned by this glossary.",
       "cardinality":"ANY_NUMBER",
  }

**Comment by davidradl** [comment]
@immmus I am looking to have this done this week. Would you like to do this one; if not I will do it.

**Comment by immmus** [comment]
> @immmus I am looking to have this done this week. Would you like to do this one; if not I will do it.

Hi @davidradl . Sorry, I am very busy this week. So that do you )

**Comment by davidradl** [comment]
@immmus no worries. Thanks for responding - I will do this one.
