### ISSUE TITLE
Subject Area FVT fails when run against Janus graph locally. Works on the build system.

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#3523]
The Subject Area FVT fails when run against Janus graph. The console shows this error :
"ERROR: OMAG-COMMON-400-016 An unexpected org.odpi.openmetadata.accessservices.subjectarea.handlers.SubjectAreaGlossaryHandler exception was caught by find for Glossary; error message was OMAG-REPOSITORY-HANDLER-400-003 An unexpected error was returned by the metadata server during findGlossary request for open metadata access service Subject Area OMAS on server cocoMDS4; message was OMRS-REPOSITORY-400-055 An unexpected exception was received from a repository connector during the findEntitiesByPropertyValue operation which had message: Could not process individual retrieval call  Suggested action: Review the error message and other diagnostics created at the same time."

The first thing that the FVT does is a find for all glossaries using a criteria of .*  

The error comes from Janus graph and occurs on line 1715 in GraphOMRSMetadataStore. I assume some change to search in Janus graph has caused this to fail. The In memory repository works.

@planetf1 This is the second time that the Subject Area FVT has exposed a difference between the repository implementations. I think we should consider running the Subject Area  FVT twice once agains the in memory and once against theJanus Graph. 

@cmgrote @grahamwallis are you aware of any Janus Graph repo changes that have occurred recently that might have caused this?

**Comment by planetf1** [comment]
Hi David

Partial reply... the fvt is set up to run against both inmem and graph. This gets done for every PR.

**Comment by planetf1** [comment]
Here's an example run from a recent pr

https://dev.azure.com/ODPi/Egeria/_build/results?buildId=9826&view=logs&j=4dc6fbf2-95db-5f93-ea5a-117822a16d38&t=61dc2478-351e-57b7-3c49-54d8ca2911d9

Search for TermFVT

There's some issues with slf bindings and verbosity but the tests are running. 18 in fact. That is for inmem and graph as we are using parametrised tests to go against both deployed servers

So I assume your failure is in local build. Can you check it works ok on master? If so could it be a change? Happy to try your branch or suggest you create s a draft pr to verify

**Comment by grahamwallis** [comment]
The error code being reported seems to be from the Enterprise layer, which suggests that it would be independent of the type of local repository, which supports the results reported by @planetf1 above.

**Comment by davidradl** [comment]
@planetf1 I tried locally against the latest master no changes and it was working on in memory and not on graph. The error I was seeing was in Janus specific code. It must be a local quirk - I am glad is not an issue more generally.

**Comment by davidradl** [comment]
> The error code being reported seems to be from the Enterprise layer, which suggests that it would be independent of the type of local repository, which supports the results reported by @planetf1 above.
Thanks Graham - I will clean my machine and debug locally.

**Comment by grahamwallis** [comment]
@davidradl Could you please post the error you are seeing?

**Comment by planetf1** [comment]
Maybe even the full logs... be good to understand what is different about the config.

Also can you confirm how exactly  you are running the tests?

**Comment by planetf1** [comment]
Is this still an issue? Does it relate to a specific branch/commit in your fork - or just master? Happy to try it out locally if you can describe your config.

Also I presume you clear out any old cohort config/graph repos etc prior to the run (the formal FVTs always start clean)

**Comment by davidradl** [comment]
My config must have been incorrect in some way, I retested with a newly created config and it worked.
