### ISSUE TITLE
Change logic return results in SubjectAreaClient

### ISSUE THREAD

**Issue by immmus** [odpi/egeria#3534]
Hi @davidradl !
I propose to change return values on `SubjectAreaOMASAPIResponse<T>`
Because we receive a response and return an object. And then, in other classes, we pack it back into `SubjectAreaOMASAPIResponse <T>`

Create method in SubjectAreaClient
<img width="1007" alt="Screenshot 2020-08-27 at 11 10 23" src="https://user-images.githubusercontent.com/35165540/91415875-496e8500-e857-11ea-8641-32c6ab578bef.png">

Actions in other classes
<img width="1071" alt="Screenshot 2020-08-27 at 11 09 33" src="https://user-images.githubusercontent.com/35165540/91416072-8dfa2080-e857-11ea-95ec-0524421c0e9f.png">
<img width="1117" alt="Screenshot 2020-08-27 at 11 10 02" src="https://user-images.githubusercontent.com/35165540/91416083-905c7a80-e857-11ea-87d8-c1befe6b78ae.png">

If we I change logic in SubjectAreaClient this will save us from unnecessary actions.

**Comment by immmus** [comment]
@davidradl I still wait your answer:)

**Comment by davidradl** [comment]
@immmus. I think you are proposing to return the response on the client API. The reason the Java client API gets the payload (the result) as the return value and throws Exception when things have not gone right, is that this seems a natural way a java programmer would expect an API - rather than the program having to be aware of the response and then decode it.  Am I understanding this proposal correctly?

**Comment by immmus** [comment]
> @immmus. I think you are proposing to return the response on the client API. The reason the Java client API gets the payload (the result) as the return value and throws Exception when things have not gone right, is that this seems a natural way a java programmer would expect an API - rather than the program having to be aware of the response and then decode it. Am I understanding this proposal correctly?

I suggest to change interface thus:
T  -->  SubjectAreaOMASAPIResponse<T>
<img width="946" alt="Screenshot 2020-08-28 at 16 39 56" src="https://user-images.githubusercontent.com/35165540/91567100-4229a300-e94d-11ea-81da-b04b1d31f52e.png">

**Comment by davidradl** [comment]
@immmus I am not in favour of exposing the response object to the java client, I think it preferable to give the payload on the return and throw exceptions for errors. Changing as you suggest would make the server and client code more consistent, but it would expose some of our implementation when we do not need to. @mandy-chessell @grahamwallis @planetf1 what are you thoughts?

**Comment by immmus** [comment]
> @immmus I am not in favour of exposing the response object to the java client, I think it preferable to give the payload on the return and throw exceptions for errors. Changing as you suggest would make the server and client code more consistent, but it would expose some of our implementation when we do not need to. @mandy-chessell @grahamwallis @planetf1 what are your thoughts?

These exceptions everyone will throw:
<img width="854" alt="Screenshot 2020-08-28 at 17 26 13" src="https://user-images.githubusercontent.com/35165540/91579044-b6ffdb80-e953-11ea-9bde-4c1b3469ae07.png">

SubjectAreaRestClient is checking and this dont dependency from return value.
<img width="1105" alt="Screenshot 2020-08-28 at 17 28 33" src="https://user-images.githubusercontent.com/35165540/91579275-0c3bed00-e954-11ea-944c-9c54afd48cc7.png">

**Comment by immmus** [comment]
@planetf1 @davidradl @mandy-chessell 
In general, I am a supporter of this code:
<img width="1079" alt="Screenshot 2020-08-28 at 17 45 55" src="https://user-images.githubusercontent.com/35165540/91580979-8d947f00-e956-11ea-8e4c-db4a3a085faa.png">
<img width="718" alt="Screenshot 2020-08-28 at 17 51 55" src="https://user-images.githubusercontent.com/35165540/91581614-4eb2f900-e957-11ea-93c9-d2cf851ff863.png">

In order not to burden the client with checked exceptions. So that the errors was in the answer in the form of standard codes and so that the client himself could decide how to deal with it, and not what we impose on him.

**Comment by mandy-chessell** [comment]
I agree with the general comments that the response object should be unpacked in the client into a return object/exceptions as appropriate so that a developer coding calls to the client sees a natural Java interface and can use try...catch structures etc.  

The purpose of the response object is ensure that no exception leaves the server because it contains a stack trace.  Server-side, the stack trace should be logged to the audit log and a description of the top level exception is added to the response object.  This is processed in the client and coverted back into the same exception (minus stack trace) and returned to the client as if it was local to the server.

There are a couple of issues in the server side processing that is shown above.

* There should be a catch block for Throwable (or at least Exception) to ensure runtime errors are caught and processed.
* The entry and exit logging should be using the `RESTCallLogger` rather than the SLF4J since the rest call logger sets up the thread name and times the call.

The RESTExceptionHandler provides methods for handling the common exceptions including logging runtime exceptions to the audit log.

```
    /**
     * Files live on a file system.  This method creates a top level anchor for a file system.
     *
     * @param serverName name of calling server
     * @param userId calling user
     * @param requestBody properties of the file system
     *
     * @return unique identifier for the file system or
     * InvalidParameterException one of the parameters is null or invalid or
     * PropertyServerException problem accessing property server or
     * UserNotAuthorizedException security access problem
     */
    public GUIDResponse   createFileSystemInCatalog(String                   serverName,
                                                    String                   userId,
                                                    NewFileSystemRequestBody requestBody)
    {
        final String methodName = "createFileSystemInCatalog";

        RESTCallToken token = restCallLogger.logRESTCall(serverName, userId, methodName);

        GUIDResponse response = new GUIDResponse();
        AuditLog     auditLog = null;

        try
        {
            auditLog = instanceHandler.getAuditLog(userId, serverName, methodName);

            if (requestBody != null)
            {
                FilesAndFoldersHandler<FileSystemProperties,
                                       FolderProperties,
                                       FileProperties> handler = instanceHandler.getFilesAndFoldersHandler(userId, serverName, methodName);

                response.setGUID(handler.createFileSystem(userId,
                                                          null,
                                                          null,
                                                          requestBody.getUniqueName(),
                                                          requestBody.getDisplayName(),
                                                          requestBody.getDescription(),
                                                          requestBody.getFileSystemType(),
                                                          requestBody.getVersion(),
                                                          requestBody.getPatchLevel(),
                                                          requestBody.getSource(),
                                                          requestBody.getFormat(),
                                                          requestBody.getEncryption(),
                                                          requestBody.getAdditionalProperties(),
                                                          null,
                                                          methodName));
            }
        }
        catch (InvalidParameterException error)
        {
            restExceptionHandler.captureInvalidParameterException(response, error);
        }
        catch (PropertyServerException error)
        {
            restExceptionHandler.capturePropertyServerException(response, error);
        }
        catch (UserNotAuthorizedException error)
        {
            restExceptionHandler.captureUserNotAuthorizedException(response, error);
        }
        catch (Throwable error)
        {
            restExceptionHandler.captureThrowable(response, error, methodName, auditLog);
        }

        restCallLogger.logRESTCallReturn(token, response.toString());

        return response;
    }
```

**Comment by immmus** [comment]
> I agree with the general comments that the response object should be unpacked in the client into a return object/exceptions as appropriate so that a developer coding calls to the client sees a natural Java interface and can use try...catch structures etc.
> 
> The purpose of the response object is ensure that no exception leaves the server because it contains a stack trace. Server-side, the stack trace should be logged to the audit log and a description of the top level exception is added to the response object. This is processed in the client and coverted back into the same exception (minus stack trace) and returned to the client as if it was local to the server.
> 
> There are a couple of issues in the server side processing that is shown above.
> 
> * There should be a catch block for Throwable (or at least Exception) to ensure runtime errors are caught and processed.
> * The entry and exit logging should be using the `RESTCallLogger` rather than the SLF4J since the rest call logger sets up the thread name and times the call.
> 
> The RESTExceptionHandler provides methods for handling the common exceptions including logging runtime exceptions to the audit log.
> 
> ```
>     /**
>      * Files live on a file system.  This method creates a top level anchor for a file system.
>      *
>      * @param serverName name of calling server
>      * @param userId calling user
>      * @param requestBody properties of the file system
>      *
>      * @return unique identifier for the file system or
>      * InvalidParameterException one of the parameters is null or invalid or
>      * PropertyServerException problem accessing property server or
>      * UserNotAuthorizedException security access problem
>      */
>     public GUIDResponse   createFileSystemInCatalog(String                   serverName,
>                                                     String                   userId,
>                                                     NewFileSystemRequestBody requestBody)
>     {
>         final String methodName = "createFileSystemInCatalog";
> 
>         RESTCallToken token = restCallLogger.logRESTCall(serverName, userId, methodName);
> 
>         GUIDResponse response = new GUIDResponse();
>         AuditLog     auditLog = null;
> 
>         try
>         {
>             auditLog = instanceHandler.getAuditLog(userId, serverName, methodName);
> 
>             if (requestBody != null)
>             {
>                 FilesAndFoldersHandler<FileSystemProperties,
>                                        FolderProperties,
>                                        FileProperties> handler = instanceHandler.getFilesAndFoldersHandler(userId, serverName, methodName);
> 
>                 response.setGUID(handler.createFileSystem(userId,
>                                                           null,
>                                                           null,
>                                                           requestBody.getUniqueName(),
>                                                           requestBody.getDisplayName(),
>                                                           requestBody.getDescription(),
>                                                           requestBody.getFileSystemType(),
>                                                           requestBody.getVersion(),
>                                                           requestBody.getPatchLevel(),
>                                                           requestBody.getSource(),
>                                                           requestBody.getFormat(),
>                                                           requestBody.getEncryption(),
>                                                           requestBody.getAdditionalProperties(),
>                                                           null,
>                                                           methodName));
>             }
>         }
>         catch (InvalidParameterException error)
>         {
>             restExceptionHandler.captureInvalidParameterException(response, error);
>         }
>         catch (PropertyServerException error)
>         {
>             restExceptionHandler.capturePropertyServerException(response, error);
>         }
>         catch (UserNotAuthorizedException error)
>         {
>             restExceptionHandler.captureUserNotAuthorizedException(response, error);
>         }
>         catch (Throwable error)
>         {
>             restExceptionHandler.captureThrowable(response, error, methodName, auditLog);
>         }
> 
>         restCallLogger.logRESTCallReturn(token, response.toString());
> 
>         return response;
>     }
> ```

Well in the code you have now provided exactly that I am trying to suggest for SubjectAreaClients.

**Comment by immmus** [comment]
@mandy-chessell I also have a question for you. Why most of the classes in Egeria do not have interfaces. For example `RESTExceptionHandler`.  
After all, further expansion of logic is much easier if the class has interfaces. If we have dependencies on abstractions (interfaces), it is much easier to apply pattern (Decorator, Proxy, Adapter, etc.) than dependencies on classes.
