### ISSUE TITLE
Problems with Open Lineage configuration

### ISSUE THREAD

**Issue by immmus** [odpi/egeria#3537]
I decided to check how work Open Lineage and faced several problems:
1) When I initially started configuring the server I got this error:
<img width="1380" alt="Screenshot 2020-08-27 at 19 23 07" src="https://user-images.githubusercontent.com/35165540/91470179-0d5e1300-e89d-11ea-94ad-67ca8b3c9794.png">

I could not figure out what the problem and disable this check. 
2) Without the check I was able to configure and run the server with embedded berkeley db.
But when I decided to configure with cassandra I got this error:

<img width="1270" alt="Screenshot 2020-08-27 at 19 15 00" src="https://user-images.githubusercontent.com/35165540/91469814-93c62500-e89c-11ea-9cce-6809926a8fe8.png">
Although the database is not empty and some tables were even created in keyspace:
<img width="610" alt="Screenshot 2020-08-27 at 19 24 28" src="https://user-images.githubusercontent.com/35165540/91469986-cd972b80-e89c-11ea-92e3-06d72d4934b7.png">

Below can look cassandra config.
```
{
  "class":"OpenLineageConfig",
  "openLineageDescription":"Open Lineage Service is used for the storage and querying of lineage",
  "inTopicName":"test_topic",
  "openLineageBufferGraphConnection":{
    "class":"Connection",
    "displayName":"Buffer Graph Connection",
    "description":"Used for storing lineage in the Open Metadata format",
    "connectorType":{
      "class":"ConnectorType",
      "connectorProviderClassName":"org.odpi.openmetadata.openconnectors.governancedaemonconnectors.openlineageconnectors.janusconnector.buffergraph.BufferGraphConnectorProvider"
    },
    "configurationProperties":{
      "graphDB":"cassandra",
      "graphType":"bufferGraph",
      "storageBackend":"cql",
      "storageHostname": "127.0.0.1:9042",
      "username": "cassandra",
      "password": "cassandra",
      "clusterName":"Test Cluster",
      "storageCqlKeyspace":"buffer",
      "indexSearchBackend":"lucene"
    }
  },
  "openLineageMainGraphConnection":{
    "class":"Connection",
    "displayName":"Main Graph Connection",
    "description":"Used for storing lineage in a format optimized for querying lineage",
    "connectorType":{
      "class":"ConnectorType",
      "connectorProviderClassName":"org.odpi.openmetadata.openconnectors.governancedaemonconnectors.openlineageconnectors.janusconnector.maingraph.MainGraphConnectorProvider"
    },
    "configurationProperties":{
      "graphDB":"cassandra",
      "graphType":"Graph",
      "storageBackend":"cql",
      "storageHostname": "127.0.0.1:9042",
      "username": "cassandra",
      "password": "cassandra",
      "clusterName":"Test Cluster",
      "storageCqlKeyspace":"main",
      "indexSearchBackend":"lucene"
    }
  }
}
```

Please help me to understand these problems). And also help me understand how to use this service, because even with the configured berkeley I still could not get a single Lineage.

I must say right away that there were no problems in setting up a connection to cassandra for the repository, everything works fine.
<img width="933" alt="Screenshot 2020-08-27 at 19 42 06" src="https://user-images.githubusercontent.com/35165540/91470679-af7dfb00-e89d-11ea-9d4c-649b7bae416a.png">

**Comment by planetf1** [comment]
@immmus This area is in development. I've not actually set it up myself

Hopefully @lcpopa @danielaotelea @popa-raluca @lpalashevski can help - would be good to ensure we have some docs to help others understand the capabilities and set things up fully (I'd also like to extend the labs/other deployment work if we can)

**Comment by immmus** [comment]
> @immmus This area is in development. I've not actually set it up myself
> 
> Hopefully @lcpopa @danielaotelea @popa-raluca @lpalashevski can help - would be good to ensure we have some docs to help others understand the capabilities and set things up fully (I'd also like to extend the labs/other deployment work if we can)

Okay, I hope that they help me)

**Comment by planetf1** [comment]
See also [Data Engine Proxy](https://github.com/odpi/egeria/blob/master/open-metadata-implementation/admin-services/docs/concepts/data-engine-proxy.md) [Data Engine Proxy Services](https://github.com/odpi/egeria/tree/master/open-metadata-implementation/governance-servers/data-engine-proxy-services) and [Data Engine OMAS](https://github.com/odpi/egeria/tree/master/open-metadata-implementation/access-services/data-engine). There should be some updates especially around integration daemons soon.

Also @cmgrote may be able to comment further

**Comment by popa-raluca** [comment]
Hi @immmus ,

The first error appears because you want to use OLS on the same platform where you have configured another server with omases and/or local-graph. They can not be configured together on the same platform.

The second problem you have is because you're using an old configuration body for OLS. We recently did a big refactoring and changed the config part as well. Unfortunately the documentation was not updated yet, and the body from the README file is an old one. 
I'm not sure how it worked with berkeley db though, because there is only one graph inside OLS now, and it needs to be configured under "lineageGraphConnection" of the configuration body. 

You can use the below sample and adapt it for your cassandra config
`{
	"class": "OpenLineageConfig",
	"openLineageDescription": "Open Lineage Service is used for the storage and querying of lineage",
	"inTopicName": "server.omas.omas.assetlineage.outTopic",
	"openLineageWiki": "wiki URL",
	"jobIntervalInSeconds" : "120",
	"lineageGraphConnection":{
        "class": "Connection",
        "displayName": "Lineage Graph Connection",
        "description": "Used for storing lineage in the Open Metadata format",
        "connectorType":{
        	"class": "ConnectorType",
        	"connectorProviderClassName": "org.odpi.openmetadata.openconnectors.governancedaemonconnectors.openlineageconnectors.janusconnector.graph.LineageGraphConnectorProvider"
    	},
    "configurationProperties": {
            "gremlin.graph": "org.janusgraph.core.JanusGraphFactory",
            "storage.backend": "berkeleyje",
            "storage.directory": "./egeria-lineage-repositories/lineageGraph/berkeley",
            "index.search.backend": "lucene",
            "index.search.directory": "./egeria-lineage-repositories/lineageGraph/searchindex"
        }
    }
}`

**Comment by popa-raluca** [comment]
From the exception that you got it looks like you're using an old version of OLS, that still had the split between BufferGraph and MainGraph instead of a single LineageGraph. Please use what is now available on master for testing

**Comment by immmus** [comment]
> Hi @immmus ,
> 
> The first error appears because you want to use OLS on the same platform where you have configured another server with omases and/or local-graph. They can not be configured together on the same platform.
> 
> The second problem you have is because you're using an old configuration body for OLS. We recently did a big refactoring and changed the config part as well. Unfortunately the documentation was not updated yet, and the body from the README file is an old one.
> I'm not sure how it worked with berkeley db though, because there is only one graph inside OLS now, and it needs to be configured under "lineageGraphConnection" of the configuration body.
> 
> You can use the below sample and adapt it for your cassandra config
> `{ "class": "OpenLineageConfig", "openLineageDescription": "Open Lineage Service is used for the storage and querying of lineage", "inTopicName": "server.omas.omas.assetlineage.outTopic", "openLineageWiki": "wiki URL", "jobIntervalInSeconds" : "120", "lineageGraphConnection":{ "class": "Connection", "displayName": "Lineage Graph Connection", "description": "Used for storing lineage in the Open Metadata format", "connectorType":{ "class": "ConnectorType", "connectorProviderClassName": "org.odpi.openmetadata.openconnectors.governancedaemonconnectors.openlineageconnectors.janusconnector.graph.LineageGraphConnectorProvider" }, "configurationProperties": { "gremlin.graph": "org.janusgraph.core.JanusGraphFactory", "storage.backend": "berkeleyje", "storage.directory": "./egeria-lineage-repositories/lineageGraph/berkeley", "index.search.backend": "lucene", "index.search.directory": "./egeria-lineage-repositories/lineageGraph/searchindex" } } }`

Thank you for response I will try to configure to your recommendation.

**Comment by immmus** [comment]
> Hi @immmus ,
> 
> The first error appears because you want to use OLS on the same platform where you have configured another server with omases and/or local-graph. They can not be configured together on the same platform.
> 
> The second problem you have is because you're using an old configuration body for OLS. We recently did a big refactoring and changed the config part as well. Unfortunately the documentation was not updated yet, and the body from the README file is an old one.
> I'm not sure how it worked with berkeley db though, because there is only one graph inside OLS now, and it needs to be configured under "lineageGraphConnection" of the configuration body.
> 
> You can use the below sample and adapt it for your cassandra config
> `{ "class": "OpenLineageConfig", "openLineageDescription": "Open Lineage Service is used for the storage and querying of lineage", "inTopicName": "server.omas.omas.assetlineage.outTopic", "openLineageWiki": "wiki URL", "jobIntervalInSeconds" : "120", "lineageGraphConnection":{ "class": "Connection", "displayName": "Lineage Graph Connection", "description": "Used for storing lineage in the Open Metadata format", "connectorType":{ "class": "ConnectorType", "connectorProviderClassName": "org.odpi.openmetadata.openconnectors.governancedaemonconnectors.openlineageconnectors.janusconnector.graph.LineageGraphConnectorProvider" }, "configurationProperties": { "gremlin.graph": "org.janusgraph.core.JanusGraphFactory", "storage.backend": "berkeleyje", "storage.directory": "./egeria-lineage-repositories/lineageGraph/berkeley", "index.search.backend": "lucene", "index.search.directory": "./egeria-lineage-repositories/lineageGraph/searchindex" } } }`

Can you describe about this field `"inTopicName": "server.omas.omas.assetlineage.outTopic"`?? What is the topic?? And what is topic name should I give? It is topic event-bus??

**Comment by immmus** [comment]
@popa-raluca Can you describe about this field "inTopicName": "server.omas.omas.assetlineage.outTopic"?? What is the topic?? And what is topic name should I give? It is topic event-bus??

**Comment by popa-raluca** [comment]
It's the out topic for AssetLineage OMAS. 
OLS is processing events containing the lineage context from AssetLineage OMAS.
AL OMAS creates the context by listening to OMRS events for lineage related events - events that come from DataEngine OMAS that creates all the lineage relates entities and relationships to the graph repository.

We definitely need to update the documentation for all lineage related components, we will do this in the following weeks I think

**Comment by immmus** [comment]
> It's the out topic for AssetLineage OMAS.
> OLS is processing events containing the lineage context from AssetLineage OMAS.
> AL OMAS creates the context by listening to OMRS events for lineage related events - events that come from DataEngine OMAS that creates all the lineage relates entities and relationships to the graph repository.
> 
> We definitely need to update the documentation for all lineage related components, we will do this in the following weeks I think

Thanks! Yes, it would be nice to make the documentation.

**Comment by immmus** [comment]
> It's the out topic for AssetLineage OMAS.
> OLS is processing events containing the lineage context from AssetLineage OMAS.
> AL OMAS creates the context by listening to OMRS events for lineage related events - events that come from DataEngine OMAS that creates all the lineage relates entities and relationships to the graph repository.
> 
> We definitely need to update the documentation for all lineage related components, we will do this in the following weeks I think

I did everything as you said. I was able to start open lineage server but no events are coming and I still can't get the lineage.

I add glossary and terms and want to get Lineage from their. I dont know that I am doing wrong

**Comment by popa-raluca** [comment]
Do you have AssetLineage OMAS configured? Do you see any events being processed by AssetLineage? Any DEBUG messages available from AssetLineage or from OLS?
Maybe you can attach more details, it's hard to figure out what's happening otherwise

**Comment by immmus** [comment]
> Do you have AssetLineage OMAS configured? Do you see any events being processed by AssetLineage? Any DEBUG messages available from AssetLineage or from OLS?
> Maybe you can attach more details, it's hard to figure out what's happening otherwise

Yes, I have AssetLineage OMAS configured, but but no events pass. Okey I give you more details.

**Comment by immmus** [comment]
@popa-raluca 

It is debug logs -> https://gist.github.com/immmus/ddc02ba67bc41f12c93275c3a20b1217
OLS config -> https://gist.github.com/immmus/61ceefdffde32529a7430e8c2b25b7bd

**Comment by popa-raluca** [comment]
Where do you have AssetLineage configured? Can you send the config for it as well?
It looks like you have a wrong inTopicName configured for OLS, it should be the out topic of AssetLineage OMAS. So if you have AL configured to run on a server "omas_server" registered to the cohort, then the inTopicName is "OMRSTopic.server.omas-server.omas.assetlineage.inTopic".

**Comment by immmus** [comment]
> Where do you have AssetLineage configured? Can you send the config for it as well?
> It looks like you have a wrong inTopicName configured for OLS, it should be the out topic of AssetLineage OMAS. So if you have AL configured to run on a server "omas_server" registered to the cohort, then the inTopicName should be "server.omas-server.omas.assetlineage.inTopic".

Configuration in the comment above. Please look at it and show me the errors please. I apparently misunderstand something. Thank.

**Comment by popa-raluca** [comment]
> > Where do you have AssetLineage configured? Can you send the config for it as well?
> > It looks like you have a wrong inTopicName configured for OLS, it should be the out topic of AssetLineage OMAS. So if you have AL configured to run on a server "omas_server" registered to the cohort, then the inTopicName should be "server.omas-server.omas.assetlineage.inTopic".
> 
> Configuration in the comment above. Please look at it and show me the errors please. I apparently misunderstand something. Thank.

That configuration is for OLS. I'm asking abut AssetLineage OMAS(https://github.com/odpi/egeria/tree/master/open-metadata-implementation/access-services/asset-lineage)

You need to have a platform configured for OLS and a separate one for Asset Lineage OMAS. These two components communicate through the out topic of Asset Lineage, which is actually the in topic for OLS. I saw that you updated the variable to "server.omas-server.omas.assetlineage.inTopic". - do you have AL OMAS configured on a server called omas-server?

**Comment by immmus** [comment]
> > > Where do you have AssetLineage configured? Can you send the config for it as well?
> > > It looks like you have a wrong inTopicName configured for OLS, it should be the out topic of AssetLineage OMAS. So if you have AL configured to run on a server "omas_server" registered to the cohort, then the inTopicName should be "server.omas-server.omas.assetlineage.inTopic".
> > 
> > 
> > Configuration in the comment above. Please look at it and show me the errors please. I apparently misunderstand something. Thank.
> 
> That configuration is for OLS. I'm asking abut AssetLineage OMAS(https://github.com/odpi/egeria/tree/master/open-metadata-implementation/access-services/asset-lineage)
> 
> You need to have a platform configured for OLS and a separate one for Asset Lineage OMAS. These two components communicate through the out topic of Asset Lineage, which is actually the in topic for OLS. I saw that you updated the variable to "server.omas-server.omas.assetlineage.inTopic". - do you have AL OMAS configured on a server called omas-server?


```
{
                "class": "AccessServiceConfig",
                "accessServiceId": 1023,
                "accessServiceAdminClass": "org.odpi.openmetadata.accessservices.assetlineage.admin.AssetLineageAdmin",
                "accessServiceName": "Asset Lineage",
                "accessServiceFullName": "Asset Lineage OMAS",
                "accessServiceURLMarker": "asset-lineage",
                "accessServiceDescription": "Store asset lineage",
                "accessServiceWiki": "https://egeria.odpi.org/open-metadata-implementation/access-services/asset-lineage/",
                "accessServiceOperationalStatus": "ENABLED",
                "accessServiceInTopic": {
                    "class": "Connection",
                    "connectorType": {
                        "class": "ConnectorType",
                        "type": {
                            "class": "ElementType",
                            "elementTypeId": "954421eb-33a6-462d-a8ca-b5709a1bd0d4",
                            "elementTypeName": "ConnectorType",
                            "elementTypeVersion": 1,
                            "elementTypeDescription": "A set of properties describing a type of connector.",
                            "elementOrigin": "LOCAL_COHORT"
                        },
                        "guid": "3851e8d0-e343-400c-82cb-3918fed81da6",
                        "qualifiedName": "Kafka Open Metadata Topic Connector",
                        "displayName": "Kafka Open Metadata Topic Connector",
                        "description": "Kafka Open Metadata Topic Connector supports string based events over an Apache Kafka event bus.",
                        "connectorProviderClassName": "org.odpi.openmetadata.adapters.eventbus.topic.kafka.KafkaOpenMetadataTopicProvider",
                        "recognizedConfigurationProperties": [
                            "producer",
                            "consumer",
                            "local.server.id",
                            "sleepTime"
                        ]
                    },
                    "endpoint": {
                        "class": "Endpoint",
                        "address": "egeria.omag.server.cocoMDS4.omas.assetlineage.inTopic"
                    },
                    "configurationProperties": {
                        "producer": {
                            "bootstrap.servers": "localhost:9092",
                            "key.serializer": "org.apache.kafka.common.serialization.StringSerializer",
                            "value.serializer": "org.apache.kafka.common.serialization.StringSerializer",
                            "kafka.omrs.topic.id": "test_egeria"
                        },
                        "local.server.id": "125ccc1f-af30-4aed-8bce-3f8620be4098",
                        "consumer": {
                            "bootstrap.servers": "localhost:9092",
                            "key.deserializer": "org.apache.kafka.common.serialization.StringDeserializer",
                            "value.deserializer": "org.apache.kafka.common.serialization.StringDeserializer",
                            "kafka.omrs.topic.id": "test_egeria"
                        }
                    }
                },
                "accessServiceOutTopic": {
                    "class": "Connection",
                    "connectorType": {
                        "class": "ConnectorType",
                        "type": {
                            "class": "ElementType",
                            "elementTypeId": "954421eb-33a6-462d-a8ca-b5709a1bd0d4",
                            "elementTypeName": "ConnectorType",
                            "elementTypeVersion": 1,
                            "elementTypeDescription": "A set of properties describing a type of connector.",
                            "elementOrigin": "LOCAL_COHORT"
                        },
                        "guid": "3851e8d0-e343-400c-82cb-3918fed81da6",
                        "qualifiedName": "Kafka Open Metadata Topic Connector",
                        "displayName": "Kafka Open Metadata Topic Connector",
                        "description": "Kafka Open Metadata Topic Connector supports string based events over an Apache Kafka event bus.",
                        "connectorProviderClassName": "org.odpi.openmetadata.adapters.eventbus.topic.kafka.KafkaOpenMetadataTopicProvider",
                        "recognizedConfigurationProperties": [
                            "producer",
                            "consumer",
                            "local.server.id",
                            "sleepTime"
                        ]
                    },
                    "endpoint": {
                        "class": "Endpoint",
                        "address": "egeria.omag.server.cocoMDS4.omas.assetlineage.outTopic"
                    },
                    "configurationProperties": {
                        "producer": {
                            "bootstrap.servers": "localhost:9092",
                            "key.serializer": "org.apache.kafka.common.serialization.StringSerializer",
                            "value.serializer": "org.apache.kafka.common.serialization.StringSerializer",
                            "kafka.omrs.topic.id": "test_egeria"
                        },
                        "local.server.id": "125ccc1f-af30-4aed-8bce-3f8620be4098",
                        "consumer": {
                            "bootstrap.servers": "localhost:9092",
                            "key.deserializer": "org.apache.kafka.common.serialization.StringDeserializer",
                            "value.deserializer": "org.apache.kafka.common.serialization.StringDeserializer",
                            "kafka.omrs.topic.id": "test_egeria"
                        }
                    }
                }
            },
```

**Comment by immmus** [comment]
@popa-raluca 

UI config
<img width="463" alt="Screenshot 2020-08-31 at 13 59 00" src="https://user-images.githubusercontent.com/35165540/91713431-6f1ac780-eb92-11ea-9d5d-ffe97e394106.png">

And UI response:
<img width="1365" alt="Screenshot 2020-08-31 at 13 59 24" src="https://user-images.githubusercontent.com/35165540/91713454-77730280-eb92-11ea-862b-27ff6ab0bc02.png">

**Comment by popa-raluca** [comment]
Can you attach the debug logs for both AL OMAS and OLS to see what gets processed and if the components communicate?

**Comment by immmus** [comment]
> Can you attach the debug logs for both AL OMAS and OLS to see what gets processed and if the components communicate?

OLS log -> https://gist.github.com/immmus/79cd7151a5badf56ad7193e3586d1175
OMAS log -> https://gist.github.com/immmus/790c3cca0fcdc70eeabebff8e9f6ff96

**Comment by popa-raluca** [comment]
> > Can you attach the debug logs for both AL OMAS and OLS to see what gets processed and if the components communicate?
> 
> OLS log -> https://gist.github.com/immmus/79cd7151a5badf56ad7193e3586d1175
> OMAS log -> https://gist.github.com/immmus/790c3cca0fcdc70eeabebff8e9f6ff96
> 
> It is logs for get lineage


I need the logs from OLS and AssetLineage, not the UI. The get will not return anything if there is nothing added to the OLS graph. 
Please make sure to set the debug on true for these packages: org.odpi.openmetadata.accessservices.assetlineage(AL OMAS) and org.odpi.openmetadata.governanceservers.openlineage(OLS) and record what logging you get when you try to add the semantic assignments(or whatever are you trying to do..it's not clear)

**Comment by immmus** [comment]
> > > Can you attach the debug logs for both AL OMAS and OLS to see what gets processed and if the components communicate?
> > 
> > 
> > OLS log -> https://gist.github.com/immmus/79cd7151a5badf56ad7193e3586d1175
> > OMAS log -> https://gist.github.com/immmus/790c3cca0fcdc70eeabebff8e9f6ff96
> > It is logs for get lineage
> 
> I need the logs from OLS and AssetLineage, not the UI. The get will not return anything if there is nothing added to the OLS graph.
> Please make sure to set the debug on true for these packages: org.odpi.openmetadata.accessservices.assetlineage(AL OMAS) and org.odpi.openmetadata.governanceservers.openlineage(OLS) and record what logging you get when you try to add the semantic assignments(or whatever are you trying to do..it's not clear)

I didn’t give you any logs from the UI. It were logging from backend with logging.level.root=DEBUG.

Now my logging settings:
<img width="669" alt="Screenshot 2020-08-31 at 18 58 30" src="https://user-images.githubusercontent.com/35165540/91741074-dd747f80-ebbc-11ea-8f3f-a90dd9351cf1.png">


OMRS logs:
```
19:01:12.202 [Information View OMRSTopicListener] INFO  o.o.o.a.i.e.EventPublisher - Event is ignored as the relationship is not a semantic assignment for a column
19:01:48.269 [Information View OMRSTopicListener] INFO  o.o.o.a.i.e.EventPublisher - Event is ignored as the relationship is not a semantic assignment for a column
19:02:10.226 [Information View OMRSTopicListener] INFO  o.o.o.a.i.e.EventPublisher - Event is ignored as the relationship is not a semantic assignment for a column
19:02:47.209 [https-jsse-nio-9444-exec-7] INFO  o.o.o.a.r.g.r.GraphOMRSMetadataCollection - findEntitiesByProperty: for type Connection found no entities
19:02:47.216 [https-jsse-nio-9444-exec-7] INFO  o.o.o.a.r.g.r.GraphOMRSMetadataCollection - findEntitiesByProperty: for type VirtualConnection found no entities
19:02:47.479 [https-jsse-nio-9444-exec-7] INFO  o.o.o.a.r.g.r.GraphOMRSMetadataCollection - findEntitiesByProperty: for type Endpoint found no entities
19:02:47.742 [https-jsse-nio-9444-exec-7] ERROR o.o.o.a.r.g.r.GraphOMRSMetadataStore - getEntitySummaryFromStore entity with GUID 108b85fe-d7b8-45c3-9fb8-742ac4e4fb14 not found
19:02:47.757 [https-jsse-nio-9444-exec-7] INFO  o.o.o.a.r.g.r.GraphOMRSMetadataCollection - findEntitiesByProperty: for type ConnectorType found 1 entities
19:02:47.857 [Information View OMRSTopicListener] INFO  o.o.o.a.i.e.EventPublisher - Event is ignored as the relationship is not a semantic assignment for a column
19:02:48.068 [Information View OMRSTopicListener] INFO  o.o.o.a.i.e.EventPublisher - Sending event class org.odpi.openmetadata.accessservices.informationview.events.UpdatedEntityEvent to information view out topic
19:02:48.079 [Information View OMRSTopicListener] INFO  o.o.o.a.i.e.EventPublisher - Event is ignored as the relationship is not a semantic assignment for a column
19:02:48.125 [https-jsse-nio-9444-exec-7] INFO  o.o.o.a.r.g.r.GraphOMRSMetadataCollection - findEntitiesByProperty: for type Application found no entities
19:02:48.132 [https-jsse-nio-9444-exec-7] INFO  o.o.o.a.r.g.r.GraphOMRSMetadataCollection - findEntitiesByProperty: for type EnterpriseAccessLayer found no entities
19:02:48.139 [https-jsse-nio-9444-exec-7] INFO  o.o.o.a.r.g.r.GraphOMRSMetadataCollection - findEntitiesByProperty: for type Engine found no entities
19:02:48.147 [https-jsse-nio-9444-exec-7] INFO  o.o.o.a.r.g.r.GraphOMRSMetadataCollection - findEntitiesByProperty: for type MetadataIntegrationCapability found no entities
19:02:48.167 [https-jsse-nio-9444-exec-7] INFO  o.o.o.a.r.g.r.GraphOMRSMetadataCollection - findEntitiesByProperty: for type DatabaseManager found no entities
19:02:48.181 [https-jsse-nio-9444-exec-7] INFO  o.o.o.a.r.g.r.GraphOMRSMetadataCollection - findEntitiesByProperty: for type SoftwareServerCapability found 1 entities
19:02:48.189 [https-jsse-nio-9444-exec-7] INFO  o.o.o.a.r.g.r.GraphOMRSMetadataCollection - findEntitiesByProperty: for type CohortMember found no entities
19:02:48.191 [Information View OMRSTopicListener] INFO  o.o.o.a.i.e.EventPublisher - Event is ignored as the relationship is not a semantic assignment for a column
19:02:48.197 [https-jsse-nio-9444-exec-7] INFO  o.o.o.a.r.g.r.GraphOMRSMetadataCollection - findEntitiesByProperty: for type NetworkGateway found no entities
19:02:48.205 [https-jsse-nio-9444-exec-7] INFO  o.o.o.a.r.g.r.GraphOMRSMetadataCollection - findEntitiesByProperty: for type OpenDiscoveryEngine found no entities
19:02:48.299 [Information View OMRSTopicListener] INFO  o.o.o.a.i.e.EventPublisher - Event is ignored as the relationship is not a semantic assignment for a column
19:02:48.506 [Information View OMRSTopicListener] INFO  o.o.o.a.i.e.EventPublisher - Event is ignored as the relationship is not a semantic assignment for a column
```

OLS logs:

```
19:02:25.473 [DefaultQuartzScheduler_Worker-2] DEBUG o.o.o.g.o.scheduler.LineageGraphJob - Run QuartzJob at 2020-08-31T19:02:25.473084
19:04:25.472 [DefaultQuartzScheduler_Worker-3] DEBUG o.o.o.g.o.scheduler.LineageGraphJob - Run QuartzJob at 2020-08-31T19:04:25.472249
19:06:25.471 [DefaultQuartzScheduler_Worker-4] DEBUG o.o.o.g.o.scheduler.LineageGraphJob - Run QuartzJob at 2020-08-31T19:06:25.471928
```


I did create Glossary -> Two terms -> Related term relationship between terms -> Asset -> SemanticAssignment between Asset and term.

**Comment by popa-raluca** [comment]
Hi @immmus ,

It's pretty hard to investigate this way. Maybe you want to join our weekly developers call on Thursday. This way we can discuss and understand your use case and what you want to achieve, so we can guide you more in the right direction.

Below are the details for the conference:
 
10 am (UK); 11 am (Amsterdam/CET); 12pm (Bucharest)

Zoom Conference https://zoom.us/j/523629111

**Comment by immmus** [comment]
> Hi @immmus ,
> 
> It's pretty hard to investigate this way. Maybe you want to join our weekly developers call on Thursday. This way we can discuss and understand your use case and what you want to achieve, so we can guide you more in the right direction.
> 
> Below are the details for the conference:
> 
> 10 am (UK); 11 am (Amsterdam/CET); 12pm (Bucharest)
> 
> Zoom Conference https://zoom.us/j/523629111

Hi!
Okay I will try to join weekly developers call. But I have badly speak and listen english...

**Comment by planetf1** [comment]
Did you manage to get this sorted @immmus

**Comment by immmus** [comment]
> Did you manage to get this sorted @immmus

Yes. Let's close this:)
