### ISSUE TITLE
server chassis issues in containers - regression for 2.2 & master

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#3540]
```
Configuring cocoMDS1...
   ... configuring the platform the server will run on...
   ...... (POST https://lab-dev:9443/open-metadata/admin-services/users/garygeeke/servers/cocoMDS1/server-url-root?url=https://lab-datalake:9443 )
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-11-3a3bd59f8553> in <module>
      7 print("Configuring " + mdrServerName + "...")
      8 
----> 9 configurePlatformURL(adminPlatformURL, adminUserId, mdrServerName, mdrServerPlatform)
     10 configureMaxPageSize(adminPlatformURL, adminUserId, mdrServerName, maxPageSize)
     11 clearServerType(adminPlatformURL, adminUserId, mdrServerName)

<ipython-input-3-82e673aa31dc> in configurePlatformURL(adminPlatformURL, adminUserId, serverName, serverPlatform)
    156     print("   ... configuring the platform the server will run on...")
    157     url = adminCommandURLRoot + serverName + '/server-url-root?url=' + serverPlatform
--> 158     postAndPrintResult(url)
    159 
    160 def configureMaxPageSize(adminPlatformURL, adminUserId, serverName, maxPageSize):

<ipython-input-3-82e673aa31dc> in postAndPrintResult(url, json, headers)
    150     print("   ...... (POST", url, ")")
    151     response = requests.post(url, json=json, headers=headers)
--> 152     print("   ...... Response: ", response.json())
    153 
    154 def configurePlatformURL(adminPlatformURL, adminUserId, serverName, serverPlatform):

/opt/conda/lib/python3.8/site-packages/requests/models.py in json(self, **kwargs)
    896                     # used.
    897                     pass
--> 898         return complexjson.loads(self.text, **kwargs)
    899 
    900     @property

/opt/conda/lib/python3.8/json/__init__.py in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    355             parse_int is None and parse_float is None and
    356             parse_constant is None and object_pairs_hook is None and not kw):
--> 357         return _default_decoder.decode(s)
    358     if cls is None:
    359         cls = JSONDecoder

/opt/conda/lib/python3.8/json/decoder.py in decode(self, s, _w)
    335 
    336         """
--> 337         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338         end = _w(s, end).end()
    339         if end != len(s):

/opt/conda/lib/python3.8/json/decoder.py in raw_decode(self, s, idx)
    353             obj, end = self.scan_once(s, idx)
    354         except StopIteration as err:
--> 355             raise JSONDecodeError("Expecting value", s, err.value) from None
    356         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

This is in the containers
... investigating

**Comment by planetf1** [comment]
This fails in a container, but works ok locally.

Suspect there is an issue with the docker image.

**Comment by planetf1** [comment]
```
jonesn:egeria/ (egeria-release-2.2) $ http --verify=no POST https://158.176.66.121:30082/open-metadata/admin-services/users/garygeeke/servers/cocoMDS1/server-url-root\?url\=https://lab-datalake:9443
HTTP/1.1 401
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Connection: keep-alive
Content-Length: 0
Date: Fri, 28 Aug 2020 09:54:34 GMT
Expires: 0
Keep-Alive: timeout=60
Pragma: no-cache
Set-Cookie: JSESSIONID=D90FA88B1E4E2F58B9F44E312264D985; Path=/; Secure; HttpOnly
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
WWW-Authenticate: Basic realm="Realm"
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block



jonesn:egeria/ (egeria-release-2.2) $ http --verify=no POST https://localhost:9445/open-metadata/admin-services/users/garygeeke/servers/cocoMDS1/server-url-root\?url\=https://lab-datalake:9443
HTTP/1.1 200
Connection: keep-alive
Content-Type: application/json
Date: Fri, 28 Aug 2020 09:54:46 GMT
Keep-Alive: timeout=60
Transfer-Encoding: chunked

{
    "class": "VoidResponse",
    "relatedHTTPCode": 200
}
```

**Comment by planetf1** [comment]
Interestingly on the same platform, an attempt to get to the REST api docs (swagger) at https://111.222.111.222:30080/swagger-ui.html results in:
<img width="892" alt="Screenshot 2020-08-28 at 11 02 06" src="https://user-images.githubusercontent.com/7292002/91548909-0deabe00-e91e-11ea-85c7-8b2244a2a4a1.png">

**Comment by planetf1** [comment]
Meanwhile swagger locally is also failing - not found? (odd):

<img width="663" alt="Screenshot 2020-08-28 at 11 09 46" src="https://user-images.githubusercontent.com/7292002/91549568-0c6dc580-e91f-11ea-8aa8-27d498b7797a.png">

**Comment by planetf1** [comment]
Somehow the image running in k8s appears to have security enabled. This looks like the default spring security challenge.

**Comment by planetf1** [comment]
Problem located.....

Egeria fails once LOADER_PATH is set to include the 'lib' directory of dependencies.
As noted when we did the assembly, we pull in ALL dependencies for all modules in the assembly due to deficiencies in the plugin. Clearly one of more of these dependencies is being pulled into the classpath and affecting the chassis configuration severely

The challenge now is how to address.

Reverting the assembly change to use uber jars is possible, but brings it's own challenges
Switching to gradle may offer more flexibility, but there's a lot to do first
Revisiting our strategy for dynamic loading may be needed
Ad-hoc stripting to manipulate the assembly pos-creation may be possible, but very tricky tro do without being platform specific. Maybe the groovy plugin could help.

Will consider best short term and long term fix
cc: @mandy-chessell

**Comment by immmus** [comment]
> Interestingly on the same platform, an attempt to get to the REST api docs (swagger) at https://111.222.111.222:30080/swagger-ui.html results in:
> <img alt="Screenshot 2020-08-28 at 11 02 06" width="892" src="https://user-images.githubusercontent.com/7292002/91548909-0deabe00-e91e-11ea-85c7-8b2244a2a4a1.png">

Swagger UI work only with this url https://localhost:9444/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config#/
I dont know why this is such. Such work after 1.8.

<img width="1395" alt="Screenshot 2020-08-31 at 14 06 56" src="https://user-images.githubusercontent.com/35165540/91714057-9d4cd700-eb93-11ea-9b88-38b4fe89762e.png">

**Comment by planetf1** [comment]
Yes I was aware of that - mentioned swagger above. Unfortunately :-(

I plan to look at this tomorrow (it's a public holiday today in uk)  - the cause was a change to packaging which is bringing in some additional things in the classpath which are changing the behaviour of spring security amongst other things.

**Comment by planetf1** [comment]
Made a change to drop the additional dependencies - as this is a one line change

The impact of this is
 - discovery notebook will fail
 - Dynamically loadable additional connectors will fail

However it would get people working again with containers.

If this helps, I will look at pushing a PR .... and then looking at better fixes.

**Comment by planetf1** [comment]
The graph repo tests completed successfully.
