### ISSUE TITLE
Changed to java.util.concurrent Collections and removed unnecessary syncs.

### ISSUE THREAD

**Issue by immmus** [odpi/egeria#3583]
Hello!

As I already wrote, I replaced your self-written queue with a queue specially designed for such tasks from the standard Java library (BlockingDeque). I also removed synchronizations from the KafkaOpenMetadataEventConsumer class by replacing the usual HashMap with ConcurrentHashMap that provide concurrent access using atomic methods and do not require additional synchronization. At the same time, they work much faster than just synchronized collections.

**Comment by immmus** [comment]
@planetf1 Please to assign @mandy-chessell and @davidradl too

**Comment by immmus** [comment]
Open

**Comment by davidradl** [comment]
@wbittles @planetf1  I am wondering where we are with this one? It looks like there is a fix for this. Can we merge or reject this please?
