### ISSUE TITLE
Minimise the CTS mandatory profile

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#3584]
From discussion on today's functionality call we discussed the existing mandatory profile (metadata sharing) of the CTS.

We suggested that we should further minimise the mandatory profile for CTS, to ensure it focuses purely on ensuring that no problems are introduced to the cohort.  This means we should be able to move the various `find...` methods into optional profiles rather than keeping them in the existing mandatory profile.

(The mandatory profile should instead be primarily about properly handling the cohort registration / type verification methods.)

**Comment by grahamwallis** [comment]
Fixed by #4298
