### ISSUE TITLE
Analytics modeling client - no code, packaging warning

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#3606]
When publishing the 2.2 release in https://github.com/odpi/egeria/issues/3518 we get a warning:

```
2020-09-13T09:49:36.2977485Z RESULT - Sync analytics-modeling-client:2.2 = {"message":"In order to sync to Maven Central your package must be included in the JCenter repository"}
```

This is because the pom for this module says it is a jar, yet there is no code present.

Is the intent to add client code? If so let's leave as is.
In general with a module if there isn't code it should be removed -- however this would be inconsistent with other OMASs

**Comment by planetf1** [comment]
^ @yevgenmar

**Comment by planetf1** [comment]
@yevgenmar is there a plan to add a client?

**Comment by yevgenmar** [comment]
Hi Nigel,

I did not have plan for client. As part of documentation I would like to have postman collection as example how to use the OMAS.

Sincerely Yevgeniy

________________________________

**Comment by planetf1** [comment]
The postman collection would be useful... I think if we have a general purpose interface we should really have a client, as this is consistent with our other OMASs.

Whilst in development it's inevitable the implementation is incomplete, but as we get it closer to released status I think then we should look at it

However if there is consensus we don't need/want a client then we can remove the stub build files to avoid the initial error above.

A long time ago we put together some guidelines for OMASs though having read them they are only rough notes, and as a community we need to improve! (fyi https://github.com/odpi/egeria/blob/master/developer-resources/standards-for-omas-implementations.md )

**Comment by planetf1** [comment]
FYI error from publishing build 2.4:
```
Hi planetf1,

Thank you for submitting this request,

JCenter follows the maven convention. In addition to the .jar and .pom file, your version should include a sources jar, and optionally a javadoc jar.

Your files should be under a maven path layout.
(See https://www.jfrog.com/confluence/display/BT/Central+Repositories+New+UI#CentralRepositoriesNewUI-JCenter)

```

**Comment by planetf1** [comment]
If there is no need, and no intent, to provide a client, I suggest that module is removed.

**Comment by planetf1** [comment]
If it's intended to implement this I suggest leaving it open, otherwise please feel free to close @yevgenmar
