### ISSUE TITLE
Subject area omas default qualified name if not specified on entity creates

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#3619]

**Comment by davidradl** [comment]
@immmus I think we talked about you defaulting the qualified name for creates - I could not find the issue for this - so I have raised this issue. I need to do this, this week; so if it is ok with you I will do this? Shout quickly if you really want to do it :-)

**Comment by immmus** [comment]
> @immmus I think we talked about you defaulting the qualified name for creates - I could not find the issue for this - so I have raised this issue. I need to do this, this week; so if it is ok with you I will do this? Shout quickly if you really want to do it :-)

Hi @davidradl !:)
Yes I remember that we told about this:), but I in weekend now so you do it:). I can review your pr.

**Comment by davidradl** [comment]
@immmus :-) Will do

**Comment by immmus** [comment]
> @immmus :-) Will do

I want to ask to you, when you merge this pr https://github.com/odpi/egeria/pull/3493 ??

**Comment by davidradl** [comment]
Some background. There is a code going into Egeria that will police the uniqueness of qualified names. So this issue is to ensure that glossary terms that, when the user has not specified a qualified name, the Subject Area OMAS will associate a unique value for the qualified name.
