### ISSUE TITLE
Port in-memory cohort demo to k8s

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#363]
In in-memory cohort demo is a potentially interesting way to show two egeria repositories 
working together (thanks @davidradl ), and to allow interested parties to experiment

To align with demo deployments of other components, I would propose making this into a helm chart
Ideally we can reuse the existing egeria image. Or if not this scenario will demostrate configurability needed in that image. 

I would run the two participants in the cohort in seperate pods,

**Comment by mandy-chessell** [comment]
Could we rename this demo to be called something like "simple kafka cohort" rather than "in-memory cohort" since the demo is about the cohort interaction not the in-memory repository (which could be demoed with only one server).

**Comment by planetf1** [comment]
I suspect this is now superceeded by #1273 (infrastructure) + our new notebooks. 
Closing
