### ISSUE TITLE
Add new addMultipleTerms call to Glossary author

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#3660]
Add new admin services to Glossary author view addBulkTerms. this will be an API that will take an object of shape:
{
    glossaryGuid: {glossaryguid}
    terms: [ {name:{name}, description:{description}, ... ]
}
It will return an object which is the same as the request, but each Term will have addition 
- status of success, error
- an optional msg, which is filled in on error
- the guid of the created term.

**Comment by davidradl** [comment]
I am developing the addBulkTerms call in the view service. I realised that I wanted to track the responses of each Term  create and also return a response object in case the overall course grained API failed.

I started looking at an API Shape of 

`   @PostMapping(path = "/{guid}/terms")
    public SubjectAreaOMASAPIResponse<SubjectAreaOMASAPIResponse<Term>> createBulkTermsInAGlossary(@PathVariable String serverName,
                                                                                                   @PathVariable String userId,
                                                                                                   @PathVariable String glossaryGUID,
                                                                                                   @RequestBody  Terms[] terms

                                                                                                  ) {
      ....
    }`

The server does not accept any calls to this. @immmus  Any thoughts on what I am doing wrong? The alternative is that I do not reuse SubjectAreaOMASAPIResponse<Term> in the response, but create other objects maybe a TermResponses object containing TermResponse elements. With TermResponse containing Term and a response status.

**Comment by davidradl** [comment]
@immmus it looks like a typo guid does not match glossaryGUID!

**Comment by immmus** [comment]
> @immmus it looks like a typo guid does not match glossaryGUID! Working now.

Yes, problem with parameter name (glossaryGUID). You need to change name to "guid'.

**Comment by davidradl** [comment]
> > @immmus it looks like a typo guid does not match glossaryGUID! Working now.
> 
> Yes, problem with parameter name (glossaryGUID). You need to change name to "guid'.

Thanks - as soon as I put up the question I spotted the issue! I hope you are ok to review the PR; it might be a pattern that we could use more widely.

**Comment by davidradl** [comment]
Separating the issues out so this issue just does addMultipleterms
