### ISSUE TITLE
Release Note content for release 2.3

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#3669]
Adding release note content for the release.
Dino is one candidate.
Others TBD.
Will place PR in draft mode for now

**Comment by davidradl** [comment]
I am looking at https://github.com/odpi/egeria/blob/master/open-metadata-implementation/user-interfaces/presentation-server/README.md. It shows as "EGERIA_PRESENTATIONSERVER_SERVER_<ui server name> when the is the tenants". It has taken the angled bracket content between " the" and "is" as a tag and not displayed it, can we escape the < and  > somehow in mark down with a back tick as correction in the release notes.

**Comment by planetf1** [comment]
thanks. I'll make the updates and push later

**Comment by planetf1** [comment]
this has been completed
