### ISSUE TITLE
OMRS getEntityNeighbourhood improvements

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#369]
I suggest that the OMRS Enterprise layer getEntityNeighbourhood code, tries the getEntityNeighbourhood call on each of the repositories in turn, if it succeeds this means that the repository has an implementation of this method. It the call fails with a Method not defined return code then we should try the next repository. There are other return code like user not authorised that would mean that the next repository should be tried. There are also non-retriable return codes - the Enterprise omrs connector addRelationship code for inspiration. 

If all the repositories fail with an error like method not defined, then try each repository, with a recursive algorithm to issue getRelationshipsForEntity. This is a more inefficient way of getting this call processed - but allows the call to proceed with a repository that has getEntityRelationships implemented but not getEntityNeighbourhood . See #350 for an example of how to do this recursive algorithm.

**Comment by mandy-chessell** [comment]
This approach would be good if no repositories had native graph support.  As it is , it is better to push doen the graph queries to each repository and let the graph engines support them.  Any organization making use of these queries need to ensure that the right metadata is replicating into the graph repositories.
