### ISSUE TITLE
View Service configuration update should not create another instance of the service

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#3717]

**Comment by grahamwallis** [comment]
When submitted (modified) configuration for a view service that is already configured, the new configuration properties should update/replace the existing service rather than creating a configuration for another instance of the service.

**Comment by mandy-chessell** [comment]
I think I have fixed this already ... - its in #3707

**Comment by grahamwallis** [comment]
Confirmed - looks like Mandy has a fix lined up in #3707, as seen in the following code change to OMAGServerAdminForViewServices:

![image](https://user-images.githubusercontent.com/17125304/94917973-8575b500-04a9-11eb-9fc6-5f72d2d596c9.png)
