### ISSUE TITLE
Extraction of the Egeria UI under egeria-ui repository

### ISSUE THREAD

**Issue by sarbull** [odpi/egeria#3722]
# Introduction

The master plan for this issue is to actually create a Web Components Skeleton on where you can load web-components so we can start delivering feature driven web components regardless of the framework being used(react, angular, vue, polymer).

The first baby steps would be to extract the UI in a separate project/repository and create a mock server that can be used for demos and future presentations on maybe new upcoming features.

We should start thinking about features as being an actual web component that can be loaded in the skeleton opened under some sort of widget based form.

For this matter two new repositories have been created, one is called egeria-ui[0] which will be used for the user interfaces and egeria-api-mocks[1] which will mock the API Enpoints that are currenlty up and running.

In order to achieve this, the easiest way is to use an API Gateway, for this reason i picked Zuul, which is coming from the Spring Cloud Stack and it is used in many projects (@netflix/zuul ~10k stars).

# Extracting the UI
![UI Extraction](https://user-images.githubusercontent.com/1864112/94788157-de771780-03db-11eb-872f-2881b0c16e46.png)

# Common workflow
![API Schema](https://user-images.githubusercontent.com/1864112/94788480-47f72600-03dc-11eb-8cb2-21095df6a2c8.png)

# Common workflow with mocks
![API Schema with mock](https://user-images.githubusercontent.com/1864112/94789007-116ddb00-03dd-11eb-88b0-6d730416877c.png)

[0] - http://github.com/odpi/egeria-ui
[1] - http://github.com/odpi/egeria-api-mocks

**Comment by sarbull** [comment]
i will continue with the extraction since there are no other comments in regards to the approach

**Comment by planetf1** [comment]
Currently the UI is not functional in master with the static removals.

As such, as soon as is reasonable we could do with some docs (just notes) showing how to get it to run.
By release time (within two weeks for 2.4) we need to do one of
 - Have the static content fully built and working
 - ensure it is referenced in the main egeria code
 - ensure our deployment e it via launching the chassis, running our container environments are working
 - AND/OR decide to drop various of those capabilities 
 - update the egeria release notes accordingly.

**Comment by sarbull** [comment]
@planetf1 we can close this after updating the READMEs in `odpi/egeria-ui` and `odpi/egeria` and stick with #3892 and #3884
