### ISSUE TITLE
"saveInstanceReferenceCopies" never called in real OMRSMetadataCollection

### ISSUE THREAD

**Issue by jnhagelberg** [odpi/egeria#3726]
The problem here is that `LocalOMRSMetadataCollection` does not override `saveInstanceReferenceCopies`, so the default implementation, which splits the BATCH_INSTANCES_EVENT into individual EntityDetails and Relationships is always used.

The problem with this is that it prevents implementations from leveraging the presence of multiple messages to optimize the message processing.  They have no way of knowing that the message was part of a batch.  They still have to process the messages one at a time.  This is every slow, since the for us processing of each message results in an update to a cloudant document along with a bunch of locking.  For our use case, in most cases all of the messages in the batch end up updating the same cloudant document, so being able to process all of the messages from the batch together will give us a big performance boost.

Doing this is very straight forward.  I will be submitting a PR with the change shortly.

**Comment by wbittles** [comment]
Hi Jeff, 
it would really help with a review if you could provide a bit of background context Not only will it speed up the review it will also help other users know when to switch to batch processing. 
For instance 
1) Describe the use case that generates the workload, this will help other users know what type of scenario would justify the switch to batch processing.
2)  Why is the change a performance fix, (what path lengths/ locks/copies etc)  are removed by this fix. This will give some clue  on how switching to batch processing will impact the relevant use cases and environments.

**Comment by planetf1** [comment]
We're already on the final stages of shipping 2.3 which was cut nearly a week ago - pretty much in line with prior releases.
Therefore whilst I think this change has merit, I would agree with @wbittles and target master (and 2.4) only.

**Comment by jnhagelberg** [comment]
@wbittles In the `cp4d` use case, we are using egeria to sync metadata between different systems.  The most typical scenario is when someone imports the metadata for bunch of relational tables and they all need to be synced over.  As I'm sure you know, it takes many entities/relationships to sync table.  There are 3 entities and 2 relationships for the table itself and about 2 entities and relationships per column.   To sync a table with 20 columns, there are about 85 entities/relationships we need to process.  We are already using the BATCH event to send all 85 entities/relationships.  However, right now egeria only provides them to us one at a time.  This results in 85 different updates to the document where we are storing the table.

However, if egeria provided us the entire batch at once, would be able to consolidate the logic, completely assemble the table in memory, and save it using just one call to cloudant.
