### ISSUE TITLE
Presentation Server pom is invalid for distribution

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#3750]
Maven artifacts that are distributed to maven central or JCenter need to satisfy certain criteria. Specifically they need to include
 - Source code
 - compiled code
 - javadoc
For default artifact type 'jar'.

As such, the current artifact will not distribute upstream. This is not necessarily an issue unless another project tries to consume the artifact, though we do know of at least one team that try to assemble their environment using the artifacts.

Additionally, if we move to gradle, there is a greater separation between build and publish

In any case we should ideally ensure the error does not occur in the release process.
We should consider how to bundle the presentation server code in a maven project & update accordingly.

**Comment by planetf1** [comment]
See #3675

**Comment by davidradl** [comment]
fyi @jmmadsen

**Comment by planetf1** [comment]
Having branched for 2.4 it would be good to have done this.
However the impact is just that there is no maven package for presentation server. Since we won't have code dependencies on it I don't think it's serious, though if anyone is composing a deployment using maven artifacts they won't be able to. In theory the maven artifact should contain the source & built code for PS (ie a war)
I think a better long term solution is probably to move the node/js based code out of egeria, but that's a broader discussion

**Comment by planetf1** [comment]
To confirm, this occurred when setting up publishing for this artifact for 2.4
```
Hi planetf1,

Thank you for submitting this request,

JCenter hosts java applications that follow maven convention. In addition to the binary jar file and the .pom file, your version should include a sources jar, and optionally a javadoc jar.

Your files should be under a maven path layout.

Once those files are added, we'll be glad to include your package in JCenter.
```

Arguably this isn't that useful as a maven artifact, however our current process is 100% maven artifacts
