### ISSUE TITLE
Partial build of any module depending on assembly not possible - requires full build

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#3752]
In our maven build, a number of modules including fvt & containers are dependent on having a valid assembly.

A full maven build works fine.

However if I for example try to build the data manager fvt only - having previously done a full build - I see:
```
$ mvn install                                         [17:08:06]
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< org.odpi.egeria:data-manager-fvt >------------------
[INFO] Building Data Manager OMAS FVT 2.4-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.871 s
[INFO] Finished at: 2020-10-05T17:08:12+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project data-manager-fvt: Could not resolve dependencies for project org.odpi.egeria:data-manager-fvt:jar:2.4-SNAPSHOT: Could not find artifact org.odpi.egeria:open-metadata-assemblies:pom:distribution:2.4-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

```
I would have expected this dependency to be available in my local ~/.m2 - but it's possible maven insists it is available in the reactor.

This makes quicker builds increasingly difficult. Gradle addresses this issue but currently does not handle execution of FVT., packaging, spring apps, or assembly.

**Comment by grahamwallis** [comment]
This behaviour changed a couple of months ago. Module-specific builds used to work until then. I am not sure what caused the change.

**Comment by planetf1** [comment]
Before the assembly wasn't correct, as the build was out of order. This was due to the assembly not expressing dependencies on the modules it contains, and any consumers of the assemblies not expressing a dependency (this also prevents circular dependencies which we had before and obscurely led to a version of code N-1 being included...)

That was the intent, but in the process you are are correct, this was introduced.. which I'll look how to correct but need to preserve correctness

**Comment by planetf1** [comment]
When an assembly is built by the assembly plugin, the docs at https://maven.apache.org/plugins/maven-assembly-plugin/faq.html state
```
Can I use an artifact created by the assembly plugin as a dependency?
Yes. You can refer to it using the id of the assembly as the dependency classifier.
```
Our 3 assemblies are called
```
jonesn:assemblies/ (issue3752) $ cat *xml | grep '<id>'                                                                                           [16:48:40]
    <id>deploy</id>
    <id>distribution</id>
    <id>presentation-server</id>

```
So in the docker (for example) component build we express a dependency as:
```
    <!-- Use assemblies as built for distribution -->
    <dependencies>
        <dependency>
            <groupId>org.odpi.egeria</groupId>
            <artifactId>open-metadata-assemblies</artifactId>
            <classifier>distribution</classifier>
            <type>pom</type>
        </dependency>
    </dependencies>
```
but trying to build standalone will fail (as above) and a manual attempt to get the dependency OUTSIDE A FULL BUILD also fails ie:
```
jonesn:egeria/ (issue3752) $ mvn dependency:get -DgroupId=org.odpi.egeria -DartifactId=open-metadata-assemblies -Dversion=2.4-SNAPSHOT -Dclassifier=egeria-omag -Dpackaging=pom -Ddest=/tmp/
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------< org.odpi.egeria:open-metadata-docker-egeria >-------------
[INFO] Building Docker image - Egeria 2.4-SNAPSHOT
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:3.1.2:get (default-cli) @ open-metadata-docker-egeria ---
[INFO] Resolving org.odpi.egeria:open-metadata-assemblies:pom:egeria-omag:2.4-SNAPSHOT with transitive dependencies
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.631 s
[INFO] Finished at: 2020-10-07T16:56:39+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.2:get (default-cli) on project open-metadata-docker-egeria: Couldn't download artifact: org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact org.odpi.egeria:open-metadata-assemblies:pom:egeria-omag:2.4-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
jonesn:egeria/ (issue3752) $ 

```
The original specification looks correct, and indeed appears to correctly resolve when all projects are part of the reactor. It however fails when they are not, slightly odd as those classifiers should be present in ~/.m2

However crucially the precise prereq spec isn't really needed for the dependencies, there we just need to ensure the module is built (assuming no-one removes an artifact with a particular classifier of course!) it's only potentially relevant in a few cases, such as actually creating an assembly where we want to select a particular artifact.

As such I've modified the dependency usages to just refer to the default classifier -- which seems to resolve this dependency partial build issue
