### ISSUE TITLE
type-explorer is broken in coco pharma notebook environment

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#3758]
A change in 2.4 has broken the configuration of type explorer

  ... configuring the type-explorer Governance Solution View Service for this server...
   ...... (POST https://dev:9443/open-metadata/admin-services/users/garygeeke/servers/cocoView1/view-services/type-explorer )
   ...... Response:  {'class': 'VoidResponse', 'relatedHTTPCode': 400, 'exceptionClassName': 'org.odpi.openmetadata.adminservices.ffdc.exception.OMAGConfigurationErrorException', 'actionDescription': 'configureViewService', 'exceptionErrorMessage': 'OMAG-ADMIN-400-036 Unable to configure server cocoView1 since view service type-explorer is not registered in this OMAG Server Platform', 'exceptionErrorMessageId': 'OMAG-ADMIN-400-036', 'exceptionErrorMessageParameters': ['cocoView1', 'type-explorer'], 'exceptionSystemAction': "The system is unable to add this view service to the server's configuration document.", 'exceptionUserAction': 'Check that the name of the view service is correctly specified in the configuration request.  If you are not sure, issue the call to list the registered view services and verify the values you are using.  If the name is right, but the view service should be registered,then the developer of the view service needs to add this registration to the code of the view service. An view service is registered in the OMAG Server Platform by adding a description of the view service to the view service registration. Once the view service being requested is registered, retry the configuration request.'}

Suspect this is relating to the name change.

cc: @grahamwallis

**Comment by planetf1** [comment]
Caused by #3736 I think

Let me know @grahamwallis if you want to do this or I will -- and if there are any other relevant changes? Would be good to keep this working in master. (and consider automation of the testing)

**Comment by grahamwallis** [comment]
Hi @planetf1 - Yes please if you wouldn't mind investigating and correcting that would be great. I'm currently doing similar updates to Rex and it will be good to get all the view service changes in and then make sure the admin services and notebooks are all consistent. 

Apart from the obvious failure in the configuration attempt above, it's worth mentioning that Tex is not a [Governance] Solution View Service - it's an IntegrationViewService. Not sure if this is just a copy/paste in the notebook, or whether it is a little deeper.

**Comment by planetf1** [comment]
Good to clarify the type -- the current implementation was rather pressed for time to get something out, and the configuration initially was the same as a Governance Solution View service, which is why it got added to that list. I can correct.

**Comment by planetf1** [comment]
If we have related changes to avoid breakage ideally we should include in the same PR so that we keep master good.
When do you think the rex updates will be done? And will both need the same config as dino? Can you provide a sample?

**Comment by grahamwallis** [comment]
Hi. Agreed and not sure exactly when Rex changes will be good to go - currently having a few problems with node, sass and Spring. But hey! It'd be dull if everything worked first time eh? Agree that we should add notebook changes to the same PR. 

All of Dino, Tex and Rex will be able to use the same resource endpoint config. Something along the following lines would be fine, albeit not as interesting as your Coco configuration:

{
            "class":"IntegrationViewServiceConfig",
            "viewServiceAdminClass":"org.odpi.openmetadata.viewservices.tex.admin.TexViewAdmin",
            "viewServiceFullName":"Type Explorer",
            "viewServiceOperationalStatus":"ENABLED",
            "resourceEndpoints" : [
                 {
                    "class"              : "ResourceEndpointConfig",
                    "resourceCategory"   : "Platform",
                    "platformName"       : "Platform1",
                    "platformRootURL"    : "https://localhost:8082",
                    "description"        : "Egeria deployment on local development server"

                },
                {
                    "class"              : "ResourceEndpointConfig",
                    "resourceCategory"   : "Platform",
                    "platformName"       : "Platform2",
                    "platformRootURL"    : "https://localhost:9443",
                    "description"        : "Egeria deployment on local test server"
                },
                {
                    "class"              : "ResourceEndpointConfig",
                    "resourceCategory"   : "Server",
                    "serverName"         : "Metadata_Server",
                    "serverInstanceName" : "Metadata Server 1",
                    "platformName"       : "Platform1",
                    "description"        : "Metadata server for development testing"
                },
                {
                    "class"              : "ResourceEndpointConfig",
                    "resourceCategory"   : "Server",
                    "serverName"         : "Metadata_Server2",
                    "serverInstanceName" : "Metadata Server 2",
                    "platformName"       : "Platform2",
                    "description"        : "Metadata server used as home for test artefacts"
                }
            ]
        },

The above cold be used for all 3 integration view services with suitable changes to the name of the VS in viewSewrviceAdminClass and viewServiceFullName.

Will let you know when I have rex resource endpoints working.

**Comment by planetf1** [comment]
I've created a draft PR #3851 with the type explorer changes. So we have the option to merge soon if needed, or - ideally - hold out a day or two for rex - and I'll make those changes too

You can also cherry-pick the commit into your own change if that's easier.

**Comment by grahamwallis** [comment]
@planetf1 - All of the updates to tex, rec and dino are now merged.

**Comment by planetf1** [comment]
Thanks. I won't be able to do this for a few days - feel free to make the notebook change otherwise I will do likely end of week/monday. until then rex won't work in coco.

**Comment by planetf1** [comment]
@grahamwallis I just checked the notebooks in master, and
 - rex still has the old style config with just omag server name/ URL
 - the admin API call passes
 - the start of cocoView1 fails with
```
                       error message is: OMAG-ADMIN-400-042 The Repository Explorer Open Metadata View Service (OMVS) has been passed an invalid configuration of ViewServiceConfig{viewServiceId=5001, viewServiceAdminClass='org.odpi.openmetadata.viewservices.rex.admin.RexViewAdmin', viewServiceName='Repository Explorer', viewServiceFullName='Repository Explorer OMVS', viewServiceURLMarker='rex', viewServiceDescription='Explore open metadata instances.', viewServiceWiki='https://egeria.odpi.org/open-metadata-implementation/view-services/rex-view/', viewServiceOperationalStatus=ENABLED, viewServiceOptions=null} in the viewServiceConfig property.
```

Should the configuration fail?

**Comment by planetf1** [comment]
With a correct config body, both the config and start works correctly.

**Comment by planetf1** [comment]
this should now be complete
