### ISSUE TITLE
Add package-lock.json to git for presentation server

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#3866]

**Comment by planetf1** [comment]
I am constantly hitting the fact this is regenerated on each build.

ie:

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        open-metadata-implementation/user-interfaces/presentation-server/package-lock.json


it is so easy to add in error.

I think we need to have it in .gitignore, and if the UI needs to get it updated, that can be done explicitly.
Or can we avoid checking it in?

It's rather unclear currently and extremely easy for any developer to add in error ie:
