### ISSUE TITLE
ui server chassis - whitelabel error page

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#3892]
WHen launching the UI server chassis in any of the following ways, an attempt to go to https://host:8443 (or forwarded port) results in:
```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Oct 15 14:21:24 GMT 2020
There was an unexpected error (type=Internal Server Error, status=500).
```
There are no useful audit events produced, or any log messages produced at default log level (or when setting LOGGING_LEVEL_ROOT to Info)

This occurs when
 - Running the egeria 'lab' environment k8s notebook
 - running `docker run -p 8443:8443 -e JAVA_APP_JAR=user-interface/ui-chassis-spring-2.4-SNAPSHOT.jar planetf1/egeria:latest` (the docker image the k8s environment uses)
 - running `java -jar user-interface/ui-chassis-spring-2.4-SNAPSHOT.jar`  from open-metadata-distribution/open-metadata-assemblies/target/egeria-2.4-SNAPSHOT-distribution/egeria-omag-2.4-SNAPSHOT (ie our assembly, which goes into the docker image)
 - running `java -jar ui-chassis-spring-2.4-SNAPSHOT.jar` from the target directory of the ui chassis spring source  (the built jar which gets put into the assembly)

**Comment by planetf1** [comment]
Note that when run in the last case, parms are also set for the location of the certs etc -- however in all case we see failures.

**Comment by planetf1** [comment]
Also get this when following the new instructions for developer use in the ui server chassis spring dir
```
mvn spring-boot:run -Dspring-boot.run.folders=/path/to/libs/ -Dspring-boot.run.arguments="--theme=default --zuul.routes.ui.url=http://localhost:8081 --omas.server.name= --omas.server.url= --open.lineage.server.url= --open.lineage.server.name= --server.ssl.trust-store=./src/main/resources/truststore.p12"
```

**Comment by sarbull** [comment]
this is because there is no more static content in the `ui-chassis-spring`, no index.html, and you get that error due to the fact that there is no static server started in parallel and URL given as a parameter to the `ui-chassis-spring`

**Comment by planetf1** [comment]
Thanks, 
 suggest

 - considering the custom error page (though this is what the end user sees)
 - adding a problem determination section/if it doesn’t work to the readme

**Comment by sarbull** [comment]
i'll add this to the README.md as a known issue

**Comment by planetf1** [comment]
this is not occuring when the UI is correctly deployed - closing
