### ISSUE TITLE
Tex/dino Admin Services configuration OMAG-ADMIN-400-039

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#3899]
From the configuration notebook for tex & dino:
```
   ... configuring the tex Integration View Service for this server...
   ...... (POST https://localhost:9445/open-metadata/admin-services/users/garygeeke/servers/cocoView1/view-services/tex )
   ...... Response:  {'class': 'VoidResponse', 'relatedHTTPCode': 400, 'exceptionClassName': 'org.odpi.openmetadata.adminservices.ffdc.exception.OMAGInvalidParameterException', 'actionDescription': 'configureViewService', 'exceptionErrorMessage': 'OMAG-ADMIN-400-039 The configureViewService service of OMAG server cocoView1 has been configured with a null root URL for its remote OMAG Server', 'exceptionErrorMessageId': 'OMAG-ADMIN-400-039', 'exceptionErrorMessageParameters': ['configureViewService', 'cocoView1'], 'exceptionSystemAction': 'The system is unable to accept this value in the configuration document because the server would not be able to operate correctly.', 'exceptionUserAction': 'The root URL is supplied by the caller to the OMAG server. This URL value needs to be corrected before the server can operate correctly.'}
   ... configuring the dino Integration View Service for this server...
   ...... (POST https://localhost:9445/open-metadata/admin-services/users/garygeeke/servers/cocoView1/view-services/dino )
   ...... Response:  {'class': 'VoidResponse', 'relatedHTTPCode': 400, 'exceptionClassName': 'org.odpi.openmetadata.adminservices.ffdc.exception.OMAGInvalidParameterException', 'actionDescription': 'configureViewService', 'exceptionErrorMessage': 'OMAG-ADMIN-400-039 The configureViewService service of OMAG server cocoView1 has been configured with a null root URL for its remote OMAG Server', 'exceptionErrorMessageId': 'OMAG-ADMIN-400-039', 'exceptionErrorMessageParameters': ['configureViewService', 'cocoView1'], 'exceptionSystemAction': 'The system is unable to accept this value in the configuration document because the server would not be able to operate correctly.', 'exceptionUserAction': 'The root URL is supplied by the caller to the OMAG server. This URL value needs to be corrected before the server can operate correctly.'}
```

it's my understanding these parameters are not relevant for these two services (and ultimately rex too) and so this validation is incorrect

**Comment by planetf1** [comment]
The workaround is to add the following to the configuration body for each
```
            "omagserverPlatformRootURL": "UNUSED",
            "omagserverName" : "UNUSED",
```

If the config body definition is changed, or validation changes, these can be removed (egeria-server-config.ipynb)

**Comment by grahamwallis** [comment]
This looks rather odd. An extra validation step was introduced as part of #2512 (i.e. an old issue/PR, but the change was was only committed and merged 20 days ago.

The change introduced the following:

   errorHandler.validateOMAGServerClientConfig(serverName, requestedViewServiceConfig, methodName);

into the configureViewService method.
As you say the omagServerName and omagServerPlatromRootURL are not used for integration view services. So the "client configuration" either needs to be extended to handle integration view services, or we should skip the validation for these view services.

I'm happy to discuss and to help fix, but at the moment I don't have sufficient context as to the role of the client and the validation I'm afraid.

@mandy-chessell  Can you please comment?

**Comment by mandy-chessell** [comment]
The client will probably be used in the view service that supports server configuration. 

Typically the clients should validate all key parameter values at the start of the method.  Looks like this was implemented before the change to remove the need for the client config for rex/tex/dino which is why it is objecting to null values.  I don't remember doing it, but it was probably created a couple of months ago and was part of my big PR.  I did do some tidy up of the admin services when I added the admin for the integration daemon.  Lots of people change the admin services and so I often have to go through it as component owner and fill in all the missing bits.  Clients, javadoc, audit log support are the typical omissions.

**Comment by grahamwallis** [comment]
@mandy-chessell Thanks - no problem - I'm thinking that maybe we should add a test to check the type of view service - and if it's an integration view service, skip the client config validation. Sound OK?

**Comment by mandy-chessell** [comment]
Yes for the moment - I am not sure if you saw the discussion about using a metadata server to supply the platform and service info for the view services - this came out of the review of the server config view services which identified many more drop down lists of information that would need to go into config - using a metadata server would mean that the lists could be updated without needing to restart the view server(s) so if we can make it work, there are a number of advantages.
