### ISSUE TITLE
Repository Handler is not checking if ends of relationships are null

### ISSUE THREAD

**Issue by danielaotelea** [odpi/egeria#3903]
"getOtherEnd" method from RepositoryHandler is not checking if the ends of relationships are not null.
This may cause a NPE. Before checking if the GUIDs are equal, a check for requiredEnd and startingEnd proxy should be added.

**Comment by mandy-chessell** [comment]
There should not be an occasion when the proxies are null - we need to put the check in the repository services so that the repository connector that is returning bad relationships is identified.  Putting a workaround at this point in the code is not going to nail the real problem.

**Comment by danielaotelea** [comment]
Yes, indeed the real problem is described here: https://github.com/odpi/egeria-connector-ibm-information-server/issues/410.

**Comment by mandy-chessell** [comment]
Fixing that problem does not resolve the general probalem that any repository connector could produce relationships without ends - the local repository connector should be validating the response from the connector and not passing it on.

**Comment by cmgrote** [comment]
Agreed that we should address this in the validators in the `OMRSMetadataCollectionBase`, call the validator from `LocalOMRSMetadataCollection`.  The logic should be to:

- log to audit log when there is any relationship found with a null end
- throw a RepositoryErrorException in such a situation

**Comment by cmgrote** [comment]
Actually, on deeper investigation it looks like the validators may be in their own class distinct from those above; but the general spirit of the above points will be retained:

- enhance the relationship validator to ensure that the ends (EntityProxies) of the relationship are non-null (should we go further to validate that the EntityProxies are also valid, not just non-null?)
- call the relationship validator from `LocalOMRSMetadataCollection`, the same as it is called today for the in-memory repo and graph repo MetadataCollections
