### ISSUE TITLE
Suggested improvements to compliance test suite

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#391]
Having run the CTS against the Atlas connector, there are a number of changes that I believe would be of benefit. These include:

- providing values for inherited properties when creating an entity instance - rather than only those defined by the immediate typeDef without inheriting from any super types. This has the benefit that when Egeria's types define mandatory properties, that these properties will be supplied, so the addEntity() call does not fall foul of property validation

- providing values for the mandatory properties (including inherited properties) when performing an updateEntityProperties() - so that the target property set is valid for an instance of the Egeria type def

**Comment by mandy-chessell** [comment]
@grahamwallis Can this be closed?

**Comment by grahamwallis** [comment]
@mandy-chessell - Yes - thanks for committing it.
