### ISSUE TITLE
Adding parent and children rest calls to subject area omas

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#3928]
I could not find the issue for a pr so am raising this issue to track it

**Comment by davidradl** [comment]
I have PR https://github.com/odpi/egeria/pull/3925. I have raised this issue for it. I would like some view points on the following issue:

- I changed the code in Subject Area as part of the pr to introduce paging to various API requests.
- Talking with @mandy-chessell there is a standard way of doing this using the InvalidParameterHandler which has a validatePaging method. This method throws Exception org.odpi.openmetadata.commonservices.ffdc.exceptions.InvalidParameterException
This method is used by Asset Owner Asset Catalog , discovery engine and other places in the Egeria code.
- @immmus has raised a review comment twice indicating he would like this Exception removed, I assume because it is a common Exception not a SubjectArea one  
-  InvalidParameterHandler, it has standard specific common messages indicating things like - 
    NEGATIVE_START_FROM(400, "OMAG-COMMON-400-008",
    NEGATIVE_PAGE_SIZE(400, "OMAG-COMMON-400-009",
Very good for debugging from logs.

I think we either:
1) Not use the InvalidParameterHandler, so we do not throw the common exception. This means we have to implement duplicate code in the subject area with Subject Area messages and Exceptions.
2) Use the InvalidParameterHandler and expose the common Exception in the Subject Area API
3) Use the InvalidParameterHandler and create duplicate Subject ares equivalent messages for all the common messages.

I am thinking that option 2) is preferable. @immmus @grahamwallis @planetf1 @mandy-chessell . What are your thoughts?

**Comment by immmus** [comment]
> I have PR #3925. I have raised this issue for it. I would like some view points on the following issue:
> 
> * I changed the code in Subject Area as part of the pr to introduce paging to various API requests.
> * Talking with @mandy-chessell there is a standard way of doing this using the InvalidParameterHandler which has a validatePaging method. This method throws Exception org.odpi.openmetadata.commonservices.ffdc.exceptions.InvalidParameterException
>   This method is used by Asset Owner Asset Catalog , discovery engine and other places in the Egeria code.
> * @immmus has raised a review comment twice indicating he would like this Exception removed, I assume because it is a common Exception not a SubjectArea one
> * InvalidParameterHandler, it has standard specific common messages indicating things like -
>   NEGATIVE_START_FROM(400, "OMAG-COMMON-400-008",
>   NEGATIVE_PAGE_SIZE(400, "OMAG-COMMON-400-009",
>   Very good for debugging from logs.
> 
> I think we either:
> 
> 1. Not use the InvalidParameterHandler, so we do not throw the common exception. This means we have to implement duplicate code in the subject area with Subject Area messages and Exceptions.
> 2. Use the InvalidParameterHandler and expose the common Exception in the Subject Area API
> 3. Use the InvalidParameterHandler and create duplicate Subject ares equivalent messages for all the common messages.
> 
> I am thinking that option 2) is preferable. @immmus @grahamwallis @planetf1 @mandy-chessell . What are your thoughts?

I raised the issue of dropping the package before the exception in a try {} catch construct, rather than dropping the exception itself

**Comment by davidradl** [comment]
@immmus OK great - my misunderstanding. We are on the same page :-)
