### ISSUE TITLE
Gaian Ranger plugin resource mapper

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#396]
From: https://github.com/GaianRangerPlugin/ranger-gaian-plugin/issues/6

Ranger plugins provide a 'resource mapper' which allows the the ranger policy edit UI to do auto-complete/assist for users writing policies, to match against known resource names.

A stub is currently in the code, but this needs implementing so that we lookup configured gaiandb virtual table names, columns etc. Until this is done, typeahead will not function

**Comment by danielaotelea** [comment]
Hi, Nigel! Can you provide more details about this resource mapper?

**Comment by planetf1** [comment]
more correctly it's resource lookup I was referring too..

It's mentioned athttps://rerun.me/2019/05/14/the-beautiful-simplicity-of-apache-ranger-plugin/, the idea being to facilitate typeahead

That being said, and given the challenges with gaian in terms of open source viability, I would recommend we close issues to improve, and instead evaluate other virtualisation technologies. 

Additionally if we do more integration with ranger, more complete integration between egeria metadata more generally, and ranger's 'rule' authoring is probably preferable, even if this might be a first step.

So I recommend closure.

**Comment by planetf1** [comment]
please reopen if you disagree :-)
