### ISSUE TITLE
Fix rex configuration in notebook

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#3961]
This should be Repository Explorer

_Originally posted by @grahamwallis in https://github.com/odpi/egeria/pull/3952#discussion_r511865062_

**Comment by planetf1** [comment]
Also mentioned was

_Whilst this configuration is valid - I wonder whether it might be more illustrative if we distinguish the serviceInstanceName from the serviceName. If there is only ever one instance of the service then it genuinely makes no difference and is arguably clearer the way it is here (with the two fields having the same value). If there might be more than one instance then reflecting that in the serviceInstanceName is clearer._

@grahamwallis can you clarify on the use of the serverInstanceName?
Presumably you are talking about the case where we have two distinct platforms, each hosting the same logical server (so same servername). Those platforms would typically share an IP address (or at least traffic would be routed to both via a different mechanism) so externally they'd look as one.

I'm not sure we currently have any configuration that would allow, for example, the platforms to be distinguished, and if they also have the same DNS name or IP how might that work?

This could be a larger topic than just the rex config?

**Comment by grahamwallis** [comment]
I think the whole clustering area probably does warrant a fuller conversation. 
Aside from ip routing, the platform URL root and server name are needed to issue a REST request to a server instance. That was the only part I was referring to here, in so far as it affects Dino et al.

**Comment by grahamwallis** [comment]
Thanks @planetf1 - apologies for not getting my review comments in prior to merge of the original PR.
