### ISSUE TITLE
deployedImplementationType does not seem appropriate name in BusinessCapabilityType

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#3967]
Recent change renamed the "type" property in BusinessCapability to "deployedImplementationType".  Something like "businessCapabilityType" seems more appropiate.
![0440-Organizational-Controls](https://user-images.githubusercontent.com/12354195/97280488-3f0b4000-1834-11eb-9b67-42eadd54b3bd.png)

**Comment by mandy-chessell** [comment]
FYI @grahamwallis

**Comment by grahamwallis** [comment]
@mandy-chessell Well found! :-)

**Comment by grahamwallis** [comment]
Presume that we should still clear this up.
