### ISSUE TITLE
Gaian - failure if access not allowed by policy

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#397]
Migrated from https://github.com/GaianRangerPlugin/ranger-gaian-plugin/issues/4
See httpds://github.com/gaiandb/gaiandb/issues/13

once implemented test/update plugin accordingly

**Comment by danielaotelea** [comment]
Is this an expected behaviour from the GaianRangerPlugin?

**Comment by planetf1** [comment]
Yes -- with the current gaian API it's not possible to 'fail' the initial request - which is why we return an empty result set. I recommend closing gaian issues at this point until we resolve where we see the future of virtualisation technologies - including for example postgres (with extensions), JBoss virtualisation (redhat), or a revitalised gaian etc ..

**Comment by planetf1** [comment]
please reopen if you disagree :-)
