### ISSUE TITLE
Gaian masking improvements

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#398]
Migrated from: https://github.com/GaianRangerPlugin/ranger-gaian-plugin/issues/7

Masking is currently implemented by transforming the result set post-query where the masked field appears in the output data, or by preventing access to the data if used in the predicate

Hive instead pushes down an expression to the database engine which allows predicates to still be used. For example a masking operation might convert a fine-grained date (YYYYMMDD) into simply a year, which could still then be used in range-based predicates, like showing data between 2000-2010. Or a mask function might generate a hash, which could then be used for cross-checking without exposing the actual data value.

This likely requires changes to gaian and needs further research, but better mirrors the approach taken more generally .

**Comment by danielaotelea** [comment]
Some improvements has been developed since the issues has been opened:
	<property>
		<name>ranger.plugin.gaian.masking.pattern</name>
		<value>CUSTOM</value>
		<description>Masking Pattern</description>
	</property>

	<property>
		<name>ranger.plugin.gaian.char.masking</name>
		<value>*****</value>
		<description>Masking Value for Characters Fields</description>
	</property>

	<property>
		<name>ranger.plugin.gaian.int.masking</name>
		<value>1000</value>
		<description>Masking Value for Number type format Fields</description>
	</property>

	<property>
		<name>ranger.plugin.gaian.date.masking</name>
		<value>0001-01-01</value>
		<description>Masking Value for Date Fields; The Pattern for data is yyyy-MM-dd</description>
	</property>

Is this enough for the moment?

**Comment by planetf1** [comment]
They're good improvements for the end user, though don't go into more complex masking algorithms that might require pushing down to the underlaying engine - be it derby or indeed the source databases. This pushdown would need changes to gaian, and given the project's current state I recommend we do not pursue this further & close the issue - but it's a worthy consideration for future virtualisation work
