### ISSUE TITLE
Add external mount point for connectors to egeria docker image

### ISSUE THREAD

**Issue by CDaRip2U** [odpi/egeria#4001]
I would like to have the ability to add my connector from local machine be loaded in classpath for egeria server with containers such as with a docker-compose file.  Seems this can be done with an addition of a directory like /deployment/server/externallib to the classpath for the image so users could mount volume for local connector .jar files and load those up

Then in our local docker-compose we just do:

volumes:
     - ~/.m2/path-to-my-jar-file-directory-example/:/deployments/server/external_libs

This has some security implications too.

**Comment by planetf1** [comment]
Agreed we need to look at how n organization deploying egeria can make use of the docker image(s) in a more flexible manner. Adding their own connectors is the most obvious example, but also for example adding additional OMASs

Options include
 - a mountpoint (as above)
 - using our docker image as a base

Both (and others if relevant) should be clearly documented

**Comment by planetf1** [comment]
My proposal for this is to add an additional component to the LOADER_PATH seen by the application

As well as server/lib in the distribution, which contains any files supplied by the project build, we also add
a directory which is an empty volume, but could contain additional libraries needed at deployment time.

In the current UBI image we deploy our app to /deployments, so for example we have:
```
jonesn:~/ $ docker exec -it 76547d6c2966 /bin/sh                                                                                                                    [15:30:29]
sh-4.4$ cd /deployments/
sh-4.4$ ls
LICENSE  NOTICE  conformance-suite  data  samples  server  truststore.p12  user-interface  utilities
```

It makes sense to keep this user directory outside this tree, so I propose to add it to
/data/lib
Anything added here will get added to the classpath of the server chassis

In kubernetes this can be resolved through a persistent volume claim to a storage location of the user's choosing ie https://kubernetes.io/docs/concepts/storage/volumes/
