### ISSUE TITLE
Open Metadata Type not selectable from dropdown on Business UI

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#4024]
I have the coco pharmaceuticals tutorial environment installed, and have run through configuration & all servers are started.
2.4 release (testing)

* Go to the Business UI which defaults to asset catalog
* Select Asset as type
* enter csv as search string
* Hit search icon
* No results returned
* hit the X to remove Asset as the type
* Now the dropdown cannot be selected ie:

<img width="1311" alt="Screenshot 2020-10-30 at 12 34 05" src="https://user-images.githubusercontent.com/7292002/97705744-797f1200-1aac-11eb-9530-d5f382f6941c.png">

Nor does starting to type a type-name give any hits whatsoever, including a full name like 'Asset'

**Comment by bogdan-sava** [comment]
https://github.com/odpi/egeria-ui/pull/40

**Comment by bogdan-sava** [comment]
fixed
