### ISSUE TITLE
Failed to setup egeria docker compose environment [2.4 release]

### ISSUE THREAD

**Issue by chenqiny** [odpi/egeria#4081]
I downloaded 2.4 release 

https://github.com/odpi/egeria/archive/V2.4.tar.gz

Then I try to setup egeria with docker compose yaml file.

localhost:~/code/aiu/egeria/egeria-2.4/open-metadata-resources/open-metadata-deployment/compose/tutorials> docker-compose -f ./egeria-tutorial.yaml up
/bin/sh: /tmp/_MEIkgWPTG/libreadline.so.7: no version information available (required by /bin/sh)
Pulling core (planetf1/egeria:2.4)...
ERROR: manifest for planetf1/egeria:2.4 not found: manifest unknown: manifest unknown

**Comment by planetf1** [comment]
See file `open-metadata-resources/open-metadata-deployment/compose/tutorials/.env`
change
`egeria_repo=odpi`

It looks as if I may have incorrectly left that file with a value I use in testing
Apologies - will add to release notes.

Let me know if this works

**Comment by planetf1** [comment]
I believe this is fixed now - please get back to us if you have any more issues & thanks for reporting
