### ISSUE TITLE
Combine all UI Code with CRA

### ISSUE THREAD

**Issue by jmmadsen** [odpi/egeria#4082]
Combine new work done in original directory with the new CRA directories. Need to freeze UI development in the meantime while this is done. @grahamwallis @davidradl

**Comment by jmmadsen** [comment]
@dkneisly

**Comment by planetf1** [comment]
+ update assembly/docker to match & test

**Comment by jmmadsen** [comment]
@planetf1 can you expand on the assembly/docker piece?

**Comment by planetf1** [comment]
The file in open-metadata-distribution/open-metadata-assemblies/src/main/assemblies/egeria-presentation-server.xml defines the files that are picked from the build directory to package up 

So it may be as simple as changing directory names there 

Then check open-metadata-distribution/open-metadata-assemblies/target/egeria-2.5-SNAPSHOT-presentation-server

has everything needed to launch the app.

We make use of this in the docker image in open-metadata-resources/open-metadata-deployment/docker/presentation-server/Dockerfile. (the actual assembly above is copied in the pom.xml initially into a subdirectory)

Basically we end up running `node src/server/index.js` to launch the app - so if the invocatino has to change, it's the Dockerfile we need to do that.

The docker image has docs on dockerhub  which I can update with any links/useful info for anyone running directly.

The docker image is then used in our helm charts & docker compose environments. 

These are in `open-metadata-resources/open-metadata-deployment/compose/tutorials` and `open-metadata-resources/open-metadata-deployment/charts/odpi-egeria-lab`

The key things to note there are that we just run the container with the default command, and the only relevant environment variable we set is `EGERIA_PRESENTATIONSERVER_SERVER_coco`

If extra environment variables are needed, they will need modification in those two directories above.

This is important as if the docker build fails our entire merge build fails. This breaks other things, but mostly stops any image updates going to docker hub. (the image not working of course also might affect anyone using it)

We need to add automated testing of the images. sadly it's not in place yet

**Comment by jmmadsen** [comment]
I have merged all the UI code under the new CRA directories and deleted the old directory. I'm going to focus on the build stuff @planetf1 highlighted above, then will create a PR. My assumption with the PR is each author will test their own sections to ensure they still operate as expected, given that manually merging/resolving conflicting code is an inexact science.

**Comment by jmmadsen** [comment]
To give further context on the above, all the UI pages still load/look as I would expect, but I am relying on everyone else to test the detailed functionality of interacting with Egeria.
