### ISSUE TITLE
Server author View service

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#4088]
Add a view service that the Server author will call and be able to get the defined platforms returned.

**Comment by davidradl** [comment]
I was thinking about a possible split between server author and dino capabilities. Originally I was going to add server authoring , deploy and activate, temporarily and permanently deactivate to server author. I am now thinking it would be cleaner if Server Author only creates , reads, updates and deletes authors and does not do operational stuff.

If Dino is the driver of everything, then it does the activate deactivate operational actions.

So to finish the first pass of Server Author view , I am thinking 
- enhance the configuration file connector and wrap with an API to be able to query the stored configurations on a platform
- remove the stub operational APIs I had added
- enhance the documentation to mention Server author  
- possibly change the behaviour of query stored configuration API to retrieve a no found if one does not exist rather than succeed returning a dummy omag server config which does not have a file behind it. 

One point I would like your thoughts on, I think it would be good for the server author to be able delete a configuration by name, it could call a new java client for operational services to call delete /open-metadata/admin-services/users/{userId}/servers/{serverName}. This seems an operational call that would shutdown the server as well as delete the stored config. I could either:
1) use this call and introduce an operation java client, which would shutdown and delete. I wonder whether someone writing servers should be allowed to do this.  
2) Introduce another call platform call that would not do anything operational and only delete the stored config from a platform  if it was not active.     

What do you think @mandy-chessell @grahamwallis @planetf1 @dkneisly @jmmadsen ?

**Comment by davidradl** [comment]
@dkneisly The server Author view initial code is in master. Are there any other APIs you need me to implement? It looks like the current UI constructs a config document then sends it. The existing API allows some parts of the config to be amended in isolation as part of an update. I suspect as you want to allow more updates of different parts of config you will want more of these fine grain API exposed. Are there any you think you use in the short to medium term? I am hoping to only add what you need, rather than everything.

**Comment by grahamwallis** [comment]
@davidradl With regard to the "...possible split between server author and dino capabilities.... cleaner if Server Author only creates , reads, updates and deletes authors and does not do operational stuff." Yes, I think that makes sense. I think it may be beneficial if the two (Dino and Server Author) are closely integrated so that someone approaching this via Dino can switch into Server Author, e.g. to compose and deploy, or modify a configuration, and then switch back to Dino to stop or start the affected server. 

It occurs to me that we might want to extend Dino to also have a form/grid/list/tree based layout alongside the TopologyDiagram, and any such views added to the Dino UI code should be similar in look and feel to those for Server Author.


With regard to "... the server author to be able delete a configuration by name, it could call a new java client for operational services to call delete /open-metadata/admin-services/users/{userId}/servers/{serverName}. This seems an operational call that would shutdown the server as well as delete the stored config." and the choice between "...  shutdown and delete. ... vs ...  only delete the stored config from a platform if it was not active.", I would think it makes sense to only delete the configuration if the server is (already) stopped. There is an existing REST api for the deletion of a server's configuration (in ...adminservices.spring.ConfigResource):

```
@RequestMapping("/open-metadata/admin-services/users/{userId}/servers/{serverName}")

    /**
     * Clear the configuration properties for an OMAG Server in a single command.
     *
     * @param userId  user that is issuing the request
     * @param serverName  local server name
     * @return void response or
     * OMAGNotAuthorizedException the supplied userId is not authorized to issue this command or
     * OMAGInvalidParameterException invalid serverName or OMAGServerConfig parameter.
     */
    @DeleteMapping(path = "/configuration")
    public VoidResponse clearOMAGServerConfig(@PathVariable String userId,
                                              @PathVariable String serverName)
    {
        return adminAPI.clearOMAGServerConfig(userId, serverName);
    }
```

**Comment by davidradl** [comment]
> @davidradl With regard to the "...possible split between server author and dino capabilities.... cleaner if Server Author only creates , reads, updates and deletes authors and does not do operational stuff." Yes, I think that makes sense. I think it may be beneficial if the two (Dino and Server Author) are closely integrated so that someone approaching this via Dino can switch into Server Author, e.g. to compose and deploy, or modify a configuration, and then switch back to Dino to stop or start the affected server.
> 
> It occurs to me that we might want to extend Dino to also have a form/grid/list/tree based layout alongside the TopologyDiagram, and any such views added to the Dino UI code should be similar in look and feel to those for Server Author.
> 
> With regard to "... the server author to be able delete a configuration by name, it could call a new java client for operational services to call delete /open-metadata/admin-services/users/{userId}/servers/{serverName}. This seems an operational call that would shutdown the server as well as delete the stored config." and the choice between "... shutdown and delete. ... vs ... only delete the stored config from a platform if it was not active.", I would think it makes sense to only delete the configuration if the server is (already) stopped. There is an existing REST api for the deletion of a server's configuration (in ...adminservices.spring.ConfigResource):
> 
> ```
> @RequestMapping("/open-metadata/admin-services/users/{userId}/servers/{serverName}")
> 
>     /**
>      * Clear the configuration properties for an OMAG Server in a single command.
>      *
>      * @param userId  user that is issuing the request
>      * @param serverName  local server name
>      * @return void response or
>      * OMAGNotAuthorizedException the supplied userId is not authorized to issue this command or
>      * OMAGInvalidParameterException invalid serverName or OMAGServerConfig parameter.
>      */
>     @DeleteMapping(path = "/configuration")
>     public VoidResponse clearOMAGServerConfig(@PathVariable String userId,
>                                               @PathVariable String serverName)
>     {
>         return adminAPI.clearOMAGServerConfig(userId, serverName);
>     }
> ```

thanks @grahamwallis. Yes I saw the existing server side call, but there is no java client call. I am making all the server  requests using the java admin client. This call does not check whether the config is active, I would need to check this prior to issuing the delete.
