### ISSUE TITLE
Request to join the organisation

### ISSUE THREAD

**Issue by akshitagupta15june** [odpi/egeria#4096]

**Comment by planetf1** [comment]
Hi AKSHITA, welcome.

Our github repositories are public, and we welcome anyone to join in and get involved by raising/commenting on issues, proposing pull requests, commenting in reviews, joining team discussions etc. 

There's some guidelines at https://egeria.odpi.org/open-metadata-resources/open-metadata-tutorials/egeria-dojo/egeria-dojo-day-2-5-becoming-a-contributor.html 

We currently will add users to the repository when they achieve the contributor badge, this just gives them slightly more access - specifically
 - they can be assigned pull request reviews
 - they can directly be assigned issues (though ANYONE can be assigned once they have commented in an issue)

That is the only change. 

We then have our maintainers who have the ability to create releases, merge PRs etc

Is there anything in particular you weren't able to do that you expected? Or are you looking for any more information on the project?

**Comment by planetf1** [comment]
Hopefully I have answered the question & pointed out the process we follow. I will close the issue. Please get back in touch if you need further information
