### ISSUE TITLE
Rework IGC Repository Proxy to make use of IGC REST adapter

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#411]
To track re-work of the IGC Repository Proxy included in the virtualizer demo to make use of the IGC REST adapter.

Anticipated sub-tasks:

- [x] update the expected configuration parameters to:
  - `igcBaseURL`: should be just the `hostname:port`
  - `igcAuthorization`: should be the base64-encoded username and password to use for connection
  - `igcVersion`: should be either `v115` or `v117` to represent the version of IGC being used
- [x] implement `getEntityDetail` method in IGCOMRSMetadataCollection
- [x] implement `getRelationshipsForEntity` method in IGCOMRSMetadataCollection
- [x] implement `findEntitiesByPropertyValue` method in IGCOMRSMetadataCollection
- [x] implement `findEntitiesByProperty` method in IGCOMRSMetadataCollection

**Comment by cmgrote** [comment]
@GuyAckermans can you check we're OK with the change suggested by the first sub-task above? This moves away from current config parameter, which hard-codes one particular endpoint (using config suggested above we'll be able to call all the IGC REST endpoints we might need to for optimal search, retrieval, session mgmt, etc)

I'll be making these changes, and submitting a separate PR, so will of course ask you to review that as well -- but thought it worth getting initial go-ahead on this approach 😉  (feel free to assign this overall issue to me, if possible?)

**Comment by GuyAckermans** [comment]
Hi Chris, 
Yes this is okay, thanks!

**Comment by cmgrote** [comment]
All methods implemented now, and tested in a basic form; the search methods won't support all options (eg. no history, and certain criteria to restrict options may be limited at least for the moment).

**Comment by cmgrote** [comment]
Submitted in PR #475
