### ISSUE TITLE
Changes remaining after migration of egeria-react-ui to new repo

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#4110]
We will move the existing presentation server code under open-metadata-implementation/user-interfaces/presentation-server to a new github repo 'egeria-react-ui'

Agreed in team call 17 Nov.

Will track the migration in this repo

Initial work

 - [x] create repo
 - [x] enable basic checks like DCO
 - [x] initial code drop (from craclient/craserver)
 - [x] iniitial github action for build
 - [x] enable codeQL for javascript code checking
 - [x] enable dependabot/security updates
 - [x] agree distributable artifacts needed (Dockerfile + .tar.gz ?)
 - [x] update docs to refer to new repo, elaborate on deployment requirements
 - [x] build docker image

During this time
 - Code under 'nodejs' in egeria repo should be left to continue to work & be built into the assembly & docker image
 - Work will continue on getting the craclient/craserver directories up to date and working

Once working
 - [x] move latest code to new repo & check

Then
 - [x] update helm & compose to pick up presentation server from new location
 - [x] delete code from egeria repo

cc: @grahamwallis @davidradl @jmmadsen

**Comment by planetf1** [comment]
I could try migrating history of the 'presentation-server' directory if those on copy feel this is useful - either before or after the merge of the current PR - if wanted please comment below.

However I will assume there is no need to do this for simplicity.

**Comment by planetf1** [comment]
Waiting for merge of this issue. 
See also https://github.com/odpi/egeria-react-ui/issues/1 for tracking new code going into repo

**Comment by planetf1** [comment]
FYI @davidradl

**Comment by planetf1** [comment]
The following content remains to be cleaned up:

CODEOWNERS - still has reference
.gitignore - lots of clutter from presentation-server should be removed
view-server.md - needs reference updated to point to new repo (*2)
configuring-the-presentation-server.md - also needs updating to point to new repo
release-notes-2.6.md - needs information adding about the move of presentation server & any neccessary actions

More generally need to decide whether any broader changes needed in the docs - I would generally err on having a pointer in the base egeria docs, but moving the details of configuration of the node app over to the new repo. Obviously view server content should remain in base egeria

@davidradl are you ok to do this as I think you're probably best place for the doc side?

**Comment by davidradl** [comment]
It might be worth changing the .gitignore so it ignores everything in the presentation server folder apart from the readme.

**Comment by planetf1** [comment]
> It might be worth changing the .gitignore so it ignores everything in the presentation server folder apart from the readme.

That's a very practical idea for this, and indeed anywhere else we remove components. But in particular for presentation server given the process.

**Comment by planetf1** [comment]
I think this is over to you now David to finish the tidy up ref docs etc.

**Comment by davidradl** [comment]
adding a comment to keep this issue open

**Comment by planetf1** [comment]
.gitignore, CODEOWNERS and view-server.md still need changes
