### ISSUE TITLE
Create Release 2.5

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#4122]
Create 2.5 release 

- [x] slack post
- [x] agree in team call (target 26 Nov)
- [x] Create branch for 2.5
- [x] Reassign any issues not being worked on to the next release
- [x] Update master to **2.6-SNAPSHOT** 
- [x] Ensure any remaining fixes are merged 
- [x] Update branch version from 2.5-SNAPSHOT to 2.5
- [x] Remove release notes from branch 
- [x] update release notes & rename 
- [x] Verify notebooks
- [x] Check polymer UI 
- [x] Check node (ps) UI 
- [x] Run CTS #4268 
- [x] Run FVTs (this is only FVTs automated in the build process)
- [x] Check samples 
- [x] Check swagger doc 
- [x] Verify docker image/charts/compose 
- [x] Launch release pipeline 
- [x] Approve release
- [x] Verify artifacts all on maven central 
- [x] Create GitHub release
- [x] ensure any fixes ported to master

**Comment by planetf1** [comment]
Agreed in team call 24 Nov to target 26 Nov for branch

**Comment by planetf1** [comment]
Agreed ok to branch now in team call 26 Nov

**Comment by planetf1** [comment]
Blocked on #2468 - will update when resolved

**Comment by planetf1** [comment]
A few minor observations from samples,utilities in error handling etc, but no regressions.

**Comment by grahamwallis** [comment]
This is blocked on #4268 (note the typo in the earlier comment). 
#4268 is making progress - currently mid-way through a CTS run against graph repo.

**Comment by planetf1** [comment]
Inmem and graph CTS completed successfully :-)

**Comment by planetf1** [comment]
Release pipeline has now been started.

**Comment by planetf1** [comment]
Artifacts are now synced to maven central with the following issues:
#3606 analytics modeling client has no source 
#4311 server-author-view* poms do not have an scm section though this appears to only break the top level packaging pom distribution
#4110 presentation server artifact contains no files -- but as a nodejs project we are moving to a new repo imminently, this is not an issue.

Impact is low, so continuing with pushing the release on github and announcing

**Comment by planetf1** [comment]
see https://dev.azure.com/ODPi/Egeria/_releaseProgress?releaseId=153&environmentId=517&_a=release-environment-logs
