### ISSUE TITLE
Subject Area UI error (PS) / pagination issue requesting > system limit

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#4124]
* Launch coco pharm lab environment (I tried both docker-compose & k8s)
* Run through config/start of servers
* Launch dino UI ( /coco/login), login, go to Glossary Author

* Error appears 

<img width="1380" alt="Screenshot 2020-11-20 at 11 25 00" src="https://user-images.githubusercontent.com/7292002/99795330-8038fc00-2b23-11eb-960e-56849ba76c9e.png">

Initially I thought this might be as no glossaries exist. I was able to successfully (at least in terms of the UI) create a new glossary, but reloading the original page shows the same error

The underlaying issue appears to be:
```
{
  class: 'SubjectAreaOMASAPIResponse',
  relatedHTTPCode: 400,
  exceptionClassName: 'org.odpi.openmetadata.viewservices.glossaryauthor.services.GlossaryAuthorViewGlossaryRESTServices',
  actionDescription: 'find for Glossary',
  exceptionErrorMessage: 'OMAG-COMMON-400-016 An unexpected org.odpi.openmetadata.accessservices.subjectarea.handlers.SubjectAreaGlossaryHandler exception was caught by find for Glossary; error message was OMAG-COMMON-400-010 The number of records to return, 500, passed on the 100 parameter of the findGlossary operation, is greater than the allowable maximum of 100',
  exceptionSystemAction: 'The system is unable to process the request.',
  exceptionUserAction: 'Review the error message and other diagnostics created at the same time.',
  result: []
}
```
The full log from presentation server is: https://gist.github.com/d4a4c375f9fe1463094ae3cab828e2f9

Version: The latest master (HEAD @ 8d2589615334548af92cd0e68426480bc4171500 )

**Comment by planetf1** [comment]
The interesting question here is what the correct result should be.

If we ask for more in pagination than system max - should we not just return system max? That's ok? 
Failing seems a little severe

Obviously the coco env could be updated with higher max, but we still shouldn't see a failure like this

**Comment by davidradl** [comment]
@planetf1 what do you mean by the system max?

**Comment by davidradl** [comment]
It would be good to see the view service and subject area service definitions.

**Comment by davidradl** [comment]
I think we should view this after https://github.com/odpi/egeria/issues/4078 has been fixed. This will mean this is only an issue if the server side server config explicitly specified a value lower than 100.  Maybe we police the subject area and glossary author max pagesize config so it has to be at least 100.

**Comment by davidradl** [comment]
Raise https://github.com/odpi/egeria/issues/4125, to enhance user experience when an error occurs.
