### ISSUE TITLE
Add a call to query the servers defined in an OMAGServerConfigStore

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#4134]
Here is my draft design
1)  introducing a new interface
`/**
 * OMAGServerConfigStoreQueryAll provides a method to retrieve all the stored servers. It is an extension to the OMAGServerConfigStore interface
 * to the configuration for an OMAG Server. This is accessed through a connector.
 *
 * This function has been added to a new interface so existing implementations using OMAGServerConfigStore continue to work.
 */
public interface OMAGServerConfigStoreRetrieveAll extends OMAGServerConfigStore
{
    /**
     * Retrieve all the stored server configurations
     *
     * @return the set of server configurations present in this OMAG Server Config store
     */
    Set<OMAGServerConfig> retrieveAllServerConfigs();

}`

The idea is to not effect existing connectors that implement the existing interface.

2) Changing EncryptedFileBasedServerConfigStoreConnector and FileBasedServerConfigStoreConnector to implement OMAGServerConfigStoreRetrieveAll 

3) retrieveAllServerConfigs implementation will involve querying the current directory for files ending in config, it will loop through the files names it has found, putting them into the variable configStoreName and will call the existing retrieveServerConfig on each valid file it has found. This is a bit contrived but allows us hopefully not effect the existing implementations or duplicate code. If a file cannot be read or does not end in config - we ignore it. 

4) A new admin call will be added called something like retrieveAllStoredServers,it will do a runtime check on the connector to see if it is implements the new interface, if it does not then a function not supported will be issued, if it does then the connector will be called. 

5) The client will be updated to add the new method.  
    
@mandy-chessell @cmgrote @grahamwallis @dkneisly @planetf1 Any feedback on this proposed design?

**Comment by davidradl** [comment]
I have just been coding up the above design. I notice that OMAGServerConfigStore has an associated server, and the admin services obtain a  connection using a serverName. In my case I do not have a serverName. So I could 
1) specify "." as the server name, which would mean the current folder and use the existing store
2) Expose a new connector that is not associated with a servername.
I plan to prototype with 1) to get something working. 2) seems a bigger change to make without getting feedback from others.

**Comment by mandy-chessell** [comment]
I wonder if this should be a different connector given that the current connector is focused on a single configuration document?  Also the file name for the config files follows a pattern that is configured for the connector - it does not necessarily end in "config"
