### ISSUE TITLE
Extend type system to cover detailed profiling result associated with a data column

### ISSUE THREAD

**Issue by cassioinboston** [odpi/egeria#414]
The following are the fields that could be captured to be associated via 1:1 relationship to a data column entity:

inferredDataType:String
inferredFormat:String
inferredLength:integer
inferredPrecision:integer
inferredScale:integer
isInferredForeignKey:boolean
isInferredPrimaryKey:boolean
domainType: string
maximumValue:string
minimumValue:string
averageValue:string
nullabilityFlag:boolean
uniqueFlag:boolean
numberDataTypeViolations:long
numberDistinctValues:long
numberEmptyValues:long
numberFormats:long
numberNullValues:long
numberPatterns:long
numberValues:long
numberSpaceValues:long
numberZeroValues:long
analysisDate:date

**Comment by cassioinboston** [comment]
@mandy-chessell I've edited the comment above to include the data types. One related aspect: we talked about frequency distribution being something we'd sync via a file. Can you elaborate on that? Should we add an attribute to the profiling annotation entity to store the file URL? Could this file be anywhere?

**Comment by mandy-chessell** [comment]
New profiling information added to area 6 ...

[area-6-discovery.xml - draw.io.pdf](https://github.com/odpi/egeria/files/2677915/area-6-discovery.xml.-.draw.io.pdf)
