### ISSUE TITLE
Asset Lineage OMAS error handling improvements technical debt

### ISSUE THREAD

**Issue by lpalashevski** [odpi/egeria#4160]
As we are getting close to releasing Asset Lineage OMAS we would need to revise the logging and follow the practice where we add proper audit logging for handling the exceptions.

We also consider logging information events such as initial load started, asset context processes etc. as regular audit log info events.

**Comment by mandy-chessell** [comment]
Adding INFO type audit log messages as described above is fine to do.
However It is important that all errors and exceptions are either logged to the audit log (if they are in a background thread) or returned in an exception with a proper error code message.  This is not a new requirement.  It is needed to enable people to diagnose problems without needing to refer to the code.  

The log.error() function does not include system action or user response information and is not easy to translate.  The call to log.error() can be used to help the component owner to fix bugs - it is just not sufficient.

This issue needs to be resolved before the component can progress to released state.  It can be fixed under a different issue/PR.

**Comment by lpalashevski** [comment]
The latest code change introduced the error handling enhancements using the audit log framework. log.error is not used anymore. Additionally we are logging info events via auditlog to improve overall monitoring of the background processing during long running operations such as initial load.

Closing this issue.
