### ISSUE TITLE
Types cache for IV OMAS

### ISSUE THREAD

**Issue by ruxandraRosu** [odpi/egeria#417]
To improve performance, use a cache to load types needed by IV OMAS. 
To refresh cache, 2 options could be used:
-Use expiry time for refreshing the cache. 
-refresh when receiving an event related to types creation/modification. These events should not happen too often

**Comment by mandy-chessell** [comment]
The types are cached in the repository content manager - no need to cache them in IV OMAS?

**Comment by ruxandraRosu** [comment]
Closing this issue and creating a new one for using OMRSRepositoryHelper to load type def from repository content manager
