### ISSUE TITLE
Allow simple way of showing full details of REST interaction in notebooks

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#4261]
Our coco pharam notebooks are pretty slick and guide a reader through the concepts of handling metadata in egeria,
and make use of a real environment to actually make this happen. Over time we have made our python functions more
slick. This helps reduce 'noise' in the notebooks so the concepts are clear, but sometimes it would be really useful for
a developer to see the exact REST API interactions, which they might copy toi postman/use in their own environment, or use as a starting point for more customization.

We already have debug functions in the notebook, so the main change here would be to add an obviously configured
'switch' (an environment variable for example - but we could render it more clearly), and if set, at each stage we show the
full REST content, headers, body etc, ideally in a way they could be cut/paste to http/curl/postman

**Comment by planetf1** [comment]
@davidradl you may have done this :-)

**Comment by davidradl** [comment]
I have assigned this to me and will put @mandy-chessell  and @planetf1 as reviewers
