### ISSUE TITLE
Error TODO in Repository Explorer for cocoMDS5 (proxy)

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#4277]
WHen using Repository Explorer in the coco pharma environment against cocoMDS5 the following message is shown
<img width="1427" alt="Screenshot 2020-12-08 at 07 32 14" src="https://user-images.githubusercontent.com/7292002/101453724-b352fc00-3927-11eb-9e23-7d73bfa30fb5.png">

cocoMDS5 is a repository proxy to coco pharma's business systems, and therefore afaik does not support enterprise queries.

The error text has a TODO that needs resolving -- in this case the main error text is correct but system detail/user action needs updating

I also noted error text cannot be cut/paste - would be useful for users recording issues.

**Comment by grahamwallis** [comment]
Was fixed in PR #4150. If you are using 2.5 maybe worth including that PR or cherry picking from it?

**Comment by planetf1** [comment]
Thanks. As not a regression and 2.5 is already running late I'd propose we leave for next release.

**Comment by grahamwallis** [comment]
Cut and paste seems to be browser specific.

It works in Safari for example:

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/17125304/101512218-b7583b80-3972-11eb-88be-b8138b195c08.png">

**Comment by grahamwallis** [comment]
(I'm not sure why that ECONNREFUSED error is not being handled properly. Thought I'd caught all of them. Will double check and raise a separate issue if necessary.

**Comment by planetf1** [comment]
this error has been corrected. closing
