### ISSUE TITLE
CRA security paths can be simplified 

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#4316]
in index.js in the cra-server folder :
It defines the cert and `key` as :
`const cert = fs.readFileSync(path.join(__dirname, '../') + "/../presentation-server/ssl/keys/server.cert");
const key = fs.readFileSync(path.join(__dirname, '../') + "/../presentation-server/ssl/keys/server.key");`

this can be simplified to :
`const cert = fs.readFileSync(path.join(__dirname, '../') + "/../presentation-server/ssl/keys/server.cert");
const key = fs.readFileSync(path.join(__dirname, '../') + "/../presentation-server/ssl/keys/server.key");`

**Comment by planetf1** [comment]
Can be closed now as fix was made & code has been migrated
