### ISSUE TITLE
Admin Services deprecated function calls

### ISSUE THREAD

**Issue by lpalashevski** [odpi/egeria#4355]
#4341 related

Following method calls can/should be replaced with the new calls:

Class | Call | Line
-- | -- | --
egeria/open-metadata-implementation/admin-services/admin-services-server/src/main/java/org/odpi/openmetadata/adminservices/OMAGServerOperationalServices.java | FunctionCall: initialize() | 693
egeria/open-metadata-implementation/admin-services/admin-services-api/src/main/java/org/odpi/openmetadata/adminservices/ffdc/exception/OMAGCheckedExceptionBase.java | FunctionCall: OCFCheckedExceptionBase() | 159
egeria/open-metadata-implementation/admin-services/admin-services-api/src/main/java/org/odpi/openmetadata/adminservices/ffdc/exception/OMAGCheckedExceptionBase.java | FunctionCall: OCFCheckedExceptionBase() | 177
egeria/open-metadata-implementation/admin-services/admin-services-api/src/main/java/org/odpi/openmetadata/adminservices/ffdc/exception/OMAGConfigurationErrorException.java | FunctionCall: OMAGCheckedExceptionBase() | 157
egeria/open-metadata-implementation/admin-services/admin-services-api/src/main/java/org/odpi/openmetadata/adminservices/ffdc/exception/OMAGConfigurationErrorException.java | FunctionCall: OMAGCheckedExceptionBase() | 175
egeria/open-metadata-implementation/admin-services/admin-services-api/src/main/java/org/odpi/openmetadata/adminservices/ffdc/exception/OMAGInvalidParameterException.java | FunctionCall: OMAGCheckedExceptionBase() | 175
egeria/open-metadata-implementation/admin-services/admin-services-api/src/main/java/org/odpi/openmetadata/adminservices/ffdc/exception/OMAGInvalidParameterException.java | FunctionCall: OMAGCheckedExceptionBase() | 157
egeria/open-metadata-implementation/admin-services/admin-services-api/src/main/java/org/odpi/openmetadata/adminservices/ffdc/exception/OMAGNotAuthorizedException.java | FunctionCall: OMAGCheckedExceptionBase() | 175
egeria/open-metadata-implementation/admin-services/admin-services-api/src/main/java/org/odpi/openmetadata/adminservices/ffdc/exception/OMAGNotAuthorizedException.java | FunctionCall: OMAGCheckedExceptionBase() | 157
egeria/open-metadata-implementation/admin-services/admin-services-spring/src/main/java/org/odpi/openmetadata/adminservices/spring/ConfigDefaultsResource.java | FunctionCall: setServerURLRoot() | 56

**Comment by mandy-chessell** [comment]
These calls are provided to support backward compatibility
