### ISSUE TITLE
Common Services deprecated function calls

### ISSUE THREAD

**Issue by lpalashevski** [odpi/egeria#4356]
#4341 related

Following method calls can/should be replaced with the new calls:

Class | Call | Line
-- | -- | --
egeria/open-metadata-implementation/common-services/repository-handler/src/main/java/org/odpi/openmetadata/commonservices/repositoryhandler/RepositoryHandler.java | FunctionCall: classifyEntity() | 1066
egeria/open-metadata-implementation/common-services/repository-handler/src/main/java/org/odpi/openmetadata/commonservices/repositoryhandler/RepositoryHandler.java | FunctionCall: classifyEntity() | 1772
egeria/open-metadata-implementation/common-services/repository-handler/src/main/java/org/odpi/openmetadata/commonservices/repositoryhandler/RepositoryHandler.java | FunctionCall: classifyEntity() | 1016
egeria/open-metadata-implementation/common-services/repository-handler/src/main/java/org/odpi/openmetadata/commonservices/repositoryhandler/RepositoryHandler.java | FunctionCall: createRelationship() | 5296
egeria/open-metadata-implementation/common-services/repository-handler/src/main/java/org/odpi/openmetadata/commonservices/repositoryhandler/RepositoryHandler.java | FunctionCall: declassifyEntity() | 1038
egeria/open-metadata-implementation/common-services/repository-handler/src/main/java/org/odpi/openmetadata/commonservices/repositoryhandler/RepositoryHandler.java | FunctionCall: declassifyEntity() | 1107
egeria/open-metadata-implementation/common-services/ffdc-services/src/test/java/org/odpi/openmetadata/commonservices/ffdc/exceptions/RuntimeExceptionTest.java | FunctionCall: getErrorMessage() | 81
egeria/open-metadata-implementation/common-services/ffdc-services/src/main/java/org/odpi/openmetadata/commonservices/ffdc/exceptions/OMAGCheckedExceptionBase.java | FunctionCall: OCFCheckedExceptionBase() | 172
egeria/open-metadata-implementation/common-services/ffdc-services/src/main/java/org/odpi/openmetadata/commonservices/ffdc/exceptions/OMAGCheckedExceptionBase.java | FunctionCall: OCFCheckedExceptionBase() | 224
egeria/open-metadata-implementation/common-services/ffdc-services/src/main/java/org/odpi/openmetadata/commonservices/ffdc/exceptions/OMAGCheckedExceptionBase.java | FunctionCall: OCFCheckedExceptionBase() | 197
egeria/open-metadata-implementation/common-services/ffdc-services/src/main/java/org/odpi/openmetadata/commonservices/ffdc/exceptions/OMAGCheckedExceptionBase.java | FunctionCall: OCFCheckedExceptionBase() | 148
egeria/open-metadata-implementation/common-services/multi-tenant/src/main/java/org/odpi/openmetadata/commonservices/multitenant/OCFOMASServiceInstance.java | FunctionCall: OCFOMASServiceInstance() | 77
egeria/open-metadata-implementation/common-services/multi-tenant/src/main/java/org/odpi/openmetadata/commonservices/multitenant/OCFOMASServiceInstance.java | FunctionCall: OCFOMASServiceInstance() | 56
egeria/open-metadata-implementation/common-services/multi-tenant/src/main/java/org/odpi/openmetadata/commonservices/multitenant/OCFOMASServiceInstance.java | FunctionCall: OCFOMASServiceInstance() | 35
egeria/open-metadata-implementation/common-services/multi-tenant/src/main/java/org/odpi/openmetadata/commonservices/multitenant/OCFOMASServiceInstance.java | FunctionCall: OCFOMASServiceInstance() | 109
egeria/open-metadata-implementation/common-services/multi-tenant/src/main/java/org/odpi/openmetadata/commonservices/multitenant/ffdc/exceptions/NewInstanceException.java | FunctionCall: OMAGCheckedExceptionBase() | 132
egeria/open-metadata-implementation/common-services/ffdc-services/src/main/java/org/odpi/openmetadata/commonservices/ffdc/exceptions/PropertyServerException.java | FunctionCall: PropertyServerException() | 147
egeria/open-metadata-implementation/common-services/ocf-metadata-management/ocf-metadata-handlers/src/main/java/org/odpi/openmetadata/commonservices/ocf/metadatamanagement/handlers/SchemaTypeHandler.java | FunctionCall: updateEntity() | 1175
egeria/open-metadata-implementation/common-services/ocf-metadata-management/ocf-metadata-handlers/src/main/java/org/odpi/openmetadata/commonservices/ocf/metadatamanagement/handlers/SchemaTypeHandler.java | FunctionCall: updateEntity() | 688
egeria/open-metadata-implementation/common-services/repository-handler/src/main/java/org/odpi/openmetadata/commonservices/repositoryhandler/RepositoryHandler.java | FunctionCall: updateEntityProperties() | 514

**Comment by mandy-chessell** [comment]
These calls were left in the code because they were in use by components that are part of the lineage function.  They can be removed if they are no longer needed since none are providing sn externlly supported interface.

**Comment by mandy-chessell** [comment]
They can not be re-coded to use the new methods because they do not have the information such as:
```
                                     String                  externalSourceGUID,
                                     String                  externalSourceName,
```
Passing nuls on these parameter means "LocalCohort" which will produce the wrong outcome in some case - particularly those calls from the Data Engine OMAS.

**Comment by lpalashevski** [comment]
Related to change in #3843

**Comment by lcpopa** [comment]
Still relevant
