### ISSUE TITLE
OCF deprecated function calls

### ISSUE THREAD

**Issue by lpalashevski** [odpi/egeria#4358]
#4341 related

Follwoing deprecated method calls should be replaced with the new implementations:

Class| Method | Line
-- | -- | --
egeria/open-metadata-implementation/frameworks/open-connector-framework/src/main/java/org/odpi/openmetadata/frameworks/connectors/ffdc/OCFCheckedExceptionBase.java | FunctionCall: getErrorMessage() | 355
egeria/open-metadata-implementation/frameworks/open-connector-framework/src/main/java/org/odpi/openmetadata/frameworks/connectors/ffdc/OCFCheckedExceptionBase.java | FunctionCall: getErrorMessage() | 328
egeria/open-metadata-implementation/frameworks/open-connector-framework/src/main/java/org/odpi/openmetadata/frameworks/connectors/ffdc/OCFRuntimeException.java | FunctionCall: getErrorMessage() | 234
egeria/open-metadata-implementation/frameworks/open-connector-framework/src/main/java/org/odpi/openmetadata/frameworks/connectors/ffdc/OCFRuntimeException.java | FunctionCall: getErrorMessage() | 207
egeria/open-metadata-implementation/frameworks/open-connector-framework/src/main/java/org/odpi/openmetadata/frameworks/connectors/properties/AssetSchemaAttribute.java | FunctionCall: getLocalSchemaType() | 271
egeria/open-metadata-implementation/frameworks/open-connector-framework/src/main/java/org/odpi/openmetadata/frameworks/connectors/ffdc/ConnectionCheckedException.java | FunctionCall: OCFCheckedExceptionBase() | 183
egeria/open-metadata-implementation/frameworks/open-connector-framework/src/main/java/org/odpi/openmetadata/frameworks/connectors/ffdc/ConnectorCheckedException.java | FunctionCall: OCFCheckedExceptionBase() | 149
egeria/open-metadata-implementation/frameworks/open-connector-framework/src/main/java/org/odpi/openmetadata/frameworks/connectors/ffdc/ConnectorCheckedException.java | FunctionCall: OCFCheckedExceptionBase() | 169
egeria/open-metadata-implementation/frameworks/open-connector-framework/src/main/java/org/odpi/openmetadata/frameworks/connectors/ffdc/OCFCheckedExceptionBase.java | FunctionCall: OCFCheckedExceptionBase() | 212
egeria/open-metadata-implementation/frameworks/open-connector-framework/src/main/java/org/odpi/openmetadata/frameworks/connectors/ffdc/OCFCheckedExceptionBase.java | FunctionCall: OCFCheckedExceptionBase() | 270
egeria/open-metadata-implementation/frameworks/open-connector-framework/src/main/java/org/odpi/openmetadata/frameworks/connectors/ffdc/PropertyServerException.java | FunctionCall: OCFCheckedExceptionBase() | 188

**Comment by mandy-chessell** [comment]
These methods are required to maintain backward compatibility
