### ISSUE TITLE
OMRS obsolete function calls

### ISSUE THREAD

**Issue by lpalashevski** [odpi/egeria#4359]
#4341 related

Following method calls can/should be replaced with the new calls:

Class|Method|Line
-- | -- | --
egeria/open-metadata-implementation/repository-services/repository-services-apis/src/main/java/org/odpi/openmetadata/repositoryservices/connectors/openmetadatatopic/OpenMetadataTopicConnector.java | FunctionCall: checkForEvents() | 171
egeria/open-metadata-implementation/repository-services/repository-services-spring/src/main/java/org/odpi/openmetadata/repositoryservices/rest/server/spring/AnonRepositoryServicesResource.java | FunctionCall: getMetadataCollectionId() | 64
egeria/open-metadata-implementation/repository-services/repository-services-apis/src/main/java/org/odpi/openmetadata/repositoryservices/ffdc/exception/OMRSCheckedExceptionBase.java | FunctionCall: OCFCheckedExceptionBase() | 228
egeria/open-metadata-implementation/repository-services/repository-services-apis/src/main/java/org/odpi/openmetadata/repositoryservices/ffdc/exception/OMRSCheckedExceptionBase.java | FunctionCall: OCFCheckedExceptionBase() | 185
egeria/open-metadata-implementation/repository-services/repository-services-apis/src/main/java/org/odpi/openmetadata/repositoryservices/ffdc/exception/OMRSCheckedExceptionBase.java | FunctionCall: OCFCheckedExceptionBase() | 203
egeria/open-metadata-implementation/repository-services/repository-services-apis/src/main/java/org/odpi/openmetadata/repositoryservices/ffdc/exception/OMRSCheckedExceptionBase.java | FunctionCall: OCFCheckedExceptionBase() | 161
egeria/open-metadata-implementation/repository-services/repository-services-apis/src/main/java/org/odpi/openmetadata/repositoryservices/ffdc/exception/OMRSConfigErrorException.java | FunctionCall: OMRSRuntimeException() | 162
egeria/open-metadata-implementation/repository-services/repository-services-apis/src/main/java/org/odpi/openmetadata/repositoryservices/connectors/omrstopic/OMRSTopicListenerBase.java | FunctionCall: processClassifiedEntityEvent() | 1350
egeria/open-metadata-implementation/repository-services/repository-services-apis/src/main/java/org/odpi/openmetadata/repositoryservices/events/OMRSInstanceEventProcessor.java | FunctionCall: processClassifiedEntityEvent() | 163
egeria/open-metadata-implementation/repository-services/repository-services-apis/src/main/java/org/odpi/openmetadata/repositoryservices/connectors/omrstopic/OMRSTopicListenerBase.java | FunctionCall: processDeclassifiedEntityEvent() | 1408
egeria/open-metadata-implementation/repository-services/repository-services-apis/src/main/java/org/odpi/openmetadata/repositoryservices/events/OMRSInstanceEventProcessor.java | FunctionCall: processDeclassifiedEntityEvent() | 218
egeria/open-metadata-implementation/repository-services/repository-services-apis/src/main/java/org/odpi/openmetadata/repositoryservices/connectors/omrstopic/OMRSTopicListenerBase.java | FunctionCall: processReclassifiedEntityEvent() | 1468
egeria/open-metadata-implementation/repository-services/repository-services-apis/src/main/java/org/odpi/openmetadata/repositoryservices/events/OMRSInstanceEventProcessor.java | FunctionCall: processReclassifiedEntityEvent() | 276

**Comment by mandy-chessell** [comment]
These calls are providing backward compatibility support and are still needed.
