### ISSUE TITLE
Remove presentation server

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#4360]
The presentation server has been moved to a new Git repositoryhttps://github.com/odpi/egeria-react-ui

**Comment by planetf1** [comment]
Please don't remove until the docker build is also sorted, plus the assemblies/packages or it will break other aspects of process such as merge. 

See #4110 open to track the removal and migration

**Comment by planetf1** [comment]
@davidradl ref commit - it's important we unwind this in the order referenced in #4110 or we will cause breakages.
Code deletion will be near the last task - we have to do the other steps first (I will try and start looking at this in the next day or two)

**Comment by davidradl** [comment]
> @davidradl ref commit - it's important we unwind this in the order referenced in #4110 or we will cause breakages.
> Code deletion will be near the last task - we have to do the other steps first (I will try and start looking at this in the next day or two)

@planetf1 Thanks - I have been updating the documentation in the new repo. https://github.com/odpi/egeria-react-ui/issues/24. I can close this issue if it is on your task list. Or you could make the docker changes and I could do the rest. Let me know - I am happy either way.
