### ISSUE TITLE
Update Spring dependencies once netflix zuul block addressed

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#4441]
As per https://github.com/odpi/egeria/issues/4263, the latest springboot etc versions are broken by netflix zuul due to spring-cloud needing to be updated. ConfigurationBeanFactoryMetadata was deprecated in spring boot 2.2, October 2019.

Need to monitor this component for updates, then hopefully we can return to regular spring updates.

An alternative is to have divergence between the chassis (where zuul isn't needed) and the spring UI (which is) - the former being most critical to keep updated for security reasons

**Comment by planetf1** [comment]
@lpalashevski zuul is preventing us updating our spring dependencies currently.
I believe we have the option to consider removing zuul, and ensuring all UI requests are targetted directly to the static content server. Shall we open a separate issue for that? Then once done we can use this issue to resume our spring updates as per dependabot

**Comment by lpalashevski** [comment]
@planetf1 Just created #4549. We will test and propose configuration changes on the next call so we can proceed with removal of zull library.

**Comment by planetf1** [comment]
In addition to base spring, when we are able to action this we need to cover

 * springdoc-openapi-ui
 
 as this is also held back by the spring update block

**Comment by planetf1** [comment]
Also I suggest updating :
*  micrometer-registry-prometheus

**Comment by planetf1** [comment]
see https://github.com/odpi/egeria/pull/5030 for a sample PR where I have cherry-picked each spring related update recommended by dependabot in April.

I then made a few further changes but the chassis failed to start
