### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by Elio-Cecchetto** [odpi/egeria#4459]
In this folder is missing the **index.yaml** file 
https://github.com/odpi/egeria/tree/master/open-metadata-resources/open-metadata-deployment/charts

**Comment by planetf1** [comment]
An index.yaml file is needed to allow the chart directory to be a helm repository.

It is possible to do this as part of a build, but I see it more as a publishing operation for our charts. Having the index.yaml only locally is of limited value. we really want to publish to a well known location - be it one we own, or a 3rd party repo. #1514 was opened for this. However We have moved the vdc chart over to the egeria-samples repository, and it is likely this chart will follow which adds a further change. Finally operator work is underway which has a similar need for publishing - albeit there to an operator catalog

I therefore propose
  - move 1514 over to the samples repo
  - update the README to clarify how to install/link to publishing oneself
