### ISSUE TITLE
Gaian plugin needs to remove hardcoded userid/password & use config

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#447]
The userid/password to connect to ranger is currently hardcoded in

open-metadata-implementation/adapters/governance-engines-plugins/gaian-ranger-plugin/src/main/java/org/odpi/openmetadata/adapters/governanceenginesplugins/gaianrangerplugin/RangerPolicyResultFilter.java

Whilst this will allow some initial testing, this needs changing fairly soon as default passwords will not be used in any sensibly configured system - certainly not with externally exposed deployments. I think this is needed soon,and for the MVP/demos.

(search for admin:admin)
re: review https://github.com/odpi/egeria/pull/416

**Comment by mandy-chessell** [comment]
Is this fixed?

**Comment by planetf1** [comment]
Yes - can close.
