### ISSUE TITLE
Egeria lab notebooks failing in master - servers not starting

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#4472]
All servers reporting
```
                       error message is: OMAG-ADMIN-400-012 The OMAG server cocoMDS2 has been passed an invalid admin services class name org.odpi.openmetadata.accessservices.securityofficer.server.admin.admin.SecurityOfficerAdmin for access service Security Officer

```
during startup
cc: @mandy-chessell

**Comment by mandy-chessell** [comment]
Sorry about that - I'll have a look at it

**Comment by mandy-chessell** [comment]
Are you using an old config file?  Trying to work out where the class name is coming from.  The correct class name is 
`org.odpi.openmetadata.accessservices.securityofficer.server.admin.SecurityOfficerAdmin` and the code uses

```
SecurityOfficerAdmin.class.getName()
```
to set it up.  So a bit puzzled.  This class name has not changed in the recent restructure either.

**Comment by planetf1** [comment]
Ah... that's possible... as I've been working with persistent storage in k8s..  So you are right that I may well have an old config file! Will cleanup and check. 

Do we say anything about version compatibility of config files? I wonder if we need to make it clear they need recreating?

**Comment by planetf1** [comment]
Your suggestion was correct. I had enabled persistence (which was working). So in terms of the failure to start, that is user error. The only question is whether a user could fall into this trap generally, and whether we need to document

**Comment by mandy-chessell** [comment]
Security Officer OMAS is in developement state so it is legitimate that it changes

**Comment by planetf1** [comment]
Agreed. Will close. (longer term we should consider testing with prior version config files - to ensure no regressions in released areas)
