### ISSUE TITLE
Extend type system to cover quality score associated with a data column or a data set

### ISSUE THREAD

**Issue by cassioinboston** [odpi/egeria#449]
A data column can have multiple quality scores associated to it, for different types of problems. Examples of quality problem types include:

- Data class violations
- Data type violations
- Format violations
- Minimum/Maximum value violations
- Missing values
- Suspect values
- Duplicate values
- Rule violations

The set of problem types is open and dependent on a given system / catalog capabilities. 

Each quality score for each type of problem could have additional properties associated to it: confidence, date it was calculated, etc. The set of such properties may differ across providers and should be open. 

A combined quality score for an entire data set can be typically calculated as the average of the scores for all its columns, but other factors may be taken into account by a given system and we should be able to associate a score to a data set, independently of the way it is calculated.

**Comment by mandy-chessell** [comment]
[area-6-discovery.xml - draw.io.pdf](https://github.com/odpi/egeria/files/2667671/area-6-discovery.xml.-.draw.io.pdf)
Design for the Area 6 open metadata types

**Comment by mandy-chessell** [comment]
Change merged into master https://github.com/odpi/egeria/blob/master/open-metadata-publication/website/open-metadata-types/0640-Quality-Scores.md
