### ISSUE TITLE
Pagination of OMRS REST services

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#4515]
Does the pagination of OMRS REST services currently work as expected?

I'm seeing responses like the following as the `nextPageURL` being returned, where the POST'd body of a search request is simply serialized into a JSON string that is appended at the end of the URL:

```json
{
    "class": "EntityListResponse",
    "relatedHTTPCode": 200,
    "nextPageURL": "https://localhost:9443me/instances/entities/by-property{{\"class\":\"EntityPropertyFindRequest\",\"offset\":1,\"pageSize\":0,\"typeGUID\":\"0db3e6ec-f5ef-4d75-ae38-b7ee6fd6ec0a\"}}",
    "offset": 0,
    "pageSize": 1,
    "entities": []
}
```

(which I don't think are valid, and likely to result in 400 or 404 responses if accessed as-is?)

Or is there some embedded processing elsewhere in the REST handling that does something like detect the `{{` in the URL and knows that it should translate anything therein into an object, and POST that object to the provided URL (which is also incomplete, but perhaps is a separate issue related to a misconfiguration on my end)?

**Comment by mandy-chessell** [comment]
I do not think anything is using it
