### ISSUE TITLE
Release 2.6 - CTS failures 

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#4527]
Release 2.6 fails with graph repo with :
```
    "testCaseCount": 4951,
     "testFailedCount": 22,
     "testPassCount": 4929,
```
At least some of these are 'findEntities' errors which may relate to #4526

Run on k8s using the coco pharma charts. platform restarted and only CTS ran

See https://ibm.box.com/s/8vdm3vdt0gi9pse06fhz0mu74c6rwrdn for the log

Will run inmem shortly... and summarise

**Comment by planetf1** [comment]
Inmem tests currently running, but already have some failures. 
I suspect a common cause may be around finding entities

**Comment by planetf1** [comment]
Added inmem test results to same folder. In summary
```
Date of conformance test:          2021-01-27T09:34:33.979+00:00
Number of tests that were run:     4951
Number of tests that failed:       341
Number of tests that were skipped: 0
```

**Comment by planetf1** [comment]
Same result seen when running locally (just to eliminate any specifics to the k8s/chart)

**Comment by mandy-chessell** [comment]
@grahamwallis traced these errors to inconsistencies in the way we are referencing dependent EntityDefs in the TypeDefs.  

There are 4 of these types of references:
* SuperType in a TypeDef
* SuperType in a TypeDefPatch
* ValidEntityDefs in ClassificationDef
* EntityType in RelationshipEndDef

The type of these references is TypeDefLink.  However EntityDef inherits from TypeDefLink and so there are many cases where a full EntityDef is passed and stored.

TypeDef, ClassificationDef and RelationshipEndDef use the clone constructor from TypeDefLink to strip down the EntityDef to a TypeDefLink on the getXXX() methods.  So the type of the reference is stripped down the first time the object is cloned or serialized/deserialized via Jackson.  However TypeDefPatch did not have this protection and there were an increasing number of patched types that were storing and returning full EntityDefs as references.

More importantly, the `equals()` method tests the stored value.  The CTS uses the equals() method and picked up the inconsistency.

To be completely safe, it should be the setXXX() methods that strip down the reference object by passing it through the TypeDefLink clone constructor to ensure we only store the stripped down TypeDefLink.

The resulting methods look something like this ...
```
    /**
     * Set up the new super type.
     *
     * @param superType super type link
     */
    public void setSuperType(TypeDefLink superType)
    {
        if (superType == null)
        {
            this.superType = null;
        }
        else
        {
            this.superType = new TypeDefLink(superType);
        }
    }
```

This change has the advantage that our type definitions are smaller as a result.

**Comment by grahamwallis** [comment]
@mandy-chessell Yep - that looks perfect. I approved the PR.

**Comment by planetf1** [comment]
Clean test run on inmem repo on the 2.6 build.
```
Date of conformance test:          2021-01-28T13:44:11.010+00:00
Number of tests that were run:     4951
Number of tests that failed:       0
Number of tests that were skipped: 0
```
still to test graph

**Comment by planetf1** [comment]
Graph ran perfectly too
