### ISSUE TITLE
NPE in RepositoryContentValidator recursive search property match

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#4535]
When popping from a nest property condition the operator will be null (by design) and should not be tested in the PropertyComparisonOperator switch statement. If null it is because the subtree is complete and processing should proceed directly to the calculation of the number of matching conditions.

**Comment by planetf1** [comment]
No sign of NPEs - albeit the types are now changed to avoid the underlaying problem. I think we can be comfortable enough to close
