### ISSUE TITLE
Release 2.6 - Dino error : Cannot add cohort for unknown server cocoMDS1

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#4546]
When running the coco pharma lab environment, with servers configured/started\
 - Access & login to presentation server UI
 - Navigate to dino
 - click on cocoMDS1
 - expand cohorts
 - expand Cohort: cocoCohort

Popup error occurs
<img width="1214" alt="Screenshot 2021-01-28 at 17 57 18" src="https://user-images.githubusercontent.com/7292002/106178955-48d57400-6192-11eb-9588-249d68618c05.png">

**Comment by planetf1** [comment]
No relevant messages on egeria platforms
Output from presentation server console:
 - see https://gist.github.com/efcb1c11ba892f4cdfe949755e42ba3c

**Comment by grahamwallis** [comment]
Fixed by Egeria-react-ui PR #62
