### ISSUE TITLE
Assess Sonarqube for Subject Area OMAs code

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#455]

**Comment by planetf1** [comment]
See https://docs.sonarqube.org/7.4/project-administration/narrowing-the-focus/ for some ideas on configuring sonarkube to ignore duplicate code, I have contacted the build team as we don't have admin access. ideally just ignoring the duplicate code checks on generated code could be useful. The suggestion at that link makes use of code tagged @generated but applies to all rules - skipping any other bug checking which could be valuable. will let you know any updates from build team

**Comment by davidradl** [comment]
Waiting for a rerun of the Sonar to see if there are still any bugs in the sonar report in the Subject Area

**Comment by mandy-chessell** [comment]
Is this fixed?
