### ISSUE TITLE
upgrade jackson and spring dependencies

### ISSUE THREAD

**Issue by bogdan-sava** [odpi/egeria#460]
jackson 2.9.2 curently used is affected by security issue.
Update dependency to jackson 2.9.7 and test the functionality

**Comment by bogdan-sava** [comment]
Build is successful.
Usecases are running successful with jackson 2.9.7 in OMAG Server is also successful.
I will extend the issue to upgrade the spring-web and spring-starter-web also.

**Comment by bogdan-sava** [comment]
All the tests are passed.
{code}
 <jackson.version>2.9.7</jackson.version>
 <spring-boot.version>2.1.1.RELEASE</spring-boot.version>
 <spring-web.version>5.1.3.RELEASE</spring-web.version>
{code}

**Comment by cmgrote** [comment]
Can be closed?
