### ISSUE TITLE
Release 2.6 - Tex requests types from wrong server?

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#4640]
Testing Release 2.6, I click on 'cocoMDS5' (enterprise selected) to query Types.
cocoMDS5 is a repository proxy (read only)

ie

<img width="1418" alt="Screenshot 2021-02-01 at 17 52 53" src="https://user-images.githubusercontent.com/7292002/106497827-73873b80-64b6-11eb-8389-9803fe1c9808.png">

HOWEVER, when looking at the output from the react ui container I see:

```
segment1 servers
deserializeUser called with id 6
findByUserId
passport.deserializeUser user is [object Object],err isnull
/servers/* post called /servers/coco/tex/users/garygeeke/types
Got body: {
  serverName: 'cocoMDS5',
  platformName: 'Core',
  enterpriseOption: true,
  deprecationOption: false
}
 getServerInfoFromEnv() 1
 getServerInfoFromEnv() 2
Found server name coco
downstream url https://lab-datalake:9443/servers/cocoView1/open-metadata/view-services/tex/users/garygeeke/types
response.data
{
  class: 'TypeExplorerResponse',
  relatedHTTPCode: 400,
  exceptionClassName: 'org.odpi.openmetadata.viewservices.tex.api.ffdc.TexViewServiceException',
  actionDescription: 'getTypeExplorer',
  exceptionErrorMessage: 'The type explorer view service operation getTypeExplorer encountered a problem with the repository, the message is OMRS-REST-API-503-002 There is no enterprise repository to support REST API call getAllTypes',
  exceptionErrorMessageId: 'OMVS-TYPE-EXPLORER-400-009',
  exceptionErrorMessageParameters: [
    'getTypeExplorer',
    'OMRS-REST-API-503-002 There is no enterprise repository to support REST API call getAllTypes'
  ],
  exceptionSystemAction: 'The system could not complete a repository operation due to the error indicated.',
  exceptionUserAction: 'Look at the error message and check the configuration and state of the repository server.'
}

```

Note that this is referring to cocoView1 -- and it would be reasonable here to see this error, indeed this is why cocoView1 is NOT in the configuration for the tex view service -- intentionally

This does not occur when doing a non-enterprise query

Two questions here
 - is it correct for cocoView1 to be in the cohort
 - Why is the behaviour different when accessing a repository proxy?
 
 cc: @grahamwallis @mandy-chessell

**Comment by mandy-chessell** [comment]
Is this the right intepretation?  It looks like it is working ok to me.

The TEX UI will always call cocoView1 and then the tex view service in cocoView1 will call the repositories.  Since cocoMDS5 is a repository proxy, it does not have the enterprise serivces running.  This means the error message is completely correct.  (The enterprise services are only activated on servers where the OMASs are running.)

**Comment by planetf1** [comment]
Ah, I hadn't realised the enterprise services weren't active on the proxy. That does makes sense. 
Maybe there's a case for elaborating possible reasons in the error message - I know one of our users was performing a similar action, and may not have understood why.

**Comment by planetf1** [comment]
closing
