### ISSUE TITLE
UI Chassis, Egeria UI API updates

### ISSUE THREAD

**Issue by lpalashevski** [odpi/egeria#4649]
As outcome of the disscussion related to #4549 we need to adjust couple of areas in the ui-chassis-spring app that will allow us to further detach these components and allow more flexible deployment options.

- Remove the endpoints that are used as helpers to support loading of resources from the static UI:
`/api/public/css/theme` and `/api/public/js/global`; these will be linked directly from the static resources; the theme resources can be replaced during deploy time.

- Add configuration option to specify `Access-Control-Allow-Origin` http header for all the responses with following options: if not specified do not iclude the origin; if specified in the config apply it to all /api endpoints and allow resource sharing only from specified origin (url).

@bogdan-sava @sarbull feel free to add if I missed something.

**Comment by sarbull** [comment]
@lpalashevski i propose to also extract and rename `ui-chassis-spring` to `egeria-api` into a separate repository

**Comment by lpalashevski** [comment]
> @lpalashevski i propose to also extract and rename `ui-chassis-spring` to `egeria-api` into a separate repository

Moving it outside of egeria main repo sounds good; This application it not tightly coupled with OMAG eco-system but uses client libraries to integrate. 

Before doing this we need to check all the aspects with respect to the Egeria release, but also includng all resources where version of the UI is used like demos and labs.

About the name of the repo I think egeria-api is too ambigious because are different apis exposing different functional areas in egeria openmetadata platform, we probabbly want to have something that suggesst that it is specific to egeria-ui. Few susggestions:

- egeria-ui-api  
- egeria-ui-spring
...

cc: @bogdan-sava

**Comment by sarbull** [comment]
> > @lpalashevski i propose to also extract and rename `ui-chassis-spring` to `egeria-api` into a separate repository
> 
> Moving it outside of egeria main repo sounds good; This application it not tightly coupled with OMAG eco-system but uses client libraries to integrate.
> 
> Before doing this we need to check all the aspects with respect to the Egeria release, but also includng all resources where version of the UI is used like demos and labs.
> 
> About the name of the repo I think egeria-api is too ambigious because are different apis exposing different functional areas in egeria openmetadata platform, we probabbly want to have something that suggesst that it is specific to egeria-ui. Few susggestions:
> 
> * egeria-ui-api
> * egeria-ui-spring
>   ...
> 
> cc: @bogdan-sava

drop the "-ui", it's unnecessary. (API - application programming interface) the API can be used maybe also for a mobile application, that's why i believe it is better to name it `egeria-api`.

**Comment by planetf1** [comment]
I'm inclined to agree with @lpalashevski - though we should get broader agreement on a team call.  Although it does offer an api, I think the first thought of 'api' on egeria are the base services -- so egeria-api would indeed be confusing. My concern with egeria-ui-* remains that of confusion between our two uis. By technology it could be 'egeria-spring-ui' or 'egeria-polymer-ui' ?

That new repo would need to build and version the required docker images (we did the same for egeria-react-ui -- and the sample process there may be a good starting point ). Also think about what artifacts are delivered. You'd need to figure out the testing dependency between ui and base and we'd need to figure out the release/versioning strategy

The references in egeria I can think of include:
 * the odpi-egeria-lab chart in the base egeria code. 'Soon' I expect this to move to a samples repository - this makes for a better layering. It only refers to the container image/version, so needs updating if they change, or indeed other deployment related configuration is needed in k8s
  * The docker-compose coco sample. As above, though I'm thinking it may be time to defocus this as it's hard to keep up with the k8s charts
  * There is a 'ui' notebook which talks about the egeria ui. WOrth thinking about what would be desirable from a demo perspective, though this is somewhat unrelated to the mechanics of build
   * We include the UI in the base egeria assembly. I expect we'll also move the assembly work out now that we are creating assets across repos. Each repo should deliver something, and the new assembly repo can do any additional aggregation - if we decide that's needed

Note that for the first three of these it's worth considering if the UI should be present in those scenarios. The docker/k8s environments were development for demos, and really tutorials. There is a new chart for a basic deployment, but in 2021 I expect there to be more focus on operator based deployment (from me at least). Whether deployment of the UI features there, or it is a seperate operator, or simply augmented using a helm chart I don't know yet....

**Comment by planetf1** [comment]
> drop the "-ui", it's unnecessary. (API - application programming interface) the API can be used maybe also for a mobile application, that's why i believe it is better to name it `egeria-api`.
> 
> Edit:
> it can also be seen as a facade of the backend.

Where the backend offers the egeria  api ...... which is why I don't think the name works.

For the presentation server work these intermediate layer services were called 'view services' and are fully integrated into the core of egeria. Would you expect to move the polymer UI over the same same (even if augmented) services? Is the current spring app a short term layer do you think? 

Also for mobile - it's still supporting a UI? mostly. 

Names are always the hardest part...

**Comment by sarbull** [comment]
@planetf1 UI stands for user interface.. there is no user interface in a backend

**Comment by sarbull** [comment]
these endpoints are not used in the UI anymore after the API_URL implementation and the CORS feature is in place for the ui-chassis-spring
