### ISSUE TITLE
data-engine-fvt pom is malformed and cannot be pushed to maven central

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#4671]
In 2.6 we cannot push data-engine-fvt to maven central as no source is included

JCenter reported error is 'Package should include sources as part of the package.'

As a comparison, asset-consumer-fvt does publish correctly, and contains binary & sources. As a binary module it's not that useful, though the source attachment does contain the source code.

Need to check/compare and see why data-engine-fvt is not working.

As a fvt test I propose no need to fix for 2.6

**Comment by mandy-chessell** [comment]
@planetf1 agreed

**Comment by planetf1** [comment]
This is not causing an issue with the new pipeline. closing.
