### ISSUE TITLE
EntityDefs without supertypes?

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#4672]
I was under the impression that after we added the `OpenMetadataRoot` type, that all EntityDefs would now have supertypes (at least the `OpenMetadataRoot`, given its description as "Common root for all open metadata entity types").  However, a number of EntityDefs do not appear to have any supertype:

- Annotation
- InformalTag
- Rating
- LastAttachment
- SearchKeyword

Just wanted to confirm if I'd understood `OpenMetadataRoot` correctly, or if these non-supertyped EntityDefs were intentional?

**Comment by grahamwallis** [comment]
I think they do have super types.

Tex displays them as all having a common root.

Here's an extract from the 2.5 types archive which did the updates when OpenMetadataRoot was introduced.

private TypeDefPatch updateAnnotation()
    {
        /*
         * Create the Patch
         */
        final String typeName = "Annotation";

        final String superTypeName = "OpenMetadataRoot";

        TypeDefPatch typeDefPatch = archiveBuilder.getPatchForType(typeName);

        typeDefPatch.setUpdatedBy(originatorName);
        typeDefPatch.setUpdateTime(creationDate);
        typeDefPatch.setSuperType(this.archiveBuilder.getEntityDef(superTypeName));

        return typeDefPatch;
    }

Is there something more subtle going on?

**Comment by mandy-chessell** [comment]
I agree with @grahamwallis. The supertypes were introduced in 2.5 in a TypeDefPatch.  This means they will be passed to the repository connector initially without super types.  However as the patched are applied, the super types are added in.

**Comment by cmgrote** [comment]
Just checking everyone was still awake 😬   (🤦‍♂️ I was looking at the wrong thing, sorry!)
