### ISSUE TITLE
Support Apache Solr

### ISSUE THREAD

**Issue by Mirovan** [odpi/egeria#4675]
Hello everyone.

I have simple question - does Egeria support Apache Solr for store indexes when we are using Janusgraph(graph database) as repository?

**Comment by planetf1** [comment]
FYI @grahamwallis

**Comment by grahamwallis** [comment]
The Egeria graph repository does not currently have a configuration option for solr as the backing index behind JanusGraph, but one could be added in a similar manner to the way that the graph connector handles configuration options for Cassandra (as a persistence backend) and Elastic Search (as an indexing store).
