### ISSUE TITLE
Graph Repository performance  improvements

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#4683]
This issue covers a set of performance improvements for the graph repository find* methods. 

The approach taken Is to try where possible to perform a single graph traversal that has steps for all the referenced properties, type filtering, etc. This is a lot faster than performing a separate traversal per type, which is how cross-type queries have worked until now.

A tightly specified query (one with type filtering that narrows the scope of the query) is quite likely to contain only unique property names and in this case it is possible to perform a single traversal. A more loosely specified (or in the extreme, completely wild) query may encounter duplicate property names. Duplicates may be vertical or horizontal - as described below.

Where there are vertical duplications, such that a super type and one/more of its subtypes define a property with the same name, this is benign. The vertically duplicated properties must share the same type, otherwise the subtype would not be a refinement of the supertype. This means that the vertically duplicated type defined attributes can only differ in terms of things like 'description' which is not of interest to the graph repository. (Type definitions are not stored in the repository). The graph repository generates unique property keys used for both storage and retrieval, which include the name of the type that defines the attribute. These are always based on the most superior attribute definition - i.e. the definition from the type nearest the OpenMetataRoot type - so there is therefore no ambiguity from a vertically duplicated attribute name.

Horizontal duplicates are more of a problem. These occur when a query refers to a property for which multiple types in the scope of the query define attributes with the same name. This is perfectly legitimate - otherwise there would be a single property name space across the entire type system. These duplicated type defined attributes may have different types or index mappings and are differentiated in the graph schema. As mentioned above, they are disambiguated by the generation of unique property keys that include the name of the most superior type that introduces the attribute. There are three possible approaches to handling horizontal duplicates. One would be to include them in a single graph traversal, using an 'or()' step that covers the range of the mapping from short property name to qualified property names. However, JanusGraph issue 2231 ([https://github.com/JanusGraph/janusgraph/issues/2231]) prevents this for the time being. The second approach would be to partition the type space admitted by the query such that each partition contains no duplicates. Each resulting partition would then be the subject of a separate traversal, with the results being aggregated. However, the partitioning of the query type space into disjoint type spaces is considered a complex solution, requiring partitioning on different dimensions for each of the duplicated property names. Whilst this is probably feasible, if 2231 is resolved in the near future, the single traversal approach would be preferred as it would be both simpler and should be more efficient. That leaves the third approach, which is effectively an extreme case of the partitioning approach - and is what the code already does - which is to perform a separate traversal per type and aggregate the results. This is slower, but is simple and is the least likely approach to stress the graph db.

This issue introduce a QueryPlan to the graph repository, which analyses the query parameters and recommends a query strategy - which is either 'iterated' (per type, slower) or 'delegated' (single traversal, faster). Wherever possible the QueryPlan will recommend a 'delegated' traversal. The QueryPlan saves the property maps it generates during its analysis so they are available for the traversal construction methods.

Where a caller specifies type filtering that is sufficiently tight that there are no horizontally duplicated properties in the scope of the query, performance is maximised. It is therefore advisable to constrain a search by using the most specific type filtering and most type-specific property names possible.

**Comment by grahamwallis** [comment]
Fixed by #4684

**Comment by porunov** [comment]
The issue https://github.com/JanusGraph/janusgraph/issues/2231 was fixed in JanusGraph and will be shipped soon with the new release 0.6.0.
