### ISSUE TITLE
How to interpret the type limiters on graph queries (e.g. getEntityNeighborhood)?

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#4688]
How should we interpret / implement the type definition limiters on graph queries like `getEntityNeighborhood`, and in relation to the provided level?

As an example:

- `entityTypeGUIDs` is documented as "list of entity types to include in the query results."  Does this mean we traverse everything, but only add results of the type defined in this parameter?  Or not even traverse to any related entity unless it is one of these types (or a subtype thereof)?

Using some actual instances as examples:

- Imagine we have an `Endpoint` instance, and send that instance's guid as the starting point for the `getEntityNeighborhood` method.
- We specify that we want to limit the entity types to RelationalColumns (by providing its typedef guid as the only String in `entityTypeGUIDs`)
- Do we return no subgraph, because there is no direct relationship between RelationalColumn and Endpoint?
- Or do we traverse all subgraphs, but discard all results _except_ for RelationalColumn entities?

**Comment by grahamwallis** [comment]
Rightly or wrongly, this is what the graph repo does. This is from a comment from the GrapHOMRSMetadataStore class getSubGraph method, which underpins getEntityNeighborhood().

        /* The essence of the traversal is as follows, where V(rootVertex) is the vertex relating to the rootEntity,
         * specified by the entityGUID parameter.
         * The traversal repeats a sub-traversal that emits each traversed relationship and destination entity. The
         * traversal does not emit the root vertex - since the root entity is retrieved and added to the InstanceGraph
         * prior to commencement of the traversal. The traversal follows all relationships (subject to filtering conditions)
         * and visit all connected entities (subject to filtering conditions). The method returns an InstanceGraph,
         * which contains a list of Relationship objects and a list of EntityDetail objects. When the traversal reaches
         * an EntityProxy it will continue to traverse, despite not being able to include th proxy in the InstanceGraph.
         * Any proxy entities will be contained in the Relationship through which they are reached, whereas EntityDetail
         * objects (whether arising from a locally hosted entity or a reference copy of a remotely hosted entity) will be
         * include in the InstanceGraph.
         * After return of the InstanceGraph, the caller could retrieve a full EntityDetail of an entity that locally is
         * only a proxy, by issuing an enterprise level query using the GUID of the proxy.
         *
         * The following is pseudo-code:
         *
         * g.V(rootVertex).repeat(
         *     bothE("Relationship").has({relationship-status-filter}).has({relationship-type-filter}).as("r").
         *     otherV().has({entity-status-filter}).has({entity-type-filter}).as("e").
         *         where(out("Classifier").has({classification-filter})).
         *     simplePath()).
         * times(2).emit().select("r","e")
         *
         * THe various filters are optional and are implemented using has(<property>,within(<filter-collection>))
         */

**Comment by cmgrote** [comment]
Agreed on 18/02 that we should take the first approach: only traverse those types that are listed in the `...TypeGUIDs` parameters (which we believe is what the graph repository has currently implemented?)

**Comment by grahamwallis** [comment]
@cmgrote - Just to confirm - that is what the graph repo currently does. (Doesn't mean it's 'correct' but it was the way I interpreted the specification).
