### ISSUE TITLE
gaiandb url as property in pom.xml

### ISSUE THREAD

**Issue by bogdan-sava** [odpi/egeria#469]
As in some environments there is no internet connection and build fails as cannot access github for download it is useful to have such urls as property to be able to override them.

**Comment by mandy-chessell** [comment]
Is this fixed?

**Comment by planetf1** [comment]
I'm not aware of any reports of issues in this area recently - @bogdan-sava if this is still a problem re-open and I will queue to address

**Comment by planetf1** [comment]
Reopened after discussion in 1843.. cc: @cong78 @mstrelchuk 

We download many artifacts during the build
 - maven dependencies
 - 'node'/npm especially for UI
 - polymer/web components
in addition to gaian, so can the same approach be taken with caching locally?

I note that recently https://github.com/odpi/egeria/pull/1910 added parms for the node/npm download, so would the same approach work for gaian? Then in your environment you could cache on artifactory and set the build properties externally (just as happens in azure pipelines for environment specific settings)

Also related are a variety of issues considering removing gaian/ranger from the main repo such as #958, and moving into a specific repo - but again that is longer term, and I think your need is shorter term?

**Comment by planetf1** [comment]
The top level pom now has a new property 'gaiandb.url' which can be set to the location of the GAIAN distro .
If this isn't sufficient please can you reopen @bogdan-sava
