### ISSUE TITLE
 home repository does not support soft-delete error issued , when repository supports soft-delete

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#4693]
Getting this error during CategoryFVT, running against 1 in-memory repo (no other servers in cohort). 
during method deleteCategory because its home repository 7c59b8a9-8a33-4fb5-bd82-14f202a2e2a8 does not support soft-delete

**Comment by mandy-chessell** [comment]
The SA OMAS is calling the wrong method in the repository handler
