### ISSUE TITLE
What is introducing heap sizings into Egeria container?

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#4696]
I've noticed that when running the Egeria container as part of a Helm chart, something seems to inject some JVM heap limits:

`-Xms1024m -Xmx4096m`

Any idea what it is that is injecting these?  I can't seem to find anything obvious in any of the chart YAMLs or in the container definition itself.

(When running some larger CTS tests, towards the very end of them -- actually after the tests have all completed -- I'm ending up with a `Terminating due to java.lang.OutOfMemoryError: Java heap space` that triggers a pod restart, and therefore loses all of my results...)

**Comment by cmgrote** [comment]
Figured it out, this is coming from the base image of our containers: ubi8/openjdk11 defaults its memory allocations to half of the resource limit of the container, and the initial heap size allocation as a quarter of that maximum size.  Hence just changing the resource limits of the container from 8GB to 16GB will automatically increase these to `-Xms2048m -Xmx8192m`.

The docs suggest that these can (and actually _should_) be further tweaked to the specific needs of an application, but did not seem to provide which args would be used to do so.  Attempting to completely override the `JAVA_OPTS`, for example, simply appends them into the stream rather than replacing any which the base image is setting up itself already.

May warrant some deeper investigation to suggest which parameters may be worth overriding, and how to actually do so.

**Comment by planetf1** [comment]
The values seem a sensible default, though I am aware of the cts issues where we may be getting close.
Yes we can change specific values in the UBI8 image, or (and additionally in any case) point users to the docs for the underlaying image, whilst making sure there is a mechanism to override completely where needed.

You should be able to use JAVA_OPTS to replace the values, JAVA_OPTS_APPEND to extend them. I believe the ubi8 image has some logic to strip certain settings even in the JAVA_OPTS case. We only use JAVA_OPTS_APPEND currently to update the metaspace size.

A general point too in terms of mem usage etc... The CTS case seems quite specific, I guess we don't yet have enough experience with other workloads.
