### ISSUE TITLE
Merges are failing in Azure pipelines

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#4714]
The merge deployment has not succeeded today on the Azure pipelines, with the following error:

```
rm: cannot remove './plexus-classworlds.license': No such file or directory
##[error]Bash exited with code '1'.
```

It appears there is a step to remove a specific file from the `/boot` directory, which does not exist, and is therefore failing the entire deployment script.  (As a result, we're not getting updated snapshot jars in Artifactory, which means dependent repositories like the connectors cannot see any merged updates in Egeria core during their own build processes.)

**Comment by planetf1** [comment]
Thanks for sorting. That was a workaround for an issue with the file originally. I guess they cleaned up.
