### ISSUE TITLE
LatestChange and ChangeAction classifications on processes have null fields when they should have values

### ISSUE THREAD

**Issue by alexandra-bucur** [odpi/egeria#4717]
While creating/updating the processes in Data Engine, I discovered that some classifications have null fields. LatestChange classification has Change Target and Change Action with null values and also AssetOwnership classification has Owner Type field with null value.

I attached some screen shots of a debug session in getOwnerProperties() from AssetHandler and updateBeanInRepository from OpenMetadataAPIGenericHandle.

<img width="1131" alt="Owner Type" src="https://user-images.githubusercontent.com/71650973/108482231-e3ad0400-72a1-11eb-8dd6-f15655d1465d.png">
<img width="1182" alt="Change Action and Target" src="https://user-images.githubusercontent.com/71650973/108482245-e7408b00-72a1-11eb-8f66-c9a120d855d6.png">

**Comment by mandy-chessell** [comment]
@alexandra-bucur is this something that you are working on or is it open for anyone to fix?

**Comment by alexandra-bucur** [comment]
@mandy-chessell I just saw it while checking process creation and update on DE, but I am not working on it. It can be taken by anyone :)
