### ISSUE TITLE
Change OMAG Server Platform Origin String

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#4726]
Today the REST API endpoints for retrieving the server's origin return the string:

```
ODPi Egeria OMAG Server Platform (version xxx)
```
I am planning on changing it to
```
Egeria OMAG Server Platform (version xxx)
```
This has impact on the tutorials and related docs.   Are there scripts in the containers that test this string?

**Comment by planetf1** [comment]
Those two strings look identical to me.
Should we change ODPi to LF AI & Data?

I'm not aware any of the scripts parse the output currently.
