### ISSUE TITLE
Missing definitions for curation notebook (containers)

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#4743]
egeria-server-config:

Step 20 fails with:
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-20-e1ca9924963d> in <module>
     57                                       {
     58                                            "class" : "Endpoint",
---> 59                                            "address" : folderConnectorFolder
     60                                       }
     61                                  }

NameError: name 'folderConnectorFolder' is not defined
```

This variable does not appear to be defined in the notebooks.

Adding something like `folderConnectorFolder='./data/files'` allowed this to continue

However with this done, step 7 in the curation notebook fails with:
`
getGovernanceEngineStatuses(governDL01Name, governDL01PlatformName, governDL01PlatformURL, petersUserId)
`
returning
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-7-f354e67e5414> in <module>
----> 1 getGovernanceEngineStatuses(governDL01Name, governDL01PlatformName, governDL01PlatformURL, petersUserId)

NameError: name 'getGovernanceEngineStatuses' is not defined

```
I don't see any definition of that function in master so I suspect there was a file missed from the checkin?

**Comment by mandy-chessell** [comment]
@planetf1 the notebook is not complete - I have added another PR to move the "Stop do not use" back up to the top of the notebook.

**Comment by planetf1** [comment]
I noted the issues occurred in the config notebook which is used for all our scenarios. The new notebook was a subsequent problem 

We need a fix in config before branching?

**Comment by mandy-chessell** [comment]
OK - let me look at the config notebook

**Comment by mandy-chessell** [comment]
I am puzzled because this value is defined on the the line above.

**Comment by mandy-chessell** [comment]
Found it - it should be `dataLakeConnectorFolder` in the first use. 
The `folderConnectorName` is defined just below.

**Comment by mandy-chessell** [comment]
Just run the building an asset catalog with the reconfigured servers and it ran ok

**Comment by mandy-chessell** [comment]
Looking at `getGovernanceEngineStatuses` - this method is in environment-check and has been around a long time.  I can not get it to fail so not sure why this is a problem.  This function call is also working in the Improving DataQuality Lab too.

**Comment by mandy-chessell** [comment]
Making progress - I had renamed `getGovernanceEngineStatuses` to `printGovernanceEngineStatuses`.  This is what these notebooks should have been calling.  However the old name must be cached somewhere because the different notebooks that use it are working correctly on my machine.

**Comment by planetf1** [comment]
To ensure you avoid caching you can restart the kernel in Jupiter which should clean out the definitions. Otherwise they stay around
