### ISSUE TITLE
Is the HttpHelper class's condition check inverted?

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#4745]
Currently the HttpHelper class's method to check whether to enforce strict SSL reads as follows:

```
if ("true".equalsIgnoreCase(System.getProperty("strict.ssl")))
{
    noStrictSSL();
}
```

By my reading (and testing), setting `-Dstrict.ssl=true` disables the SSL verification, while using `-Dstrict.ssl=false` enables verification.  Shouldn't it be the other way around?

**Comment by planetf1** [comment]
Good spot! This is only used in our client/samples. The clients will work with certs correctly passed, this was added as a
bypass. 

Indeed the correct setting is to compare with false !!

Feel free to fix or assign to me.

**Comment by planetf1** [comment]
I will do this fix now -- I am about to test the clients as part of the release so it's good timing

**Comment by planetf1** [comment]
I note that we used to have this call in OpenMetadataConformanceTestReport.java - but the recent cts changes have removed this.

Does it need to be readded?
Did you check the client with cert/keystore specs (a bit cumbersome but secure and should work -- though work in progress in this area to correct our certs which are currently wrong)?
Or with a ssl bypass to connect to the server via REST?
