### ISSUE TITLE
Repositories are incrementing entity version when classification changes

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#4834]
Both the in-memory and the grpah repository are incrementing the version of the entity when classify/updateClassification/declassify are called.   Given that classifications can be added independently of the entity (effectively added in a server that is not the master of the entity), it would seem that the version would be inconsistent depending on which server was used to make the changes to the classification.

The CTS does not seem to inspect the entity version when the claasifications are added/updated/deleted.

**Comment by grahamwallis** [comment]
Good spot. Looks like we just need to drop the calls to the repository helpers incrementVersion method.

As you say, the CTS should probably be augmented too. (If someone new to the CTS adds this, there are examples of version verification in the lifecycle tests that update entities, for example.)
