### ISSUE TITLE
Release 2.7 -queryKnownServers undefined early in Understanding Platform Services lab

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#4842]
Running Exercise 2 / step 13 results in error:
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-13-95717f7861cd> in <module>
----> 1 queryKnownServers(platformName, platformURLroot)
      2 queryActiveServers(platformName, platformURLroot)

NameError: name 'queryKnownServers' is not defined
```

This happens the FIRST time through with a fresh kernel, since this function IS defined in the following step, where we run the common/environment-check.ipynb

Much of the time the user is likely to have run the configuration notebook in the same session, but I think in the other notebooks they stand by themselves and can be run cleanly with a fresh kernel, so this is an outlier.

**Comment by planetf1** [comment]
@mandy-chessell I'm not sure how you'd like to fix this - I don't think it's urgent for 2.7, but we can include if you like. I'll add something to the release notes otherwise.

**Comment by planetf1** [comment]
Moving to 2.8

**Comment by mandy-chessell** [comment]
Fixed in master
