### ISSUE TITLE
Not able to create Schema with Attributes

### ISSUE THREAD

**Issue by buchan123** [odpi/egeria#4886]
Hello,
I have gone through Egeria Dojo training and Jupyter Labs.

I could run Labs end to end and created simple assets of CSVFile type.

I tried to create different types of assets (e.g. Database) it is created successfully.
Next part is I attached SchemaType (RelationalDBShemaType) and it is attached as well.

 
Point i am stuck at is to attach attribute to Schema, it fails with below details :

I need community help for some samples where an Asset is created with more details (not just CSVFile) like attaching Schema with Attributes, attaching Glossary Terms etc.

Details of what i Tried So far :
OMAG-REPOSITORY-HANDLER-500-001 An unexpected error org.odpi.openmetadata.repositoryservices.ffdc.exception.InvalidParameterException was returned to createRelationship by the metadata server during addSchemaAttribute request for open metadata access service Asset Owner OMAS on server myMetaDataServer; message was OMRS-REPOSITORY-400-047 A addRelationship request has been made to repository myMetaDataServer for a relationship that has one or more ends of the wrong or invalid type.  Relationship type is RelationshipDef{name='SchemaAttributeType', description='The schema type for an attribute.', endDef1=RelationshipEndDef{attributeName='usedInSchemas', entityType='TypeDefLink{guid='1a5e159b-913a-43b1-95fe-04433b25fca9', name='SchemaAttribute', status=TypeDefStatus{ordinal=1, name='ActiveTypeDef', description='TypeDef available and in use.  This is the default value equivalent to null'}, replacedByTypeGUID='null', replacedByTypeName='null'}', attributeDescription='Occurrences of this schema type in other schemas.', attributeCardinality=RelationshipEndCardinality{ordinal=2, name='Any Number', description='0..* or * for any number of instances'}}, endDef2=RelationshipEndDef{attributeName='type', entityType='TypeDefLink{guid='5bd4a3e7-d22d-4a3d-a115-066ee8e0754f', name='SchemaType', status=TypeDefStatus{ordinal=1, name='ActiveTypeDef', description='TypeDef available and in use.  This is the default value equivalent to null'}, replacedByTypeGUID='null', replacedByTypeName='null'}', attributeDescription='The structure of this attribute.', attributeCardinality=RelationshipEndCardinality{ordinal=1, name='At Most One', description='0..1 for zero or one instances. 0..1.'}}, superType=null, descriptionGUID='null', origin='bce3b0a0-662a-4f87-b8dc-844078a11a6e', createdBy='ODPi Egeria', updatedBy='null', createTime=Wed Jan 01 13:42:11 GMT 2020, updateTime=null, options=null, externalStandardMappings=null, validInstanceStatusList=[InstanceStatus{ordinal=15, name='Active', description='The instance is approved and in use.'}, InstanceStatus{ordinal=99, name='Deleted', description='The instance has been deleted and is no longer available.'}], initialStatus=InstanceStatus{ordinal=15, name='Active', description='The instance is approved and in use.'}, propertiesDefinition=null, category=TypeDefCategory{typeCode=8, typeName='RelationshipDef', typeDescription='A link between two entities.'}, propagationRule=ClassificationPropagationRule{ordinal=0, name='NONE', description='No classification propagation'}, version=1, versionName='1.0', GUID='2d955049-e59b-45dd-8e62-cde1add59f9e'}; entity proxy for end 1 is EntityProxy{type=InstanceType{typeDefName='RelationalDBSchemaType', typeDefCategory=TypeDefCategory{typeCode=6, typeName='EntityDef', typeDescription='An object or concept of interest.'}
========================

I tried to read the code and figure it out but it seems I am missing on providing the correct request body. Here are more details :

1. To Create Asset : --> Works

typeName = Database
Post : {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-owner/users/{{user}}/assets/{{typeName}}
Body :
{  
    "class":"AssetProperties",
    "qualifiedName": "EIN124",
    "displayName": "Employee 1",
    "description": "To Create First Employee Asset",
     "extendedProperties": {
         "type":"Oracle",
         "deployedImplementationType":"On-Prem",
         "databaseVersion":"19c"
     }
}

2. Attach Schema to Asset  --> works

POST : {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-owner/users/{{user}}/assets/{{assetGUID}}/schemas
Body :
{
    "class" :"SchemaTypeProperties",
    "versionNumber" : "v1.0",
    "author":"Employee Dept",
    "usage" : "Employee DB Schema",
    "encodingStandard":"utf8",
    "namespace" : "Employee Repository",
    "displayName" : "Schema for Employee DB",
    "description" : "Employee Repository Employee Details ",
    "qualifiedName" :"E_EmployeeSchema",
    "typeName":"RelationalDBSchemaType"
}

3. Attach Schema Attribute --> Fails

POST : {{baseURL}}/servers/{{server}}/open-metadata/access-services/asset-owner/users/{{user}}/assets/{{assetGUID}}/schemas/{{schemaGUID}}/schema-attributes

Body :

    {
        "class":"SchemaAttributeProperties",
        "allowsDuplicateValues":"false",
        "orderedValues":"false",
        "sortOrder": "ASCENDING",
        "minimumLength": "5",
        "length":"20",
        "isNullable":"false",
        "displayName":"Employee ID",
        "description":"Unique ID Assigned to each Employee",
        "qualifiedName":"EMP_DTLS",
        "typeName":"RelationalTable",
         "additionalProperties": {    
         "encodingStandard":"base64",
         "dataType":"string",
         "type":"RelationalDBSchemaType"
         
                }
      ,

        "attributeType": {
            "class":"SchemaTypeProperties",
            "usage" : "Table in DB Schema",
            "displayName":"Employee Table",            
            "qualifiedName":"EMP_DTLS",
            "typeName":"RelationalTableType",
             "additionalProperties": {    
         
         "usedInSchemas":"1"
                }
               
        }

    }

**Comment by mandy-chessell** [comment]
Thank you for a detailed write up - can you confirm which version you are using - is it one of our releasese or master?

**Comment by mandy-chessell** [comment]
I have managed to recreate this and I am testing the fix

**Comment by mandy-chessell** [comment]
@buchan123 The fix is merged into master if you would like to retry ...

**Comment by buchan123** [comment]
@mandy-chessell it's working thanks!
