### ISSUE TITLE
Unable to connect two assets

### ISSUE THREAD

**Issue by Munira-Fatima** [odpi/egeria#4894]
Hello,

I want to draw your attention towards the problem I am facing while connecting associating two assets.

Using Version:- egeria-released-2.6

I have gone through basics of Egeria, like 
       -  I have gone through Egeria Dojo and Jupyter Labs.
       -  I am able to create simple CSV asset as given in labs.
       -  For practical use case I am creating two different assets of type Database for  Employee Database and Department Database.

Logically there is relationship between Employee DB and Department DB.
I am trying to add some connection/relationship between above two assets.

While searching I could figure out how to find relationship between two asset using below API.

GetMapping as below.
Base URL :
@RequestMapping("/servers/{serverName}/open-metadata/access-services/asset-catalog/users/{userId}")
End Point :
@GetMapping(path = "/linking-assets/from/{assetGUID}/to/{endAssetGUID}"

I am exploring as how to create the linking between two assets. 
I tried to explorer in code for asset-owner, asset-manager, asset-catalog, asset-lineage and asset-consumer, but unable to find the endpoint to connect two assets.

I have few doubts 

1. Is it possible to attach two assets, if yes, can you please help with some sample or REST end points or article which I can check for it. 

2. Is it logical to attach two assets ? if not , its would-be real-world scenario where we want to have relationship between Asset, so can you please guide on it.

**Comment by mandy-chessell** [comment]
Hello @Munira-Fatima 
There are many possible choices on the types of relationships that could be set up between two assets - or between elements that enrich the definition of the asset such as its tables/columns.   Each reflects a different meaning.
Could you give me more information on your use case?

**Comment by Munira-Fatima** [comment]
Hello @mandy-chessell 
Question : we want to associate Emp Dtls (Relational Table) with Employee Database Asset
![Egeria_asset_relation_ss](https://user-images.githubusercontent.com/80409447/110760125-60654980-8274-11eb-969d-c0a30c2cea3d.png)

**Comment by mandy-chessell** [comment]
Thanks, I understand :)  The picture below shows the open metadata types involved in modelling a database.  The coloured blocks show the major parts of the database structure and the names on the side are the open metadata types for the entities.

![image](https://user-images.githubusercontent.com/12354195/110791723-75d57600-826a-11eb-986d-d1c56d0a03b6.png)

A relational table is represented as a RelationalTable (inherits from SchemaAttribute) and a RelationalTableType (inherits from SchemaType)  It is linked to a DeployedDatabaseSchema asset via a RelationalDBSchemaType.

This picture shows the relationship types:

![image](https://user-images.githubusercontent.com/12354195/110797994-9fde6680-8271-11eb-8ab6-3252dba6310e.png)

There is also a more abbreviated form that you can use:

![image](https://user-images.githubusercontent.com/12354195/110798171-ce5c4180-8271-11eb-818d-842d956e475c.png)


The Data Manager OMAS has a specialize API for creating databases - this is in the DatabaseManagerResource file.
It needs a DataManager definition found in DataManagerResource.

**Comment by Munira-Fatima** [comment]
Thank you @mandy-chessell ....

**Comment by mandy-chessell** [comment]
I am going to close this as it seems nothing more to do but it can easily be reopened in I have misunderstood
