### ISSUE TITLE
Use Case Implementation of Egeria

### ISSUE THREAD

**Issue by chandaksagar** [odpi/egeria#4898]
Hello Team,
We started exploring Egeria project. I have gone in bit of details of Egeria like
  1. Egeria Dojo
  2. Egeria Jupyter Labs
  3. Exploring different access services
  3. Creating different type of Assets like SoftwareServer, Adding comments , adding Schema etc.

Next thing is we are trying to map our use case to Egeria. 
Below is high level similar scenario we are trying to map to Egeria
Consider We are Financial Company 'A-FINTECH' (hypothetical) which provides financial services for Clients who want to invest money.
A-FINTECH company have multiple Agents (Employee) who can serve multiple clients at same time.

There are multiple departments in A-FINTECH company like Equity Management, Hedge Fund Management, Commission handling etc.

Every Department have multiple Agents working for it.

Single client can avail services from different departments (many to many relationship between client and Agent)

We can think to  create different department in A-FINTECH company as Databse Asset for each department.

We wanted to create Client and Agent in Egeria. We tried to find how we can map the Client and Agent (working in different department ) to existing assets types provided by Egeria.

As of now, logically we are not able to map the Client and Agent (basically Personas of different type ) in Egeria in logical way.
We also want to add more to Assets of type Client and Agent by adding relationship between them.

Our basic questions
1. Is it logical to put Personal profile like Client and Agent in Egeria is correct ? If there is sample use case where it is implemented for different Personas ?
2. If we can can implement personal profiles in Egeria, how to map it available open metadata asset types.
3. Can we please connect with you (admins/maintainers) directly, in order to explain our use case for more exploration of Egeria for our use case implementation and get your guidance ?
Thanks

**Comment by mandy-chessell** [comment]
Hello @chandaksagar ,
Egeria does support the modelling of organizations/teams and people with their roles and responsibilities.  This is describe in the Area 1 model and Area 4 model.
These are the links:
* https://egeria.odpi.org/open-metadata-publication/website/open-metadata-types/0112-People.html - shows the model for a person
* https://egeria.odpi.org/open-metadata-publication/website/open-metadata-types/0115-Teams.html - shows the model for a team (department)
* https://egeria.odpi.org/open-metadata-publication/website/open-metadata-types/0440-Organizational-Controls.html - shows model for business capability 

Egeria's main focus is to document the people, processes and technologies used to run an organization.  This does seem in line with your use case.  However, it would depend on the types of queries and processing that you need to build around the repository.

**Comment by mandy-chessell** [comment]
Is there any more help I can give you?

**Comment by planetf1** [comment]
@chandaksagar I'm going to close now, but as per request above, if you need more help do join our slack or raise any issues on github
