### ISSUE TITLE
Enabled easier searching of egeria documentation

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#4899]
See #4262 for original reference

_A final suggestion is to integrate some search functionality in your site (and possibly in your project by bundling a tool like elasticsearch) and a more hierarchical menu structure especially in anything that deals with instructions/installation and configuration steps._

We do have a hierarchical structure - though opinions will always vary on the right hierarchy!

However the search comment is one I've heard before - and felt lacking myself. One approach is to search directly in github and look for '.md' files, but that's quite a developer-oriented avenue.

Google can be useful, but it's far from perfect. For example to configure TLS for egeria

egeria configure tls
site:egeria.odpi.org configure transport level security -> returns no docs
egeria configure certificates -> no precise hits

I propose we look at what we can do to improve the indexing of the site -- this may include additional metadata in our docs, or guidance on using public search engines, or deploying our own website/index.

**Comment by cmgrote** [comment]
Looking into this as part of reworking the documentation into the new rendering -- hope to have something initial to show in early August to agree how to proceed.

**Comment by planetf1** [comment]
This can be closed - the new site has search
