### ISSUE TITLE
Build failure error on local machine.

### ISSUE THREAD

**Issue by pan-vaghole97** [odpi/egeria#4900]
Hello,

I'm exploring Egeria project. I have gone through Egeria Dojo tutorial.
I was working with docker images of Egeria & it working fine. Now I want explore more & I want build Egeria in local. When I'm trying to build locally its fails.
Below are steps followed :
1. I have cloned a Egeria source repository from GitHub using "**git clone https://github.com/odpi/egeria.git**"
2. In egeria directory tried to build project with Apache Maven 3.6.0 on local machine using command "**mvn clean install**" but build **fails for module Asset Manager OMAS FVT** with the error **"Error while storing the mojo status"**. please refer screenshot for error details .
3. I have tried to build with egeria-2.6 & egeria-2.7 but same error. 

![egeria](https://user-images.githubusercontent.com/15229219/110747896-001adb80-8265-11eb-8988-6b1fad2dc45d.png)

**Comment by planetf1** [comment]
Hi,
 I've not seen this when building egeria, but I see you have a 'Too many open files' error.
 I'm not sure of the current defaults in your environment, but you could try `ulimit -a` to see
 A tool like 'lsof' can help you see how many file handles are currently open.
 You can increase the values most likely in `/etc/security/limits.conf` ie the hard & soft entries for 'nofile'

It may be you are close to the limit, and the build is pushing things over the edge

If you need more detailed help, let me know more information about your environment, OS level etc and I'll try to dig out exact changes for you

**Comment by pan-vaghole97** [comment]
Hi @planetf1 
Thank you for the reply.  I'm using Ubuntu 18.04. I have added below entries in `/etc/security/limits.conf` & tried build after rebooting the system but still same issue. Can you please help to find out the exact changes for me.
```
* soft nofile 99999
* hard nofile 99999
```

Below is the result of `ulimit -a` command :

![Screenshot from 2021-03-13 00-23-47](https://user-images.githubusercontent.com/15229219/110987942-df05d800-8395-11eb-91a9-0ecb4d6cdc93.png)

**Comment by planetf1** [comment]
Ok. I'll get a clean ubuntu system and check for you

**Comment by planetf1** [comment]
I tried the change and saw the same as you - no difference in the shell by default.

It seems as if the shell is defaulting to 1024 - though I've not found the invocation of 'ulimit' that might do this, with a default max of 4096 (which is probably enough).

You could leave the change you already have, but in your ~/.bashrc use
```
ulimit -n 4096
```
I don't have a desktop ubuntu env to try right now --- there is more configuration which can affect these settings in /etc/pam.d, but I hope the above is good enough to get you working

**Comment by planetf1** [comment]
I tested the same initial change on Ubuntu 20.10 and it worked fine as initially described - there was no need to add the ulimit command

**Comment by planetf1** [comment]
I hope this helps. I shall close this for now but please reopen if it hasn't helped or you need further advice

**Comment by pan-vaghole97** [comment]
@planetf1 Thank You. 

I have did changes as you have mentioned initially & now 'Too many open files' error has been resolved. ([Detailed Steps.](https://askubuntu.com/questions/1102512/set-ulimit-for-non-root-user))

**Comment by pan-vaghole97** [comment]
Hi @planetf1 
Thank you for helping to resolve the "Too many open files' error. Now I'm able to build Egeria & "`mvn clean install`" command show "BUILD SUCCESS" message but the target folder contains an empty jar. I want to debug/run an Egeria project in IntelliJ to explore more about Egeria & also want to understand the code flow/structure to contribute. Local debugging will be helpful to me to verify the local changes. Could you please help me to debug the Egeria in intelliJ.

![Screenshot from 2021-03-22 15-30-31](https://user-images.githubusercontent.com/15229219/111974530-7e109980-8b25-11eb-865c-5d8173c2c368.png)
![Screenshot from 2021-03-22 15-07-40](https://user-images.githubusercontent.com/15229219/111974544-81a42080-8b25-11eb-9f00-e122c700f67f.png)
