### ISSUE TITLE
Define suggested per-type algorithms for constructing qualifiedNames

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#4931]
Discussed on 22/03/2021 call the desire to define a suggested algorithm for constructing `qualifiedName` in a consistent way, to help with efforts like duplicate detection.

We agreed that such an algorithm will likely need to be defined on a per-type basis, as depending on the type of information the specific components that need to be combined into the `qualifiedName` will inevitably be different.

While we cannot enforce that every technology integrating to Egeria applies the algorithms (hence "suggested" rather than a "standard"), we think it will nonetheless be helpful if there is such a suggestion for implementing technologies to follow where feasible.

Examples:

- `RelationalColumn`'s `qualifiedName` would be a combination of the `name` (technical) value of the `RelationalColumn` and the `qualifiedName` of its related `RelationalTable`
- `RelationalTable`'s qualifiedName would be a combination of the `name` field (technical) of the `RelationalTable` and the `qualifiedName` of its related `DeployedDBSchemaType`
- ... and so on up the chain
- Files would be a different combination (but a similarly recursive `name`-based approach for its containment hierarchy)
- Topics would be different again (but again, still similarly recursive `name`-based approach for its containment hierarchy)

**Comment by wbittles** [comment]
I'm not sure the examples are fine grained enough, it's not just the probability of duplicates in user defined data, such as the likes of  employee.Id, employee.name and account.id.
There is also the use of database structures by vendors to store operational metadata and this structure is replicated on a per instance basis. So if you had two postgres instances you would get qualified name clashes.
This is the scheme I'm using in the postgres connector for tables 

` table_catalog + "." + table_schema + "." + table_type.substring(0,4) + "." + table_name`

The table_type.substring just adds "BASE" of "VIEW" , which is useful when debugging query results, but will get removed at a later date.
