### ISSUE TITLE
Allow find methods to retrieve deleted instances if explicitly requested

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#4935]
The various find methods define the following parameter:

- `limitResultsByStatus` as "By default, instances in all statuses are returned.  However, it is possible to specify a list of statuses (eg ACTIVE) to restrict the results to.  Null means all status values."

Yet despite this, there are currently explicit checks to exclude any instances with a `DELETED` state in all of the following methods. Note that not only does this contradict the documented behavior of this property, but (even more problematic) this entirely blocks searching for deleted instances -- _even when `DELETED` is explicitly specified in the `limitResultsByStatus` list passed to the method_:

- [x] findRelationshipsByProperty (InMemory and Graph)
- [x] findEntitiesByProperty (InMemory and Graph)
- [x] findEntities (InMemory and Graph)
- [x] findEntitiesByClassification (InMemory and Graph)
- [x] findEntitiesByPropertyValue (InMemory and Graph)
- [x] findRelationships (InMemory and Graph)
- [x] findRelationshipsByPropertyValue (InMemory and Graph)
- [x] getRelationshipsForEntity (InMemory and Graph)

Given the implementation, it seems as if this may be the _expected_ behavior, even though it is not the _defined_ behavior.  I would suggest taking one of the following approaches to resolve:

1. Remove the explicit check for the `DELETED` status so that behavior of the methods matches the documented interface (that is, if `null` is provided for this parameter, then the search will retrieve both active and deleted (and any other status) results). This would have an impact on any existing users of these methods in that they would now need to explicitly request the statuses they are interested in finding (which is not as simple as `ACTIVE` as various types have things like `DRAFT` or other statuses as their default initial values).
2. Update the documented interface such that if the parameter is `null`, then we default the list of statuses to be included to be all statuses _except_ `DELETED`. (Still remove the explicit check for the `DELETED` status, so that if someone explicitly includes `DELETED` in the parameter they will have results of deleted instances.) This puts more of a burden on the find methods, but should have no impact on the existing users of the methods. This would mean the documentation for this parameter should now read: "By default, instances in all non-DELETED statuses are returned.  However, it is possible to specify a list of statuses (eg ACTIVE) to restrict the results to.  Null means all status values except DELETED."

I don't believe it is an option to leave the behavior as-is, since it currently entirely excludes the possibility to search for deleted instances.

**Comment by mandy-chessell** [comment]
We need to update the documentation - the design is that deleted status elements are not visible to the callers of the metadata collections.

**Comment by cmgrote** [comment]
I suspected as much -- so option (1), right?

Agree that we should not be explicitly excluding `DELETED` if a request explicitly asks for it?

**Comment by mandy-chessell** [comment]
I do like option 2 but it is a design change because it makes deleted elements visible to callers.   The current behaviour is a copy of Atlas's behaviour.  It does not make it right - and I think it is a bit clunky.   But we have to think carefully about whether we want to allow queries for deleted elements.

**Comment by mandy-chessell** [comment]
One use case that would argue in favour of option 2 is to allow a process to query deleted elements and the purge them.

**Comment by cmgrote** [comment]
Yes, it is precisely that use case that I think is important.

Without the ability to somehow expose deleted things through the metadata collection interface, they otherwise are basically never again retrievable (so could never be subsequently purged in some later operation, without whatever soft-deleted them in the first place managing its own state of what is soft-deleted to later recall it for purging -- but then that state is silo'd in whatever thing did the soft-delete, rather than accessible by the cohort).

I could understand a debate about whether such exposure of deleted instances is made via some entirely new interface rather than the find methods (though I think that could be clunky), but having no way to retrieve them at all is IMO a problem.

**Comment by cmgrote** [comment]
Per this note, even Atlas allows the deleted information to be retrieved in certain scenarios, so I'm not sure that we've actually even copied Atlas's behavior at the moment: https://docs.cloudera.com/runtime/7.2.7/atlas-reference/topics/atlas-reference-purging-deleted-entities.html

"... deleted entities show up in search results when the checkbox to Show historical entities is checked. Deleted entities appear in lineage graph dimmed-out."

**Comment by mandy-chessell** [comment]
We use the Memento classification to show elements in the lineage graph that represent elements that are physically deleted - this is different from a metadata element that has been deleted because it is no longer needed

**Comment by cmgrote** [comment]
Agreed 25/03 that we should implement option 2 -- will put up-front in 2.9-SNAPSHOT.
