### ISSUE TITLE
remove ibm-igc-repository-connector & tomcat from atlas/egeria patch/build

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#494]
The following needs to be fixed in both the atlas patch and/or dependent egeria components AND then in the docker build for atlas+egeria so it can be deployed as a demo.

Please raise additional issue if only part is done under this issue #

Excerpt from
https://github.com/odpi/egeria/pull/493

Yes! Indeed. 
What I found until now is that this new version brings to atlas spring-web and also spring-boot of Egeria and shouldn't. And that's because the **ibm-igc-repository-connector** is brought to atlas and shouldn't. 
And, why i**bm-igc-repository-connector** it depends on s**pring-boot-starter-web**, which get's dependency of **embbeded-tomcat**?

Solution:

First exclude  **ibm-igc-repository-connector** from atlas. In **open-metadata** module pom.xml :
There is in two dependencies!

First one:

        <dependency>
            <groupId>org.odpi.egeria</groupId>
            <artifactId>repository-services-implementation</artifactId>
            <version>${egeria.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>log4j-over-slf4j</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.odpi.egeria</groupId>
                    <artifactId>ibm-igc-repository-connector</artifactId>
                </exclusion>
            </exclusions>
        </dependency> 

And second one:

        <dependency>
            <groupId>org.odpi.egeria</groupId>
            <artifactId>admin-services-server</artifactId>
            <version>${egeria.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>log4j-over-slf4j</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.odpi.egeria</groupId>
                    <artifactId>ibm-igc-repository-connector</artifactId>
                </exclusion>
            </exclusions>
        </dependency> 

Next step is to exclude **admin-services-server** and **epository-services-implementation** from **atlas-webapp** as there is already dependency of open-metadata module.

_Originally posted by @bogdan-sava in https://github.com/odpi/egeria/pull/493#issuecomment-449748797_

**Comment by cmgrote** [comment]
The `spring-boot-starter-web` is dependency is most likely my fault -- copy/paste gone wrong (actually under `igc-rest-client-library`, on which `ibm-igc-repository-connector` depends).  I simply need to be able to use spring to call REST APIs, so I believe just need this dependency instead:

```xml
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
            <version>${spring-web.version}</version>
        </dependency>
```

?

**Comment by cmgrote** [comment]
I think this one has been resolved for some time, so proactively closing -- please re-open if not?

**Comment by planetf1** [comment]
agreed
