### ISSUE TITLE
understanding platform services notebook fails to query servers correctly

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#5023]
```
queryKnownServers(platformName, platformServicesURLRoot)
queryActiveServers(platformName, platformServicesURLRoot)
```
results in a response of:
```
Querying the known servers on platform: Data Lake Platform ...
GET https://lab-datalake:9443/open-metadata/platform-services/users/garygeeke/server-platform/open-metadata/platform-services/users/garygeeke/server-platform/servers
Response: 
{
    "timestamp": "2021-04-02T14:32:34.743+00:00",
    "status": 404,
    "error": "Not Found",
    "message": "",
    "path": "/open-metadata/platform-services/users/garygeeke/server-platform/open-metadata/platform-services/users/garygeeke/server-platform/servers"
}
 
 
Querying the active servers on platform: Data Lake Platform ...
GET https://lab-datalake:9443/open-metadata/platform-services/users/garygeeke/server-platform/open-metadata/platform-services/users/garygeeke/server-platform/servers/active
Response: 
{
    "timestamp": "2021-04-02T14:32:34.773+00:00",
    "status": 404,
    "error": "Not Found",
    "message": "",
    "path": "/open-metadata/platform-services/users/garygeeke/server-platform/open-metadata/platform-services/users/garygeeke/server-platform/servers/active"
}
```
This is despite the servers being active and the other notebooks having been used to, for example, query assets.

**Comment by planetf1** [comment]
This still fails.

Looking at the URL it shows as:
GET https://lab-datalake:9443/open-metadata/platform-services/users/garygeeke/server-platform/open-metadata/platform-services/users/garygeeke/server-platform/servers

This is incorrectly formed . In fact in cell 13 we have the long-form code:
```
print (" ")
print ("Querying the known servers on platform: " + platformName + " ...")
url = platformServicesURLRoot + '/servers'
print ("GET " + url)
response = requests.get(url)
prettyResponse = json.dumps(response.json(), indent=4)
print ("Response: ")
print (prettyResponse)
print (" ")

print (" ")
print ("Querying the active servers on platform: " + platformName + " ...")
url = platformServicesURLRoot + '/servers/active'
print ("GET " + url)
response = requests.get(url)
prettyResponse = json.dumps(response.json(), indent=4)
print ("Response: ")
print (prettyResponse)
print (" ")

```
which is correct

In fact most of the logic in this notebook creates the URL for the request specifically, rather than make of the common functions defined - it probably makes sense to switch to using these functions once tested/fixed accordingly

**Comment by planetf1** [comment]
This is still failing in 2.10 (appears to have been closed in error)

**Comment by planetf1** [comment]
Still failing in 3.0-SNAPSHOT

**Comment by tcnt** [comment]
I will take this issue as I just ran into the same problem.
Current notebook understanding-platform-services.ipynb calls 
queryKnownServers(platformName, platformServicesURLRoot)
queryActiveServers(platformName, platformServicesURLRoot)

The functions in common expects the url+portnumber which is in platformURLroot.
It will then internally generate platformServicesURLRoot.

I will rename platformURLroot to serverPlatformURL to align with the name used internally in the function.
And then call the function accordingly with serverPlatformURL in place of platformServicesURLRoot

**Comment by planetf1** [comment]
thanks @tcnt
