### ISSUE TITLE
Release 2.8 - updates to UI documentation

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#5024]
* UI notebook needs to refer to the new nginx container and guidance on using the right URL
* chart readmes need update similarly
* docker compose readme needs updating
* advice of this change needs adding to release notes

Adding as an issue to track for inclusion in the 2.8 branch

**Comment by davidradl** [comment]
@planetf1 Can I check that  this issue is not related to the react UI?

**Comment by planetf1** [comment]
Correct, this is about the polymer UI

**Comment by planetf1** [comment]
fixed
