### ISSUE TITLE
Deletion interface for DE OMAS

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#5050]
To enable deletions to be propagated, we need methods exposed through the Data Engine OMAS to send through deletes.

We may want to spend a bit more time thinking through what these should be / what inputs they should receive, but I would suggest as a starting point that we mirror the existing upsert methods:

- deleteProcesses
- deleteExternalDataEngine
- deleteSchemaType
- deletePortImplementation
- deletePortAlias
- removeProcessHierarchy
- removeLineageMappings
- removePortsFromProcess

(This came out of discussions on ensuring we can have deletes sent through from DataStage as part of future evolutions -- still details to be worked out on the DataStage side, but once it has detected and wants to send through a delete, it'll need some interface to call to action that delete 😁  cc: @mstrelchuk)

**Comment by lpalashevski** [comment]
Points discussed on the last community call:

 We identified two scenarios applicable for removal of process related metadat in the area of design lineage recorded by external tools via Data Engine:

(1) Hard-delete strategy. Process and related metadata associated is deleted by purging it from the metadata reposiotory; This means that lineage associated metadata is also removed.

(2) Soft-delete strategy. This means that process metadata will be not removed physically but classified as memento asset. (This is done by classifying process asset with memento classification). This way the lineage related information is preserved but the process is no longer "visible" as asset via OMAS-es.

The strategy can be configured in Open Lineage Proxy server and this setting will be delegated to DataEngine proxy.

Initially, we will start working on new Data Engine OMAS interface and implemet the logic for "hard-delete".

We need to further think and analyze deletion as process for different DataEngine use-cases especially in the area of operational lineage where things are more complex and need for soft-delete strategy is even more evident.

**Comment by lpalashevski** [comment]
This feature has been implement with the referenced PRs + additional enahncements are added in #5352.
