### ISSUE TITLE
NullPointerException thrown by GetEntityExecutor.issueRequestToRepository method

### ISSUE THREAD

**Issue by wbittles** [odpi/egeria#5059]
While the server is processing the following events 

Wed Apr 14 13:57:40 BST 2021 postgresTargetServer Event OMRS-AUDIT-8006 Processing incoming event of type ReclassifiedEntityEvent for instance b241747e-a694-44bb-a991-34319bab8741 from: OMRSEventOriginator{metadataCollectionId='4eb1cae4-7d13-4d78-aa6c-79fa72939037', serverName='postgresTargetServer', serverType='Open Metadata and Governance Server', organizationName='null'}

an occasional NullPointerException is thrown by  the following line of code 
if (metadataCollectionId.equals(retrievedEntity.getMetadataCollectionId()))
because the metadataCollectionID is null .

All that is output to the console is the following 

Wed Apr 14 14:07:18 BST 2021 postgresTargetServer Information OMRS-AUDIT-0135 Configuration for an existing remote member from server postgresTargetServer for cohort postgresCohort has changed and is being updated in the enterprise connector manager.  It has a metadata collection id of 4eb1cae4-7d13-4d78-aa6c-79fa72939037

There doesn't appear to be any ill effects of the exception and the server seems to be functioning properly.

**Comment by mandy-chessell** [comment]
I need all of the server messages from start up

**Comment by mandy-chessell** [comment]
Message OMRS-AUDIT-8006 is output in the event processing logic.

From talking to Billy, this line of code `if (metadataCollectionId.equals(retrievedEntity.getMetadataCollectionId()))` is in the enterprise connector logic that is called when an OMAS API request is made.  It is not involved in processing incoming events.

Message OMRS-AUDIT-0135 is output when a member of the cohort detects that the configuration of another cohort member has changed.  This occurs in the thread that is receiving registration events from the cohort and is not involved in the processing of an OMAS request.  Although the message shown above is incomplete, it does include enough to show that that metadata collection id was available.  It will reconfigure the enterprise connectors with the new connection information.

So the reported symptoms are coming out of

**Comment by mandy-chessell** [comment]
@wbittles this is ready to test

**Comment by wbittles** [comment]
all good ..
