### ISSUE TITLE
Simple Helm Chart for Kubernetes Documentation Unclear

### ISSUE THREAD

**Issue by aproeve** [odpi/egeria#5062]
Hi! I was working on getting the Helm Chart for Kubernetes deployment of Egeria working [here](https://github.com/odpi/egeria/tree/master/open-metadata-resources/open-metadata-deployment/charts/egeria-base) and it was unclear to me which part of the directory I should be running the commands shown on the page. However, after speaking with someone my issue was resolved quickly! 

I'd be happy to edit to document so future developers in a similar position know exactly where they should be issuing these commands!

**Comment by planetf1** [comment]
Thanks for the feedback @aproeve. Will keep a look out for the PR to review.

**Comment by planetf1** [comment]
The charts are now published to a helm repository, so there is no need to download any files!

These docs are temporarily at https://odpi.github.io/egeria-charts , but will move into the main egeria-docs repo soon 
```
helm repo add egeria https://odpi.github.io/egeria-charts
helm search repo egeria
helm install lab egeria/odpi-egeria-lab 
```
