### ISSUE TITLE
Cleanup old git branches

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#5098]
We have a number of branches that I think are unnecessary and confusion. They've been generated by a combination
of admin tasks directly against the main repo (some of the git tools do this - for example recently when I created issue templates), dependabot, and a few other pieces of work.

The list currently - excluding features and branches is:

$ git branch -r | grep upstream | egrep -v 'egeria-release|master'                            [17:52:07]
  **upstream/add-badges**
  **upstream/azure-pipelines**
  **upstream/dependabot/add-v2-config-file**
  upstream/dependabot/github_actions/actions/setup-java-v2
  **upstream/dependabot/maven/groovy.version-3.0.4**
  **upstream/dependabot/maven/janus.version-0.5.2**
  upstream/egeria-feature-openlineage
  **upstream/egeria-feature-testfeature**
  upstream/feature-relationship-supertypes
  upstream/initial-load
  **upstream/jmertic-patch-1**
  **upstream/jmertic-patch-2**
  upstream/lf-projects-header
  **upstream/planetf1-initial-issue-templates**
  **upstream/planetf1-stale**
  **upstream/remove-zuul-module**
  **upstream/revert-2220-git1942**
  **upstream/revert-3075-egeria-feature-openlineage**
  **upstream/revert-4922-remove-zuul-module**
  **upstream/revert-4924-revert-4922-remove-zuul-module**
  **upstream/update-dojo-link**
jonesn:egeria/ (initial-issue-template) $

I propose removing the branches marked **BOLD** above

For discussion in a community meeting

**Comment by mandy-chessell** [comment]
I agree

**Comment by planetf1** [comment]
These have now been cleaned up.
