### ISSUE TITLE
Outdated documentation - Running Egeria natively

### ISSUE THREAD

**Issue by aproeve** [odpi/egeria#5163]
Hi! I was working on getting Egeria to run natively and ran into an issue with the outdated ports given in the documentation [here](https://github.com/odpi/egeria/blob/master/open-metadata-resources/open-metadata-tutorials/lab-infrastructure-guide/running-natively.md). 

I'd be happy to fix this!

**Comment by planetf1** [comment]
Thanks for spotting - reassigning.
