### ISSUE TITLE
Still got "Whitelabel Error Page" when opening the UI server in the UI Asset Lab

### ISSUE THREAD

**Issue by TakumiHaruta** [odpi/egeria#5165]
I read #3892 and understood that this error happened because the UI server couldn't reach the static contents. Then, the new docker image of `egeria-ui` has already added to `uistatic` in the docker compose file.

https://github.com/odpi/egeria/blob/V2.9/open-metadata-resources/open-metadata-deployment/compose/tutorials/egeria-tutorial.yaml#L147

But I still got the same error when I execute `ui-asset-search.ipynb` and open https://localhost:18443/

```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri May 07 11:51:38 GMT 2021
There was an unexpected error (type=Not Found, status=404).
```

How can I fix this or are there any additional steps before getting in the UI Asset Lab?

## Environment and Procedure

- macOS Catalina 10.15.7
- Docker Desktop 3.3.1
- Egeria 2.9

1. Download the resources via https://github.com/odpi/egeria/releases/tag/V2.9
2. Execute `docker-compose -f ./egeria-tutorial.yaml up -d` at `egeria-2.9/open-metadata-resources/open-metadata-deployment/compose/tutorials`
3. Open the Jupyter Lab
4. Execute all codes in Configuring Egeria Servers Lab for the initial setup
5. Execute `%run common/environment-check.ipynb` and make sure all servers are configured and active like logs below
6. Execute all codes in UI Asset Search Lab
7. Open https://localhost:18443/ and get the error

```
%run ../common/environment-check.ipynb

Checking OMAG Server Platform availability...
    Core Platform is active
        Checking OMAG Server cocoMDS2
           ... cocoMDS2 is configured
           ... cocoMDS2 is active - ready to begin
        Checking OMAG Server cocoMDS3
           ... cocoMDS3 is configured
           ... cocoMDS3 is active - ready to begin
        Checking OMAG Server cocoMDS5
           ... cocoMDS5 is configured
           ... cocoMDS5 is active - ready to begin
        Checking OMAG Server cocoMDS6
           ... cocoMDS6 is configured
           ... cocoMDS6 is active - ready to begin
    Data Lake Platform is active
        Checking OMAG Server cocoMDS1
           ... cocoMDS1 is configured
           ... cocoMDS1 is active - ready to begin
        Checking OMAG Server cocoMDS4
           ... cocoMDS4 is configured
           ... cocoMDS4 is active - ready to begin
        Checking OMAG Server cocoView1
           ... cocoView1 is configured
           ... cocoView1 is active - ready to begin
    Dev Platform is active
        Checking OMAG Server cocoMDSx
           ... cocoMDSx is configured
           ... cocoMDSx is active - ready to begin
Done.
```

**Comment by planetf1** [comment]
Further, it's worth noting that in the k8s environment, accessing the UI or indeed any service is very depending on what port forwarding/ingress rules have been set up, and from within the notebook it's not possible to be sure any URL given is correct in terms of external accessibility.

**Comment by TakumiHaruta** [comment]
@planetf1 
Thank you for explaining in detail. I could enter the UI via https://localhost:10443, but it doesn't show any data.
(The lab of Egeria 2.4 could show the sample data.)

Some part of the lab haven't actually updated as you said. I'll try to find other ways for understanding the system.

**Comment by sarbull** [comment]
@TakumiHaruta please also check the odpi/egeria-ui project and check the README on how to start the User Interface. They are two separate projects now, API and UI.

**Comment by sarbull** [comment]
@TakumiHaruta @planetf1 the simplest way to start Egeria is to start the backend/API separately a given PORT and enable CORS from `application.properties` and then start the egeria-ui project with `npm run start --api-url=http://api:PORT` linking the UI to backend data or `npm run build --api-url=http://api:PORT` and serve it with nginx or any other static server
