### ISSUE TITLE
broken link in Subject area samples

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#5166]
If you look at https://github.com/odpi/egeria/tree/master/open-metadata-resources/open-metadata-samples/access-services-samples.  Then click on the subject area link - it navigates to a folder.

But if you go to https://egeria.odpi.org/open-metadata-resources/open-metadata-samples/access-services-samples/ and click on the link it gives 404.

I think this needs to be changed so that the link points to a readme.md file in the target folder.

I am looking to use this as a first issue for a particular person in an IBM open source initiative I have been communicating with, so have assigned to me for now so no-one will take it.

**Comment by davidradl** [comment]
This is likely to be one of the link error identified in https://github.com/odpi/egeria/issues/5160

**Comment by MRaybuck** [comment]
I think I found the problem. Please assign to me so I can resolve it.
