### ISSUE TITLE
Survey on globally distributed software engineering 

### ISSUE THREAD

**Issue by AsWali** [odpi/egeria#5168]
Hey there. 

We are doing a survey on globally distributed software engineering focused on open source projects. If you have some spare time we would really appreciate your response. The form takes about 10 minutes. Thanks in advance!
Survey can be found [here](https://forms.gle/N1TnifRuCYHrCY9JA)

**Comment by planetf1** [comment]
No reference or information about the data use or organisation so closing as spam
