### ISSUE TITLE
IGC repository proxy uses deprecated OMRS api

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#517]
Just a FYI @cmgrote I noticed when building -- use of a deprecated OMRS api

[INFO] --- maven-compiler-plugin:3.6.0:compile (compile) @ igc-repository-proxy ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 19 source files to /Users/jonesn/IdeaProjects/egeria/open-metadata-resources/open-metadata-demos/virtual-data-connector/igc-repository-proxy/target/classes
[WARNING] /Users/jonesn/IdeaProjects/egeria/open-metadata-resources/open-metadata-demos/virtual-data-connector/igc-repository-proxy/src/main/java/org/odpi/openmetadata/virtualdataconnector/igc/connectors/repositoryconnector/IGCOMRSMetadataCollection.java:[50,9] OMRSMetadataCollectionBase(java.lang.String) in org.odpi.openmetadata.repositoryservices.connectors.stores.metadatacollectionstore.OMRSMetadataCollectionBase has been deprecated
[INFO] /Users/jonesn/IdeaProjects/egeria/open-metadata-resources/open-metadata-demos/virtual-data-connector/igc-repository-proxy/src/main/java/org/odpi/openmetadata/virtualdataconnector/igc/connectors/repositoryconnector/IGCOMRSRepositoryConnector.java: Some input files use unchecked or unsafe operations.
[INFO] /Users/jonesn/IdeaProjects/egeria/open-metadata-resources/open-metadata-demos/virtual-data-connector/igc-repository-proxy/src/main/java/org/odpi/openmetadata/virtualdataconnector/igc/connectors/repositoryconnector/IGCOMRSRepositoryConnector.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ igc-repository-proxy ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.6.0:compile (default-compile) @ igc-repository-proxy ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 19 source files to /Users/jonesn/IdeaProjects/egeria/open-metadata-resources/open-metadata-demos/virtual-data-connector/igc-repository-proxy/target/classes
[INFO] /Users/jonesn/IdeaProjects/egeria/open-metadata-resources/open-metadata-demos/virtual-data-connector/igc-repository-proxy/src/main/java/org/odpi/openmetadata/virtualdataconnector/igc/connectors/repositoryconnector/IGCOMRSMetadataCollection.java: /Users/jonesn/IdeaProjects/egeria/open-metadata-resources/open-metadata-demos/virtual-data-connector/igc-repository-proxy/src/main/java/org/odpi/openmetadata/virtualdataconnector/igc/connectors/repositoryconnector/IGCOMRSMetadataCollection.java uses or overrides a deprecated API.
[INFO] /Users/jonesn/IdeaProjects/egeria/open-metadata-resources/open-metadata-demos/virtual-data-connector/igc-repository-proxy/src/main/java/org/odpi/openmetadata/virtualdataconnector/igc/connectors/repositoryconnector/IGCOMRSMetadataCollection.java: Recompile with -Xlint:deprecation for details.
[INFO] /Users/jonesn/IdeaProjects/egeria/open-metadata-resources/open-metadata-demos/virtual-data-connector/igc-repository-proxy/src/main/java/org/odpi/openmetadata/virtualdataconnector/igc/connectors/repositoryconnector/IGCOMRSRepositoryConnector.java: Some input files use unchecked or unsafe operations.
[INFO] /Users/jonesn/IdeaProjects/egeria/open-metadata-resources/open-metadata-demos/virtual-data-connector/igc-repository-proxy/src/main/java/org/odpi/openmetadata/virtualdataconnector/igc/connectors/repositoryconnector/IGCOMRSRepositoryConnector.java: Recompile with -Xlint:unchecked for details.
[INFO]

**Comment by cmgrote** [comment]
Thanks -- that's the "old" proxy, which I believe should be (eventually) replaced by `open-metadata-implementation/adapters/open-connectors/repository-services-connectors/open-metadata-collection-store-connectors/ibm-igc-repository-connector`

**Comment by planetf1** [comment]
Ah yes the whole component is deprecated.

We could use this issue to do the removal? Can we do it before we do the next release @mandy-chessell ? Or at least flag it up as deprecated, add notes in readme?

**Comment by mandy-chessell** [comment]
I would prefer it is removved before we cut the R1.  Check that Maryna is happy to remove it

**Comment by mstrelchuk** [comment]
Go ahead with the removal of the old igc proxy before the release.

**Comment by cmgrote** [comment]
Was this wrapped for the R1 cut / can we close the issue?

**Comment by cmgrote** [comment]
Seems there were a number of things we still needed to migrate over from the "old" VDC demo...  Would it be worthwhile listing those explicitly in separate issues and grouping them all under a milestone (probably including this one as well)?

**Comment by planetf1** [comment]
If this issue is only for code removal we should probably update the abstract?

On deprecation - there are a variety of compiler options that can be enabled to do more code checking -- similar to our work with sonar, security scans etc

ref: https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javac.html#xlintwarnings

**Comment by planetf1** [comment]
this might need to be closed/removed now?
