### ISSUE TITLE
Beans do not show all inherited properties in .toString()

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#5171]
I've noticed that various beans (for example, `EntityDetail`) explicitly list the properties to include in their `.toString()` method -- which inevitably contain a mixture of both properties that are defined directly in that bean, as well as other properties that are inherited from one or more superclass's of that bean.

The problem I'm running into is that since these are defined explicitly in each bean, there are areas where not _all_ of the properties from the superclass's are included in a subclass's `.toString()`.  Not sure if this is intentional?

(If not, it would seem advisable to use a `super()` call to build-up the string from the superclass's `toString()`'s to avoid needing to maintain the explicit property lists across all inherited beans...)

The problem I'm running into if it _is_ intentional is that doing a `.equals()` that fails becomes difficult to debug, because a number of the properties that are used to calculate the `.equals()` at some level of the class hierarchy are not actually printed out in the `toString()` method -- making the only possible way to detect where things are not equal being going straight into the debugger.  (In particular: unit testing frameworks that print out the actual and expected values, using `.toString()`, will show what appear to be identical expected and actual values, but fail the `assertEquals()` condition, which is very confusing.)

**Comment by davidradl** [comment]
@cmgrote We talked about Lombok recently and I think we said it could be used to automatically generate the equals , hashcode, toString as well as the getters and setters from the annotations.It might be worth considering for the cases you are seeing.

**Comment by mandy-chessell** [comment]
There are multiple views on what should be in the toString().  I have had complaints that OMRS outputs every field and does not just put out selected "useful fields".   This issue is a complaint that some of the fields are missing in the OMRS toString() methods.  This is why the design of the implementation is up to the component owner.  Similarly each component owner can choose whether they use Lombok or not.

For OMRS, the toString() methods are designed to output all fields.  They are generated using intelliJ's code generator.  
If there are missing fields in the output then the methods should just be regenerated.  It is a bug introduced when a new property was added.

**Comment by cmgrote** [comment]
Ok, for now I'll just update the generated methods in IntelliJ...

**Comment by cmgrote** [comment]
Given:

- different editors (or even different versions of the same editor: IntelliJ) have different ways of generating this `.toString()` method
- keeping changes consistent for all subclasses would mean an addition high up the class hierarchy could involve manually re-generating these methods on many subclasses (potential to forget / miss one)

... would an alternative approach make sense?  For example: defining a `.toString()` method that is overridden in each subclass, but that calls `super.toString()` to automatically inherit any member changes from the entire superclass type hierarchy?

(I've used this approach in e.g. connector code to keep maintenance simple.)

**Comment by mandy-chessell** [comment]
Currently for OMRS the toString methods are generated by intellij - if possible to get IntelliJ to generate using a super method then ok - otherwise if they have to be hand coded then just a likely to get it wrong.  

I would say for OMRS, the changes are so infrequent I am not sure this is worth the effort to re-code them all?

**Comment by planetf1** [comment]
What do we want out of toString? Often it is to help in quick debugging - often with extra debug statements/trace (vs IDE/agent debug where the tooling does it anyway), or it is to better clarify the appropriate concepts that are likely useful for that level of abstraction ? 

If so, then if we consistently call super() the superclass is effectively deciding what is relevant, which loses that brevity/simplicity of content, and we could equally auto-generate through a framework or using reflection (ToStringBuilder.reflectionToString(this); ??). The main benefit in this suggestion is at least ignoring some fields  that one things might never be useful?

**Comment by cmgrote** [comment]
For OMRS, I believe the intention is to show all properties, per Mandy's earlier comment.  (And I'd suggest this be the case, as the specific problem I ran into was that some properties were missing that were used as part of a `.equals()` -- so when I look at the two objects side-by-side as string output or in the IDE (which .toString'd them) they looked identical, but `.equals()` was failing.)

**Comment by cmgrote** [comment]
I'd also specifically suggest avoiding using reflection due to it's significant performance overhead and impact...

**Comment by cmgrote** [comment]
In any case, see the draft PR #5171 -- if we're happy with this approach, we can un-draft and merge; if not, I'll need to hand this over to someone else as my IntelliJ community edition does not give me the ability to generate the full `.toString()` (inherited properties are never there), so I'd just end up doing all the coding by hand anyway (with far more copy / pasting and potential for error).

**Comment by mandy-chessell** [comment]
My community edition does allow the generation of toString with properties from super classes - which version are you on?

**Comment by cmgrote** [comment]
The latest:

```
IntelliJ IDEA 2021.1.1 (Community Edition)
Build #IC-211.7142.45, built on April 30, 2021
Runtime version: 11.0.10+9-b1341.41 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.3.1
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Non-Bundled Plugins: Docker (211.7142.13), YourKit Java Profiler 2021.3-b228 Integration (2021.3.228.0), org.jetbrains.idea.clojure (2020.3.1), org.jetbrains.kotlin (211-1.5.10-release-891-IJ7142.45), PythonCore (211.7142.45)
Kotlin: 211-1.5.10-release-891-IJ7142.45
```

I'm presumably doing something daft, but I just have a bunch of different options for which code to use (concatenation, StringBuffer, commons, guava, etc) -- but regardless of the chosen option, the only property listed is the one in the class itself (no properties from super-types).  Adding the code just gives me a toString with only that single property in the screenshot, and I can't see anything in the detailed settings to include any others.  (Example below from EntityDetail)

<img width="637" alt="Screenshot 2021-05-25 at 14 07 43" src="https://user-images.githubusercontent.com/5864283/119503530-fa606c80-bd62-11eb-9639-830bc3087e33.png">

Only thing I can see in the detailed settings is there is a templating language that the IDE itself seems to use to generate the method, which I could presumably modify, but that would be entirely custom from one to another then so wouldn't seem like a good way to go...

**Comment by mandy-chessell** [comment]
This is my intelliJ version
<img width="666" alt="Screenshot 2021-05-25 at 16 49 55" src="https://user-images.githubusercontent.com/12354195/119528781-68179300-bd79-11eb-9145-78fbaa6aa95b.png">

These are the setting I have:
<img width="837" alt="Screenshot 2021-05-25 at 16 50 10" src="https://user-images.githubusercontent.com/12354195/119528939-8b424280-bd79-11eb-8331-09cbaeb08d18.png">

This is the result when I ask to generte toString()
<img width="531" alt="Screenshot 2021-05-25 at 16 49 39" src="https://user-images.githubusercontent.com/12354195/119529048-a7de7a80-bd79-11eb-8c60-e2a789f72256.png">

**Comment by cmgrote** [comment]
No idea then -- maybe it's a regression in newer version of IntelliJ?  We're spending way more time trying to figure this out than just fixing the problem in the code...

**Comment by planetf1** [comment]
I've only checked 2021.1.2 ultimate, but see similar to mandy. (I had to set 'Enable getters in code generation' as per mandy's screenshot to see the .. getters...)

**Comment by planetf1** [comment]
> I'd also specifically suggest avoiding using reflection due to it's significant performance overhead and impact...

good point, though each version tends to improve performance, and depends on if it's main-line code or supporting debug (albeit then accept we don't want to change characteristics often).  There's also a relationship here to other tools to reduce boilerplate - lombok, but also Immutables and Autovalue (both are less intrusive annotation processors, not bytecode mods), but that requires a diff style of writing the beans so unlikely a good option for current classes?
