### ISSUE TITLE
 linkcheck.yaml file refering a users folder

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#5195]
I notice that in the linkcheck.yaml file, we reference Chris Grote's and Peter Evans id. I assume this is incorrect.
```
  uses: cmgrote/github-action-link-check@master
#      - name: Create issue from file
#        if: success()
#        uses: peter-evans/create-issue-from-file@v2
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          title: Broken links
#          content-filepath: ./errors.txt
#          labels: documentation, consumability, tidy up
```

**Comment by planetf1** [comment]
That is referring to a custom action ie not an official GitHub one. Just a link to a repo. In this case one that Chris built.

One can of course discuss with actions to use or whether we should move to odpi but is quite possible you'll find a variety of actions we need to use that are community contributions

So no error here

**Comment by cmgrote** [comment]
That's correct -- I made some changes to the original link checker to better meet our needs, so this is just a custom one that I've written (and hence it refers to that custom one).

**Comment by davidradl** [comment]
I was expecting this to be an Egeria repo containing the custom github actions, i.e. something owned by the community not an individual. Am I missing something here?

**Comment by cmgrote** [comment]
As Nigel stated, it's pretty common practice to just refer to whatever actions are out there in the marketplace -- if you'd prefer to create a new repository just for this tiny action within the Egeria workspace, that's fine, but it seems like unnecessary overhead to me...

**Comment by davidradl** [comment]
@planetf1 ok if you are both happy.
