### ISSUE TITLE
Kubernetes on Ubuntu 20.04 & Fedora 34 issues

### ISSUE THREAD

**Issue by exonianp** [odpi/egeria#5206]
In a clean Ubuntu (with no other software installed other than curl) the set up of the kubernetes was performed from scratch following [these instructions:](https://thenewstack.io/how-to-deploy-a-kubernetes-cluster-with-ubuntu-server-18-04/),

Tried to follow through the [instructions](https://github.com/odpi/egeria/tree/master/open-metadata-resources/open-metadata-deployment/charts/egeria-base).

The outcome is as shown here:

![image](https://user-images.githubusercontent.com/6937118/118893430-14d1ba80-b90b-11eb-9456-c6952e66fd77.png)

Kafka, zookeeper, platform-0 machines that require persistent volume storage come with this error:
_0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims._

config-xz8bh  comes with this error:
_Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "acd1c9300303b61d4806b2adc29ab8b74545819b459a8da197ab90eebe3ea167" network for pod "egeria-base-config-xz8bh": networkPlugin cni failed to set up pod "egeria-base-config-xz8bh_default" network: open /run/flannel/subnet.env: no such file or directory_

The machine that presentation-647cbcc9fc-rmm7s machine only worked after issuing this instruction:
_kubectl taint nodes  egeria node-role.kubernetes.io/master-_

I think (because I am still investigating) that Ubuntu requires explicit configuration of the Persistent Volumes in the yaml. Else it fails - e.g. where exactly the volumes will be created and that that have been granted sufficient privileges.

 In the lab example the situation is as follows:
![image](https://user-images.githubusercontent.com/6937118/118894371-c4f3f300-b90c-11eb-8435-68e15da10d8a.png)

So far it also seems that other installed software, such as ansible, can prevent such events. 

https://www.linode.com/docs/guides/deploy-minio-on-kubernetes-using-kubespray-and-ansible/

I am happy to create a documentation about the exact installation steps for Ubuntu.

**Comment by exonianp** [comment]
With the hope that the issue was ubuntu 20.04 specific, I installed Fedora 34 and the situation is identical.

![image](https://user-images.githubusercontent.com/6937118/118962428-0b2d6e80-b96e-11eb-8bdc-816f037a18dc.png)

I hope that an expert on the matter will enlighten us.  Maybe there is a configuration command that allows (but by default prevents) for the creation of volumes in persistent volume claims.

**Comment by planetf1** [comment]
This is as expected, though some clarification in the docs to explain it's dependent on persistent storage could be useful.

Many k8s requirements will automatically allocate storage. In particular public cloud - For example openshift does, IBM IKS. It does this using a 'storage provisioner'

In a local environment using microk8s this is enabled by `microk8s.enable storage` and I think (not verified) docker for windows/mac enables a provisioner by default

So you have a choice of either:
 - resolve the pvcs manually
 - enabling a storage provisioner in your k8s environment
 
 I think you also have issue with networking - as per your original message `Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "acd1c9300303b61d4806b2adc29ab8b74545819b459a8da197ab90eebe3ea167" network for pod "egeria-base-config-xz8bh": networkPlugin cni failed to set up pod "egeria-base-config-xz8bh_default" network: open /run/flannel/subnet.env: no such file or directory` - looks like a command that your k8s environment needs isn't present
 
 I think this is a very general question about k8s setup on ubuntu - so it may be worth looking at the k8s groups/lists? I use, for example, kubernetes.slack.com for a discussion area.
 
 I don't myself have experience with raw setup of k8s other than docker-for-mac/windows, microk8s. Beyond that I've used cloud-hosted environments (or full comercial product stacks like openshift) where storage provisioning is available by default/simple switch
 
 Any general tips you can add to the docs would be useful. If you just want to get things running and can't find a solution, microk8s may offer an alternative for your local environment

**Comment by planetf1** [comment]
Set up cephfs perhaps? https://ubuntu.com/kubernetes/docs/storage

**Comment by exonianp** [comment]
OMG!

Yes thank you very much Nigel - this ought to be it!
