### ISSUE TITLE
Top readme refers to ODPI code of conduct

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#5237]
The top readme refers to the ODPi's [Code of Conduct]. A @planetf1 pointed out it should point to an LF or LF AI&data code of conduct.

**Comment by planetf1** [comment]
@mandy-chessell I'm unaware where to find this. @jmertic ?

**Comment by jmertic** [comment]
The default one for projects in the LF Projects LLC series ( which Egeria is in ) is at https://lfprojects.org/policies/code-of-conduct/

**Comment by mandy-chessell** [comment]
The project has its own conde of conduct here https://github.com/odpi/egeria/blob/master/CODE_OF_CONDUCT.md
