### ISSUE TITLE
Remove Data Platform OMAS

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#5319]
In #5314 some atlas/ranger etc related code was removed and it was noted that Data Engine OMAS can now be removed, since it's capabilities have been replaced by Integration Services

However currently the cassandra metadata extractor depends on Data Engine, so it seems prudent to remove the cassandra metadata extractor first (cc: @lpalashevski )and then return to complete the removal of data engine omas

**Comment by mandy-chessell** [comment]
Data Platform OMAS?

**Comment by cmgrote** [comment]
As far as I know Data Engine OMAS is still used extensively for lineage (?)

**Comment by lpalashevski** [comment]
> Data Platform OMAS?
I hope so :)
Duly noted @planetf1. I will consider this and have step to remove Data Platform OMAS as part of the cassandra metadata extractor removal activity. I will create new issue to track this and link it here. Lets update the title on this though to say "Remove Data Platfom OMAS".

**Comment by planetf1** [comment]
@mandy-chessell @cmgrote Yes 'data platform'. Apologies. So many overlapping terms causing mental capacity overflow

**Comment by lpalashevski** [comment]
@mandy-chessell I need confirmation, removing Data Platform OMAS also implies removing the dedicated governance server (data-platform-services) including admin-services and documentation parts, right?

**Comment by mandy-chessell** [comment]
@lpalashevski yes :) - except leave the following file ...
https://github.com/odpi/egeria/blob/master/open-metadata-implementation/admin-services/docs/concepts/data-platform-server.md

**Comment by lpalashevski** [comment]
> @lpalashevski yes :) - except leave the following file ...
> https://github.com/odpi/egeria/blob/master/open-metadata-implementation/admin-services/docs/concepts/data-platform-server.md

This is now addressed in #5344 

Some occurences of Data Platform services in admin modules are not removed to preserve backward compatibility aspects i.e. checks in server type classifier that I think are still needed (that pulls in configuration document and related classes...)

We can disscuss it on the community call 10/06/2021 and decide if we completely remove the support.

**Comment by planetf1** [comment]
this has now been completed
