### ISSUE TITLE
Secured properties and other such information is part of toString in Connection

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#5328]
I was under the impression from the JavaDocs of the `Connection` bean that we should not be including sensitive information in the `toString()` method:

```
Note SecuredProperties and other credential type properties are not displayed.
This is deliberate because there is no knowing where the string will be printed.
```

... and yet they are actually there in the string that's built-up. Was this intentional, or an IDE re-generation of the `toString()` method that mistakenly left them there?  (i.e. do we need to change the JavaDoc or the code?)

**Comment by mandy-chessell** [comment]
The toString is wrong
