### ISSUE TITLE
Remove printStackTrace in Analytics Modeling

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#5329]
The analytics modeling code issues a stack trace in certain circumstances.
```
	
		} catch (InvalidParameterException | UserNotAuthorizedException | PropertyServerException e) {
207		
			e.printStackTrace();
208		
		}
209		
	}
```
This can leak private information and should be removed (IdentifierResolver.java)

See https://sonarcloud.io/project/security_hotspots?id=odpi_egeria&sinceLeakPeriod=true

**Comment by planetf1** [comment]
This needs addressing as stack traces are regarded as a security issue

**Comment by planetf1** [comment]
fyi: @mandy-chessell @lpalashevski @bogdan-sava as discussed in security meeting from sonar scan

**Comment by planetf1** [comment]
@yevgenmar fyi

**Comment by planetf1** [comment]
Assigning to myself for now

**Comment by planetf1** [comment]
@yevgenmar We need to remove this stack trace - would you like to do it? What would be useful to record instead?

**Comment by planetf1** [comment]
Hi Billy - would you like to fix this up alongside your improvements to the security hotspots?

**Comment by wbittles** [comment]
It seems that shipping debug code in a release is becoming common practice , there have been 10 new occurrences since I last completed that piece of work. It looks like we will need to strengthen the PR process to prevent debug code being merged into main.
Then I'm happy to go back and resolve the historical offences that are currently visible in the scan.

**Comment by wbittles** [comment]
The issue we are trying to prevent is the releasing of debug code into production environments so If you want to support debug code being merged into the main branch , does that not mean that the release process is going to have so as not to ship modules that may contain said debug code ? 

If the developer intends to ship debug code they are free to suppress the warning , which is tracked at a lower sev.

**Comment by planetf1** [comment]
Closing, as the analytics modeling OMAS has been removed
