### ISSUE TITLE
Empty response to request all glossary terms 

### ISSUE THREAD

**Issue by Inventoroz** [odpi/egeria#5337]
Glossary Term create
[create glossary term.txt](https://github.com/odpi/egeria/files/6617072/create.glossary.term.txt)

Request all term for glossary
POST https://172.22.100.177:19445/servers/cocoMDSx/open-metadata/access-services/asset-manager/users/garygeeke/glossaries/32b334f6-1701-46ed-a0b1-c7dbe852fdd1/terms/retrieve?startFrom=0&pageSize=10
{
  "assetManagerGUID" : "cf37f16d-3ef2-4aad-9e5d-03faa95184ce",
  "assetManagerName" : "AssetManager Unique Name"
}
200 OK 
{
  "class" : "GlossaryTermElementsResponse",
  "relatedHTTPCode" : 200,
  "elementList" : [ { } ]
}

why elementList is empty?

**Comment by mandy-chessell** [comment]
Not sure why this is not working.  The request looks ok - I'll have a look.

**Comment by Inventoroz** [comment]
request glossary term set category

POST https://172.22.100.177:19445/servers/cocoMDSx/open-metadata/access-services/asset-manager/users/garygeeke/glossaries/categories/34e782e6-76f3-4e0a-b776-aa251001b771/terms/06954ee5-078b-4256-9eb9-8bb42b7de0c0
{
  "assetManagerGUID" : "cf37f16d-3ef2-4aad-9e5d-03faa95184ce",
  "assetManagerName" : "AssetManager Unique Name"
}
200 OK 
{
  "class" : "VoidResponse",
  "relatedHTTPCode" : 200
}

request get all glossary term of category

POST https://172.22.100.177:19445/servers/cocoMDSx/open-metadata/access-services/asset-manager/users/garygeeke/glossaries/categories/34e782e6-76f3-4e0a-b776-aa251001b771/terms/retrieve?startFrom=0&pageSize=10
{
  "assetManagerGUID" : "cf37f16d-3ef2-4aad-9e5d-03faa95184ce",
  "assetManagerName" : "AssetManager Unique Name"
}
200 OK 
{
  "class" : "GlossaryTermElementsResponse",
  "relatedHTTPCode" : 200,
  "elementList" : [ { } ]
}

elementList is empty too
