### ISSUE TITLE
missing PathVariable in the path

### ISSUE THREAD

**Issue by rychagova** [odpi/egeria#5350]
I'm not sure, i'm newbee, it looks like there's no {setGUID} in the path to create a new valid value definition.
`@RestController
@RequestMapping("/servers/{serverName}/open-metadata/access-services/asset-owner/users/{userId}")

public class ValidValuesOnboardingResource{

@PostMapping(path = "/valid-values/new-definition")

    public GUIDResponse  createValidValueDefinition(@PathVariable String                 serverName,
                                                    @PathVariable String                 userId,
                                                    @PathVariable String                 setGUID,
                                                    @RequestBody  ValidValuesRequestBody requestBody)`

**Comment by mandy-chessell** [comment]
Agreed - looks wrong to me

**Comment by mandy-chessell** [comment]
Would you like to fix it, or should I?

**Comment by rychagova** [comment]
I would!

**Comment by planetf1** [comment]
Closing as this is now merged. Thanks @rychagova for spotting and fixing
