### ISSUE TITLE
Add further lombok information to developer guide

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#5360]
Lombok can cause duplicate classes.

I just posted the following to slack, which I think clarifies the situation.

I think we should extend our developer guide with this info:

If using IntelliJ, it’s important to ensure that Build, Execution, Deployment->Build Tools -> Maven -> IMportant ->Generated source folders is set to ‘Don’t detect’ to avoid issues with duplicate classes (due to our lombok usage combined with javadoc). This is now in our developer guide

However if this wasn’t set when your project was initially setup, you may find that ‘delombok’ directories are already present in IntelliJ’s source path for some modules, leading to errors with duplicate classes.

To check for any modules still refering to delombok you can run this at the command line, from your top level source tree:
```
find . -name '*.iml' | xargs -n50 grep -y delombok
```
If you find any hits such as:
```
./open-metadata-implementation/access-services/data-engine/data-engine-api/data-engine-api.iml:      <sourceFolder url="file://$MODULE_DIR$/target/delombok" isTestSource="false" />
```
then either remove those lines WITH INTELLIJ NOT RUNNING, or go into File->Project Structure->Modules, and remove ’target/delombok from the ‘Source Folders’ list

Explanation - In addition to importing importation on source files from maven, IntelliJ also tries to look for generated source. It finds the delombok directory causing duplicates — in fact we only use this directory for generating javadoc of lombok-enabled modules. Switching the setting/removing these source folders prevents duplicate classes.

For more info on the recent adding-back of lombok see https://github.com/odpi/egeria/pull/5216

Will create a PR of same...

**Comment by planetf1** [comment]
Any additional comments @lpalashevski @alexandra-bucur ? does this make sense

**Comment by lpalashevski** [comment]
I like the detailed explanation, lets put it into IngelliJ guide. I know I followed similar process so it will definately help for somone who already had environment before the lombok change.

**Comment by planetf1** [comment]
done
