### ISSUE TITLE
Fix deprecation warnings across egeria components

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#5363]
We have a number of deprecations currently being reported in relation to egeria APIs
A recent build shows around 130 

For example:
```
[WARNING] /Users/jonesn/IdeaProjects/egeria.maven/open-metadata-implementation/view-services/server-author-view/server-author-view-server/src/main/java/org/odpi/openmetadata/viewservices/serverauthor/services/ServerAuthorViewRESTServices.java:[810,33] captureThrowable(org.odpi.openmetadata.commonservices.ffdc.rest.FFDCResponse,java.lang.Throwable,java.lang.String,org.odpi.openmetadata.frameworks.auditlog.AuditLog) in org.odpi.openmetadata.commonservices.ffdc.RESTExceptionHandler has been deprecated
```
The deprecations are in multiple areas of the code.

We do also have some which are intentional - for example code which is actually supporting the old APIs (or testing it). In these cases we should add a tag to ignore these warnings using the @SuppressWarnings annotation

**Comment by mandy-chessell** [comment]
This is ongoing work - never-ending - no point in having an issue for this
