### ISSUE TITLE
Incorrect message formatting in the governance engine.

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#5376]
while running the Subject Area FVT I git this message. I notice that the insert {3} is incorrectly being displayed in the message  

Thu Jun 17 11:22:55 BST 2021 cocoMDS1 Information OMAS-GOVERNANCE-ENGINE-0021 The Governance Engine Open Metadata Access Service (OMAS) is ignoring event from Governance Engine OMAS of type processDeletedEntityEvent for instance 020d6b94-3398-429f-bd1a-0f7742914b34 because it does not have access to all of the instances information. Error message is: {3}

**Comment by mandy-chessell** [comment]
The problem is caused because the message format string includes a single quote for "instance's".  This turns off the formatting for the end of the message.
