### ISSUE TITLE
Change website's documentation rendering?

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#5384]
Having come across its usage on other projects, this looks like a much more flexible way for us to generate our website out of the various Markdowns that currently exist -- and produces a result that looks (IMHO) far more polished and consumable: https://squidfunk.github.io/mkdocs-material/

(The documentation visible via the link is entirely done through the project itself.)

Assuming that moving to this rendering over what we have at the moment would not introduce additional manual maintenance and that we could re-use our existing Markdown-based documentation as-is (TBC), would this be something we'd be interested in adopting?

**Comment by planetf1** [comment]
I'd be interested in improving.

I've come across readthedocs which some projects use. I think it also supports free hosting and search but I haven't looked closely

There's also devdocs. I wonder if it's worth comparing these various options

**Comment by planetf1** [comment]
I see readthedocs supports mkdocs as well as sphinx (richer?)

In terms of content it would be great off we could figure out how to tie rest API docs , javadoc, and our guides together coherently

**Comment by cmgrote** [comment]
Next step: @cmgrote to experiment with the rendering in his own fork and see what things look like / what problems it might surface.

(Note: would be very nice if we could more easily do some multi-repository documentation and search, if somehow feasible via the tooling.)
