### ISSUE TITLE
Data Engine OMAS Server-side ....................... Build Failure [Windows 10]

### ISSUE THREAD

**Issue by MaheBabu** [odpi/egeria#5387]
[org.odpi.openmetadata.accessservices.dataengine.server.handlers.DataEngineFolderHierarchyHandlerTest.txt](https://github.com/odpi/egeria/files/6704307/org.odpi.openmetadata.accessservices.dataengine.server.handlers.DataEngineFolderHierarchyHandlerTest.txt)

**Comment by planetf1** [comment]
We currently don't support, build or test Windows (as in win32 api) builds for Egeria.

We recommend you use the 'Windows Subsystem for Linux' (v2). See https://docs.microsoft.com/en-us/windows/wsl/

Whilst this particular issue relates to file seperators and would be easily addressed, we are aware of other issues also.
This clarification was addressed in https://github.com/odpi/egeria/pull/5084

See https://github.com/odpi/egeria/issues/4917
Noted in the 2.9 release notes at https://github.com/odpi/egeria/blob/51c0ad4fa186e72d172d85f899f1cfdb6df07c85/release-notes/release-notes-2-9.md
And in https://github.com/odpi/egeria/blob/51c0ad4fa186e72d172d85f899f1cfdb6df07c85/developer-resources/tools/Maven.md and similar places we are now recommending builds are done under WSL2 on Windows which is is a real *nix environment

If you would like to help us work through multiple issues with windows, and support build, test and ongoing use of windows I'd be happy to help you work through the issues and understand how to test, update build processes etc so we can get to a supported state for 'native' windows, but currently the core team is not working much with Windows, so we do not have the resource to take this on.
