### ISSUE TITLE
fix paging logic in the in memory omrs connector

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#540]
The paging logic is not quite right in InMemoryOMRSCollection in  formatRelationshipResults and  formatEntityResults.

I propose changing these methods to static - so they can be easily junitted and create a common  method for the paging logic.

**Comment by mandy-chessell** [comment]
I do not agreed with the use of static methods unless it is absolutely necessary.  This is because it reduces the flexibility of the code.

**Comment by mandy-chessell** [comment]
I think this is fixed now.
