### ISSUE TITLE
Rehoming classifications?

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#5400]
The repository services support the rehoming of metadata instances.  This means moving the ownership of an instance from one metadata collection to another.

Currently there are two methods - one for entities and one for relationships.  The question is, what about classifications?

When the original API was designed, classifications were always an attachment to an entity and so they were rehomed with the entity.  Now it is possible that classifications can belong to a different metadata collection and so now we could add a new repository connector method to rehome the classification with corresponding event.

If we did not do this, the way to rehome a classification is to delete it and recreate it using the current methods.  This is effective because the classification only has an attachment to an entity instance and so there is no loss if metadata. The small risk is that the instance is unclassified for the time window between the unclassify and classify commands.
This is OK for asset related metadata (assets, schemas, connections, ...) since we can use the zone support to withdraw and publish the asset while the update to the classification is enacted.  The question is whether this is a problem for other types of entities?

----
On a similar vein
* A reIdentify method/event method is not needed because classifications do not have GUIDs - their logical unique identfier is the entity GUID plus the classification name.
* A reType method for classifications is of little practical use because of the limited use of inheritance in classifications however if we added reHome for classifications we may want to add reType for consistency?

**Comment by cmgrote** [comment]
Are we also controlling this potential situation?

Given that homing of classifications can be done in a different repository than the entity itself, where do we control that the same classification (e.g. `Confidentiality`) is not applied against the same instance (`GlossaryTerm`) in multiple repositories (i.e. with one specifying the level as `1` and another specifying the level as `3`: which is correct?)?

(Based on my understanding that classification "instances" are intended to be singular in cardinality against a given entity (for example, a `GlossaryTerm` can only be classified with `Confidentiality` once and not multiple times).)

**Comment by mandy-chessell** [comment]
If the cohort is connected then only the first classification is allowed - subsequent classifications result in an exception.

If a repository that has a classification that has not been shared with any other member of the cohort is down when the second classification is added then the second classification is stored and the duplicate is detected on the next time the entity is read.

**Comment by cmgrote** [comment]
> If a repository that has a classification that has not been shared with any other member of the cohort is down when the second classification is added then the second classification is stored and the duplicate is detected on the next time the entity is read.

How is the duplicate notified: do both come back in the response (leaving the requester to decide how to handle / which to "survive"), or just in the audit log of the enterprise connector (in which case how do we choose which "survives" in the response)?

Or does this cause some more general exception response back to the requester?
