### ISSUE TITLE
Restart KafkaOpenMetadataEventConsumer if thread dies

### ISSUE THREAD

**Issue by jnhagelberg** [odpi/egeria#5407]
We have been having problems where, for whatever reason the `KafkaOpenMetadataEventConsumer` thread dies.  When this happens, the sync processing completely stops.  In order for our product to continue functioning when this happens, we need the `KafkaOpenMetadataEventConsumer` thread to be restarted if it dies.

There is already similar logic for restarting the `KafkaOpenMetadataEventProducer` if that thread dies.  The mechanism needs to be extended to also apply to the consumer.

**Comment by jnhagelberg** [comment]
FYI, I'm working on a PR for this.

**Comment by mandy-chessell** [comment]
What are the reasons for the thread dying - should there be some additional error handling in place to prevent it dying?

**Comment by jnhagelberg** [comment]
@wbittles What we saw was that that thread died during what appeared to be a transient out of memory issue.  We are looking at that, but to us this is really about resiliency.  If the thread dies, we are pretty much dead in the water, so we need to do everything we can to keep it alive.  In our scenario, the memory issue resolved itself but the kafka consumer thread remained dead.

**Comment by jnhagelberg** [comment]
@mandy-chessell ^^

**Comment by wbittles** [comment]
@jnhagelberg 

Resiliency shouldn't be valued over functional integrity, there is little value in restarting a thread if it's behaviour is indeterminate.
My understanding is that OOM is a Java JVM Error , where the JVM has already decided that it's in an error state and that the JVM needs to be shut down. 
My fear is that this JVM Error has been caught and translated into an Exception which is allowing Egeria to ignore the state of the JVM, and Egeria is in effect just limping along in an error state.
To resolve OOM errors usually involves allocating more memore via the JVM command line options and it's unclear how we are going to avoid the need to shut the JVM and down and restart with an increased heap ?

**Comment by planetf1** [comment]
@wbittles - Completely agree... In fact in this case I would suggest that the JVM must be restarted - for example in a k8s environment this could be to intentionally let the server 'die' (shut itself down) and exit, and k8s will restart it elsewhere - clean environment, new jvm etc

**Comment by jnhagelberg** [comment]
@planetf1 @wbittles I agree that we should probably restart the JVM.  However, to this is more about resiliency.  We cannot guarantee that the JVM will be restarted.  If it does not restart we need to make a best effort attempt to keep functioning. 
 There is already logic for handling of the event producer dies, and there also needs to be logic to handle of the consumer dies.  This is not a theoretical issue.  We have customers whose systems are out of sync because the consumer thread died.  This is further complicated by the fact that in our implementation code we have no way of detecting and responding to instances where the kafka consumer thread dies.  The thread lives in egeria, so the fix must go in egeria.  Restarting the thread in cases like this is very easy in the egeria side, but nearly impossible for us to do on our side.  
 
I do not understand what your concern is.  If there is some specific aspect of the fix you are concerned about, please let us know and we will address it.  We need egeria to robust, and we need for it to be updated when we find problems.  We have even provided the code that fixes this particular problem.

**Comment by jnhagelberg** [comment]
We are also looking into the cause of the OOM issue.  I suspect that it is the queue of unprocessed messages.  Probably the size ("event_bus_max_queue_size") is configured to be too big in their system.  That definitely does need to be fixed.  However, that is separable from this issue.  It is also separable from the fact that we have no good way of detecting and reporting the status of the producer and consumer threads.  I think that all of these need to be fixed.  This issue is just fixing one piece of that, the piece where we attempt to recover when faced with unexpected errors.

**Comment by planetf1** [comment]
I see the PR is closed now so I believe this can be closed.

I have also looked through the code and understand the design. The code does as you intended - though we may need to look again at whether some exceptions should be treated as fatal (ie I am concerned around OOM), but they can be raised in a new issue when we have action.

For now therefore I propose we close the issue
