### ISSUE TITLE
IGC Repo Connector - NEW_RELATIONSHIP event issue

### ISSUE THREAD

**Issue by ruxandraRosu** [odpi/egeria#543]
InstanceProvenanceType of relationship is null thus atlas doesn't persist it.
The entity proxy1 type is the supertype Referenceable, should be the actual type of the entity proxy (RELATIONAL_COLUMN etc.)

**Comment by cmgrote** [comment]
Thanks!  Just testing out these changes on my side before putting into a PR...

**Comment by cmgrote** [comment]
Just added PR #544 to address these problems.

**Comment by ruxandraRosu** [comment]
@cmgrote relationships are stored in atlas now so this issue can be closed once PR is merged
