### ISSUE TITLE
Community Guide content has outdated call info

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#5452]
At https://github.com/odpi/egeria the top level README.md correctly lists our current calls on Tue/Wed/Thu
<img width="1096" alt="Screenshot 2021-07-01 at 16 51 07" src="https://user-images.githubusercontent.com/7292002/124153682-97ae6f00-da8c-11eb-94d8-8b9bb28edecb.png">

However if someone goes to https://egeria-project.org & then follows the link the 'Community Guide' they are presented with OLD information - with calls on a tuesday, and no links to the calendar.

<img width="1275" alt="Screenshot 2021-07-01 at 16 50 48" src="https://user-images.githubusercontent.com/7292002/124153696-9bda8c80-da8c-11eb-8d03-e2d0d62155e6.png">

* Can we consolidate to a single copy of this information to avoid them getting out of sync
* We need to ensure the up to date info is available to those going to the egeria-project.org page

Thanks for spotting @sumalaika , cc:  @davidradl @mandy-chessell

**Comment by davidradl** [comment]
@adharida is interested in doing this change - he says he will do this today, as a way of contributing to Egeria - are you ok with this @planetf1 and @mandy-chessell. You may have already done though Mandy!

**Comment by adinh808** [comment]
If I get approval, I would perform the change today.

**Comment by planetf1** [comment]
Note that our web page docs are moving from https://github.com/odpi/egeria to https://github.com/odpi/egeria-docs . I would recommend searching both places for related text & consistency

**Comment by davidradl** [comment]
@adinh808 Mandy and Nigel are fine with you doing this, I have assigned this issue to you. You are free to proceed, thank you for your interest and forthcoming contributions to Egeria.

**Comment by davidradl** [comment]
@cmgrote drawing your attention to this docs change.

**Comment by cmgrote** [comment]
Hi @adinh808 -- indeed we've started to migrate some of this information, with the idea that the best approach for up-to-date call information is likely going to be just rendering our calendar itself (rather than needing to maintain the calendar and these static markdowns separately)...  The revised information is here:

https://odpi.github.io/egeria-docs/guides/community/

It does sound like there might be additional information in the top-level README, though, that is not currently in the community guide?  I wonder if it would make sense to move that information from the top-level README into the community guide, and then point the top-level README at the community guide?

**Comment by adinh808** [comment]
The actual project Readme page (https://github.com/odpi/egeria) has all the info about calls and links to calendar. If the top level README page contains updated and all the necessary information, then we can add the same to https://odpi.github.io/egeria-docs/guides/community/ and https://egeria-project.org/community-guide pages. Definitely, we can point out the top level README page in these Community guides.

**Comment by adinh808** [comment]
I see the content in https://github.com/odpi/egeria-docs/blob/main/site/docs/guides/community.md seems to be the latest and this can be integrated into https://egeria-project.org/community-guide page. I will validate the content across both pages.

**Comment by davidradl** [comment]
@cmgrote I see what you are saying Chris. I assume we will lose the top level readme in the move to mkdocs. So copying over the content to the community guide should be an improvement for now. Maybe we remove from the top level readme as part of the transition - as people are used to seeing it there in the current structure. This would allow @adinh808 to complete his first contribution.

**Comment by adinh808** [comment]
Should I go ahead and collate information from both sources and set up the data or wait for some more time to go with the update?

**Comment by planetf1** [comment]
Ref the removal from the top level README. I would be inclined to agree - remove the info from there, but ensure there is a clear link in the readme to the location of the community guide which includes information about contribution and regular calls. I realise that link is a bit transient for now - I'm inclined to leave this until the main docs migration is at a point we were are back to doing small incremental changes rather than large restructuring.

**Comment by cmgrote** [comment]
+1

**Comment by adinh808** [comment]
I have done the requested changes as per the comments mentioned in this issue. A Pull request opened for this update: [5603](https://github.com/odpi/egeria/pull/5603) 

Following are update, 
1. Updated the Community Guide with information present in top level README.md file
2. Removed the content from top level README.md file
3. Updated the egeria-docs repo Communityguide page as well with latest information available in top level README.md file

**Comment by davidradl** [comment]
@cmgrote I am looking for your approval or not of this change - as I do not want to interfere with your big change.

**Comment by planetf1** [comment]
I think we pretty much focus on the new repo, with the expectation that will become the default 'soon'. I don't think it's particularly valuable to updat the existing docs. In some cases a link may be helpful, but even then it could be unnecessary (unless the source of that link remains long-term, such as the readme)

**Comment by planetf1** [comment]
this is now fixed, as we embed a google calendar in the page
