### ISSUE TITLE
Validating that required properties are present on an instance

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#5455]
Granted there are very few required attributes in the open metadata type model (just `qualifiedName`, I think?), but it seems that currently there is no validation carried out that such instance properties have a value -- making it possible to for example create a `Referenceable` through `addEntity` without any value for `qualifiedName` provided.

Presumably this should not be possible, given that `qualifiedName` is defined with a minimum value count of 1?

If so, should we be validating such required fields through a common method like `validatePropertiesForType`, which is already used by most (all?) repositories to validate the instance properties as part of methods like `addEntity`?

**Comment by mandy-chessell** [comment]
It is not true to say there is no validation of qualified name.

The responsibility for validating qualified name (its uniqueness and its presence) is currently located in the OMASs.  There are validation functions in the generic handlers for use by the OMASs and many of them do so.  The OMASs that do not use the generic handlers need to provide their own validation.

This issue needs a list of places where the OMASs are not validating qualifiedName.

**Comment by cmgrote** [comment]
Aha, so we expect this validation only to occur at the OMAS level, then. I was looking for it at the OMRS level...

For clarity, would it be worth adding a quick bullet to the common service that implements the check, so that any OMAS not using the common services knows this check must be independently implemented?

(I just quickly scanned the Generic and Repository Handlers and didn't see it mentioned in either...)

**Comment by mandy-chessell** [comment]
Where should it be documented so that developers would read it?
