### ISSUE TITLE
Inconsistent Audit logging on purge

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#5474]
In the repository handler 
- removeEntity tries to delete then if delete is not supported issues a purge, the purge method issues an audit log
- There are 2 callers to purgeRelationship only one of which audit logs 

This is inconsistent. 
I suggest we move the relationship audit log to the purge method, which means that both callers will audit log.

**Comment by mandy-chessell** [comment]
To make this a good first issue, you need to add details of where this code is and how to test it.  Also what should appear on the audit log - for example if purge is called from the API then you would want a different audit message to the case where purge is being used instead of delete.

**Comment by davidradl** [comment]
Thanks @mandy-chessell I will update after https://github.com/odpi/egeria/issues/5399 is complete -as it simplifies what we need to change

**Comment by planetf1** [comment]
(assigning for clarification)
