### ISSUE TITLE
qualifiedName – not unique when creating Valid Value Sets

### ISSUE THREAD

**Issue by rychagova** [odpi/egeria#5478]
I wonder, why it's possible to create two new valid value sets with identical names when sending queries in parallel. 

> POST https://172.22.100.228:9443/servers/uad2/open-metadata/access-services/digital-architecture/users/admin/valid-values/sets
> {
>   "class" : "ValidValueProperties",
>   "qualifiedName" : "not unique name",
>   "isDeprecated" : false
> }
> 200 OK 
> {
>   "class" : "GUIDResponse",
>   "relatedHTTPCode" : 200,
>   "guid" : "2ab3612d-1eea-4a69-8f59-9da16e1fe92b"
> }
> POST https://172.22.100.228:9443/servers/uad2/open-metadata/access-services/digital-architecture/users/admin/valid-values/sets
> {
>   "class" : "ValidValueProperties",
>   "qualifiedName" : "not unique name",
>   "isDeprecated" : false
> }
> 200 OK 
> {
>   "class" : "GUIDResponse",
>   "relatedHTTPCode" : 200,
>   "guid" : "e3547a6e-2268-4fb9-af84-0ac940e91dd2"
> }

Though there exists validation on name uniqueness for queries sent with delay in time.

**Comment by mandy-chessell** [comment]
This is because in a distributed world it is not possible to serialize all updates to all repositories.  The architecture has to handle the possibilities that duplicates can be created.  All that is possible is to minimize the occurances.

**Comment by rychagova** [comment]
Thank you, thats make sense.
