### ISSUE TITLE
securedProperties Field Retrieved Through REST API

### ISSUE THREAD

**Issue by stevengreens10** [odpi/egeria#5485]
The `securedProperties` field on org.odpi.openmetadata.frameworks.connectors.properties.ConnectionProperties.java comes back via the REST API.

The documentation for this field says:

> securedProperties - Protected properties for secure log on by connector to back end server.  These
> are protected properties that **can only be retrieved by privileged connector code.**

But when I use the securedProperties during configuration, the fields come back via the REST API at this endpoint:
`GET {{baseURL}}/open-metadata/admin-services/users/{{user}}/servers/{{server}}/configuration.`

Experiencing this issue in the latest version of Egeria.

**Comment by cmgrote** [comment]
Now that I read the detail again I may have been wrong about this being a bug: it may be valid that retrieving the configuration via admin services (which could be protected behind other security mechanisms) does return the secured properties -- as they are by default encrypted on disk so there is little other way to easy retrieve or review them.

Will check and confirm.

**Comment by mandy-chessell** [comment]
You are right - the values have to be sent over REST.  The documentation that you are reading is for Java - and the protection is minimal because it can be overcome with reflection.

**Comment by cmgrote** [comment]
So maybe what we need to delve into more deeply (discussed briefly on today's dev call) is how to secure these admin endpoints to ensure access to such restricted info is appropriately controlled.

@stevengreens10 perhaps you could help us understand the specific issues from your side so that we consider solutions in light of such scenarios?

**Comment by mandy-chessell** [comment]
There is a specific security connector for the platform that provides explicit protection to all platform calls - ie admin, ops and diagnostics.  
https://egeria.odpi.org/open-metadata-implementation/common-services/metadata-security/

We demonstrate it in the Coco labs so there is a sample implementation.

**Comment by davidradl** [comment]
I suggest we close this one. If there are not more updates I will code at the end of this week.
