### ISSUE TITLE
LineageGraphconnector transaction concern

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#5521]
I was looking at the code and noticed 
` private void upsertToGraph(LineageEntity fromEntity, LineageEntity toEntity,
                               final String relationshipLabel, final String relationshipGuid) {

        Function<LineageEntity, Vertex> createVertexFunction = (lineageEntity) ->
             g.V().has(PROPERTY_KEY_ENTITY_GUID, lineageEntity.getGuid())
                    .fold()
                    .coalesce(unfold(),
                            addV(lineageEntity.getTypeDefName())
                                    .property(PROPERTY_KEY_ENTITY_GUID, lineageEntity.getGuid()))
                    .next();

        Vertex from = commit(graphFactory, g, createVertexFunction, fromEntity,
                "Unable to create vertex with type " + fromEntity.getTypeDefName() + " and guid "
                        + fromEntity.getGuid());

        Vertex to = commit(graphFactory, g, createVertexFunction, toEntity,
                "Unable to create vertex with type " + toEntity.getTypeDefName() + " and guid "
                        + toEntity.getGuid());

        Supplier<Edge> createEdgeSupplier = () -> g.V(from.id()).as("from").V(to.id())
                .coalesce(inE(relationshipLabel).where(outV().as("from")),
                        addE(relationshipLabel).from("from")).property(PROPERTY_KEY_RELATIONSHIP_GUID, relationshipGuid).next();

        commit(graphFactory, g, createEdgeSupplier,
                "Unable to create edge with label " + relationshipLabel + " and guid " + relationshipGuid);
        //TODO add relationship properties -> meaning add relationship properties on AssetLineage omas event

        BiConsumer<Vertex, LineageEntity> addOrUpdatePropertiesVertexConsumer = this::addOrUpdatePropertiesVertex;

        commit(graphFactory, g, addOrUpdatePropertiesVertexConsumer, from, fromEntity,
                "Unable to add properties on vertex from entity with type " + fromEntity.getTypeDefName() +
                "and guid " + fromEntity.getGuid());
        commit(graphFactory, g, addOrUpdatePropertiesVertexConsumer, to, toEntity,
                "Unable to add properties on vertex from entity with type " + toEntity.getTypeDefName() +
                        "and guid " + toEntity.getGuid());`

I had some concerns:
1- If possible it would seem far safer to do all of this in one transaction, rather than having multiple commits in this one method. I would think it must be possible to chain commands after the vertex creations through to the edge creation. I suspect Graham's remote investigations might have covered this sort of thing.
2- if we cannot chain the creations into one transaction, we should have compensation logic to undo any creates that we have done prior to the error. Otherwise we are left with partially created content.  

Assigning to Ljupcho to see what you think.

**Comment by lpalashevski** [comment]
I am not quire sure if 1) is option. Based on our knowledge at that point in time this was the only way we can make it work if you consider running the query agains janusgraph server where you do not explicitly control the transaction -- every call is one single transaction. Lets see what Graham's investigation suggests.

For 2) I agree it is good practice in general but here with this implementation not sure how possible it is to do it efficiently for upsert; It looks to me that it will be quite expensive for each call to query the state before upate and revet on error.

Let's continue the discussion on the functional call today.
