### ISSUE TITLE
Lombok.config

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#5570]
After running a build I am often seeing the following in my Git status:

```
jonesn:egeria/ (master*) $ git status                                                                                    [9:51:48]
On branch master
Your branch is ahead of 'origin/master' by 73 commits.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    lombok.config

no changes added to commit (use "git add" and/or "git commit -a")
```
Needs investigation. Probably needs adding as a .gitignore

**Comment by planetf1** [comment]
Probably relates to 41079079ec0e4e55a139be8fb89aa18fea3c852f , though have not yet identified what is causing this config file to be deleted

**Comment by alexandra-bucur** [comment]
@planetf1, unfortunately I am not aware of the reason. I am back to building with maven (don't know if maven/gradle are related to this but nothing else comes to mind) and the file looks unaltered. At a first look on Google nothing shows.

**Comment by planetf1** [comment]
Thanks. Going to close for now - will reopen if it reoccurs
