### ISSUE TITLE
IGC Repo Proxy - missing instanceProperties values

### ISSUE THREAD

**Issue by ruxandraRosu** [odpi/egeria#558]
Following properties are not populated:
-networkAddress for Endpoint entity
-connectorProviderClassName for ConnectorType

**Comment by cmgrote** [comment]
question on the `connectorProviderClassName`: the connectors I'm outputting are to eg. the local file system of Information Server and DB2 (neither of which has an OCF connector defined)...

Therefore I don't think there's a realistic value I can set `connectorProviderClassName` with...  Should I simply not output this `ConnectorType` entity (ie. is it reserved only for OCF connectors)?

**Comment by ruxandraRosu** [comment]
@cmgrote Without _connectorProviderClassName_ virtualizer will not know how to resolve the source table for a view in gaian as the convention for the mapping is similar to: ORACLECONNECTOR_XE_HR_EMPSALARYANALYSIS
DB2CONNECTOR_XE_HR_EMPSALARYANALYSIS
The actual values we used so far were not fully qualified classes or OCF Connectors. Examples used: OracleConnector, DB2Connector.
Is it possible to set up to these values(that I think is type from additionalProperties) and have a separate thread if we want to have only OCF Connectors saved as ConnectorType? Removing ConnectorType entity impacts IV OMAS, Virtualizer and possibly Asset Catalog.

**Comment by cmgrote** [comment]
ah, ok, gotcha -- yes, trivial for me to put that kind of info in the className -- just want to be sure you don't actually try to use it as some executable class (since it isn't)!

**Comment by cmgrote** [comment]
@ruxandraRosu can you re-test my latest update to PR #544 and confirm if that addresses these issues?

**Comment by ruxandraRosu** [comment]
@cmgrote I've tested and networkAddress and connectorProviderClassName are populated, but the value for endpoint network address is the address of IGC host, not of the database host. Same issues is for the other endpoint properties like name, qualifiedName. The expected endpoint should be representing database host. The value for connectorProviderClassName is correct(OracleConnector)

**Comment by cmgrote** [comment]
@ruxandraRosu understood.  The hostname I'm picking up is the name of the `host` object as it exists in IGC (there is no other name or network address available as far as I'm aware).  This name is set during the Metadata Asset Manager (IMAM) loading of the metadata: and unfortunately, by default this name is set to the name of the engine tier of Information Server.

However, it is configurable as part of the IMAM import process: and we should be using the database hostname as part of that configuration:

<img width="1280" alt="screenshot 2019-01-18 at 09 34 56" src="https://user-images.githubusercontent.com/5864283/51378221-af841980-1b04-11e9-9456-c03561391422.png">

Or for your specific assets, do you have another property in mind which has the correct hostname?  Would be interested in seeing what that is, if so =)

**Comment by ruxandraRosu** [comment]
@cmgrote This might be an issue with our environment as we have an alias(the one showing up as host) for the database host(that is the same as IGC host). The currently displayed name in endpoint comes from host engine that contains network node, which seems correct. The current mapping that we're using in gaian contains the host name that is the same as _host details_ linked to the _host engine_(that it's a simple string). I will try to modify the mappings in gaian to use the alias and retest.

**Comment by ruxandraRosu** [comment]
@cmgrote after changing gaian node name for alias name it works fine, this issue is solved

**Comment by cmgrote** [comment]
Excellent, thanks!  I just need to re-build granular version bindings for another issue (will probably go over the weekend), and then I'll merge #544 to get these changes into master.
