### ISSUE TITLE
A Small Error in the Open MetaData Types Documentation

### ISSUE THREAD

**Issue by Kelukin** [odpi/egeria#5581]
Documentation URL: https://egeria.odpi.org/open-metadata-publication/website/open-metadata-types/0020-Property-Facets.html

The ReferenceableFacet's stereotype should be a **relationship** instead of an **entity** in the UML Model.

**Comment by mandy-chessell** [comment]
Thanks for pointing these out.  I will update them

**Comment by mandy-chessell** [comment]
They should be fixed now ...
