### ISSUE TITLE
Enhance the server author fetch platforms to include the registered access services.

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#5590]
currently the ui get the platforms using the admin call then gets the registered access services on the platform in 2 calls. 

I have already extended the fetch platforms in the server author view service to augments the returned server objects with an operational status. I intend to extend the response to include the registered access services. This means the ui only needs to issue one call to the server rather than 2. The platform content is not expected to change under the server author (or at least we are not coding for that in the UI at this time!).

**Comment by davidradl** [comment]
I notice that MetadataAccessPointConfigurationClient has a constructor that takes a serverName.
This server name ends up in the top level super constructor and creates a Spring rest admin client.

For the getRegisteredAccessServices() I see
`  public List<RegisteredOMAGService> getRegisteredAccessServices() throws OMAGNotAuthorizedException,
                                                                            OMAGInvalidParameterException,
                                                                            OMAGConfigurationErrorException
    {
        final String methodName  = "getRegisteredAccessServices";
        final String urlTemplate = "/open-metadata/platform-services/users/{0}/server-platform/registered-services/access-services";
`

This is a platform call so there is no server - so I should not have a supply a server on the constructor in order to make this call. 

I propose moving this call to OMAGServerPlatformConfigurationClient , next to the call that gets all the server configurations.

I will deprecate the existing API call - as the admin API is released. 

@mandy-chessell are you ok with this?

**Comment by davidradl** [comment]
A further consideration is that the intent for the Server author is to author a new server on the omag platform that the view service is connected to. So
- maybe I should only use the access services defined on that server
- maybe I should always assume that all access services are available on the platform targeted by the view server config.     
In that case it simplified the callers job, as they do not need to deal with registered access services 
- if I then look to deploy onto another platform I could check whether the target platform supports all the access services that are in the configuration
- the platform targeted by the view service (in terms of the remote end point it talks to) config may not be actually defined as a platform )

I suggest a minimal design as:
- for the server author view service to check if it is defined as a platform - and not start if it is not - with appropriate message
- for the server author view service to check if all the access services are registered - and not start if it is not - with appropriate message. This would save the caller from having to query it.
- at deployment the caller could query the target platform to check that the selected access services in the configuration to be deployed match the registered ones on the target platform. 

@planetf1 @mandy-chessell Are we ok with this suggested approach?

**Comment by davidradl** [comment]
I am going to enhance the client  get the integration and engine services associated with the platform and pass these back is sub-objects of the Platform in the Server Author View service

**Comment by davidradl** [comment]
TODO I need to change the postman collections to use the new non deprecated call.

**Comment by mandy-chessell** [comment]
I am not quite following the discussion.
When you talk about access services do you mean all of the registered services? IE the engine services, integration services, view services as well?

The admin client is designed to support the configuration of the server.  It includes getting the registered services to allow the look up of the valid service names when configuring specific services on the server.  This is likely to be part of a sequence of calls made to the client.  **Please do not deprecate these calls.**

If you want to make platform only calls (ie no server) then you are right that the platform services client is the right one to use.

The platform does not know its platformRootURL, name and description and so can not return it.  These values are coming from the view service configuration.

**Comment by planetf1** [comment]
One thing I think important for large deployments - such as those done via k8s/operator is a clear distinction between authoring and deployment.

As such I was wondering how the operational status is being used - since the state of the platform where the authoring is being done will not be the same as where it is deployed. Indeed in the particular case of access services I think it's possible the server author may want to create a server definition referring to a non-registered access service which is only dropped in at deployment time

I note references to the ui checking the target platform, but I do not think deployment is the server author's responsibility (certainly it won't be in an operator environment).

My preference would be that server author is focussed on creating definitions to be deployed with the end result of storing a configuration. I get that for convenience we may want a short cut to deployment in simple environments but feel that should be only using the configs we stored earlier. We do also potentially have an issue with host/service names on connectors which may need updating at deployment time.

**Comment by mandy-chessell** [comment]
Thats a good point - we also did discuss getting the information about available platforms, services and connector types from the metadata server that the view server calls.  These metadata elements would have descriptions filled out.
They could then be ued to populate the dropdowns needed in the server config.

Note that the underlying admin calls do validate the java class name of the connector provider when a connection is configured.  This means the platform of the MDR will need the connector implementations available to its platform.  However, they do not need to be in the platform where the view server is located.

**Comment by mandy-chessell** [comment]
> ```
> private List<RegisteredOMAGService> accessServices;
> private List<RegisteredOMAGService> commonServices;
> private List<RegisteredOMAGService> governanceServices;
> private List<RegisteredOMAGService> viewServices;`
> ```
This list is not correct for configuring the registered services - the list should be access services, integration services, engine services and view services.

The common services are services such as the repository services, admin services, OCF management etc.
The governance services is the code that supports each of the governance server types - eg the code for the integration daemon, engine host and discovery engine proxy.  These are not configured as services - they are different types of OMAG servers.

**Comment by davidradl** [comment]
> I am not quite following the discussion.
> When you talk about access services do you mean all of the registered services? IE the engine services, integration services, view services as well?
> 
> The admin client is designed to support the configuration of the server. It includes getting the registered services to allow the look up of the valid service names when configuring specific services on the server. This is likely to be part of a sequence of calls made to the client. **Please do not deprecate these calls.**
> 
> If you want to make platform only calls (ie no server) then you are right that the platform services client is the right one to use.
> 
> The platform does not know its platformRootURL, name and description and so can not return it. These values are coming from the view service configuration.

Sorry for not being clear. I was looking at Dino's PlatformOverview- that is populated by calling the PlatformServicesClient, which exposes those Registered OMAG Services.  I copied this approach in Server Author, augmenting the server objects with the operational server status - I get from other calls and the information from the server author view configuration.

I think you are suggesting that this PlatformServicesClient  is not correct and that it should expose calls to return  access services, integration services, engine services and view services. I should then use these calls  to get the registered services content. Have I understood correctly?

**Comment by davidradl** [comment]
> One thing I think important for large deployments - such as those done via k8s/operator is a clear distinction between authoring and deployment.
> 
> As such I was wondering how the operational status is being used - since the state of the platform where the authoring is being done will not be the same as where it is deployed. Indeed in the particular case of access services I think it's possible the server author may want to create a server definition referring to a non-registered access service which is only dropped in at deployment time
> 
> I note references to the ui checking the target platform, but I do not think deployment is the server author's responsibility (certainly it won't be in an operator environment).
> 
> My preference would be that server author is focussed on creating definitions to be deployed with the end result of storing a configuration. I get that for convenience we may want a short cut to deployment in simple environments but feel that should be only using the configs we stored earlier. We do also potentially have an issue with host/service names on connectors which may need updating at deployment time.

I am currently looking to update the existing code to use rest calls to the Server author View service, which in turn uses the admin clients. The existing code only supports creating metadata server and does not seem to deal with more than one platform, all the other server types are place holders. Prior to the changes I am working on, it showed a list of servers (without the platform) and a hard coded ACTIVE status. The idea is that a server author will need to see what is already there, before they amend or add new ones. I think it is useful to see what servers are on the platforms that the server author view server config defines. 

A very minimal solution for the server author would be 
- remove the status from the servers in the list
- remove the ability to start or shutdown. Though we may need to shutdown in order to be able to delete a configuration. 
- remove the ability to see what servers are on which platforms, you only get the servers that are defined on the omag platform that the server author is connected to.
- remove the platform specifications from the server author config. 
- do not do allow deploy - until such time (if we ever do) as we want them to be aware of platforms. 
- In this case the platform would need to have all services registered on it so it could author all types of server.

The deployment would then need to add in the platform specifics like connector details into the configuration. We just need to know what platform values we store in the server config that the server author creates. Maybe Nigel's idea of templates and variables to allow substitution at deploy time would help here.

@mandy-chessell @planetf1 what do we think of this cut down reduced scope server author UI.

**Comment by mandy-chessell** [comment]
I think the view service should call a backend platform because the view services may be a platform that is infront of the cohort platforms and there may be a firewall inbetween.  If the view service is using its own platform then the connectors to the back end technology need to be installed in the view service platform.

It is possible that there is only one platform - but we should preserve the ability for the platform where the admins calls run  to be different from the view server's platform.

This should not affect the code because the admin and platform services clients issue remote calls.

**Comment by davidradl** [comment]
> I think the view service should call a backend platform because the view services may be a platform that is infront of the cohort platforms and there may be a firewall inbetween. If the view service is using its own platform then the connectors to the back end technology need to be installed in the view service platform.
> 
> It is possible that there is only one platform - but we should preserve the ability for the platform where the admins calls run to be different from the view server's platform.
> 
> This should not affect the code because the admin and platform services clients issue remote calls.

If I have understood correctly : 
The view service does call a backend platform. So the amendment to the above proposal  is that the server author user chooses from a list of backend platforms, which one the server will be authored on; by default it would be the downstream platform associated with the view service. The platform list would come from the Server author view service configuration - which is already there . I guess there would be 2 modes of working - one where configs are accumulated on one platform, another whether they are authored in the place where they will run.

**Comment by mandy-chessell** [comment]
Support of pushing config to different platforms is important.  Particularly if servers are configured on a specific platform.

We would move to the retrieval of values such as platforms, connector types from the back end metadata server as soon as the IT Infrastructure OMAS is available (end of Aug).

It is not necessary to shutdown a server to update or delete its config.

It is necessary to have some knowledge of the platform that a cohort member (ie metadata server, repository proxy, metadata access point) will run in in order to set up the local reposiotry remote connection parameter so I do not think removing the knowledge of the platform from the configuration process is possible.

Nigel and I where working on identifying all of the places where network information is added - in the endpoints plus configuration properties of the connection objects basically.  This is where the templating - or support for retrieved values - is needed.

**Comment by mandy-chessell** [comment]
> If I have understood correctly :
> The view service does call a backend platform. So the amendment to the above proposal is that the server author user chooses from a list of backend platforms, which one the server will be authored on; by default it would be the downstream 

It is possible to do it that way.  It has the advantage that the server author could target the platform where the connectors are located for the server.  It would make it possible to configure a connector that is only available on a third party platform for example.  However, these platforms are not going to be the production platforms.

The downside is that it makes the view server different from the others.  If the view service had one platform/MDR to call, then only one dev platform would need to be set up with all the connectors.  The user would still select a platform to use to set up the platform URL etc.  However, the config calls would go to the view service's principle platform/MDR.  Then when the config is complete, all of the config is kept together and can be deployed into test systems and eventually onto production.

It suggests that the platform being configured for is not necessarily the platform where the admin services run.

**Comment by planetf1** [comment]
> We would move to the retrieval of values such as platforms, connector types from the back end metadata server as soon as the IT Infrastructure OMAS is available (end of Aug).

We'll need to figure out the relationship with k8s resources then too -- for example I currently envision a platform CRD (defines image to run, connector code artifacts etc) and a server CRD (name, replicas, link to config etc). Both are defining resource definitions that act as a goal for the operator. That goal could of course be to achieve a modeled deployment retrieved from the metadata server.. but we'll need to think through that.

> It is necessary to have some knowledge of the platform that a cohort member (ie metadata server, repository proxy, metadata access point) will run in in order to set up the local reposiotry remote connection parameter so I do not think removing the knowledge of the platform from the configuration process is possible.

In order to be able to make deployment decisions, the k8s operator is going to need to be aware of these relationships. We need to be able to define the characteristics to check, requirements to be met. But it needs to make some of those decisions at deployment time, not authoring time, so there has to be an element of late-binding here. It would be ideal if this binding could be done only by processing simple documents

**Comment by davidradl** [comment]
I assume once we do to the MDS approach then we would get the platform names descriptions and server names descriptions from there as well. Could this remove the need for the Tex, Rex, Server Author resource endpoint configuration, if the user is tested then security plugin then this should gate what they are allowed to see. The Server author view service would need the remotePlatform endpoint to call (as it currently has) as well as the MDS endpoint in its config.

**Comment by mandy-chessell** [comment]
> I think you are suggesting that this PlatformServicesClient is not correct and that it should expose calls to return access services, integration services, engine services and view services. I should then use these calls to get the registered services content. Have I understood correctly?

Not quite - the platform service client returns all types of registered services, along with the common servies and governance services.  It is used by dino to show what is running in the server.

Server author has a different remit.  It is ok to use the platform services client to retrieve the information about the platform, however, details of the common/governance services are not relevant to the configuring of servers.  In that use case, information about the platform and the existing services are typically needed in pieces as the administrator is making choices.  For example, extracting all of the registered services at the start may allow the server author code to determine that there are no view services enable so it is not possible to configure a view server on that plaform, so the view server could be disabled on the initial drop-down on the server type to select.  However at this point, the details of the view services are not relevant to the user and are only needed when they choose to configure a view server.  This is why the ability to list the registered view services is in the ViewServerConfigurationClient.  Similarly, the ability to list the registered engine services is in the EngineHostConfigurationClient; listing the registered integration services is in the IntegrationDaemonConfiguration client and listing the registered access services is in the MetadataAccessPointConfigurationClient.

**Comment by davidradl** [comment]
> > I think you are suggesting that this PlatformServicesClient is not correct and that it should expose calls to return access services, integration services, engine services and view services. I should then use these calls to get the registered services content. Have I understood correctly?
> 
> Not quite - the platform service client returns all types of registered services, along with the common servies and governance services. It is used by dino to show what is running in the server.
> 
> Server author has a different remit. It is ok to use the platform services client to retrieve the information about the platform, however, details of the common/governance services are not relevant to the configuring of servers. In that use case, information about the platform and the existing services are typically needed in pieces as the administrator is making choices. For example, extracting all of the registered services at the start may allow the server author code to determine that there are no view services enable so it is not possible to configure a view server on that plaform, so the view server could be disabled on the initial drop-down on the server type to select. However at this point, the details of the view services are not relevant to the user and are only needed when they choose to configure a view server. This is why the ability to list the registered view services is in the ViewServerConfigurationClient. Similarly, the ability to list the registered engine services is in the EngineHostConfigurationClient; listing the registered integration services is in the IntegrationDaemonConfiguration client and listing the registered access services is in the MetadataAccessPointConfigurationClient.

I agree.   I have changed the PlatformServices client in https://github.com/odpi/egeria/pull/5591 (not yet merged) to add new calls to return the registered integration and engine services, so the server author can get the registered services for engine, integration, view and access services - as you suggested. I assume you are ok with this change?

**Comment by davidradl** [comment]
After adding code to return the integration and engine services, I see :
2021-08-16 10:22:34.308 DEBUG 52159 --- [nio-9443-exec-4] o.o.o.c.ffdc.RESTExceptionHandler        : FFDC Response: RegisteredOMAGServicesResponse{services=[RegisteredOMAGService{, serviceName='DigitalService', 
2021-08-16 10:22:34.337 DEBUG 52159 --- [nio-9443-exec-4] o.o.o.c.ffdc.RESTExceptionHandler        : FFDC Response: RegisteredOMAGServicesResponse{services=[RegisteredOMAGService{, serviceName='Governance Action', 
2021-08-16 10:22:34.360 DEBUG 52159 --- [nio-9443-exec-4] o.o.o.c.ffdc.RESTExceptionHandler        : FFDC Response: RegisteredOMAGServicesResponse{services=[RegisteredOMAGService{, serviceName='Files Integrator OMIS', 
2021-08-16 10:22:34.383 DEBUG 52159 --- [nio-9443-exec-4] o.o.o.c.ffdc.RESTExceptionHandler        : FFDC Response: RegisteredOMAGServicesResponse{services=[RegisteredOMAGService{, serviceName='Glossary Author', 

I assume there is some issues around the registering of these specific services - I will investigate each.
