### ISSUE TITLE
JVM crashed while waiting for running brokers

### ISSUE THREAD

**Issue by guptaneeru** [odpi/egeria#5592]
Egeria connector waits for the available Kafka brokers during activation. It reties connecting to Kafka multiple times and spawns new threads in a loop without closing. We noticed that if for some reason kafka brokers are not available, it ends up consuming all the JVM threads and eventually leads to JVM crash. 

We debugged this behavior in 2.8 code base. I see that in master brach the code is different and client is auto closed. Although, it seems like the default close method gives a very large grace period and hence my suspicion is that latest code may not actually resolve this issue. But we have not tested with latest code. 

Opening this issue to see if we there is a way to confirm that issue will be resolved in latest (and which Egeria version) or if we should change the default close behavior with shorter grace period. Any other suggestions?

https://github.com/odpi/egeria/blob/52a1272e3a4f6098808968773f6dcfac664af39c/open-metadata-implementation/adapters/open-connectors/event-bus-connectors/open-metadata-topic-connectors/kafka-open-metadata-topic-connector/src/main/java/org/odpi/openmetadata/adapters/eventbus/topic/kafka/KafkaOpenMetadataTopicConnector.java#L420

**Comment by cmgrote** [comment]
@wbittles any thoughts?

**Comment by planetf1** [comment]
The possible exposure in master appears to be that we create a KafkaAdminClient each time, and I'm unsure what that might mean in terms of threads left running. It would look as if a thread could be created each time, and will hang around for a time period as mentioned. It seems as, assuming the overall design remains,  that we should explicitly close the admin client if the create succeeded to be safe. However I'm not familiar with that code or the kafka api.

**Comment by planetf1** [comment]
kafka code - https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/admin/KafkaAdminClient.java
docs - suggest using close() to remove all resources - https://kafka.apache.org/23/javadoc/?org/apache/kafka/clients/admin/AdminClient.html - and not relying on autoclose?

looks like a bug?

**Comment by guptaneeru** [comment]
Yes @planetf1 Nigel. Thats what I thought too. I will submit a PR.

**Comment by planetf1** [comment]
> Yes @planetf1 Nigel. Thats what I thought too. I will submit a PR.

I'll be interested in other comments but that sounds appropriate to me.

**Comment by guptaneeru** [comment]
Please add me as contributor so that i can submit PR.

**Comment by planetf1** [comment]
Anyone can submit a pr.... no extra provisions needed

**Comment by guptaneeru** [comment]
hmm I tried pushing my changes but it says I dont have access rights. I was able to clone using ssh.

Neerus-MBP:egeria neerju$     git push --set-upstream origin jvm_crash
Enter passphrase for key '/Users/neerju/.ssh/id_rsa': 
ERROR: Permission to odpi/egeria.git denied to guptaneeru.
fatal: Could not read from remote repository.

**Comment by cmgrote** [comment]
Hi @guptaneeru -- you need to fork, clone your fork, push changes to your fork, then create a PR from your fork.  The command you're attempting there is to push a new branch directly to the main repo itself, which indeed we don't allow.

**Comment by planetf1** [comment]
There's some info at https://egeria.odpi.org/open-metadata-resources/open-metadata-tutorials/egeria-dojo/egeria-dojo-day-2-3-contribution-to-egeria.html on the steps for making a contribution.

All developers (including maintainers and admins) follow this process. It's sometimes referred to as the fork and pull workflow, and the principle is to try and follow a common pattern that enables anyone to contribute on equal terms (then we do have a review by maintainers)

If you need some more assistance shout out and I'd be happy to talk you through it. Similarly If you feel we need to improve the docs here please do suggest that - where did you go looking, what did you find, what was missing etc.

**Comment by planetf1** [comment]
Are you planning to make this change? If not let me know and we'll make the change
Do you need some help working through it? If so feel free to ping me on LF AI&Data Slack and I can help you work through the process

**Comment by guptaneeru** [comment]
Thank you @cmgrote and @planetf1. I will try to push PR today. Changes are very small, but this will help me get started.

**Comment by guptaneeru** [comment]
@planetf1 I submitted PR at https://github.com/odpi/egeria/pull/5599/files

**Comment by planetf1** [comment]
I've added some further notes to the PR - one small change I think + you need to get the DCO completed. Comment here or message on slack if you need any help.

**Comment by planetf1** [comment]
The fix above is going in, so will close this issue.

I've tested some combinations of zookeeper/kafka not being available and looked at startup behaviour, though this has not been done in a test framework (there are many interactions coming together).

Please do raise an issue if you think there are further things we need to look at here. cc: @jnhagelberg 
We currently have these open:
 * #5681 - to make it easier to understand whether a server has completed initialization (including connecting to kafka)
 * #5685 - to document the startup behaviour and resolve a few discrepancies
 * #5471 - improve connector status reporting
