### ISSUE TITLE
Missing Javadoc

### ISSUE THREAD

**Issue by CoolKangaroo2022** [odpi/egeria#5595]
Hello! I find in your [Developer Guidelines](https://github.com/odpi/egeria/blob/master/developer-resources/Developer-Guidelines.md#javadoc) that 
> Every Java source file should begin with a header javadoc tag just before the start of the class/interface/enum, which explains the purpose and responsibilities of the code.
> All public methods should have a clear Javadoc header describing the purpose, parameters and results (including exceptions). This includes test cases.

However, I still witness some public classes without Javadocs, e.g.,
* open-metadata-implementation/governance-servers/open-lineage-services/open-lineage-services-api/src/main/java/org/odpi/openmetadata/governanceservers/openlineage/model/LineageVertex.java
* open-metadata-implementation/access-services/subject-area/subject-area-client/src/main/java/org/odpi/openmetadata/accessservices/subjectarea/client/AbstractSubjectArea.java
* open-metadata-implementation/access-services/subject-area/subject-area-client/src/main/java/org/odpi/openmetadata/accessservices/subjectarea/utils/QueryBuilder.java

I also find likely missing Javadoc for public methods in the following files:
* open-metadata-implementation/access-services/subject-area/subject-area-server/src/main/java/org/odpi/openmetadata/accessservices/subjectarea/utilities/SubjectAreaUtils.java
* open-metadata-implementation/adapters/open-connectors/repository-services-connectors/open-metadata-collection-store-connectors/graph-repository-connector/src/main/java/org/odpi/openmetadata/adapters/repositoryservices/graphrepository/repositoryconnector/GraphOMRSMapperUtils.java
......

Would you like to add Javadoc for these methods or classes, or they are just not that important?
If there is anything I can help with?

**Comment by mandy-chessell** [comment]
Please help :)
