### ISSUE TITLE
Introduce more APIs around the audit log destination authoring 

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#5666]
In the admin services there is a call 
```
@PostMapping(path = "/audit-log-destinations/connection")
public VoidResponse addAuditLogDestination
```
 I could introduce update and delete calls  as a rest call and in the admin client. I would then also expose these APIs in the server author view.

 It would then allow the server author user to supply a name and description for their audit log destination - the calling code would map the audit log destination  type (console , default etc) to the appropriate class for the connection. 

As to what to use as the resource identifier:
-there is a Connection open type which extends referencable so it could have a guid. but this is not set in the Connection objects.
      
I see in `ConnectorConfigurationFactory` for example that the connection for console is created like this 
`public Connection getConsoleAuditLogConnection(List<String> supportedSeverities)
    {
        final String destinationName = "Console";

        Connection connection = new Connection();

        connection.setDisplayName(destinationName);
        connection.setConnectorType(getConnectorType(CONSOLE_AUDIT_LOG_STORE_PROVIDER));

        setSupportedAuditLogSeverities(supportedSeverities, connection);

        return connection;
    }`

So even though the connection is a Referencable there is no guid - I assume because it is not persisted in the repository. 

I suggest that the best identifier for me to use in the API would be the display name the server code would only look for this in the CONSOLE_AUDIT_LOG_STORE_PROVIDER type.

**Comment by davidradl** [comment]
@mandy-chessell I would appreciate your thoughts on this approach.

**Comment by mandy-chessell** [comment]
OK to add the extra calls.

On the name - I would have the end user supply the name since they have their own ideas on what the destination's means to them.  The default could be the display name from the connector type but that is not so useful if they set up multiple desintations of the same type.

I do not understand the reference to the open types?  Are you saying that we do not set the GUID of elements in the config - that is true - we did originally but now only set up minimal values to make it easier for people to specify the payloads.
The Connection in the config document is the OCF Connection object.  It does include a guid field if you want to set it.

**Comment by davidradl** [comment]
> OK to add the extra calls.
> 
> On the name - I would have the end user supply the name since they have their own ideas on what the destination's means to them. The default could be the display name from the connector type but that is not so useful if they set up multiple desintations of the same type.
> 
> I do not understand the reference to the open types? Are you saying that we do not set the GUID of elements in the config - that is true - we did originally but now only set up minimal values to make it easier for people to specify the payloads.
> The Connection in the config document is the OCF Connection object. It does include a guid field if you want to set it.

thanks for the quick response :-)  Yes you understand correctly - I was thinking I might have been able to use a guid - but as I found out, and you confirmed, there are no guids in the connection in the config. I will put you as a reviewer on this change.
