### ISSUE TITLE
How to get started with Open Lineage Services, there is no tutorial for lineage 

### ISSUE THREAD

**Issue by MarkizaSckuza** [odpi/egeria#5669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My goal is to write a little demo, where I can create some Apache NiFi flow, or Spark job, or Hive (ideally - in future I need all three of them) and load data lineage to Egeria.

Firstly, I started from manual Egeria installation, but it's tutorial ends, then I tried the Helm chart with Coco lab - but there are no any lineage services presented there.

How can I achieve my goal? Is there any information about lineage that I can use?

Any peace of information is appreciated.

### Expected Behavior

Open Lineage Services tutorial present

### Environment

```markdown
- Egeria: 3.0
- OS: Centos 7.9
- Java: 11
- Browser (for UI issues):
- Additional connectors and integration:
```

**Comment by planetf1** [comment]
@lpalashevski @mstrelchuk can you help with this question?

**Comment by davidradl** [comment]
@MarkizaSckuza my understanding is that we are using the words 'open lineage' to mean 2 things:
1) the open lineage services work with a repository proxy. There is an associated Egeria UI 
2)there is https://github.com/OpenLineage/OpenLineage

Working with Spark or Hive I think you need to take the option 2 approach. This is currently being worked on by the Egeria community, where we are looking to consume operation lineage content from Spark and the like using the open lineage standard. This was talked about in the community call this week. [https://wiki.lfaidata.foundation/display/EG/2021-09-01+CM+-+Using+the+OpenLineage+standard](https://wiki.lfaidata.foundation/display/EG/2021-09-01+CM+-+Using+the+OpenLineage+standard).

**Comment by lpalashevski** [comment]
> @lpalashevski @mstrelchuk can you help with this question?

Creating tutorial and lab for Open Lineage Services is on our backlog and it will be picked up next. I hope to have it available quite soon ideally in the next release. 

However as David stated it is important to distinguish that is will be covering the case (1) where lineage information is fed from Egeria Repository to Open Lineage Services (not via the new LFAI open lineage sandbox project).

**Comment by davidradl** [comment]
@mandy-chessell thanks for pointing out an error in my post. I have now corrected it. The open lineage services work with the Asset Lineage OMAS. They are not restricted to using the repository proxy.

**Comment by mandy-chessell** [comment]
This page on our website shows the different capabilities of lineage https://egeria.odpi.org/open-metadata-publication/website/lineage/

You can see on the left hand side are the different mechanisms for capturing lineage and on the right hand side are the Open Lineage Services for querying and displaying lineage.

For each of your sources of lineage, you need to think about the easiest mechanism to use to capture the information that you want.
* Apache NiFi has lineage services - does it have an API?, could you build an integration connector (running in the Lineage Integrator OMIS in the Integration daemon) to extract lineage from Apache NiFi and push it to Egeria?
* Apache Spark - we are currently working with a new open source project call OpenLineage (that David referenced above) that provides detailed operational tracing of data driven processes.  They have a plug-in for Apache Spark and we are in the process of building an integration connector that integrates OpenLineage events into Egeria.  Once this is in place, it would just be a question of configuing your spark runtime and the integraiton daemon to support it.
* Apache Hive - this is a vitualized database and so the lineage is from the Hive table to the files or other data sources.  It is integrated using an integration connector running in the Database Integrator OMIS in the Integration Daemon.  We may need to extend the Database Integrator OMIS to allow it to link files to the database tables/columns.   Alternatively, if you are using Hive MetaStore (HMS) then we also have a repository connector in progress that would mean the Hive information in HMS would be directly queriable and integrated in Egeria without needing to go through the integration connector.

Happy to go into more detail and help you with the connectors if you like

**Comment by lpalashevski** [comment]
@MarkizaSckuza recently we also published new hand-on lab to demonstrate how you can create design-time lineage using Egeria Data Engine OMAS and Open Lineage Server. You can find it as part of the [labs](https://odpi.github.io/egeria-docs/education/open-metadata-labs/) (or see its content directly here https://github.com/odpi/egeria/blob/master/open-metadata-resources/open-metadata-labs/asset-management-labs/open-lineage.ipynb). The exercise shows simplest use-case to capture design time lineage metadata.... 

You can also watch the youtube video from our webinar series, this November it was about lineage management in Egeria. https://odpi.github.io/egeria-docs/education/previous-webinars/november-2021/

Hope this helps. You can always get in touch via our slack channel.
