### ISSUE TITLE
NPE exception for UPDATED_RELATIONSHIP event coming from IGC repo proxy

### ISSUE THREAD

**Issue by ruxandraRosu** [odpi/egeria#567]
Please find attached the exception stacktrace and events samples

**Comment by ruxandraRosu** [comment]
[exception_updated_relationship.txt](https://github.com/odpi/egeria/files/2768045/exception_updated_relationship.txt)
[updated_relationship.txt](https://github.com/odpi/egeria/files/2768046/updated_relationship.txt)
[updated_relationship1.txt](https://github.com/odpi/egeria/files/2768047/updated_relationship1.txt)
[updated|_relationship2_semnatic_assignment.txt](https://github.com/odpi/egeria/files/2768048/updated._relationship2_semnatic_assignment.txt)

**Comment by cmgrote** [comment]
Just checked on my side, and my relationship events from IGC at the moment are *not* including any update time -- I've just changed that and will add to my other PR #544 shortly.

**Comment by cmgrote** [comment]
Looking at the detail, this example is for a "special" relationship between basically the same entity in IGC...  I'm not sure I'm covering that yet in regard to *any* dates on the relationship.  I'll check what I can do there and push to #544 accordingly...
