### ISSUE TITLE
[BUG] 3 Broken links on "running kubernetes" page

### ISSUE THREAD

**Issue by davidmurrells** [odpi/egeria#5674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://egeria.odpi.org/open-metadata-resources/open-metadata-tutorials/lab-infrastructure-guide/running-kubernetes.html

shows 404 on all three links e.g.

https://odpi.github.io/egeria-charts/site/intro/k8s/

### Expected Behavior

Links to work

### Steps To Reproduce

Navigate to https://odpi.github.io/egeria-charts/site/intro/k8s/
Access any of three hyperlinks

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

**Comment by planetf1** [comment]
Hi, Thanks...
 We are in the process of migrating our docs over to a new repo, as well as adding some new content. Apologies for the current breakage.
 
 The new location starts from https://odpi.github.io/egeria-docs/guides/admin/kubernetes/intro/
 
 I'll update those links to avoid confusion - at some point we'll remove all the content

**Comment by planetf1** [comment]
I've added a PR to direct the links to the new location

I'd be very welcome for your feedback on the new docs also - so please do raise any issues accordingly, ask questions, submit improvements etc. We'll be continuing that (for k8s) in https://github.com/odpi/egeria-docs
