### ISSUE TITLE
Intermittent failures in Data Engine OMAS FVT

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#5687]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Seeing the error below in some environments, building direct from master (3.2-SNAPSHOT - 13 Sep)
```
[INFO] Running org.odpi.openmetadata.accessservices.dataengine.fvt.SoftwareServerCapabilityFVT
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.165 s <<< FAILURE! - in org.odpi.openmetadata.accessservices.dataengine.fvt.SoftwareServerCapabilityFVT
[ERROR] org.odpi.openmetadata.accessservices.dataengine.fvt.SoftwareServerCapabilityFVT.registerExternalTool(String, DataEngineClient, RepositoryService)[1]  Time elapsed: 0.068 s  <<< ERROR!
java.lang.NullPointerException
	at data.engine.fvt@3.2-SNAPSHOT/org.odpi.openmetadata.accessservices.dataengine.fvt.SoftwareServerCapabilityFVT.registerExternalTool(SoftwareServerCapabilityFVT.java:55)

[ERROR] org.odpi.openmetadata.accessservices.dataengine.fvt.SoftwareServerCapabilityFVT.registerExternalTool(String, DataEngineClient, RepositoryService)[2]  Time elapsed: 0.085 s  <<< ERROR!
java.lang.NullPointerException
	at data.engine.fvt@3.2-SNAPSHOT/org.odpi.openmetadata.accessservices.dataengine.fvt.SoftwareServerCapabilityFVT.registerExternalTool(SoftwareServerCapabilityFVT.java:55)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   SoftwareServerCapabilityFVT.registerExternalTool:55 NullPointer
[ERROR]   SoftwareServerCapabilityFVT.registerExternalTool:55 NullPointer
[INFO]
[ERROR] Tests run: 14, Failures: 0, Errors: 2, Skipped: 0
```

The exception appears to occur on
```
        assertEquals(softwareServerCapability.getEngineType(), entity.getProperties().getPropertyValue(DEPLOYED_IMPLEMENTATION_TYPE).valueAsString());
```

### Expected Behavior

Build works correctly

### Steps To Reproduce

trying to establish cause.
The error occurs even after clearing out ~/.m2
Failure is on Ubuntu 20.10

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

**Comment by planetf1** [comment]
Looking at this code segment:
```
tails.get(0);
        assertEquals(softwareServerCapability.getDescription(), entity.getProperties().getPropertyValue(DESCRIPTION).valueAsString());
        assertEquals(softwareServerCapability.getName(), entity.getProperties().getPropertyValue(NAME).valueAsString());
```
Then, this is the failing line (55):
```
        assertEquals(softwareServerCapability.getEngineType(), entity.getProperties().getPropertyValue(DEPLOYED_IMPLEMENTATION_TYPE).valueAsString());
```

From this we can assert
 * softwareServerCapability is not null
 * entity is not null
 * entity.getProperties() is not null
 
 And the most likely cause is trying to do valueAsString on the property         DEPLOYED_IMPLEMENTATION_TYPE which is set to 'deployedImplementationType'
 
 Checking with modified test code we find a null at:
 ```
 assertNotNull(entity.getProperties().getPropertyValue(DEPLOYED_IMPLEMENTATION_TYPE));
 ```
 as expected.

**Comment by planetf1** [comment]
we would expect to find a property 'deployedImplementationType'. However we do not, explaining why the get returns null.

**Comment by lcpopa** [comment]
Will take a look, already in that area

**Comment by lcpopa** [comment]
The instruction was deleted a few days back, but the PR (#5675 ) hasn't been merged yet. Curious as to how it got merged in the first place

**Comment by planetf1** [comment]
That line was added by @mandy-chessell under fd65550f, but I'm not sure why it only affected this environment, not the build environment. that's a concern.

Can you elaborate on the reason for the failure at all? Any idea why it might have worked on my macOS environment, and the build, but not here...

I presume it is to do with the helpers?

**Comment by planetf1** [comment]
I applied the fixes in your draft PR @lcpopa and my FVTs are running fine 
I'll defer to you or Mandy as to whether any further investigation is required, but I'll stop looking at this now on the basis the upcoming PR will address the issue
