### ISSUE TITLE
[Enhancement] User request HTTP header access from SecurityConnector 

### ISSUE THREAD

**Issue by alex231330** [odpi/egeria#5700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently the security connector only allows to manage access by checking userId of incoming request. For some cases this is okay. But now i need to add a little bit more restriction condition for incoming user request - the external group membership information, which is obtained from JWT token in my external application. I think that the best way to pass additional data in HTTP request is a header, so i put group membership inside it. And i faced the issue: there is no way to access any other data except userId from security connector. 

### Expected Behavior

I think a kind of interface to implement or overriding of existence access restriction methods could help to fix this issue. For example, if we will have a request`s header access, we will be able to process a JWT token, which is usually kept inside one 

### Would you be prepared to be assigned this issue to work on?

- [X] I can work on this

**Comment by planetf1** [comment]
The egeria REST api allows a user to be specified for authorization (and this is passed to the security connector) but we do not do authentication, nor - as you suggest - is any other context passed.

Can I check what kind of request you are referring to & the topology here. Is this an interaction with the Egeria UI (polymer), React UI, or core Egeria OMAS/OMRSs?

**Comment by alex231330** [comment]
![arch](https://user-images.githubusercontent.com/16401287/134289561-64831a43-ea1e-4202-8125-b9a59cba7a53.jpg)

This is a short schematic of the my system`s topoligy. So, i already solved the authentification case by using Ldap+Keycloak. In my case, i use several egeria OMAS. As i mentioned above, i would like to manage user access to such actions as editing, deleting, creating and reading. It is easily possible with userId. According to the scheme, i use a JWT token travelling across. The backend parse it and send only useful data to the egeria. As it known, userId is passed in URI. By default there is no way to put any addtitional data to the request, so i decide to put one in HTTP header. But there is no way to get header information in egeia security connector.

**Comment by planetf1** [comment]
It would be useful if the spring controller we use in Egeria populated an additional properties map (or similar) from the http headers (often added to provide more context/security around a request) using the techniques described here : https://www.baeldung.com/spring-rest-http-headers - this could then allow a custom security plugin to use whatever it deemed necessary to authorize a request. However I'm not clear how that might be structured,  and will propose to discuss on a call.

As an alternative could you add an proxy between your backend & egeria. Do you have enough flexibility to take account of your rules there? My guess is that it could be tricky depending on what you are trying to do (for example modifying the response rather than permit/deny)?

**Comment by planetf1** [comment]
Let's keep this open. We've seen multiple requirements in this area

**Comment by planetf1** [comment]
@lpalashevski Sending you this based on our discussions on security.

**Comment by MihaiIliescu** [comment]
We used ThreadLocal and a custom HTTP filter to solve this issue (PR #6793). The headers that will be processed by the filter are set as a comma-separated list in the "header.name.list" application property. Next, the filter saves all predefined headers in the ThreadLocal variable. Doing things this way, ensured headers consistency between different requests (threads). The HttpHeadersThreadLocal class which holds the ThreadLocal is in the http-helper module; therefore this functionality can be used in any module that includes http-helper. PR #6851  is a good example of this, it was created to propagate HTTP headers through federated queries. This is done using the ThreadLocal and by changing the way request headers are built.

**Comment by planetf1** [comment]
This feature went out in 3.11 - I added placeholder text in the release notes. Can you update with something more appropriate? Probably linking to more docs in egeria-docs ?

**Comment by MihaiIliescu** [comment]
@planetf1 yes, I am on it right now.
