### ISSUE TITLE
Add a new FVT for the Glossary Author OMVS

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#5715]
This would be very similar to the Subject Area FVT. There will need to be some scaffolding code when running this in the build so that the view servers are started prior to the test (see https://github.com/odpi/egeria/blob/master/open-metadata-test/open-metadata-fvt/access-services-fvt/subject-area-fvt/build.gradle for how this is done for the subject area omas FVT).

**Comment by odttlnt** [comment]
Hi David, I would like to take a stab at it.

**Comment by davidradl** [comment]
@planetf1 I notice https://github.com/odpi/egeria/blob/master/open-metadata-test/open-metadata-fvt/access-services-fvt/subject-area-fvt/build.gradle . I think to do the glossary author test we need to copy this style so that there are 2 servers started on the platforms. Can I check:
- the task startServer seems to start the java process, which is the platform. 
- I assume we need a startPlatform.
- maybe we autostart the 2 servers we need the view server with the glossary author view configured and the metadata server with at least the subject area omas configured. If so we would need to server configturations that could be picked up.

Have I understood this correctly? @odttlnt does this make sense ?

**Comment by planetf1** [comment]
* The configServer task is launching the groovy scripthttps://github.com/odpi/egeria/blob/master/open-metadata-test/open-metadata-fvt/access-services-fvt/subject-area-fvt/src/test/script/configureStartServer.groovy which is configuring, and starting the servers ontop of the platform
* The startServer ( server in the concept of client application/server process - at odds with our use of server in egeria) task is starting the Platform (a java process) using a gradle plugin which also helps in recording it's pid/shutting it down when needed 
* So no start platform is needed - the previous entry does this
* The config script in first bullet is starting two servers (janus graph + inmem) with as minimal config as possible (just subject area OMAS)

I'm not clear what you need
 * Is a single PLATFORM enough? If so you can leave that as-is
 * Do you need more servers? More OMASs? If so it's the groovy script that needs updating
 
 Note that there is a similar implementation for maven - along the same lines. It too uses the same groovy script, currently both maven+gradle are required.

**Comment by odttlnt** [comment]
Still working on it.
