### ISSUE TITLE
RepositoryContentManager does not seem to setTypeDefSUperTypes correctly

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#573]
The typeDefSuperTypes field of an InstanceType should contain all the supertypes of the type to which the InstanceType relates.
However, the typeDefSuperTypes field is lazily computed but seems to contain only some of the super types.
An example I saw was that Process had a supertype chain including Asset but not including Referenceable.

**Comment by mandy-chessell** [comment]
I think this is fixed now - not seeing problems in instances
