### ISSUE TITLE
[BUG] Subject-Area NPE in request GetGraph

### ISSUE THREAD

**Issue by Inventoroz** [odpi/egeria#5734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A non-existent guide is passed 

GET https://1.2.3.4:9443/servers/server/open-metadata/access-services/subject-area/users/test/nodes/acea7a30-b304-4cf8-97d8-830999cac3ad?nodeFilter=Term&relationshipFilter=HasA&statusFilter=ACTIVE&level=1

200 OK 
{
  "class" : "SubjectAreaOMASAPIResponse",
  "relatedHTTPCode" : 400,
  "exceptionClassName" : "org.odpi.openmetadata.accessservices.subjectarea.server.services.SubjectAreaGraphRESTServices",
  "actionDescription" : "getGraph",
  "exceptionErrorMessage" : "OMAS-SUBJECT-AREA-400-070 An unexpected Exception occurred. The Exception message is Cannot invoke \"org.odpi.openmetadata.repositoryservices.connectors.stores.metadatacollectionstore.properties.instances.InstanceGraph.getRelationships()\" because \"instanceGraph\" is null.",
  "exceptionSystemAction" : "The system encountered an unexpected exception.",
  "exceptionUserAction" : "Review the exception message to assess whether this is a logic error, in which case raise a git issue against Egeria, or a resource constraint - in which case address that issue.",
  "result" : [ ]
}

### Expected Behavior

Either a 404 error that the object was not found should be returned, or an empty Graph object should be returned 

### Steps To Reproduce

Suspecting an error occurs at this point in the code: https://github.com/odpi/egeria/blob/3803e0fa92f8a5df5de3173e087217dd53f05e29/open-metadata-implementation/access-services/subject-area/subject-area-server/src/main/java/org/odpi/openmetadata/accessservices/subjectarea/handlers/SubjectAreaGraphHandler.java#L114

Calling the getRelationships () method results in npe, since retrieved instanceGraph object is null

### Environment

```markdown
- Egeria: 3.0
- OS: CentOS 7
- Java: 11
- Additional connectors and integration: https://github.com/odpi/egeria-connector-xtdb
```

**Comment by davidradl** [comment]
@Inventoroz Thanks - interesting. I have tried recreating (with a local graph repository - janus graph), but I get a 404. With a valid guid with no relationships or an invalid guid. So a few questions:

1) Are you on the latest code in master?
2) What local repository are you using? Does it fail on the other local repositories for you. I would try with  in memory and janus to see if you get different results.
3) what is the type of the node that you are looking for? If it an extension to one of the supported ones?
4) If the Node is a glossary - can you successfully issue  GET https://1.2.3.4:9443/servers/server/open-metadata/access-services/subject-area/users/test/glossaries/acea7a30-b304-4cf8-97d8-830999cac3ad
if it is a Term or a category - replace glossaries with terms or categories in the rest call.

**Comment by Inventoroz** [comment]
1. Release 3.0, but on the latest version this also occurs
2. This situation occurs when using:  https://github.com/odpi/egeria-connector-xtdb
3. Looking for a GlossaryTerm type entity. 
4. The entity does not really exist. The problem is not that it is there, but it is not. I am knowingly requesting a non-existent entity 

This is exactly the error that occurs due to the use of https://github.com/odpi/egeria-connector-xtdb

**Comment by davidradl** [comment]
@Inventoroz thanks for the information. I will have a look.

**Comment by davidradl** [comment]
@Inventoroz I see it looks like the in memory repository returns an empty array but the XTDB one returns null. I want to understand which one is correct - as the omrs should not have different behaviour for different implementations. Do you want to add the protection to the code to check for null in the meantime on that if?

**Comment by Inventoroz** [comment]
Yes, at least add protection from such situations.

**Comment by Inventoroz** [comment]
Let's add such protection, it will not be so important whether the repository returns zero or an object with empty arrays

**Comment by davidradl** [comment]
@Inventoroz  would you like to contribute it - and get a contributor badge :-) ?

**Comment by Inventoroz** [comment]
Yes, I would be grateful. I still have to work with the Egeria for a long time, so this will not be the only fix :)

**Comment by cmgrote** [comment]
> @Inventoroz I see it looks like the in memory repository returns an empty array but the XTDB one returns null. I want to understand which one is correct - as the omrs should not have different behaviour for different implementations. Do you want to add the protection to the code to check for null in the meantime on that if?    

This is a good question -- generally methods all return null rather than an empty collection (list, map, etc), so I'm surprised this one behaves differently. (I prefer returning empty collections to avoid the need for null checks everywhere, but intentionally made everything return null instead as I thought this was what we had decided we should do long ago?)

@mandy-chessell thoughts?

**Comment by Inventoroz** [comment]
It is considered good practice to return empty arrays, collections, maps instead of null

**Comment by cmgrote** [comment]
Here's the original issue I was thinking of #183

I'd be very happy to move to empty collections, but suggest we just need to agree whether to go that route or not.  At the moment it sounds like the behaviour is inconsistent even within a given repository connector -- for example, the `findEntities...` methods all use a `formatEntityResults` helper method which has as its very second condition `if (results.isEmpty()) { return null; }`...

**Comment by mandy-chessell** [comment]
It should be null if there are no contents.   This is what the repository hander is expecting.  It only returns an empty collection to its callers if values were retrieved from the repository but they have all been filtered out (eg through effectivity dating).  This is to tell the caller that they should retrieve the next page.

**Comment by cmgrote** [comment]
As discussed on today's call, this particular method (`getEntityNeighborhood`) for the particular scenario being discussed (the starting entity does not exist) should throw an `EntityNotKnownException` rather than returning an empty object or a null.  In the case where the entity does exist, but has no relationships, the InstanceGraph returned should have just the entity itself and nothing else.

**Comment by Inventoroz** [comment]
> As discussed on today's call, this particular method (`getEntityNeighborhood`) for the particular scenario being discussed (the starting entity does not exist) should throw an `EntityNotKnownException` rather than returning an empty object or a null. In the case where the entity does exist, but has no relationships, the InstanceGraph returned should have just the entity itself and nothing else.

This is also normal behavior. Will the repository now return EntityNotKnownException if the entity does not exist? And perhaps this should be foreseen not only in this request?

**Comment by cmgrote** [comment]
> Will the repository now return EntityNotKnownException if the entity does not exist

Yes, that's actually the documented behaviour of the interface, just that none of our implementations are currently adhering to it -- so they all have a bug that needs to be fixed in this respect.

In general all the other interfaces that start with a given metadata instance (entity or relationship) would also throw this exception (or RelationshipNotKnownException for relationships).  If you find any other instances where they do not behave this way, please raise accordingly as those are likely also bugs! 🙏
