### ISSUE TITLE
[Enhancement] LocalOMRSMetadataCollection validations should not bypass consistency of underlying repositories

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#5786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Many (most?) operations in the `LocalOMRSMetadataCollection` apply validations prior to actually running a write operation against the real metadata collection (underlying repository). For example, `updateEntityClassification`:

1. Retrieves the `EntityDetail` for the entity being classified from the real metadata collection (using `getEntityDetail`).
2. Checks over various aspects of that retrieved entity, including aspects of classifications within it.
3. If these pass, validate that a user is permitted to do the operation via the security verifier / connector.
4. If those all pass, then actually run the operation against the real metadata collection (`updateEntityClassification` in this example).

If the real metadata collection is using an eventual consistency model which it handles itself i.e. across a cluster of servers, then (1) may not behave as expected due to the ordering of operations that are self-managed by the underlying real metadata collection (and whether the given node that (1) happens to run against within that cluster is at the same level of consistency as previous write operations).

If (1) fails, or more problematically returns information about that `EntityDetail` which does not actually accurately reflect the current state of that `EntityDetail`, then the entire set of subsequent validation steps may either fail outright or (worse) proceed and end up risking silently clobbering some other interim update.

This introduces challenges in particular for (3), though, since currently the interfaces for (3) require that a full object (`EntityDetail`) is used for the security verification rather than the simple reference information about the entity (i.e. its GUID) that is received by the `LocalOMRSMetadataCollection` operation itself.

### Expected Behavior

Since the underlying metadata collection is also responsible for validating prior to running its operations, on the one hand _most_ of these validations should be redundant in the `LocalOMRSMetadataCollection`. The exception is the security verification, though, which appears to _only_ exist in the `LocalOMRSMetadataCollection` (it doesn't appear to be part of the base `OMRSMetadataCollection` interfaces).

The hope would be that for a clustered metadata collection that self-manages its own consistency (like XT), we can:

- enforce the consistency model we require directly in the plugin repository connector itself (to ensure that all write operations are appropriately ordered to avoid clobbering per #5707)
- not have this consistency model violated by the validations done at the facade level (`LocalOMRSMetadataCollection`), which may themselves inadvertently prevent valid operations from executing
- still apply the appropriate security verifier / connector constraints against the operations being run

However, to do this, it would seem we will need to:

- allow a `LocalOMRSMetadataCollection` in which validations are switched off (or more accurately, are pushed down to rely entirely on the underlying real metadata collection applying those validations)
- include the application of the security verifier / connector in this push-down (i.e. be able to configure that verifier / connector to be used directly within the real metadata collection rather than the `LocalOMRSMetadataCollection` facade)

### Alternatives

If pushing down the security verifier / connector to run directly in the real metadata collection (the only place where a consistent read operation to retrieve the full `EntityDetail` object against which to validate could be guaranteed in distributed cluster) is not viable, then we may need to resort to either:

- having that security verifier / connector make its decision based on much more limited information (just the GUIDs received by the `LocalOMRSMetadataCollection` interface itself, not the retrieved full object details)
- rely on the underlying repository to apply some kind of "speculative" operation to return back the result of what it would have applied assuming the user is permitted to do so, then based on this returned result from the underlying real metadata collection apply the security verifier / connector in the `LocalOMRSMetadataCollection`, and then assuming it passes push yet another call back to the real metadata collection to actually do the persistence of the speculative work (e.g. something along the lines of a 2-phase commit).

(The latter option seems to me to be very cumbersome, and likely to be very expensive (if even feasible?) for many repositories, while the former seems like it will probably be insufficient -- we won't know just from the GUIDs e.g. what classifications that entity actually possesses, which may be the core drivers to a security decision.)

### Any Further Information?

Based on all of this, it seems like the most robust approach is to ensure that the security verifier / connection can be applied directly within the real metadata collection (?)

### Would you be prepared to be assigned this issue to work on?

- [X] I can work on this

**Comment by mandy-chessell** [comment]
The layer above is doing very similar operations.  For example, if we create an entity, the next operation is often to add a relationship to it which involves retrieving the entity.   There are also security checks going on in the layer above so I am not sure it is possible to push down this problem.

However, I am keen to optimise the calls to the repositories whilst still preventing a rogue repository from corrupting the cohort's metadata.  So it may be work looking at which validations could be removed because the risk is worth the gain?

In the case where a guid is requested but not found, we could add similar logic in the topic listeners that assumes GUIDs are probably (eventually) valid and retry the retrieval a few times after a short sleep.  This does not of course help with the old version of an update being retrieved but could reduce problems seen higher up?
