### ISSUE TITLE
IGC  Repo Proxy - method is not implemented

### ISSUE THREAD

**Issue by ruxandraRosu** [odpi/egeria#580]
In IGCOMRSMetadataCollection an exception is thrown for get/find methods. This is causing 2 issues:
1)If atlas is registered first in cohort, the retrieval on column context works fine. This is done through getEntity and getRelationship calls. However, if igc-repo proxy is registered first in the cohort, this fails with the attached example. 
2)for the creation of information views, even if atlas is registered first, calls to enterpriseConnector - findEntityByProperty throw Exception method not implemented. This means that the metadata is not retrieved from atlas and we end up with duplicated entities for the Information view, each containing one logical table.
Possibly we need to look into the enterprise connector, but as a quick fix, can we rely only on metadata from atlas for now and return nothing from igc for now?

**Comment by ruxandraRosu** [comment]
[error_igc_repo.txt](https://github.com/odpi/egeria/files/2778221/error_igc_repo.txt)

**Comment by cmgrote** [comment]
Hi @ruxandraRosu -- `getEntitySummary` appears to be the method you're after, which should be quite simple for me to add.  (I hadn't prioritised it as it wasn't on the original "must-haves" list.)

It probably makes sense for me to start going through and ensuring that all of the methods are available in `IGCOMRSMetadataCollection`...

One point to be aware of that I've noticed in both Graham's AtlasOMRSMetadataCollection and the IGCOMRSMetadataCollection are that certain parts of certain method are not implemented -- for example, providing a historical date by which to `find...`.  I believe both of us are throwing the "MethodNotImplemented" exception if we receive parameters that we've not implemented: so we may get to a point where it's helpful to also understand what parameters are being used in the method call.

**Comment by ruxandraRosu** [comment]
I am pasting an example of call, I am not using pagination or historical queries, but I am calling using status=ACTIVE 
relationships = enterpriseConnector.getMetadataCollection()
                    .getRelationshipsForEntity(Constants.USER_ID,
                            guid2,
                            relationshipTypeGuid,
                            0,
                            Collections.singletonList(InstanceStatus.ACTIVE),
                            null,
                            null,
                            null,
                            0);

**Comment by cmgrote** [comment]
@grahamwallis -- probably need your thoughts on (2) as well (?)

@ruxandraRosu -- the quick-fix you're suggesting is at enterprise connector level, I assume?  Not sure who looks after that portion and would need to make any update there, but might be worth spending just a day or so seeing if we can't get a "proper" solution before making such other changes...

**Comment by cmgrote** [comment]
> I am pasting an example of call, I am not using pagination or historical queries, but I am calling using status=ACTIVE

Ok, that should be an easy fix from my side as well (I was just checking for non-null, but now I'll allow both non-null and ACTIVE status, since that's all I'll return anyway).

**Comment by ruxandraRosu** [comment]
> @grahamwallis -- probably need your thoughts on (2) as well (?)
> 
> @ruxandraRosu -- the quick-fix you're suggesting is at enterprise connector level, I assume? Not sure who looks after that portion and would need to make any update there, but might be worth spending just a day or so seeing if we can't get a "proper" solution before making such other changes...

The fix I'm suggesting it's on IGCOMRSMetadataCollection - not throwing the exception, just returning null. For enterpriseConnector we need input from Mandy.

**Comment by ruxandraRosu** [comment]
Would you please do the same change for findEntitiesByProperty, getRelationships with matchCriteria?

**Comment by mandy-chessell** [comment]
The repository API has some features that are mandatory and some that are optional.  So it is ok if the Atlas or IGC connector throw FunctionNotSupportedExceptions for optional capabilities that are not in the scope of their respective repositories.  The OMASs should be coded to accept when the repository can not support a particular function.

The list of functions that are mandatory and optional are in the spreadsheet used to design the conformance suite.  See this link https://github.com/odpi/data-governance/blob/master/compliance/repository-compliance/Open%20Metadata%20-%20Repository%20Compliance%20Workbook.xlsx.

**Comment by mandy-chessell** [comment]
In reply to the comment on InstanceStatus setting and whether they should be ignored or not.  This is a bit of additional information.  There are many InstanceStatus values.  

```
    UNKNOWN                 (0,  "<Unknown>",               "Unknown instance status."),
    DRAFT                   (1,  "Draft",                   "The content is incomplete."),
    PREPARED                (2,  "Prepared",                "The content is ready for review."),
    PROPOSED                (3,  "Proposed",                "The content is in review."),
    APPROVED                (4,  "Approved",                "The content is approved."),
    REJECTED                (5,  "Rejected",                "The request or proposal is rejected."),
    APPROVED_CONCEPT        (6,  "Approved concept",        "The request or proposal is approved for development."),
    UNDER_DEVELOPMENT       (7,  "Under development",       "The instance is being developed."),
    DEVELOPMENT_COMPLETE    (8,  "Development complete",    "The development of the instance is complete."),
    APPROVED_FOR_DEPLOYMENT (9,  "Approved for deployment", "The instance is approved for deployment."),
    STANDBY                 (10, "StandBy",                 "The instance is deployed in standby mode."),
    ACTIVE                  (15, "Active",                  "The instance is approved and in use."),
    FAILED                  (20, "Failed",                  "The instance is not in use due to failure."),
    DISABLED                (21, "Disabled",                "The instance is shutdown or disabled."),
    COMPLETE                (22, "Complete",                "The activity associated with the instance is complete."),
    DEPRECATED              (30, "Deprecated",              "The instance is out of date and should not be used."),
    OTHER                   (50, "Other",                   "The instance is in a locally defined state."),
    DELETED (99, "Deleted", "The instance has been deleted and is no longer available.");

```

The only one that is special is DELETED which means that the instance has been soft-deleted.

The OMRSRepositoryConnector should return all instances that don't have a status of DELETED.

Some repositories, such as Atlas, only support 2 status values: ACTIVE and DELETED.  This means its OMRSRepositoryConnector declares it does not support any types that include other status values during the verifyTypeDef loop at start up.   IGC is a little more advanced in that it supports additional statuses for glossary terms - in other words it is able to support the ControlledGlossaryTerm type where as Atlas is not able to.

**Comment by cmgrote** [comment]
> The repository API has some features that are mandatory and some that are optional. So it is ok if the Atlas or IGC connector throw FunctionNotSupportedExceptions for optional capabilities that are not in the scope of their respective repositories. The OMASs should be coded to accept when the repository can not support a particular function.

My fault -- I was throwing `RepositoryErrorException`'s for the `asOfTime`, but now see I should be sending `FunctionNotSupported` (changing that now).

> Would you please do the same change for findEntitiesByProperty, getRelationships with matchCriteria?

@ruxandraRosu not sure what you mean by this: there is no `matchCriteria` on `getRelationshipsForEntity` (?)  For `findEntitiesByProperty` do you mean default `matchCriteria` to eg. `ANY` if it is not provided?

**Comment by ruxandraRosu** [comment]
@mandy-chessell  @cmgrote 
1)The first use case description is not correct, sorry for this. TThe issue is actually for the second part of the flow, the creation of views. The enterprise connector is throwing an exception when IV OMAS is calling addRelationship. This is because in addRelationship implementation there is a call to getEntitySummary. I can handle the exception for get calls, but I cannot handle this exception. Though the entity exists in atlas, it doesn't seem that the enterprise connector gets to call atlas REST, it stops at IGC REST, so when it tries to create the first relationships it fails and the flow stops, with only the first entity created.
2) Because of the exception from IGC proxy when calling findEntitiesByProperty, the enterprise connector is not retrieving any entities from atlas. This means that we end up with duplicated entities(for the first two that are created, representing gaian server/endpoint). Since there is no entity retrieved, I assume that the enterprise connector doesn't get to call atlas REST, but I haven't looked into the code further. Shouldn't the enterprise connector return the result from the other cohort members? 
The scenario of the flow for both points is the following:
- IV OMAS looks for entity matching gaian server
-it gets an exception from enterprise connector. 
-since no entity is retrieved, I've implemented IV OMAS to consider there is no entity for gaiandb so it is creating a new one. The other approach would be to throw the exception, but this would mean no view is created.
-it tries to create the relationship between the 2 entities, it fails(exception at point 1.)
-the flow stops

**Comment by cmgrote** [comment]
So `getEntitySummary` should be there now for (1) in #581 , but I still haven't implemented any write operations (ie. `addRelationship` still isn't there for IGC).  As a mandatory function, it sounds like the enterprise connector should be able to expect it to be implemented, rather than receiving any exception back from IGC? <-- @mandy-chessell correct assumption on my part (in which case for instances that IGC cannot support creating, not sure how to handle)?

For (2) with #581, `findEntitiesByProperty` should now handle the `ACTIVE` status.  Sounded like there might be another gap, though, with some of the other parameters (I'm still not clear which other parameter(s), though)?

**Comment by mandy-chessell** [comment]
Every typeDef has a list of valid instance status values.
A repository must support all of the status values defined for the type.
If it does not support any of the valid status values defined for the type then it should return false to verifyTypeDef.

**Comment by cmgrote** [comment]
> A repository must support all of the status values defined for the type.

So just to check my understanding: for the moment, none of the repositories support `GovernancePolicy`, as it extends from `GovernanceDefinition` which has a number of statuses listed as valid beyond just `ACTIVE` and `DELETED`?

Also, does this mean that a repository that does not support soft-deletes will not verify successfully against *any* TypeDefs (since `DELETED` as a status = soft-delete)?  (Or maybe I'm just misunderstanding the intention of the `verifyTypeDef` -- can a repository still "partially support" a TypeDef even when returning `false` for this method?)

(I'm assuming the default statuses are `ACTIVE` and `DELETED`, as in the OpenMetadataTypesArchive I'm only seeing status lists explicitly set on two objects...)

**Comment by mandy-chessell** [comment]
The in-memory repository supports GovernanceDefinition - but Atlas and IGC do not.
Atlas does not support it because of the status values, IGC does not support the types linked off of it. 

DELETED is a special case - if soft-delete is not supported in the home repository, the instance will never move to that status and the repository can say it supports the type.
When it is storing reference copies of that type, it needs to be able to represent the DELETED status (or just remove the reference copy if that is not possible) when it receives a DELETED event from the remote home repository.

**Comment by cmgrote** [comment]
> DELETED is a special case - if soft-delete is not supported in the home repository, the instance will never move to that status and the repository can say it supports the type.

Ok, sounds good: I'll `DELETED` as that special case =)

**Comment by ruxandraRosu** [comment]
@cmgrote 
I've retested and got the exception attached
Should the exception be RepositoryErrorException or EntityNotKnownException?
@mandy-chessell in EnterpriseOMRSMetadataCollection - addRelationship I can see it calls getSummary for each entity(iterating over the remoteConnectors) and after that it tries to call again getEntitySummary for each entity(iterating again on remoteConnectors). The issue is in the second for. Does it need to create a proxy in all repositories where the entity doesn't exist?

**Comment by ruxandraRosu** [comment]
Pasting the exception as upload doesn't seem to work currently on github issues:
org.odpi.openmetadata.repositoryservices.ffdc.exception.RepositoryErrorException: OMRS-REPOSITORY-404-002 The entity identified with guid "e73fcf64-83c6-4961-ba9a-8191779a02a9" passed on the getEntitySummary call is not known to the open metadata repository igc-event-mapper
        at org.odpi.openmetadata.adapters.repositoryservices.rest.repositoryconnector.OMRSRESTMetadataCollection.detectAndThrowRepositoryErrorException(OMRSRESTMetadataCollection.java:5263) ~[omrs-rest-repository-connector-0.3-SNAPSHOT.jar!/:na]
        at org.odpi.openmetadata.adapters.repositoryservices.rest.repositoryconnector.OMRSRESTMetadataCollection.getEntitySummary(OMRSRESTMetadataCollection.java:1053) ~[omrs-rest-repository-connector-0.3-SNAPSHOT.jar!/:na]
        at org.odpi.openmetadata.repositoryservices.enterprise.repositoryconnector.EnterpriseOMRSMetadataCollection.addRelationship(EnterpriseOMRSMetadataCollection.java:5034) ~[repository-services-implementation-0.3-SNAPSHOT.jar!/:na]
        at org.odpi.openmetadata.accessservices.informationview.contentmanager.EntitiesCreatorHelper.addRelationship(EntitiesCreatorHelper.java:129) ~[information-view-server-0.3-SNAPSHOT.jar!/:na]

**Comment by cmgrote** [comment]
> Based on the code from enterpriseConnector - addRelationship - should the exception be RepositoryErrorException or EntityNotKnownException?

Not sure about the code from enterpriseConnector, but certainly makes sense given the condition and error on IGC's side that this should be `EntityNotKnownException` rather than `RepositoryErrorException`.  Sorry for that -- just fixing and adding to #581 !

**Comment by cmgrote** [comment]
Hi @ruxandraRosu -- I suspect we may have diverged a bit higher-up in the thread: just to check, has this latest merge addressed the original issue (ie. by now raising an `EntityNotKnown` rather than `RepositoryError` exception?

**Comment by ruxandraRosu** [comment]
@cmgrote getSummary call is now throwing org.odpi.openmetadata.repositoryservices.ffdc.exception.EntityNotKnownException

**Comment by cmgrote** [comment]
@ruxandraRosu so OK to close this issue, or something else we still need to do to address the original issue?
