### ISSUE TITLE
[BUG] Incorrect result request in OMAS Subject-Area

### ISSUE THREAD

**Issue by Inventoroz** [odpi/egeria#5803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you run queries. Anything can be substituted for the category guide

https://1.2.3.4:9443/servers/xxx/open-metadata/access-services/subject-area/users/admin/categories/a8883fbd-0707-416f8/categories?sequencingOrder=ANY&startingFrom=0&exactValue=false&ignoreCase=true

https://1.2.3.4:9443/servers/xxx/open-metadata/access-services/subject-area/users/admin/categories/nonsense-not-meaning/terms?sequencingOrder=ANY&startingFrom=0&exactValue=false&ignoreCase=true

Response:
{"class":"SubjectAreaOMASAPIResponse","relatedHTTPCode":200,"result":[]}

### Expected Behavior

And a 404 error should be returned, indicating that the category was not found or does not exist

### Environment

```markdown
- Egeria: 3.0
- OS: CentOS 7
- Java: 11
- Additional connectors and integration: https://github.com/odpi/egeria-connector-xtdb
```

**Comment by davidradl** [comment]
I will include the change to the getEntityNeighbourhood to return entity not known when the supplied guid is not known.

**Comment by davidradl** [comment]
Note this change will not include any change to the xtdb repository connector, which lives in another repository

**Comment by Inventoroz** [comment]
The problem is in these places. 

https://github.com/odpi/egeria/blob/c8f44fafbc6dd629f0d9077ef08739a662283da0/open-metadata-implementation/access-services/subject-area/subject-area-server/src/main/java/org/odpi/openmetadata/accessservices/subjectarea/handlers/SubjectAreaCategoryHandler.java#L517

https://github.com/odpi/egeria/blob/c8f44fafbc6dd629f0d9077ef08739a662283da0/open-metadata-implementation/access-services/subject-area/subject-area-server/src/main/java/org/odpi/openmetadata/accessservices/subjectarea/handlers/SubjectAreaCategoryHandler.java#L594

Here only 200 code is checked, but if suddenly another code, then the method will return SubjectAreaOMASAPIResponse empty
{"class":"SubjectAreaOMASAPIResponse","relatedHTTPCode":200,"result":[]}

**Comment by davidradl** [comment]
the EntityNotFound should end up as an invalidParameterException for the OMAS. Currently I have started prototyping a fix but am getting propertyServerException - which is not correct. I think there need to be more server side logic to make sure the invalid parameter exception is flowed back on the rest call and is thrown from the client OMAS API

**Comment by Inventoroz** [comment]
Is there any movement on the issue?
