### ISSUE TITLE
[BUG] Missing additionalProperties entity GlossaryTerm in OMAS Subject-Area

### ISSUE THREAD

**Issue by Inventoroz** [odpi/egeria#5810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

in Request Object exist additionalProperties
but in Response Object additionalProperties is absent

POST https://1.2.3.4:9443/servers/xxx/open-metadata/access-services/subject-area/users/admin/terms

{
  "class" : "Term",
  "nodeType" : "Term",
  "name" : "Term Test Name 0.5748931709211221",
  "readOnly" : false,
  "additionalProperties" : {
    "today" : "1633689021318"
  },
  "glossary" : {
    "type" : "Glossary",
    "guid" : "5e305954-5aee-4cac-b65b-4eff606860fd"
  },
  "spineObject" : false,
  "spineAttribute" : false,
  "objectIdentifier" : false
}
200 OK 
{
  "class" : "SubjectAreaOMASAPIResponse",
  "relatedHTTPCode" : 200,
  "result" : [ {
    "class" : "Term",
    "nodeType" : "Term",
    "name" : "Term Test Name 0.5748931709211221",
    "qualifiedName" : "Term Test Name 0.5748931709211221@4ab66c39-978d-4d95-a3a6-535ac3cacdfe",
    "systemAttributes" : {
      "status" : "ACTIVE",
      "createdBy" : "admin",
      "createTime" : 1633688996635,
      "version" : 1,
      "guid" : "60a50022-9e71-4d9e-a633-d525dd6440d2"
    },
    "readOnly" : false,
    "glossary" : {
      "type" : "Glossary",
      "name" : "Glossary Test 0.4801305388788021",
      "qualifiedName" : "Glossary Test 0.4801305388788021@c90c4dae-94e6-4b00-8cf1-d12a66fc1401",
      "guid" : "5e305954-5aee-4cac-b65b-4eff606860fd",
      "relationshipguid" : "1a23d392-ae9b-4f41-a2d6-d9ce28420643"
    },
    "spineObject" : false,
    "spineAttribute" : false,
    "objectIdentifier" : false
  } ]
}

### Expected Behavior

in Response Object 

"additionalProperties" : {
    "today" : "1633689021318"
  },

### Steps To Reproduce

Create Term in OMAS Subject-Area with property "additionalProperties"

### Environment

```markdown
- Egeria: 3.2
- OS: CentOS 7
- Java: 11
```

**Comment by Inventoroz** [comment]
Is there any movement on the issue?

**Comment by davidradl** [comment]
@Inventoroz sorry I have not got to this -and am unlikely to get to it near term. Do you want to have a look at it?

**Comment by davidradl** [comment]
@Inventoroz I will try to get to this, this week.
