### ISSUE TITLE
[Enhancement] Clarification on Inheritance Hierarchy for Relational Table

### ISSUE THREAD

**Issue by DaveMurrells** [odpi/egeria#5831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This may be more of a question than an enhancement request.  Relational Table appears Schema Attribute

https://egeria.odpi.org/open-metadata-publication/website/open-metadata-types/0534-Relational-Schemas.html

However the attributes/properties on SchemaAttribute do not appear to be correct for a relational table as they are far more suitable for a RelationalColumn.

I understand that in an inheritance hierarchy pragmatic modelling decisions need to be made but why does a table unwind to a Schema Attribute?   Properties like length,isNullable, min and max cardinality and a significant number of the others do not seem to make sense.

Apologies if I am misreading - note I had to check "I can work on this" to submit but I may simply be misunderstanding something.

### Expected Behavior

Change in type structure

### Alternatives

No

### Any Further Information?

N/A

### Would you be prepared to be assigned this issue to work on?

- [X] I can work on this

**Comment by wbittles** [comment]
Will the Egeria types be described in the future ?

**Comment by mandy-chessell** [comment]
@wbittles which types are your referring to?

All of the open metqdata types are described on the website - https://odpi.github.io/egeria-docs/types/.  However they are defined in the egeria git repository in the open-metadata-types module (https://github.com/odpi/egeria/tree/master/open-metadata-resources/open-metadata-archives/open-metadata-types).  This module is the authoritative source.

Are there types missing from the website?  Are you looking for something different ?

**Comment by wbittles** [comment]
If I take the [Database](https://odpi.github.io/egeria-docs/types/2/0224-Databases/) as a sample, what's missing for me is a description of what the type attributes are trying to capture, so for instance "importedFrom" , "instance" .I know they are optional but it would help clarify things if the intent was clearer.

**Comment by mandy-chessell** [comment]
That makes sense. This documentation is improving over time as different people work with the types but it is down to the priorities that different people have on their contribution as to whether the docs get updated.

There are multiple levels of detail to consider:
-  every attribute has a short description of its meaning in the type definition.  This is the first level of documentation.  These descriptions could be brought up into the overall open metadata types docs if someone wants to take the time to do it.
- as connectors to third party technoloogies are written, the author of these connectors need create a mapping of the terms used in the third party technology to the open metadata types.  This provides documentation of the attributes in context of the third party technology.
- finally as different OMASs consume the open metadata types, their provide the documentation on how these attributes are used in different contexts.

All three pieces contribute to the full description of each attribute.

**Comment by DaveMurrells** [comment]
Thanks.   Just to make sure I respond correctly have

databases - https://egeria-project.org/open-metadata-implementation/integration-services/database-integrator/
events - https://egeria-project.org/open-metadata-implementation/integration-services/topic-integrator/
APIs - https://egeria-project.org/open-metadata-implementation/integration-services/api-integrator/

moved or are they just now available now?  Showing 404 for me as of now

**Comment by mandy-chessell** [comment]
@DaveMurrells the URL `https://egeria-project.org/` is now pointing at a different git repository.  The code is still in the egeria.git repo at the same location  - however the documentation is now at:

databases - https://odpi.github.io/egeria-docs/services/omis/database-integrator/overview/
topics/events - https://odpi.github.io/egeria-docs/services/omis/topic-integrator/overview/
APIs - https://odpi.github.io/egeria-docs/services/omis/api-integrator/overview/

**Comment by planetf1** [comment]
Closing as this is answered
