### ISSUE TITLE
Multiple entities of the same type with the same qualified name are created in atlas

### ISSUE THREAD

**Issue by ruxandraRosu** [odpi/egeria#592]
Multiple entities are created in atlas repository with the same qualifiedName. The qualifiedName should be unique for an entity type

**Comment by cmgrote** [comment]
Agreed: did you have some example payloads to illustrate the duplication?  @grahamwallis ^^

**Comment by ruxandraRosu** [comment]
[entities_with_same_qualified_name.txt](https://github.com/odpi/egeria/files/2782578/entities_with_same_qualified_name.txt)

**Comment by grahamwallis** [comment]
The connector defines the qualifiedName attribute in Atlas as being unique, but It looks to me as if the only place that isUnique actually has an effect is during index creation. We *could* police uniqueness at various levels, one of which would be the metadataCollection - but I am not sure whether that would have too much of a performance impact.

It certainly seems that two entities are being created for the same SoftwareServer, which is a problem in itself. But it is possible that we should be policing uniqueness of values at the receiving repository as well.

**Comment by ruxandraRosu** [comment]
Hi,
These entities are created by IV OMAS through the enterprise connector, meaning that REST calls are issued to both atlas and igc-repo-proxy. Regarding the comment above, there were some WARN messages in atlas about not being able to create the index because OM_Referenceable has too many subtypes. Could this be linked?

**Comment by grahamwallis** [comment]
I doubt that the warning is related - the fundamental issue seems to be that the same software server is being created as two different entities (different GUIDs). Do we know why that is causing the duplication? Should the enterprise connector actually decide on a (single) home repository and create the entity there? 
@mandy-chessell ^^

**Comment by cmgrote** [comment]
Just checking if this is still a problem to be resolved (given the age of the issue it seems potentially stale)?

**Comment by planetf1** [comment]
I think this is defunct now given we are moving away from the atlas fork?

**Comment by cmgrote** [comment]
Closing as stale given move away from Atlas fork and lack of updates over past 6 months.  Please open a new issue on the specific problem related to latest configs (ie. not including Atlas fork), if there is an issue still remaining to be addressed.
