### ISSUE TITLE
[Enhancement] EventSchemaAttribute should be classified as either Key or Value

### ISSUE THREAD

**Issue by juergenhemelt** [odpi/egeria#5928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

According to [Topic Integrator Open Metadata Integration Service (OMIS)](https://odpi.github.io/egeria-docs/services/omis/topic-integrator/overview/) an EventType consists of many EventSchemaAttributes. 
In event-brokers such as Kafka events (or messages) typically are represented as key/value pairs.  

### Expected Behavior

An EventSchemaAttribute should be classified either as EventKey or as EventPayload similar to the classification of a RelationalColumn as PrimaryKey.

### Would you be prepared to be assigned this issue to work on?

- [X] I can work on this

**Comment by davidradl** [comment]
@cmgrote @mandy-chessell 
It seems that for relational databases the primary key is in the payload. In this requirement the key is separate from the payload. I was thinking in order to make this more generic and potentially re usable for other metadata schema use cases. 

1) Adding a classification on the schema attribute to indicate that it is a key. Can we use "Key" ?
2) Adding a classification on the schema type to indicate that all associated schema attributes should not consider the key  part of the payload. Maybe "SeparateKey" classification. When the schema type is embedded in the schema attribute this would also apply to the schema attribute.

@juergenhemelt would this make sense?

**Comment by mandy-chessell** [comment]
What does "payload" mean?  Is this the content of the event?  So when the key is separate, it is sent in a different event?

**Comment by mandy-chessell** [comment]
Key-value pairs are typically modelled using the MapSchemaType.  Is this something different - is it possible to have some examples?

**Comment by mandy-chessell** [comment]
Are we trying to model which attributes are unique identifiers?  If PrimaryKey is the right concept then we could change it so it can be attached to any type of SchemaAttribute.

**Comment by davidradl** [comment]
@mandy-chessell  the way the event schema is structured is something like this:,

event: {
   payload: {....}.
   key: {....}
}

So it is not really related to key value pairs. So calling the classification key is not correct. I am not sure if the primary key is too RDB language or whether it works here too. @mandy-chessell  I agree it would be nice to be able to extend the use of our existing primaryKey classification if it is appropriate @juergenhemelt what do you think would primary key suffice as a name here? 

@juergenhemelt I agree with Mandy examples would be good - are you envisaging this key only at the top level of the event or do you see it used also to identify objects nested further down in the structure  ?

**Comment by juergenhemelt** [comment]
@davidradl @mandy-chessell 
The key of the event is actually not the identifier. It is not even unique. In Kafka the key is usually used as partition criteria, which means that all events with the same key go into the same partition. Hence Kafka can guarantee the correct timely order of events with the same key. Therefore we use the identifier of the entity (or aggregate in DDD slang) which is linked to the event as key. So eventually the key is more of a foreign key than a primary key.
So we should defnitely not misuse the PrimaryKey classification for the key of an event. I think it does make sense, to have a dedicated classification for the key of an event. It also does make sense to have a kind of 'ForeignKey' as a relationship between the EventType and a 'Referencable'.

**Comment by davidradl** [comment]
@juergenhemelt thanks for the clarification - that is really useful.

**Comment by davidradl** [comment]
@juergenhemelt it seems that you use the word key in this context, to indicate that events would go to a particular partition - so enforcing the correct order. As this 'key' is not unique, we would not want to call this a key as it is not really associated with identification.  This is more internal system data or technical data. One way to handle this is to only associate glossary terms with business schema attributes - the other attributes are not exposed. 

Without using glossary terms, we could have a classification called "technical" or "system" just so they are not included in the payload. Would this work for you? @mandy-chessell does this make sense to you?

**Comment by juergenhemelt** [comment]
@davidradl 
Maybe you should treat the "key" of the Kafka message simply as a regular SchemaAttribute with NestedSchemaAttributes of the EventSchemaType and the same with the "value" part of the Kafka message. I would not distinguish between "technical" and "business" attributes because that can vary depending on the particular usage.

**Comment by davidradl** [comment]
@juergenhemelt that sounds fine, if at some future time we need to distinguish between these parts of the event schema, we can look at this again. I will close out this issue - if that is ok with you.
