### ISSUE TITLE
[BUG] UI-Labs search instruction not correct

### ISSUE THREAD

**Issue by tcnt** [odpi/egeria#5933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

According to the instruction you should search for 'csv' in the asset search.
But this will give you a message: No more metadata to fetch for this criteria!

What does work is if you search on a string which is available in the displayName of the 2 loaded assets.
"displayName": "List of patients",
"displayName": "Log of treatments",

So searching for 'of' will show you 2 records.
Searching for patient or treatments shows you 1 record.

Also the screenshots in the notebook are not aligned with the screens as are now shown in the UI

### Expected Behavior

Showing correct result based on the instruction

### Steps To Reproduce

Execute ui-asset-search.ipynb in labs-ui

![image](https://user-images.githubusercontent.com/7771078/142198371-0f8e33b6-47be-427a-8dda-e4b470aed2de.png)

![image](https://user-images.githubusercontent.com/7771078/142198409-cf58fdaf-de7d-49c4-ae0a-f25f0207e008.png)

### Environment

```markdown
- Egeria: 3.4
- OS: Kubernetes
- Java:
- Browser (for UI issues): Chrome
- Additional connectors and integration:
```

**Comment by planetf1** [comment]
@ljupcho @sarbull - refinement of the UI instructions?

**Comment by lpalashevski** [comment]
The UI lab instructions are updated and aligned with the screenshots now (PR https://github.com/odpi/egeria/pull/6057). Thanks for reporting.
