### ISSUE TITLE
[BUG] Change the Subject Area FVT to use logger rather than System.err / System.out 

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#5934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A large amount of output goes to the log, this should not happen by default.

### Expected Behavior

much less content in the output of the FVT and the build bu default

Switch on debug in the logging configuration and then see all the output.

### Steps To Reproduce

run the build

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

### Any Further Information?

This should be reasonably easy to change for a Java developer. By looking in the Subject Area FVT project and defining a logger per class and replacing  System.err and System.out to logger.debug or logger.error as appropriate. 

an example of the usage of stdout is 
[https://github.com/odpi/egeria/blob/master/open-metadata-test/open-metadata-fvt/access-services-fvt/subject-area-fvt/src/main/java/org/odpi/openmetadata/accessservices/subjectarea/fvt/GraphFVT.java](https://github.com/odpi/egeria/blob/master/open-metadata-test/open-metadata-fvt/access-services-fvt/subject-area-fvt/src/main/java/org/odpi/openmetadata/accessservices/subjectarea/fvt/GraphFVT.java)

An example of what should be changed is 
`System.out.println("Create a glossary");`

There is code which produces output to stdout used when prompting for user input. This code should not be changed. 
for example [https://github.com/odpi/egeria/blob/master/open-metadata-test/open-metadata-fvt/access-services-fvt/subject-area-fvt/src/main/java/org/odpi/openmetadata/accessservices/subjectarea/fvt/RunAllFVT.java](https://github.com/odpi/egeria/blob/master/open-metadata-test/open-metadata-fvt/access-services-fvt/subject-area-fvt/src/main/java/org/odpi/openmetadata/accessservices/subjectarea/fvt/RunAllFVT.java)

`public static String getServerName(String[] args) throws IOException
    {
        String name = null;
        if (args.length > 1)
        {
            name = args[1];
        } else
        {
            BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
            System.out.print("Enter a OMAG Server Name. Press enter to get the default (" + FVTConstants.SERVER_NAME1 + ")) :");
            name = br.readLine();
            if (name.equals(""))
            {
                name = FVTConstants.SERVER_NAME1;
            }

        }
        return name;
    }`

Also all of the main methods System.out should not be removed.

**Comment by odttlnt** [comment]
@davidradl I can take a look at this if you haven't started it as yet.

**Comment by odttlnt** [comment]
I made the changes to use a logger. The o/p from the FVT code is reduced , however there is still a bunch of log entries coming from the OMRS like 
[INFO] Fri Feb 04 13:19:51 EST 2022 serverinmem Startup OMRS-AUDIT-0031 The local repository outbound event manager is starting with 1 type definition event consumer(s) and 1 instance event consumer(s)

The default level in the new logback xml has been kept as INFO
