### ISSUE TITLE
Multi architecture docker images (+m1)

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#5935]
Container images are built for Intel architecture x86_64 only
  - egeria (our main distribution)
  - configure (a small utility container)
  - jupyter (standard OOTB + our notebooks)
  
  As noted in https://github.com/odpi/egeria-docs/issues/164 , Apple Silicon based macbooks pose some challenges.
  
  Even when good container and k8s support is complete, emulation can be slow and buggy (and is for now). This means we ideally need multiple architectures supported for our Docker builds.
  
  We already use buildx in the pipelines, which in theory supports multi-arch builds. But we need to look at the overall process, see if we have all the base layers we need (for example the redhat ubi-8 openjdk image could be a problem), as well as test/document
  
  Where a base image isn't available, we may need to either change that base, or have 2 versions - a lighter basic one for dev/tutorial scenarios, and a hardened one for production use cases....
  
  This is a related issue for raspberry pi -> https://github.com/odpi/egeria/issues/2391 (leaving seperate issue open to make it easier to develop that independently/incrementally)

**Comment by tcnt** [comment]
Please have a look at #2391 where I mentioned building the Egeria images for ARM64 architecture is not a problem.
But having a correct supported Kafka version might be an issue for Macbook as it is for Kubernetes on Raspberry PI
