### ISSUE TITLE
New entity missing homeMetadataCollectionId 

### ISSUE THREAD

**Issue by ruxandraRosu** [odpi/egeria#594]
For the new entities pushed by IV OMAS there are some exceptions logged in igc repo proxy:
2019-01-22 10:41:14.582 ERROR 74627 --- [OpenMetadataTopicListener: OMRSTopic.open-metadata.repository-services.cohort.cohort1.OMRSTopic] o.o.o.r.auditlog.OMRSAuditLog            : igc-event-mapper OMRS-AUDIT-9011 An incoming event of type processNewEntityEvent from atlas (82117324-8cfc-48fb-b63e-17226b1e857b) generated an exception with message OMRS-METADATA-COLLECTION-500-004 Null home metadata collection identifier found in metadata instance entity from open metadata repository processNewEntityEvent
This is probably because the event published by atlas is generated based on the POST request to create a new entity from IV OMAS. The entity pushed by IV OMAS has metadataCollectionId="" as IV OMAS has no local repository. 
@mandy-chessell How should it be populated? Is it mandatory to have homeMetadataCollection?

**Comment by cmgrote** [comment]
So it looks like that error message is generated by `validateHomeMetadataGUID` on the repository validator, which is called from the following OMRSMetadataCollection methods:

- `reHomeEntity`
- `reHomeRelationship`
- `purgeEntityReferenceCopy`
- `refreshEntityReferenceCopy`
- `purgeRelationshipReferenceCopy`
- `refreshRelationshipReferenceCopy`

Not sure which of these methods is the one being invoked by a `processNewEntityEvent`, though (?)  The `IGCOMRSMetadataCollection` has only copied these from `OMRSMetadataCollectionBase` for now -- so the base implementation seems to be what's doing this validation...

**Comment by mandy-chessell** [comment]
It is invalid for an incoming NewEntityEvent to have a null home metadata collection Id.
The message described above comes from the method `validateHomeMetadataGUID` in the OMRSRepositoryContentValidator.   In addition to the methods listed above, it is used in processing instances from remote repositories through the `validateReferenceInstanceHeader` method.  I expect this is where the exception is originating from.

**Comment by mandy-chessell** [comment]
I noticed there is a formatting error in the message OMRS-METADATA-COLLECTION-500-004 so I fixed it in PR #618.

**Comment by mandy-chessell** [comment]
The error message seems to be coming from the IGC repository proxy and complaining about an event from Atlas.  Can you see the event payload to determine if it is the inbound event handling that is not unpacking the event correctly, or the sending side that is not adding the home repository id?  The OMRS Event Management component should add the home metadata collection Id into the instance header if the local repository forgot to do it, so the trouble could be either end.

**Comment by cmgrote** [comment]
Just checking if this is still a problem to be resolved (given the age of the issue it seems potentially stale)?

**Comment by cmgrote** [comment]
Closing as stale given no further update in last 6 months -- please re-open if still an issue.
