### ISSUE TITLE
OMVS endpoint log is incomplete & incorrectly reports null

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#6005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

During startup of the view server - with server author, dino, rex, tex all configured, we see:
```
Mon Nov 29 15:07:29 UTC 2021 cocoView1 Startup OMAG-ADMIN-0214 The Server Author Open Metadata View Service (OMVS) is using the following resource endpoints as permitted endpoints: [ResourceEndpointConfig{resourceCategory='Platform', description='Core Platform', platformRootURL=https://lab-core:9443, serverName=null, serverInstanceName=null, platformName=Core}, ResourceEndpointConfig{resourceCategory='Platform', description='DataLake Platform', platformRootURL=https://lab-datalake:9443, serverName=null, serverInstanceName=null, platformName=DataLake}, ResourceEndpointConfig{resourceCategory='Platform', description='Development Platform', platformRootURL=https://lab-dev:9443, serverName=null, serverInstanceName=null, platformName=Development}]
```
In the startup log.

The 'serverName' and 'serverinstanceName' in both of thsese cases is null. This is confusing for the reader. It may be because this is only the platform definition. However if we are logging, then I think we should log the complete configuration including servers. Additionally there isn't any logging of the other OMVSs which is inconsistent.

### Expected Behavior

* Consistently log or remote

### Steps To Reproduce

Startup view server with configured endpoints

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

**Comment by planetf1** [comment]
This is still occuring

**Comment by mandy-chessell** [comment]
This issue is not going to be fixed because we are deprecating the Egeria UI Application where this occurs - see #7924
