### ISSUE TITLE
[BUG] Parameters in class OMRSRepositoryContentManager.processNewAttributeTypeDefEvent maybe need to be updated.

### ISSUE THREAD

**Issue by gnahZ-eH** [odpi/egeria#6022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the class OMRSRepositoryContentManager, here are two methods: **processNewAttributeTypeDefEvent** and **processNewTypeDefEvent**.

I believe that these two methods are similar, one will handle the EntityTypeDef, another will handle AttributeTypeDef.
You can see two lines codes from these two methods: line 2866, and 2677
I believe that the line 2866 in **processNewAttributeTypeDefEvent**, 
```
metadataCollection.addAttributeTypeDef(localServerUserId, attributeTypeDef);
```
the parameter **localServerUserId** should be changed to sourceName, just like line 2677 in **processNewTypeDefEvent**

### Expected Behavior

Class OMRSRepositoryContentManager
line 2866 in **processNewAttributeTypeDefEvent**, 
```
metadataCollection.addAttributeTypeDef(localServerUserId, attributeTypeDef);
```
the parameter **localServerUserId** should be changed to sourceName, just like line 2677 in **processNewTypeDefEvent**

### Would you be prepared to be assigned this issue to work on?

- [X] I can work on this

**Comment by planetf1** [comment]
@mandy-chessell  ?

**Comment by mandy-chessell** [comment]
The processNewAttributeTypeDefEvent is correct in passing the localServerUserId on the first parameter of the call to addAttributeTypeDef().

The processNewTypeDefEvent should be passing localServerUserId as the first parameter of the call to metadataCollection.addTypeDef().  If you look at the definition of the API then the parameter is "userId" and the local metadata collection implementation passes it to the security verifier to check that the user is permitted to add new types.

**Comment by gnahZ-eH** [comment]
![image](https://user-images.githubusercontent.com/17507934/145136345-1fc236c2-8633-4eec-ac66-4390270adfed.png)
![image](https://user-images.githubusercontent.com/17507934/145136493-afbd9422-6070-4274-b3de-9d697888d48c.png)

Do you mean that the first parameter **sourceName** should be changed to **localServerUserId** in the first picture? @mandy-chessell

**Comment by mandy-chessell** [comment]
yes that is right - the first parameter should be the userId.

**Comment by gnahZ-eH** [comment]
> yes that is right - the first parameter should be the userId.

Would you mind that I create a PR to fix it ?

**Comment by mandy-chessell** [comment]
Please do :)
