### ISSUE TITLE
[BUG] Error getting an EventType using the topicIntegratorConnector

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#6027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Attempting to create an EventType gives this error :

PropertyServerException{reportedHTTPCode=500, reportingClassName='org.odpi.openmetadata.commonservices.ffdc.RESTExceptionHandler', reportingActionDescription='getEventTypeByGUID', reportedErrorMessage='OMAG-GENERIC-HANDLERS-500-002 The Data Manager OMAS service has not implemented the getNewBean(entity) method in a subclass of the org.odpi.openmetadata.accessservices.datamanager.converters.EventTypeConverter converter class for bean class org.odpi.openmetadata.accessservices.datamanager.metadataelements.EventTypeElement and so is unable to create the bean for method getEventTypeByGUID', reportedErrorMessageId='OMAG-GENERIC-HANDLERS-500-002', reportedErrorMessageParameters=[Data Manager OMAS, getNewBean(entity), org.odpi.openmetadata.accessservices.datamanager.converters.EventTypeConverter, org.odpi.openmetadata.accessservices.datamanager.metadataelements.EventTypeElement, getEventTypeByGUID], reportedSystemAction='The system is unable to process the request because it is not able to populate the bean.', reportedUserAction='Correct the converter implementation as part of this module.', reportedCaughtException=null, reportedCaughtExceptionClassName='null', relatedProperties=null}
	at org.odpi.openmetadata.commonservices.ffdc.RESTExceptionHandler.throwPropertyServerException(RESTExceptionHandler.java:283)
	at org.odpi.openmetadata.commonservices.ffdc.RESTExceptionHandler.detectAndThrowStandardExceptions(RESTExceptionHandler.java:126)
	at org.odpi.openmetadata.accessservices.datamanager.client.rest.DataManagerRESTClient.callEventTypeGetRESTCall(DataManagerRESTClient.java:1427)
	at org.odpi.openmetadata.accessservices.datamanager.client.EventBrokerClient.getEventTypeByGUID(EventBrokerClient.java:1004)
	at org.odpi.openmetadata.integrationservices.topic.connector.TopicIntegratorContext.getEventTypeByGUID(TopicIntegratorContext.java:524)
	at .....

### Expected Behavior

The error message indicates " has not implemented the getNewBean(entity) method in a subclass of the org.odpi.openmetadata.accessservices.datamanager.converters.EventTypeConverter"

I assume that we need a getNewBean(entity) method  in EventTypeConverter, similar to the method in TopicConverter. 
I also need to ensure that the create processing associated this EventType with the Topic asset as its anchor

### Steps To Reproduce

Create a topicIntegration connector that issues `myContext.createEventType(topicGUID, properties) `

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

**Comment by mandy-chessell** [comment]
This is not the correct fix.  EventType is a schema attribute and so getNewBean(entity) should not be called for a get.

The question is why is the converter called for create ...?   What are the messages/stack trace in the metadata server.

**Comment by davidradl** [comment]
As discussed, the error is actually in get not create.  sorry to mislead you @mandy-chessell .

**Comment by davidradl** [comment]
@mandy-chessell I have the above fix on and can see in the Rex Ui that a topic has an EventTypeList that has an EventType. My integration connector issues a call to the context to get the event-types associated with a topic. This issues an OMAS GET call  https://localhost:9443/servers/cocoMDS1/open-metadata/access-services/data-manager/users/fred/topics/9ebef6c1-4ff8-4161-8331-299fabb141a7/event-types?startFrom=0&pageSize=1000  ,which ends up in the generic handler line 8514.  where is still getting the 'OMAG-GENERIC-HANDLERS-500-002 error as below. This exception is swallowed because the code thinks it is an inaccessibility exception - but it is a real error.  
<img width="1425" alt="Screenshot 2021-12-14 at 22 29 06" src="https://user-images.githubusercontent.com/39792797/146089591-a109272a-6de7-42c9-bed2-7d0d2f04df43.png"> I have not done testing to prove it but this appears to be a regression.
