### ISSUE TITLE
[BUG] Missing nested attribute rest endpoint for data manager omas 

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#6035]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the TopicIntegrationConnector can call the context to getNestedAttributes which ends up calling  data-manager omas rest endpoint `https://localhost:9443/servers/{0}/open-metadata/access-services/data-manager/users/{1}/schema-elements/{2}/nested-attributes.` Unfortunately this end point does not exist.   

### Expected Behavior

the rest endpoint to exist and return any nested attributes associated with the schema- element 

### Steps To Reproduce

start Egeria metadata server with the data manager omas and issue a get rest call in curl or postman `https://localhost:9443/servers/{0}/open-metadata/access-services/data-manager/users/{1}/schema-elements/{2}/nested-attributes` replacing the parameters. The rest call will fail, as the endpoint does not exist  

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

**Comment by mandy-chessell** [comment]
It looks like the endpoint URL should be `https://localhost:9443/servers/{0}/open-metadata/access-services/data-manager/users/{1}/schema-attributes/{2}/nested-attributes`

**Comment by mandy-chessell** [comment]
Actually changed my mind - going to change the server-side to `https://localhost:9443/servers/{0}/open-metadata/access-services/data-manager/users/{1}/schema-elements/{2}/nested-attributes` because the guid that goes in `{2}` can be a schema type or a schema attribute.
