### ISSUE TITLE
bugs in findRelationshipsByProperty and findRelationshipsByPropertyValue

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#604]
bugs in 
findRelationshipsByProperty
findRelationshipsByPropertyValue

the code incorrectly only finds deleted relationships

**Comment by mandy-chessell** [comment]
Which code?

**Comment by cmgrote** [comment]
`InMemoryOMRSMetadataCollection`:

```
if ((relationship.getStatus() == InstanceStatus.DELETED)
```

should be (we think):

```
if ((relationship.getStatus() != InstanceStatus.DELETED)
```

**Comment by mandy-chessell** [comment]
Also noticed similar propblem in findEntitiesByClassification - except that was looking at the statusOnDelete rather than current status.
