### ISSUE TITLE
[BUG] getNestedAttribute is not performing correctly

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#6044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a tree of nested attributes. If I issue the call getNested attributes, I get back all of the schema attributes that are connected to the supplied guid, including the parent. 

### Expected Behavior

I have a tree of nested attributes. If I issue the call getNested attributes, I get back all of the schema attributes that are connected to the supplied guid, excluding the parent. 

### Steps To Reproduce

set up a Topic, EventType and some nested schema attributes. got example nested attributed  A with child B with child C. Issue getNestedAttribute on B, and you expect to see only C in the response not A and C.  

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

### Any Further Information?

In SchemaAttributeHandler method getNestedSchemaAttributes it calls this.getAttachedEntities. There appears to be no relationship end checking.  It should only return children, i.e. connected schema attributes to the nestedAttributes and not the parentAttribute end.

**Comment by mandy-chessell** [comment]
I have extended the SchemaAttributeHandler to pass the end identifier of the relationship that it should navigate.  This means that only children are returned.
