### ISSUE TITLE
[BUG] OMRSRepositoryContentManager returns InstanceType with null validInstanceStatusList

### ISSUE THREAD

**Issue by keytiong** [odpi/egeria#6051]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`OMRSRepositoryContentManager.getInstanceType()` always returns an `InstanceType` with null `validInstanceStatusList`.

### Expected Behavior

`OMRSRepositoryContentManager.getInstanceType()` should return an `InstanceType` with the same `validInstanceStatusList` as the corresponding `TypeDef` .

### Steps To Reproduce

1. Create an instance of `OMRSRepositoryContentManager`
2. Initialize the `OMRSRepositoryContentManager` with OpenMetadata type defs
3. Invoke `OMRSRepositoryContentManager.getInstanceType()`  with any type def name
4. The `InstanceType` returned always has null `validInstanceStatusList`

### Environment

```markdown
- Egeria: 3.3
- OS: Ubuntu 20.04
- Java: 11.0.3
- Browser (for UI issues): N/A
- Additional connectors and integration:
```

### Any Further Information?

The implementation omitted `InstanceType.setValidInstanceTypeList()` when creating an `InstanceType` from `TypeDef` `OMRSRepositoryContentManager.getInstanceType()` 

File: `OMRSRepositoryContentManager.java`

```
public InstanceType getInstanceType() {

     ...
      instanceType = new InstanceType();

      instanceType.setTypeDefCategory(category);
      instanceType.setTypeDefGUID(typeDef.getGUID());
      instanceType.setTypeDefName(typeDef.getName());
      instanceType.setTypeDefVersion(typeDef.getVersion());
      instanceType.setTypeDefDescription(typeDef.getDescription());
      instanceType.setTypeDefDescriptionGUID(typeDef.getDescriptionGUID());
      instanceType.setTypeDefSuperTypes(this.getSuperTypes(sourceName, typeName, methodName));
      instanceType.setValidStatusList(typeDef.getValidInstanceStatusList()); // <-- valild status list was missed out
     ...
}
```

**Comment by davidradl** [comment]
Hi @keytiong are you willing to contribute your suggested change and a unit test along the lines of your suggested recreation steps. I can review and merge for you. One thought -  maybe only issue the setValidStatusList if typeDef.getValidInstanceStatusList() is not null.

**Comment by keytiong** [comment]
@davidradl , I've raised a pull request to fix this bug. Please review.
