### ISSUE TITLE
[Enhancement] Open Lineage Services - janus connector potential improvements

### ISSUE THREAD

**Issue by lpalashevski** [odpi/egeria#6053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Code works fine but can be further improved so we can get it to tech preview:

- Some of the class names are misleading, their purpose changed over time or was moved around in different classes;
- The code in some areas is hard to read; Potentially duplicate and usage of different coding patterns for similar purpose. 
- Need improvement in error/audit logging.

### Expected Behavior

1) GraphFactory can become GraphHelper. Helper class that takes connector parameters and provides:
 - Janus graph instance lifecycle management (open close) for the connector. 
 - GraphTraversal instance for the graph connector. This abstracts the graph deployment options (local/remote)  - connector will always interact using graph traversals interface for executing queries.

2) IndexingFactory can become OpenLineageSchemaHelper. This helper class should be responsible about graph schema initialization and indexing in one single place (the code that was responsible for remote schema management should be moved here)

3) Consolidate querying and transaction management code
 - Check if we can have consolidate the gremlin traversals in single class (i.e. OpenLineageGremlinService) instead of having queries in the connector and additional helper class. (Check pros/cons) 
 - Check if we can have even more unified pattern for transaction management that may cleanup the code. To be discussed with examples.

4) AuditLog - Revise exception handling, consolidate error messages and add AuditLog events for critical operations.

Other suggestions are welcomed.

### Would you be prepared to be assigned this issue to work on?

- [X] I can work on this

**Comment by davidradl** [comment]
@lpalashevski I am not that familiar with this code, but I am curious why we would refactor away from factories. Factories being one of the GoF design patterns, which are usually good practise. Could we not have common code (helper functions) as methods in a parent class if required -that would seem more in line with object orientated design.

**Comment by lpalashevski** [comment]
Fixed with #6223
