### ISSUE TITLE
New Repository - hive metastore

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#6113]
New Repository request

**Name**: egeria-connector-hivemetastore
**Type**: connector
**Language**: Java
**Build tool:** gradle
**Issues**: Yes
**License**: Apache 2.0
**Owner**: @wbittles 
**Admins**: @wbittles, @planetf1 
**Release process**: tbd

Rationale

Work is underway to create an egeria connector to connect to Hive metastore in order to pull metadata for spark jobs.  This is a standalone, optional connector which can be used alongside egeria & is currently in development. The code will follow the usual Egeria standards including being Apache 2.0 licensed

One of the first tasks is to document and breakdown the work through creation of issues (the work on which may include creation of further repositories as needed - but they will be requested here)

See also https://github.com/odpi/egeria-docs/issues/217 which has been opened to document the process for requesting a new repository

**Comment by davidradl** [comment]
@planetf1 I had some questions about the text. "egeria connector to connect to Hive metastore in order to pull metadata for spark jobs". Is the metadata being pulled for spark jobs? I was assuming that the connector only talks to the Hive metastore and has no knowledge of spark jobs. I think the use of the term spark jobs implies that there is something to do with a flow recorded by the connector. I suggest that the flow element of this would come in through open lineage. @wbittles have I understood this correctly?

**Comment by planetf1** [comment]
Spark as in Just a high level description of the use case. Technology wise it's a hive meta store connector

Once there are issues/epics/docs/code in the repo will create a clearer description

**Comment by davidradl** [comment]
ok thanks @planetf1.

**Comment by wbittles** [comment]
@planetf1 Your above summary isn't quite correct , the listener is designed to collect only the metadata generated by spar jobs, which is opposed to all the meta data types supported by the Hive Metatstore , which would be the supper set.

**Comment by planetf1** [comment]
@wbittles understood. We can go either way with the repository naming. hive metastore implies we might broaden the support in future for type mapping (which I hope we could, if required).  I think this is ok since a substantial amount of the work is around infrastructure and connectivity, then there is of course a part which is type mapping -- hive metastore itself possibly containing a large variety of hadoop-oriented metadata

**Comment by planetf1** [comment]
Agreed in dev call 2022-01-11 to go ahead with repository creation

**Comment by planetf1** [comment]
The repository is now available at https://github.com/odpi/egeria-connector-hivemetastore/issues
 - Updated docs issue with notes from going through the creation process
 - The basic license, readme, branch protection rules, DCO, dependabot, codeQL, CODEOWNERS  are setup with sensible defaults

**Comment by planetf1** [comment]
Closing this issue now. Further changes will be documented in the docs issue and for specifics, tracked in that new repo itself. cc: @wbittles
