### ISSUE TITLE
[Enhancement] Add Egeria React UI Dojo content

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#6121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

No dojo content

### Expected Behavior

Add documentation for React Ui for Dojo

### Would you be prepared to be assigned this issue to work on?

- [X] I can work on this

**Comment by planetf1** [comment]
Should this be moved to egeria-docs (possibly closed?)
