### ISSUE TITLE
[BUG] Fix issues with the enhancement issue template

### ISSUE THREAD

**Issue by wbittles** [odpi/egeria#6124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When opening an Issue of type enhancement there are two issues
1) There is a mandatory box to describe the current behaviour 
2) The checkbox with the id: work_on_it is set to mandatory so you can only open an enhancement if your prepared to do the work

### Expected Behavior

Remove the current behaviour text box completely , and reword the next textbox to 
"label: Please describe how this enhancement will improve Egeria"

and secondly make the "work_on_it" checkbox to optional 

### Steps To Reproduce

try to open an Enhancement Issue

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

**Comment by planetf1** [comment]
This has now been merged & the changes look good - thanks
