### ISSUE TITLE
[Enhancement] FVT tests to include mustg ather documentation in case of failure

### ISSUE THREAD

**Issue by wbittles** [odpi/egeria#6132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

currently no console output , or any server diagnostic logs captured if an FVT fails

### Expected Behavior

the PR output should include the relevant diagnostic logs

### Alternatives

Spend weeks diagnosing why a PR has failed.

### Any Further Information?

This should probably be grouped up in an epic along with #6123

### Would you be prepared to be assigned this issue to work on?

- [X] I can work on this

**Comment by planetf1** [comment]
Lots of output is saved from the FVTs - in fact in many cases it's too much.
Console output is kept -- The build logs can be seen at - for example a recent gradle build failure -> https://github.com/odpi/egeria/actions/runs/1718011997

These logs are the stdout/stderr from the results of the commands run during the build, such as gradle or maven.

There are also data files created during a build -- for example 
 - some tests log output to files (and this can be good - to keep top level build simple)
 - distributable code such as archives
 - transient data files, for example the berkelydb in use during a particular FVT
 
 Out of these files only the distributable code is kept - others need to be added as needed
 
 #5290 was opened to track a few suggestions of files to capture - no doubt this list could be extended
 
 In the case of the FVTs, the client log showing test execution is captured in the build report . What isn't is the output from the server-chassis - it is that omission the above issue suggests amongst others.
 
 There are differences between maven and gradle. the former is currently default/definitive, whilst gradle is aspirational/intent for the future,/
 
 Other refactoring may be possible
 
 This may be a dup of #5290 or are there related things to consider whereby it makes sense to have a grouping?
