### ISSUE TITLE
Atlas- findEntitiesByProperty issue

### ISSUE THREAD

**Issue by ruxandraRosu** [odpi/egeria#614]
There is an issue with findEntitiesByProperty as it doesn't return anything anymore. I think the piece of code causing the issue is 
 findEntityByProperty – line
`String matchPropType = matchPropValue.getTypeName();`
Should probably be replaced with
`matchPropValue.getInstancePropertyCategory().getName()`

**Comment by cmgrote** [comment]
@grahamwallis ^^

**Comment by grahamwallis** [comment]
I am not sure I agree.

There are fields in InstancePropertyValue for typeGUID and typeName. Admittedly the type name (and guid) could be derived by looking in the InstancePropertyCategory, but as far as I know a properly formed property value should have the typeGUID and typeName set.

This is an extract from the PrimitivePropertyValueTest class:
    private PrimitivePropertyValue getStringTestObject()
    {
        PrimitivePropertyValue testObject = new PrimitivePropertyValue();

        testObject.setTypeGUID(typeGUID);
        testObject.setTypeName(typeName);
        testObject.setPrimitiveDefCategory(stringCategory);
        testObject.setPrimitiveValue(stringValue);

        return testObject;
    }

The following appears to be how IV OMAS is initialising a PrimitivePropertyValue. Note that is is explicitly setting both these fields to "".

private void createStringPropertyValue(InstanceProperties instanceProperties, String propertyName, String value) {
        PrimitivePropertyValue propertyValue = new PrimitivePropertyValue();
        propertyValue.setPrimitiveDefCategory(PrimitiveDefCategory.OM_PRIMITIVE_TYPE_STRING);
        instanceProperties.setProperty(propertyName, propertyValue);
        propertyValue.setTypeGUID("");
        propertyValue.setTypeName("");
        propertyValue.setPrimitiveValue(value);
    }

I would suggest that the value is not properly initialised.
Please let me know your thoughts.
Thanks
  Graham

**Comment by ruxandraRosu** [comment]
Thanks for spotting this. I am not setting it explicitly to "", I am currently not setting anything for these fields, I thought it should use PrimitiveCategory. The code example above is from test class. I will modify to set it to typeGuid of PrimitiveDefCategory.OM_PRIMITIVE_TYPE_STRING.getGUID() and retest(the same for name).
We will probably need to do the same in OMRSRepositoryHelper as it doesn't set these values explicitly for addStringProperty (or the other methods).

**Comment by ruxandraRosu** [comment]
I've tested with qualifiedName and it works fine after setting typeGuid. There is a use case that it's not working: when searching by qualifiedName and classifications. I am attaching the sample of the entity that exists. The classification is DatabaseServer. Not sure why it is not working, would you please have a look?

**Comment by ruxandraRosu** [comment]
[entity_with_classifications.txt](https://github.com/odpi/egeria/files/2788289/entity_with_classifications.txt)

**Comment by grahamwallis** [comment]
OK - will do - I will spin this up and test it. Thanks for the details.

**Comment by grahamwallis** [comment]
OK - I have been trying to reproduce the behaviour you described but I don't get the same result.
Here is what I have:

I created an entity of type Process with qualifiedName='my-new-process' and classification='Confidence'

If I search (findEntitiesByProperty) using the qualifiedName (only) I get back the entity

If I search again with qualifiedName and typeGUID I get back the entity

If I search again with qualifiedName, typeGUID and classification, I also get back the entity.

My search body on that last call looks like this:
{
	"class":"EntityPropertyFindRequest",
	"offset":0,
	"pageSize":10,
	"typeGUID":"d8f33bd7-afa9-4a11-a8c7-07dcec83c050",
	"limitResultsByClassification":["Confidence"],
	"matchProperties":{
		"class":"InstanceProperties",
		"instanceProperties":{
			"qualifiedName":{
				"class":"PrimitivePropertyValue",
				"instancePropertyCategory":"PRIMITIVE",
				"typeGUID":"b34a64b9-554a-42b1-8f8a-7d5c2339f9c4",
				"typeName":"string",
				"primitiveDefCategory":"OM_PRIMITIVE_TYPE_STRING",
				"primitiveValue":"my-new-process"
				
			}
		},
		"propertyCount":1,
		"propertyNames":["qualifiedName"]
	},
	"matchCriteria":"ALL"
}

The classification filter seems to be working correctly.
Do these tests reflect what you are trying? Or am I doing something different?
All the best
  Graham

**Comment by cmgrote** [comment]
Lots of work has been done in this area since the discussion above -- I'm pretty confident this is stale, so closing -- please re-open if still an issue.
