### ISSUE TITLE
[BUG] Egeria git repo home page does not refer to the the egeria-docs content

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#6147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is no reference to the new docs site in the Egeria home page for this repo 

### Expected Behavior

Expect the users to be pointed to the docs site for a better docs user experience.

### Steps To Reproduce

Expect the users to be pointed to the docs site for a better docs user experience.
https://egeria-project.org/ - follow the link to github - notice there is not a lionk to the new docs site.[https://odpi.github.io/egeria-docs/](https://odpi.github.io/egeria-docs/)

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

**Comment by planetf1** [comment]
Many of the links in that page are outdated. Some are broken links, others land on a page which is a stub to point elsewhere. This includes much of the site content info, webinars etc

The calendar info is correct.

I would be inclined to mostly point to the docs site, including for calendars, webinars, docs etc

Then maybe we can have a 'DEVELOP.md' of similar for any very specific repository content

**Comment by davidradl** [comment]
looks fixed
