### ISSUE TITLE
Publish JavaDoc

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#6148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Please describe the new behavior that that will improve Egeria

As part of egeria build, publish javadoc

Ideally this would be per-release, but it may be just master for simplicity
publish would use github pages, to publish to the *egeria* repository (not egeria-docs)

No fancy formatting likely, just plain, simple javadoc

### Alternatives

Manual run of javadoc & publish to static site

### Any Further Information?

We have day 2 of the dojo coming up, which is going to involve a developer making use of our Java APIs.

Whilst javadoc content is available via maven central, and should be searchable within a compliant IDE like IntelliJ, it would be useful to have a simple web presentation.

I believe we can now use egeria github pages for this purpose, since website content has moved to egeria-docs

Comments: @mandy-chessell @cmgrote @davidradl ?

### Would you be prepared to be assigned this issue to work on?

- [X] I can work on this

**Comment by planetf1** [comment]
Now that the main docs website is sorted, this repository is no longer publishing.

As such, I think it is safe to use to publish code reports/javadoc etc -- using the default domain (github) -- fully integrating into the main website could be a later activity

**Comment by planetf1** [comment]
@mandy-chessell You mentioned you had a favoured filter of which classes to use to cover the 'external' APIs - pretty much the *api and *client modules.

Could you confirm that filter/command you use here - I'm aiming to run that in the build and publish to github pages as we are seeing more requests for API documentation (I had another one today) & this will help with the java case

**Comment by planetf1** [comment]
Added an initial version in #6214 - see notes for caveats.

**Comment by planetf1** [comment]
@mandy-chessell https://odpi.github.io/egeria/ now has our latest javadoc

The PR #6214  posed a few questions about how we refine (path, filtering, branding), but this demonstrates one possible approach.

**Comment by planetf1** [comment]
Some other things to think about
 - What other content might we publish from the codebase. Build reports? Test coverage information? If so, javadoc may need to be pushed down a level in the tree (or 2 with versions)
 - publishing for each release
 ...

**Comment by mandy-chessell** [comment]
I think we are likely to publish other content from the build - eg the swagger and I am thinking that we can generate a messages and codes manual (if you remember such a thing :) from the audit log and exceptions message definition enums.

These are the settings I have - but getting errors in the modules using lombok:
<img width="510" alt="Screenshot 2022-02-09 at 06 58 56" src="https://user-images.githubusercontent.com/12354195/153138748-3f6b10ec-1140-42d6-af4d-98e34d4e6632.png">
<img width="881" alt="Screenshot 2022-02-09 at 07 00 13" src="https://user-images.githubusercontent.com/12354195/153138773-7bd481a4-52f6-4797-aa1b-080851eb7a37.png">

**Comment by planetf1** [comment]
Additional Tasks

- [ ] Move published javadoc to 'javadoc' subdirectory
- [ ] Make publish directory version-specific and publish both from master and branches
- [ ] Update javadoc filter to include 'framework' 
- [ ] Verify lombok'd javadoc is building correctly

**Comment by planetf1** [comment]
@mandy-chessell Thanks for the feedback. Other than the above, did the content at https://odpi.github.io/egeria/ look as you expected? 

Publishing from a single pipeline is easy. Last time (with the k8s charts) I had issues trying to get multiple pipelines publishing, and have a correct index.html for the components - so not sure if I'll manage that refinement this week.. I'll do the filter though.

**Comment by planetf1** [comment]
'data-engine-client' is not generating javadoc (gradle)

```
jonesn:egeria.gradle/ (javadoc) $ cat ~/tmp/javadoc.log | grep data-engine-client                                   [11:40:44]
> Task :open-metadata-implementation:access-services:data-engine:data-engine-client:generateMainEffectiveLombokConfig1
> Task :open-metadata-implementation:access-services:data-engine:data-engine-client:processResources NO-SOURCE
> Task :open-metadata-implementation:access-services:data-engine:data-engine-client:compileJava
> Task :open-metadata-implementation:access-services:data-engine:data-engine-client:classes
> Task :open-metadata-implementation:access-services:data-engine:data-engine-client:jar
> Task :open-metadata-implementation:access-services:data-engine:data-engine-client:delombok
> Task :open-metadata-implementation:access-services:data-engine:data-engine-client:javadoc
> Task :open-metadata-implementation:access-services:data-engine:data-engine-client:javadoc
/Users/jonesn/IdeaProjects/egeria.gradle/open-metadata-implementation/access-services/data-engine/data-engine-client/build/generated/sources/delombok/java/main/org/odpi/openmetadata/accessservices/dataengine/client/DataEngineEventClient.java:64: warning: no comment
/Users/jonesn/IdeaProjects/egeria.gradle/open-metadata-implementation/access-services/data-engine/data-engine-client/build/generated/sources/delombok/java/main/org/odpi/openmetadata/accessservices/dataengine/client/DataEngineEventClient.java:68: warning: no comment
> Task :open-metadata-implementation:access-services:data-engine:data-engine-client:javadoc
/Users/jonesn/IdeaProjects/egeria.gradle/open-metadata-implementation/access-services/data-engine/data-engine-client/build/generated/sources/delombok/java/main/org/odpi/openmetadata/accessservices/dataengine/client/DataEngineRESTClient.java:146: warning: no comment
/Users/jonesn/IdeaProjects/egeria.gradle/open-metadata-implementation/access-services/data-engine/data-engine-client/build/generated/sources/delombok/java/main/org/odpi/openmetadata/accessservices/dataengine/client/DataEngineRESTClient.java:150: warning: no comment
jonesn:egeria.gradle/ (javadoc) $ cat ~/tmp/javadoc.log | grep data-engine-api                                      [11:40:50]
> Task :open-metadata-implementation:access-services:data-engine:data-engine-api:generateMainEffectiveLombokConfig1
> Task :open-metadata-implementation:access-services:data-engine:data-engine-api:processResources NO-SOURCE
> Task :open-metadata-implementation:access-services:data-engine:data-engine-api:compileJava
/Users/jonesn/IdeaProjects/egeria.gradle/open-metadata-implementation/access-services/data-engine/data-engine-api/src/main/java/org/odpi/openmetadata/accessservices/dataengine/ffdc/DataEngineAuditCode.java:83: warning: Not generating getMessageDefinition(): A method with that name already exists
/Users/jonesn/IdeaProjects/egeria.gradle/open-metadata-implementation/access-services/data-engine/data-engine-api/src/main/java/org/odpi/openmetadata/accessservices/dataengine/model/RelationalColumn.java:19: warning: Generating equals/hashCode implementation but without a call to superclass, even though this class does not extend java.lang.Object. If this is intentional, add '@EqualsAndHashCode(callSuper=false)' to your type.
> Task :open-metadata-implementation:access-services:data-engine:data-engine-api:compileJava
> Task :open-metadata-implementation:access-services:data-engine:data-engine-api:classes
> Task :open-metadata-implementation:access-services:data-engine:data-engine-api:jar
> Task :open-metadata-implementation:access-services:data-engine:data-engine-api:delombok
/Users/jonesn/IdeaProjects/egeria.gradle/open-metadata-implementation/access-services/data-engine/data-engine-api/src/main/java/org/odpi/openmetadata/accessservices/dataengine/ffdc/DataEngineAuditCode.java:83: warning: Not generating getMessageDefinition(): A method with that name already exists
/Users/jonesn/IdeaProjects/egeria.gradle/open-metadata-implementation/access-services/data-engine/data-engine-api/src/main/java/org/odpi/openmetadata/accessservices/dataengine/model/RelationalColumn.java:19: warning: Generating equals/hashCode implementation but without a call to superclass, even though this class does not extend java.lang.Object. If this is intentional, add '@EqualsAndHashCode(callSuper=false)' to your type.
> Task :open-metadata-implementation:access-services:data-engine:data-engine-api:javadoc NO-SOURCE
```

**Comment by planetf1** [comment]
Problem observed:

Go to https://odpi.github.io/egeria
In search field (right) enter createAsset
Hit enter on first item
Get a 404 page.

**Comment by mandy-chessell** [comment]
@planetf1 there are a lot of packages missing.  It looks like only packages with "api" and "client" in their name are being picked up.  (The frameworks are not being picked up because the filter includes "framework/" not "frameworks/" It looks like the filter is built from the package names not the contents of the modules.  The set up I have in my IntelliJ works off of the module names - but does not work for the lomboked modules.

If we need to work off of the package names then we will need a much bigger list of package name elements.  

The list below are complete directory names and I think will work with a filter of `include ( "**/XXX/*.java" )`
* api
* client
* properties
* metadataelements
* metadataelement
* events
* ffdc
* configuration
* store
* connectors
* connector
* frameworks
* context
* graph
* model
* auditlog
* omrstopic
* openmetadatatopic
* archivestore
* auditlogstore
* cohortregistrystore
* repositoryconnector
* repositoryeventmapper
* metadatacollectionstore
* metadatacollectionstore/utilities
* archiveutilities
* clients

**Comment by planetf1** [comment]
The current implementation is in the `javadoc {}` section in build.gradle. It uses this plugin for aggregate javadoc - https://plugins.gradle.org/plugin/io.freefair.aggregate-javadoc. This in turn uses the standard javadoc plugin as far as I know.

Docs on this at https://docs.gradle.org/current/dsl/org.gradle.api.tasks.javadoc.Javadoc.html
The include/exclude options are based around file names/paths rather than packages

So I think we need to do one of
 * Compose the correct include/exclude purely based on filenames
 * Use a different tool to generate javadoc - external etc (ie for the aggregaate but we still need to do in build for the per-component javadoc due to maven central rules)
 * Figure out how to write appropriate groovy to build a list of files based on a set of classname patterns
 * Somehow add some annotations to different modules which can define them to be internal vs external (or encapsulate matching logic here) & use in above
 * Generate all javadoc & capture info on the internal/external usage within the content
 
 None are probably entirely trivial

**Comment by planetf1** [comment]
I'll try with that list.
