### ISSUE TITLE
[BUG] Broken links in swagger docs

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#6158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The following sections have broken links from generated swagger UI at /swagger-ui.html

* Administration Services - Operational
* Catalog Integrator OMIS
* Conformance Suite
* Dino OMVS
* Glossary View OMAS
* Platform Services
* Search Integrator OMIS

### Expected Behavior

Links should be correct

### Steps To Reproduce

go to swagger endpoint and view

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

**Comment by mandy-chessell** [comment]
@planetf1 Which links are bad? the same list as at the top of this issue?

**Comment by mandy-chessell** [comment]
I had a look at the code and although the URL for `Administration Services - Operational` is coded correctly, the swagger parser is mangling it.  I have changed it to not refer to a section within the operations guide.

**Comment by planetf1** [comment]
Very minor, but we might get a minor improvement with the long labels -> https://github.com/odpi/egeria/issues/6158#issuecomment-1081713323

**Comment by planetf1** [comment]
I checked the swagger docs as part of 3.9 testing and raised more specific issues for any remaining problems
