### ISSUE TITLE
Centralise all Postman sample scripts

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#617]
Based on the headache we came across in trying to re-use Postman scripts that we'd each configured with slightly different environment variable names, this issue is to suggest that we centralise all Postman scripts and create consistency in how we refer to the variables within them.

Suggestion is to follow the base set of samples already available under `open-metadata-resources/open-metadata-samples/postman-rest-samples`.

1. Place any Postman sample scripts of your own as a new collection under the `collection` subdirectory.
1. Ensure that your scripts use the same base variables as the others, namely:

   - `baseURL` the base URL of the Egeria admin services, eg. `https://localhost:8080`
   - `user` the Egeria user, as embedded in most Egeria REST calls
   - `server` the name of the Egeria server, as embedded in most Egeria REST calls
   - `cohort` the name of the Egeria cohort, used as part of the Kafka topic name for OMRS
   - `kafkaep` the Kafka endpoint for the cohort, eg. `localhost:9092`

1. Ensure that if your scripts require any additional variables, you also include a new environment under the `environment` subdirectory, along with a Markdown file explaining the additional variables. (For variables that overlap with other collections, again, be sure to follow the same variable naming.)

**Comment by mandy-chessell** [comment]
I think it is a great idea to have consistency in our naming of variables - we should document the common valriable names in the developer resources.  

However a central place for the postman scripts could make them difficult to find.  We are going to want different postman scripts for different audiences - eg end user of an OMAS verses an administrator verses a tutorial verses a sample ... The audience will determine how the postman script is organized and the comments within it.   I would favour keeping them with the resources that provide context to the postman script itself.

**Comment by cmgrote** [comment]
> However a central place for the postman scripts could make them difficult to find. We are going to want different postman scripts for different audiences - eg end user of an OMAS verses an administrator verses a tutorial verses a sample ... The audience will determine how the postman script is organized and the comments within it. I would favour keeping them with the resources that provide context to the postman script itself.

I was thinking of still linking to them from those other areas' README's -- but I was thinking that by having all of them in one place it also makes it easy for developers to "know where to go" to get them, without having to dig deep into different parts of the code hierarchy (?)  Particularly if they just want to test out some portion of a service to get familiar with it, without first needing to figure out where it happens to be buried in the code hierarchy...

**Comment by mandy-chessell** [comment]
We need to think about what we mean by "developer".  Is this an Egeria developer interested in debugging Egeria code - or a developer wanting to use one of the OMASs.  These are different people needing different postman scripts.  Could be confusing if they are all together - they may get the wrong one.  If they need the appropriate README to get the right one then it may be easier to have the postman scripts with the rest of the material they are using.

**Comment by cmgrote** [comment]
Updated samples have been merged, here: https://github.com/odpi/egeria/tree/master/open-metadata-resources/open-metadata-samples/postman-rest-samples

And updated instructions for developers, here: https://github.com/odpi/egeria/blob/master/developer-resources/Postman-Samples.md

(Approach is to provide a centralised linking point under `open-metadata-resources/open-metadata-samples/postman-rest-samples`, but to allow the actual collections themselves to exist wherever is most appropriate for their use.  Furthermore, _all_ samples should make use of the same environment file -- if they need extra variables, those should be added to the single environment definition under `open-metadata-resources/open-metadata-samples/postman-rest-samples/`)
