### ISSUE TITLE
[BUG] Fork executing Github Worklflows

### ISSUE THREAD

**Issue by odttlnt** [odpi/egeria#6208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a fork/master is updated with Upstream. It triggers off github flows on the fork. It ultimately ends with an error 
` Error:  The goal you specified requires a project to execute but there is no POM in this directory (/home/runner/work/egeria/egeria). Please verify you invoked Maven from the correct directory. -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
Error: Process completed with exit code 1.`

### Expected Behavior

Activity on Forks should not be triggering any GitHub workflows

### Steps To Reproduce

On a fork/master update code from upstream. This will trigger off the workflows

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

**Comment by planetf1** [comment]
I think this is the problem. 

There is a condition 
```if: ${{ github.event_name == 'push' && github.repository == 'odpi/egeria' }}
```

. Great right? Well it would be if it was done at the right scope.....

I’m pretty sure this was at the JOB scope — so it would stop that build from running in your fork.
However right now it is at STEP scope — the step that checks out the code
So it runs, and doesn’t have any source 

We have done a little refactoring for docker, java changes, so probably did this in error and noone noticed
Though looking at git blame it’s been there for ages. Though steps were changed in oct for arm64. I vaguely remember having some issue with the job scope, so likely each step had this condition attached… except the new/modified ones

Will investigate & fix

**Comment by planetf1** [comment]
corrected. - the text was there, just a bad quote :-)

**Comment by planetf1** [comment]
an additional check has been added on all actions at the task level, to ensure it only runs under the odpi org
