### ISSUE TITLE
[Enhancement] Add create controlled term api to subject area omas 

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#6217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Please describe the new behavior that that will improve Egeria

allow glossary terms to be used in a workflow. this means enhancing the subject area omas to
- expose a create controlled terms API
- expose a change status for the controlled term to allow it to move through different status's  

### Would you be prepared to be assigned this issue to work on?

- [X] I can work on this

**Comment by mandy-chessell** [comment]
Also need to return the instance status when elements are retrieved and the type name of the element so caller can distinguish the controlled glossary terms from the ordinary ones.

**Comment by davidradl** [comment]
@mandy-chessell thanks for you feedback. The SubjectArea OMAS already has a parent object called node that has the typename and a NodeType. I was thinking that the nodeType would be everything we know about that I could paint on the canvas. currently I have Activity -> Term -> GovernedNode -> Node. I am thinking of having a ControlledActivity -> Activity and a ControlledTerm-> Term as new NodeTypes which could have their own icon. The alternative is conditional code around the nodetype to look at whether the object is controlled or not.
