### ISSUE TITLE
Q: Can a cohort have repositories with different levels of constraint/enforcement?

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#622]
We've just been doing some testing of the k8s environment and brought up a cohort with an OMAG Server with an in-memory repository and an Atlas server. (This works very well, and correctly propagates entity instances - provided they are 'well-formed' in the eyes of all members of the cohort). This question relates to an instance that is 'not well-formed'.

It was possible, on the OMAG Server, to create an entity of type Database that did not have values for the 'qualifiedName' and 'name' attributes. The creation in the local (in-mem) repository succeeds and propagates an OMRS 'new entity event' to the rest of the cohort. The absence of the attributes is not policed by the in-memory repository.
 
On arrival of the OMRS Event at the Atlas server, an entity reference copy should be created. But this fails due to the missing attributes. The 'qualifiedName' attribute is mandatory in the Egeria Referenceable type definitions, so in principle this should be enforceable anywhere in the cohort and this is possibly just something we should tighten up in the in-mem repository. The 'name' attribute is more subtle; since Database is a subtype of Asset, and in Atlas this is OM_Asset and is a subtype of Asset. In the Atlas Asset type, 'name' is defined as mandatory - which is why the saveEntityReferenceCopy is bounced. This would not be enforced elsewhere in the cohort - ince 'name' is not mandatory in the Egeria type. It would only be a problem on arrival of the OMRS at the Atlas server.

I have two questions:

Do we need to ensure that the Egeria F5 types are strict sub-types of their Atlas counterparts - i.e. that Asset.name is mandatory?

If not, and there is a difference of strictness that means a repository in the cohort decides it cannot save an entity or relationship instance, is this an issue? Or is something that just needs to be audit-logged and trigger a compensating workflow?

**Comment by mandy-chessell** [comment]
Going to close as I think this is all sorted now.
