### ISSUE TITLE
[Enhancement] Add a property to a connection object to allow seeding of the QualifiedName and GUID fields. 

### ISSUE THREAD

**Issue by wbittles** [odpi/egeria#6222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Please describe the new behavior that that will improve Egeria

In some environments  it's difficult for connector developers to generate GUID's and Qualified Names for top level entities such databases. The idea is to allow an extra property to a connection object that would allow a user to set the base of any qualified names and GUID's generated. 

### Would you be prepared to be assigned this issue to work on?

- [X] I can work on this

**Comment by mandy-chessell** [comment]
The is the purpose of the `configurationProperties` in the Connection object.  This is a map of property names to values.  It is set up by the administrator when the connector is configured.

The ConnectorType that links off of the connection and is returned by the connecotr's ConnectorProvider class has the `recognizedConfigurationProperties` property.  This is a list of the names of properties that the developer of the connector expects the administrator to set up in the connection object.
 
Many of the integration connectors and governance action services in egeria.git use the confiration properties if you are looking for examples.

**Comment by wbittles** [comment]
We do need to add support for this to the existing integration daemon connectors.
should we move this issue , or just  open a new one on the connector repo.
