### ISSUE TITLE
[BUG] Enable all access services - Asset Lineage OMAS service NPE

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#6229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Metadata server will not start due to a NPE in Asset Lineage OMAS service

Consistently getting the following exception when configuring a test environment: (scripted from a empty 'data' dir)

 - Event bus configured
  - local graph repo
  - cohort member
  - All access services enabled
  - start server

Code: Master (head 4c26396c137f8466337fed208020bfe7628679f8 ) - current as of 2022-02-21 1300
```
{"class":"SuccessMessageResponse","relatedHTTPCode":500,"exceptionClassName":"org.odpi.openmetadata.adminservices.ffdc.exception.OMAGConfigurationErrorException","exceptionCausedBy":"java.lang.NullPointerException","actionDescription":"initialize","exceptionErrorMessage":"OMAG-ADMIN-500-004 The Asset Lineage OMAS service detected an unexpected java.lang.NullPointerException exception with message Cannot invoke \"java.util.Map.get(Object)\" because \"accessServiceOptions\" is null during initialization","exceptionErrorMessageId":"OMAG-ADMIN-500-004","exceptionErrorMessageParameters":["Asset Lineage OMAS","java.lang.NullPointerException","Cannot invoke \"java.util.Map.get(Object)\" because \"accessServiceOptions\" is null"],"exceptionSystemAction":"The system is unable to start the service in the OMAG server.","exceptionUserAction":"This is likely to be either an operational or logic error. Look for other errors in the audit log.  Validate the request.  If you are stuck, raise an issue."}
```

No access service settings have been configured for asset lineage omas - since the 'enable all access services' option has been chosen.

### Expected Behavior

* Server should start normally
* At worst, asset lineage should log a warning that it cannot start with default parameters, but should not prevent startup of other access servers - since if it does, the 'enable all access services' call is not very useful

Workaround (to be tested) is to enable minimal access services specifically

### Steps To Reproduce

see above

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

### Any Further Information?

none

**Comment by planetf1** [comment]
FAO @lpalashevski @mandy-chessell

**Comment by planetf1** [comment]
This also breaks the 'egeria-base' helm chart, and the Egeria Dojos - HOWEVER the docs guide the user to run 'released' versions, which are still ok. This will be an issue for the 3.6 release however (or can be tested now by adding `--devel` to the chart install)

**Comment by planetf1** [comment]
This regression is likely to have been introduced in ~ last 10 days

**Comment by davidradl** [comment]
I assume that supportedZones is mandatory for the current processing- and it is not being supplied. I guess there are options 
- fail start all access services if we cannot start any of the access services because a mandatory option has not been specified
- remove start all access services API 
- supply enough parameters to start all access services - but only have the ability to specify one option for all the access services - this is what the server author ui does.
- all the lineage service to start but not be usable until its mandatory options have been supplied. Is it really started in this case?

**Comment by planetf1** [comment]
This also affects the coco pharma labs
```
                Starting server cocoMDS2 ...
                   ...cocoMDS2 failed to start
                       error message is: OMAG-ADMIN-500-004 The Asset Lineage OMAS service detected an unexpected java.lang.NullPointerException exception with message null during initialization
```
