### ISSUE TITLE
Add 3 new contributors

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#6237]

**Comment by planetf1** [comment]
@davidradl Please provide the *github id* of each of the three members.
I'll also propose a new template/doc update to document the process [(see https://egeria-project.org/guides/project-operations/#contributors for](https://github.com/odpi/egeria-docs/issues/347)

**Comment by planetf1** [comment]
I see from CONTRIBUTORS.md you added
```
| Federica Donald | federica.donald@ibm.com |
| Adinarayana Harida | adharida@in.ibm.com |
| Sachin Naik |  sachin.naik@ibm.com |
```
which seems to be:
@fedtried
@adinhtdsibm
@odttlnt

I have added these under https://github.com/odpi -> Teams -> Egeria Contributors
This group has 'read' access for egeria, as can be seen under
https://github.com/odpi/egeria/settings/access-> where it can be seen that this team has the role 'read'


This may not be the case for all repos (I'd need to check through them).  A quick look suggests it's done for the old ones, not the latest

I also think any 'member' (and usually this won't happen until they are a contributor) can ask for more access, but we should generally do that through the process that you linked, but which is incomplete -- so will be improved in the referenced issue

**Comment by planetf1** [comment]
Note I think the user in question may receive an invite to the org, if not already a member. Any problems post back here.
