### ISSUE TITLE
Move IGC user/password to k8s secret

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#626]
Currently the igc user/pasword is stored in values.yaml of the vdc chart and must be manually edited before deployment as needed

User/passwords should be managed using kubernetes secrets.

**Comment by planetf1** [comment]
Also ensure the endpoint address is appropriately configurable ie at helm install command line, or maybe as part of secret setup.

**Comment by cmgrote** [comment]
We should be able to drop the need for these host details and credentials for IGC entirely from the charts once I've de-coupled the data deployment piece (the IGC deployment piece is either completely external, via Ansible playbook I'll update, or is embedded inside an IGC container that you can execute via `kubectl exec` against the running container: no SSH or credentials needed)

**Comment by planetf1** [comment]
In the case where we deploy IGC within the container we may still want properties for the userid/pass to use - though it may be hardcoded initially... albeit that is a slightly different requirement.

**Comment by cmgrote** [comment]
Only credential left is the `auth` needed for IGC Proxy -- there is no SSH access to the IGC container (if using); for external environments, we'll leave it up to however folks want to manage that environment rather than try to orchestrate something from inside the k8s cluster towards an external resource.

**Comment by planetf1** [comment]
Yes agree - was never comfortable with the outward ssh, but it was a necessary step en route to a better solution
