### ISSUE TITLE
Updated managed fork

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#630]
Just a heads-up that I have pushed my latest updates to the managed fork.
These changes include:

- addEntity with initialClassifications - fix for subtype checking and creation of InstanceType

- save*ReferenceCopy() methods now perform rigorous enforcement of fields in supplied instances (missing system attributes were causing NPEs in Atlas).

- purge*ReferenceCopy() methods no longer insist that the instance has already been deleted

- purgeEntity() will also purge any relationships attached to entity

- saveEntityReferenceCopy() will inject values for attributes that are mandatory in Atlas (but not in Egeria)

Ran full CTS suite cleanly.

Please let me know if you have any problems or questions.

@planetf1 @ruxandraRosu @cmgrote @bogdan-sava @mandy-chessell ^^

**Comment by grahamwallis** [comment]
Fresh update as of today.

This update makes the following changes:

- fixes the missing metadataCollectionId from generated instance events

- adds findRelationshipByProperty and findRelationshipByPropertyValue (these support all MatchCriteria but string matchProperties and searchCriteria must currently be exact match (not substrings)

- OMRSEventMapper resilience change - should recover following loss of Kafka connection

Ran full CTS suite cleanly.

Please let me know if you have any problems or questions.

@planetf1 @ruxandraRosu @cmgrote @bogdan-sava @mandy-chessell ^^

**Comment by grahamwallis** [comment]
Fresh update as of today.

This update makes the following changes:

* fixes the additionalProperties property value issue
* enables search by properties with values containing special characters
* fixes the endpoint address reported in the registration event

Please let me know if you have any problems or questions.

@planetf1 @ruxandraRosu @cmgrote @bogdan-sava @mandy-chessell ^^

**Comment by planetf1** [comment]
Can we have the Egeria dependency updated to 1.1-SNAPSHOT please?

**Comment by grahamwallis** [comment]
Done :-)

**Comment by planetf1** [comment]
Might be worth closing this now?
