### ISSUE TITLE
Log exceptions / stack traces in OMRSRepositoryContentManager

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#632]
I see there are lots of "TODO" items at the bottom of `OMRSRepositoryContentManager` to add error messages -- as a starting point can we simply print stack traces rather than swallowing the exceptions?

Would have saved me a lot of time seeing and then tracking down a buried NPE 😉

**Comment by mandy-chessell** [comment]
I would suggest the effort to output a stack trace is just as much as outputting a proper message.

**Comment by cmgrote** [comment]
I think part of it was that for a fair number of the exceptions being caught, the logging was done by concatenating the `Throwable` with the rest of the message, rather than passing it as a `Throwable` argument to the `log.error` method.

Commit merged as part of PR above addresses this by passing as argument rather than concatenating.
