### ISSUE TITLE
Document how to avoid ssl certificate validation errors for IGC connector

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#634]
I got a HTTP 500 error returned when starting the omag server instance after configuring the IGC connector. It turned out the underlaying error was:

`I/O error on POST request for “https://158.176.66.119:9446/ibm/iis/igc-rest/v1/search”: java.security.cert.CertificateException: No subject alternative names matching IP address 158.176.66.119 found **`

As posted (by me) to slack.. the answer is:

A tip relating to spring boot. See https://stackoverflow.com/questions/35531661/using-env-variable-in-spring-boots-application-properties which has a comment stating:

> I wanted to add to this and mention that if you are using spring boot(didn't check if it works without boot), then any property can be overriden via an environment variable automatically without modifying your application.properties. ie, if you have a property called spring.activemq.broker-url then the corresponding environment variable would be: SPRING_ACTIVEMQ_BROKER_URL. periods and dashes are automatically converted to underscores. This is extremely convenient when working with containers/spring boot.

So Spring boot makes it easy to set an application property in the environment (this is quite k8s/docker friendly). Since I hit an issue with the IGC connector failing with certificate validation (as my IGC uses a self-signed cert & ip address not signed+ name) I added:

`STRICT_SSL=false
`
In the environment was enough to then allow OMAG Application to work ok, and the igc connector to happily connect to a server with a bad cert!

You’ll notice this in the startup debug messages if set:
`2019-01-25 10:24:31.870  WARN 28359 --- [           main] org.odpi.openmetadata.http.HttpHelper    : Strict SSL is set to false! Invalid certificates will be accepted for connection!`

Not good for production.

Other alternatives include updating application.properties. This could be added into classpath at runtime also, but environment is a good fit for docker/k8s.

We may want a first class config option to set this. Open for consideration as to best way to handle

FAO @cmgrote

**Comment by cmgrote** [comment]
I suspect this is broader than just IGC?  Any of the endpoints we try to connect to via Spring will presumably either need to have a proper certificate, be accessed through the use of a custom certificate authority, or will run into the same problem...  We likely need to think about documenting how to setup certificate stores / authorities in general: in my experience most systems sitting inside a firewall end up using self-signed certificates rather than appropriate CAs, etc...

**Comment by mandy-chessell** [comment]
Remember we can not rely on application properties because there are enviornments where there are no files :). Supporting certifications needs to be part of our REST connector work, which is most definately a high priority feature :)

**Comment by mandy-chessell** [comment]
I am also reliably informed by our resident security expert that the term to use now-a-days for SSL is TLS - Transport Level Security :)

**Comment by cmgrote** [comment]
I stumbled across this while investigating some other topic:

https://letsencrypt.org

Sounds like they provide a cost-free way of setting up independent-CA-signed certificates.

**Comment by cmgrote** [comment]
Another option to consider might be to offload this to Istio (?)  Though this might simply cover a different level than what we're after, the concept of offloading mTLS in a micro-services sense sounds promising...

https://istio.io/docs/concepts/security/

**Comment by cmgrote** [comment]
So this seems to work for simple self-signed certificates, without needing to go out and use other utilities or services:

1. Obtain the self-signed certificate of the IGC host (from any machine with a JVM: could be the Egeria OMAG Server Platform so long as you're confident it is reaching the correct host):

```bash
$ keytool -printcert -sslserver my.igc.host.com:9446 -rfc > infosvr_self_signed.crt
```

2. Import the certificate into the Java keystore used by the environment (eg. in an Alpine openjdk docker image, this seems to be `/etc/ssl/certs/java/cacerts`):

```bash
$ keytool -trustcacerts -keystore /etc/ssl/certs/java/cacerts -storepass changeit -noprompt -alias my.igc.host.com -importcert -file infosvr_self_signed.crt 
$ rm infosvr_self_signed.crt
```

Notes:

- Keystore location should be specified, and probably best to use the one for the environment (if user-specific will likely depend on the user under which JVM itself is running whether it is picked up)
- The default keystore password in Java is `changeit`; obviously replace with the password for your actual keystore if it has been changed...  (Both this `-storepass` and `-noprompt` can be skipped if you would rather be prompted for the password and confirmation of importing the certificate.)
- The `-alias` should be specified and _must_ match the hostname of the IGC machine itself (the services tier host): if different, the certificate won't match and won't be validated

**Comment by cmgrote** [comment]
The various options for setting this up are now documented as part of the IGC connector setup, here (linked from the main README for that connector): https://github.com/odpi/egeria-connector-ibm-igc/blob/master/docs/security/README.md

We might want to move to a more general location (as the options are all connector-agnostic rather than IGC-specific), but suggest a separate issue for that if and when we want to do so?
