### ISSUE TITLE
[BUG] glossary author FVT should not use subject area clients

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#6352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I was looking at [https://github.com/odpi/egeria/issues/6326](https://github.com/odpi/egeria/issues/6326) and I noticed that in the glossary author FVT SubjectAreaDefinitionCategoryFVT contains `SubjectAreaNodeClient<SubjectAreaDefinition> subjectAreaCategory = null;` and it uses `SubjectAreaRestClient`. Also TermFVT contains    ` private SubjectAreaNodeClient<Term> subjectAreaTerm = null;`

I think that the glossary author FVT should only use glossary author rest calls so should have no need to create subject area clients. The issue that was raise around security seems to be dealing with SubjectAreaDefinitionCategory I am not sure if this is related.

### Expected Behavior

Do not refer to the subject area FVT clients in the glossary author fvt

### Steps To Reproduce

as above.

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

**Comment by davidradl** [comment]
@odttlnt Could you have a look at this please?

**Comment by davidradl** [comment]
I was expecting you to use GlossaryAuthorViewCategoryClient or a version of it GlossaryAuthorViewSubjectAreaDefinitionClient in line with the style of the rest of the code.  I think you have spotted a hole in the glossary author APIs, I think we need to add Glossary author rest APIs endpoints that do CRUD on SubjectAreaDefinition; are you ok to add this - then create the appropriate GlossaryAuthorViewSubjectAreaDefinitionClient in the FVT code?

**Comment by odttlnt** [comment]
I checked again. It looks like the SubjectAreaDefinition just uses the category endpoints to do its thing. So my earlier impression that something is missing from the GlossaryAuthor rest API was incorrect.
So the only thing to change would be what was put in the first issue comment, use a GlossaryAuthor client wrapper to replace the use of any subjectArea end points. Consequently we will only use glossary author endpoints for doing the FVT.
