### ISSUE TITLE
[BUG] Non-test scoped test only dependencies found

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#6410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After Mar 22 dependabot updates, many errors similar to the following are seen when building (the build stops, as we treat these as failures)

[INFO] --- maven-dependency-plugin:3.3.0:analyze-only (analyze) @ open-connector-framework ---
[WARNING] Non-test scoped test only dependencies found:
[WARNING]    com.fasterxml.jackson.core:jackson-databind:jar:2.13.2:compile

This occurs for varied components.

Trying to fix it for databind was unsuccessful, even where `mvn dependency:tree` was only showing the dependency to be in test scope.

Needs further investigation to determine if
 - the dependencies are wrong
 OR
 - these are false positives due to issues with the dependency checker
 
 Originally found in https://github.com/odpi/egeria/pull/6408 where the workaround was to add into the pom.xml the following for the `maven-dependency-plugin` plugin
 ```
                            <ignoredNonTestScopedDependencies>
                                <ignoredNonTestScopedDependency>*</ignoredNonTestScopedDependency>
                            </ignoredNonTestScopedDependencies>
```

### Expected Behavior

Build should run clean without skipping checks for test-only scope

### Steps To Reproduce

remove the exclusion line above and rebuild with maven

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

**Comment by tashoyan** [comment]
I confirm this issue with maven-dependency-plugin 3.3.0.

mvn --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Java version: 1.8.0_332, vendor: Temurin, runtime: /Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"

**Comment by planetf1** [comment]
We're currently considering switching over fully to gradle -- perhaps for version 4. We're still finishing off some of the changes to bring the gradle build to parity with maven.
There are different plugins in the gradle build that perform similar validation on dependencies.
It would be interesting to check you are able to do whatever you needed in gradle too
