### ISSUE TITLE
Document usage of helm charts

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#643]
Document simple useage of helm charts
 * What is kubernetes/helms (summary+links) & getting started (cloud service, local)
 * How to install VDC using helm (helm install)
 * Pod/container overview
 * how to delete vdc (helm delete)
 * how to map to public ports (loadbalancer)
 * How to check overall status (helm list, helm status, kubectl get pods etc)
 * How to see logs from node (kubectl logs)
 * How to login to node to see what is happening/debug (kubectl exec)

**Comment by cmgrote** [comment]
Happy to take a first cut at this, particularly as I'm adding extra bits around `initContainers` and `Jobs` 😉

**Comment by planetf1** [comment]
You could add kNative too :-)

We're not (yet) using either of those. I expect initContainers may be a useful tool - for example waiting for kafka.. Jobs perhaps at some point. In both cases they are probably the next level down beyond basic deployment, so I suggest we ensure we keep the 'getting started' text as simple as possible, and then allow the reader to progress to more useful info if they have the desire :-)

**Comment by cmgrote** [comment]
Happy enough with these to close this issue, or other things we should add first?

- https://github.com/odpi/egeria/tree/master/open-metadata-resources/open-metadata-deployment
- https://github.com/odpi/egeria/blob/master/open-metadata-resources/open-metadata-deployment/docs/k8s-ops.md

**Comment by planetf1** [comment]
I suspect we'll keep adding notes over time.

I'd be inclied to keep the docs narrow enough to focus on
 a) Initial user experience (including for those who don't know k8s)
 b) Details on the implementation/requirements which may assist k8s experts take what we have and extend to work in a production environment.

I would not try to create a k8s tutorial here -- though that could be the subject of external posts

**Comment by cmgrote** [comment]
I think we have the basis for this covered now, so pro-actively closing -- please re-open with specific actions remaining if not?
