### ISSUE TITLE
[BUG] Duplicate property defined for NetworkGatewayLink

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#6436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The same property `externalEndpointAddress` is defined twice (with different descriptions) on the `NetworkGatewayLink` relationship update in `OpenMetadataTypesArchive`.

I'm guessing the second definition needs a different name (?)

```java
final String attribute3Name            = "externalEndpointAddress";
final String attribute3Description     = "Network address used by callers to the network gateway.";
final String attribute3DescriptionGUID = null;
final String attribute4Name            = "externalEndpointAddress";
final String attribute4Description     = "Network address that the network gateway maps the request to.";
final String attribute4DescriptionGUID = null;
```

### Expected Behavior

That when we define attributes in a type, they are uniquely named (otherwise there's no way to distinguish them when storing values into them, searching for them, etc 😉)

### Any Further Information?

I'd suggest this is a blocker to the 3.8 release...

**Comment by cmgrote** [comment]
@mandy-chessell -- not sure I'm parsing the git log properly, but looks like you made this particular type change (copy / paste typo? 😬)

@planetf1 -- fyi on waiting for this prior to branching for release

**Comment by mandy-chessell** [comment]
Thanks  - should be `internalEndpointAddress`
