### ISSUE TITLE
maven.multiModuleProjectDirectory causes red warning in IntelliJ

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#647]
The following line causes IntelliJ to complain about the maven variable. however it is valid (since 3.3.1 or so, and we are using > 3.5.2)
`<sonar.jacoco.reportPaths>${maven.multiModuleProjectDirectory}/target/jacoco.exec</sonar.jacoco.reportPaths>`

This was reported to jetbrains at
[https://intellij-support.jetbrains.com/hc/en-us/community/posts/360002798140-IntelliJ-complains-it-cannot-resolve-maven-multiModuleProjectDirectory-](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360002798140-IntelliJ-complains-it-cannot-resolve-maven-multiModuleProjectDirectory-)
        
The fix is to add an exclusion directive into the pom

**Comment by mandy-chessell** [comment]
This is now fixed on my machine having pulled latest from master
