### ISSUE TITLE
Updata Datafile type as described in documentation

### ISSUE THREAD

**Issue by ruxandraRosu** [odpi/egeria#651]
Currently AssetSchemaType relationship cannot be added for DataFile type because DataFile doesn't currently inherit from Asset. As mentioned in documentation, DataFile type should inherit from DataStore.

**Comment by mandy-chessell** [comment]
I have fixed this - will be in my next PR today.

**Comment by cmgrote** [comment]
> I have fixed this - will be in my next PR today.

Can you tag me in the comment on that one? I have an updated mapping ready-to-go as well, but will wait to commit until this fix is in 😉

**Comment by mandy-chessell** [comment]
@cmgrote merged into master
