### ISSUE TITLE
[BUG] repository proxies are started without the repository helper populated

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#6531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

whilst writing a new repository proxy, I noticed that the repository connector what started before the open types had been processed. This means that the the repository proxy does not have a repositoryHelper that contains the open types in the start method, so calls like `repositoryHelper.getTypeDefByName`  cannot be used, as the repositoryHelper does not have any types to check against. 

### Expected Behavior

The archive manager should process the archives prior the the start being issued

### Steps To Reproduce

You can see this in the debugger using a metadata server if you start it as usual using a rest call and break point on the line
` localRepositoryConnector.start();` in file `OMRSOperationalServices.java`

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

### Any Further Information?

I think that this is not an issue normally because
- repository helper is not normally called in the start method.
- also using the enterprise services are configured after the archives and may pick up the correct repository helper.

**Comment by davidradl** [comment]
I tried this fix  
`            localRepositoryConnector = initializeLocalRepository(localRepositoryConfig);
            **archiveManager.setLocalRepository(localMetadataCollectionId,
                                              localRepositoryContentManager,
                                              localRepositoryConnector.getIncomingInstanceEventProcessor());**
            /*
             * Start processing of events for the local repository.
             */
            try
            {
                localRepositoryConnector.start();
            }
            catch (Exception error)
            {
                auditLog.logMessage(actionDescription,
                                    OMRSAuditCode.LOCAL_REPOSITORY_FAILED_TO_START.getMessageDefinition(error.getMessage()));
            }
        }


        /*
         * This is the point at which the open metadata archives will be processed.  The archives are processed
         * using the same mechanisms as TypeDef/Instance events received from other members of the cohort.  This
         * is because the metadata in the archives is effectively reference metadata that is owned by the archive
         * and should not be updated in the local repository.
         *
         * Note that if the local repository is not configured then only TypeDefs are processed because there
         * is nowhere to store the instances.  The TypeDefs are used for validation of metadata that is passed to
         * the enterprise repository services.
         */
        if (localRepositoryConnector != null)
        {
//            archiveManager.setLocalRepository(localMetadataCollectionId,
//                                              localRepositoryContentManager,
//                                              localRepositoryConnector.getIncomingInstanceEventProcessor());
        }
        else
        {
            archiveManager.setLocalRepository(localMetadataCollectionId,
                                              localRepositoryContentManager,
                                              null);
        }`


This works for my repository proxy, but type explorer breaks as when it asks for all the typedefs it does not receive any. I have not debugged this.

**Comment by mandy-chessell** [comment]
The current design is correct - the processing of types needs to happen after the start() because it can happen any time - there is no guarenteed time when all of the types are processed.  For example new types can come in when a new member joins the cohort, or when an open metadata archive is loaded into the server.
