### ISSUE TITLE
[BUG] when The local OMRS connection is incorrectly configured I receive a message incorrectly referring to EnterpriseOMRSRepositoryConnector   

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#6604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The local OMRS connection is incorrectly configured I received message :

 "class": "SuccessMessageResponse",
    "relatedHTTPCode": 500,
    "exceptionClassName": "org.odpi.openmetadata.adminservices.ffdc.exception.OMAGConfigurationErrorException",
    "exceptionCausedBy": "org.odpi.openmetadata.repositoryservices.ffdc.exception.OMRSConfigErrorException",
    "actionDescription": "activateWithSuppliedConfig",
    "exceptionErrorMessage": "OMAG-ADMIN-500-001 Method activateWithSuppliedConfig for OMAG server cocomap returned an unexpected exception of org.odpi.openmetadata.repositoryservices.ffdc.exception.OMRSConfigErrorException with message OMRS-CONNECTOR-400-004 The connection null passed to the EnterpriseOMRSRepositoryConnector is invalid.",
    "exceptionErrorMessageId": "OMAG-ADMIN-500-001",
    "exceptionErrorMessageParameters": [
        "cocomap",
        "activateWithSuppliedConfig",
        "org.odpi.openmetadata.repositoryservices.ffdc.exception.OMRSConfigErrorException",
        "OMRS-CONNECTOR-400-004 The connection null passed to the EnterpriseOMRSRepositoryConnector is invalid."
    ],
    "exceptionSystemAction": "The system is unable to configure the OMAG server.  No change was made to the server's configuration document.",
    "exceptionUserAction": "This is likely to be either an operational or logic error. Look for other errors.  Validate the request.  If you are stuck, raise an issue."

### Expected Behavior

The error should not mention the enterprise OMRS - as this is misleading as in my case the error is not to do with the  enterprise OMRS. It is only to do with the local OMRS

### Steps To Reproduce

Incorrectly configure a local OMRS connection 

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

**Comment by mandy-chessell** [comment]
This may not be a bug.  The error thrown will be the first one encountered and the enterprise connector may have been intitialized with a null repository connection - which is invalid.  What is the configuration document being used when starting the server?  What is the nature of the error introduced into the local repository configuration?

**Comment by planetf1** [comment]
@davidradl suggest updating the title to something meaningful ;-)
