### ISSUE TITLE
How to get total count of entities by type or by criteria

### ISSUE THREAD

**Issue by sergey-soloviov** [odpi/egeria#6613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using Egeria API I could not found the methods to get total count of entities by type or by criteria like in findEntities method.

### Expected Behavior

I am able to get total count of entities by type or by criteria used in findEntities method.

### Environment

```markdown
- Egeria: 3.9
- OS: Linux
- Java: 16
```

**Comment by davidradl** [comment]
@sergey-soloviov We have considered this in the past and have decided hat Egeria would not do these count orientated queries. Theses queries could be very costly, they could mean issuing paged federated queries across multiple repositories, to return a number. Egeria rest calls are more geared to issuing calls page by page producing data as required.

**Comment by mandy-chessell** [comment]
@sergey-soloviov having said that, you can code a loop that keeps updating the startFrom to step through the pages.  Keep the loop going until you get null

**Comment by planetf1** [comment]
Also there is work currently around building indexes of egeria content, which in future could be queried to gather similar information.

I wonder also if this kind of information, gathered from the index, could be kept as metrics -- not an accurate number, but some indication of size which might help with capacity planning & reporting.

**Comment by davidradl** [comment]
I guess a count means a count of the content in assets in the zones I can see, that are not deleted and at the appropriate effectivity date, without mementos and they may or may not contain duplicates depending on the calls used.
