### ISSUE TITLE
[Enhancement] Enable view services running in ui-chassis-spring

### ISSUE THREAD

**Issue by bogdan-sava** [odpi/egeria#6629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Please describe the new behavior that that will improve Egeria

TEX, REX and DINO view services endpoints will be available on ui-chassis-string to be consumed by static egeria-ui react UI

**Comment by planetf1** [comment]
Is there a reason not to use the existing strategy? Is it to ease migration over to the view services since the ui-server-chassis is the existing endpoint for the business UI?

**Comment by bogdan-sava** [comment]
Yes! For migration of tex rex and dino to components and use them in bussines UI.
Also shows how to import and use Egeria modules in a spring-boot based app.

**Comment by bogdan-sava** [comment]
@davidradl is not about moving. They are used in the UI chassis. View services are still available for running in the standard omag configuration.  Separately they are running in UI chassis. 
Config is done in a different way, but functionality is the same.
