### ISSUE TITLE
Egeria Dojo/Developer Day Activities dependencies cannot be resolved

### ISSUE THREAD

**Issue by GinaIsaia** [odpi/egeria#6722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

At the moment I'm following the Developer Day Dojo Activities, and am at the "Writing a integration connector" part (project egeria-dojo4). It is asking me to create main/java directory and paste several skeleton codes into different java **classes**. After that I have to "Resolve the Egeria dependencies in all 4 of the java classes for your connector." Some of them seem to be solved by changing **"class"** to **"enum"** (in TopicCataloguingAuditCode and TopicCataloguingErrorCode).

But not all dependencies can be resolved as shown in the screenshot. 

<img width="1728" alt="Screenshot 2022-07-21 at 09 48 19" src="https://user-images.githubusercontent.com/108683152/180159575-1bc6c67e-a26f-414a-b845-b87ea211df06.png">

I've had some problems resolving dependencies with an earlier part of the dojo too (egeria-dojo1 when making the AssetListen class), and decided to skip past it back then and move on. 

<img width="1728" alt="Screenshot 2022-07-21 at 10 14 43" src="https://user-images.githubusercontent.com/108683152/180164717-f9f45195-bcb2-4cd9-9480-1f177394d5e0.png">

### Expected Behavior

I expected all java classes to be be resolved as asked, after adding the pom.xml file and going back to the classes to fix them. But it seems some part is missing to resolve the dependency of KafkaTopicsCaptureIntegrationProvider in egeria-dojo4 (and AssetConsumerEvent in egeria-dojo1).

### Steps To Reproduce

Just following the Developer Day Dojo Activities will result in this problem occurring. 

### Environment

```markdown
Egeria: 3.8 / 3.11
Java: 11.0.15 (adoptopenjdk hotspot)
Working in IntelliJ IDEA 2022 Build #IC-221.5921.22 with Apache Maven 3.8.6


_Changing the metadata versions (3.8 tot 3.11 and with or without -SNAPSHOT) does not change anything._
```

**Comment by mandy-chessell** [comment]
Thanks for raising these errors.   I am in the mddle of another fix, but once that is done I will look at this

**Comment by planetf1** [comment]
@ginalsaia I took a look and noticed a few errors
* Agree - you need those enum changes & also update the Egeria project version to 3.11 (you could also change the version tag for the project you are creating, though this isn't important)
* At line 256 for the code to paste into TopicCataloguingConnector you'll see an extra 'n' on a single line - syntax error
* tip: For searching for classes I go to search.maven.org and type 'c:myclassname' (or fc:fully.qualified.classname) to search for packages containing a class. IntelliJ also has some built in search, but I've not found it as good
* In TopicCataloguingConnector change KafkaTopicsCaptureIntegrationProvider to TopicCataloguingProvider

With this I got a clean build (though have not continued on the exercise). May help until @mandy-chessell checks

**Comment by lpalashevski** [comment]
> Agreed - what is the breaking change?

Some of the event beans (AssetEvent, NewAssetEvent, UpdateAssetEvent...) are now removed with the event handling improvement change. Now there is I think single bean class for all so the sample needs update to use the new beans.

**Comment by lpalashevski** [comment]
sorry by breaking I mean it breaks the sample code not regression in egeria functionality :)

**Comment by mandy-chessell** [comment]
Ah - I understand :) I normally run these samples each release - and the ones in egeria-dev-projects and egeria-samples and update the poms so they are running on the latest release - however, I did not do this recently because I have been doing the refactor of the generic handlers.  I will get to this as soon as I can.

**Comment by planetf1** [comment]
We've just branched for 3.12, so will need to test/update for that release.

I wonder if we need to update the release process docs at https://egeria-project.org/guides/contributor/release-process/?h=release+proces & the template at https://github.com/odpi/egeria/blob/master/.github/ISSUE_TEMPLATE/release.yml so that we ensure these samples will work at the point of release. This may include figuring out how we can ensure the code in the docs is functional in a semi-automated way
