### ISSUE TITLE
[BUG] REST services not using RESTCallLogger to record start and return of reST invocation

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#6727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This came to light when reviewing the SonarScan results. There are a number of modules still using log.debug to record the start and end of a REST call rather than using the RESTCallLogger that also records the time of the call.  For many this is because they were written before RESTCallLogger was available.

[ ] Repository services
[ ] Asset Catalog OMAS
[ ] Asset Lineage OMAS
[ ] Data Engine OMAS
[ ] Glossary View OMAS
[ ] Governance Engine OMAS
[ ] Security Officer OMAS
[ ] Software Developer OMAS
[ ] Subject Area OMAS
[ ] Data Engine Proxy Governance Server
[ ] Open Lineage Governance Server 
[ ] UI Chassis
[ ] Glossary Author OMVS
[ ] Server Author OMVS

In Admin Services, the following REST Services are not logging
[ ] OMAGServerConfigOpenLineage
[ ] OMAGConfigOpenLineage
[ ] OMAGServerDataEngineProxy

These interfaces are embryonic - but they have the logger defined rather than the RESTCallLogger
[ ] Data Privacy OMAS
[ ] Data Science OMAS
[ ] Design Model OMAS
[ ] DevOps OMAS
[ ] Project Management OMAS

### Expected Behavior

These services should be logging via the RESTCallLogger

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

**Comment by Raunak-S** [comment]
Hi @mandy-chessell if this functionality is still needed I would be happy to work on this issue. I'm currently working with @davidradl so I would start with either the Subject Area OMAS or Server Author OMVS. 

For my understanding - what sort of unit testing would be required for this sort of change? The modules I mentioned above already have FVTs, would those be enough to satisfy testing requirements? 

Thanks!

**Comment by mandy-chessell** [comment]
Yes please :)

**Comment by Raunak-S** [comment]
I've created a child issue #7001 to keep track of the discussions around switching the Subject Area OMAS from the current `Logger` to the `RESTCallLogger` and to track of the subsequent PR. This seemed like the better option so this umbrella issue remains cleaner for more general discussion, but happy to delete the other issue and keep the discussions here as well, welcome to any feedback on this. Thanks!

PR for the Subject Area OMAS to come
