### ISSUE TITLE
[REPOSITORY] OMRS connector for Amazon Glue 

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#6734]
### Name

egeria-connector-aws-glue

### Owner

davidradl

### Deliverable

Provides an OMRS polling connector in the style of egeria-connectors-hivemetastore but for Amazon Glue.This make Glue metadata available to cohort members.

### Build, test and CI-CD process

The same as egeria-connector-hivemetastore with names like 

egeria-connector-aws-glue

Description: OMRS repository proxy connector for Amazon Glue. 

Testing will be interesting as it will require an Amazon account.

### Dependencies

Core Egeria

It will require the AWS Glue client as a dependancy in addition to the usual Egeria dependancies

### Justification

To Expose Amazon Glue metadata ti the the Egeria cohort

### Assumptions

Yes all true, The glue client is Apache 2 licensed

### Work Plan

Before creating the repo
- [ ] review overall request & get clarifications
- [ ] get approval on developer/TSC call from maintainers

Creating the repo
- [ ] Create the repo under the odpi organization (default gitignore, license, readme)
- [ ] Setup branch protection rules
- [ ] Set pull request options (allow merge, squash, rebase, suggest updating, allow automerge, do not delete head)
- [ ] Update security settings in repo (policy, advisories, alerts)
- [ ] set up permissions

First steps
- [ ] Initial code-drop (author)

Getting CI/CD started & refining settings
- [ ] Add initial build script for PR (including gradle wrapper if required)
- [ ] Add initial build script for merge

Further Refinement
- [ ] Add link in egeria docs to new repo describing purpose ( https://github.com/odpi/egeria-docs/blob/main/site/docs/education/tutorials/git-and-git-hub-tutorial/egeria-git-repositories.md ) 
- [ ] Add to connector catalog, if new repo is for connector ( https://github.com/odpi/egeria-docs/blob/main/site/docs/connectors/index.md )
- [ ] Add to release process docs ( https://github.com/odpi/egeria-docs/blob/main/site/docs/guides/contributor/release-process/index.md )
- [ ] Add required credentials for publishing to container repos, maven central etc
- [ ] Add artifact signing if needed
- [ ] Add dependabot config        
- [ ] Add CodeQL 
- [ ] Add to LFX ( https://projectadmin.lfx.linuxfoundation.org/project/a092M00001IV4JtQAL  ) for
  - [ ] LFXSecurity
  - [ ] LFAnalytics
- [ ] Add check for stale defects
- [ ] Add any required issue tags

Release
- [ ] Add release pipeline

**Comment by planetf1** [comment]
@davidradl I suggest we make sure we can get access to AWS & start on this connector before creating the repository
