### ISSUE TITLE
Add capability to export and import archives into the Subject Area OMAS

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#674]
Maybe this will require exposing collections to group glossary terms and then we export a collection into an archive. 
The archive would associated with the local OMAG server.
I am not sure if the imported terms would be readonly in the OMAS. 

I assume would allow terms, categories , glossaries and the relationships between them to be in the archive. I assume it would not include assets.
consider adding :
- projects,
- governance owners .

**Comment by mandy-chessell** [comment]
I don't think this is a valid requirement for subject area OMAS - this function is already supported by the OMRS
