### ISSUE TITLE
[Enhancement] Allow getting associated event broker from TopicIntegratorContext 

### ISSUE THREAD

**Issue by juergenhemelt** [odpi/egeria#6840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Please describe the new behavior that that will improve Egeria

TopicIntegratorContext includes private fields for the associated event broker `eventBrokerGUID`, `eventBrokerName`, etc. Those fields should be retrievable by corresponding getter methods. 

### Would you be prepared to be assigned this issue to work on?

- [ ] I can work on this

**Comment by mandy-chessell** [comment]
What is the purpose for retrieving these value?
