### ISSUE TITLE
[BUG] Correct documentation for classifyEntity interfaces in OMRSMetadataCollection

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#6852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The (newer) `::classifyEntity` method (that receives an `EntityProxy`):

- Is implemented directly in the base class (`OMRSMetadataCollection`).
- In cases where the received `EntityProxy` does not exist, this implementation throws an `EntityNotFoundException`.
- Lacks any documentation about any other expected behavior in cases where the received `EntityProxy` does not exist.

The (older) `::classifyEntity` method (that receives only a GUID):

- Returns an `EntityDetail` object.
- Lacks any documentation about handling any object other than an `EntityDetail`.

### Expected Behavior

The (newer) `::classifyEntity` method (that receives an `EntityProxy`):

- It seems is *expected* to be overridden by implementing repositories.
- The expected behavior of this overridden implementation is to handle the case where the received `EntityProxy` does not exist (by first creating it), and therefore should *never* actually throw an `EntityNotFoundException`.

The (older) `::classifyEntity` method (that receives only a GUID):

- It seems is *expected* to handle both full entity objects (`EntityDetail`) *and* `EntityProxy` objects.
- That when handling an `EntityProxy` object, it should be converted / coerced into an `EntityDetail`.
- (Note: these objects are peers in our object model rather than directly related (they both inherit from EntitySummary directly) — so strictly speaking, this is type conversion / coercion and not "normal" object subtype / supertype inheritance.)

### Environment

```markdown
All
```

### Any Further Information?

Suggested changes:

- (Newer) `::classifyEntity` method (that receives an `EntityProxy`): we should add much more detail to the JavaDoc of this newer method indicating its expected behavior for non-existent entity proxies, and that the provided default implementation is in reality only a partial solution. (In particular, emphasize strongly that we expect underlying repository implementations to override this method with additional functionality.)
- (Older) `::classifyEntity` method (that only receives a GUID): we should add more detail to the JavaDoc of this older method indicating it's expected to do such type coercion from `EntityProxy` into `EntityDetail` in cases where it is only operating on an entity proxy. (And probably further add detail to the JavaDocs that the method should work for both full entities and proxies.)

**Comment by cmgrote** [comment]
Discovered via: https://github.com/odpi/egeria-connector-xtdb/issues/390

**Comment by cmgrote** [comment]
On further thought, actually I think the documentation updates to the older `::classifyEntity` method are probably not necessary. The main updates should be to the new method, basically:

1. Bluntly indicating that it is a default implementation of a *partial* solution.
2. It has been provided *purely* for some minimal level of backwards-compatibility.
3. That it *should be* overridden by all repositories that want to provide the functionality of the method.
4. The expected functionality of that method:
    - It should not necessarily use the older `::classifyEntity` method at all
    - If the provided entity proxy exists (either as a proxy or a full entity), classify it
    - If it does not already exist, create it and classify it
    - Return the classification

**Comment by mandy-chessell** [comment]
We could change the default implementation of the new method in OMRSMetadataCollection to throw "FunctionNotSupportedException".  Then the enterprise connector will move on to another repository.  If there are no repositories that support the new method then if the caller has the entity then we could try the old method.  If the entity is not available (probable because this is why the new method was added) then the request fails.  This would create a more rapid identification that a repository's implementation needs updating.
