### ISSUE TITLE
Build error that seems to have not impact

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#6895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am occasionally seeing an error in the maven build that looks alarming but does not seem to cause a problem

<img width="1606" alt="Screenshot 2022-09-15 at 09 55 57" src="https://user-images.githubusercontent.com/12354195/190361829-5232aa8a-58e7-4279-ad69-98cbea05c192.png">

I am raising this issue in case others see it too.  This is the error in text

```
Could not find artifact org.osgi:org.osgi.core:pom:8.0.0 in 1-MavenCentral (https://repo1.maven.org/maven2/)
```

### Expected Behavior

No errors in the build

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

**Comment by planetf1** [comment]
Does this only occur with intellij? Ie is command line clean?
If only intellij, What intellij version
Is it only on a clean clone where no clue build has been done?

May be related to https://youtrack.jetbrains.com/issue/IDEA-301612/Importing-a-gradle-project-into-intelliJ-gives-errors-after-prepareKotlinBuildScriptModel-Build-is-working

**Comment by planetf1** [comment]
Checked jetbrains issue. no update. chasing. Probably worth concentrating on the gradle variant in future and fix up these glitches there (as much as we can). 

It may also be worth adding a note in the docs on this scenario

**Comment by planetf1** [comment]
removing maven tag. will leave open to verify for gradle only

**Comment by planetf1** [comment]
I am going to suggest we close this if it's only affecting maven as we will move fully to gradle.

The project init issue in #6893 will be left open as gradle is impacted
