### ISSUE TITLE
Move to 'main' for default branch (vs 'master')

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#6907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Please describe the new behavior that that will improve Egeria

I propose we switch our main branch from master to main.

Many repositories have now done this, and all of our new repositories are already using main.

There are two approaches

* copying master to main, updating HEAD, pointing default branch to main
* renaming master to main ( https://github.com/github/renaming )

The latter is simplest & clearest - no accidental onward use of main
In both cases build scripts will need updating main->master (easy), and individuals will need to update their environment. However github automatically sends email advising of this.

This should apply to each egeria repo (to be listed below) & if we agree with the principal we can discuss rollout

Originally raised as https://github.com/odpi/egeria/issues/3486

### Would you be prepared to be assigned this issue to work on?

- [X] I can work on this

**Comment by planetf1** [comment]
This was agreed in the Egeria face-to-face meeting 5-7 October 2022 held at IBM, Hursley.

We will start sharing information & planning for this change across all repos where main isn't already the primary branch & make this change in the coming weeks.

Any questions please discuss on slack, mailing list, or in this issue

**Comment by planetf1** [comment]
Following the branch rename, all users with local clones will need to do :

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
Alternatively users may create a new clone

Open PRs will be updated automatically, and some redirection of URLs will be in place.

More information can be found at https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch

This is targetted prior to release 3.13

**Comment by planetf1** [comment]
Proposed schedule

|Date|Action|Who|
|Mon 10 Oct|Initial notification via slack/email|Nigel|
|Thu 13 Oct|Discuss in developer call|Nigel|
|Wed 19 Oct|Notify/discuss in community call||Nigel|
| Thu 20 Oct|Implement rename|Nigel|
| Thu 20 Oct|Update branches|all|

**Comment by planetf1** [comment]
This will be discussed in the developer call today. I am still proposing the change is made next Thursday.

**Comment by planetf1** [comment]
On dev call 2022-10-13 Agreed that this proposal is still reasonable for 20 Oct.

Discussed impact on users:
 - dev work always goes via a PR. 
 - open PRs will be updated automatically by github
 - new PRs, the user will get 'main' by default (master no longer present)
 - a typical 'git pull upstream master' will fail. User will need to do 'git pull upstream main' instead, if they haven't renamed the branch (which they will be advised to do via slack, email list, and github)
 
 What else needs to be updated?
  - github actions (as above)
  
 Also asked whether charts affected
  - charts mostly do not refer to gitub branch names except for jupyter, where a git clone is done of master. this needs updating to main

Discussed 'egeria-ui'
 - this will be included in the rename
 
 I will arrange a wider email advising users of the change for next thu

**Comment by planetf1** [comment]
List of tasks for migration:

Pre-migration notice:
- [ ] Initial discussion on proposal
- [ ] agreement in developer call
- [ ] announcement via email/slack of upcoming change
- [ ] reminder in community call

Note: 'code' below includes
 - dependabot configuration
 - .github/workflows action definitions (often refer to the main branch)
 - Any remaining files (for example .md) that contain references to 'master' which need checking & updating if egeria

Migration (approx order based on impact)

 - egeria
   - [ ] name 
   - [ ] code
  - egeria-docs
    - [ ] code
  - egeria-ui
    - [ ] name
    - [ ] code
 - egeria-charts
    - [ ] code
  - egeria-dev-projects
    - [ ] name
    - [ ] code
  - egeria-samples
    - [ ] name
    - [ ] code  
  - egeria-api-mocks
    - [ ] name
    - [ ] code
 - data-governance
   - [ ] name
  - egeria-connector-ibm-information-server
    - [ ] name
    - [ ] code

  - [ ] Final cross-repository search

  And then advice
  - [ ] notification to slack & mailing list that task is complete
    
   The aim is to finish this during the day of Thu 20 Oct, with some tidying up/minor repositories continuing to 21 Oct. During this time there may be some inconsistencies due to the cross-repo linkages we have.

**Comment by mandy-chessell** [comment]
Does the "code" change in egeria-docs mean the changes to the documentation?

**Comment by planetf1** [comment]
* for egeria-connector-sas-viya I have left the PR open as reviews are enforced on this repo (@CDaRip2U )
* egeria-connector-ibm-information-server has had build failures on PRs for a few months. Will work with @lpalashevski to fix
