### ISSUE TITLE
User interface uses downloaded code that must be excluded from checkins

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#694]
I had an issue with my helm charts whereby I had mandy extra + files as part of my commit.

It appeared to be down to
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	../../../../open-metadata-implementation/user-interfaces/access-services-user-interface/src/main/resources/public/
	../../../../open-metadata-implementation/user-interfaces/access-services-user-interface/tools/

(easy to add the latter accidentally).

It appears the correct files are not being ignored once the UI is built.

**Comment by planetf1** [comment]
This is slowing my environment down and making it too error prone so I've made a PR

**Comment by cmgrote** [comment]
See #684

**Comment by bogdan-sava** [comment]
is this still an issue?

**Comment by cmgrote** [comment]
Not for me

**Comment by planetf1** [comment]
no, I fixed it. Closing
