### ISSUE TITLE
[BUG] InMemoryMetadatacollection save ReferenceCopy APIs allows null guids.

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#6996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

InMemoryMetadatacollection saveEntityReferenceCopy does not check for a non null guid. The saveRelationshipReferenceCopy does not check for non null relationship guid or that either ends guids are null. This means that incorrect logic in the caller of these methods can result in invalid reference entities and relationships.     

### Expected Behavior

The methods should validate the guids are not null. 

Note this issue may also exist in the ReadOnly, Janus and XTDB repository connectors. 

### Steps To Reproduce

I found this while developing the HMS connector 

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

**Comment by mandy-chessell** [comment]
In the OMRS runtime, the real repository OMRS metadata collections (ie in memory, graph, XTDB) are wrapped by the LocalOMRSRepositoryConnector.  This local connector's role is to trap invalid metadata instances being passed to the real metadata collection.  It means that the real metadata collection does not need to provide this validation and the broader ecosystem is protected against missing validation in the real metadata collections.

If using one of the real metadata collections in the caching pattern, the outer caching repository should do the validation and not rely on the real metadata collections.
