### ISSUE TITLE
[BUG] Unused field foreignKeyProperties in databaseColumnElement

### ISSUE THREAD

**Issue by lcpopa** [odpi/egeria#7052]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Field is empty when retrieving a column via the integrator context

### Expected Behavior

Field contains foreign key information

### Steps To Reproduce

Trigger metadata transfer of jdbc-integrator

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration: jdbc-connector
```

**Comment by mandy-chessell** [comment]
I had a look at the code and the guid/qualifiedName of the primary key column should be in the `referencedColumnGUID` and `referencedColumnQualifiedName` but the converter was adding the the values from the wrong end of the relationship.

**Comment by mandy-chessell** [comment]
I had a look at the code and the guid/qualifiedName of the primary key column should be in the `referencedColumnGUID` and `referencedColumnQualifiedName` but the converter was adding the the values from the wrong end of the relationship.
