### ISSUE TITLE
Warning when creating the git hub pages

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#710]
I created the github pages locally and got the following Warning:

 Build Warning: Layout 'empty' requested in open-metadata-implementation/user-interfaces/access-services-user-interface/tools/node_modules/polymer-cli/node_modules/accessibility-developer-tools/lib/closure-library/doc/index.md does not exist.

**Comment by cmgrote** [comment]
Actually, thinking about this a tiny bit more, the simplest way to solve this is probably adding the following directory to the Jekyll `_config.yml`:

`open-metadata-implementation/user-interfaces/access-services-user-interface/tools/node_modules/` -- everything under there should be downloaded modules from NPM (so no documentation under there that is specific to Egeria).

For readability, probably easiest to add these in YAML list notation:

```
exclude:
  - "open-metadata-resources/open-metadata-deployment/sample-data/**.yml"
  - "open-metadata-implementation/user-interfaces/access-services-user-interface/tools/node_modules/"
```

Any chance you can add to your environment and test the site generation to ensure a) it still works with this additional exclusion, and b) that the warning goes away?
