### ISSUE TITLE
[Enhancement] New methods on LineageIntegratorContext getDataFlows and getDataFlowByGUID

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#7122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Please describe the new behavior that that will improve Egeria

I see there is a method on LineageIntegratorContext
```
public DataFlowElement getDataFlow(String dataSupplierGUID,
                                       String dataConsumerGUID,
                                       String qualifiedName,
                                       Date   effectiveTime)
```
It would be useful to have an additional method  getDataFlows that returns all of the dataflows.

```
public List<DataFlowElement> getDataFlows(String dataSupplierGUID,
                                       String dataConsumerGUID,
                                       Date   effectiveTime)
```

As the caller may not know the qualifiedName, in which case would not be able to access this relationship.

If the caller only has the guid of the Relationship there should be a 

```
public DataFlowElement getDataFlowByGUID(String dataFlowGUID,
                                       Date   effectiveTime)
```

### Would you be prepared to be assigned this issue to work on?

- [ ] I can work on this

**Comment by mandy-chessell** [comment]
You do not need the qualified name to access the data flows - if you leave it blan you will get all of the data flows.

**Comment by mandy-chessell** [comment]
I think this one can be closed since there are not changes to be made.
