### ISSUE TITLE
repository-services client addEntity failed

### ISSUE THREAD

**Issue by DLaoLiu** [odpi/egeria#7125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when I use repository client to add entity, the server return 404.

### Expected Behavior

the right url would be " https://localhost:9443/servers/{serverName}/open-metadata/repository-services/..."
but the request url was "https://localhost:9443/open-metadata/repository-services/..."

### Environment

```markdown
- Egeria:3.12-SNAPSHOT
- OS:centos7
- Java:11
- Browser (for UI issues):
- Additional connectors and integration:
```

**Comment by mandy-chessell** [comment]
Hello @DLaoLiu.  The "/servers/{serverName}" part of the URL is supplied on the constructor of the client.  I am not sure which client you are using but they both work with the same base class, so the logic is similar.  Here is the JavaDoc for the LocalRepositoryServicesClient:
```
    /**
     * Create a new client with no authentication embedded in the HTTP request.
     *
     * @param repositoryName name of the repository to connect to (used in error messages)
     * @param restURLRoot the network address of the server running the repository services.  This is of the form
     *                    serverURLroot + "/servers/" + serverName.
     *
     * @throws InvalidParameterException bad input parameters
     */
    public LocalRepositoryServicesClient(String repositoryName,
                                         String restURLRoot) throws InvalidParameterException
    {
        super(repositoryName, restURLRoot, "/");
    }
``` 
If you update your `restURLRoot` to `https://localhost:9443/servers/{serverName}` when you call the client, all should be well.

This is different from most of Egeria's other REST clients which typically take the platformRootURL.  However the respository services may have to call servers that are not Egeria and not multi-tenant.  This is why the `/servers/{serverName}` part of the URL is parameterised in the constructor.

**Comment by DLaoLiu** [comment]
Yes, I did not add /servers/{serverName} while calling. I will try again. Thanks for your reply!

**Comment by mandy-chessell** [comment]
Assuming all ok now
