### ISSUE TITLE
[Enhancement] LineageIntegratorContext method to get Dataflow relationships associated with a process

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#7132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Please describe the new behavior that that will improve Egeria

similar to https://github.com/odpi/egeria/issues/7122

I am processing events as part of [https://github.com/odpi/egeria-connector-integration-lineage-event-driven-sample](https://github.com/odpi/egeria-connector-integration-lineage-event-driven-sample) I that describe a process and input and output assets. I would like t be able to see any existing DataFlow relationships associated with the Process so I can work out which data flows and assets I need to delete to ensure that the new process topology is now in place. 

### Would you be prepared to be assigned this issue to work on?

- [ ] I can work on this

**Comment by davidradl** [comment]
@mandy-chessell does this sound reasonable? I was thinking for Dataflows we could have a getDataflowsForProcess call. 
If you agree I could implement this. This is currently stopping the lineage sample work completing.

**Comment by mandy-chessell** [comment]
What is wrong with using the existing getDataFlowConsumers() and gatDataFlowSuppliers() methods?

**Comment by davidradl** [comment]
thanks @mandy-chessell  - I did not find those- they look perfect :-)
