### ISSUE TITLE
[Issue?] Using XTDB repository appears to have missing methods?

### ISSUE THREAD

**Issue by dwolfson** [odpi/egeria#7153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Log indicates that there may be missing methods (in classifyEntity?). Found when running labs and looking in logs after configuring XTDB for cocoMDS1. No errors show up when in-memory repository is configured.

### Expected Behavior

No errors in log ;)

### Steps To Reproduce

Configure xtdb as the repository and run the "building a data catalog" lab. Then inspect the log for the datalake pod - a copy of the log is:

Wed Nov 30 16:25:38 GMT 2022 cocoMDS1 Exception OMAG-REPOSITORY-HANDLER-0003 An unexpected error org.odpi.openmetadata.repositoryservices.ffdc.exception.FunctionNotSupportedException was returned to classifyEntity by the metadata server during addCSVFileToCatalog->createFolderStructureInCatalog request for open metadata access service Asset Owner OMAS on server cocoMDS1; message was OMRS-METADATA-COLLECTION-501-001 OMRSMetadataInstanceStore method classifyEntity for OMRS Connector org.odpi.openmetadata.adapters.repositoryservices.rest.repositoryconnector.OMRSRESTMetadataCollection to repository type REST-connected Repository https://lab-core:9443/servers/cocoMDS5 is not implemented
Wed Nov 30 16:25:38 GMT 2022 cocoMDS1 Exception OMAG-REPOSITORY-HANDLER-0003 An unexpected error org.odpi.openmetadata.repositoryservices.ffdc.exception.FunctionNotSupportedException was returned to classifyEntity by the metadata server during addCSVFileToCatalog->createFolderStructureInCatalog request for open metadata access service Asset Owner OMAS on server cocoMDS1; message was OMRS-METADATA-COLLECTION-501-001 OMRSMetadataInstanceStore method classifyEntity for OMRS Connector org.odpi.openmetadata.adapters.repositoryservices.rest.repositoryconnector.OMRSRESTMetadataCollection to repository type REST-connected Repository https://lab-core:9443/servers/cocoMDS5 is not implemented
Wed Nov 30 16:25:38 GMT 2022 cocoMDS1 Exception OMAG-REPOSITORY-HANDLER-0003 An unexpected error org.odpi.openmetadata.repositoryservices.ffdc.exception.FunctionNotSupportedException was returned to classifyEntity by the metadata server during addCSVFileToCatalog request for open metadata access service Asset Owner OMAS on server cocoMDS1; message was OMRS-METADATA-COLLECTION-501-001 OMRSMetadataInstanceStore method classifyEntity for OMRS Connector org.odpi.openmetadata.adapters.repositoryservices.rest.repositoryconnector.OMRSRESTMetadataCollection to repository type REST-connected Repository https://lab-core:9443/servers/cocoMDS5 is not implemented
Wed Nov 30 16:25:38 GMT 2022 cocoMDS1 Exception OMAG-REPOSITORY-HANDLER-0003 An unexpected error org.odpi.openmetadata.repositoryservices.ffdc.exception.FunctionNotSupportedException was returned to classifyEntity by the metadata server during addCSVFileToCatalog request for open metadata access service Asset Owner OMAS on server cocoMDS1; message was OMRS-METADATA-COLLECTION-501-001 OMRSMetadataInstanceStore method classifyEntity for OMRS Connector org.odpi.openmetadata.adapters.repositoryservices.rest.repositoryconnector.OMRSRESTMetadataCollection to repository type REST-connected Repository https://lab-core:9443/servers/cocoMDS5 is not implemented

### Environment

```markdown
- Egeria: 3.12
- OS: Ubuntu 22.04.1 LTS
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

**Comment by planetf1** [comment]
With 3.15-SNAPSHOT getting
```
Thu Dec 15 10:29:53 GMT 2022 cocoMDS1 Error OMAG-REPOSITORY-HANDLER-0010 Method reclassifyEntity(LatestChange) called from addCSVFileToCatalog->createFolderStructureInCatalog for service Asset Owner OMAS is using function that not supported by any of the metadata repositories connected to cocoMDS1 - error message is: OMRS-METADATA-COLLECTION-501-001 OMRSMetadataInstanceStore method updateEntityProxyClassification for OMRS Connector org.odpi.egeria.connectors.juxt.xtdb.repositoryconnector.XtdbOMRSMetadataCollection to repository type cocoMDS1 is not implemented
```
along with the latest (2022-12-14) xtdb/3.14-SNAPSHOT connector
as the first error

**Comment by davidradl** [comment]
I am a bit confused, OMRSMetadataCollectionBase has 
1.
 ```
public  EntityDetail classifyEntity(String               userId,
                                        String               entityGUID,
                                        String               classificationName,
                                        String               externalSourceGUID,
                                        String               externalSourceName,
                                        ClassificationOrigin classificationOrigin,
                                        String               classificationOriginGUID,
                                        InstanceProperties   classificationProperties) throws InvalidParameterException,
                                                                                              RepositoryErrorException,
                                                                                              EntityNotKnownException,
                                                                                              ClassificationErrorException,
                                                                                              PropertyErrorException,
                                                                                              UserNotAuthorizedException,
                                                                                              FunctionNotSupportedException
    {
        final String  methodName = "classifyEntity (detailed)";

```
2.
```
    public EntityDetail classifyEntity(String               userId,
                                       String               entityGUID,
                                       String               classificationName,
                                       InstanceProperties   classificationProperties) throws InvalidParameterException,
                                                                                             RepositoryErrorException,
                                                                                             EntityNotKnownException,
                                                                                             ClassificationErrorException,
                                                                                             PropertyErrorException,
                                                                                             FunctionNotSupportedException,
                                                                                             UserNotAuthorizedException
    {
        final String  methodName   = "classifyEntity"; 
```
3.
```
 @Deprecated
    protected TypeDef  classifyEntityParameterValidation(String               userId,
                                                         String               entityGUID,
                                                         String               classificationName,
                                                         InstanceProperties   classificationProperties) throws InvalidParameterException,
                                                                                                               RepositoryErrorException,
                                                                                                               PropertyErrorException,
                                                                                                               UserNotAuthorizedException
    {
        final String  methodName   = "classifyEntity";
```

and [https://github.com/odpi/egeria-connector-xtdb/blob/main/connector/src/main/java/org/odpi/egeria/connectors/juxt/xtdb/repositoryconnector/XtdbOMRSMetadataCollection.java](https://github.com/odpi/egeria-connector-xtdb/blob/main/connector/src/main/java/org/odpi/egeria/connectors/juxt/xtdb/repositoryconnector/XtdbOMRSMetadataCollection.java ) contains both these methods. @cmgrote added classifyEntity on the 27th of August this year.

I am unsure why with the latest code we would get a function not found . @dwolfson are you using the latest XTDB driver?

**Comment by planetf1** [comment]
@davidradl I didn't get any issue with classify running with 3.15-SNAPSHOT -- Dan did, but was running 3.12

I did get an issue with updateEntityClassification (reported in logs a updateEntityProxyClassification)

**Comment by davidradl** [comment]
@planetf1 yes I see - it looks a straight forward fix . @mandy-chessell do you want me to make the change?

**Comment by mandy-chessell** [comment]
I agree - the problem we are seeing is in reclassify and declassify.

**Comment by mandy-chessell** [comment]
The problem we are seeing is in reclassify and declassify in terms of missing methods.

Also the implementation of the new classifyEntity method the @cmgrote added to the XTDB repository connector is not correct.  The purpose of these three new methods (and getHomeClassifications) is to allow a repository to store a classification independently of its entity using the entityProxy as a stub to connect it to.  The repository needs to look to see if it has the entity and if so, it can use the old method to add/update/delete the classification.  If the entity is not stored then it should add the entity proxy to the store with the classification.  When the entity finally turns up in the repository via an event typically, the entity proxy is upgraded to an entity, with care that the classification is not lost.

**Comment by mandy-chessell** [comment]
@davidradl given it is a complex change, are you still willing to do the development work.  Then I can focus on the changes to CTS to check these four new methods are working consistently.

**Comment by davidradl** [comment]
@mandy-chessell lets discuss at office hours.

**Comment by davidradl** [comment]
I see that Inmemory and graph collections have a method named   
```
 @Override
    public Classification classifyEntity(String               userId,
                                         EntityProxy          entityProxy,
                                         String               classificationName,
                                         InstanceProperties   classificationProperties)
```

The local repository drives this method.

Even though there is an  @Override I do not see [this method](https://github.com/odpi/egeria/issues/7153#issuecomment-1353047318) in `OMRSMetadataCollectionBase` class.  It is in abstract class OMRSMetadataCollection. 

It looks like the logic to do with determining if it is a proxy or not is in the enterprise repository layer and if called by rest.
@mandy-chessell If you are ok with this existing logic then for classify Entity, the change for XTDB would be to add the above method to XTDB


 
![Screenshot 2022-12-15 at 14 57 50](https://user-images.githubusercontent.com/39792797/207893673-e16615f3-9381-457e-a122-3dbe1e26bfca.png)

**Comment by davidradl** [comment]
@mandy-chessell as discussed in the office hours, we need to talk this through with @cmgrote and more widely with the community. I will not do anything on this at this time.   
In office hours we talked of 
- whether this orchestration logic around handling classifications and proxies should be moved to the local repository. The advantage of this would be that there would be one place for the logic. The disadvantage would mean that the repository could not optimise its calls.
- we talked of XTDB classifyEntity current implementation probably being incorrect.  If the new classifyEntity call gave function not supported, then the enterprise connector could have handled this
- we talked of the metadataCollectionBase having an implementation for 2 of the 3 classifyEntity methods. Mandy suggested that there should not be a base implementation.

**Comment by mandy-chessell** [comment]
@davidradl I am not sure I am completely understanding the comments above.  This was my thoughts of the work that we talked about doing

* Verifying that the logic of the enterprise connector is correctly switching to the old classificaton methods (passing entityGUID) if the new methods that pass entityProxy throw FunctionNotSupportedException.
* Verifying that the new methods in OMRSMetadataCollection throw FunctionNotSupportedException so that the enterprise connector can correctly determine the implementation status of the repository connector.
* Remove any implementation of the new classification methods that pass the proxy which simply delegate to the old method.   This includes the base class and any repository connector implementation.
* Adding tests to the CTS to test the 3 new classification methods that pass the proxy and the getHomeClassifications method.   These tests would consitute a new profile for the repository connector.

We did talk about whether the local repository connector could provide the implementations of the new methods.  This would involve multiple calls to the real (plugin) repository connector for every change to metadata via API call or event.  It is a complex implementation.  We would go for this option if implementing the methods in XTDB proved difficult.  Before going for this option, we would check with @cmgrote because, as you mention, it removes the option for the real repository implementation to optimize this function.

**Comment by cmgrote** [comment]
This is what I documented as the expected behaviour of these new methods, and implemented accordingly in the XTDB repository connector: https://github.com/odpi/egeria/issues/6852

I note that I did not at that point make some of these other more invasive changes (removing default implementations, etc) for fear of what impact that might have on any other implementations that might be relying on that behaviour. Awesome from my perspective if we're comfortable going ahead with them, though 😁 

> I am unsure why with the latest code we would get a function not found

So I did indeed make the changes to these methods way back at the end of August, but I haven't created a new release of the connector since. So unless everyone happens to be using the snapshot releases of the connector (unlikely?) they won't be able to access this revised behaviour.

That said, I'm pretty much ready to release 3.14 of the connector now (which would include this changed method) — just waiting for Egeria core 3.14 to officially be released.

**Comment by mandy-chessell** [comment]
Thanks @cmgrote :) I will update the CTS to add a new optional repository profile for this.  I will also add another optional profile for the new entity/relationshipVersions methods

**Comment by mandy-chessell** [comment]
This looks good - the problems I found in Egeria's inmemory connector was when an entity was received as an event.  The connector was incorrectly saving the entity without perserving any additional home classifications.

**Comment by cmgrote** [comment]
Hopefully I've avoided the same problem, but to be honest I've probably not explicitly tested it — so will be cool to have it in the CTS 😁

**Comment by mandy-chessell** [comment]
Indeed -  I  also have new open metadata labs that test this too - in the new development labs folder.  I will let you know how I get on - I am running the code directly from main.

**Comment by planetf1** [comment]
@cmgrote I was running 3.14-SNAPSHOT (last update b885e7f6024dc67f7d638cfcda4f94f21c114704 8 Dec) when I posted https://github.com/odpi/egeria/issues/7153#issuecomment-1352990023 - this was with a recent 3.15-SNAPSHOT egeria build. That was slightly different to Dan's initial issues but still related to classification. just pointing out as I'm not sure if you thought this would now work ok.
