### ISSUE TITLE
Add Mihai Iliescu to the contributors team

### ISSUE THREAD

**Issue by lpalashevski** [odpi/egeria#7233]
As agreed via the maintainers channel, add [Mihai Iliescu](https://github.com/MihaiIliescu) to contributors Team with read access across all repositories.

**Comment by planetf1** [comment]
* For contributors we also need to invite/add  the new joiner the the 'Egeria Contributors' 'team' defined at the ODPI level - this grants 'read' access to the repo which enables issue/PR assignment etc
* The COnTRIBUTORS md file should contain email address if possible (I didn't do this last time!) as this is used by the Linux Foundation team to know where to send badges (checked monthly)
* Maintainers are similar, though they also need to be added to the maintainer mailing list

I've added Mihael to the relevant team

**Comment by planetf1** [comment]
@MihaiIliescu I have added you to the github contributors group. You should receive an email at the address listed in CONTRIBUTORS.md. This will increase your access to the project.

Have you received an email from the LF with your 'badge'. If not reply here and I'll chase up.

**Comment by MihaiIliescu** [comment]
@planetf1 I have received the invitation and accepted it. Thank you!

**Comment by planetf1** [comment]
Super. Did you get sent a badge?

**Comment by MihaiIliescu** [comment]
It was a bit low in the email inbox (5 jan)  but I found it. Thank you!
