### ISSUE TITLE
[BUG] Using the generic handlers, it is possible to create an asset using an qualifiedName that already exists

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#7234]
### Current Behavior

I create a glossary with  qualified name "aaaa" and then create an asset using asset manager with the same qualified name.
It does not fail . The code gets the existing Entities to check using 
```
 List<EntityDetail> existingEntities = this.getEntitiesByValue(localServerUserId,
                                                                      uniqueParameterValue,
                                                                      uniqueParameterName,
                                                                      entityTypeGUID,
                                                                      entityTypeName,
                                                                      propertyNames,
                                                                      true,
                                                                      null,
                                                                      OpenMetadataAPIMapper.MEMENTO_CLASSIFICATION_TYPE_NAME,
                                                                      false,
                                                                      false,
                                                                      supportedZones,
                                                                      null,
                                                                      0,
                                                                      invalidParameterHandler.getMaxPagingSize(),
                                                                      effectiveTime,
                                                                      methodName);
```

<img width="593" alt="Screenshot 2022-12-07 at 16 05 55" src="https://user-images.githubusercontent.com/39792797/206229998-90fde5c2-c95d-4bfd-810f-fc2e7c00a338.png">

So the code will only find an existing entity if the type is the same. I though qualified names were supposed to be unique across entities not within a type.

### Expected Behavior

I would expect the generic handler check for existing entity of the same qualified Name of a different type to stop the creation of a subsequent entity. 

### Steps To Reproduce

create a glossary with qualified name aaa. Then using the asset manager OMAS to create a new asset , it will incorrectly create.

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

### Any Further Information?

I suspect that the checking of the unique attribute should be in the scope of the type in which it is defined. For example qualifiedName should check all referenceables and not the sub type.

**Comment by mandy-chessell** [comment]
This is not a specific Asset Manager OMAS issue - it is common to most OMASs that use the generic handlers.
