### ISSUE TITLE
[Enhancement] update java version for github actions to 17

### ISSUE THREAD

**Issue by bogdan-sava** [odpi/egeria#7236]
- required to upgrade dependencies that are require java 17
- allow using the new features from java >= 11

**Comment by planetf1** [comment]
@bogdan-sava This has already been done & tracked via https://github.com/odpi/egeria/issues/6987

The changes are in the 'egeria-release-4.0pre' branch, and actions are currently running there that
 - use gradle (./gradlew build) 
 - use Java 17 (temurin)
 
 Packages are being signed and shipped to maven central as '4.0-SNAPSHOT'
 Docker images are being created. https://quay.io/repository/odpi/egeria?tab=tags
 
 Periodically this branch is rebased on 'main'.
 
 The intent is to merge back with master once we are 'ready' to do the final run-up to version 4.
 
 Do the current releases look good?
 
 This is of course for base, though I anticipate less issues

**Comment by planetf1** [comment]
Execution runs for v4 merge -> https://github.com/odpi/egeria/actions/workflows/merge-v4.yml
Execution runs for v4 PR -> https://github.com/odpi/egeria/actions/workflows/pr-v4.yml

**Comment by planetf1** [comment]
Project board for v4 -> https://github.com/orgs/odpi/projects/5

**Comment by planetf1** [comment]
Hope the explanation makes sense. Will close as I think these objectives are met, but if you do find any issues/additions needed please raise. Will be good to get feedback on how the v4 branch is working.
