### ISSUE TITLE
Gradle/java modules - visibility issues with OpenMetadataStoreClient ?

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#7242]
### Current Behavior

> Task :open-metadata-implementation:access-services:community-profile:community-profile-client:compileJava FAILED
/Users/jonesn/IdeaProjects/egeria/v4/open-metadata-implementation/access-services/community-profile/community-profile-client/src/main/java/org/odpi/openmetadata/accessservices/communityprofile/client/OpenMetadataStoreClient.java:13: error: OpenMetadataStoreClient is not abstract and does not override abstract method updateRelatedElementsInStore(String,String,boolean,boolean,boolean,ElementProperties,Date) in MetadataElementInterface
public class OpenMetadataStoreClient extends OpenMetadataStoreClientBase
       ^
1 error

> Task :open-metadata-implementation:access-services:governance-program:governance-program-client:compileJava FAILED
/Users/jonesn/IdeaProjects/egeria/v4/open-metadata-implementation/access-services/governance-program/governance-program-client/src/main/java/org/odpi/openmetadata/accessservices/governanceprogram/client/OpenMetadataStoreClient.java:13: error: OpenMetadataStoreClient is not abstract and does not override abstract method updateRelatedElementsInStore(String,String,boolean,boolean,boolean,ElementProperties,Date) in MetadataElementInterface
public class OpenMetadataStoreClient extends OpenMetadataStoreClientBase
       ^
1 error

> Task :open-metadata-implementation:access-services:digital-service:digital-service-client:compileJava FAILED
/Users/jonesn/IdeaProjects/egeria/v4/open-metadata-implementation/access-services/digital-service/digital-service-client/src/main/java/org/odpi/openmetadata/accessservices/digitalservice/client/OpenMetadataStoreClient.java:13: error: OpenMetadataStoreClient is not abstract and does not override abstract method updateRelatedElementsInStore(String,String,boolean,boolean,boolean,ElementProperties,Date) in MetadataElementInterface
public class OpenMetadataStoreClient extends OpenMetadataStoreClientBase
       ^
1 error

### Expected Behavior

No compile error

### Steps To Reproduce

This occurs with the v4 build when compiling using modules (so not easily reproducible). Checks are stricter in this environment

### Environment

```markdown
- Egeria: 4.0 (egeria-prerelease-4.0)
- OS: macOS 13.1
- Java: 17.0.4 (temurin)
- Browser (for UI issues): n/a
- Additional connectors and integration: gradle
```

**Comment by planetf1** [comment]
Raising to note (it may be a consequence of other changes). Will return to propose a fix once other issues addressed

**Comment by mandy-chessell** [comment]
How did this get into main if it does not compile?  Do you have a clean environment?

**Comment by planetf1** [comment]
This is one of the things picked up in a Java 17, gradle, java module enabled build. 

I took a look at the detail (I just logged it when there were a lot of concurrent issues) ....

In this case, it does appear that OpenMetadataStoreClient (in community profile, and its abstract) extends OpenMetadataStoreClientBase (which is abstract).

OpenMetadataStoreClientBase is defined in gaf-metadata-client & includes the method UpdateRelatedElementsInStore. This is not defined as abstract, it's implemented

As such, it looks as if the code is fine - so this is is most likely a class visibility issue with the module definitions rather than an error in the java class itself. I'll unassign you and take a look

**Comment by mandy-chessell** [comment]
Where does it say it is a Java 17 problem?

**Comment by mandy-chessell** [comment]
The environment section is not filled in - that was where I looked.   But maybe it is not the right place to look.  If it is blank I tend to assume it is main :)

**Comment by planetf1** [comment]
Fair. 'Do as I say not as I do'. I originally added that template ;-)

**Comment by planetf1** [comment]
This was a class visibility issue. Thanks to @davidradl who questioned 'is it the same ElementProperties'

it is, but I needed to add

* gradle dependency    ` implementation project(':open-metadata-implementation:frameworks:governance-action-framework')`
* module import `requires egeria.open.metadata.implementation.frameworks.governance.action.framework.main;` (or whatever the name of the gaf module is)

Java Modules enforce stricter contracts between modules, so this dependency has to be explicitly declared.
