### ISSUE TITLE
[BUG] How is Juergen's surname spelt?

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#7244]
### Current Behavior

Just looking in the Contributors.md file and see that Jurgen's surname is spelt differently from his userid.  Is it correct?

### Expected Behavior

Just checking it is correct for the end of year presentation

**Comment by planetf1** [comment]
Jürgen Hemelt
 - I made a typo error in CONTRIBUTORS.md so needs updating. can correct now - or if you are mid-update...

**Comment by mandy-chessell** [comment]
I can fix - did not want it fix it so it was consistent and wrong :)
