### ISSUE TITLE
[Enhancement] Create Jackson object mappers, readers and writers at class level in JUnit tests

### ISSUE THREAD

**Issue by alexandra-bucur** [odpi/egeria#7252]
### Please describe the new behavior that that will improve Egeria

Jackson object mappers, readers and writers are created at test level in JUnits and could be instantiated once at class level as static final members. This could improve performance for classes that instantiate it multiple times in methods like: PrimitivePropertyValueTest.

**Comment by mandy-chessell** [comment]
This work is not planned
