### ISSUE TITLE
how can I run my connector 

### ISSUE THREAD

**Issue by DLaoLiu** [odpi/egeria#7260]
I have wirte a mysql connector , I do not want to run it though the OMIS intergation daemon ,  
how could I run it directly through an OMAS client

**Comment by mandy-chessell** [comment]
Connectors implement specific interfaces that allow them to be plugged into a specific framework.  The framework then uses the connector's interface to control the execution of the connector, and to provide it with specific resources.

So the place where you run your connector needs to be where the framework is available to manage your connector.

For example, if you implement the the interface from Data Integrator OMIS then you need to run the connector in an environment where the Data Integrator OMIS is running.  This is the integration daemon in Egeria.  With this interface, the connector does not call the OMAS client.  It is provided with a context that gives it access to the open metadata interfaces.

Another example, is that the connector is written for a framework outside of Egeria.  For example the connector is using a a framework from a technology such as DataHub.  In this example, the connector runs in DataHub where its framework is available.  It would create an appropriate OMAS client and call the client directly.

The OMAS clients are just client libraries.  They are not a runtime.

**Comment by DLaoLiu** [comment]
Thank you, Mandy. I get it.

**Comment by planetf1** [comment]
@DLaoLiu Are you aware of the new generic jdbc connector - see https://github.com/odpi/egeria-database-connectors -- it's actively being developed & tested against various dbs. I believe mysql has already been tested. Feedback, suggestions for improvement etc I'm sure would be very welcome, and it may be appropriate for your needs? It does run through omis etc.
