### ISSUE TITLE
[Enhancement] Alleviate the Configuration of an Audit Log in Unit-Tests

### ISSUE THREAD

**Issue by juergenhemelt** [odpi/egeria#7326]
### Please describe the new behavior that that will improve Egeria

Currently if you need an audit log for unit tests - e. g. to test the log records or exceptions - it is a huge effort. You have to write code like the one below. There should be a way, to configure a default console based audit log with a defined severity level by writing only a few (2 - 3) lines of code. Example:

```
connector.setAuditLog( new DefaultAuditLog( Severity.TRACE )
```

### Alternatives

Currently required code (sample):
```
    // Audit logging
        ConnectorConfigurationFactory connectorConfigurationFactory = new ConnectorConfigurationFactory();
        ConnectorBroker broker = new ConnectorBroker();

        Connector auditLogConnector = null;
        try {
            ArrayList<String> severities = new ArrayList<String>();
            severities.add("Trace");
            auditLogConnector = broker.getConnector(connectorConfigurationFactory.getConsoleAuditLogConnection("console", severities));
            auditLogConnector.start();
        } catch (ConnectionCheckedException | ConnectorCheckedException e) {
            e.printStackTrace();
            Assertions.assertNull(e, "Unable to get or start audit log via the broker.");
        }
        List<OMRSAuditLogStore> auditLogDestinations = new ArrayList<>();
        auditLogDestinations.add( (OMRSAuditLogStore)auditLogConnector );
        OMRSAuditLogDestination destination = new OMRSAuditLogDestination(
                "server1",
                "Integration Daemon",
                "org",
                auditLogDestinations
        );

        OMRSAuditLog auditLog = new OMRSAuditLog(
                destination,
                -1,
                ComponentDevelopmentStatus.SAMPLE,
                "ConnectorTest",
                "Testing of the connector",
                null
        );
        connector.setAuditLog(auditLog);
```

**Comment by davidradl** [comment]
The connector does not know about audit logs in the architecture. So I do not think we should update the Connector to be aware of audit logs.  I wonder if you could create a connector.setAuditLog( new MockDefaultAuditLog( Severity.TRACE )). A MockDefaultAuditLog would encapsulate the above construction and start logic and pass through the log calls to the encapsulated default log. I suspect this class should be in the test source, so would need to be in each project. Would this work?

Another idea for the mock audit log would be to not use default but instead have a java map to store the log entries  The Map key could be the message number and the value could be a map of audit log instances. The mock could be configured to only store the messages the test is interested in checking, so the maps do not get too big.The mock could then expose a method to get all the log entries for a particular map key (message). The audit log has getters so you can easily get the message constituents for example the message parameters in java.

**Comment by mandy-chessell** [comment]
The FVTs use a similar approach ... See FVTAuditLogDestination

**Comment by juergenhemelt** [comment]
This makes it a bit easier. But can I set the severity with the FVTAuditLogDestination?

**Comment by davidradl** [comment]
> This makes it a bit easier. But can I set the severity with the FVTAuditLogDestination?

1) Using the FVTAuditLogDestination as-is you could check the severity is correct in the audit log record. I wonder why you need the severities. Are you trying to test that different destinations only get particular log messages depending on their severities? I would think that would be a unit test in the auditlog framework.  

2) If you were to implement a unit test audit log destination with the map idea - then finding whether you had a particular message would be a map look up; the alternative would be you need to scan each log entry looking for a particular message id. This seems to simplify the unit test checking of log entries a lot. 
 
3) You could copy FVTAuditLogDestination and have your version extend OMRSAuditLogDestination, so you can send in the severities on the constructor. I am not sure what this would test.

Hopefully this is making sense.
