### ISSUE TITLE
open metadata security connector update user list info while user list changed

### ISSUE THREAD

**Issue by PeterChenTian** [odpi/egeria#7329]
In open-metadata-security-samples , CocoPharmaServerSecurityConnector setup user list in Constructor method,
If getting user list by looking up to a user directory such as LDAP , how to refresh the user list while user list updated ? 
should I write a Runnable Service for polling the user list ?

**Comment by mandy-chessell** [comment]
This connector is a demo connector and the user list is hard coded and so loaded into memory.

If you were writing a security connector for LDAP then you would not load the users in the constructor, but look up the user and their groups in LDAP on each request.  This means the security connector is using the latest information on each request.

**Comment by PeterChenTian** [comment]
> 

OK， Thank you!
