### ISSUE TITLE
Docker repo for VDC images is non-ODPi

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#739]
The docker repository for the VDC images is currently hard-coded to a non-ODPi location (Nigel's): `planetf1/egeria-egeriavdc`, etc.

(See `image` map inside `open-metadata-resources/open-metadata-deployment/charts/vdc/values.yaml`)

Needs to be changed to ODPi, so that images can be updated as-needed by the broader team.

**Comment by planetf1** [comment]
Indeed. This is part of an overall requirement to look at the build pipeline for the docker images.
This needs to be automated, quite likely via the linux foundation jenkins server
I'll likely also add an additional maven profile to allow an easy user-initiated build, and allow the repo name to be overriden
(one of the shortcuts getting a demo env ready quickly)

**Comment by cmgrote** [comment]
Wondering if for development work it would be handy to be able to use a local registry (`localhost:5000`) for re-deployment of changes to some containers to integration test, etc -- presumably part of what #771 will enable (you mention parameterising the repo, I guess / hope this is for the chart as a whole)?

**Comment by planetf1** [comment]
I think configuration of the image repository is important -- I initially chose dockerhub as a quick way to get started. 

In a corporate k8s environment I might well want to push images to my local container registry - perhaps in openshift, or ICP. On IBM cloud I might want to push to the container repo there.

I hadn't thought too much about the local case (I try and avoid this - my machine is too full!) - but no reason why not

The image repository is in fact already configurable on a per-image basis, but it might help to have a single setting for the default registry to use also - meaning if you want all images from one place, just set it as a single parameter for the helm command (or config file). 

And for container build in maven, the intent was indeed to parameterize the repo to write to.

**Comment by planetf1** [comment]
See #771 for further details on the changes made to docker build.

I will keep this issue to track changing the default repository from planetf1 to odpi (or similar -- or even updating the default registry) once we have the required build process & shared ids in place

**Comment by planetf1** [comment]
See https://github.com/odpi/ci-management/issues/44 for a request to the build team to get access to ODPi.

Suggest we use this issue also to parameterize the repo to be used for images.

it's already possible to update the image to be used, but would be useful if by default we could just set a single value for all images (still allowing for individual images to override this)

**Comment by planetf1** [comment]
I'll assign, and update once process in place

**Comment by planetf1** [comment]
See the ci-management issue above for latest updates.
Basically the build is now working but we are trying to get access to the odpi account on dockerhub.
will keep this open until resolved, then will migrate our references to odpi (from planetf1)
