### ISSUE TITLE
[BUG] v4 Gradle build does not publish spring boot fat jars

### ISSUE THREAD

**Issue by lpalashevski** [odpi/egeria#7413]
### Current Behavior

When building using current gradle configuration, spring boot based application modules are build correctly but not published to a maven repository.

This can be verified on maven central snapshot repository:

https://oss.sonatype.org/content/repositories/snapshots/org/odpi/egeria/server-chassis-spring/4.0-SNAPSHOT/
https://oss.sonatype.org/content/repositories/snapshots/org/odpi/egeria/ui-chassis-spring/4.0-SNAPSHOT/

Same is evident when publishing to local maven.

### Expected Behavior

Fat jars published as maven artifacts.

### Steps To Reproduce

local gradle build:

gradle :open-metadata-implementation:user-interfaces:ui-chassis:ui-chassis-spring:publishToMavenLocal

> ls -la .m2/repository/org/odpi/egeria/ui-chassis-spring/4.0-SNAPSHOT
total 1728
drwxr-xr-x  8 xxxxx  staff     256 Feb 16 13:22 .
drwxr-xr-x  9 xxxxx  staff     288 Feb 16 13:22 ..
-rw-r--r--  1 xxxxx  staff    1322 Feb 16 18:19 maven-metadata-local.xml
-rw-r--r--  1 xxxxx  staff  486595 Feb 16 18:19 ui-chassis-spring-4.0-SNAPSHOT-javadoc.jar
-rw-r--r--  1 xxxxx  staff  184826 Feb 16 18:19 ui-chassis-spring-4.0-SNAPSHOT-plain.jar
-rw-r--r--  1 xxxxx  staff  128619 Feb 16 18:19 ui-chassis-spring-4.0-SNAPSHOT-sources.jar
-rw-r--r--  1 xxxxx  staff   34627 Feb 16 18:19 ui-chassis-spring-4.0-SNAPSHOT.module
-rw-r--r--  1 xxxxx  staff   34054 Feb 16 18:19 ui-chassis-spring-4.0-SNAPSHOT.pom

or 

gradle :open-metadata-implementation:server-chassis:server-chassis-spring:publishToMavenLocal

> ls -la .m2/repository/org/odpi/egeria/server-chassis-spring/4.0-SNAPSHOT
total 424
drwxr-xr-x  8 xxxxx  staff    256 Feb 16 18:05 .
drwxr-xr-x  9 xxxxx  staff    288 Feb 16 18:05 ..
-rw-r--r--  1 xxxxx  staff   1326 Feb 16 18:05 maven-metadata-local.xml
-rw-r--r--  1 xxxxx  staff  93286 Feb 16 18:05 server-chassis-spring-4.0-SNAPSHOT-javadoc.jar
-rw-r--r--  1 xxxxx  staff  18184 Feb 16 18:05 server-chassis-spring-4.0-SNAPSHOT-plain.jar
-rw-r--r--  1 xxxxx  staff  14151 Feb 16 18:05 server-chassis-spring-4.0-SNAPSHOT-sources.jar
-rw-r--r--  1 xxxxx  staff  39638 Feb 16 18:05 server-chassis-spring-4.0-SNAPSHOT.module
-rw-r--r--  1 xxxxx  staff  38767 Feb 16 18:05 server-chassis-spring-4.0-SNAPSHOT.pom

same it top level project build/publish is executed.

### Environment

```markdown
/
```

### Any Further Information?

/

**Comment by planetf1** [comment]
I'll take a look next week

**Comment by planetf1** [comment]
See PR for fix, which makes the main jar the one with all dependencies, but also leaves the small jar available via an alternate classifier.
