### ISSUE TITLE
[BUG] deleteGovernanceZone error

### ISSUE THREAD

**Issue by DLaoLiu** [odpi/egeria#7423]
### Current Behavior

(https://github.com/odpi/egeria/blob/main/open-metadata-implementation/access-services/governance-program/governance-program-client/src/main/java/org/odpi/openmetadata/accessservices/governanceprogram/client/GovernanceZoneManager.java)
line: 210 spell error
`final String urlTemplate = serverPlatformURLRoot + "/servers/{0}/open-metadata/access-services/governance-program/users/{1}/governance-zones/{2}/delete}";`
the last symbol '}' is redundant 

### Expected Behavior

the correct as follow
`final String urlTemplate = serverPlatformURLRoot + "/servers/{0}/open-metadata/access-services/governance-program/users/{1}/governance-zones/{2}/delete";`

### Environment

```markdown
- Egeria:3.12
- OS:centos7
- Java:11
- Browser (for UI issues):chrome
- Additional connectors and integration:
```

**Comment by lpalashevski** [comment]
@DLaoLiu thanks for spotting. Feel free to submit PR fixing the typo.
