### ISSUE TITLE
Javadoc errors in IGC Client library

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#743]
looks like Javadoc confused by the angle brackets

/Users/mandy-chessell/CloudStation/Drive/Code/ODPi/egeria-governance/egeria/open-metadata-implementation/adapters/open-connectors/repository-services-connectors/open-metadata-collection-store-connectors/igc-rest-client-library/src/main/java/org/odpi/openmetadata/adapters/repositoryservices/igc/clientlibrary/model/common/Reference.java:545: error: unknown tag: String
     * @return List<String>
                   ^
/Users/mandy-chessell/CloudStation/Drive/Code/ODPi/egeria-governance/egeria/open-metadata-implementation/adapters/open-connectors/repository-services-connectors/open-metadata-collection-store-connectors/igc-rest-client-library/src/main/java/org/odpi/openmetadata/adapters/repositoryservices/igc/clientlibrary/model/common/Reference.java:562: error: unknown tag: String
     * @return List<String>
                   ^
/Users/mandy-chessell/CloudStation/Drive/Code/ODPi/egeria-governance/egeria/open-metadata-implementation/adapters/open-connectors/repository-services-connectors/open-metadata-collection-store-connectors/igc-rest-client-library/src/main/java/org/odpi/openmetadata/adapters/repositoryservices/igc/clientlibrary/model/common/Reference.java:579: error: unknown tag: String
     * @return List<String>
                   ^
/Users/mandy-chessell/CloudStation/Drive/Code/ODPi/egeria-governance/egeria/open-metadata-implementation/adapters/open-connectors/repository-services-connectors/open-metadata-collection-store-connectors/igc-rest-client-library/src/main/java/org/odpi/openmetadata/adapters/repositoryservices/igc/clientlibrary/model/common/Reference.java:596: error: unknown tag: String
     * @return List<String>
                   ^

**Comment by mandy-chessell** [comment]
A couple more ...

/Users/mandy-chessell/CloudStation/Drive/Code/ODPi/egeria-governance/egeria/open-metadata-implementation/adapters/open-connectors/repository-services-connectors/open-metadata-collection-store-connectors/igc-rest-client-library/src/main/java/org/odpi/openmetadata/adapters/repositoryservices/igc/clientlibrary/model/generated/v11502sp3/AnalysisProject.java:27: error: bad HTML entity
     * The 'short_&_long_description' property, displayed as 'Short & Long Description' in the IGC UI.
                  ^
/Users/mandy-chessell/CloudStation/Drive/Code/ODPi/egeria-governance/egeria/open-metadata-implementation/adapters/open-connectors/repository-services-connectors/open-metadata-collection-store-connectors/igc-rest-client-library/src/main/java/org/odpi/openmetadata/adapters/repositoryservices/igc/clientlibrary/model/generated/v11502sp3/AnalysisProject.java:27: error: bad HTML entity
     * The 'short_&_long_description' property, displayed as 'Short & Long Description' in the IGC UI.
                                                                    ^

**Comment by mandy-chessell** [comment]
/Users/mandy-chessell/CloudStation/Drive/Code/ODPi/egeria-governance/egeria/open-metadata-implementation/adapters/open-connectors/repository-services-connectors/open-metadata-collection-store-connectors/igc-rest-client-library/src/main/java/org/odpi/openmetadata/adapters/repositoryservices/igc/clientlibrary/model/generated/v11502sp3/ColumnAnalysisSummary.java:27: error: bad HTML entity
     * The 'short_&_long_description' property, displayed as 'Short & Long Description' in the IGC UI.
                  ^
/Users/mandy-chessell/CloudStation/Drive/Code/ODPi/egeria-governance/egeria/open-metadata-implementation/adapters/open-connectors/repository-services-connectors/open-metadata-collection-store-connectors/igc-rest-client-library/src/main/java/org/odpi/openmetadata/adapters/repositoryservices/igc/clientlibrary/model/generated/v11502sp3/ColumnAnalysisSummary.java:27: error: bad HTML entity
     * The 'short_&_long_description' property, displayed as 'Short & Long Description' in the IGC UI.
                                                                    ^

**Comment by cmgrote** [comment]
Don't worry about finding all of them, I'm sure there are lots -- I'll do an in-depth scan on my side to correct!

**Comment by mandy-chessell** [comment]
Just seems to be a couple of issues that repeat ... :)

**Comment by cmgrote** [comment]
To save me digging around for how to generate them to re-test on my side: any pointer on a quick command to run the Javadoc generation? 🙏

**Comment by mandy-chessell** [comment]
From IntelliJ - Tools menu -> Generate Javadoc

**Comment by cmgrote** [comment]
Thanks, found it!  Surprised it didn't show up from the "Help" menu 😕 

I've noticed a few problems elsewhere as well -- shall I just go ahead and do a cleanup of the JavaDocs wherever I'm able?
