### ISSUE TITLE
Slight mismatch in task for installing Egeria server

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#745]
In the readme for task-installing-egeria.md we say that within the 'server' directory there is a a directory for the OMAG Server Platform.
The example command is shown as 'cd servers/omag-server*' (note tha plural 'servers').

In my egeria-install I unpack the tar.gz and I have an 'egeria-omag-0.3-SNAPSHOT/server' directory, which directly contains the server-chassis-spring-0.3-SNAPSHOT.jar.

**Comment by cmgrote** [comment]
That was one of my fixes -- @mandy-chessell are the tutorials in an update-able state for PRs against these kinds of points, or still working on further areas and we should continue to hold off?

**Comment by mandy-chessell** [comment]
Its ok to correct the install tutorial - working on the admin text to break down the descriptions to cover the different OMAG server "personalities".  Had to put it to one side to finish all of the changed needed for release 1.
