### ISSUE TITLE
Add a customisable FVT for subject area omas

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#747]
Add a customisable FVT for subject area omas - to allow any serverName and any userId to be used to run the Subject Area OMAS FVT

**Comment by planetf1** [comment]
See https://github.com/odpi/egeria/issues/2524

Suggest we ensure we can easily and regularly run the FVT 

Depends upon:
 - Switch containers to run the full metadata distribution (#2375)
 - FVT execution (#426)

This issue needs to:
 * Ensure this FVT is appropriately packaged within the distribution files
 * Provide instructions to run these tests against the 'standard' environment (this could be a docker/kubectl 'exec' command to launch the test - whilst making the tests as configurable as needed
 * Subsequently automate the execution of these specific tests

**Comment by planetf1** [comment]
persue in #426
