### ISSUE TITLE
[question] model for database table alias

### ISSUE THREAD

**Issue by runqch** [odpi/egeria#7511]
### Existing/related issue?

How to represent database table alias

### Current Behavior

For Table, we use `RelationalTable` entity to represent a table.
For View, we use `RelationalTable` + `CalculatedValue` Classification to represent a view. 
By this we can distinguish table and view by whether has a `CalculatedValue` attached.

How about table alias? How to represent it and how to distinguish it from table and view?

### Expected Behavior

Have a proper way to represent database Table Alias.

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

**Comment by planetf1** [comment]
Specifically, I understand the question here is about DB2 Aliases https://www.ibm.com/docs/en/db2-for-zos/11?topic=concepts-aliases

The term 'alias' is also used for
 - temporary use within sql statements (ie `select aaa from bbb as ccc`)
 - with connection catalogs (db2, sql server) ie using a name to represent a database endpoint to connect to

**Comment by runqch** [comment]
@planetf1 

Thanks. Yes. The `Alias` here means `An alias is a substitute for the three-part name of a table or view`

**Comment by planetf1** [comment]
It's possible a similar question would apply to
 - Filesystem symbolic links
 - hostname aliases
