### ISSUE TITLE
Add Krisha as contributor

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#7547]
Krishna ( @ilovechai ) is now a Contributor following a vote by the maintainers:

- [x] Add to contributors file
- [x] Add access permissions
- [ ] Assign contributor badge

**Comment by planetf1** [comment]
@ilovechai Were you assigned your contributor badge?

**Comment by ilovechai** [comment]
@planetf1 not yet

**Comment by planetf1** [comment]
@ilovechai Thanks for confirming. I'm checking with the linux foundation - we'll get this sorted.

**Comment by planetf1** [comment]
@ilovechai I checked, and the badge should be issued to your email address in https://github.com/odpi/egeria/blob/main/CONTRIBUTORS.md

Can you check any spam?

If you still don't see it, I'll put you in touch with the person at the LF who issues the badges

**Comment by planetf1** [comment]
Closing. please re-open if there are any issues
