### ISSUE TITLE
[BUG] Fix Rex view service to not use propertyNames when returning an entity

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#7565]
### Existing/related issue?

https://github.com/odpi/egeria-react-ui/pull/634

### Current Behavior

as per https://github.com/odpi/egeria-react-ui/pull/634 the react ui was looking at the entity for properties - it expected propertyNames to be populated. At Egeria v4 this is not populated. The fields are still being included in the entity but do not contain any content. This field should be removed from the Entity. 

### Expected Behavior

view service not to send propertyNames field in an entity

### Steps To Reproduce

run Rex and view an entity and look at the flow from the view service. 

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

**Comment by planetf1** [comment]
does this explain https://github.com/odpi/egeria-react-ui/issues/637 ?

If so I think we need a v4 fix
