### ISSUE TITLE
Add new PurgeDelete Event

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#757]
Soft-delete is an optional capability for an open metadata repository.  This means a repository may purge an entity or a relationship that is still active.

The current purge event only sends the guid of the instance being purged, whereas the delete event (used with a soft-delete) includes the full instance object.

These events are received either by another repository, or an OMAS that is, say, configuring external technology.

Having just a purge event without the delete event can make it hard for consuming technologies that do not directly support the guid to identify what has been purged - particularly for relationships which may not be first class objects in the repository.

This feature therefore adds a new event type for a combined delete and purge event that passes the instance object in the same way that the soft-delete event does.  It is used by repositories that do not support soft-delete to say this is a combined delete and purge event.

Repositories that support soft-delete would continue to send two events - the delete event when delete occurs (allowing other technologies remove or soft-delete their reference copies or derived definitions) and purge when the soft-deleted instance is finally deleted.

**Comment by cmgrote** [comment]
Now that this is implemented in base OMRS, and implemented in IGC proxy (eventmapper), are we OK to close the issue?
