### ISSUE TITLE
IGC client library module should be a submodule of ibm-igc-repository-connector

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#758]
The IGC client library is a reusable client library for calling the IBM Information Governance Catalog.  In the Egeria context, however, it is only used by the IGC OMRS Repository Connector.  Therefore, the igc-client-library module should be a submodule of ibm-igc-repository-connector.  This will not effect its reusability in other contexts, and avoids confusion that it implements a repository connector.

**Comment by cmgrote** [comment]
Good point -- on it!

**Comment by cmgrote** [comment]
So...  learning a bit more about Maven packaging, and it sounds like a bit of a nightmare to have code in one module (`ibm-igc-repository-connector`) that itself has a sub-module (`igc-rest-client-library`)... (Can't use `jar` packaging for the parent module, which means `ClassNotFoundException`s for connector instantiation via admin services, etc.)

Sounds like simplest suggestion is to create two sub-modules of a parent module, and leave the parent module code-less (https://stackoverflow.com/questions/18733729/packaging-jar-is-invalid-aggregator-project-need-pom-as-packaging).

Ok to go with this structure?

- `ibm-igc-repository-connector`
    - `igc-rest-client-library`
    - `igc-repository-connector`
