### ISSUE TITLE
[BUG] updateTerm error

### ISSUE THREAD

**Issue by PeterChenTian** [odpi/egeria#7582]
### Current Behavior

when create has-a relationship between termA and termB,  the subjectArea OMAS automatically set spineObject to termA, but in the updateTerm function , the addCategorizationRelationship failed, it looks like the deleted relation was detected and status is delete, this will cause the update relation **validateRelationshipIsNotDeleted** error and the termCategorization relation of termA lost.

```
org.odpi.openmetadata.repositoryservices.ffdc.exception.RelationshipNotKnownException returned message of OMRS-REPOSITORY-404-012 The TermCategorization relationship identified with guid 9dfe7b0d-552b-4168-a9ae-d6307df9edfb passed on the getRelationship call is soft-deleted in the open metadata repository cocoMDS1 and stacktrace of 
OCFCheckedExceptionBase{reportedHTTPCode=404, reportingClassName='org.odpi.openmetadata.repositoryservices.localrepository.repositorycontentmanager.OMRSRepositoryContentValidator', reportingActionDescription='getRelationship', reportedErrorMessage='OMRS-REPOSITORY-404-012 The TermCategorization relationship identified with guid 9dfe7b0d-552b-4168-a9ae-d6307df9edfb passed on the getRelationship call is soft-deleted in the open metadata repository cocoMDS1', reportedErrorMessageId='OMRS-REPOSITORY-404-012', reportedErrorMessageParameters=[TermCategorization, 9dfe7b0d-552b-4168-a9ae-d6307df9edfb, getRelationship, cocoMDS1], reportedSystemAction='The system is unable to retrieve the properties for the requested relationship because the supplied guid is for a relationship that has already been deleted.', reportedUserAction='The guid is supplied by the caller to the OMRS.  It is most likely to be a timing issue where the relationship was deleted by another process since the guid was retrieved.  However, there is a  possibility of a logic problem that has corrupted the guid.', reportedCaughtException=null, reportedCaughtExceptionClassName='null', relatedProperties=null}
        at org.odpi.openmetadata.repositoryservices.localrepository.repositorycontentmanager.OMRSRepositoryContentValidator.validateRelationshipIsNotDeleted(OMRSRepositoryContentValidator.java:3098)
        at org.odpi.openmetadata.adapters.repositoryservices.inmemory.repositoryconnector.InMemoryOMRSMetadataCollection.getRelationship(InMemoryOMRSMetadataCollection.java:830)
        at org.odpi.openmetadata.repositoryservices.localrepository.repositoryconnector.LocalOMRSMetadataCollection.validateRelationshipCanBeUpdated(LocalOMRSMetadataCollection.java:3605)
        at org.odpi.openmetadata.repositoryservices.localrepository.repositoryconnector.LocalOMRSMetadataCollection.updateRelationshipProperties(LocalOMRSMetadataCollection.java:5444)
        at org.odpi.openmetadata.repositoryservices.enterprise.repositoryconnector.EnterpriseOMRSMetadataCollection.updateRelationshipProperties(EnterpriseOMRSMetadataCollection.java:3948)
```

### Expected Behavior

keep termA  termCategorization  relation normally

### Environment

```markdown
- Egeria:3.12
- OS: centos9
- Java: 11
- Browser (for UI issues): chrome
- Additional connectors and integration:
```

**Comment by mandy-chessell** [comment]
@davidradl could you have a look at this ...

**Comment by davidradl** [comment]
HI @PeterChenTian  @mandy-chessell
I have had a quick look. It looks like the subject are code goes to the generic handler and calls the linkElementToElement method. In this method:
1) repositoryHandler.getRelationshipsBetweenEntities , can you confirm that this method should return deleted relationships?
2) If we get back a deleted relationship we should either 
     - restore the deleted relationship and update it
     or
     -  create a new relationship
     
Which would be best? I am thinking restore and update might be better, as if we create a new relationship and ever attempt to restore the old one we would need to handle the case when there are 2 termCategorisation relationships between the same term and category but this relationship is not multi-link.

I think we should be able to update the Subject Area FVT to test this scenario. @PeterChenTian once we agree on the design - are you interested in coding this ? I could advise (if required), review and merge.

**Comment by PeterChenTian** [comment]
> 

Hi David, as you mentioned

1. repositoryHandler.getRelationshipsBetweenEntities  I will check this again. 
2. yes, I think restore this relation is better.

OK, I will try to fix it

**Comment by davidradl** [comment]
@PeterChenTian @mandy-chessell (the project leader) may have some thoughts on this. 

The only complexity I see here is for multi link relationships. Currently this method is links 2 entities with the supplied  relationship details; if it finds an existing relationship it attempts to update its properties. This makes no sense for[ multi link](https://egeria-project.org/concepts/uni-multi-link/?h=link) relationships. I suggest the method throws a new error if called with a relationshipDef (as determined by attachmentTypeGUID and attachmentTypeName) that is multilink.

**Comment by mandy-chessell** [comment]
The linkElementToElement relationship is not for multi-link relationships - there is a separate method for multi-link.  However it is ok, none of the glossary relationships are multi-link.

getRelationshipBetweenEntities would only return deleted entities if the status DELETED is requested.

Method linkElementToElement() should always create a new relationship if the previous relationship is deleted rather than restore the previous relationship because the previous relationship was removed for a reason.

**Comment by PeterChenTian** [comment]
same code different performance on windows and centos, on windows it is ok , but deleted relation returned on centos, 
I will debug the getRelationshipBetweenEntities method

**Comment by PeterChenTian** [comment]
I add some debug info after **repositoryHandler.getRelationshipsBetweenEntities** like this
![debug](https://user-images.githubusercontent.com/19702268/229136449-7e789bf4-92fc-4b37-b56a-8908f8b245e3.png)
the relation found on centos,and status is active, but there come with some watchdog action show delete relation 
and cause exception
![info](https://user-images.githubusercontent.com/19702268/229138100-ca89c3a6-8b9e-45a4-ad1f-d68643b08c27.png)
