### ISSUE TITLE
Explain and understand how the OMRSRepositoryConnector find methods work.

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#759]
Pull request #742 illustrated that the behaviour of the find methods on the OMRSRepositoryConnector are not well understood.  This issue is to add some more documentation.

**Comment by cmgrote** [comment]
JavaDoc updates are merged, suggest further documentation should be tracked by blog entry pending under #1621 ?

**Comment by cmgrote** [comment]
Good reminder — @grahamwallis is your blog pending publishing? =)

**Comment by grahamwallis** [comment]
Yup - please see https://www.odpi.org/category/blog/egeria

**Comment by cmgrote** [comment]
Think we can close this one, then?
