### ISSUE TITLE
Add Liviu Enache to contributors

### ISSUE THREAD

**Issue by lpalashevski** [odpi/egeria#7678]
- [x] Add member to CONTRIBUTORS.md (top level)  - PR for the list changes #7677 
- [x] Add member to organization contributors group
- [ ] Issue badge
- [x] Notify member

**Comment by planetf1** [comment]
* Invited Liviu to contributors group (he needs to respond, and join the odpi github organization. ANy problems let me know)

**Comment by lpalashevski** [comment]
cc @LeeVi3w

**Comment by planetf1** [comment]
@LeeVi3w Your badge should now be issued to the email address in https://github.com/odpi/egeria/blob/main/CONTRIBUTORS.md -- can you confirm you have it ok?

**Comment by planetf1** [comment]
Closing. please re-open if there are any issues
