### ISSUE TITLE
Add Mihai Iliescu to maintainers

### ISSUE THREAD

**Issue by lpalashevski** [odpi/egeria#7679]
- [x] Add member to MAINTAINERS.md - PR for the list changes #7677 
- [x] Add member to organization contributors group
- [ ] Issue badge
- [ ] Notify member

**Comment by lpalashevski** [comment]
cc @MihaiIliescu

**Comment by planetf1** [comment]
@MihaiIliescu The badge should now be issued. Can you check you received ok? Will have used the email address from https://github.com/odpi/egeria/blob/main/CONTRIBUTORS.md

**Comment by planetf1** [comment]
Closing. please re-open if there are any issues
