### ISSUE TITLE
Installation using docker

### ISSUE THREAD

**Issue by lucas-carrijo** [odpi/egeria#7683]
I've been trying to use the guide in the following link to install egeria using docker on ubuntu, I can download the image, create the container but I can't access anything in the browser, could someone tell me if there is any other configuration that should be done

https://egeria-project.org/education/tutorials/docker-tutorial/overview/#downloading-the-egeria-docker-image

**Comment by planetf1** [comment]
@lucas-carrijo The docker image above runs the core of egeria, something we call the 'server chassis'. Think of it as a web application server. 

It can accept REST api requests & return responses. That web page gives a few more examples.

If you're looking for a more complete environment to try out or learn egeria, I would recommend using our Kubernetes charts, as these contain not just this server chassis (in fact multiple!), but also user interfaces for looking at assets, types, instances, kafka for inter-server communication & some demo python code in notebooks.

I'd recommend the 'running egeria' day at https://egeria-project.org/education/egeria-dojo/running-egeria/running-egeria-intro/ which will walk you through a few different setups, and explain how to use.

You will need to have a Kubernetes implementation installed. This is available within docker desktop, and also alternatives like Rancher desktop. I would recommend giving 12GB to your container environment to make sure everything will run - (simple setups should run in 8GB)
There is also specific information on the charts at https://egeria-project.org/guides/operations/kubernetes/

**Comment by planetf1** [comment]
Closing for now. please reopen if you have any difficulties

**Comment by planetf1** [comment]
Both the 'strimzi' and 'config' pods are not running correctly.

Can you check how much memory you have allocated -- this chart can probably work in 6GB or so, but we recommend/test 12GB for the lab chart

Which kubernetes runtime are you using? (ie ibm cloud, aks, rancher, docker etc)

If you have the option to change kubernetes version (rancher) make sure you are running the 'stable' version (or if you prefer 'latest')

You can also get logs from strimzi ie
```
kubectl logs strimzi-cluster-operator-687b8c77db-4xxcs
kubectl logs strimzi-cluster-operator-687b8c77db-4xxcs --previous
```

**Comment by lucas-carrijo** [comment]
I understand I'll check the memory, but apparently they worked, i'm using minikube

![image](https://github.com/odpi/egeria/assets/58045516/a4111450-5824-4d43-b538-a4d4d1cc77c6)

but when trying to run the command to open the interface in the browser, this output only appears

![image](https://github.com/odpi/egeria/assets/58045516/dd7f28c2-ad8e-49f0-aa21-ffcc313c1060)

**Comment by planetf1** [comment]
Ok - so your pods are running. However there are a high number of restarts - normally if you've not been doing any cluster changes, and it's in a dev environment I'd have expected 0, or perhaps 1 or 2 if there are timing issues on startup.

YOu have a high number of restarts - I would suggest checking the logs of all those pods (the `--previous` option especially, as you want to see why it previously failed). Often this is a resource issue ie not enough memory.

I can't give specifics as I am currently mostly using openshift(cloud) and rancher desktop(local/macOS) - but perhaps check the current sizing as per https://www.shellhacks.com/minikube-start-with-more-memory-cpus/

For the UI -- that command forwards traffic for port 8091 on the local machine to port 8091 within the kubernetes cluster .. on that local machine (which I presume is your laptop/desktop?)

To actually view the UI you would go to https://localhost:8091/org (the 'org' is the default name of the organization/tenant)

**Comment by lucas-carrijo** [comment]
I'm using an ubuntu virtual machine, I did the process again and now the restarts stopped, I believe it could really be the memory, I only have 7.7GB, I'll increase it and try again, thank you very much for your help friend

![image](https://github.com/odpi/egeria/assets/58045516/722ca008-18cf-45cc-ac2c-f8e56f3f6269)

**Comment by planetf1** [comment]
Yes - that is normal for the first two. They are 'jobs' which just run once to set things up.

I'd have thought 7.7GB would be ok for this chart.. but worth trying more.

As an alternative to running an Ubuntu VM with minikube, there are other alternatives that support macOS and windows -- such as 'rancher desktop' and 'docker desktop' (needs license for commercial use). Within linux itself, I have also tried microk8s in the past. Though minikube should be fine, it's been around a long time.

**Comment by lucas-carrijo** [comment]
I understand friend, let me ask you one more last question, I'm just having trouble viewing the UI, let's say my virtual machine has the ip 10.1.1.11 I can't access the interface using the address https://10.1.1.11/org ? everything looks fine, i don´t know why i can´t acess the IU in browser
