### ISSUE TITLE
[Enhancement] Add self-build Dockerfile for egeria

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#7684]
### Please describe the new behavior that that will improve Egeria

Create 'self-build' Dockerfile

This Dockerfile can be self-contained, ie it will build egeria from source, and create a suitable runtime container.
A multi-stage build can be used to ensure the runtime is kept lean.
Build arguments can be used to specify branch/commitid etc 

This could be an alternative (not replacement) to the existing Dockerfile
 - easier to just copy around a single file
 - easier to add into a CI/CD process -- at least as an example
 - easier to document how to build the image
 - removes dependence on developer machine environment (ie versions of java)
 
 
 Our very early dockerfiles (as well as, for example, the apache atlas dockerfile) used this approach. However egeria took a long time to build - at points getting well beyond 1 hour including tests, and even 40 mins without. Doing this twice - once native, and then again in a container, was really inefficient and slow, hence the current mechanism
 
 With the build now refactored to use gradle, builds are a lot lot quicker, making this approach much more ameniable

### Alternatives

Use the Existing Dockerfile. This requires:
 - local build (ie on macOS)
 - copying assembly to correct location
 - running docker build

### Any Further Information?

I propose providing such a Dockerfile as an alternative example.

The possible downsides are
 - what testing is done of the alternate version

### Would you be prepared to be assigned this issue to work on?

yes

**Comment by planetf1** [comment]
The first version of this has been done. Issues should be raised for any improvements

**Comment by dwolfson** [comment]
@planetf1 Does this start from your local (possibly modified) source code or does it pull in a fresh copy from git and build it - seems to do the latter though I haven't inspected it..

**Comment by planetf1** [comment]
> @planetf1 Does this start from your local (possibly modified) source code or does it pull in a fresh copy from git and build it - seems to do the latter though I haven't inspected it..

The latter. It's an entirely self-contained docker build. All you need is that single file - so you could copy it to docker.io, openshift etc & just build from that. Nothing else needed, no reliance on local context or installed software
