### ISSUE TITLE
New maven profile for docker build

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#771]
Currently the docker images required to build egeria, configuration tools, atlas & other components needed for our VDC demo, are built manually.

As a first step to improve this I plan to
 - Add a new profile to enable the following (default is no docker build, since it requires additional tools)
 - use the dockerfile-maven plugin to manage the execution of docker build (Apache 2.0 licensed)

This is effectively just automating what today is done by following the README instructions for docker build.

I will also add a parameter to define the repository to use, in order to address #739 

Some useful notes can be found at https://stackoverflow.com/questions/27767264/how-to-dockerize-maven-project-and-how-many-ways-to-accomplish-it

redhat's 'source-to-image' offers another approach for git-centric building, but this is a more significant change from what we have currently, and also requires more tooling that is not available from maven central,so I will take the maven approach first, for speed and simplicity, and later evaluate s2i

**Comment by cmgrote** [comment]
Looks nice and straightforward for Maven stuff -- if it results in super-small images, which presumably it will given the right second base image is chosen, then agreed this looks like the ideal direction over `s2i`.

**Comment by planetf1** [comment]
As an update ref s2i ... knative build is now the in thing for building containers from source 
 -> https://blog.openshift.com/knative-building-your-serverless-service 

My conclusion -- it's an evolving area, many possibilities, keep it simple and generic for now.

**Comment by planetf1** [comment]
Initial build support added.

To enable

mvn clean install -Pdocker -Ddocker.repo=planetf1

docker.repo is nornally your userid for dockerhub, but actually relates to the namespace within a registry for the image.

This is mandatory, and maven-enforce is used to produce an error if it is not provided when the plugin is in use

-Ddocker.registry

can be used to specify an alternative registry to post images to

Two issues found with the spotify plugin 
https://github.com/spotify/dockerfile-maven/issues/272 - attempting to build on a remote docker host fails
https://github.com/spotify/dockerfile-maven/issues/273 - MacOS's default docker configuration using the OSX keychain will prevent image push from working

Both are noted in readme as well as reported on github. 

The spotify docker plugin being used is on maven central and Apache 2.0 licensed.
Both it & maven-enforcer (see below) have had their version defined using <PluginManagement> rather than properties, as this is a superior model moving forward.

Enabled one image so far.
Next commit will add support for the other docker images

**Comment by planetf1** [comment]
Note this issue is used to enable driving the build from maven only - any changes to the actual images will be covered in other issues.

**Comment by planetf1** [comment]
After some testing, the invocation is now

mvn clean install -Ddocker -Ddocker.repo=planetf1

This has been changed due to the way profiles are activated. Now I use a system property to cause a profile to be activated, since then it will be correctly inherited and picked up whichever level the build is performed from (once under 'docker' it's assumed to be done always .. as why else would you be there). This was tricky using profiles as I wanted to refer to the docker submodule, or subsubmodule, or subsubsubmodule...

Note that ideally it's probably better to build in the 'deploy' phase. This may become relevant if any of the image builds need to make use of build time artifacts (currently they do not). However the deploy phase also currently assumes you are pushing maven artifacts to nexus, and without configuration this fails..... this is why currently the build is bound to the 'install' phase.
