### ISSUE TITLE
[Enhancement] Egeria file layout proposal to simplify deployment

### ISSUE THREAD

**Issue by dwolfson** [odpi/egeria#7766]
### Please describe the new behavior that that will improve Egeria

On today's  [community call we](https://wiki.lfaidata.foundation/display/EG/2023-06-28+CM+-+Deployments) discussed a proposal to update the file layout of Egeria to simplify deployment in a production environment. We are currently considering these changes for the 4.3 release of Egeria (tentatively planned for September, 2023). Updates would be required to the Egeria's assembly, labs and helm charts. 

The current file layout is:

![image](https://github.com/odpi/egeria/assets/1976757/f7d59653-5bf4-4dc3-a860-b1106bd4721c)

While the current layout works, we propose changes  to clarify and simplify the structure. The proposal  suggests grouping of:

- optional components
- log storage locations
- convenient directory mount points
- more use of common conventions

The following diagram shows the proposed changes.

![image](https://github.com/odpi/egeria/assets/1976757/eec31c62-3e04-486d-97b9-599ca68842ca)

Suggested changes include:

- a **var** directory for logs and ssl information
- an **opt** directory for optional components such as samples and pre-built metadata archives
- Boxes colored green are suggested directory mount points. For example, logs may often be shared or aggregated with others. 
- Clearer separation between the Egeria OMAG Server Platform and the Egeria UI Application.

As always, we are looking for feedback from the community as we explore these proposals. Attached below is a draw.io file with the source for the diagrams above. We look forward to your thoughts and comments - and especially welcome your ideas on how we can continue to simplify deployment.

[egeria_file_layout_community.drawio.zip](https://github.com/odpi/egeria/files/11896572/egeria_file_layout_community.drawio.zip)

### Would you be prepared to be assigned this issue to work on?

Yes

**Comment by mandy-chessell** [comment]
These are the current new layouts implemented so far.  

For the OMAG Server Platform runtime (see new module https://github.com/odpi/egeria/tree/main/open-metadata-distribution/omag-server-platform) the assembly includes samples and utilities designed to allow someone to explore the platform capabilities.  It includes the Docker file to build a new docker container from the assembly.

For the UI Application (see new module https://github.com/odpi/egeria/tree/main/open-metadata-distribution/egeria-ui-application) simply provides the application jar and associated files.

**Comment by mandy-chessell** [comment]
The new file layout is implemented here: https://github.com/odpi/egeria/tree/main/open-metadata-distribution/omag-server-platform
