### ISSUE TITLE
Split postgresql data loading from IGC configuration in VDC helm chart

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#780]
Currently the postgresql-init container runs ansible scripts that both
 * Load sample data into the VDC environment (postgresql)
 * Load sample data into IGC
 * Invoke IGC's 'IMAM' capability to import sample data metadata into IGC 

It would be desirable to separate the two, so that IGC is not required, yet sample data can still be loaded
Additionally since IGC sits outside k8s currently it may be better to invoke the IGC data loading activities externally - clearer separation

**Comment by cmgrote** [comment]
Approach I'll go for is to separate into two operations:

1. Load sample data (to wherever: postgresql, mariadb, DB2, etc)
1. Load sample metadata (to wherever: IGC, etc)

I'll then use an (optional) outer orchestration to allow these two to run in sequence as a single step, while still allowing the more granular "only the first" to run, or "only the second" to run (when the second isn't dependent on the first).

**Comment by planetf1** [comment]
Thanks.

I think for the helm charts, running 1/ as part of the initialization makes sense (it's the way the other components are setup), and will work when we don't have IGC too. I could also enable/disable via a configuration option. I do think it's important to have the ability to create the sample data within k8s, and to ensure this has no IGC dependency. If possible it would be useful if this did not depend on SSH and could only use external service APIs - as this would allow re-use of existing postgresql container images and charts, though I recognize that is potentially a further step.

running 2/ externally is most likely appropriate for IGC which sits outside the cluster. 

We're still discussing other metadata stores, though they would likely be inside for demo purposes, but could be significantly different in their approach

An outer orchestration would make sense either in the case where we want to run all the IGC stuff together, or indeed when deploying the sample data in a non k8s environment, but I don't think we'd use it in other cases within k8s.

**Comment by cmgrote** [comment]
Ok, here's what I've worked out (just doing some final testing before committing):

![base-integration](https://user-images.githubusercontent.com/5864283/53409462-dc0b3b00-39b8-11e9-836b-0158d61ee050.png)

So we have:

- use of official postgresql container, untouched, exposing its default 5432 port (config like password is passed via officially-documented env vars)
- use of a k8s Job (temporal) to run a minimal Alpine container with the database clients (postgresql, mariadb, etc) in it -- first clones just the sample data portion of Egeria repo, then runs the SQL scripts directly via the db clients to connect remotely to the container above to deploy the sample data (orchestrated via initContainers to ensure container above is up and running before loading); and once successfully completed will remove itself (if it fails will stay behind so you can review its logs)
- IGC is now its own distinct entity -- could still be a separate server, but I've also built some containers we can use internally for quick testing purposes. This will have Ansible embedded within it for its own metadata loading process (which we can kick-off manually via a `kubectl exec` against the IGC container / running directly against a remote system if outside the cluster).

None of the containers have SSH any longer, and only the IGC container requires any extra container settings (not privileged anymore, but still some others).

**Comment by planetf1** [comment]
Sounds good. In particular using the official container is far preferable, along with using the standard service protocol (ie over 5432 in this case) - I wasn't able to do this before given the need for ssh. There is also a postgresql helm chart which has the ability to run scripts at startup, but it's somewhat more restrictive than our data loading scripts, so I'd probably go with just the container. (there was also a bug in it, but now fixed).

One future change is to add persistence to all the containers, at which point we may need to again review what is done in the init (it may already be just fine)

**Comment by planetf1** [comment]
One additional point - there's probably no need to keep the job active if initialization fails. The logs should still be available since though the pod has completed running, it's not deleted.

**Comment by cmgrote** [comment]
> One future change is to add persistence to all the containers, at which point we may need to again review what is done in the init (it may already be just fine)

I agree with your point on (for now) not having persistence making life easier (to just delete everything and test again) — so I will park that item for now...

> One additional point - there's probably no need to keep the job active if initialization fails. The logs should still be available since though the pod has completed running, it's not deleted.

Jobs don’t run as part of the Pod, they’re an external, temporal resource. Leaving them around doesn’t leave them running, it just let’s you view their log in the case of failures; when successful the resource itself is entirely removed (including its log). Another “interesting” thing I just found out is that they execute sequentially — which while I don’t think is ideal, does give a fair degree of control over orchestration... (99% of the time in the Job is waiting on the Pod they’re going to configure to be ready; the actual “work” is done pretty much instantly after that, but it would be nicer IMHO if we had multiple Jobs waiting in parallel and executing as and when their dependent Pods / Services are available.)

**Comment by planetf1** [comment]
I've not tried jobs myself yet, but the docs at https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/ appear to indicate that when the job completes, it is left around - so that logs can be examined? Though there is the capability to remove automatically. (I was referring to the job pod(s))

**Comment by cmgrote** [comment]
Sorry, should have been clear: it's Helm that has the capability to auto-delete the job on success (see "hook-delete-policy" at https://github.com/helm/helm/blob/master/docs/charts_hooks.md)
