### ISSUE TITLE
VDC helm chart - add support for external cloud kafka - such as Event Streams

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#782]
Currently the VDC chart depends on a kafka chart, which means we deploy an instance of kafka as part of installing VDC.

It would be useful to provide -- as an option -- the ability to use an existing cloud based kafka service.
For example on IBMcloud this could be IBM Event Streams.
A similar approach could be taken for google, azure etc.

A simple optional setting in 'values' could either enable internal or external kafka
Additional settings could provide the fixed endpoint and authorization data

**Comment by cmgrote** [comment]
I'm thinking we should be able to "abstract" this through the k8s `service` objects we're already using; but in cases where the back-end is actually external to the cluster this `service` would just use `ExternalName` (
https://kubernetes.io/docs/concepts/services-networking/service/#externalname)

Then hopefully we can still re-use the same credentials config (just different values), and exactly the same service names -- so any resources *in* the cluster that depends on such a service can still refer to the service the same way, irrespective of whether it is actually deployed in-cluster or externally (?)

**Comment by cmgrote** [comment]
Also requires a conditional dependency import -- working on testing it out now against a cluster-external Kafka setup...

**Comment by planetf1** [comment]
I can try it out against the IBM cloud service too at some point.

**Comment by planetf1** [comment]
It would also be worth considering allowing the topic names to be set/prefixed . WHen deploying against a shared kafka service we may want multiple instances of vdc to share the same kafka.

However it also makes sense to try and make small, incremental changes - easier to merge, integrate, test, track & prioritize - so we could raise a separate issue for this
