### ISSUE TITLE
VDC chart : IGC import failure

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#783]
The postgresq-init pod runs ansible scripts to load coco pharma sample data, and glossary into IGC & postgres

The import tends to fail if the vdc chart is reinstalled without IGC manually being cleared out (delete all import areas)

It would be useful if the scripts could ensure the import works reliably, perhaps by clearing out the import area prior to re-import

The error that occurs is

```
TASK [IBM.infosvr-metadata-asset-manager : import_areas - remove connectivity configuration files] ***
ok: [igc.openmetadata.ibmcloud.com] => (item=CocoPharma_SampleFiles)

TASK [IBM.infosvr-metadata-asset-manager : import_areas - re-import existing import areas via IMAM (skipping local files)] ***
failed: [igc.openmetadata.ibmcloud.com] (item=CocoPharma_SampleFiles) => {"changed": true, "cmd": "source dsenv && /opt/IBM/InformationServer/ASBNode/bin/imam.sh -af /tmp/isauth.Chlcsa -a reimport -i 'CocoPharma_SampleFiles' --checkEventDiff", "delta": "0:02:25.399140", "end": "2019-02-22 09:08:21.969233", "failed_when_result": true, "item": {"assets_to_import": ["folder[/data/files/CocoPharma]"], "dcn": {"name": "LOCALFS"}, "description": "Loads metadata for CocoPharma sample files", "hostname": "IGC.OPENMETADATA.IBMCLOUD.COM", "metadata_interchange_server": "igc.openmetadata.ibmcloud.com", "name": "CocoPharma_SampleFiles", "type": "LocalFileConnector"}, "msg": "non-zero return code", "rc": 247, "start": "2019-02-22 09:05:56.570093", "stderr": "", "stderr_lines": [], "stdout": "\nAn error occurred while importing metadata into the staging area.\nSee the server log(SystemOut.log or messages.log) for details.", "stdout_lines": ["", "An error occurred while importing metadata into the staging area.", "See the server log(SystemOut.log or messages.log) for details."]}

NO MORE HOSTS LEFT *************************************************************
```

If the import areas are delete manually, the pod can be deleted - and will get recreated, and correctly load up the sample data/metadata

(CG: updated to format error for readability)

**Comment by cmgrote** [comment]
In some ways (ie. using an IGC container) this can now be skipped by just deleting the pod with the container and letting it startup from empty again -- will leave it open to investigate for non-k8s-clustered environments

**Comment by cmgrote** [comment]
Re-tested running multiple times with all of the latest updates, and can no longer reproduce the error -- now able to (idempotently) run the same deploy process multiple times agains the same environment without errors.

(Note: for environments that already existed that were loaded with some older version of the scripts, this likely won't be the case -- but is for any fresh environments, going forward.)

**Comment by planetf1** [comment]
ok
