### ISSUE TITLE
Cohort name is being passed as userId for ReferenceCopy methods

### ISSUE THREAD

**Issue by sethvi** [odpi/egeria#785]
Let's take saveEntityReferenceCopy(String userId, EntityDetail entity) as an example.

1 In LocalOMRSInstanceEventProcessor, processInstanceBatchEvent calls saveInstanceReferenceCopies which in turn calls saveEntityReferenceCopy() where sourceName is passed as userId
   public void processInstanceBatchEvent(String         sourceName,
                                         String         originatorMetadataCollectionId,
                                         String         originatorServerName,
                                         String         originatorServerType,
                                         String         originatorOrganizationName,
                                         InstanceGraph  instances)
   {
       final String methodName = "processInstanceBatchEvent";

       try
       {
           verifyEventProcessor(methodName);

           realMetadataCollection.saveInstanceReferenceCopies(sourceName, instances);
    
    
2 In LocalOMRSInstanceEventProcessor, saveEntityReferenceCopy is called with sourceName
   private void updateReferenceEntity(String       sourceName,
                                      String       methodName,
                                      String       entityParameterName,
                                      String       originatorMetadataCollectionId,
                                      String       originatorServerName,
                                      EntityDetail entity)
   {
       try
       {
           verifyEventProcessor(methodName);
           repositoryValidator.validateReferenceInstanceHeader(realRepositoryName,
                                                               localMetadataCollectionId,
                                                               entityParameterName,
                                                               entity,
                                                               methodName);

           if (verifyEventToSave(sourceName, entity))
           {
               realMetadataCollection.saveEntityReferenceCopy(sourceName, entity);

**Comment by mandy-chessell** [comment]
We can easily change that to the local server's userId

**Comment by mandy-chessell** [comment]
The events now use the local server's userId on the processing of events.
