### ISSUE TITLE
Update samples removal to also remove stubs

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#789]
Cleanup the OMRS Stubs automatically as part of the removal playbook

**Comment by cmgrote** [comment]
This should actually be done already anyway, as the samples removal process removes the "real" objects themselves, which in turn (as part of propagating via eventmapper) will delete the OMRS Stubs -- must be missing an object or two during that removal process.

**Comment by cmgrote** [comment]
Currently deletion only operates at the file / table level (this is as granular as IGC allows), so there is no explicit delete for the columns or fields -- could be where many left-over stubs are coming from + be something we should handle via #772 ?

**Comment by planetf1** [comment]
ok let's assume fix on #772
