### ISSUE TITLE
Replace ldap-init container with Job

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#804]
Can free up almost 400MB of image space by replacing the current `ldap-init-egeriavdc` image with the pattern of a (temporal) `Job` and `initContainers` used for other config and data loading.

**Comment by cmgrote** [comment]
Actually, since we're using the `openldap` Helm chart, it looks like the configurability we need (loading LDIF files at startup) is already built-in to that chart (so can probably just re-use this rather than have any additional containers / images at all?)

https://github.com/helm/charts/tree/master/stable/openldap

- `customLdifFiles` - Custom ldif files to seed the LDAP server. List of filename -> data pairs

**Comment by planetf1** [comment]
if it works, yes :-)

**Comment by cmgrote** [comment]
> if it works, yes :-)

So.... no, it doesn't...  Resorting to the pattern we have elsewhere (Jobs)

**Comment by planetf1** [comment]
The postgresql image has a similar capability, but I tend to agree - let's stick with our jobs which we can better control
