### ISSUE TITLE
Optimise gaian image

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#805]
Can probably free up 600MB of image space by optimising `gaian-egeriavdc` to a minimal `alpine` image

**Comment by planetf1** [comment]
Note there will be more work to do on gaian (such as add the ranger plugin) but that's independent of this change

**Comment by cmgrote** [comment]
Happy to take a first stab at optimising, but not sure what to test / check to confirm that it still "works" after the optimisation...  Maybe I should leave this one for now (?)

**Comment by planetf1** [comment]
That's reasonable - the gaian integration still needs to be done -- which will require some additional local artifacts and configuration.
