### ISSUE TITLE
Optimise (or remove?) kafka-monitor image

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#806]
Can probably free up 500-600MB of image space by optimising the `kafka-monitor-egeriavdc` image (or perhaps even remove it entirely?)

It seems that the image is doing the same as the following command (when using the Kafka deployed by default as part of the Helm chart):

```bash
$ kubectl exec -c cp-kafka-broker -it cp-kafka-0 -- /bin/bash /usr/bin/kafka-console-consumer --bootstrap-server localhost:9092 --topic open-metadata.repository-services.cohort.coco.OMRSTopic --from-beginning
```

(If this is more complicated than first looking up the unique pod name of the kafka monitor, and then using `kubectl logs -f ...` maybe we should just put it into a shell script that people can run?)

Out-of-cluster could people rely on whatever other monitoring they'd already have for their Kafka environment (eg. at a minimum basically the same `kafka-console-consumer` command as above running on their Kafka environment?)

**Comment by planetf1** [comment]
Yes, it is... I initially added as a container as it was self-contained so just a case of tailing the logs without needing any additional knowledge. It was useful for the early stages of WIP.

It's crude though, so doesn't add a huge amount of value - and as you say can be easily replicated by a relatively simple command.

Perhaps a bigger question is whether there are any other/nicer kafka monitoring tools around that it would be useful to integrate.

**Comment by planetf1** [comment]
removed as part of the kafka work now committed labelled #831
