### ISSUE TITLE
Configurable git pulls for IGC container

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#810]
When using a container for IGC, allow the initialisation (git pull) to be configurable based on different branches, PRs, etc.

**Comment by cmgrote** [comment]
Just testing now: strategy is to allow using either a local machine's repository (via `hostPath`) for very fast and iterative testing on your local development machine without needing to check *anything* into git; otherwise (default) to use the public Egeria master branch.

**Comment by planetf1** [comment]
It would be useful if we could enable this via a maven property either
 * Build all container images - optimising in this way where possible
 * Build only egeria - with this optimization << this is the most likely case

I could do this in a separate issue if needed.

Integrating into maven is primarily for consistency

**Comment by cmgrote** [comment]
The setup I'm referring to for these containers is all done at run-time (ie. mounting the Egeria codebase into a pre-existing container) -- so it doesn't make any change to the image itself, which I would suggest is better as it means we don't need to constantly re-build the image(s).  (ie. these are all about how we use the `.../sample-data/...` assets within images: not running Egeria itself.)

I think the case of the runtime of Egeria *itself* is a separate case -- would suggest we handle that through a separate issue.

**Comment by planetf1** [comment]
Ok will raise a new issue -- it's something I would certainly find useful, but would require ensuring the local assets are made available to the container runtime -- and qutie likely the easiest way to do this for something like a cloud service is in fact to build the image.
