### ISSUE TITLE
Add options for external Kafka authentication

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#811]
Add options to provide authentication information for Kafka to externalisation logic / setup.

**Comment by planetf1** [comment]
I've started on this (continue monday) against my cloud deployment.

* will use a secret for auth
* Ideally need to support a list of brokers not one (this may touch many places)

**Comment by planetf1** [comment]
I am continuing to work on this - through a number of differences with an enterprise kafka environment  and through some bugs in the egeria code. Once things are clea, happy locally I will finish modifying the config scripts to work, but it is going to take a few more changes.

**Comment by planetf1** [comment]
Committed as part of #831 in error
