### ISSUE TITLE
Support VDC chart without IGC

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#817]
Ensure the VDC helm chart can be used without IGC and starts/runs cleanly.
(Though we really need a persistent store in egeria to make this especially useful..)

**Comment by cmgrote** [comment]
This is the default configuration now with the refactored chart: IGC will not be used (at all) -- either k8s cluster-internally or externally. Configuration allows you to:

1. Switch on IGC inclusion (defaulting to a cluster-internal, container-based IGC -- BYOI)
1. Switch on IGC inclusion + use a cluster-external, pre-existing IGC environment (by providing additional details of that environment: host, IP, port)

**Comment by planetf1** [comment]
Super... (not yet able to test). Will verify and close.
