### ISSUE TITLE
vdc helm chart - warning on chart deployment

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#825]
when deploying a chart an error such as

➜  charts git:(helm22) ✗ helm install vdc -f ~/cloud.yaml                                                  git:(helm22|✚3
2019/03/07 15:02:12 Warning: Building values map for chart 'cp-kafka'. Skipped value (map[]) for 'image', as it is not a table.

Appears  - due to likely incorrect formatting in values.yaml

low priority but should fix

**Comment by cmgrote** [comment]
Seems to be an embedded error from the `cp-kafka` Helm chart we're re-using, I think?

**Comment by planetf1** [comment]
yes that's my perception too - if nothing else I should report to that team so will retain the issue for that. Perhaps even a PR..

**Comment by cmgrote** [comment]
I think this is no longer an issue after moving to the Bitnami charts?

**Comment by planetf1** [comment]
agreed
