### ISSUE TITLE
Revert default registry for Helm charts to dockerhub

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#829]
- [x] Revert the default registry to dockerhub
- [x] Make the repository configurable (and default to a usable value)

(In parallel, @planetf1 still chasing LF build team for an odpi-official repo to which to push images as part of deploy process.)

**Comment by cmgrote** [comment]
@planetf1  to default to your dockerhub repo (for now), we need both the `1.1-SNAPSHOT` and `latest` tags -- looks like for the moment there are only `1.1-SNAPSHOT` tags (?)

**Comment by planetf1** [comment]
I will build later - backlogged on other tests. If you do the pr i can push sometime later/weekend.
