### ISSUE TITLE
[BUG] Test Failure on x86-64 Related to FVT in Egeria on UBI 9.3

### ISSUE THREAD

**Issue by pooja0805** [odpi/egeria#8301]
### Current Behavior

The majority of the tests in the package **org.odpi.openmetadata.viewservices.glossaryauthor.fvt.junit** are failing.

### Expected Behavior

Task **':open-metadata-test:open-metadata-fvt:view-services-fvt:glossary-author-fvt:test'** should pass without failures.

### Steps To Reproduce

```bash
yum install -y git wget tar java-17-openjdk-devel

#Setting JAVA Path
export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
export PATH=$JAVA_HOME/bin:$PATH
java -version

#Cloning egeria repo
git clone https://github.com/odpi/egeria.git
cd egeria
git checkout V4.3

export LC_ALL=C.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

./gradlew clean build -x test
./gradlew test
```

### Environment

```markdown
- Egeria: V4.0
- OS: UBI 9.3
- Java: 17.0.12
- Browser (for UI issues): - 
- Additional connectors and integration: -
```

### Any Further Information?

We have encountered a test failure when running Egeria on UBI 9.3 for the x86-64 architecture. The error log is as follows:
[Screenshot 2024-07-29 103746](https://github.com/user-attachments/assets/80b00c67-ef21-438e-8eae-9d3090e88849)

Also, attaching the HTML report of the failed tests below for more information:
[Egeria-test-failures.zip](https://github.com/user-attachments/files/16407809/Egeria-test-failures.zip)

Any help or pointers to resolve this issue would be greatly appreciated.

Thanks.

**Comment by mandy-chessell** [comment]
4.0 is a very old version of Egeria - we only have resources to provide fixes to the latest level of Egeria and normally I would look at fixing the main branch.  This is not possible in this case because the Glossary Author OMVS and and associated FVT were removed in 5.0.

**Comment by dwolfson** [comment]
@pooja0805 Perhaps it would help if you could give us a bit more background on what you are trying to do? The capabilities around the glossary are in the latest Egeria but perhaps under a different name..
