### ISSUE TITLE
maintainedBy is never set

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#837]
As far as I can see nothing ever sets the InstanceAuditHeader's maintainedBy field.

Is this field supposed to be set on instance creation? Or is it a derived field that should contain the userids of all users that have either created or updated the instance?

**Comment by mandy-chessell** [comment]
This field is to allow us to have instance based access control.  For example, edit rights on a personal profile.   Generally editing of the profile is only allowed by the person who it refers to.   If the profile is created by the individual concerned then we can use the createdBy field.  If the profile is created by an admin process that is pulling profiles from a HR system then we need an additional mechanism to determine who is allowed to edit it.  This is what the maintainedBy field is for.
