### ISSUE TITLE
Kafka: add notes on setup with secured kafka, required topics, debugging

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#838]
When trying to get Egeria working with IBM Event streams (a secure implementation of Kafka on public cloud) I noticed that after starting up egeria and configuring into a cohort, a stream of messages such as:

```
2019-03-13 09:22:57.309  WARN 18542 --- [ionView.inTopic] org.apache.kafka.clients.NetworkClient   : [Consumer clientId=consumer-3, groupId=0d1dc807-681b-4b6f-a430-d3cec52001ad] Error while fetching metadata with correlation id 374 : {null.server.myserver.open-metadata.access-services.InformationView.inTopic=UNKNOWN_TOPIC_OR_PARTITION}
```

were logged at INFO level 

However nothing was visible if logging was disablled. There are no audit messages logged.

The CAUSE of this issue (which has functional impact) was that the secure implementation is not configured to auto create topics. So the topics needed by many egeria components do not exist.

A few issues become clear
 * Where does a user go to ensure they can tell the kafka team (or configure manually themselves) the FULL list of kafka topics that Egeria needs
 * The log (INFO) message should contain the topic name & any other salient information
* There needs to be at least one audit message (or a low frequency periodic) reporting the fact that the topic does not exist.
 * the attempt to launch the server instance reported 200, with a result including:
```
{
    "class": "VoidResponse",
    "relatedHTTPCode": 200,
    "successMessage": "Wed Mar 13 09:22:04 GMT 2019 myserver is running the following services: [Repository Services, Data Engine OMAS, Subject Area OMAS, Governance Engine OMAS, Governance Program OMAS, Information View OMAS, Asset Consumer OMAS, Connected Asset OMAS, Asset Catalog OMAS]"
}
```
Which may be deemed slightly misleading since those services have been launched, but are not in any way running correctly.

Since we may have a situation where kafka comes up later we might want to consider how else to handle this - perhaps there should be an additional status check for each individual OMAS to report it's fine grained status for example.. Needs consideration.

**Comment by planetf1** [comment]
For reference the current topics I see are:
```
open-metadata.repository-services.cohort.cocoCohort.OMRSTopic
null.server.myserver.open-metadata.access-services.GovernanceEngine.outTopic
null.server.myserver.open-metadata.access-services.InformationView.inTopic
null.server.myserver.open-metadata.access-services.InformationView.outTopic
null.server.myserver.open-metadata.access-services.AssetConsumer.outTopic
```
I will raise a separate issue on the null.server naming of those 4 OMASs

**Comment by planetf1** [comment]
I did create the topics manually - however the OMAG server was unable to connect to the topics UNTIL the server was restarted/reconfigured. This sequence may need some retesting is there is an intent to allow the server to complete initialization once kafka is present, or the topic becomes available.

**Comment by mandy-chessell** [comment]
The asynchronous configuration of kafka was a change I made to the server start up at your request I seem to remember :).

Are you seeing the following events ... at start up ... specifically `OCF-KAFKA-TOPIC-CONNECTOR-0001` defines the topic names.

```
Wed Mar 13 15:49:54 CET 2019 cSuiteServer OMRS-AUDIT-0026 Initializing listener for cohort cocoCohort
Wed Mar 13 15:49:54 CET 2019 cSuiteServer OMRS-AUDIT-0019 The OMRS Topic Connector TopicConnector.Cohort.cocoCohort has registered with an event bus connector connected to topic open-metadata.repository-services.cohort.cocoCohort.OMRSTopic
Wed Mar 13 15:49:54 CET 2019 cSuiteServer OCF-KAFKA-TOPIC-CONNECTOR-0001 Connecting to Apache Kafka Topic open-metadata.repository-services.cohort.cocoCohort.OMRSTopic with a server identifier of e418a1d9-b374-48e4-893d-0864074f5733
Wed Mar 13 15:49:54 CET 2019 cSuiteServer OCF-KAFKA-TOPIC-CONNECTOR-0003 The properties passed to the Apache Kafka Consumer for topic open-metadata.repository-services.cohort.cocoCohort.OMRSTopic are: [key.deserializer->org.apache.kafka.common.serialization.StringDeserializer, max.partition.fetch.bytes->null, auto.commit.interval.ms->1000, bootstrap.servers->localhost:59092, group.id->e418a1d9-b374-48e4-893d-0864074f5733, enable.auto.commit->true, value.deserializer->org.apache.kafka.common.serialization.StringDeserializer, session.timeout.ms->30000]
Wed Mar 13 15:49:54 CET 2019 cSuiteServer OCF-KAFKA-TOPIC-CONNECTOR-0002 The properties passed to the Apache Kafka Producer for topic open-metadata.repository-services.cohort.cocoCohort.OMRSTopic are: [retries->null, bootstrap.servers->localhost:59092, linger.ms->null, acks->all, value.serializer->org.apache.kafka.common.serialization.StringSerializer, buffer.memory->null, batch.size->null, key.serializer->org.apache.kafka.common.serialization.StringSerializer]
Wed Mar 13 15:49:54 CET 2019 cSuiteServer OCF-KAFKA-TOPIC-CONNECTOR-0010 The Apache Kafka producer for topic open-metadata.repository-services.cohort.cocoCohort.OMRSTopic is starting up with 0 buffered messages
Wed Mar 13 15:49:54 CET 2019 cSuiteServer OMRS-AUDIT-0020 The OMRS Topic Connector TopicConnector.Cohort.cocoCohort is ready to send and receive events
Wed Mar 13 15:49:54 CET 2019 cSuiteServer OMRS-AUDIT-0015 The listener thread for an OMRS Topic Connector for topic open-metadata.repository-services.cohort.cocoCohort.OMRSTopic has started
```

And then these messages ... in this example, Kafka is not running at all.

```
Wed Mar 13 15:50:54 CET 2019 cSuiteServer OCF-KAFKA-TOPIC-CONNECTOR-0011 Unable to send event on topic open-metadata.repository-services.cohort.cocoCohort.OMRSTopic.  0 events successfully sent; 414 events buffered. Latest error message is org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
Wed Mar 13 16:01:54 CET 2019 cSuiteServer OCF-KAFKA-TOPIC-CONNECTOR-0011 Unable to send event on topic open-metadata.repository-services.cohort.cocoCohort.OMRSTopic.  0 events successfully sent; 414 events buffered. Latest error message is org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
Wed Mar 13 16:12:54 CET 2019 cSuiteServer OCF-KAFKA-TOPIC-CONNECTOR-0011 Unable to send event on topic open-metadata.repository-services.cohort.cocoCohort.OMRSTopic.  0 events successfully sent; 414 events buffered. Latest error message is org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
Wed Mar 13 16:23:54 CET 2019 cSuiteServer OCF-KAFKA-TOPIC-CONNECTOR-0011 Unable to send event on topic open-metadata.repository-services.cohort.cocoCohort.OMRSTopic.  0 events successfully sent; 414 events buffered. Latest error message is org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
Wed Mar 13 16:34:54 CET 2019 cSuiteServer OCF-KAFKA-TOPIC-CONNECTOR-0011 Unable to send event on topic open-metadata.repository-services.cohort.cocoCohort.OMRSTopic.  0 events successfully sent; 414 events buffered. Latest error message is org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
```

Although Kafka outputs detailed exceptions in its debug log, it wraps them in a generic exception so our ability to have better messages is limited.  However it may be that an indefined topic is raising an exception in a different code path.

**Comment by mandy-chessell** [comment]
It should however be possible to (re)connect to kafka once admin errors are correct (just as it reconnects when kafka is restarted.

**Comment by planetf1** [comment]
Rechecked and I do indeed see
```
Thu Mar 14 09:47:39 GMT 2019 myserver OCF-KAFKA-TOPIC-CONNECTOR-0011 Unable to send event on topic egeria.open-metadata.repository-services.cohort.cocoCohort.OMRSTopic.  0 events successfully sent; 418 events buffered. Latest error message is org.apache.kafka.common.errors.TimeoutException: Topic egeria.open-metadata.repository-services.cohort.cocoCohort.OMRSTopic not present in metadata after 60000 ms.
```

which addressed the code issue

Furthermore I again tried creating the topic after this, and it the code does reconnect

So it is working correctly.

So I think the change here is just to document the required topics for manual kafka setup. I will leave this open to cater for it here, or as part of kafka docs generally.

**Comment by mandy-chessell** [comment]
Where is the documentation of the topic names?

**Comment by planetf1** [comment]
I haven't documented them yet.

The current list I have deployed is as follows -- it's possible additional requirements have been added since I last checked
```
egeria.server.myserver.open-metadata.access-services.DataPlatform.inTopic
egeria.server.myserver.open-metadata.access-services.AssetLineage.outTopic
egeria.server.myserver.open-metadata.access-services.SubjectArea.inTopic
egeria.server.myserver.open-metadata.access-services.AssetConsumer.inTopic
egeria.server.myserver.open-metadata.access-services.InformationView.inTopic
egeria.server.myserver.open-metadata.access-services.AssetCatalog.outTopic
egeria.server.myserver.open-metadata.access-services.SecurityOfficer.inTopic
egeria.server.myserver.open-metadata.access-services.AssetLineage.inTopic
egeria.server.myserver.open-metadata.access-services.ConnectedAsset.outTopic
egeria.open-metadata.repository-services.cohort.cocoCohort.OMRSTopic
egeria.server.myserver.open-metadata.access-services.DataEngine.inTopic
egeria.server.myserver.open-metadata.access-services.GovernanceEngine.outTopic
myserver.open-metadata.repository-services.enterprise.myserver.OMRSTopic
egeria.open-metadata.repository-services.cohort.coco.OMRSTopic
egeria.server.myserver.open-metadata.access-services.DataEngine.outTopic
egeria.server.myserver.open-metadata.access-services.SubjectArea.outTopic
egeria.server.myserver.open-metadata.access-services.GovernanceEngine.inTopic
egeria.server.myserver.open-metadata.access-services.GovernanceProgram.inTopic
egeria.server.myserver.open-metadata.access-services.AssetCatalog.inTopic
egeria.server.myserver.open-metadata.access-services.SecurityOfficer.outTopic
egeria.server.myserver.open-metadata.access-services.InformationView.outTopic
egeria.server.myserver.open-metadata.access-services.ConnectedAsset.inTopic
egeria.server.myserver.open-metadata.access-services.AssetConsumer.outTopic
egeria.server.myserver.open-metadata.access-services.DataPlatform.outTopic
egeria.server.myserver.open-metadata.access-services.GovernanceProgram.outTopic
```
I have the topic root set to 'egeria' and my server instance is 'myserver'

It would be useful if we were able to provide this list automatically. One could parse the event log for failures. An initial rest call might be useful (though arguably you want the queues setup ahead of time). Annotation of the source code.. or a simple manually updated list.

**Comment by planetf1** [comment]
We do need to figure out how to document this for someone deploying egeria. As an example, EventStreams in IBM cloud does not permit auto topic creation. All topics must be created via UI or a rest API (but this is implementation specific). At a minimum providing the user (deployer) info on the list of topics they need is important.

**Comment by cong78** [comment]
> We do need to figure out how to document this for someone deploying egeria. As an example, EventStreams in IBM cloud does not permit auto topic creation.

Same for us. We also need to request different topics per env first from our Event Bus service team. It would be helpful to let the people know how is the naming convention of the topics and which parameters are changing dynamically?

**Comment by planetf1** [comment]
A PR has been created which addresses this issue
