### ISSUE TITLE
[BUG] <OMAG Server Not Available in Egeria UI on Private GKE with Default Chart Deployment (404 Error)>

### ISSUE THREAD

**Issue by eashanroy7** [odpi/egeria#8434]
### Current Behavior

Used the documentation guide, and executed the following commands inside the private GKE cluster:
```
helm repo add egeria https://odpi.github.io/egeria-charts
helm repo update
helm install egeria egeria/egeria-base
```
After deployment:
`kubectl get svc`

NAME                                      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                               AGE
egeria-platform                           ClusterIP   34.118.228.176   <none>        9443/TCP                              142m
egeria-presentation                       ClusterIP   34.118.239.161   <none>        8091/TCP                              142m
egeria-strimzi-kafka-0                    NodePort    34.118.230.154   <none>        9094:31268/TCP                        141m
egeria-strimzi-kafka-bootstrap            ClusterIP   34.118.230.254   <none>        9091/TCP,9092/TCP                     141m
egeria-strimzi-kafka-brokers              ClusterIP   None             <none>        9090/TCP,9091/TCP,8443/TCP,9092/TCP   141m
egeria-strimzi-kafka-external-bootstrap   NodePort    34.118.229.108   <none>        9094:32000/TCP                        141m
egeria-strimzi-zookeeper-client           ClusterIP   34.118.230.54    <none>        2181/TCP                              142m
egeria-strimzi-zookeeper-nodes            ClusterIP   None             <none>        2181/TCP,2888/TCP,3888/TCP            142m
kubernetes                                ClusterIP   34.118.224.1     <none>        443/TCP                               163m

`kubectl get pods`

NAME                                              READY   STATUS      RESTARTS   AGE
egeria-autostart-f9mhc                            0/1     Completed   0          86m
egeria-base-platform-0                            1/1     Running     0          86m
egeria-base-presentation-79f574749c-zjtpb         1/1     Running     0          86m
egeria-config-p27wd                               0/1     Completed   0          86m
egeria-strimzi-entity-operator-68c5bfd9df-t9pgm   3/3     Running     0          84m
egeria-strimzi-kafka-0                            1/1     Running     0          84m
egeria-strimzi-zookeeper-0                        1/1     Running     0          85m
strimzi-cluster-operator-b98874885-7qcxk          1/1     Running     0          86m

Port forwarding on port 8092:
`kubectl port-forward service/egeria-presentation 8092:8091`

Then accessed the UI from local Chrome browser:
`https://localhost:8092/org/`

The UI was accessible, but there's this popup saying **localhost 8092 says: Could not get servers (status : 404). OMAG-MULTI-TENANT-404-001 The OMAG Server view1 is not available to service a request from user garygeeke. System detail: The system is unable to process the request because the server is not running on the called platform.**
### Expected Behavior

Was hoping to have a smooth deployment with a functioning OMAG server. 

To debug, I checked the running servers on the Platform:
`kubectl port-forward svc/egeria-platform 9443:9443`

```
curl -k -X POST "https://localhost:9443/open-metadata/admin-services/users/garygeeke/servers/view1/start" \
-H "accept: */*" \
-H "Content-Type: application/json"
```

Response of above command:
`{
   "timestamp":"2024-10-08T05:52:36.680+00:00",
   "status":404,
   "error":"Not Found",
   "path":"/open-metadata/admin-services/users/garygeeke/servers/view1/start"
}
`
Looks like the view1 server is not setup at all.

### Environment

```markdown
- Egeria: 4.3
- OS: MacBook Pro, 13-inch, M1, 2020
- Browser (for UI issues): Chrome
- Additional connectors and integration:
```

### Any Further Information?

https://egeria-project.org/guides/operations/kubernetes/charts/base/

**Comment by eashanroy7** [comment]
I tried installing the base chart with latest Egeria version as well:
```
helm install egeria egeria/egeria-base \
  --set egeria.version=5.1
```
But this gives me Image Pull Back Off errors, so I guess there is some compatibility issues with egeria 5.1 and docker images with tag 'latest'?

**Comment by mandy-chessell** [comment]
Hello @eashanroy7, these charts are not operational at the moment.  

We have been focused on building a docker compose environment for evaluation and test.  This is in the https://github.com/odpi/egeria-workspaces repository.

**Comment by eashanroy7** [comment]
Oh thank you @mandy-chessell for letting me know that. 
Is there any recommended way for deploying Egeria in production?
