### ISSUE TITLE
vdc chart docker terminology - use 'namespace'

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#855]
```
  Normal   Scheduled  6m56s                  default-scheduler       Successfully assigned default/yummy-emu-vdc-atlas-7d8558dd69-8mzpc to 10.72.127.138
  Normal   Pulling    5m26s (x4 over 6m55s)  kubelet, 10.72.127.138  pulling image "docker.io/planetf1/apache-atlas/apache-atlas:1.1-SNAPSHOT"
  Warning  Failed     5m25s (x4 over 6m54s)  kubelet, 10.72.127.138  Failed to pull image "docker.io/planetf1/apache-atlas/apache-atlas:1.1-SNAPSHOT": rpc error: code = Unknown desc = failed to resolve image "docker.io/planetf1/apache-atlas/apache-atlas:1.1-SNAPSHOT": no available registry endpoint: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

```

**Comment by planetf1** [comment]
In my case local values.yaml had
```
 atlas:
    repository: planetf1/apache-atlas
    tag: 1.1-SNAPSHOT
    pullPolicy: Always
```

**Comment by cmgrote** [comment]
Are you sure you aren't running with an override?  These are the default settings:

```
imageDefaults:
  registry: docker.io
  repository: planetf1
  tag: latest
  pullPolicy: IfNotPresent

atlas:
    name: apache-atlas
```

Which will result in: `docker.io/planetf1/apache-atlas:latest`

**Comment by cmgrote** [comment]
Right -- your override should be:

```
atlas:
    repository: planetf1
    name: apache-atlas
    tag: 1.1-SNAPSHOT
    pullPolicy: Always
```

**Comment by planetf1** [comment]
Yes - the issue is the use of the name 'repository'. At dockerhub this refers to the full location of the image, not just the basename

So a comment in the values, and possible rename of the parm to 'repoBase' or similar is probably the best approach.

I had a previous values file which was resulting in this behaviour - not a problem behaviour is changed.

**Comment by cmgrote** [comment]
Probably easiest to add a comment, or you need to change lots of files that use the variables...  (Definitely wouldn't suggest combining into a single parameter or you're going to have some extremely convoluted checks to write in the templates 😉)

**Comment by planetf1** [comment]
Probably namespace is a better name, as this term is used in the docker docs..

**Comment by planetf1** [comment]
A useful summary of names
https://console.bluemix.net/docs/services/Registry/registry_overview.html#terms
