### ISSUE TITLE
OMRS instance start, activateWithStoredConfig should not return 200 when the kafka clients fail to start.

### ISSUE THREAD

**Issue by hjv333** [odpi/egeria#864]
When starting/activating an omrs instance, 200 is returned even when the kafka clients fail to start.

The OMAGServerOperationalServices.activateWithStoredConfig should not return 200 when the kafka clients fail to start (for example, due to a credential or a configuration being incorrect).

As a user, the 200 response makes you think that everything is OK until you realize that sync is not happening.   Then, in the logs, you see messages like these:

"class":"org.odpi.openmetadata.repositoryservices.auditlog.OMRSAuditCode",
"line":675,"method":"getFormattedLogMessage",
"message":"\u003d\u003d\u003e OMRS Audit Code.getMessage([vegah_cohort7, Failed to construct kafka consumer]): Configuration error detected while connecting to cohort vegah_cohort7, error message was: Failed to construct kafka consumer",
"logger":"org.odpi.openmetadata.repositoryservices.auditlog.OMRSAuditCode"

"class":"org.odpi.openmetadata.repositoryservices.auditlog.OMRSAuditLogDestination",
"line":94,"method":"logRecord",
"message":"abd434e0-00be-47b5-b095-0dd370d398c0_omag OMRS-AUDIT-0006 Configuration error detected while connecting to cohort vegah_cohort7, error message was: Failed to construct kafka consumer",
"logger":"org.odpi.openmetadata.repositoryservices.auditlog.OMRSAuditLog"

"class":"org.odpi.openmetadata.adapters.repositoryservices.auditlogstore.console.ConsoleAuditLogStoreConnector",
"line":71,"method":"storeLogRecord",
"message":"AuditLogRecord: OMRSAuditLogRecord{guid\u003d\u00277482f8b7-e665-453d-a6be-62e1bcb1eeb6\u0027, timeStamp\u003dSun Mar 17 17:07:36 PDT 2019, originator\u003dOMRSAuditLogRecordOriginator{metadataCollectionId\u003d\u0027abd434e0-00be-47b5-b095-0dd370d398c0\u0027, serverName\u003d\u0027abd434e0-00be-47b5-b095-0dd370d398c0_omag\u0027, serverType\u003d\u0027Open Metadata and Governance Server\u0027, organizationName\u003d\u0027IBM\u0027}, severity\u003d\u0027Exception\u0027, reportingComponent\u003dOMRSAuditLogReportingComponent{componentId\u003d14, componentName\u003d\u0027Cohort Manager\u0027, componentDescription\u003d\u0027Manages the initialization and shutdown of the server\u0027s connectivity to a cohort.\u0027, componentWikiURL\u003d\u0027https://odpi.github.io/egeria/open-metadata-implementation/repository-services/docs/component-descriptions/cohort-manager.html\u0027}, messageId\u003d\u0027OMRS-AUDIT-0006\u0027, messageText\u003d\u0027Configuration error detected while connecting to cohort vegah_cohort7, error message was: Failed to construct kafka consumer\u0027, additionalInformation\u003dnull, systemAction\u003d\u0027The local server has started to initialize the communication with the named open metadata repository cohort and a configuration error was detected.\u0027, userAction\u003d\u0027Review the exception and resolve the issue it documents. Then disconnect and reconnect this server to the cohort.\u0027, GUID\u003d\u00277482f8b7-e665-453d-a6be-62e1bcb1eeb6\u0027}",
"logger":"org.odpi.openmetadata.adapters.repositoryservices.auditlogstore.console.ConsoleAuditLogStoreConnector"

"class":"org.odpi.openmetadata.repositoryservices.metadatahighway.OMRSCohortManager",
"line":265,"method":"initialize",
"message":"Initialize Cohort Manager COMPLETE",
"logger":"org.odpi.openmetadata.repositoryservices.metadatahighway.OMRSCohortManager"

**Comment by mandy-chessell** [comment]
This is working as designed.  The start up used to be synchronous but it meant that the initialization hung if Kafka was down.  So we changed it so that the start up is asynchronous and the administrator can fix the errors and the server recovers.    The server does a lot more that talk to Kafka.
