### ISSUE TITLE
Add @generated to IGC generated code

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#865]
The sonar scan is currently showing very high stats on duplicated code
See https://sonar.odpi.org/component_measures?id=org.odpi.egeria%3Aegeria&metric=duplicated_lines_density

Originally the subject area was a big factor (removing this from scans reduced dup counts to 5% or so). However now the generated IGC code is a large factor.

We can then set sonar to skip duplicate scanning on all lines where @generated is used?

This is far from perfect, and if it is awkward I will stick to exclusion based on selected file paths - it just seems @generated is probably a more generic approach to cater for other scanning tools as it's effectively standard java

cc: @cmgrote 

See also https://github.com/odpi/ci-management/issues/34

**Comment by cmgrote** [comment]
Very happy to make this change — any example you can point me to so I can be sure I get the syntax right? =)

**Comment by planetf1** [comment]
https://docs.oracle.com/javase/8/docs/api/javax/annotation/Generated.html

it seems to still be in Java 11 (which we should compile with)

https://docs.oracle.com/en/java/javase/11/docs/api/java.compiler/javax/annotation/processing/Generated.html

though there appear to have been some changes done around standard annotations after java 8 -- so hopefully things won't break (not tested myself yet)

**Comment by cmgrote** [comment]
I'm testing this out on my own (in my own Sonar instance), but it doesn't seem that `@Generated` is automatically causing duplication checks to be ignored.  Is there something somewhere I need to configure to ensure that `@Generated` is used to ignore duplicated lines?

(Also as a heads-up, it also seems to have increased the processing time of the Sonar report by 10x -- hopefully avoidable by whatever extra configuration I need for the above point?  Otherwise I'd suggest we're probably back to just ignoring paths -- eg. anything whose code package has `generated` in it...)

**Comment by cmgrote** [comment]
... in fact, this documentation seems to imply that for duplicate code checks, the only way to ignore them is to exclude the files themselves (via a file pattern):

https://docs.sonarqube.org/latest/project-administration/narrowing-the-focus/#header-3

(?)

**Comment by planetf1** [comment]
Indeed - by default that is the case. In my personal nexus scan I do just that.
However since @generated is fairly standard java, the sonar docs give a tip on defining a pattern that (a little crudely) removes @generated tagged files from the scan
I explain the thought in odpi/ci-management#34

**Comment by cmgrote** [comment]
I've tried `@javax\.annotation\.Generated` (as documented), which had no effect; then `@Generated` assuming it is only doing a regex match, and still no effect...

The generated files are still all listed as having heavy duplication.

I think it's still worthwhile having the annotation to indicate that the classes are generated, so I'll put in a PR with the change, but it won't have any impact on the duplicate line check in Sonar it seems.

**Comment by planetf1** [comment]
your change would only take effect when the sonar config was changed on the build machine. It has been done now, and the reports are looking hugely better :-) (see comment on issue for more info)

**Comment by cmgrote** [comment]
So...  we can close this issue now? 😉

**Comment by planetf1** [comment]
yes...
