### ISSUE TITLE
Incompatibility between OCF Connection and Open Metadata Types

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#882]
In the Open Connector Framework (OCF), the additionalProperties property is of type Map<String, Object>.  In our open metadata types, OMRS Connector implementations, OMAS implementations and in Apache Atlas, this property is a Map<String, String>.

With the current implementation, we may have problems storing OCF objects such as Connection in an open metadata repository.  Ideally we need to change the OCF property to be Map<String, String>.

The OCF Connection object is used by the admin services.  Connectors such as the Kafka event bus connector use the additional properties to pass complex configuration properties.  So if we just change the additionalProperties type to Map<String, String> then the Kafka connector will not get its properties.

The Connection object still needs a property of type Map<String, Object>.

Java does not properly distinguish Map<String, Object> from Map<String, String> so having two methods like this is not allowed:

setAddtionalProperties(Map<String, Object> properties)
setAddtionalProperties(Map<String, String> properties)

At the same time Java will not allow an object of type Map<String, String> to be assigned to a Map<String, Object>.

**Comment by mandy-chessell** [comment]
This is the fix I have coded:

- Add new property to Connection called configurationProperties of type Map<String, Object>.
- Change the additionalProperties object in all OCF objects to be Map<String, String>.
- Change the Egeria admin services to use the new configurationProperties property.
- Change IGC Connector and Kafka Connector to use configurationProperties.
- Add recognizedConfigurationProperties property to connectorType and updated the open metadata topic and Kafka connector providers to set this up.

This fix seems to be working ok.  The downside

**Comment by mandy-chessell** [comment]
The fix seems to be working well except that it is not able to read old versions of a configuration document.  It means you eithern eed to recreate the document or do a global change of additionalProperties to configurationProperties and all is well.

**Comment by mandy-chessell** [comment]
This is the response from the activate request if the configuration document is out of date.

POST http://{{platformURLroot}}/open-metadata/admin-services/users/{{adminUserId}}/servers/{{mdrServerName}}/instance

{
    "class": "VoidResponse",
    "relatedHTTPCode": 400,
    "exceptionClassName": "org.odpi.openmetadata.adminservices.ffdc.exception.OMAGConfigurationErrorException",
    "exceptionErrorMessage": "OMAG-ADMIN-400-018 OMAG server cocoMDS1 has been called with a configuration document that has no services configured",
    "exceptionSystemAction": "The requested server provides no function.",
    "exceptionUserAction": "Use the administration services to add configuration for OMAG services to the server's configuration document."
}

**Comment by mandy-chessell** [comment]
If you want to see the fix it is in my fork - https://github.com/mandy-chessell/egeria/tree/foundation

**Comment by mlottesen** [comment]
This begs the question, can we add versioning to the configuration document so that when breaking changes are made across versions (we had a similar breaking change due to class hierarchy refactoring a few months back) some kind of upgrade utility can be run to bring them up to date offline?

**Comment by mandy-chessell** [comment]
That is a good idea.  I will add it - and an exception that refuses to load an out-
of-date config file.

**Comment by mandy-chessell** [comment]
This is the new error ...
```json
{
    "class": "VoidResponse",
    "relatedHTTPCode": 400,
    "exceptionClassName": "org.odpi.openmetadata.adminservices.ffdc.exception.OMAGInvalidParameterException",
    "exceptionErrorMessage": "OMAG-ADMIN-400-022 The configuration document for OMAG server cocoMDS1 is at version V1.0 which is not compatible with this OMAG Server Platform which supports versions [V2.0]",
    "exceptionSystemAction": "The system is unable to configure the local server because it can not read the configuration document.",
    "exceptionUserAction": "Migrate the configuration document to a compatible version (or delete and recreate it).  See https://egeria.odpi.org/open-metadata-implementation/governance-servers/admin-services/docs/user/migrating-configuration-documents.html"
}
```

**Comment by guptaneeru** [comment]
@mandy-chessell Above error will be thrown on activating the OMAG server. Will the same error be thrown on trying to read the configurations? If so, we can use that to auto migrate existing configurations to newer version. Will egeria provide support to migrate the existing configurations. IN WKC cloud version, there can be multiple config documents saved in Cloudant. We will need to migrate those documents at the time of deploying the latest changes.

**Comment by mandy-chessell** [comment]
The same error will be thrown any time the out-of-date configuration document is read.  The current plan is to just document how to fix it on the Egeria site (when the PR is merged into master).

If anyone wants to contribute an auto migration script to ODPi Egeria then please supply a pull request.

**Comment by cmgrote** [comment]
Looks good from my perspective
