### ISSUE TITLE
auth-vdc-kafka now seems mandatory, even for configs that don't need it

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#899]
It seems that `auth-vdc-kafka` secret is now required by the deployment process, even for configs (like local in-cluster-deployed) that do not require it (?)

Deployment fails at `init-egeria` job:

```
local-vdc-job-02-init-egeria-wnbdp            0/1       CreateContainerConfigError   0          18m
```

With a more detailed error from the `pod describe`:

```
Events:
  Type     Reason                 Age               From                         Message
  ----     ------                 ----              ----                         -------
  Normal   Scheduled              10m               default-scheduler            Successfully assigned local-vdc-job-02-init-egeria-wnbdp to docker-for-desktop
  Normal   SuccessfulMountVolume  10m               kubelet, docker-for-desktop  MountVolume.SetUp succeeded for volume "default-token-qncm5"
  Normal   Pulled                 10m               kubelet, docker-for-desktop  Container image "docker.io/planetf1/egeria-configure:latest" already present on machine
  Normal   Created                10m               kubelet, docker-for-desktop  Created container
  Normal   Started                10m               kubelet, docker-for-desktop  Started container
  Normal   Pulled                 9m                kubelet, docker-for-desktop  Container image "docker.io/planetf1/egeria-configure:latest" already present on machine
  Normal   Created                9m                kubelet, docker-for-desktop  Created container
  Normal   Started                9m                kubelet, docker-for-desktop  Started container
  Warning  Failed                 7m (x9 over 9m)   kubelet, docker-for-desktop  Error: secrets "auth-vdc-kafka" not found
  Normal   Pulled                 9s (x44 over 9m)  kubelet, docker-for-desktop  Container image "docker.io/planetf1/egeria-configure:latest" already present on machine
```

Is this expected (ie. that we must always manually create an `auth-vdc-kafka`?  Have we documented it somewhere, if so?  (Why not provide an empty default so that people can deploy the default configuration without manual intervention?)

**Comment by planetf1** [comment]
i agree, that if using the 'built-in' kafka, there should be no need to create a secret. it should only be required for an external kafka deployment

will look at this (pm) and verify it works with cloud, in case I need to demo cloud deployment on tue/wed.

**Comment by cmgrote** [comment]
Looks like there might be a couple other related issues with spacing from the templating added for this to the job charts, as well -- I'm testing out a couple quick changes now and will submit a PR against this issue before this pm for you to review.

(My best guess is that the very basic templating that Helm does means *any* information provided in values is traversed; so to avoid it trying to lookup the `auth-vdc-kafka` -- even if it is ultimately unused -- it must not be specified in the file.  So we should probably default this to an empty string, same as the brokers list?  Seems to be working if I do this -- but again, will include in PR shortly...)

**Comment by cmgrote** [comment]
For posterity, the other issue was these lines:

```
                {{- if .Values.kafka.internal.enabled -}}
                --data '{"producer": {"bootstrap.servers":"'"${KAFKA_ENDPOINT}"'"}, "consumer": {"bootstrap.servers":"'"${KAFKA_ENDPOINT}"'"} }'
                {{- else -}}
```

That last `-}}` needs is overly aggressive in removing whitespace, causing the `--data ...` on the following line to be directly concatenated to previous lines (without any spacing), meaning it is then interpreted as part of the URL being sent to curl rather than a `--data` parameter.  Simple fix: change the `-}}` into `}}`:

```
                {{- if .Values.kafka.internal.enabled }}
                --data '{"producer": {"bootstrap.servers":"'"${KAFKA_ENDPOINT}"'"}, "consumer": {"bootstrap.servers":"'"${KAFKA_ENDPOINT}"'"} }'
                {{- else -}}
```

**Comment by planetf1** [comment]
Ok will aim to look at your proposal later today & verify against cloud.
