### ISSUE TITLE
IBM IGC container fails to run on IBM cloud

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#906]
Note: This issue refers to a particular vendor package. 

The current VDC charts built for demos include support for IBM IGC
This uses the docker image created using: https://github.com/IBM/ansible-role-infosvr/tree/master/docker

Currently the charts work
 - When using an external IGC server - whether the k8s environment used is docker locally (MacOS), or IBM Public Cloud.
 - when using the IGC container - using docker locally only.

Currently the IGC container does not appear to start correctly when deployed to IBM Cloud.
Issues seem include
 - dbus communication issues
 - sudo permission problems
 - db2 failing to start 

It's expected that the container needs to run privileged, may need ipc-owner capabilities, and perhaps more. The image makes use of systemd which can be problematic.

It's also worth noting that this area can vary by cloud platform, and note that locally on mac we use docker, whilst on ibm cloud we are using containerd.

For now I will consolidate my latest changes, and add a note to the readme/config.
Leaving this to an avid IGC user to debug/address.

**Comment by planetf1** [comment]
For reference the current failure is

> kubectl logs irreverent-quail-vdc-ibm-igc-69759485cc-wzw7d
.......
TASK [IBM.infosvr : start IBM DB2] *********************************************
fatal: [infosvr]: FAILED! => {"changed": false, "cmd": "source ~/.bashrc && db2start", "delta": "0:00:00.723224", "end": "2019-04-11 11:00:47.974036", "msg": "non-zero return code", "rc": 4, "start": "2019-04-11 11:00:47.250812", "stderr": "", "stderr_lines": [], "stdout": "04/11/2019 11:00:47     0   0   SQL1072C  The request failed because the database manager resources are in an inconsistent state.  The database manager might have been incorrectly terminated, or another application might be using system resources in a way that conflicts with the use of system resources by the database manager.\nSQL1032N  No start database manager command was issued.  SQLSTATE=57019", "stdout_lines": ["04/11/2019 11:00:47     0   0   SQL1072C  The request failed because the database manager resources are in an inconsistent state.  The database manager might have been incorrectly terminated, or another application might be using system resources in a way that conflicts with the use of system resources by the database manager.", "SQL1032N  No start database manager command was issued.  SQLSTATE=57019"]}

**Comment by cmgrote** [comment]
For the broader community: be aware that this container we're referring to is not officially an IBM-supported configuration anyway -- in any "real" scenario the external IGC configuration should be used, pointing to a k8s-external installation and configuration of IGC that is officially supported.

**Comment by planetf1** [comment]
Since we can't take any action here, and it is specific to an individual vendor option, I suggest we close this
