### ISSUE TITLE
Cannot update relationship effectivity dates if there are no properties to update.

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#925]
OMRS  call updateRelationshipProperties, OMRSRepositoryContentValidator validateNewPropertiesForType method, causes a validation error if there are no supplied properties. This is the call that updated the effectivity dates, which means  you cannot update relationship effectivity dates if there are no properties to update.

The validations should cause an error if there are no changes to properties or effectivity dates - to indicate that an update has been issued but there is nothing to update.

**Comment by planetf1** [comment]
is this fixed for 1.2?

**Comment by mandy-chessell** [comment]
This is an old problem.  David was going to check whether it was still a problem - if he does not have time to do this then move to 1.3 so we can validate

**Comment by planetf1** [comment]
@davidradl reassigning to 1.3 - can you check if it's still an issue when you have a chance.

**Comment by mandy-chessell** [comment]
I think the problem I found with the governance program sample is the same as this.
The relationship.getProperties() returns null if there are no properties and ignored the fact that there could be effectivity dates - will post the fix under this issue. (and will also fix getProperties on entities too.

**Comment by mandy-chessell** [comment]
Looks fixed
