### ISSUE TITLE
The event for referenceCopy published by graph-repository is incomplete

### ISSUE THREAD

**Issue by ruxandraRosu** [odpi/egeria#927]
ERROR LocalAtlasOMRSMetadataCollection:11331 - saveRelationshipReferenceCopy: Supplied relationship is missing the following fields - updatedBy updateTime
8:14:05,865 ERROR LocalAtlasOMRSMetadataCollection:10738 - saveEntityReferenceCopy: Supplied entity is missing the following fields - updatedBy updateTime

**Comment by grahamwallis** [comment]
Actually I think the problem is not that the event is incomplete - it is that the Atlas connector is over-policing the attributes. Chris R ran into this as well - I need to remove the checks on the updateXX attributes.

**Comment by grahamwallis** [comment]
Update pushed to managed-fork.

**Comment by ruxandraRosu** [comment]
The entity created in the home repository(graph repository) is saved also to the cohort member repository(atlas)
