### ISSUE TITLE
Rat Check fails for Deployment Sample Data

### ISSUE THREAD

**Issue by innerTide** [odpi/egeria#929]
[‎17-‎4-‎2019 10:12] Wu, Y. (Yuefeng): 

*****************************************************
Summary
-------
Generated at: 2019-04-17T09:40:26+02:00

Notes: 0
Binaries: 4
Archives: 0
Standards: 116

Apache Licensed: 0
Generated Documents: 0

JavaDocs are generated, thus a license header is optional.
Generated files do not require license headers.

1 Unknown Licenses

*****************************************************

Files with unapproved licenses:

  C:/Workspace/egeria/open-metadata-resources/open-metadata-deployment/sample-data/coco-pharmaceuticals/metadata/ibm-igc/ds_jobs_ibm-db2.isx

*****************************************************

**Comment by innerTide** [comment]
Hi Chris, thanks. I will revert my modification on POM file in my pull request and add exclusion locally.

**Comment by cmgrote** [comment]
If it's breaking on all Windows builds (which sounds like it is the case?) then I think we _do_ want the fix to go into master (not just locally)...

Looking at your change, though, I think it overlaps a bit with the root project `pom.xml` -- which already excludes all `.json` and `.csv`.  Probably we should add the RAT exclusion to the list there, to ignore either `**/*.isx` or at least `/open-metadata-deployment/**.isx`?

**Comment by innerTide** [comment]
Sure, I will add it. to the exclusion. :)

**Comment by cmgrote** [comment]
Maybe as a separate, super-simple PR as well?  Would like to ask @GuyAckermans to review it, as he seemed to face the same issue.
