### ISSUE TITLE
Access Services User Interface deployment

### ISSUE THREAD

**Issue by wiktorof** [odpi/egeria#939]
is there any documentation how to deploy and configure Access Services User Interface ?

**Comment by enrush01** [comment]
I was able to start the Access Services User Interface, and I saw the design diagram in the readme. But I could not find documentation on how to manage users. Has any progress been made?

**Comment by planetf1** [comment]
If you are using our helm charts, the UI should be deployed by default. 
The helm charts set
 OMAS_SERVER_URL (ie 'http://localhost:8080')
 OMAS_SERVER_NAME ( ie 'myserver')

This will provide for a simple asset search

However there is currently an issue that needs investigating: https://github.com/odpi/egeria/issues/1129

That being said, the UI components are currently being developed actively to allow for better exploration of the metadata in egeria

UI notes to add @bogdan-sava @davidradl @grahamwallis ?

What were you both trying to do with the UI?

**Comment by davidradl** [comment]
@planetf1  Hi Nigel I am prototyping a subject area UI web component. To allow authoring of subject area content. This will involve exploration, currently I am investigating creating a properties pane.

**Comment by grahamwallis** [comment]
Just for info: I'm in the process of extending the UI to include a Type Explorer interface - this will enable a user to view the types known by an OMAG Server.

**Comment by enrush01** [comment]
Thanks all. This project looks very promising. 

I'll give k8s a try and let you know how it goes.

**Comment by planetf1** [comment]
See also #1215

**Comment by planetf1** [comment]
@davidradl do you plan any additional docs?

**Comment by davidradl** [comment]
@planetf1 yes to describe the new ui config and operation

**Comment by planetf1** [comment]
Ok will let you document :-)
I'll provide any review comments
