### ISSUE TITLE
Support flexible choice of open metadata cohort members in VDC chart

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#941]
The vdc chart currently support a cohort with
 * Egeria local repo ( in mem [default]. local graph) - but always deployed
 * Apache atlas - always deployed
 * IGC - can already be disabled

We should allow any combination - so need to be able to disable local repo, or apache atlas

**Comment by planetf1** [comment]
Making a more general change.

Egeria is mandatory
Kafka is also mandatory, but with a choice of internal or external

All other components (ui, omrsmonitor, gaian, ranger, postgresql, atlas etc) are optional. They will default to enabled, but can be turned off. 

This allows for more flexible use - for example someone could just deploy egeria itself, or egeria itself, or everything apart from ranger and atlas etc.

The deployments & jobs have had conditionals added to support this. This extends to all config options in the map too.

At this time I have not added support for EXTERNAL ranger, atlas components -- but that could be a later improvement :-)

Limited testing. Default configuration OOTB & IBM cloud

**Comment by planetf1** [comment]
Also changed
egerialocalrepomode
to
egeria.localrepomode

And added configuration capability for server, user, cohort names

**Comment by cmgrote** [comment]
> Default configuration OOTB & IBM cloud

Does this mean that running the default configuration requires a (paid) IKS setup?  I'd suggest that in line with all our other open source focus that we ensure that the default configuration does not require any paid or external accounts to run (ie. that it is entirely self-contained and locally-executable unless absolutely unavoidable due to commercial software constraints like IGC)...

**Comment by planetf1** [comment]
Not at all. It's just a reference to what I tested after making the change.
Absolutely 200% agree with the principle.

There is absolutely no requirement for any proprietary components including IBM cloud 

(More automated tests would be desirable as it's very easy to have issues with templating)
