### ISSUE TITLE
Configuration 1.0 to 2.0 migration instructions

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#949]
I think the migration instructions for moving from V1.0 to V2.0 should include the need for the "versionId": "V2.0" entry in the configuration.

It's also not clear whether "additionalProperties" is the only change to be made or whether "recognizedAdditionalProperties" also need changing.

**Comment by mandy-chessell** [comment]
Could you explain more?

**Comment by mandy-chessell** [comment]
recognizedAdditionalProperties is a list of property names - it has not changed.
I thought the verdionId was added automatically?

**Comment by mandy-chessell** [comment]
Ah - I see what I did - I added the error message (and test for the version number) after I tested the migration.  I'll look at fixing the message so that we can add the version number automatically.

**Comment by grahamwallis** [comment]
That would be great - or just document that if someone is doing a manual upgrade then they will need to manually add the versionId property.

**Comment by mandy-chessell** [comment]
I think this is done ?
