### ISSUE TITLE
Move Ranger & Gaian Specific code to separate repo

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#958]
Currently we have gaian & ranger specific code in the main egeria codebase

This has a few impacts
 - Gaian is challenging as there are no maven artifacts - so we have to go externally to download artifacts
 - ranger clients end up pulling a variety of hadoop and other dependencies which increases the dependencies for egeria itself

Needs some design work....

cc: @mandy-chessell @danielaotelea

**Comment by planetf1** [comment]
@danielaotelea I can take a look if you like - or if you'd prefer let me know.
First step is to request a new repository from odpi.

**Comment by danielaotelea** [comment]
Hi, Nigel! Sounds a good idea to move the Ranger related components  into a new repository (gaian ranger plugin and gaian impersonation).
Besides the issues that you mentioned,there are some security issues that are triggered by the ranger code (also I encountered some maven issues when I have tried to use something from ranger common).

**Comment by planetf1** [comment]
This is a dup with the current intent of #458 - ie to move hadoop oriented content to a new repo. Closing.
