### ISSUE TITLE
Migrate IGC connector to its own repository

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#960]
Objectives:

- Demonstrate building an external proxy connector (outside core Egeria codebase)
- Demonstrate how to dynamically include / bind such a connector into a running environment (eg. Helm-orchestrated containers)

**Comment by cmgrote** [comment]
It looks likely that we'll need to change the packaging mechanism for Spring Boot in the server chassis to use `ZIP` instead of the default `JAR` -- to be able to load external dependencies (like connectors) at runtime (using `loader.path`) rather than forcing everything to be pre-bundled into a single jar file.

Unless we want to have some interim deployment step that re-bundles the jar file by injecting external connector jars into its `BOOT-INF/lib`?

See:

- https://stackoverflow.com/questions/30745132/external-library-folder-for-spring-boot
- http://weyprecht.de/2018/05/02/how-to-really-package-and-deploy-a-spring-boot-application/
- https://docs.spring.io/spring-boot/docs/current/maven-plugin/usage.html

**Comment by planetf1** [comment]
This will presumably also affect the ability to do java -jar XXX.jar which is how the current docker containers launch the spring boot app, so will need to change there? However reading the docs it does seem as if the change is needed almost for this very reason - to get additional flexibility in the loading process...

**Comment by cmgrote** [comment]
You can still run the executable jar file using `java -jar XXX.jar`, this approach just allows you to additionally provide a `-Dloader.path=...` to the same command.  So you can run:

```
java -Dloader.path=... -jar XXX.jar
```

Without using this approach, the `-Dloader.path=...` is ignored, as is any `-cp`, `CLASSPATH` environment variable, etc.

So this way we could even still use the same 'vanilla' Egeria Docker image for even these custom connector proxies -- just by init'ing the container first to mount in the additional connector jar(s) and changing the entrypoint / CMD args to include the mounted path with `-Dloader.path=...`
