### ISSUE TITLE
FVT test generation code is taking 60% of overall build time

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#967]
Currently the open types test generator is taking up 60% (7 minutes) of the overall build time - taking a typical macos build to around 11:30. This can impact developer productivity and has been observed by a number of people.

It would be worthwhile looking into:
 * Why it is taking so long. Can the code be improved?
 * Adding an option to skip - at least for developers building their own code locally

The first would be my preferred option if we do find a significant issue as more validation is good. We should understand what the generator is doing, and whether it is effective - though the second is ok since the open types are updated less often. I would suggest keeping the tests in the commit build regardless.

On skipping, note that I experienced an issue with profiles & submodules when working on https://github.com/odpi/egeria/issues/771 and instead adopted the '-Ddocker' flag to *enable* docker builds (here we want a flag to disable IMO if we go down that route)

cc: @davidradl @bogdan-sava

**Comment by innerTide** [comment]
I'm have the same issue as well. Is there any update? Thanks!
![image](https://user-images.githubusercontent.com/17440495/57459383-6e5e7380-7273-11e9-9ec9-a839702803c7.png)

**Comment by planetf1** [comment]
I see a PR is proposed to support skipping (which I agree with). Let's leave this issue open to improve the performance when this step is undertaken
see https://github.com/odpi/egeria/pull/1008/files

**Comment by planetf1** [comment]
@innerTide as an aside i notice your build is taking 32 mins - that's about 3 times my duration/official build. Maybe you have other issues/limitations too. 
Also note that when I tested previously a windows build was about 2.5x slower than either MacOS or linux (though a build in a vm on windows or using WSL was close to linux)

**Comment by innerTide** [comment]
@planetf1 This is my first build so it took some time to download dependencies from Maven central. But I will try WSL :) Thanks!

**Comment by planetf1** [comment]
Verify builds are now down to 14 minutes . Builds with FVT (master after merging, daily) remain at 40 mins or so on official LF systems

**Comment by planetf1** [comment]
Suggest leaving this open to look at actual test code and confirm it needs to take this long when run

**Comment by bogdan-sava** [comment]
In order to have dev builds I do recommend you to run:
`mvn -pl '!org.odpi.egeria:open-metadata-assemblies' clean install -DskipTests -DskipFVT `

It excludes assemblies also. On my computers finishes under 2 min.

**Comment by bogdan-sava** [comment]
-pl param is a built in functionality in maven

**Comment by bogdan-sava** [comment]
If you don't need the UI for the work in progress... 
`mvn -pl '!org.odpi.egeria:open-metadata-assemblies' clean install -DskipTests -DskipFVT -DskipUI`

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  51.179 s
[INFO] Finished at: 2019-05-31T10:23:11+03:00
[INFO] ------------------------------------------------------------------------

**Comment by planetf1** [comment]
A further observation.

When I build within the open-metadata-test tree I get 
```
14:58:12,814 [INFO]
14:58:12,815 [INFO] --- exec-maven-plugin:1.6.0:java (default) @ open-types-test ---                                                                                     14:58:12,971 [INFO]
```

yet if I build as part of the whole project:
```
15:05:34,783 [INFO] --- exec-maven-plugin:1.6.0:java (default) @ open-types-test ---
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
15:19:06,896 [INFO]
15:19:06,896 [INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ open-types-test ---
```

I opened up #1256 for the logger, though it's slightly unclear why there is a difference, since both runs used the same maven invocation.

More relevant behaviour for THIS issue, is that the operation is quick. Very quick.

Overall the difference is
Full
```
15:19:37,519 [INFO] Open Metadata Open Types Test Resources ............ SUCCESS [  0.195 s]
15:19:37,519 [INFO] Open Types Test generator .......................... SUCCESS [  0.493 s]                                                                             15:19:37,519 [INFO] Open Types Test execution .......................... SUCCESS [14:03 min]
```
Just fvt
```
14:58:59,888 [INFO] Open Metadata Open Types Test Resources ............ SUCCESS [  0.399 s]
14:58:59,889 [INFO] Open Types Test generator .......................... SUCCESS [  7.183 s]
14:58:59,890 [INFO] Open Types Test execution .......................... SUCCESS [ 49.335 s]
```

**Comment by planetf1** [comment]
In the debugger, the test run takes around a minute -- so the former behaviour.

OmrsBeanGenerator.generateTopReferenceFile takes 93% of the CPU. In fact the replaceAll() call in writeTopReferenceAttributesToFile takes 50%, with a further 20% in token replacement.

This may be possible to optimize but doesn't explain the 5-15 minutes taken in a full build.

**Comment by davidradl** [comment]
@planetf1 I am wondering whether the heap and stack jvm settings might be worth checking and whether the full build needs to fight for memory in some way that the the fvt case does not.  Or maybe that the full case bring in a dependancy that effects the runtime performance adversely..

**Comment by planetf1** [comment]
I added some debugging (problematic due to the way maven integrates slf4j), and refactored the pom to use maven-antrun instead of exec, as this allows for extra configuration checks.

I also changed the generator to return 1 if generation fails due to bad context (current working directory) and fail the build -- since this was the reason builds are sometimes so quick.... this was partly masked by the fact the maven clean implementation had a typo, so 'clean' was not working.

Having done this, there remains a difference between a full build (10 mins vs 90 mins). The greater time is probably due to logging - and whilst slf offers control, within the maven context it's awkward to adjust. It may be prudent to add a conditional around the logging using a new system variable.

Will now check the logs with timings

**Comment by planetf1** [comment]
I'm returning to this as the large amount of code and/or time are causing knock-on effects in build time,  sonar scans, security checks, random memory failures in the build

**Comment by planetf1** [comment]
Some key times in the generation
```
     [java] 14:50:26.192 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - Generating Enum files
     [java] 14:50:26.722 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - Generating Classification files
     [java] 14:50:27.351 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - Generating Classification bean factory
     [java] 14:50:27.354 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - Generating OMRS Relationship to Lines
     [java] 14:50:27.369 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - Generating Entity related files
     [java] 14:50:29.876 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - Generating Relationship files
     [java] 14:50:31.679 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - Generating Reference files
     [java] 15:03:16.791 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - Generating OMRS Beans Accessor file                                  [java] 15:03:17.388 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - Generating OMRS Beans Accessor file
     [java] 15:03:18.534 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - Ending test code generation
```

**Comment by planetf1** [comment]
It is the reference files that are taking a long time

Each line of debug for the reference files shows:
```
    [java] 14:51:15.896 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - Generating top reference file open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/entities/DataProfileAnnotation/DataProfileAnnotationReferences.java
```

There are 180 files

But interestingly they are created many times ie
```
➜  egeria git:(sadvt3) ✗ cat ~/log3 | awk '{print $11}' | sort | uniq -c | head                                                                          git:(sadvt3|✚1
    564 open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/entities/APIOperation/APIOperationReferences.java
    564 open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/entities/APISchemaType/APISchemaTypeReferences.java
    564 open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/entities/ActorProfile/ActorProfileReferences.java
    564 open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/entities/Annotation/AnnotationReferences.java
    564 open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/entities/AnnotationReview/AnnotationReviewReferences.java
    564 open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/entities/Application/ApplicationReferences.java
    564 open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/entities/ArrayDocumentType/ArrayDocumentTypeReferences.java
    564 open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/entities/ArraySchemaType/ArraySchemaTypeReferences.java
    564 open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/entities/Asset/AssetReferences.java
    564 open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/entities/AssetOwner/AssetOwnerReferences.java
```

**Comment by planetf1** [comment]
From logging and inspection we can see that the process of building the references is expensive:

ie
```
        List<org.odpi.openmetadata.fvt.opentypes.model.OmrsBeanReference> omrsBeanReferences = omrsBeanModel.getOmrsBeanReferences();
``` << that is 282

With an inner iterator around
```
            for (String entityName : entitiesWithRelationships) {
``` << that is 180

**Comment by planetf1** [comment]
Or looking at logs, per file we have these files being created each 564 times (need to check if double logging)

The first file touched is `open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/entities/CertificationType/CertificationTypeReferences.java`and this is then created another 564 times in the following 15 minutes or so (not all at once).

Examining the logic

**Comment by planetf1** [comment]
Added optimization when creating entity reference file -- store entityName in a set, only create top references if not already done. - the algorithm was resulting in these files being created many times.

Alternative fixes may be possibly by modifying the searches, but I opted for light touch.

This brings execution time down from 15 minutes to around 43s

There are further optimizations on string processing possible, but this is the 'big win'

**Comment by planetf1** [comment]
Leaving logging in build for now - may remove it later, but need to see how this works in a proper PR/build environment

**Comment by planetf1** [comment]
Now getting times like
```
17:18:53,368 [INFO] Open Metadata Open Types Test Resources ............ SUCCESS [  0.189 s]
17:18:53,369 [INFO] Open Types Test generator .......................... SUCCESS [  0.831 s]
17:18:53,370 [INFO] Open Types Test execution .......................... SUCCESS [ 43.766 s]
```
And this is with the generator running 

however on build machine:
```
18:34:18 [INFO] Open Metadata Deployment ........................... SUCCESS [  0.303 s]
18:34:18 [INFO] Open Metadata Test Resources 1.1-SNAPSHOT .......... SUCCESS [  0.499 s]
18:34:18 [INFO] ------------------------------------------------------------------------
```

So something is odd that is aborting the build (though it returns success)

**Comment by planetf1** [comment]
To close out this issue -- the above output is correct for a PR build, since fvt tests are no longer run there. This was initially done to avoid running any long tests (or those with external dependencies).

The merge master build now runs the code generation in around 15s, another 2s for reading the archive. These then take 44s to compile. The total runtime for building the classes & executing is around 72s
