### ISSUE TITLE
Need to include graph key prefix on qualifiedAttribute names

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#969]

**Comment by grahamwallis** [comment]
Already fixed

**Comment by popa-raluca** [comment]
Hi @grahamwallis,
Not sure if this issue is fixed, but the corresponding PR https://github.com/odpi/egeria/pull/972/ breaks findEntityByProperty method. 
I'm not able to retrieve an entity based on the qualifiedName(i.e testQualifiedName)
Also, I'm not able to query the local graph for an entity based on the guid(using the rest call  {{url}}//servers/{{server-id-omas}}/open-metadata/repository-services/users/{{user-id}}/instances/entity/{{guid}})

**Comment by grahamwallis** [comment]
Hi @popa-raluca - With regard to the first problem (find of entity by qualifiedName property) are you trying to retrieve an entity that was created (added to the repository) before the PR was applied? If so, I would not expect that to work, as the PR changed the key associated with the property. If that's the case, can you please try on a clean repository (or on a newly created entity)?
I don't understand the second problem you mentioned because the core attributes were not changed by the PR - so properties like the GUID property should not be affected.
Please could you retest at least the first part? 
I will test as well and let you know the results.

**Comment by grahamwallis** [comment]
Here are the results of a quick create and find:

I created a DataSet entity with quakifiedName 'coco-dataset-111':

Create request body:
{
   "class":"EntityCreateRequest",
   "entityTypeGUID":"1449911c-4f44-4c22-abc0-7540154feefb",
   "initialProperties":
   {
      "class":"InstanceProperties",
      "instanceProperties":
      {
         "qualifiedName": 
         {
            "class":"PrimitivePropertyValue",
            "instancePropertyCategory":"PRIMITIVE",
            "primitiveDefCategory":"OM_PRIMITIVE_TYPE_STRING",
            "primitiveValue":"coco-dataset-111"
         }
      },
     "propertyNames":["qualifiedName"],
     "propertyCount":1
   }
}

Create response body:
{
    "class": "EntityDetailResponse",
    "relatedHTTPCode": 200,
    "entity": {
        "class": "EntityDetail",
        "type": {
            "class": "InstanceType",
            "typeDefCategory": "ENTITY_DEF",
            "typeDefGUID": "1449911c-4f44-4c22-abc0-7540154feefb",
            "typeDefName": "DataSet",
            "typeDefVersion": 1,
            "typeDefDescription": "Collection of related data.",
            "typeDefSuperTypes": [
                {
                    "guid": "896d14c2-7522-4f6c-8519-757711943fe6",
                    "name": "Asset"
                },
                {
                    "guid": "a32316b8-dc8c-48c5-b12b-71c1b2a080bf",
                    "name": "Referenceable"
                }
            ],
            "validInstanceProperties": [
                "qualifiedName",
                "additionalProperties",
                "name",
                "description",
                "owner",
                "ownerType",
                "zoneMembership",
                "latestChange"
            ]
        },
        "instanceProvenanceType": "LOCAL_COHORT",
        "metadataCollectionId": "e256ac56-c3ae-4b4f-980e-3628500cc6e7",
        "metadataCollectionName": "cocoMDS1",
        "createdBy": "graham",
        "createTime": "2019-08-23T17:52:03.954+0000",
        "version": 1,
        "guid": "714decf0-b475-4f2d-a04f-4bd1c83498be",
        "properties": {
            "class": "InstanceProperties",
            "instanceProperties": {
                "qualifiedName": {
                    "class": "PrimitivePropertyValue",
                    "instancePropertyCategory": "PRIMITIVE",
                    "primitiveDefCategory": "OM_PRIMITIVE_TYPE_STRING",
                    "primitiveValue": "coco-dataset-111"
                }
            },
            "propertyNames": [
                "qualifiedName"
            ],
            "propertyCount": 1
        },
        "status": "ACTIVE"
    }
}

I then performed a findEntitiesByProperty specifying the qualifiedName:

Find request body:
{
	"class":"EntityPropertyFindRequest",
	"offset":0,
	"pageSize":10,
	"typeGUID": "1449911c-4f44-4c22-abc0-7540154feefb",
	"matchProperties":{
    	"class":"InstanceProperties",
    	"instanceProperties":{
	    	"qualifiedName":{
    			"class":"PrimitivePropertyValue",
    			"instancePropertyCategory":"PRIMITIVE",
	    		"typeGUID":"b34a64b9-554a-42b1-8f8a-7d5c2339f9c4",
    			"typeName":"string",
    			"primitiveDefCategory":"OM_PRIMITIVE_TYPE_STRING",
	    		"primitiveValue":"coco-dataset-111"
	    	}
    	},
    	"propertyCount":2,
    	"propertyNames":["qualifiedName"]
	},
	"matchCriteria":"ALL"
}

Find result:
{
    "class": "EntityListResponse",
    "relatedHTTPCode": 200,
    "offset": 0,
    "pageSize": 10,
    "entities": [
        {
            "class": "EntityDetail",
            "type": {
                "class": "InstanceType",
                "typeDefCategory": "ENTITY_DEF",
                "typeDefGUID": "1449911c-4f44-4c22-abc0-7540154feefb",
                "typeDefName": "DataSet",
                "typeDefVersion": 1,
                "typeDefDescription": "Collection of related data.",
                "typeDefSuperTypes": [
                    {
                        "guid": "896d14c2-7522-4f6c-8519-757711943fe6",
                        "name": "Asset"
                    },
                    {
                        "guid": "a32316b8-dc8c-48c5-b12b-71c1b2a080bf",
                        "name": "Referenceable"
                    }
                ],
                "validInstanceProperties": [
                    "qualifiedName",
                    "additionalProperties",
                    "name",
                    "description",
                    "owner",
                    "ownerType",
                    "zoneMembership",
                    "latestChange"
                ]
            },
            "instanceProvenanceType": "LOCAL_COHORT",
            "metadataCollectionId": "e256ac56-c3ae-4b4f-980e-3628500cc6e7",
            "metadataCollectionName": "cocoMDS1",
            "createdBy": "graham",
            "createTime": "2019-08-23T17:52:03.954+0000",
            "version": 1,
            "guid": "714decf0-b475-4f2d-a04f-4bd1c83498be",
            "properties": {
                "class": "InstanceProperties",
                "instanceProperties": {
                    "qualifiedName": {
                        "class": "PrimitivePropertyValue",
                        "instancePropertyCategory": "PRIMITIVE",
                        "primitiveDefCategory": "OM_PRIMITIVE_TYPE_STRING",
                        "primitiveValue": "coco-dataset-111"
                    }
                },
                "propertyNames": [
                    "qualifiedName"
                ],
                "propertyCount": 1
            },
            "status": "ACTIVE"
        }
    ]
}

So for me, the find seems to working correctly.

I then did a getEntityByGUID specifying the GUID of the dataset above, i.e:

localhost:8080/servers/cocoMDS1/open-metadata/repository-services/users/graham/instances/entity/714decf0-b475-4f2d-a04f-4bd1c83498be

and the result returns the entity:

{
    "class": "EntityDetailResponse",
    "relatedHTTPCode": 200,
    "entity": {
        "class": "EntityDetail",
        "type": {
            "class": "InstanceType",
            "typeDefCategory": "ENTITY_DEF",
            "typeDefGUID": "1449911c-4f44-4c22-abc0-7540154feefb",
            "typeDefName": "DataSet",
            "typeDefVersion": 1,
            "typeDefDescription": "Collection of related data.",
            "typeDefSuperTypes": [
                {
                    "guid": "896d14c2-7522-4f6c-8519-757711943fe6",
                    "name": "Asset"
                },
                {
                    "guid": "a32316b8-dc8c-48c5-b12b-71c1b2a080bf",
                    "name": "Referenceable"
                }
            ],
            "validInstanceProperties": [
                "qualifiedName",
                "additionalProperties",
                "name",
                "description",
                "owner",
                "ownerType",
                "zoneMembership",
                "latestChange"
            ]
        },
        "instanceProvenanceType": "LOCAL_COHORT",
        "metadataCollectionId": "e256ac56-c3ae-4b4f-980e-3628500cc6e7",
        "metadataCollectionName": "cocoMDS1",
        "createdBy": "graham",
        "createTime": "2019-08-23T17:52:03.954+0000",
        "version": 1,
        "guid": "714decf0-b475-4f2d-a04f-4bd1c83498be",
        "properties": {
            "class": "InstanceProperties",
            "instanceProperties": {
                "qualifiedName": {
                    "class": "PrimitivePropertyValue",
                    "instancePropertyCategory": "PRIMITIVE",
                    "primitiveDefCategory": "OM_PRIMITIVE_TYPE_STRING",
                    "primitiveValue": "coco-dataset-111"
                }
            },
            "propertyNames": [
                "qualifiedName"
            ],
            "propertyCount": 1
        },
        "status": "ACTIVE"
    }
}

So for me the get of the entity by GUID is working too.

What results are you getting?

**Comment by popa-raluca** [comment]
Hi Graham,

I had this problem while trying to run DataEngine OMAS on master. findEntityByProperty fails every time, for qualifiedNames that used to work. I noticed that after the revert of the PR everything worked as expected. 
I attached a file with some debug info for a simple qualified name. 
Noticed that {{url}}//servers/{{server-id-omas}}/open-metadata/repository-services/users/{{user-id}}/instances/entity/{{guid}}) is working for a newly created entity, just findentityByProperty doesn't seem to work.
Haven't had time to investigate further, I was mainly focused on the preparations for the lineage demo.

[debug_local_graph.log](https://github.com/odpi/egeria/files/3540056/debug_local_graph.log)

**Comment by grahamwallis** [comment]
HI @raluca - I would expect the behaviour I think you are seeing. If you have an entity created prior to the PR, it will not be retrieved once the PR is applied - because the PR changes the keys. You need to apply the PR to a clean repository.

**Comment by popa-raluca** [comment]
Hi @grahamwallis - The problem I'm facing is not being able to retrieve an entity that was created on a clean repo with the PR applied. I am able to query it with {url}}//servers/{{server-id-omas}}/open-metadata/repository-services/users/{{user-id}}/instances/entity/{{guid}}), but I'm not able to retrieve it based on qualifiedName with findEntityByProperty

**Comment by grahamwallis** [comment]
Fixed by #972
