### ISSUE TITLE
Delete generated FVT file from GitHub master

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#970]
The file open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/entities/InformationView/InformationViewReferences.java should be deleted, as it is a generated file.

Following a maven build it shows up as modified.

**Comment by planetf1** [comment]
I just noticed same :-)

**Comment by planetf1** [comment]
This has become somewhat of an annoyance. Perhaps we should add a step to the build to verify there are no git changes after build has completed...

I made the change earlier, but it clashed with another PR where it had been accidentally checked in the file. Unsurprising as it's easy to miss when making a large code change. I nearly did the same multiple times.

I've now removed the file & build looks good so will propose in a PR.
cc: @davidradl @danielaotelea
