### ISSUE TITLE
Support certificates and https access in helm charts/docker images for egeria

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#975]

**Comment by cmgrote** [comment]
If it's specific to the k8s environment, it would be good to look at something like Istio to handle this for us (rather than needing to manually configure, manage and maintain the various certificates and trusts -- particularly handling rotation...)

**Comment by planetf1** [comment]
Agreed, istio could be a good fit for managing security both internally between the services, as well as on the periphery. it can be policy driven and consistent. IMO it makes for a cleaner more task centric approach than having to inject the certs into each image and then manage them. Logging, monitoring, throttling and api management can also be similarly integrated. indeed those tools themselves could benefit from egeria integration, and area we will discuss further

**Comment by planetf1** [comment]
We now have this underway for core egeria. There are other issues specifically around istio, so closing this for now
