### ISSUE TITLE
Update IGC proxy configuration in Helm chart

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#976]
Post-migration of the IGC connector, update the proxy configuration of the Helm chart for IGC to dynamically load the connector jar as part of the initialisation of an otherwise vanilla Egeria (core) container image.

**Comment by cmgrote** [comment]
Need to still decide best mechanism (ie. from where?) to pull the IGC connector in order to load it up into the proxy image as part of its initialisation...

**Comment by planetf1** [comment]
If builds are still a tbd we may need to put the connector somewhere temporarily.
We now have at least 2 teams consuming the helm charts .. and need to keep them working through any refactoring
T

**Comment by cmgrote** [comment]
As a temporary measure I could build a jar and include on the other GitHub repo as a release — and setup the chart to simply download this release to initialise the IGC proxy...  Longer-term I’m looking for a more consistent “snapshot” download mechanism that uses more of a runtime / install-time package manager (ala RPM, NPM, etc) rather than a build-time manager like Maven...  not sure that such a thing exists in the Java world (?)

**Comment by planetf1** [comment]
the temp measure sounds good to ensure we can keep working esp as I am actively working on the charts over the coming days/week

Longer term it's not a simple decision.. as every platform/environment has it's own package manager. What does a package mean for egeria? 

If you were to ensure you created a maven artifact (or more) that contained everything needed, this can be retrieved when launching the image, plus there is support to create (maven) and push the artifacts through the LF build process, and ultimately to maven central, including release snapshots. So it could work. but if there's something better - need to think about that for longer :-)

**Comment by cmgrote** [comment]
> Longer term it's not a simple decision.. as every platform/environment has it's own package manager. What does a package mean for egeria?

I'd say a package is anything that someone might want to use as-is, without needing to run a build or even have a build environment.  So basically one or more jar files: purely able to use the JRE -- no JDK or such needed.  (Maybe our assemblies?)  I think in that sense it'd be pretty environment and platform independent (that's the whole portability promise of Java's bytecode, after all... 😉), just a simple mechanism to reliably retrieve jar files...

I'm happy to setup a Maven build process to automatically put snapshots into Maven Central, but it seems as if Maven is really geared more towards building: you need to run a goal, not just a simple command to download a package / assembly (?)  But quite possible I'm simply not familiar enough with Maven 🤷‍♂
