### ISSUE TITLE
ContactThrough relationship and ContactDetails entity overlap?

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#991]
The `ContactThrough` relationship -- between an ActorProfile entity and a ContactDetails entity -- currently has the following properties (on the relationship):

- contactMethodType
- contactMethodValue

... and yet `ContactDetails` itself has precisely those same properties:

- contactMethodType
- contactMethodValue

Are they intended to represent different information?  I would think we'd only need the properties on the `ContactDetails` entity itself, not on the relationship as well (?)  (It's confusing to have the same properties on both, with exactly the same names and descriptions, if they're intended to represent different information...)

**Comment by mandy-chessell** [comment]
Hello Chris - good spot.  The UML model shows these parameters on the contact details
![area-1-collaboration-0110-Actors](https://user-images.githubusercontent.com/12354195/57081433-af2e1980-6cc2-11e9-8ebd-2f45c9427f14.png)

I'll remove it from the ContactThrough relationship
